### ISSUE TITLE
Support accesskeys in plugin menu registration (RM #2510)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1230]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2510***
*Originally created by **Dave Page** at 2017-06-23 09:05:19 UTC.*

When plugins register menu options, they should be able to specify an accesskey option to allow quick access to that function. Each plugin should define an access key so all menus are easily navigated.

**Comment by khushboovashi** [comment]
@dpage, is this still valid?

**Comment by dpage** [comment]
Nope - we don't support plugins any more.
