### ISSUE TITLE
Wizard for filters (RM #2734)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1404]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2734***
*Originally created by **FelipeR Ricardo** at 2017-09-26 16:53:09 UTC.*

Hi.
When the filter window opens. It should show the initial query in a readOnly field (then the user can know how to complete the query):

SELECT * FROM table WHERE 

On double click in * all fields appears with X for quit them:

SELECT field1[X], field2[X], field3[X] FROM table WHERE

Also in the Filter or SQL window the field names and SQL sentences appears in an upper bar with select lists (or clicking Ctrl + Space) for add the fields and construct the query doing click in each list or buttons according to the possible sentences where is the cursor.

Example:
ListFields: [field1][field2][field3]...
ListCounts: [COUNT(*)][AVG()][MAX()]...
ListFunctions: [date()][upper()][lower()]...
ListCompare: [=][>=][<=][IN]...
ListConectors: [AND][OR][BETWEEN]... 
ListGroups: [GROUP BY][ORDER BY][LIMIT][HAVING]

Thanks you.

**Comment by pravesh-sharma** [comment]
This will be taken care of with  #3354.
