### ISSUE TITLE
Tools/Query Tool/Data Ouput or View/Edit Data (RM #2736)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1405]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2736***
*Originally created by **Bojan Marceta** at 2017-09-27 08:02:55 UTC.*

I would greatly appreciate fast navigation through result table, e.g. CTRL End, CTRL Home in Data Output tab.

**Comment by pravesh-sharma** [comment]
Duplicates #5099
