### ISSUE TITLE
Open in new browser tab detached by default new config option (RM #3254)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1767]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3254***
*Originally created by **César Arriaga Egues** at 2018-04-07 16:49:26 UTC.*

In v1.21 is possible to Open query tool in new browser tabs.

This tabs can be afterwards be detached in separate windows.

New feature: add a new config. option in order to query tool in new browser tabs be opened in detached/separate windows.

**Comment by yogeshmahajan-1903** [comment]
This feature is already implemented.
