### ISSUE TITLE
The slider of the query result view is useless in case of long tables (RM #3269)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1780]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3269***
*Originally created by **bassi bass** at 2018-04-11 09:17:35 UTC.*

If I use the Slider on the right side of the result vies they would jump up if new lines are loaded. Then I have grab the slider again to navigate in the result set. This is very irritating if I navigate within long results. Going to the end of a long result with this way is nearly impossible.

**Comment by adityatoshniwal** [comment]
We've decided to replace infinite scrolling with pagination for better UX.

**Comment by pravesh-sharma** [comment]
Feature implemented and is working fine. Tested on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-03/).

Env:
OS - macOS 14.7 (Sonoma)
Mode - Desktop

**Comment by anilsahoo20** [comment]
If we run queries like this, it always shows `page no.` 2 of 1.
<img width="1380" alt="Screenshot 2024-11-05 at 3 13 44 PM" src="https://github.com/user-attachments/assets/b0cd94aa-8ce3-48c7-af28-749d512eeae1">

If we make empty the first control of `Showing rows`, and clicks the apply button, it shows the message tab and if we click on cancel edit button it closes the control and shows `Showing rows: to 201`
<img width="701" alt="Screenshot 2024-11-05 at 3 34 49 PM" src="https://github.com/user-attachments/assets/256f9dae-237a-4fad-b01a-175bf28c147a">
<img width="621" alt="Screenshot 2024-11-05 at 3 35 09 PM" src="https://github.com/user-attachments/assets/106e9af6-b9d8-4787-ac60-03e77cff59c1">
<img width="588" alt="Screenshot 2024-11-05 at 3 35 16 PM" src="https://github.com/user-attachments/assets/62fec41e-79eb-4776-8165-640c91a96872">

If we enter some value and did not click on apply and clicked cancel edit button, it still shows Showing rows: 100 of 201, but the data output tab shows data from 1 to 201.
<img width="1382" alt="Screenshot 2024-11-05 at 3 43 35 PM" src="https://github.com/user-attachments/assets/5a5816a5-3f87-4041-9009-5db5673bfe71">

If we give the valid starting row no. and invalid end row no, still the error is on start row no. Note: this comes only when end row no is greater than 0. if 0 is given then it shows error
<img width="1383" alt="Screenshot 2024-11-05 at 3 48 49 PM" src="https://github.com/user-attachments/assets/8d586585-2974-457b-a13d-f022c82ed0d0">
<img width="836" alt="Screenshot 2024-11-05 at 3 51 36 PM" src="https://github.com/user-attachments/assets/85036fbc-d3f7-4b87-87a7-44cece8793bd">

**Comment by pravesh-sharma** [comment]
I found one more issue

If I mark a row for deletion or add a new row and then change the page and then return, the marking or new row is gone and the bottom status bar still shows `Changes staged`. Attached recording:

https://github.com/user-attachments/assets/17b6db06-21e0-4e5c-99d0-ff93c6822f11

**Comment by anilsahoo20** [comment]
1. Previous page and first page are still active when page and rows are 0.
![Image](https://github.com/user-attachments/assets/12b59ec0-11fc-4f16-92bb-e0967b7dcdae)

2. First clicked on edit of the page icon and then selected all rows by clicking the top left corner box and the css looks distorted.
Already all the rows are selected, but still it is showing `Select All Rows`
![Image](https://github.com/user-attachments/assets/3cb1a368-f7c0-4853-b56d-a0aa82672cc4)

3. I have shared a video on slack.

4. If I give from row 5 and apply, then after some forward and next pages, if we see the `Showing rows` are 1 to 197 for page 1 and 198 to 201 for page 2. You can see the same in the end of the video.

**Comment by adityatoshniwal** [comment]
> 4. If I give from row 5 and apply, then after some forward and next pages, if we see the `Showing rows` are 1 to 197 for page 1 and 198 to 201 for page 2. You can see the same in the end of the video.

For this, you need to check the docs once. I've added details on how it is calculated. New page nos are calc based on new page size.

**Comment by anilsahoo20** [comment]
Tested and verified with latest source code.
Environment: macOs 13.5.1
