### ISSUE TITLE
Prompt for DB Connection credentials (login/pwd) on server connection (RM #3311)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1813]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3311***
*Originally created by **Peter Butkovic** at 2018-04-25 10:00:27 UTC.*

As we need to run pgadmin4 in the central place and we have huge count of the DBs, following is required:
* create a DB connection keeping login and password blank
* dialog that would prompt for login/pwd once user tries to connect to server (` pgadmin4/web/pgadmin/browser/server_groups/servers/templates/servers/password.html` could be reused, just with an option to type login as well)

**Comment by yogeshmahajan-1903** [comment]
This can be achieved using shared server or copy server feature.
