### ISSUE TITLE
[WEB] External database user settings storage  (RM #3336)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1832]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3336***
*Originally created by **Peter Palka** at 2018-05-07 02:32:11 UTC.*

h1. Current user settings storage
Right now all user settings are stored in SQLite database file in /var/lib/pgadmin/pgadmin4.db.

h1. Proposal
Ability to store user settings on external database like PostgreSQL

h1. Motivation
During large pgAdmin4 deployment (for example on AWS using Auto Scaling group with load balancer) we can't rely on single SQLite file database as it:
# Is not prepared to be failure-proof (no HA support),
# May be a bottleneck (not designed to handle many connections concurrently reading/writing data to it).
This implies it can be single point of failure.

To prevent it we can separate user data storage from pgAdmin4 web service by using external database for user storage on another machine. To achieve it the external database connector will be needed.

**Comment by anovis** [comment]
any thoughts on this. this would be very helpful, when deploying in a serverless environment (ie gcp cloudrun)

**Comment by FaharAbbasRizvi** [comment]
This feature is thoroughly tested

Here are the permutations:

External database tested on Windows 64:
------------------
1. pgadmin4 6.14>pgadmin4 6.15 with latest snapshot build
2. pgadmin4 6.9>pgadmin4 6.15 with latest snapshot build
3. pgadmin4 4.30 >pgadmin4 5.7 > pgadmin4 6.9> pgadmin4 6.15 with latest snapshot build
4. Fresh installation mode on Windows 64

Linux 64
------------
1. The fresh mode of pgadmin4 6.15(Latest snapshot build)rpm on the Desktop and the server mode
2. Upgrade scenario on the Desktop and the server mode

MAC OS X
---------------
Fresh and Update scenario

pgadmin4 with CONFIG_DATABASE_URI:
-------------------------------------------
Performed testing with CONFIG_DATABASE_URI  on Linux and Windows with fresh and upgrade scenarios.

**Comment by adityatoshniwal** [comment]
@FaharAbbasRizvi Can you please test this scenario as well:
1. Install v5.3 or or below in server mode.
2. Add some users in user management.
3. Upgrade to the latest.

Changes were done to add a new unique column in the users table, need to test if working fine.

**Comment by FaharAbbasRizvi** [comment]
The Above message scenario is working fine and Python Package Tested with 5.3 and upgrade to the latest snapshot build successfully:

Tested on Ubuntu 18.04
