### ISSUE TITLE
Please provide Reset to Default option in Preferences (RM #3427)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1900]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3427***
*Originally created by **Aditya Toshniwal** at 2018-06-15 05:39:52 UTC.*

Currently, there is no option to reset the preferences to default values.
It will be helpful if there a "Reset to Default" button.

**Comment by RohitBhati8269** [comment]
@pravesh-sharma,  Facing one issue while resetting all preferences.
Please check the attached image:-
<img width="522" alt="Screenshot 2024-09-11 at 11 21 14 AM" src="https://github.com/user-attachments/assets/654cfc60-1293-4467-a3f2-48096814abd4">

**Comment by RohitBhati8269** [comment]
Issue fixed and verified on latest snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-09-16/).
Package: arm64
Environment: macOS
