### ISSUE TITLE
We need to add support for Safari browser with feature tests on MAC OS X (RM #3483)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1946]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3483***
*Originally created by **Fahar Abbas** at 2018-07-09 13:04:14 UTC.*

We need to add support for safari browser with feature tests as per Dave approval:

python runtests.py --pkg feature_tests
/Users/fahar12/myenv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
NOTE: Configuring authentication for SERVER mode.

pgAdmin 4 - Application Initialisation
======================================

Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.12.6 x86_64)

**Comment by yogeshmahajan-1903** [comment]
pgadmin now uses nwjs/electron container. Also feature tests can be run on FF and chrome.
