### ISSUE TITLE
Automatic server & DB disconnect after idle (RM #3504)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1962]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3504***
*Originally created by **Gareth Vaughan** at 2018-07-17 04:42:07 UTC.*

I'd like to see auto-disconnect functionality for servers and databases so as to improve security and avoid confusing databases

*Current behaviour*
1) Start pgAdmin4 and connect to a server
2) Close browser without disconnecting server, 
3) restart machine 
4) restart pgAdmin4, 
5) observe that server is still connected.

*My concerns*
i)  Vulnerable data could be exposed by failing to disconnect
ii) Similar databases (i.e.prod vs test vs dev) on the same or separate servers could be easily confused

*Request*
Configurable options for each server and database to allow 
a) auto-disconnect enable/disable
b) auto-disconnect after ...5min idle
c) auto-disconnect after ....5min of browser shutdown...

**Comment by khushboovashi** [comment]
This is already implemented.  SERVER_HEARTBEAT_TIMEOUT can be configured for the auto-disconnect servers after closing the browser tabs.
