### ISSUE TITLE
Make all synchronous ajax to async (RM #3515)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1972]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3515***
*Originally created by **Harshal Dhumal** at 2018-07-24 10:29:13 UTC.*

Currently there are lot of places in pgAdmin4 where synchronous (async=false) ajax are used.
This is causing UI to freeze until ajax is completed. Form end user point of view it's bad UI experience.

Code causing problem:

@$.ajax({
        async: false,
        url: full_url,
      })@

async: false should not be used.

e.g.
 NodeAjaxOptionsControl, NodeAjaxOptionsCell, Select2Cell, Select2Control, etc...

Attached screenshot of browser warning.

**Comment by adityatoshniwal** [comment]
jquery was replaced with axios which doesn't support sync calls. So eventually, this is done.
