### ISSUE TITLE
PostGIS Mapviewer - Add zoom to all geometry features tool (RM #3603)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2046]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3603***
*Originally created by **Jeremy Palmer** at 2018-08-30 19:30:53 UTC.*

To help with user navigation it would be great to add a map tool that zooms to all features, or the original map dataset extent. There are Leaflet plugins that provide this type of function: https://github.com/torfsen/leaflet.zoomhome

**Comment by yogeshmahajan-1903** [comment]
For developer - Update leaflet library.https://github.com/pgadmin-org/pgadmin4/pull/7403

**Comment by anilsahoo20** [comment]
Tested and verified on candidate build: https://developer.pgadmin.org/builds/2024-08-20-2/
Package: arm64
Environment: macOs Ventura 13.5.1
