### ISSUE TITLE
Cannot create Databases or Logins on remote PostgreSQL servers [SSPI] (RM #3701)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2119]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3701***
*Originally created by **Christophe Nicolas** at 2018-10-12 13:12:25 UTC.*

Hi
Using Pg Admin 4.3.2, version included in Postgresql 10.5 x64 for Windows.

When I connect to local PostgreSQL server, I can create new databases from pgAdmin 4: right click from Databases entry, then Create

But with same pgAdmin, if I connect to remote PostgreSQL server (same version also on Windows), I can't found create entry when right click on Databases, only Refresh is available.

Same issue for Login/Group Roles and Tablespaces menus.

Also same after upgrade pgAdmin to 4.3.4

Thank for your help

**Comment by yogeshmahajan-1903** [comment]
This is woking fine.
