### ISSUE TITLE
Tree should auto scroll with auto expand (RM #3781)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2174]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3781***
*Originally created by **Aditya Toshniwal** at 2018-11-29 04:56:14 UTC.*

Currently, the tree auto expands. But if the selected item after expand is not in the window, we need to scroll to find the selected item.
The tree should scroll to the selected item.

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-11-08/
