### ISSUE TITLE
PostGIS Mapviewer - allow visualisation in case PostGIS is installed not on public schema (RM #3944)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2317]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3944***
*Originally created by **Sergey Burkov** at 2019-01-29 12:31:52 UTC.*

As of now, Mapviewer functionality is only enabled for geometry/geography types which imply that PostGIS extension is installed in public schema.
In case PostGIS extension is installed in another schema and types are as follows {schema_name}.geometry / {schema_name}.geography there is no possibility to use map visualization.

**Comment by robe2** [comment]
I think this one you can close out.  I don't see this as being an issue and i suspect maybe the user just didn't set the schema postgis is installed in to their search_path or didn't reconnect after.
