### ISSUE TITLE
CSS bundling should be modular (RM #4005)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2371]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4005***
*Originally created by **Aditya Toshniwal** at 2019-02-18 07:30:29 UTC.*

Currently, all the SCSS/CSS files are tracked recursively and bundled together in pgadmin.css. There is an exclude and include files option in webpack.shim.js but still everything bundles in pgadmin.css.
webpack should be configured in a way that based on entry points, selective files be picked and bundled for that entry point.

**Comment by adityatoshniwal** [comment]
We don't use CSS anymore. MUI is used.
