### ISSUE TITLE
Disable auto-fill on all dialogues (RM #4048)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2410]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4048***
*Originally created by **Dave Page** at 2019-03-05 10:40:09 UTC.*

**Comment by anilsahoo20** [comment]
@pravesh-sharma 
In chrome the these below given dialog's password and Name field is autofilled with password and username.

![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/bdb6789d-ec25-4d72-912f-4fbf19ea3d0f)
![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/7a1dea89-9e43-4348-8a40-40449bbd9d43)
![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/4158c06d-8a54-4bd4-a912-ff4165335234)

**Comment by anilsahoo20** [comment]
Tested and verified on candidate build:https://developer.pgadmin.org/builds/2024-04-29-1/
Environment: Debian 12

**Comment by ianbamforth** [comment]
This may have caused https://github.com/pgadmin-org/pgadmin4/issues/7627?
