### ISSUE TITLE
field type in table tree view (RM #4049)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2411]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4049***
*Originally created by **Stijn Sanders** at 2019-03-05 11:05:33 UTC.*

I would like to see the field type of each field on the tree-nodes under 'columns' under a table, suffixed parenthesized.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-09-11/
