### ISSUE TITLE
View/Edit offer a history of previous filter values (RM #4093)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2454]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4093***
*Originally created by **Dave Caughey** at 2019-03-18 12:23:11 UTC.*

When debugging code or dealing with a customer issue I may have to run several queries, over-and-over again.

E.g., I go to "View/Edit Data..." | "Filter by" and enter "customer_id = 7 and date >= 15147378170000 and date < 1564726347563 and purchase_type = 0"

But I also have to do other tasks on the same table, but occasionally I have to come back to the same "Filter by" clause.

It would be great if pgAdmin offered a means (e.g., a "History" table like the Query Tool has?) that would let me pick a previously-entered "Filter by" rather than having to type the entire clause in, over and over again.

**Comment by adityatoshniwal** [comment]
will be implemented in #2453
