### ISSUE TITLE
Enhancement to query history feature. (RM #4113)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2472]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4113***
*Originally created by **Murtuza Zabuawala** at 2019-03-26 10:47:58 UTC.*

1) What if my query has some sensitive information?
- I should allow to clear that individual query from history.

2) Encrypt the query before saving it to SQLite
- Same reason user can have sensitive information in the query if we save it plain text then other user can open SQLite directly and see the content.

**Comment by pravesh-sharma** [comment]
This is done. Queries are no longer saved in plain text.
