### ISSUE TITLE
Datatype on Columns (Serial Type) (RM #4146)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2499]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4146***
*Originally created by **Martín Comesaña** at 2019-04-05 14:35:10 UTC.*

On Table Properties View, Tab "Columns" the Data Types "Serial" or "BigSerial" are shown like "int" and "bigint" respectively.

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by adityatoshniwal** [comment]
We're reopening this. There is still no reliable way to identify but we can add some logic to assume the serial/bigserial data type for added convenience. We can say a column is serial/bigserial:
1. If the column is of type int
2. If the column has default value as sequence nextval
3. If the sequence has name pattern of `<table>_<column>_seq`

**Comment by adityatoshniwal** [comment]
> We're reopening this. There is still no reliable way to identify but we can add some logic to assume the serial/bigserial data type for added convenience. We can say a column is serial/bigserial:
> 
> 1. If the column is of type int
> 2. If the column has default value as sequence nextval
> 3. If the sequence has name pattern of `<table>_<column>_seq`

Unfortunately, this didn't work out reliably. We may end up showing `serial` incorrectly. We'll use this only for ERD.
