### ISSUE TITLE
Add Expression Index creation (RM #4260)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2595]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4260***
*Originally created by **Michel Feinstein** at 2019-05-15 06:00:59 UTC.*

Currently (version 4.6) there's no way to create an Expression Index such as:

<pre><code class="sql">
CREATE UNIQUE INDEX idx_lower_unique 
   ON your_table (lower(the_column));
</code></pre>

It would be great if this feature could be added.

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build and tested in all supported platforms.
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-08-07/
