### ISSUE TITLE
Create trigger: Event update multiply columns selection (RM #4268)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2602]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4268***
*Originally created by **Ivan Sobolev** at 2019-05-16 05:53:37 UTC.*

there is drop-down list with tables columns, and it is possible to select column at that list.
But, ater selection the list disapeared, and if you need to add more columns, than you have to retrieve drop-down list again and again.

Please, add possibility to add mutiply columns with out additional clicking

**Comment by adityatoshniwal** [comment]
This is fixed.
