### ISSUE TITLE
See (and set) encrypted password (RM #4323)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2646]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4323***
*Originally created by **Michael Shapiro** at 2019-06-05 05:51:33 UTC.*

PgAdmin3 has the ability to see the encrypted password for a login role. Can this be added to PgAdmin4?

When you select the SQL for a login role, PgAdmin3 shows.

  CREATE ROLE xxx_user LOGIN
    ENCRYPTED PASSWORD 'md5f349771b7d83b170e8377bd7d09'
    SUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION;

Can this functionality be added to PgAdmin4? 
Also, can the dialog for a login role support setting an encrypted password?

**Comment by khushboovashi** [comment]
An encrypted password for the login role is implemented in the SQL tab.

**Comment by khushboovashi** [comment]
https://www.postgresql.org/docs/15/sql-createrole.html

**Comment by akshay-joshi** [comment]
As per the documentation from PostgreSQL v10 and above "The password is always stored encrypted in the system catalogs. The ENCRYPTED keyword has no effect, but is accepted for backwards compatibility."

Hence closing this feature.
