### ISSUE TITLE
Geometry Viewer: Multipolygon fails  (RM #4383)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2690]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4383***
*Originally created by **Giacomo Leonardi** at 2019-06-21 13:44:00 UTC.*

I execute this simple query: 

SELECT ST_GeomFromText('MULTIPOLYGON(((-10 30,10 10,50 50,30 50,-10 30)),((-10 20,50 50,50 30,-10 20)))')

the rendered geometry is wrong, seems like this: 

https://github.com/Leaflet/Leaflet/issues/6173

Two polygons of the same MultiPolygon object, even if overlapping, must be shown without holes

**Comment by adityatoshniwal** [comment]
Closing as per comment - https://github.com/Leaflet/Leaflet/issues/6173#issuecomment-790615562
