### ISSUE TITLE
Add Close Panel button to the tab+ (RM #4538)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2821]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4538***
*Originally created by **Avin Kavish** at 2019-07-31 02:07:35 UTC.*

On most if not all tabbed browsing applications, the button to close the tab is on the tab itself on the right side next to the title. It is both convenient and intuitive because it is logical to expect to close the tab somewhere on the tab itself and not to the right where it is not related to any panel in particular.  Also since most applications are designed this way, it is muscle memory to reach for the tab to close it. With the way things are currently, it is only possible to close the currently focused tab which is very rare considering that the currently opened tab is the one that a user is working on and is needed.

**Comment by adityatoshniwal** [comment]
Implemented with #6479

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on today's snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-11-02/yum/

OS - Rocky Linux 9.2 (Blue Onyx)
Mode - Desktop
