### ISSUE TITLE
Add Close other panels option to context menu (RM #4539)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2822]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4539***
*Originally created by **Avin Kavish** at 2019-07-31 02:12:59 UTC.*

On most if not all tabbed browsing applications, it's common for a user to not need the other tabs and only need the tab they are currently working on. Apps like Google Chrome, VS Code and most IDEs have a "close others" option which allows users to close all but the tab/panel they are currently working on. I currently have to resort to manually closing all panels which takes a considerable amount of time.

**Comment by adityatoshniwal** [comment]
Will be implemented with #5394.
