### ISSUE TITLE
Alternate the background color of rows to enhance readability (RM #4598)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2874]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4598***
*Originally created by **Luther Goh** at 2019-08-09 14:44:38 UTC.*

Table rows' background colour can be alternated in order to make them more readable.

It may be achieved by just adding css as suggested in this message:

https://www.postgresql.org/message-id/CAAj2gHwUrYz7t2nzwZgZXeTj5fbEtkACQdHWR2KEsd2_T4gU7g%40mail.gmail.com

**Comment by pravesh-sharma** [comment]
The feature is implemented and is working as expected, verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-03/).

Env:
OS - macOS 14.7 (Sonoma)
Mode - Desktop and server
Browser - Chrome

**Comment by pravesh-sharma** [comment]
Hi @jon777,

We tested on dark and high-contrast themes and found no issues. Texts are readable.
