### ISSUE TITLE
Add a third option to Plain editor mode as Auto (RM #4722)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2979]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4722***
*Originally created by **Aditya Toshniwal** at 2019-09-10 12:08:47 UTC.*

Add a third option to Plain editor mode as Auto which will switch the editor to plain mode automatically after a certain file or editor size.

Currently, it has Yes/No options.

**Comment by adityatoshniwal** [comment]
This feature is not needed anymore with CodeMirror 6.
