### ISSUE TITLE
the question about panel locate in firefox (RM #4729)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2986]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4729***
*Originally created by **Dada Zhang** at 2019-09-11 06:56:22 UTC.*

In the pgadmin tool in firefox, the memory position of the panel scroll bar disappears as you switch between panels

**Comment by yogeshmahajan-1903** [comment]
Will be fixed with #6479.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-10-26/
Environment: macOsx Ventura 13.4.1
Package: pip wheel
