### ISSUE TITLE
copy and paste on table with column with type 'SERIAL' (RM #4782)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3027]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4782***
*Originally created by **André Burkhardt** at 2019-09-26 08:39:47 UTC.*

In pgAdmin III, when copy and
paste a row with columns with Type SERIAL, a messagebox with question pops up:

"This table contains columns from type 'SERIAL'. Use values from within
clipboard for this column? YES/NO"

If select NO, the column with the SERIAL is cleared after
insert. When saving the changes, the field is filled with next value
from sequence.

In pgAdmin 4 the dedection of such SERIAL-columns is not implemented, so
that you have to clear the column with SERIAL manually. Otherwise there are
double values in that column.

Is it on roadmap to implement this useful feature in pgAdmin 4?

**Comment by pravesh-sharma** [comment]
This feature is related to #5922 and is implemented with it.
