### ISSUE TITLE
Preview or import selected file in Query Tool (RM #4841)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3065]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4841***
*Originally created by **Bastiaan Wakkie** at 2019-10-16 12:09:40 UTC.*

Sometimes I just need a part out of an already saved sql file.

Now I have to open a new query tool, open the file where I need a part from, copy the part I want, close the new query tool, move to my working query tool, paste the section.

Instead of opening the file and loosing my work in the current query tool I would love to have a little preview at the bottom of the "select file" window so I can +without opening it in the Query Tool+ select the part I am looking for and close the "select file" so I can continue with my work.

Alternatively (or as an other extra feature) an option to import a different file into my working query tool? So add an extra option to the open file 'import file (like śuggested in #4829)

**Comment by adityatoshniwal** [comment]
pgAdmin uses native OS dialog now, so this cannot be implemented.
