### ISSUE TITLE
add an option in "preferences" that allows pgadmin4 to ping the server every x number of seconds to keep the tcp connection alive (RM #4986)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3163]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4986***
*Originally created by **Nico Kne** at 2019-11-29 14:09:59 UTC.*

add an option in "preferences" that allows pgadmin4 to ping the server every x number of seconds to keep the tcp connection alive. although from the server configuration this can be done by setting the number of seconds to "tcp_keepalives_idle", sometimes this is not possible because the provider does not allow changing the postgresql.conf file. another advantage of having this configuration is the convenience of keeping the connection alive without changing any configuration from the server.

**Comment by adityatoshniwal** [comment]
pgAdmin allows to set keep alive settings on the client side as well. Feel free to re-open this if doesn't serve the purpose.

<img width="700" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/95a7c4d5-f34d-4553-9b22-535ffff6fd7c">
