### ISSUE TITLE
Copy and paste of row containing bytea column saves bytea as 'binary_data' in ascii (RM #5037)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3199]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5037***
*Originally created by **Jason K.** at 2019-12-24 04:23:53 UTC.*

I apologize if this bug has been reported before but I have not found anything matching variations on the description.

I am using pgadmin 4.16 and have encountered a situation where copying and pasting a row containing a bytea column saves the bytea column as 'binary_data' in ascii bytes instead of the actual byte contents of the bytea column. I first observed this in pgadmin 4.8. The data continues to be displayed as '[binary data]' so it is not obvious until usage of the column data that the copy of the data is corrupt. Unless someone looks at the contents of the column bytes, they might simply think that their data was randomly damaged.

Either it should not be possible to use cut and paste on rows containing bytea columns or the cut/paste should actually copy and paste the bytes.

**Comment by RohitBhati8269** [comment]
Fixed and verified on [snapshot-build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-07-10/) 
OS:- macOS Arm64
Installer: Mac (dmg package)
