### ISSUE TITLE
[Usability] Confusing UI when adding FK (RM #5162)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3298]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5162***
*Originally created by **Pekka Järvinen** at 2020-02-07 03:16:32 UTC.*

When using *Create table* and going to *Constraints* tab and *Foreign Key* sub tab the UI is confusing.

User clicks plus sign and then *Name* and *Columns* appears. There is no clear indication that pen icon must be clicked also.

Maybe open it by default or make empty columns list clickable.

I think *Columns* tab should be opened by default instead of *General* as you are first thinking what you are referencing and usually after that the *Action* and lastly the name in *General* tab and more rarely *Definition*.

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
