### ISSUE TITLE
Stats not shown for materialized views (RM #5190)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3316]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5190***
*Originally created by **Bilge B** at 2020-02-14 22:17:22 UTC.*

The stats tab shows "No statistics are available for the selected object.", even though pg has support for stats for materialized views. It is useful to see the storage requirements for such views.

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-19/
