### ISSUE TITLE
Query tool filter options do not support null ordering (RM #5191)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3317]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5191***
*Originally created by **Bilge B** at 2020-02-14 22:19:46 UTC.*

Using the sort/filter options dialogue of the query tool, it is possible to select column order. However, the nulls first/last option is missing.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-11-29/
Package: arm64
Environment: macOs Sonoma 14.7.1
