### ISSUE TITLE
Names are automatically generated for constraints but not indexes (RM #5192)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3318]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5192***
*Originally created by **Bilge B** at 2020-02-14 22:27:04 UTC.*

Constraints (i.e. primary keys) receive default names automatically if not specified. However, indexes do not, which is inconsistent and inconvenient.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-28/
