### ISSUE TITLE
Searching of saved SQL by name (RM #5296)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3385]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5296***
*Originally created by **androxkentaki .** at 2020-03-27 09:14:33 UTC.*

Finding proper SQL file to open in query tool: when I am preparing some maintenance solution or report in our ERP system I am preparing SQL script and save it into a file. When I want to come back to it. So I open query tool > open file > select file. But main problem Is that I can’t find it by part of a name. Is there any trick of plugin to filter files by part of name? (in pgA3 it was explorer window so we can use search function).

maybe by typing string in name column it can limit displaying result to only this that have a mach

**Comment by nikhil-mohite** [comment]
This is done with react porting.
