### ISSUE TITLE
Add a new profile to allow the user browse only to the databases choosen by the administrator (RM #5301)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3389]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5301***
*Originally created by **Manuel Pavy** at 2020-03-30 07:53:58 UTC.*

The goal of this new profile is to avoid the user create its own "Server".
So he will can connec only to the server define by an administrator.

In consequence, a new panel should be create to the administrator profile to create servers for others.

**Comment by akshay-joshi** [comment]
Will be implemented as a part of #7310
