### ISSUE TITLE
IAM token based authentication  (RM #5428)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3491]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5428***
*Originally created by **Naga Raj** at 2020-04-21 21:49:26 UTC.*

It would be nice if the database connection starts with a token-based token-based authentication for AWS RDS or Azure DB. 

This kind of feature is available in SQL workbench J for MySQL and it not working for PostgreSQL.

**Comment by mconigliaro** [comment]
More info on IAM authentication on RDS/AWS: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.PostgreSQL.html

An easy way to implement this would be to have a password command option (i.e. command to run to generate the token).

**Comment by aelgn** [comment]
@mconigliaro I've made PR https://github.com/pgadmin-org/pgadmin4/pull/5430 to solve this exact case

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
