### ISSUE TITLE
Provide GUC configuration for connections (RM #5545)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3591]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5545***
*Originally created by **Andrey Marinchuk** at 2020-05-20 07:30:05 UTC.*

Sometimes we need to configure the GUC variables for every connection to the database. PostgreSQL provides an ability to configure GUC variable per-user for each database, but it's not always possible. Some postgresql clients provide feature to configure GUC variables in connection settings, other clients provide the connection initialization sql, but there is no configuration in pgAdmin.

Actual usecase is: several users behind the NAT connect to PostgreSQL using one role. All their connection are visible to PostgreSQL server as connection from single IP-address. To provide the user information for session monitoring, we configure the application_name GUC parameter, but pgAdmin does not provide a way to make this configuration authomatically.
Another usecase is setting xmloption GUC variable to document for users who need to work with xml documents periodically.

I suggest to add the setting "Initialization SQL" (textarea) in Advanced tab of the server properties window. Any query specified in this setting should be executed with autocommit mode on in each connection to this server right after initial setup made by pgAdmin. The exclusion could be made for the maintenance connections (which is used to get the information about database objects, database status etc).

**Comment by akshay-joshi** [comment]
"Initialization SQL" (textarea) in Advanced tab of the server properties window" will be implemented as a part of #4503
