### ISSUE TITLE
Query editor issue on mobile browsers (RM #5613)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3647]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5613***
*Originally created by **Steven Beverly** at 2020-06-18 15:55:51 UTC.*

Devices: iPad, iPhone, Pixel
Browsers: Chrome, Safari

There seems to be an issue with the query editor on mobile browsers. On iOS devices the page tries to scroll when pressing the space key in the Query Editor area, however the Scratch Pad area works just fine. On Android devices the virtual keyboard closes immediately when clicking into the Query Editor and Scratch Pad areas. I have been unable to find a workaround create queries using a mobile device.

**Comment by adityatoshniwal** [comment]
Tested on iPad, pgAdmin works fine. 
For other devices, not tested.
