### ISSUE TITLE
pgagent job grouping (RM #5702)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3717]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5702***
*Originally created by **Frank Brendel** at 2020-07-27 15:52:34 UTC.*

Grouping jobs like pgAdmin Server Groups would be helpful to organize/categorize jobs.

**Comment by anilsahoo20** [comment]
This requires major changes in pgAgent which we are not accepting currently.
