### ISSUE TITLE
Filtered Rows... dialog to suggest column names (RM #5752)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3751]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5752***
*Originally created by **Þórhallur Hálfdánarson** at 2020-08-19 13:18:39 UTC.*

I find myself frequently using the Filtered Rows... option from the table/view context menu

However, occasionally I'm looking at tables where I can't recall exact column names.

Having the column list right next to the input field would be of great use - and auto-complete suggestions would also be convenient.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-11-29/
Package: arm64
Environment: macOs Sonoma 14.7.1
