### ISSUE TITLE
No input field for file name in "Save file" dialog (RM #5755)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3754]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5755***
*Originally created by **Max Yankov** at 2020-08-20 08:56:34 UTC.*

Steps to reproduce:

Open "Save file dialog"

Expected result:

The dialog mimics the "Save file" dialog found in different operating systems and programs, including the separate input field for the name of the file, OR the dialog looks different from said standard dialog archetype.

Actual result:

Diaog looks extremely similar to the usual "save file" dialog found in different operating systems and programs, but lacks the file name input field. Instead, the user is expected to input the file name in the path.

Discussion:

I understand that this probably is just a design decision, but in my opinion, it's a decision bordering on a bug. Exactly because the dialog is so similar to what the user is accustomed to, he has the expectation that he would enter the file name in a separate field, not in the field that contains the file path. It creates an awful user experience — I just spent 20 minutes reloading pgadmin, trying to open it in a different browser and reinstalling it, until I understood what the interface expected me to do.

**Comment by adityatoshniwal** [comment]
This is done after dialog porting to React.
