### ISSUE TITLE
Automatic pgAdmin4 server restart after shutting down to taker effect for changes done from 'configure window' (RM #5819)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3810]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5819***
*Originally created by **Yogesh Mahajan** at 2020-09-09 07:35:48 UTC.*

Currently whenever I change setting from 'Configure window, a pop is presented saying 'Server restart is required. Do you want to shut down server now?'.

After clicking 'Yes' button, pgAdmin server gets shut-down but does not start on its own. 
User has to start from desktop menu/ application.

When ever a plugin is  installed in browser, & it requires for restart, after allowing restart browser is launched back.
Can we have pgadmin behaving on same line?

**Comment by adityatoshniwal** [comment]
This is no more valid as we have moved to NW.js now.
