### ISSUE TITLE
Option to only show active connections? (RM #5844)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3831]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5844***
*Originally created by **Chris Wiegand** at 2020-09-17 20:20:55 UTC.*

Can we get an option to only show active connections in the Dashboard display of a server in the "Server Activity" -> Sessions window? I often have several idle connections from pgbouncer or other pooling drivers and really only care about the ones that are active.

**Comment by cdwiegand** [comment]
Submitted a pull request on this: https://github.com/pgadmin-org/pgadmin4/pull/6107

**Comment by adityatoshniwal** [comment]
Hi @cdwiegand,

Wouldn't it be easier to just add a switch `Active Only?` on the UI for sessions tab and filter there itself. That way,
1. No extra tab will be required.
2. No extra query required to be run.
3. No performance hampering.

Thanks.

**Comment by cdwiegand** [comment]
I'm not an expert in JSX, React, or Python, so I can eventually do that I'm sure; but I'm also concerned that adding a checkbox would have to be -within- the panel, which would take up valuable UI space, and there's at most 4 tabs currently, so I think this is more efficient than adding a row for a checkbox within the existing panel.

**Comment by cdwiegand** [comment]
Ok - I'll work on doing that, it will take me some time to debug, thanks for the input!

**Comment by FaharAbbasRizvi** [comment]
This feature has been implemented. 
If select Active Session only Cancel the active query and click on the yes button for confirmation,  I am getting Request failed with status code 500 message.
<img width="1005" alt="Screen Shot 2023-05-08 at 4 04 22 PM" src="https://user-images.githubusercontent.com/43006122/236808895-5c0dcaba-8bab-4fba-ab97-01f6410eca55.png">
<img width="1002" alt="Screen Shot 2023-05-08 at 4 04 31 PM" src="https://user-images.githubusercontent.com/43006122/236808922-eae245be-0fbf-47da-8968-96d82a259fd7.png">

**Comment by cdwiegand** [comment]
Hmm I just re-tried and wasn't able to get that @FaharAbbasRizvi  - are you running this in a way that you can see the python log/error in your console or terminal? I see the correct process ID is passed to the back end, so I'm not sure why it would happen that would relate to the front end code change. Also on your first screenshot the only active session is the pgAdmin one itself, which I thought we still blocked users from terminating? For my testing I created an idle in transaction and an active (but long) query to test stopping and terminating, since I can't kill my "main active session".

**Comment by adityatoshniwal** [comment]
Hi @FaharAbbasRizvi,

This is reproducible if you're on dashboard for a non-maintenance DB. This occurs on v7.1 as well. You can create a separate bug for the above issue as it is not related to this ticket.

Thanks.

**Comment by FaharAbbasRizvi** [comment]
I have reported a separate issue for this. This Feature has been implemented.
