### ISSUE TITLE
Support for authentication by proxy (RM #5854)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3841]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5854***
*Originally created by **Jeroen Landheer** at 2020-09-19 10:46:46 UTC.*

Proxy servers can set a header like X-Forwared-User: <Username> to facilitate Single Sign On. The proxy server can authenticate the user via various methods (Kerberos, OIDC, etc.) and basically takes care of the authentication for the app. (The header name is not standardized, so it varies among different proxy implementations, but X-Forwarded-User is fairly common.) 

If would be nice if pgAdmin could support such a header, so the login process can be skipped entirely.

**Comment by adityatoshniwal** [comment]
Multiple authentication ways are implemented in pgAdmin. Closing.
