### ISSUE TITLE
SQL formatter interferes with multi-character operators (RM #5963)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3924]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5963***
*Originally created by **Frank Limpert** at 2020-11-02 12:56:50 UTC.*

In pgAdmin 4.27, docker installation, I observed the following:
I typed: <pre>
SELECT ARRAY[1] <@ ARRAY[1, 2], 'a' !~* 'abc'
</pre>
and the Formatter (Shift+Ctrl+K) produced: <pre>
SELECT ARRAY[1] < @ ARRAY[1,
       2], 'a' !~ * 'abc'
</pre>
which results in completely garbled operators.
Note the inappropriate white spaces between the operator characters.

Please don't tamper with white spaces between operator characters mentioned "here":https://www.postgresql.org/docs/13/sql-createoperator.html#id-1.9.3.72.5

**Comment by pravesh-sharma** [comment]
Fixed with #5083.
