### ISSUE TITLE
Add a cascade toggle to the create extension dialog (RM #5988)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3942]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5988***
*Originally created by **Robert Hewlett** at 2020-11-12 09:10:07 UTC.*

When creating an extension via the UI cascade is not an option.

Adding an a toggle would be nice (see below, I could not find the correct font):

!create_ext.jpg!

**Comment by FaharAbbasRizvi** [comment]
If the user creates any new extension then create extension cascade is displayed in SQL and this need to be fixed.
<img width="945" alt="Screen Shot 2023-08-09 at 2 04 13 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/c3a43636-9ebf-40f2-85e8-cfa80be070ba">
