### ISSUE TITLE
Tables > Properties > Columns tab: Rearrange columns (RM #6009)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3959]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6009***
*Originally created by **Simon Strandgaard** at 2020-11-16 11:27:14 UTC.*

The columns in my table has a somewhat inconsistent ordering and one would like to reorder the columns.

It's seems to be non-trivial changing the position of columns:
https://wiki.postgresql.org/wiki/Alter_column_position
https://stackoverflow.com/questions/285733/how-do-i-alter-the-position-of-a-column-in-a-postgresql-database-table
https://stackoverflow.com/questions/126430/is-it-possible-to-change-the-natural-order-of-columns-in-postgres

Wishful thinking: 
Inside pgAdmin 4, change the ordering, hit `Save`, and this tricky operation takes place in a robust way.

**Comment by akshay-joshi** [comment]
We have done this while creating a new table. Rearranging columns for existing tables is highly complex.
