### ISSUE TITLE
ctrl+mouse click on table name opens automatically data browser (RM #6016)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3965]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6016***
*Originally created by **Paweł Andruszków** at 2020-11-17 13:19:27 UTC.*

It would be very helpful to add a shortcut to auto-open table data browser after ctrl(command) + mouse click on table name

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
