### ISSUE TITLE
show PostgreSQL server log (RM #6037)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3981]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6037***
*Originally created by **Frank Limpert** at 2020-11-24 15:09:50 UTC.*

In pgAdmin3 (see attached screen shot), I can have a look inside the most recent PostgreSQL server log file. This helps me especially to tune SQL commands inside of functions using <code>auto_explain</code> et al. This feature would be especially helpful for developers not having shell access to their PostgreSQL server.

Older PostgreSQL servers might need <code>EXTENSION adminpack</code> for this. Newer PostgreSQL versions have <code>pg_read_file()</code>.

**Comment by ronwildt** [comment]
@akshay-joshi Thank you for identifying my enhancement request as a duplicate #6696 What is the timeframe for implementing this feature and why was it removed from pgadmin4 in the first place, my I ask?  Thanks!

**Comment by akshay-joshi** [comment]
@ronwildt 

We have completely rewritten pgAdmin 4 in React/ Python and other web technologies. pgAdmin III is c++ based standalone application. pgAdmin 4 is a web + desktop application. We will prioritize it.

**Comment by ronwildt** [comment]
@akshay-joshi The info is appreciated.  When might the team be adding this to the backlog and what might be the ETA for delivery of the feature?  (looking to know for planning purposes on our end, fyi.) Thanks! :)

**Comment by akshay-joshi** [comment]
@ronwildt 

Will see the feasibility and if possible will try to add this to the next release 7.7 on 21st September.

**Comment by ronwildt** [comment]
@akshay-joshi That would be totally awesome!  Didn't expect the team might be able to do so that quickly.  Looking forward to it.  Have a great weekend, thx. :)

**Comment by akshay-joshi** [comment]
@ronwildt

We have to check the feasibility, this feature is not straightforward and seems to be very complex. So definitely it won't be there in the next release v7.7

**Comment by ronwildt** [comment]
@akshay-joshi We appreciate the update and I figured it would not be easy if not already in development.  Any idea when the feature may be planned and implemented?

**Comment by akshay-joshi** [comment]
@ronwildt 

We will check the feasibility/analysis first and then we can priorities.

**Comment by ronwildt** [comment]
@akshay-joshi Sounds good, looking forward to learning about ETA on inclusion in pgadmin4!  Have a great Labor Day weekend! :)

**Comment by yogeshmahajan-1903** [comment]
Getting error while loading pg1 logs
<img width="1517" alt="Screenshot 2024-07-04 at 11 57 19 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/c839684c-29ef-40df-b930-64a135aec61e">

**Comment by pravesh-sharma** [comment]
1. Loading / no message is being displayed for disconnected servers

![image](https://github.com/pgadmin-org/pgadmin4/assets/111979571/dbb4fa2a-5814-4f9d-920f-4aceda990117)

<img width="1580" alt="Screenshot 2024-07-08 at 10 54 48 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/334723c7-b238-484d-98c0-a12fdd8d552a">

**Comment by yogeshmahajan-1903** [comment]
Some more issues - 
1.Format of logs shown in text area does not change on changing log format.
<img width="1404" alt="Screenshot 2024-07-09 at 1 14 51 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/bddc78d1-e241-4a1f-bee6-50d121ba954e">
<img width="1406" alt="Screenshot 2024-07-09 at 1 14 56 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/8d19dec4-02af-43d7-b8bb-cb74bd3ccc2f">


2.Download button for logs can be moved on left top corner inline with Log format field.

3.Scroll bar appears while changing log format.

4.Get fixed rows for all 3 sections and add scroll.

**Comment by yogeshmahajan-1903** [comment]
1.Getting error below while selecting not connected server.

<img width="1784" alt="Screenshot 2024-07-11 at 11 33 20 AM" src="https://github.com/user-attachments/assets/bc49d63c-bf67-4317-858b-35527c034ea1">

**Comment by yogeshmahajan-1903** [comment]
All issues are fixed.
