### ISSUE TITLE
Disconnect All Context Menu Option on Server Group Node (RM #6044)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3987]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6044***
*Originally created by **john klann** at 2020-11-24 20:00:27 UTC.*

It would be convenient to be able to disconnect from all servers in a group rather than one by one.

**Comment by akshay-joshi** [comment]
Duplicate #1984
