### ISSUE TITLE
The open file dialog should remember the last sort order  (RM #6066)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4002]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6066***
*Originally created by **Ernst Hansmair** at 2020-12-04 15:59:40 UTC.*

I have to open files from a directory with hundreds of files. Usually I need one of the newer files. So I have to order each time the filelist by modification timestamp.

**Comment by pravesh-sharma** [comment]
We are now using native OS dialog and it seems to remember the last sort order.
