### ISSUE TITLE
edit multiple selected 'cells' in the Data output panel at ones (RM #6123)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4052]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6123***
*Originally created by **Bastiaan Wakkie** at 2021-01-01 13:02:49 UTC.*

To enhance editing productivity in the Data output panel I like to be able to edit all selected cells at ones in stead of cell by cell.

**Comment by yogeshmahajan-1903** [comment]
Closing in favour of  #1866
