### ISSUE TITLE
Remove Backgrid and Backform (RM #6134)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4060]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6134***
*Originally created by **Akshay Joshi** at 2021-01-07 08:17:28 UTC.*

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-15
