### ISSUE TITLE
ERD relationships should be able to bind to the closest side of the table (RM #6166)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4088]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6166***
*Originally created by **Dave Page** at 2021-01-21 13:43:34 UTC.*

At present, relationship lines always leave the parent on the right and enter the child on the left. We should add a configuration option to allow them to automatically move to whichever side of either table is closest to the other table, thus minimising routing and resulting diagram complexity.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build.
