### ISSUE TITLE
[NWjs] Taskbar icon is a red square for query tool, schema diff, etc.. when opened in new window. (Only on Windows) (RM #6258)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4165]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6258***
*Originally created by **Akshay Joshi** at 2021-02-23 06:49:08 UTC.*

Steps to reproduce:
* Launch pgAdmin 4 v5.0
* Set query tool to open in new browser tab from Preferences (Browser -> Tab settings)
* Connect to the database server and open the query tool.

**Comment by akshay-joshi** [comment]
Tested on Snapshot build, working fine.
