### ISSUE TITLE
Child nodes are not selected in comparison result tree in the schema diff when parent node is collapsed (RM #6265)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4171]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6265***
*Originally created by **Amol Vyavahare** at 2021-02-24 12:57:00 UTC.*

Steps to reproduce:
1. Open Schema Diff from the menu tools>schema diff

2. Select source and destination with a difference

3. Start comparison

4. Once the comparison result is populated, do not expand node and select the checkbox of any parent node in the result tree 

5. Observe the child nodes are not selected when the parent checkbox is ticked

6. Observe Generate script button is enabled.

7. An empty script is generated

Expected behavior:
1. User first need to expand the parent, then only child nodes get selected.. it should get selected even if the tree is collapsed
2. Checkbox before unexpanded items is for selecting all the items under that item itself without expanding the node

Refer attached screenshot for the reference

**Comment by nikhil-mohite** [comment]
This issue is resolved with schema diff porting #4059
