### ISSUE TITLE
Managing user-based GUC settings with group membership in pgAdmin (RM #6303)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4207]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6303***
*Originally created by **Mohini Ogale** at 2021-03-10 05:27:49 UTC.*

We are looking for a feature request where if we have set some settings for a ROLE and add the USER to the role, all the settings that were available to the ROLE should go to the USER.

e.g.

There are user1 and role1, when adding user1 as a member of role1, pgAdmin panel of user1 can also provide GUC settings that are already set in role1;
and when adding any new GUC setting to role1, pgAdmin can also "cascade" the setting to all its members (user1 here).

**Comment by anilsahoo20** [comment]
This is outside of pgAdmin 4 scope.
