### ISSUE TITLE
ERD don't show table partitions or limit to a schema (RM #6371)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4261]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6371***
*Originally created by **Jukka Raimovaara** at 2021-04-05 22:33:15 UTC.*

Hi, I have a db with the timescaleDB extension, so I have thousands of partitions in my db. So I'd like to check erd, but it takes forever to load and contains so many tables it's useless. Also limiting the erd generation to a schema er list of tables would be nice.

**Comment by adityatoshniwal** [comment]
Tested on pgAdmin v8.13 - partitions of partitioned tables are not shown in ERD. ERD also has "ERD for schema" option.
Closing.
