### ISSUE TITLE
[Documentation] Include versions of bundled PG utilities in every release notes (RM #6449)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4320]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6449***
*Originally created by **Paco Calvo** at 2021-05-14 10:58:57 UTC.*

Include versions of bundled PG utilities in every release notes.
For instance, for pgAdmin 4 v5.2 it could include something like this:
* Bundled PostgreSQL utilities:
# psql 13.0.2.21041
# pg_dump 13.0.2.21041
# pg_dumpall 13.0.2.21041
# pg_restore 13.0.2.21041

Thanks in advance,
Paco.

**Comment by pravesh-sharma** [comment]
Verified on latest code. Hence closing.
