### ISSUE TITLE
Cannot reconnect after "Connection to the server has been lost" (RM #6493)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4352]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6493***
*Originally created by **David Waterworth** at 2021-05-26 23:51:42 UTC.*

I'm connecting to an AWS postgres instance via a VPN. Every 24 hours the VPN resets so I lose my connection to the postgres instance. Each time this happens pgAdmin4 gets into what appears to be an unrecoverable state.

1) Every action I try reports "Connection to the server has been lost"
2) I cannot save unsaved work (the save file option from a query tool window opens a blank window with only one enabled option (cancel), create is disabled)
3) I cannot reconnect, selecting browser items simply repeats the error or spins.
4) I cannot close the existing query tool window (the save options repeats [2] and the discard option does nothing)

**Comment by yogeshmahajan-1903** [comment]
We are not able to reproduce issues. Can you please share logs?

**Comment by pravesh-sharma** [comment]
No response from author hence closing
