### ISSUE TITLE
Keep procedure/function/etc dialog open on [Save] (RM #6519)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4374]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6519***
*Originally created by **Tamas Vizmathy** at 2021-06-07 20:10:44 UTC.*

Is there, or could there be any way to keep a dialog open, when clicking [Save]?
Editing a procedure - or any other database object - would be so much more efficient (or rather un-inefficient) if pgAdmin 4 would not close the dialog every single time I hit Save to run the code. If the edit did not turn out to be perfect on the first try, re-opening the window, switching to the Code tab and finding the last position in the code is a tedious, and rather inefficient way of working with it. (having the option of keeping the dialog open would help even if restoring the dialog state - like scroll position - would turn out to be complicated. I guess that's the reason it keeps resetting on window docking/resize)

**Comment by yogeshmahajan-1903** [comment]
This functionality can be achieved using query tool more efficiently along with error hi lighting. You can chose option Script > create Script from context option which will open query tool with script.
