### ISSUE TITLE
ERD: Add background fill color for any table (RM #6542)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4392]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6542***
*Originally created by **Andrey Balykov** at 2021-06-18 09:05:25 UTC.*

Adding a background fill color to tables will allow to visualize their division into several groups, and will make it easier to read large database diagrams with many tables.

**Comment by yogeshmahajan-1903** [comment]
Background color reset after selecting text color. Also on dragging a table, 'Add Note' button is disabled until user clicks outside & respect table.

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
