### ISSUE TITLE
Schema diff: Columns with sequences get altered unnecessarily and generate column X of relation Y is not an identity column (RM #6564)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4413]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6564***
*Originally created by **Stan Hu** at 2021-06-25 18:00:02 UTC.*

Two databases have the same primary key:
 
```
ref_database=# \d+ users;

                                                                             Table "public.users"
                    Column                    |            Type             | Collation | Nullable |              Default              | Storage  | Stats target | Description
----------------------------------------------+-----------------------------+-----------+----------+-----------------------------------+----------+--------------+-------------
 id                                           | integer                     |           | not null | nextval('users_id_seq'::regclass) | plain    |              |
```

For some reason, the schema diff inserted this line for every table that followed this pattern:

```
ALTER TABLE public.users
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET MINVALUE 1 SET MAXVALUE 9223372036854775807 SET CACHE 1;
```

This failed when applying:

```
ERROR:  column "id" of relation "users" is not an identity column
```

Commenting out this `ALTER TABLE` call worked around the problem.

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by thiagodamas** [comment]
Issue present in pgadmin4 8.2, same problem here

**Comment by adityatoshniwal** [comment]
> Issue present in pgadmin4 8.2, same problem here

@thiagodamas please share the problem and reproduction steps.

**Comment by thiagodamas** [comment]
Hi
pgadmin. 8.2 (running on docker).
PostgreSQL version: PostgreSQL 15.5 (Debian 15.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

source ddl:
CREATE TABLE relacionamento.preferencias_cliente
(
    id integer NOT NULL DEFAULT nextval('relacionamento.relacionamento_clientes_id_seq'::regclass),
    sistema text COLLATE pg_catalog."default" NOT NULL,
    cod_cliente integer NOT NULL,
    sms boolean NOT NULL DEFAULT true,
    whatsapp boolean NOT NULL DEFAULT true,
    email boolean NOT NULL DEFAULT true,
    CONSTRAINT relacionamento_clientes_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS relacionamento.preferencias_cliente
    OWNER to postgres;



target ddl:
CREATE TABLE relacionamento.preferencias_cliente
(
    id integer NOT NULL DEFAULT nextval('relacionamento.relacionamento_clientes_id_seq'::regclass),
    sistema text COLLATE pg_catalog."default" NOT NULL,
    cod_cliente integer NOT NULL,
    sms boolean NOT NULL DEFAULT true,
    whatsapp boolean NOT NULL DEFAULT true,
    email boolean NOT NULL DEFAULT true,
    CONSTRAINT relacionamento_clientes_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS relacionamento.preferencias_cliente
    OWNER to postgres;


difference:
ALTER TABLE IF EXISTS relacionamento.preferencias_cliente
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET MINVALUE 1 SET MAXVALUE 2147483647 SET CACHE 1;

**Comment by anilsahoo20** [comment]
Hi @thiagodamas 
Can you please provide the DDL of source and target sequence for the above tables?

**Comment by thiagodamas** [comment]
> Hi
> 
> pgadmin. 8.2 (running on docker).
> 
> PostgreSQL version: PostgreSQL 15.5 (Debian 15.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
> 
> 
> 
> source ddl:
> 
> CREATE TABLE relacionamento.preferencias_cliente
> 
> (
> 
>     id integer NOT NULL DEFAULT nextval('relacionamento.relacionamento_clientes_id_seq'::regclass),
> 
>     sistema text COLLATE pg_catalog."default" NOT NULL,
> 
>     cod_cliente integer NOT NULL,
> 
>     sms boolean NOT NULL DEFAULT true,
> 
>     whatsapp boolean NOT NULL DEFAULT true,
> 
>     email boolean NOT NULL DEFAULT true,
> 
>     CONSTRAINT relacionamento_clientes_pkey PRIMARY KEY (id)
> 
> )
> 
> 
> 
> TABLESPACE pg_default;
> 
> 
> 
> ALTER TABLE IF EXISTS relacionamento.preferencias_cliente
> 
>     OWNER to postgres;
> 
> 
> 
> 
> 
> 
> 
> target ddl:
> 
> CREATE TABLE relacionamento.preferencias_cliente
> 
> (
> 
>     id integer NOT NULL DEFAULT nextval('relacionamento.relacionamento_clientes_id_seq'::regclass),
> 
>     sistema text COLLATE pg_catalog."default" NOT NULL,
> 
>     cod_cliente integer NOT NULL,
> 
>     sms boolean NOT NULL DEFAULT true,
> 
>     whatsapp boolean NOT NULL DEFAULT true,
> 
>     email boolean NOT NULL DEFAULT true,
> 
>     CONSTRAINT relacionamento_clientes_pkey PRIMARY KEY (id)
> 
> )
> 
> 
> 
> TABLESPACE pg_default;
> 
> 
> 
> ALTER TABLE IF EXISTS relacionamento.preferencias_cliente
> 
>     OWNER to postgres;
> 
> 
> 
> 
> 
> difference:
> 
> ALTER TABLE IF EXISTS relacionamento.preferencias_cliente
> 
>     ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET MINVALUE 1 SET MAXVALUE 2147483647 SET CACHE 1;

**Comment by anilsahoo20** [comment]
Hi @thiagodamas 
These are the source and target DDL for tables, that you have given earlier.

I am looking for definition of the source and target sequence.
You can get those in Schema Diff easily by following these steps:

1. Select Server for source and target
2. Select DB for source and target
3. Select schema for source and target
4. Click on compare
5. Expand the sequences tree
6. select the sequence 'relacionamento_clientes_id_seq'
7. get the source and target sequence from respective sections of schema diff and share here

**Comment by anilsahoo20** [comment]
Hi @thiagodamas 

Please follow the steps I mentioned earlier to get the source and target sequence's SQL from schema diff.

Is the sequence is coming under identical or not?

Also have look at the screenshot how I got source and target sequence's SQL, Please share the screenshot of yours.

<img width="1728" alt="Screenshot 2024-02-21 at 10 47 53 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/122535205/58e3337b-d564-402a-b7cb-984482422d5b">

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-28/
Environment: macOs ventura 13.5.1
package: arm64
