### ISSUE TITLE
Drag-n-drop columns (RM #6571)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4419]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6571***
*Originally created by **Lars Ellebjerg** at 2021-06-30 09:29:19 UTC.*

Hi,
First of all thanks for a great product!

A feature which I often use in SQL Server Management Studio but miss in pgAdmin is the possibility to drag and drop a complete list of columns into a query. In SSMS I simply leftclick on the columns folder for a table and drag the entire list of columns into the query. This saves quite a bit of time compared to having to generate a SELECT script to copy the list from.

Best regards,
Lars Ellebjerg

**Comment by nikhil-mohite** [comment]
Resolved. Verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-24/
OS: macOS (Sonoma 14.1)
Mode: Desktop
