### ISSUE TITLE
the list of tables is not displayed  (RM #6575)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4423]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6575***
*Originally created by **Danielle Lamarre** at 2021-06-30 15:04:54 UTC.*

When I click on the table, nothing appears

**Comment by FaharAbbasRizvi** [comment]
This is still not fixed and how I tested:
1. create the following database:

CREATE DATABASE a_sql_asscci
    WITH
    OWNER = postgres
    TEMPLATE = template0
    ENCODING = 'SQL_ASCII'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
2. create the following table in a_sql_asscci:
CREATE TABLE public."C:\User\te"
(
    "C:\User\te" "char" NOT NULL,
    PRIMARY KEY ("C:\User\te")
);

ALTER TABLE IF EXISTS public."C:\User\te"
    OWNER to postgres;
3. Table created
4. Click on the newly created table and view data
5.  Error "'rawunicodeescape' cod
<img width="1024" alt="Screen Shot 2023-02-23 at 2 26 36 PM" src="https://user-images.githubusercontent.com/43006122/220867995-25d1c550-8679-4a2e-be8f-fd9429c53e5c.png">
ec can't decode bytes in position 24-25: truncated \UXXXXXXXX escape" is displayed
