### ISSUE TITLE
show table diagram links and fields in pgadmin (RM #6600)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4442]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6600***
*Originally created by **Misha Shaygu** at 2021-07-13 05:49:12 UTC.*

i choose table and in context menu click show diagram links and fields

Table A          Table B
id PK numberic   id PK numberic
b_id FK

diagram show all tables links with table A, useful set depth links(ex. show links for table B too or not)

Thanks!

**Comment by adityatoshniwal** [comment]
This is implemented. One can use "ERD for table" from context.
