### ISSUE TITLE
pgAdmin4 stopped work after upgrade python3.9 to 3.10 in my distro (RM #6639)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4466]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6639***
*Originally created by **Mikhail Gavrilov** at 2021-07-23 11:15:03 UTC.*

<pre>
[mikhail@fedora ~]$ ll /usr/pgadmin4/venv/bin/
total 88
-rw-r--r--. 1 root root  1893 Jul 12 16:26 activate
-rw-r--r--. 1 root root   842 Jul 12 16:26 activate.csh
-rw-r--r--. 1 root root  1982 Jul 12 16:26 activate.fish
-rw-r--r--. 1 root root  8834 Jul 12 16:26 Activate.ps1
-rwxrwxr-x. 1 root root   227 Jul 12 16:26 alembic
-rwxrwxr-x. 1 root root   235 Jul 12 16:26 chardetect
-rwxrwxr-x. 1 root root   228 Jul 12 16:26 email_validator
-rwxrwxr-x. 1 root root   222 Jul 12 16:26 flask
-rwxrwxr-x. 1 root root   227 Jul 12 16:26 mako-render
-rwxrwxr-x. 1 root root   235 Jul 12 16:26 pip
-rwxrwxr-x. 1 root root   235 Jul 12 16:26 pip3
-rwxrwxr-x. 1 root root   235 Jul 12 16:26 pip3.9
-rwxrwxr-x. 1 root root   236 Jul 12 16:26 pybabel
lrwxrwxrwx. 1 root root     7 Jul 12 16:30 python -> python3
lrwxrwxrwx. 1 root root    18 Jul 12 16:30 python3 -> /usr/bin/python3.9
-rwxr-xr-x. 1 root root 15592 Jul 12 16:31 python3.9
-rwxrwxr-x. 1 root root   230 Jul 12 16:26 sqlformat
-rwxrwxr-x. 1 root root   232 Jul 12 16:26 sshtunnel
-rwxrwxr-x. 1 root root   222 Jul 12 16:26 wheel
[mikhail@fedora ~]$ dnf provides /usr/bin/python3.9
Last metadata expiration check: 0:00:14 ago on Fri 23 Jul 2021 02:18:14 PM +05.
python3.9-3.9.6-2.fc35.i686 : Version 3.9 of the Python interpreter
Repo        : rawhide
Matched from:
Filename    : /usr/bin/python3.9

python3.9-3.9.6-2.fc35.x86_64 : Version 3.9 of the Python interpreter
Repo        : rawhide
Matched from:
Filename    : /usr/bin/python3.9

[mikhail@fedora ~]$ rpm -qa | grep python3 | sort
libpeas-loader-python3-1.30.0-4.fc35.x86_64
python3-3.10.0~b4-2.fc35.x86_64
python3-abrt-2.14.6-6.fc35.x86_64
python3-abrt-addon-2.14.6-6.fc35.noarch
python3-argcomplete-1.12.3-2.fc35.noarch
python3-audit-3.0.3-1.fc35.x86_64
python3-augeas-1.1.0-1.fc35.noarch
python3-babel-2.9.1-3.fc35.noarch
python3-beaker-1.10.0-11.fc35.noarch
python3-beautifulsoup4-4.9.3-3.fc35.noarch
python3-blivet-3.4.0-4.fc35.noarch
python3-blockdev-2.25-4.fc35.x86_64
python3-bodhi-5.7.0-2.fc35.noarch
python3-bodhi-client-5.7.0-2.fc35.noarch
python3-brlapi-0.8.2-9.fc35.x86_64
python3-bugzilla-3.0.2-3.fc35.noarch
python3-bytesize-2.6-1.fc35.x86_64
python3-cached_property-1.5.2-3.fc35.noarch
python3-cairo-1.20.0-3.fc35.x86_64
python3-cccolutils-1.5-18.fc35.x86_64
python3-cffi-1.14.6-1.fc35.x86_64
python3-chardet-4.0.0-3.fc35.noarch
python3-click-8.0.1-2.fc35.noarch
python3-construct-2.10.67-2.fc35.noarch
python3-crypto-2.6.1-35.fc35.x86_64
python3-cryptography-3.4.7-4.fc35.x86_64
python3-cups-2.0.1-10.fc35.x86_64
python3-dasbus-1.6-2.fc35.noarch
python3-dateutil-2.8.1-6.fc35.noarch
python3-dbus-1.2.18-1.fc35.x86_64
python3-decorator-5.0.9-2.fc35.noarch
python3-distro-1.5.0-6.fc35.noarch
python3-dnf-4.8.0-1.fc35.noarch
python3-dnf-plugins-core-4.0.22-1.fc35.noarch
python3-dnf-plugins-extras-common-4.0.15-1.fc35.noarch
python3-dnf-plugin-system-upgrade-4.0.15-1.fc35.noarch
python3-docutils-0.16-6.fc35.noarch
python3-enchant-3.2.0-4.fc35.noarch
python3-fedora-1.1.1-3.fc35.noarch
python3-firewall-0.9.3-6.fc35.noarch
python3-future-0.18.2-10.fc35.noarch
python3-gitdb-4.0.5-3.fc35.noarch
python3-GitPython-3.1.14-3.fc35.noarch
python3-gobject-3.40.1-4.fc35.x86_64
python3-gobject-base-3.40.1-4.fc35.x86_64
python3-gpg-1.15.1-4.fc35.x86_64
python3-gssapi-1.6.14-1.fc35.x86_64
python3-hawkey-0.63.1-2.fc35.x86_64
python3-humanize-0.5.1-26.fc35.noarch
python3-idna-2.10-4.fc35.noarch
python3-imagesize-1.2.0-5.fc35.noarch
python3-jinja2-3.0.1-1.fc35.noarch
python3-kickstart-3.34-1.fc35.noarch
python3-kitchen-1.2.6-10.fc35.noarch
python3-koji-1.25.1-1.fc35.noarch
python3-langtable-0.0.54-3.fc35.noarch
python3-libcomps-0.1.17-1.fc35.x86_64
python3-libdnf-0.63.1-2.fc35.x86_64
python3-libmodulemd-2.13.0-1.fc35.x86_64
python3-libreport-2.15.2-5.fc35.x86_64
python3-libs-3.10.0~b4-2.fc35.x86_64
python3-libselinux-3.2-2.fc35.x86_64
python3-libsemanage-3.2-2.fc35.x86_64
python3-libxml2-2.9.12-5.fc35.x86_64
python3-lockfile-0.12.2-3.fc35.noarch
python3-louis-3.18.0-1.fc35.noarch
python3-lxml-4.6.3-3.fc35.x86_64
python3-mako-1.1.4-4.fc35.noarch
python3-markupsafe-2.0.0-1.fc35.x86_64
python3-meh-0.50-3.fc35.noarch
python3-meh-gui-0.50-3.fc35.noarch
python3-munch-2.5.0-5.fc35.noarch
python3-nftables-0.9.9-2.fc35.x86_64
python3-olefile-0.46-14.fc35.noarch
python3-openidc-client-0.6.0-12.20180605gitcd8d91c.fc35.noarch
python3-packaging-21.0-1.fc35.noarch
python3-paste-3.5.0-4.fc35.noarch
python3-pexpect-4.8.0-8.fc35.noarch
python3-pid-2.2.3-11.fc35.noarch
python3-pillow-8.3.1-1.fc35.x86_64
python3-pip-21.1.3-1.fc35.noarch
python3-ply-3.11-12.fc35.noarch
python3-policycoreutils-3.2-3.fc35.noarch
python3-productmd-1.33-2.fc35.noarch
python3-progressbar2-3.52.1-3.fc35.noarch
python3-psutil-5.8.0-8.fc35.x86_64
python3-ptyprocess-0.6.0-13.fc35.noarch
python3-pwquality-1.4.4-4.fc35.x86_64
python3-py3nvml-0.2.6-5.fc35.noarch
python3-pyatspi-2.38.1-2.fc35.noarch
python3-pybeam-0.6-5.fc35.noarch
python3-pycparser-2.20-4.fc35.noarch
python3-pycurl-7.43.0.6-9.fc35.x86_64
python3-pygit2-1.5.0-2.fc35.x86_64
python3-pygments-2.9.0-1.fc35.noarch
python3-pyOpenSSL-20.0.1-3.fc35.noarch
python3-pyparsing-2.4.7-8.fc35.noarch
python3-pyparted-3.11.7-3.fc35.x86_64
python3-pyroute2-0.5.14-2.fc35.noarch
python3-pysocks-1.7.1-10.fc35.noarch
python3-pytz-2021.1-3.fc35.noarch
python3-pyudev-0.22.0-5.fc35.noarch
python3-pyusb-1.0.2-12.fc35.noarch
python3-pyxdg-0.27-2.fc35.noarch
python3-pyyaml-5.4.1-3.fc35.x86_64
python3-requests-2.25.1-3.fc35.noarch
python3-requests-file-1.5.1-3.fc35.noarch
python3-requests-ftp-0.3.1-22.fc35.noarch
python3-requests-gssapi-1.2.3-2.fc35.noarch
python3-rpkg-1.62-6.fc35.noarch
python3-rpm-4.17.0-0.beta1.0.fc35.1.x86_64
python3-rpmautospec-0.2.3-1.fc35.noarch
python3-setools-4.4.0-2.fc35.x86_64
python3-setuptools-57.1.0-2.fc35.noarch
python3-simpleline-1.8-2.fc35.noarch
python3-six-1.16.0-3.fc35.noarch
python3-slip-0.6.4-24.fc35.noarch
python3-slip-dbus-0.6.4-24.fc35.noarch
python3-smmap-3.0.1-5.fc35.noarch
python3-snowballstemmer-1.9.0-9.fc35.noarch
python3-soupsieve-2.2.1-1.fc35.noarch
python3-speechd-0.10.2-4.fc35.x86_64
python3-sphinx-4.0.2-3.fc35.noarch
python3-sphinxcontrib-applehelp-1.0.2-5.fc35.noarch
python3-sphinxcontrib-devhelp-1.0.2-5.fc35.noarch
python3-sphinxcontrib-htmlhelp-2.0.0-1.fc35.noarch
python3-sphinxcontrib-jsmath-1.0.1-12.fc35.noarch
python3-sphinxcontrib-qthelp-1.0.3-5.fc35.noarch
python3-sphinxcontrib-serializinghtml-1.1.5-1.fc35.noarch
python3-sphinx-theme-alabaster-0.7.12-12.fc35.noarch
python3-systemd-234-17.fc35.x86_64
python3-tempita-0.5.2-1.fc35.noarch
python3-templated-dictionary-1.1-3.fc35.noarch
python3-tkinter-3.10.0~b4-2.fc35.x86_64
python3-toml-0.10.2-4.fc35.noarch
python3-unbound-1.13.1-7.fc35.x86_64
python3-urllib3-1.26.6-1.fc35.noarch
python3-utils-2.5.6-2.fc35.noarch
python3-vdf-3.4-2.fc35.noarch
python3-xmltodict-0.12.0-12.fc35.noarch
python3-yubico-1.3.3-6.fc35.noarch
python3-zstd-1.4.5.1-4.fc35.x86_64
[mikhail@fedora ~]$ 
</pre>

Package pgadmin4-server should has dependencies from package python3.9

**Comment by stefanhh0** [comment]
Hello @dpage,

the debian stable and unstable distribution have dropped python3.9. 

For Reference see:
https://tracker.debian.org/pkg/python3.9
https://tracker.debian.org/news/1355122/python39-removed-from-testing/
https://tracker.debian.org/news/1407625/removed-3913-1-from-unstable/

Probably also other distributions are moving away from python-3.9.

Because of that, it would be great to see a pgadmin4 release in the near future that runs fine with >= python3.10.

Best regards,
Stefan

**Comment by dpage** [comment]
pgAdmin already supports up to Python 3.11, however, packages for Debian/Redhat based platforms have to be built against the version of Python that comes with the system. Due to limited resources for testing of releases, and the fact that test versions of OSs are a moving target, we do not build official packages Fedora Rawhide (or Debian Testing).
