### ISSUE TITLE
pgAgent 13 spammed messages log (RM #6740)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4544]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6740***
*Originally created by **Joshua White** at 2021-09-15 00:48:29 UTC.*

Yesterday I had the odd situation where something caused pgAgent to lose access to its logfile. It proceeded to spam the messages log for hours, filling my server's disk.

@Sep 14 18:49:04 db-host pgagent_13: open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not op
Sep 14 18:49:04 db-host pgagent_13: pen the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not ope
Sep 14 18:49:04 db-host pgagent_13: n the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open
Sep 14 18:49:04 db-host pgagent_13: the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open th
Sep 14 18:49:04 db-host pgagent_13: e logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the
Sep 14 18:49:04 db-host pgagent_13: logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the lo
Sep 14 18:49:04 db-host pgagent_13: gfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logf
Sep 14 18:49:04 db-host pgagent_13: ile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfil
Sep 14 18:49:04 db-host pgagent_13: e!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!
Sep 14 18:49:04 db-host pgagent_13: Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Ca
Sep 14 18:49:04 db-host pgagent_13: n not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can not open the logfile!Can
Sep 14 18:49:04 db-host pgagent_13: not open the logfile!Can not open t@

Presumably this is not expected behaviour.

**Comment by FaharAbbasRizvi** [comment]
The latest pgAgent  contains this change 5d87a7b758eeaca09b6e7f4be3fa32c8eb4a9dce 
pgAgent_PG15 4.2.2-1 --- Built on 2022-11-15 04:59:13 IB: 22.8.0-202210031222

Please note that I have  not seen any issue related to the permission *Can not open the logfile*
