### ISSUE TITLE
Import SQL file exported with the "Include CREATE DATABASE statement" option (RM #6769)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4569]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6769***
*Originally created by **Cheyenne Forbes** at 2021-09-20 16:15:25 UTC.*

I'm not able to restore a database with the "Include CREATE DATABASE statement" option

**Comment by adityatoshniwal** [comment]
Duplicates #3060.
