### ISSUE TITLE
Generate ERD at the schema level (RM #6785)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4580]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6785***
*Originally created by **Robert Hewlett** at 2021-09-22 13:30:17 UTC.*

It would be nice to generate an ERD at the schema level or restricted to the schema.

**Comment by githubchr** [comment]
+1
I would appreciate that very much. On large databases (30 schemas, ~ 3000 tables), the function is unusable because the application locks up (I gave up after 15 minutes and killed pgAdmin).

**Comment by akshay-joshi** [comment]
Tested with snapshot build [2023-12-01](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-01/).
Working fine.
