### ISSUE TITLE
improving acces to objects metadata (RM #6805)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4596]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6805***
*Originally created by **Fred Escallier** at 2021-09-24 13:48:37 UTC.*

hi
I use metadata "comment" to document my postgresql database (any objects : tables , fields...)

it would by nice if pgadmin4 can display "comment" metadata in the tree view

I propose 2 ideas :
* a tooltip that displays the comment on mouseover in the tree view
* a right-click action that proposes a tabular display of the metadata for some objects (tables, views...) with columns the name of the fields and the comments metadata (others ?)

your opinion ?

Fred

**Comment by adityatoshniwal** [comment]
This is done and can be controlled using `Object Breadcrumbs` - https://www.pgadmin.org/docs/pgadmin4/8.1/preferences.html
