### ISSUE TITLE
Tree icons hide on browser tree horizontal resize (RM #6860)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4645]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6860***
*Originally created by **Aditya Toshniwal** at 2021-10-05 06:13:50 UTC.*

Attached is the screenshot. Resize horizontally to reduce size and labels will overlap the icons.
The node selection is also partial on horizontal scroll.

**Comment by nl-savills-insightdata** [comment]
I believe this issue is not manifesting itself anymore, at least not on Windows 11 H2 and pgAdmin v6.21.

**Comment by akshay-joshi** [comment]
This issue is not reproducible on the latest version.
