### ISSUE TITLE
"Create - Server" UI ; "Name" equals "Servcie" if nothing else is entered (RM #6884)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4666]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6884***
*Originally created by **Marek Läll** at 2021-10-08 10:28:01 UTC.*

*Goal / Expectation:*
While we add new server then we would like to enter only (and only) "Name".
Nothing else should be mandatory. If no other input is given then "Name" should be used as "Service" to connect to database.

*Why?*
Imagine there are tens or hundreds of databases, many users, and users use multiple applications to connect to databases.
It is easy to have central "pg_service.conf" and ".pgpass" file shared by multiple client applications inside same "computer/server".
It is easy to have central "pg_service.conf" in a git, file share  or web server etc which is shared by multiple "users/applications/computers"
There is no point to enter same information (hostname, port, username, database name etc) again and again by different users into different clients (pgAdmin3, pgAdmin4 etc).

*Problems at the moment with pgAdmin4*
Right now we need to:
1) enter "Name" and "Service" <- same information 2 times   <- expectation: only "Name" is filled
2) delete prefilled value in field "Port" manually          <- expectation: either not filled by default OR if service provices "port" then ignored (right now it overrides service.port)
3) delete prefilled value in field "Username" manually      <- expectation: either not filled by default OR if service provices "user" then ignored (right now it overrides service.user)
4) fill in mandatory value for field "Maintenance database"  <- expectation: either not filled by default OR if service provices "dbname" then ignored (right now this field is mandatory! I even can not delete it! I really need to go to service description and copy real value!)

**Comment by adityatoshniwal** [comment]
If the `service` in connection tab is entered then host name, port, username, etc becomes optional.
Closing.
