### ISSUE TITLE
Launching from task bar spawns an extra icon (RM #6934)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4708]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6934***
*Originally created by **Bilge B** at 2021-10-19 08:18:29 UTC.*

Windows users have the option to add the application to their task bar. However, since v6, launching the application this way will cause a second icon to spawn next to the shortcut, instead of just highlighting the one that was clicked. In the attached screenshot of the taskbar, the left-most icon is the shortcut to v6, but clicking it causes another icon to appear to its right. In v5 this worked as expected.

**Comment by akshay-joshi** [comment]
This seems to be fixed with the latest version. I have tested it on Windows 11.
