### ISSUE TITLE
After removing database from properties tab, its properties is also displayed (RM #6964)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4731]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6964***
*Originally created by **Fahar Abbas** at 2021-11-01 07:41:39 UTC.*

Steps:
1. create new database
2. Go into the properties tab
3. Select database
4. Click on drop database
5. Database removed
6. Properties of database still displayed

Expected Result:
----------------
After removing database from properties tab, its properties should not displayed

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
