### ISSUE TITLE
Be able to close "SQL" and "Properties" tabs (RM #6966)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4733]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6966***
*Originally created by **Dave Caughey** at 2021-11-01 12:29:09 UTC.*

Please make it possible to close the "SQL" and "Properties" tabs (currently, they have no "X" to close it). In many years of using pgAdmin, I've only used the SQL tab a few times (mostly to report pgAdmin bugs via redmine). I do occasionally use the "Properties" tab, but again, it would be ideal if this could be hidden and only shown when I need it. *Screen real estate for tabs is in very short supply* so it's frustrating having space dedicated to functionality that a developer has decided that all users must see, all the time.

**Comment by adityatoshniwal** [comment]
Related to #6479.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on today's snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-11-02/yum/

OS - Rocky Linux 9.2 (Blue Onyx)
Mode - Desktop
