### ISSUE TITLE
It's confusing/unnecessary having multiple "Properties" UI elements (RM #6967)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4734]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6967***
*Originally created by **Dave Caughey** at 2021-11-01 12:45:07 UTC.*

One can drill down to a database/table, right click on it and select an item called "Properties" that brings up a tabbed properties dialog, showing (presumably) all modifiable settings for that particular table.

There is also a "Properties" tab in the main window that shows a selection of settings/info about the currently selected table.  This information is not quite the same as right-clicking and selecting "Properties" as described above.

There should only be one "Properties" interface for an entity (presumably the one you get by right-clicking on the entity).  Whether you choose to offer alternative ways to access it (e.g., right-click and select "Properties", or click on the "Properties" tab in the main window) you should see exactly the same information/settings.  

If the argument is that the "Properties" tab in the main window is *supposed* to be different because it only shows a quick snapshot or overview of the entity, then call it something appropriate!  E.g., rename the tab to be "Overview" or "Entity" or "Quick View" or something to indicate it's just a high-level subset of the *actual* properties.

And as per RM #6966, regardless of whether the "Properties" tab shows the same information as right-click "Properties" or just a subset (and is renamed to something less confusing than "Properties"), the main window tab should be closable...

**Comment by yogeshmahajan-1903** [comment]
Working fine.
