### ISSUE TITLE
Usability issue with Macros (RM #6969)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4735]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6969***
*Originally created by **Dave Caughey** at 2021-11-01 14:31:18 UTC.*

I just started playing with macros, and have the following usability observations:

To create a macro, you should be able to right click on any displayed SQL (e.g., in the Query Tool or "View/Edit Rows") and click "Add to macros" (or "Create macro"), whereby you get prompted for the name and key binding (or just add it to the next free slot).

There should be a default name (e.g., "Macro 5") so the user doesn't have to pick an explicit name for each macro before they can save it.  (Minor issue)

If you ever want to change the key bindings (e.g., swap CTRL+1 and CTRL+2 functionality), you have to manually rebuild both macros (e.g., type in the name and SQL for both).  Either the key sequence should be editable, or there should be shift up/down keys to re-order them.

There is a limit of 22 macros (CTRL + 0-9, CTRL + F1-F12).  There is no need for this limit, because there's actually no need to have a macro bound to a CTRL+<key> sequence.  Most people will click on the Macros icon, look at the names, and pick the desired macro from the list, rather than blindly type CTRL+5 and hope that they remembered that their desired query was bound to CTRL+5 and not CTRL+6.  Only the most commonly used macros will ever be invoked by a CTRL+<key> sequence.

The "Save" button in Manage Macros isn't enabled until focus is lost on an input.  E.g., if I paste in some SQL, then click on the "Name" input and enter "My Macro" I still can't click Save, until I tab away from the Name input.

**Comment by pravesh-sharma** [comment]
@RohitBhati8269, I found one issue.

The Macros dialog opens but nothing is displayed, if I close the dialog and then again open contents are displayed. It displays content on alternate clicks. Attaching screen recording for ref:


https://github.com/pgadmin-org/pgadmin4/assets/111979571/a6a25511-32e6-4707-a713-b38dec50220e
