### ISSUE TITLE
Save DB access information per database instead of per server (RM #6995)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4757]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6995***
*Originally created by **Yu Jin** at 2021-11-11 12:27:59 UTC.*

When there are many different databases on the same server I find it difficult to keep an overview in pgadmin. I guess that pgadmin is meant for the database administrators where the user can access all databases on the server, but that is often not the case for me. Most of the time I only get access info for one specific database which I have to work on, with that info I have permissions only on the given database, I can not access all the other databases running on the same server. I am aware that a user can see all the databases on the server and also all the tables in the databases by default, but that user can not access the table's content on a different database than his own and therefore not work on the other databases. As it is right now in pgadmin I can only add a server connection with the user I'm given and that user and password then is fixed for all the databases on that server connection. If I'm given a second user info to access a second database, I have to add another server connection, which would be the same server just a different user. Then it is kind of strange having 2 same servers for 2 databases which are actually on 1 server. I then would have to keep in mind which server connection is for which database and always search the one I currently need jumping back and forth between the server connections.
What would make sense here is a possibility to store user and password for each database instead of each server additionally to the administrator credentials. When adding a connection, make a checkbox next to username asking if it is an administrator user or a regular user and then if it is a regular user let them choose which database to access with that user and store that credentials for that database. This would also enable another useful addition, a setting where users can let pgadmin hide the databases on a server, for which there is no access info stored (as long as there is no administrator access info supplied).

**Comment by pravesh-sharma** [comment]
This is by the design of pgAdmin. However, we have added a copy server feature.
