### ISSUE TITLE
disable master password requirement when using alternative auth source (RM #7012)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4769]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7012***
*Originally created by **Eric Gagnon** at 2021-11-18 22:00:59 UTC.*

Using alternative auth sources (oauth2, webserver, kerberos) still requires the user to either:
* set and use a master password every time you 'login'
* enter the database connection passwords every time you 'login'  

This effectively negates the benefit of outsourcing auth to other systems. It should be possible to either disable the master password or use a default one.

**Comment by ericsgagnon** [comment]
Any update on this feature?

**Comment by ericsgagnon** [comment]
Any update on this yet?

**Comment by DavidHaltinner** [comment]
Right now I am swapping in the master key directly into the master_password.py at runtime, passing it by way of a kubernetes secret as an environment variable (Running it in OpenShift). 
But having the option of using an env variable for k8s-based environments may make sense for this case as well.

sed -i "s/enc_key = current_app.keyManager.get()/enc_key = '$MASTER_PASSWORD'/g" /pgadmin4/pgadmin/utils/master_password.py

is what i am doing now to make it work for me, but it is not ideal.

**Comment by tchristie-meazure** [comment]
+1 for an update on this. I'll be using @DavidHaltinner fix for now, but Oauth2 users should not have to enter the master password every time they log in.

**Comment by khushboovashi** [comment]
We have already prioritised this feature, you will get an update on this soon.

**Comment by pravesh-sharma** [comment]
Below are my findings after initial testing:

1. If a user moves back from `MASTER_PASSWORD_HOOK` application asks for master password and if we enter wrong password no prompt is show for wrong master password (It is reproducible if `MASTER_PASSWORD_HOOK` is not used at all).
2. If we try to reset master password we are getting an error and master password is not reset.
3. If file permission for script file is not proper the error message is not descriptive, we should show error with proper message like file does not haver permission etc.

**Comment by pravesh-sharma** [comment]
Tested on latest snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-26/) and is working as expected
