### ISSUE TITLE
Range partitions creation works but subsequently can't be found correctly (RM #7028)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4784]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7028***
*Originally created by **Ian Campbell** at 2021-11-24 22:24:25 UTC.*

The following executes without problem:

CREATE TABLE part (
    h "char" not null,
    val int4 not null
) PARTITION BY RANGE (h);

create table part_00 partition of part FOR VALUES FROM ((-128)::"char") to ((-113)::"char");
create table part_01 partition of part FOR VALUES FROM ((-112)::"char") to ((-97)::"char");
create table part_02 partition of part FOR VALUES FROM ((-96)::"char") to ((-81)::"char");
create table part_03 partition of part FOR VALUES FROM ((-80)::"char") to ((-65)::"char");
create table part_04 partition of part FOR VALUES FROM ((-64)::"char") to ((-49)::"char");
create table part_05 partition of part FOR VALUES FROM ((-48)::"char") to ((-33)::"char");
create table part_06 partition of part FOR VALUES FROM ((-32)::"char") to ((-17)::"char");
create table part_07 partition of part FOR VALUES FROM ((-16)::"char") to ((-1)::"char");
create table part_08 partition of part FOR VALUES FROM (0::"char") to (15::"char");
create table part_09 partition of part FOR VALUES FROM (16::"char") to (31::"char");
create table part_10 partition of part FOR VALUES FROM (32::"char") to (47::"char");
create table part_11 partition of part FOR VALUES FROM (48::"char") to (63::"char");
create table part_12 partition of part FOR VALUES FROM (64::"char") to (79::"char");
create table part_13 partition of part FOR VALUES FROM (80::"char") to (95::"char");
create table part_14 partition of part FOR VALUES FROM (96::"char") to (111::"char");
create table part_15 partition of part FOR VALUES FROM (112::"char") to (127::"char");

I'm aware the upper bounds should be exclusive. Nonetheless, in pgAdmin 6.1, navigating to "Partitions" (even after refreshing and rebooting the server) results only in a spinning wheel.

**Comment by FaharAbbasRizvi** [comment]
Range partition was found correctly in the last release of pgadmin4 v2.0 as well on the latest psycopg3 and the following SQL  is still displayed:

CREATE TABLE IF NOT EXISTS public.part_00 PARTITION OF public.part
    FOR VALUES FROM ('\200') TO ('\217')
TABLESPACE pg_default;

**Comment by FaharAbbasRizvi** [comment]
Version tested
PG/AS 12, 13, 14 and 15.

This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-14/
