### ISSUE TITLE
Add all the new options in subscription(Supported from v14 above)  (RM #7055)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4805]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7055***
*Originally created by **Pradip Parkale** at 2021-12-03 11:02:07 UTC.*

https://www.postgresql.org/docs/14/sql-createsubscription.html

**Comment by anilsahoo20** [comment]
Add password_required (16 and above). #6454

**Comment by FaharAbbasRizvi** [comment]
This is tested on the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-08-30/
