### ISSUE TITLE
SELinux denials for /var/log/pgadmin (using httpd) (RM #7068)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4812]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7068***
*Originally created by **Heidi Kühnemann** at 2021-12-13 08:00:17 UTC.*

I installed pgadmin4 on RHEL 8.5 using httpd as web server. However, there is a SELinux denial for the directory pgadmin4.log (located in /var/log/pgadmin/pgadmin4.log).

I got the following sealert:

<pre><code class="shell">
SELinux is preventing /usr/sbin/httpd from remove_name access on the directory pgadmin4.log.

*****  Plugin catchall (100. confidence) suggests   **************************

If you believe that httpd should be allowed remove_name access on the pgadmin4.log directory by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'httpd' --raw | audit2allow -M my-httpd
# semodule -X 300 -i my-httpd.pp

Additional Information:
Source Context                system_u:system_r:httpd_t:s0
Target Context                unconfined_u:object_r:httpd_log_t:s0
Target Objects                pgadmin4.log [ dir ]
Source                        httpd
Source Path                   /usr/sbin/httpd
Port                          <Unknown>
Host                          dbserver
Source RPM Packages           httpd-2.4.37-43.module+el8.5.0+13064+c4b14997.x86_
                              64
Target RPM Packages
SELinux Policy RPM            selinux-policy-targeted-3.14.3-80.el8.noarch
Local Policy RPM              selinux-policy-targeted-3.14.3-80.el8.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Enforcing
Host Name                     dbserver
Platform                      Linux dbserver 4.18.0-348.2.1.el8_5.x86_64 #1 SMP
                              Mon Nov 8 13:30:15 EST 2021 x86_64 x86_64
Alert Count                   156877
First Seen                    2021-11-26 14:19:45 CET
Last Seen                     2021-11-29 16:46:15 CET
Local ID                      e0d88406-f4a7-44d4-8b83-002c3d4db50a

Raw Audit Messages
type=AVC msg=audit(1638200775.83:157617): avc:  denied  { remove_name } for  pid=20571 comm="httpd" name="pg                         admin4.log" dev="dm-0" ino=67597311 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:htt                         pd_log_t:s0 tclass=dir permissive=0

type=SYSCALL msg=audit(1638200775.83:157617): arch=x86_64 syscall=rename success=no exit=EACCES a0=7f70e1733                         950 a1=7f70e1970520 a2=0 a3=2 items=0 ppid=1330 pid=20571 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsui                         d=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm=httpd exe=/usr/sbin/httpd subj=system_u:system_                         r:httpd_t:s0 key=(null)

Hash: httpd,httpd_t,httpd_log_t,dir,remove_name
</code></pre>

After I created a custom rule for httpd_t (allow httpd_t httpd_log_t:dir remove_name;), a new denial appeared.

<pre><code class="shell">
type=AVC msg=audit(1638864082.541:196945): avc:  denied  { rename } for  pid=49875 comm="httpd" name="pgadmin4.log" dev="dm-0" ino=67597311 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:httpd_log_t:s0 tclass=file permissive=0
</code></pre>

I had to create a second custom rule: 
<pre><code class="shell">
allow httpd_t httpd_log_t:file rename;
</code></pre>

**Comment by akshay-joshi** [comment]
Not reproducible.

**Comment by smiba** [comment]
Exact same issue on RHEL9, selinux denies for almost all of pgadmin's files, clean RHEL install. Can't access the log directory or sessions directory for example

**Comment by smiba** [comment]
Update: This happened because we didn't run /usr/pgadmin4/bin/setup-web.sh after installation, this script includes the necessary selinux configuration

This happens in:
https://github.com/pgadmin-org/pgadmin4/blob/306269af5de842d2674de72348f9af745bbe3ed5/pkg/linux/setup-web.sh#L95-L101
