### ISSUE TITLE
ERD: unique indexes (RM #7092)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4832]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7092***
*Originally created by **Mattia Manfroni** at 2021-12-27 11:33:56 UTC.*

In the current version of ERD I don't see the possibility neither to visualize, or edit, or create unique index on tables.. am I wrong?
If it is, then it would be nice to have this feature.. Maybe an idea could be to have an additional tab in Table Constraint section (see in attachment)? Thanks

**Comment by adityatoshniwal** [comment]
This is already implemented. Closing.
