### ISSUE TITLE
Add filename filter to Open File dialog (RM #7095)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4834]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7095***
*Originally created by **Paul Bryant** at 2021-12-28 16:27:33 UTC.*

It would be useful to have a filter feature in the Open File dialog, for finding files in directories with lots of files in them.  All major operating systems have this feature in their system file > open dialogs and so it seems like a missing feature in pgAdmin 4's custom version of this dialog.

**Comment by adityatoshniwal** [comment]
This is implemented when file dialog was ported to React based.
