### ISSUE TITLE
Schema diff - Timeout error is not handled when pgAdmin4 is hosted on Apache/Httpd (RM #7104)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4841]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7104***
*Originally created by **Murtuza Zabuawala** at 2022-01-07 06:32:35 UTC.*

Newer version of httpd on CentOS/Redhat has very low TimeOut value by default - 60 sec
So if schema diff takes longer than that it throws blank error popup.

Refer attached screenshot.

Expected - Display proper error instead of blank popup.

**Comment by adityatoshniwal** [comment]
This can be handled with SocketIO lib which pgAdmin is already using in psql and in ERD to fetch database tables data.

**Comment by FaharAbbasRizvi** [comment]
Tested on candidate build for v6.16.
