### ISSUE TITLE
Tree browser section is not properly proportionate to screen size. Centos7 (RM #7112)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4848]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7112***
*Originally created by **Yogesh Mahajan** at 2022-01-11 05:41:11 UTC.*

On fresh installation , please find first view of pgAdmin.

**Comment by FaharAbbasRizvi** [comment]
This is also reproducible on Rhel 9 as well.

**Comment by adityatoshniwal** [comment]
wcDocker will be replaced with #6479. To be tested once it is committed.
