### ISSUE TITLE
Move alert box in properties panel (RM #7129)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4862]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7129***
*Originally created by **Jonathan G** at 2022-01-19 01:34:28 UTC.*

As a user, when I'm building new tables that have more columns than the height of the properties menu, I have to go back and forth to hit the plus button.  When I do add a new column, because I have to scroll down that triggers the alert message box to complain about not having a column name.  This almost completely covers the new column row I added.  Assuming I can get a name in for the column, the error box doesn't go away it just complains about the type being missing too.  Again I'm forced to try and type behind the alert box or have to close the alert every single time.  As a big usability gain, could that alert box be top aligned instead of bottom aligned so as not to cover things up.

**Comment by adityatoshniwal** [comment]
This is completed. Error message doesn't override input controls.
