### ISSUE TITLE
release pgAgent source bundle v4.2.2 for download (RM #7153)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4881]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7153***
*Originally created by **Frank Limpert** at 2022-02-03 11:44:08 UTC.*

On the "pgAgent Source Code":https://www.pgadmin.org/download/pgagent-source-code/ page there is still version v4.0.0 which is buggy regarding bug #6238 which was fixed some time ago. I know that the current version is available via GIT. However, it would be nice to replace the download of the buggy version.

**Comment by akshay-joshi** [comment]
This is fixed.
