### ISSUE TITLE
It is not possible to import csv data to tables having columns with german umlauts in their names (RM #7156)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4884]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7156***
*Originally created by **ED H** at 2022-02-03 18:24:20 UTC.*

It is not possible to use the import/export - function provided by pgadmin4 6.4 to import csv data to tables having columns with german umlauts in the column's names.
The error occurs even if the import file is empty, i.e. the error occurs independently of the imported data.

If you create a table like this described by the following create script then importing data leads to this error under WINDOWS 10 (see also attached screenshot):
'ERROR:  invalid byte sequence for encoding "UTF8": 0xfc'

CREATE SCRIPT:

CREATE TABLE IF NOT EXISTS public."TableWithUmlautInColumnName"
(
    "Hülsenfrüchte" text COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."TableWithUmlautInColumnName"
    OWNER to postgres;

**Comment by FaharAbbasRizvi** [comment]
This issue is still not fixed in the latest psycopg3 builds:

<img width="1015" alt="Screen Shot 2023-02-23 at 12 08 56 PM" src="https://user-images.githubusercontent.com/43006122/220840570-9f6f918c-36da-44f9-b73d-ed63559d0e8f.png">

**Comment by khushboovashi** [comment]
This issue is not reproducible with WIN120 encoding as these are Windows-1250 characters.

**Comment by FaharAbbasRizvi** [comment]
I have tested this issue on Windows 10 and MAC OS X.

In the case of MAC OS X, this issue is fixed with uft8 while on windows "ERROR: invalid byte sequence for encoding "UTF8": 0xfc'" is also displayed with utf8 and that is expected behaviour and message coming from the server side.

On Windows I created with database with  ENCODING = 'WIN1252 and the issue has been resolved.
