### ISSUE TITLE
Native Apple Silicon support (RM #7161)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4888]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7161***
*Originally created by **Richard Brockie** at 2022-02-06 01:45:14 UTC.*

Apple silicon has been available for more than a year.

At some point Rosetta 2 will go away - this is a feature request to have native Apple Silicon support well before the demise of Rosetta 2.

Apologies if this is a duplicate request - I was surprised when searching for "Apple silicon" didn't reveal any prior requests

**Comment by scottt** [comment]
@akshay-joshi , @dpage , since the upstream NW.js issue is closed as fixed I think the "Waiting for upstream" tag should be removed from this issue https://github.com/nwjs/nw.js/issues/7620

**Comment by dpage** [comment]
Unfortunately we are still waiting for upstream - whilst we have an M1 build now, there are issues with code signing it: https://github.com/nwjs/nw.js/issues/8086

**Comment by stuaxo** [comment]
@akshay-joshi now that @dpage has closed https://github.com/nwjs/nw.js/issues/8086 this might be good to go ?

**Comment by akshay-joshi** [comment]
@stuaxo

We are working on it.

**Comment by scottt** [comment]
Hi @akshay-joshi , @dpage  any chance you guys could give pgadmin4 Apple Silicon builds another try and move this into a sprint?

The previous nwjs/nwjs#8086 blocker has been closed for a while.

**Comment by dpage** [comment]
Hmm, I guess we forgot to close this issue. We've had an Apple Silicon build since v7.7.

**Comment by rafrafek** [comment]
https://www.pgadmin.org/docs/pgadmin4/development/release_notes_7_7.html
