### ISSUE TITLE
pgAdmin 4 v6.5 / Windows 10 - screen flashes white on window switching (RM #7185)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4905]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7185***
*Originally created by **David Chalmers** at 2022-02-16 21:07:00 UTC.*

The screen flashes white when switching from any other window to the pgAdmin window. A video of the issue is attached. It occurs no matter what the other program being switch from happens to be (EditPad Pro 8 is the other program used in the video, but also occurs when switching from Firefox, Outlook, Office programs, etc). It also occurs whether the pgAdmin theme is Dark or Standard.

This may only occur with a full screen / maximised window, as smaller window sizes were not tested.

I've switched back to pgAdmin v6.4 and can confirm that this does not occur with v6.4.

**Comment by FaharAbbasRizvi** [comment]
I am not able to reproduce the issue on the latest snapshot build.

**Comment by FaharAbbasRizvi** [comment]
Issue is not reproducible on Windows 10.
