### ISSUE TITLE
cntrl+enter to execute the specific statement where cursor is blinking (RM #7251)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4956]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7251***
*Originally created by **Suvradipta Sadhukhan** at 2022-03-16 12:27:47 UTC.*

1. cntrl+enter to execute the specific statement where cursor is blinking, witouht selecting the specific statement.
2. Need to save the SSH Tunnel password.

**Comment by pravesh-sharma** [comment]
Both the features are implemented in other issues.
