### ISSUE TITLE
Error when trying to register a server using ssh tunneling (RM #7271)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4973]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7271***
*Originally created by **Junior Ortiz** at 2022-03-27 01:18:02 UTC.*

I am on v6.7 and I got it from the official websites download page
I'm running on desktop mode (windows 10).

And here are the steps I take to repro the issue:
    1. Start by opening the dialog to register a new server.
    2. Fill out required info as normal.
    3. Enable use ssh tunneling fill out required info
    4. I selected identity file and selected the file path but this also happens when I tried to use password as well.
    5. Attempt to press save and the error will appear (INTERNAL SERVER ERROR: [Errno 22] Invalid argument: '\\\\.\\pipe\\openssh-ssh-agent')

I' attached my log file and hopefully that can help ^ ^

**Comment by akshay-joshi** [comment]
Hi @James, @Junior, and @Michael

Issue [#2008](https://github.com/https://github.com/paramiko/paramiko/issues/2008) has been fixed by Paramiko. Can you please verify it with the latest pgadmin?
