### ISSUE TITLE
Query editor problem on safari browser - ipad (RM #7284)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4982]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7284***
*Originally created by **Yustanto ST** at 2022-04-02 07:10:33 UTC.*

When typing on query editor, no cursor shown, and spacebar not working properly. 
There’s no problem on scrath pad editor.

**Comment by yogeshmahajan-1903** [comment]
Duplicate of #3647.
