### ISSUE TITLE
[ERD] Downloads image maybe lost links (RM #7298)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4995]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7298***
*Originally created by **Thomas Chen** at 2022-04-08 08:35:08 UTC.*

Hi, guys:
When I use downloads image from the erd, maybe lost the links the foreign relations.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-10-06/
Environment: macOSX Ventura 13.4.1

**Comment by NuwanSameera** [comment]
Is this fixed now ?

**Comment by adityatoshniwal** [comment]
@NuwanSameera  Yes, please try on v7.8 and let us know.

**Comment by NuwanSameera** [comment]
@adityatoshniwal Great. It is working. Thank you.
