### ISSUE TITLE
[ERD] Generate sql, delete old tables  (RM #7300)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4997]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7300***
*Originally created by **Thomas Chen** at 2022-04-08 09:37:34 UTC.*

When I generate SQL, can we set an option for whether delete old tables?
If I choose YES, then the SQL will include a drop table and create a table; if choose NO, then create a table if not exists.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-10-07/
