### ISSUE TITLE
Shared storage mount in server mode (RM #7318)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5014]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7318***
*Originally created by **Eric Ellsworth** at 2022-04-14 18:56:47 UTC.*

In server mode, pgadmin creates a new virtual root for each user inside their own user account, which is typically in /var/lib/pgadmin/storage.  In many cases, a user may want to load or save items to shared storage.  

While it is possible to create symlinks for each user, this is a manual process and not very easy to integrate with deployment methods such as Docker.

I am currently mounting Windows storage into pgadmin inside a Docker container.

It would be very helpful if there were a shared storage folder and the user creation process generated symlinks inside each user's own folder.  This way the storage folder would be visible inside the virtual root for the user.

Some "bonus" features here would be:
 - Ability to add/remove shared storage through the Storage Manager window in pgAdmin (basically through mountable filesystems).
 - Also cool but possible harder would be the ability to have pgadmin read files directly from cloud sources such as S3 buckets.

**Comment by adityatoshniwal** [comment]
I tried this on ubuntu jammy with shared location as `/tmp/sharedfolder` but somehow it is taking some other location.
Also, a note need to be added in the docs related to folder permission. I am getting below error when I tried to share a folder with owner not same as what pgAdmin is running.
![image (13)](https://user-images.githubusercontent.com/31855755/225223302-b8eea275-b1be-4697-b3be-6eee2f3a5706.png)

**Comment by adityatoshniwal** [comment]
Hi @nikhil-mohite,
The feature seems to be working very well. I have few suggestions here:
1. When the storage is in restricted access then user should not be allowed to `Save` a new file and `Save As` as we're restricting upload.
2. Options like create folder, rename, delete should be hidden in case of restricted access. Backend works fine.
3. Shared storage documentation update:
```
In the storage manager, My Storage is the pgAdmin user’s storage directory, and other listed directories are shared storages set by the pgAdmin server administrator. Using this shared storages users, pgAdmin users can have common storages to share files. pgAdmin server administrator can configure the shared storages using the <link>config file</link>. Storages can be marked as restricted to give read-only access to non-admin pgAdmin users.
```
4. In docs, the note section should match styling with other notes. Refere master password page.
5. @dpage Can you please improve `NOTE: You must ensure the directories specified are writeable by the user that the web server processes will be running as, e.g. apache or www-data.`
6. When switching from "All files" to "sql" and back to "All files", some of the files are not visible. A refresh is needed. This behaviour occurs only in shared storages.
![image](https://user-images.githubusercontent.com/31855755/226584416-19c58767-55c6-4700-b5c7-e2313c79cc40.png)

**Comment by adityatoshniwal** [comment]
Works fine. Tested on Ubuntu Jammy on 28-Mar-2023 build.
