### ISSUE TITLE
Accesskey won't work in windows CTRL-C and CTRL-V  with View/Edit Table (RM #7328)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5022]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7328***
*Originally created by **Mike Moening** at 2022-04-20 22:25:41 UTC.*

When opening two different tables using PGAdmin 6.7 I am unable to use CTRL-C and CTRL-V to move rows between two tables in a different databases.
In the attached pic is shows AccessKey - C as the way to copy and Accessky - V as paste.

However where does it say what Accesskey actually is?
Without standard windows behavior its very difficult to use and clunky.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-28/

Environment - macOS Monterey 12.6.3 (Desktop mode)

**Comment by pravesh-sharma** [comment]
Reopening issue as in ubuntu access key is not correctly displayed.

<img width="1716" alt="Screenshot 2023-03-28 at 7 14 06 PM" src="https://user-images.githubusercontent.com/111979571/228258165-70922b1d-e5af-4247-9b5b-95136bc14731.png">

**Comment by adityatoshniwal** [comment]
@pravesh-sharma Please share the accesskey for the mentioned platform+browser. Accesskey is not automatically detected. It is hard coded based on OS+Browser combination.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-03/

Environment - 

1. macOS Monterey (12.6.3) (Desktop and server mode).
2. Ubuntu 22.04 (Desktop and server mode).
3. Windows 10 Pro (22H2) (Desktop and server mode).
