### ISSUE TITLE
Function Keywords (count, distinct) are formatted as identifiers rather than keywords (RM #7329)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5023]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7329***
*Originally created by **Brexton Popejoy** at 2022-04-21 00:20:57 UTC.*

When using the SQL formatting function in the Query Tool, function keywords like "count" and "distinct" are formatted according to identifier settings rather than keyword.

Ex, if in Preferences >> Query Tool >> SQL formatting I set "Identifier case" to "Lower case" and "Keyword case" to "Upper case", my query will be formatted like _SELECT count column_x FROM table_a;_ when it should be _SELECT COUNT column_x FROM table_a;_

**Comment by nikhil-mohite** [comment]
Hi Brexton Popejoy,

With parentheses, it's a function and not a keyword anymore.
