### ISSUE TITLE
Show only non-empty nodes/categories/groups in pgAdmin-4 (RM #7357)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5048]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7357***
*Originally created by **Jan Zidek** at 2022-05-04 15:38:29 UTC.*

In the IntelliJ Idea's Database View, you can hide all the empty categories/nodes/groups by unchecking the `Show Empty Groups` switch.

In the following example, in my database the only existing objects are tables and functions. I am not disturbed by a lot of unused categories.

**Is it possible to achieve a similar effect in pgAdmin?** 

All I found in the settings is `Preferences` | `Nodes` | `Show/Hide nodes in the browser tree`, but these settings are static, they do not reflect the presence of objects in the categories.
!https://i.stack.imgur.com/uPpzU.png!

#### pgAdmin - always all categories
!https://i.stack.imgur.com/bisYV.png!

See also https://dba.stackexchange.com/q/311642/55104

**Comment by FaharAbbasRizvi** [comment]
@adityatoshniwal 

If the user disabled "Show empty object collections?" and in the view child nodes are still displayed.

**Comment by adityatoshniwal** [comment]
> @adityatoshniwal
> 
> If the user disabled "Show empty object collections?" and in the view child nodes are still displayed.

Please share some screenshot.

**Comment by FaharAbbasRizvi** [comment]
<img width="1418" alt="Screen Shot 2023-05-25 at 10 52 08 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/15a8a374-db5e-463d-a397-cb5d6cddda53">

**Comment by adityatoshniwal** [comment]
@FaharAbbasRizvi Test everything and then assign it to me with all the issues.

**Comment by FaharAbbasRizvi** [comment]
@adityatoshniwal 

I have checked the pgAgent is still available if we disable the Show empty object collections? from the preferences, is this expected?

**Comment by FaharAbbasRizvi** [comment]
@adityatoshniwal 

The schema node is still visible if the user drops the public schema and the node is empty if the user disables the *Show empty object collections?* from the preferences.

<img width="950" alt="Screen Shot 2023-05-25 at 3 21 03 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/d64a2164-ff6a-4dd3-bba0-575cebb09fc6">

**Comment by FaharAbbasRizvi** [comment]
@adityatoshniwal 

Language nodes should also be disabled.
<img width="882" alt="Screen Shot 2023-05-25 at 3 48 53 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/373bb9f1-5390-4229-9cd9-ddc7d582a330">

**Comment by FaharAbbasRizvi** [comment]
@adityatoshniwal 

Index nodes should be disabled for metalized views
<img width="992" alt="Screen Shot 2023-05-25 at 6 12 33 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/2fad1ad4-8f2f-4636-94c1-91a489e97aa7">

**Comment by FaharAbbasRizvi** [comment]
Aggregated should also be disabled if the user disabled the Show empty object collections? from the preferences.
CREATE OR REPLACE AGGREGATE public.avg(double precision) (
    SFUNC = float8_accum,
    STYPE = float8[] ,
    FINALFUNC = float8_avg,
    FINALFUNC_MODIFY = READ_ONLY,
    INITCOND = '{0,0,0}',
    MFINALFUNC_MODIFY = READ_ONLY
);

**Comment by adityatoshniwal** [comment]
HI @FaharAbbasRizvi,

The aggregates one is not reproducible. And we cannot hide pgAgent node as there is no way to add jobs without that node. So I have skipped pgAgent node. All other issues mentioned are fixed.

Thanks.

**Comment by FaharAbbasRizvi** [comment]
All issues have been fixed and now I am closing this ticket.
