### ISSUE TITLE
Save Button should be disabled by default on the Sort/Filter options (RM #7371)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5058]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7371***
*Originally created by **Fahar Abbas** at 2022-05-12 07:08:59 UTC.*

Save Button should be disabled by default on the Sort/Filter options

Steps
1. Launch pgadmin4
2. open Sort/Filter options
3. Save button is enabled

!Screen%20Shot%202022-05-12%20at%2012.05.56%20PM.png!

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-10-24/
