### ISSUE TITLE
Lock Layout > Full Lock Does Not Prevent Detaching of Query Tool Panels (RM #7375)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5062]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7375***
*Originally created by **Anthony DeBarros** at 2022-05-12 15:09:55 UTC.*

Using new version 6.9 on macOS Monterey. I have "Full Lock" chosen under "Lock Layout." Even so, I am able to detach and move panels around.

Not sure if that is the intended behavior, but I was looking for a way to prevent panels from detahcing. Sometimes when I resize the results grid, it detaches. I want to prevent that.

**Comment by stephane303** [comment]
Also it doesn't prevent to close the statistics tab

**Comment by adityatoshniwal** [comment]
The panel management will be completely revamped based on all the issues reported by users in #6479. Lock layout will be discontinued.
