### ISSUE TITLE
regression, re-allow arbitary characters in CSV/TXT Output as separator or quote character (RM #7379)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5066]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7379***
*Originally created by **Attila Soki** at 2022-05-13 12:50:32 UTC.*

Since PgAdmin 4 V6.8, V6.9:
In the preference pane under Settings, Query Tool, CSV/TXT Output the fields
CSV field separator
CSV quote character
CSV quoting
doesn't allowing anymore to select arbitrary characters, only a selection from the dropdown is allowed.
Typing in an arbitrary character is allowed, but it is not possible to save this settings because the save button is remains inactive.

Installing and starting PGAdmin version V4 6.8 or newer changes the previously chosen characters back to the default.

**Comment by FaharAbbasRizvi** [comment]
This is tested and fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-11-07/
