### ISSUE TITLE
"FORMAT SQL"  command messes up -> operator (RM #7400)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5083]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7400***
*Originally created by **Alexis Panagiotopouos** at 2022-05-21 06:51:55 UTC.*

If you have a query containing the '->' or '->>', FORMAt SQL command (shift+ctrl+k) produces wrong SQL.
Example:
<pre><code class="sql">
select '{}'::jsonb->'a'
</code></pre>
becomes:
<pre><code class="sql">
SELECT '{}'::JSONB - > 'a'
</code></pre>
Which is wrong sql (syntax error)

**Comment by danielsamuels** [comment]
`@>` for arrays, too.

**Comment by slyapustin** [comment]
Would like that to be fixed, any ideas on how to better fix that?

**Comment by adityatoshniwal** [comment]
I think we should replace library used formatting the SQL and use - https://www.npmjs.com/package/sql-formatter. It has PostgreSQL dialect support and has better predictable formatting. The existing one works for simple queries, but messes complex queries.
CC: @dpage @akshay-joshi

**Comment by dpage** [comment]
If it truly is better, then I have no problem switching.

**Comment by pravesh-sharma** [comment]
We found that we can not change case of keywords and identifiers separately in the suggested library (which is a limitation as we support it currently) and a feature request is [pending](https://github.com/sql-formatter-org/sql-formatter/issues/237) for the same on library. So, for now we are not moving to the new library

**Comment by anilsahoo20** [comment]
Tested and verified on candidate build: https://developer.pgadmin.org/builds/2024-02-05-1/
Environment: Debian 11

**Comment by we-sell-bags** [comment]
> I think we should replace library used formatting the SQL and use - https://www.npmjs.com/package/sql-formatter. It has PostgreSQL dialect support and has better predictable formatting. The existing one works for simple queries, but messes complex queries. CC: @dpage @akshay-joshi

Why use a "dead" project?
The development of this formatter is currently in maintenance mode. Bugs will get fixed if feasible, but new features will likely not be added.

I have started a new SQL formatting tool: [prettier-plugin-sql-cst](https://github.com/nene/prettier-plugin-sql-cst).

    It solves several problems which can't be fixed in SQL Formatter because of fundamental problems in its arhictecture.
    It makes use of the Prettier layout algorithm, doing a better job of splitting long expressions to multiple lines.
    It takes much more opinionated approach to SQL formatting, giving only a very limited set of options to adjust the code style.
    It already has full support for SQLite and BigQuery syntax. It should work for the most common SQL code in various other dialects.

**Comment by adityatoshniwal** [comment]
> Why use a "dead" project? The development of this formatter is currently in maintenance mode. Bugs will get fixed if feasible, but new features will likely not be added.
> 
> I have started a new SQL formatting tool: [prettier-plugin-sql-cst](https://github.com/nene/prettier-plugin-sql-cst).
> 
> ```
> It solves several problems which can't be fixed in SQL Formatter because of fundamental problems in its arhictecture.
> It makes use of the Prettier layout algorithm, doing a better job of splitting long expressions to multiple lines.
> It takes much more opinionated approach to SQL formatting, giving only a very limited set of options to adjust the code style.
> It already has full support for SQLite and BigQuery syntax. It should work for the most common SQL code in various other dialects.
> ```
HI @we-sell-bags, We're looking forward for the new lib. But we need all the options available in sql-formatter for PostgreSQL which currently are not present in prettier-plugin-sql-cst.
