### ISSUE TITLE
The save button is enabled if the user sees the properties of the table by right-click  (RM #7420)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5098]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7420***
*Originally created by **Fahar Abbas** at 2022-05-26 06:59:37 UTC.*

Steps
1. Table should be created
2. Right-click and go into the properties and click on the Column tab
3. Save button is already enabled <- Issue
4. If save then the message "Cannot execute the empty query" is displayed.

!Screen%20Shot%202022-05-26%20at%2011.39.21%20AM.png!
!Screen%20Shot%202022-05-26%20at%2011.39.30%20AM.png!

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots
