### ISSUE TITLE
Problem with Query Tool (RM #7422)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5099]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7422***
*Originally created by **Mark Pare** at 2022-05-26 19:37:15 UTC.*

Hello, I just upgraded to v6.9 from a previous release (v5.0) and I have multiple issues in the Query Tool:

Standard notepad shortcuts used to work

CTRL-A no longer selects all data
CTRL-END no longer moves the cursor to the last row / last column
Highlighting cells to be able to issue CTRL-C on doesn't work anymore

In general, navigation in the query tool doesn't work the same anymore. Whenever I execute a query, I need to left-click in the Query window otherwise I'm in the Data Output window automatically, which is different than before.

**Comment by pravesh-sharma** [comment]
Except ctrl/cmd + A i.e. select all other keys seems to work. Changes are required in react-data-grid lib used in the query tool

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-12-09/
Package: exe, arm64
Environment: macOs Sonoma 14.7.1 & WIndows 11
