### ISSUE TITLE
Schema Diff issue (RM #7424)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5101]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7424***
*Originally created by **Mark Pare** at 2022-05-26 20:23:14 UTC.*

Hi, when running a schema diff, because the permissions of a table are displayed in a different order, it is considered a difference when it shouldn't be. Example:

DEV database
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE <schema>.<tablename> TO <role>

UAT database
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE <schema>.<tablename> TO <role>

This will generate a difference but it shouldn't the SQL tab displays permissions in a random order in some cases, even if they are always created as SELECT, INSERT, UPDATE, DELETE

Thanks

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-29/
