### ISSUE TITLE
Unable to move expanded cell window into view (RM #7438)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5112]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7438***
*Originally created by **Katie Vogel** at 2022-05-31 18:49:57 UTC.*

When clicking into a cell, particularly a jsonb column that has quite a bit of information, the window that opens to view the information is cut-off with the top half above the output window. There is no way to grab and drag the window down into view so that you can see everything in it. This began when my pgadmin updated to the latest version.

**Comment by yogeshmahajan-1903** [comment]
This is fixed in 6.14 release.
