### ISSUE TITLE
PgAdmin4 v6.10. won't start on ubuntu 20.04. (RM #7442)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5116]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7442***
*Originally created by **Marko Šuštić** at 2022-06-03 07:08:58 UTC.*

After updating to 6.10. I can't start pgAdmin4 on ubuntu 20.04. Same thing is happening to few of my colleagues. I can see the process running but app won't start. Downgrading back to 6.9. is the only solution I have found.

**Comment by nikhil-mohite** [comment]
waiting for nw.js to fix it.

**Comment by khushboovashi** [comment]
This issue has been resolved as we are using latest NWJS v 0.70.0.
