### ISSUE TITLE
[tree] Spinner does not show up when a tree node is refreshed (RM #7448)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5122]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7448***
*Originally created by **Aditya Toshniwal** at 2022-06-06 06:20:13 UTC.*

Spinner does not show up when a tree node is refreshed. If a refresh is slow then then it is difficult to judge if any process is running or not.

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-11-07/
