### ISSUE TITLE
Standard desktop secret store integration for App Bundles (RM #7449)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5123]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7449***
*Originally created by **Tamir Daniely** at 2022-06-06 08:31:35 UTC.*

Support standard desktop secret stores (OSX keychain, Windows Credential Store, Gnome Keyring...) as alternative configuration for master password mechanism in desktop app targets.

**Comment by FaharAbbasRizvi** [comment]
@nikhil-mohite 
In the case of fresh mode, I think, the Cancel button should be available, please note that if I provide any random password it says incorrect master password, this needs to be updated. I have to provide the password again and again.

<img width="1256" alt="Screen Shot 2023-05-26 at 12 21 09 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/427740a4-34cd-426a-ba2b-28405ac415e1">
<img width="1253" alt="Screen Shot 2023-05-26 at 12 28 14 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/4fc29cc2-10c9-4c0c-b68f-547cadeea3c1">

<img width="1159" alt="Screen Shot 2023-05-26 at 12 43 27 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/9e0f2f33-cfc8-4c61-b475-6dcc1977e252">

**Comment by FaharAbbasRizvi** [comment]
@nikhil-mohite 

I can see the master password dialog in the latest snapshot, I have tested on Ubuntu 23.04.
<img width="1257" alt="Screen Shot 2023-05-29 at 8 46 11 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/287277b2-9cd4-4f5f-8265-ade0482580a7">

**Comment by nikhil-mohite** [comment]
> @nikhil-mohite
> 
> I can see the master password dialog in the latest snapshot on fresh installaion, I have tested on Ubuntu 23.04. <img alt="Screen Shot 2023-05-29 at 8 46 11 AM" width="1257" src="https://user-images.githubusercontent.com/43006122/241626693-287277b2-9cd4-4f5f-8265-ade0482580a7.png">

Hi @FaharAbbasRizvi, If pgAdmin is unable to use the OS password manager then it will use the Master password, this is expected behavior.

**Comment by adityatoshniwal** [comment]
> > @nikhil-mohite
> > I can see the master password dialog in the latest snapshot on fresh installaion, I have tested on Ubuntu 23.04. <img alt="Screen Shot 2023-05-29 at 8 46 11 AM" width="1257" src="https://user-images.githubusercontent.com/43006122/241626693-287277b2-9cd4-4f5f-8265-ade0482580a7.png">
> 
> Hi @FaharAbbasRizvi, If pgAdmin is unable to use the OS password manager then it will use the Master password, this is expected behavior.

Hi @nikhil-mohite, We have logs for that right, if there is any exception when trying to use OS secret? We should check if this is expected by checking the underlying error first.

**Comment by FaharAbbasRizvi** [comment]
This functionality has been tested on the latest snapshot build:

https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-29

**Comment by 1Map** [comment]
The latest version does not work as I cannot get past the screen shown below.  I am on Windows 11 and, YES, the master password I type is correct.

<img width="653" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/1152458/d560e1d8-30f5-4e8a-90bb-627312c7f392">

**Comment by gpchelkin** [comment]
On KDE (I use Ubuntu with KDE5 aka Kubuntu) KDE Wallet is used as main default keyring.
And [dbus-python](https://pypi.org/project/dbus-python) module needs to be installed as per https://github.com/jaraco/keyring:
> KDE4 & KDE5 [KWallet](https://en.wikipedia.org/wiki/KWallet) (requires [dbus](https://pypi.python.org/pypi/dbus-python))

I had got an error in pgAdmin 4 7.3 desktop, telling me that it is not installed. So I did this:
```bash
sudo -s
cd /usr/pgadmin4/venv
bin/pip install dbus-python
```
And it works now. So I guess it should be enough to just add [dbus-python](https://pypi.org/project/dbus-python) to  https://github.com/pgadmin-org/pgadmin4/blob/master/requirements.txt

I also added this to my `~/.config/python_keyring/keyringrc.cfg` just in case:
```ini
[backend]
default-keyring=keyring.backends.kwallet.DBusKeyring
```
