### ISSUE TITLE
Backup on Win10 fails with: environment can only contain strings (RM #7459)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5133]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7459***
*Originally created by **Chris M** at 2022-06-08 07:23:05 UTC.*

1. Download and install pgAdmin 4 v6.10 (released June 2, 2022) for *Windows*
2. Connect to a pg14 db instance
3. Try to backup a entire database via right click -> _Backup_
4. Set a _Filename_ and press _Backup_
5. Error: *"environment can only contain strings"*

It seems like there is something broken on Windows with the backup function.

**Comment by pravesh-sharma** [comment]
Resolved in snapshot build - https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-10-10/
