### ISSUE TITLE
ERD Tool: Cannot read properties of undefined (reading 'attnum') (RM #7463)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5137]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7463***
*Originally created by **Jan Vidar Nordstrand** at 2022-06-09 13:25:45 UTC.*

Error message appeared when adding a comment to a table. Error message persists if comment is removed but changes seem to be saved even if window does not close when selecting save in the table editor window. Deleting the table and recreating it without the comment does not produce the error message.
The table that triggers the error message is 'measurement_unit' in the attached .pgerd

**Comment by adityatoshniwal** [comment]
This is fixed in #5342. Closing.

**Comment by PixelP4radise** [comment]
Error message appears when trying to save a table that has a link(in this case foreign key) associated to another table that was deleted or after deleting a link without going into the foreign key constraint.

Maybe not related to this. Some tables become impossible to delete.

Solution:
When deleting a link and/or table delete all associated. Like when deleting a table deletes all foreign keys that reference it.

![Image](https://github.com/user-attachments/assets/b14315f0-d7a1-495a-97f4-1c61d78287ca)
