### ISSUE TITLE
The message "EDB Big Animal authentication process is in progress" is displayed on the Big Animal credentials screen if the user closes the URL with the crossbar without authentication (RM #7472)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5144]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7472***
*Originally created by **Fahar Abbas** at 2022-06-14 09:24:51 UTC.*

Build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-06-13/

Steps

1. open Deploy cloud instance
2. Select EDB Big Animal 
3. Click Next
4. Click on Click here to authenticate yourself to EDB Big Animal
5. Big Animal authentication URL opened
6. Close this URL with a crossbar
7. Message "EDB Big Animal authentication process is in progress" displayed <-

Please note that the user has close the authentication URL and this is not expected behavior 

Expected Result:
----------------
We should add a timer of 1 minute, add new authentication, or close the EDB big animal registration.

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-19/
