### ISSUE TITLE
Error displayed "SERVICE UNAVAILABLE - Connection to the server has been lost." if user clicks on ERD tool through right click on template0 database (RM #7477)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5149]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7477***
*Originally created by **Fahar Abbas** at 2022-06-16 07:38:32 UTC.*

Builds:
-----
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-06-16/

Steps
-----
1.  Go into preferences
2. Click on Display 
3. select  Show system objects? and Show template databases? option
4. Click on templates
5. Right Click and generate ERD 
6. Error displayed SERVICE UNAVAILABLE - Connection to the server has been lost.

Please note that if the user clicks on the templates database and SELECT Tool, the ERD tool option is disabled

Expected:
----------
ERD Tool should be disabled through right-click or an Error message should be updated like ERD tool is not supported with template0 database.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-10-24/
