### ISSUE TITLE
nwjs is requesting kdewallet upon pgAdmin startup (RM #7488)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5155]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7488***
*Originally created by **Thomas Landauer** at 2022-06-20 14:59:32 UTC.*

When starting pgAdmin, I'm getting a confirmation window from KDE Plasma, saying that "nwjs" is requesting to open "kdewallet". But pgAdmin obviously doesn't really require anything from there, since I can just close the window and everything works fine.

I have disabled pgAdmin's master password as I explained at https://askubuntu.com/a/1150779/800003

pgAdmin 6.10, but already present in previous versions

**Comment by yogeshmahajan-1903** [comment]
pgAdmin now uses the OS secret storage for save the server password. Hence pgAdmin will require access to  kdewallet.
