### ISSUE TITLE
Setting encoding doesn't work (RM #7491)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5157]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7491***
*Originally created by **Felipe Eduardo Morschel** at 2022-06-21 11:00:00 UTC.*

I've created a StackOverflow question (https://stackoverflow.com/questions/71783353/pgadmin-iv-charmap-codec-cant-decode-byte-0x8d-in-position-8773-character-m) and as of right now could not find a solution.
As written there:

I'm using pgAdmin IV (version 5.7) now because of my job, previously I only had used pgAdmin III. My problem is that I have already set the charset correctly with +_set client_encoding = 'Win1252';_+ and when I execute a select, this error still appears. I'm connected to the same database with both (the database I'm linking to is Postgres 9.5). When I do the same select with pgAdmin III (+_select * from ws.ws_log order by id desc limit 100;_+), I get all the data correctly.
When I run show server_encoding on the database I receive *WIN1252*
Error when running the select mentioned above on pgAdmin IV:
  _'charmap' codec can't decode byte 0x8d in position 8773: character maps to <undefined>_

Adrian Klaver (https://stackoverflow.com/users/7070613/adrian-klaver) tried to "set the client_encoding under the _Parameters_ tab of the database _Properties_ and it seemed to ignore that setting" as he said in a comment under my question just before suggesting creating an issue here. 

I'm new here so any help/guidance would be appreciated.

**Comment by nikhil-mohite** [comment]
No response from the author, hence closing it.

**Comment by FMorschel** [comment]
Note: I missed that this was transferred over to here.

More details (data example) here: https://github.com/dbeaver/dbeaver/issues/22100#issuecomment-1919575883

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
