### ISSUE TITLE
PSQL Tool psqlrc problem (RM #7503)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5167]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7503***
*Originally created by **Yasuaki Fukaishi** at 2022-06-24 06:22:40 UTC.*

When different users start PSQL Tool at the same time, the user who started it first will run psqlrc of the user who started it later.

When only UserA begins, UserA's psqlrc work.
UserA's $PSQLRC
<pre><code class="shell">
db=> \! echo $PSQLRC
/var/lib/pgadmin/storage/usera_email.com/.psqlrc
</code></pre>

But this case, other user's psqlrc had run.
# UserA clicks PSQL Tool.
# UserB clicks PSQL Tool before UserA's PSQL begins.
# UserA's PSQL run UserB's psqlrc.

UserA's $PSQLRC
<pre><code class="shell">
db=> \! echo $PSQLRC
/var/lib/pgadmin/storage/userb_email.com/.psqlrc
</code></pre>

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
