### ISSUE TITLE
Blank datatable result when fast execute (RM #7510)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5172]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7510***
*Originally created by **Fin aiko** at 2022-06-27 09:21:14 UTC.*

I try run fast execute query, press F5 as fast I can, datatable result will blank even simple query or less data
but sometime show normally

---
Version
6.10
Application Mode
Desktop
Current User
pgadmin4@pgadmin.org
NW.js Version
0.65.0
Browser
Chromium 102.0.5005.61
Operating System
Linux-5.4.0-121-generic-x86_64-with-glibc2.29

**Comment by anilsahoo20** [comment]
Issue is not reproducible.

Tested and verified on pgAdmin 4 v8.5 : https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.5/macos/

Environment: macOs ventura 13.5.1
Package: arm64
