### ISSUE TITLE
The continue/start button is  enabled if the user stop the Debugger for the procedure only (RM #7531)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5188]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7531***
*Originally created by **Fahar Abbas** at 2022-07-06 07:26:56 UTC.*

Snapshot build:
---------------
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-07-06/

Steps
1. Go into the procedure node(list_emp)
2. Right Click> Debugging and Click on Debug.
3. Click on the Continue button
4. Only Continue/Start and Help button enabled
5. All Buttons are enabled
6. Click on the Stop button
7. Continue/start button is still enabled<- Issue
8. If again click on Continue/Start button
9. Now Continue/Start button is disabled

Please note that such a scenario is not reproducible in a function node

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build :
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-25/
