### ISSUE TITLE
UI rendering issue (RM #7553)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5206]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7553***
*Originally created by **Zach Smith** at 2022-07-15 12:18:34 UTC.*

The 'register server' dialogue is behind the 'no options' notice. Screenshot attached.

This issue is in dpage/pgadmin4:6.11

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
