### ISSUE TITLE
Performance regression on Firefox after opening any Dashboard (RM #7556)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5208]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7556***
*Originally created by **Edoardo Codeglia** at 2022-07-18 20:03:57 UTC.*

I am encountering a quite annoying bug on Firefox 102 + pga4 6.11 which will start using a lot of cpu whenever a dashboard is opened. This keeps happening even after leaving the dashboard tab since the refreshing still happens in background.

How to reproduce:
1. Open pgadmin4
2. Connect to any DB
3. Open the dashboard and let the graph load
4. Open the query editor and start writing

What should happen:
Beautiful stress-free typing experience

What happens:
Every second the typing gets delayed
Connecting to more than one server makes it even worse.

Additional info:

Firefox trace: https://share.firefox.dev/3OfpGF6

From Marker Chart -> Jank you can see all the typing events are delayed by up to half a second.
_updateDatasets seems to take the most to run.

**Comment by anilsahoo20** [comment]
Chart.js is replaced with uPlot.
