### ISSUE TITLE
Query tool (Alt+Shift+Q) create new Tab with wronq user (RM #7558)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5210]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7558***
*Originally created by **Mikhail Konopko** at 2022-07-20 13:46:03 UTC.*

1.	First step - click on icon "Query tool"
result - in new tab select user return "postgres" and in connection string [db name]/postgres@[server]

2.	Second step - change connection to user jooq_user
result select user return "jooq_user" and in connection string [db name]/jooq_user@[server]

3.	Third step - Query tool (Alt+Hift+Q)
result - in new tab select user return "postgres" but in connection string [db name]/jooq_user@[server]

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
