### ISSUE TITLE
High CPU usage when in idle (RM #7560)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5211]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7560***
*Originally created by **Tom Boettger** at 2022-07-21 14:41:51 UTC.*

It looks like the dashboard panel uses a lot of CPU (and also network). I am using Chromium and inspected the CPU and network utilization with the built-in task manager (shift+esc). It utilizes around 3-5 times as much CPU than my favorite music streaming service which also runs in the browser.

When I start the dashboard panel, the CPU usage increases from around 3% to about 40-70%. When I remove the dashboard panel, the CPU usage does not drop again and stays at the same level. I guess that's a bug. And also, I think that the dashboard should not have such an excessive CPU usage just to display some graphs every second.

I run pgadmin from the `dpage/pgadmin4:latest` docker image with my browser on version 103.

**Comment by Bouke** [comment]
CPU usage for me spikes to ~70%, burning through my battery. From the upstream bug it seems that the issue was introduced with v3 of the charts library. If this is the case, could we simply downgrade to v2 to fix the issue in pgadmin?

**Comment by adityatoshniwal** [comment]
@Bouke You can disable the graphs from File -> Preferences -> Dashboards -> Display -> Show Graphs till the time the issue is fixed.

**Comment by khushboovashi** [comment]
Ref: https://github.com/chartjs/Chart.js/issues/10073

**Comment by anilsahoo20** [comment]
Chart.js is replaced with uPlot.
