### ISSUE TITLE
Toast message box did not hide (very annoying and cannot continue working) (RM #7561)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5212]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7561***
*Originally created by **Vy Donhu** at 2022-07-22 04:21:44 UTC.*

pgAdmin version 6.11 on Windows 11 pro x64.

pgAdmin rans inside Docker container.

Run docker-compose up for running

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-28/
