### ISSUE TITLE
in Query Editor: Seach and Replace Text Editor (RM #7606)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5249]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7606***
*Originally created by **FERHAT YILDIRIM** at 2022-08-12 06:03:32 UTC.*

Use Ctrl + Shift + F key combination then open seach and replace editor.
The selected text does not appear on the search edit.
Also, I can't directly to write Tab character in the editor that opens. To do this, I have to type the ascii character. Alt + 09

**Comment by FaharAbbasRizvi** [comment]
If the user types any word in find and tries to delete it, the query tool crash, and the user has to relaunch the pgadmin4.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-10-03/
