### ISSUE TITLE
[UI] Change ownership - After changing the ownership of shared server, select server group show error at UI. (RM #7607)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5250]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7607***
*Originally created by **Nikhil Mohite** at 2022-08-12 08:36:38 UTC.*

Mode: Server Mode.
OS: Centos 7.
Version: Snapshotbuild(V6.12) [https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-08-12/yum/]
Steps:
# Create 3 users User-A, User-B & User-C, and create a shared server with user-A.
# Login using User-C, and Try to delete User-A, It will show a change ownership dialog.
# Select User-B in change ownership and click on Change.
# Now click the Save button on the user management dialog.
# Now In the browser tree select the shared server group, and it shows the error dialog PFA.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest candidate build for v6.14
