### ISSUE TITLE
Remove Alertify completely from pgAdmin (RM #7619)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5260]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7619***
*Originally created by **Akshay Joshi** at 2022-08-17 07:29:04 UTC.*

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-19/
