### ISSUE TITLE
[UI] User management - Filter users should work if user try to add new user (RM #7620)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5261]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7620***
*Originally created by **Nikhil Mohite** at 2022-08-17 08:40:54 UTC.*

Mode: Server mode.
OS: Fedora 35
pgAdmin version: (v6.12) snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-08-17/yum/
Steps:
# Open User Management dialog
# Add search text in search input-box
# Now click on Add row button to add a new user.
# Filter text is present in the search input box but in the table all records are visible.
# Expected behavior: Only filtered rows should be visible in the table.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
---
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-27/
