### ISSUE TITLE
[UI] User management - Create internal user allow case sensitive email address (RM #7621)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5262]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7621***
*Originally created by **Nikhil Mohite** at 2022-08-17 10:10:40 UTC.*

Mode: Server mode
Steps:
# Open user management dialog
# Add 2 new internal users with email addresses *user-a@test.com* with Administrator role and *user-A@test.com* with User role
# It allows saving these users.
# If try to login with *user-A@test.com*, it will login as *user-a@test.com* with the Administrator role, it login with the first matching email address.
# Expected behavior - Email address check should be case insensitive, and should not allow adding 2 different users with the same email with different letter casing.

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-26/yum/
