### ISSUE TITLE
Schema diff doesnt pickup change in column GRANTs (RM #7631)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5269]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7631***
*Originally created by **Pocin Pocin** at 2022-08-21 16:41:32 UTC.*

<pre>
# create database source;
# create database target;
# create role bob;
# \c source
source# create table foo(id text, amount text);
source# grant select, insert(id, amount), update(amount) on foo to bob;

source# \c target
target# create table foo(id text, amount text);
target# grant select, insert(id, amount), update(id, amount) on foo to bob;

</pre>
the difference is the @UPDATE@ on @target.public.foo.amount.id@

the diff is empty but i would expect something along the lines of

<pre>
GRANT INSERT(id), UPDATE(id) on foo to bob;
</pre>

Or is the safe thing to do here REVOKE ALL on foo from bob; and apply the GRANTS from the `target`?

**Comment by nikhil-mohite** [comment]
Resolved, Verified on snapshot build [https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-20/](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-20/)
OS: macOS Monterey 12.6
Mode: Desktop

**Comment by nikhil-mohite** [comment]
Resolved, Verified on candidate build 6.21: https://developer.pgadmin.org/builds/2023-03-01-1/
OS: macOS Monterey 12.6
Mode: Desktop
