### ISSUE TITLE
On startup, autofocus on master password input only on windows (RM #7635)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5273]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7635***
*Originally created by **Yogesh Mahajan** at 2022-08-23 09:30:50 UTC.*

**Comment by yogeshmahajan-1903** [comment]
As pgAdmin 4 uses os secrets, master password dialogue will not appear. Hence closing the issue.
