### ISSUE TITLE
Improve error message shown on clicking cloud server for which deployment is in progress. (RM #7636)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5274]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7636***
*Originally created by **Yogesh Mahajan** at 2022-08-23 11:28:56 UTC.*

Improve error message shown on clicking cloud server for which deployment is in progress.
Currently error shown - 'cloud Server information not available'.

We can also change the error message and add Please check the processes tab for more information or cloud deployment is in progress

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the Candidate build for v6.14.
