### ISSUE TITLE
XSS vulnerability issue displayed  if server name contains javascript (RM #7639)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5277]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7639***
*Originally created by **Fahar Abbas** at 2022-08-24 13:22:03 UTC.*

Steps
1. create a new server with ><iframe src=javascript:alert(document.domain)>    name
2. server created
3. Connect with this server
4. go into the database postgres
5. Click on PSQL
6. XSS vulnerability found

**Comment by Florian-Sabonchi** [comment]
Still open? Can repoduce

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-10-17/
