### ISSUE TITLE
Auto completetion on tables with quotes ... (RM #7643)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5281]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7643***
*Originally created by **Richard Brown** at 2022-08-25 16:34:45 UTC.*

On pgAdmin 6.12 (and 6.13) the auto complete is not working for me.  This is pgAdmin running on Windows 11, and querying against tables with capitals (that require quoting).

On pgAdmin 6.11, if when auto completion appears for tables with quotes, I am presented with a list:
!pgadmin6_11.auto_complete1.png!

Once I start to type, the list is reduced:
!pgadmin6_11.auto_complete3.png!

And finally, I can either select an option manually, or hit tab once it's narrowed to a single selection:
!pgadmin6_11.auto_complete2.png!

On pgAdmin 6.12, typing makes the list disappear, and does not narrow it down (unless there are lowercase-only tables without quotes).

**Comment by akshay-joshi** [comment]
@Richard Brown 

Can you please test this issue on tomorrow's snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/

**Comment by FlukeFan** [comment]
Sure.  I can confirm the problem still exists on the nightly 2022-11-07 build.

I'll wait for 2022-11-08, then test it (with commit 398675597a5df7a3d7ccd95896bf95d7e4be756d).

**Comment by akshay-joshi** [comment]
@FlukeFan 

I have tested the latest code and the issue is not reproducible. Just FYI  

<img width="848" alt="Screenshot 2022-11-07 at 6 03 49 PM" src="https://user-images.githubusercontent.com/1632882/200312923-e77a26be-487d-457e-9ba4-c16d071de758.png">
<img width="671" alt="Screenshot 2022-11-07 at 6 10 24 PM" src="https://user-images.githubusercontent.com/1632882/200312948-dfd0e1ed-fcef-4868-affc-e1cd1589ff9f.png">

**Comment by akshay-joshi** [comment]
Hi @FlukeFan 

Do you have 6.15 already installed on the machine? The new version of **psutil** is released yesterday only. I tried with fresh installation on the Windows 10 machine and working fine. 

We will investigate more about the **psutil** issue.

**Comment by FlukeFan** [comment]
Hi @akshay-joshi,

I previously had the 6.15 from 2022-11-07 installed.  I've now uninstalled pgAdmin, and re-installed the 2022-11-08 version.

It now starts up correctly again, but I'm still seeing the problem with the intelli-sense (with the 2022-11-08 version).

I uninstalled (the 2022-11-08 version), and re-installed 6.11, and the intelli-sense is working for me again.

Is there anything else I can do to help re-create the problem?

Cheers,
    Richard

**Comment by akshay-joshi** [comment]
Hi @FlukeFan 

This is strange. The same test case I have performed and working fine for us. 
Two options:
1. Either share the DDL of the schema and table.
2. Connect on zoom to have a screen-sharing session.

**Comment by FlukeFan** [comment]
My guess is the schema you showed me in your screenshots looks appropriate for testing.

How shall we progress option 2?

**Comment by FlukeFan** [comment]
Sure, any time after 7:30am GMT (1pm IST) should be OK for me.

**Comment by akshay-joshi** [comment]
Topic: Issue #5281 Discussion
Time: Nov 10, 2022 01:00 PM Mumbai, Kolkata, New Delhi

Join Zoom Meeting
https://enterprisedb.zoom.us/j/94029571852?pwd=aDhxUEcrb21OekZUNXFib28yTHptdz09
Meeting ID: 940 2957 1852
Passcode: 272251

**Comment by FlukeFan** [comment]
Perfect.

In the meantime, I have created a VM in Hyper-V, with PG and pgAdmin (2022-11-08).

I created a database using:

```
-- DROP DATABASE IF EXISTS "pgAdminIntellisenseTest";

CREATE DATABASE "pgAdminIntellisenseTest"
    WITH
    OWNER = postgres
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
```

I created a schema with a couple of tables:

```
CREATE SCHEMA IF NOT EXISTS "Schema1"
    AUTHORIZATION postgres;

CREATE TABLE IF NOT EXISTS "Schema1"."Table1"
(
    "Id" bigint NOT NULL,
    CONSTRAINT "PK_Table1" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Schema1"."Table1"
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS "Schema1"."table2"
(
    "Id" bigint NOT NULL,
    CONSTRAINT "PK_table2" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Schema1"."table2"
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS "Schema1"."Table3"
(
    "Id" bigint NOT NULL,
    CONSTRAINT "PK_Table3" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Schema1"."Table3"
    OWNER to postgres;
```

The intellisense was still not working on that instance.  I could not filter the capitalised tables.

Does that help at all?

**Comment by FlukeFan** [comment]
Looking back at the screenshots you showed me, I see the drop-down list, but not the auto-completion working.

If you type 'D' (or 'd') for example, does the DoubleQuote table stay in your dropdown?

**Comment by akshay-joshi** [comment]
@FlukeFan 

I have tested the DDL that you mentioned. When we type **SELECT * FROM "Schema1".** and check the IntelliSense it shows all the tables, but when we type 'T' (or 't') it shows only "**table2**".

But if we type a double quote before typing 'T' (or 't') it shows all the tables. Example **SELECT * FROM "Schema1"."T**

FYI, We have referred to the code of **pgcli** and the same scenario working there so I think it's a Bug, we will need to investigate. 

I think we don't need a screen-sharing session now so should I cancel the Zoom meeting?

**Comment by FlukeFan** [comment]
Hi @akshay-joshi ,

Yes, I think we don't need the zoom meeting now.

Of note, the way the 6.11 version worked was you could type upper or lower case letters (but no quotes), and the list was filtered case-insensitively.  (Perhaps the case-insensitive part is the key here?)

Cheers,
    Richard

**Comment by nikhil-mohite** [comment]
This issue is resolved. 
Verified on:
OS: macOS (Monterey 12.6)
OS: Windows 10 (21H1)
pgAdmin build (v6.16): https://developer.pgadmin.org/builds/2022-11-16-1/

We also found 2 autocomplete issues if a user uses " in query please check #5551 for more information.
