### ISSUE TITLE
Ensure that the tooltips are consistent throughout the entire application (RM #7657)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5293]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7657***
*Originally created by **Akshay Joshi** at 2022-08-31 09:00:39 UTC.*

The entire application should follow the same tooltip (like the Query Tool)

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-27/
