### ISSUE TITLE
Table gets reset to top when changing Query Tool Tabs (RM #7660)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5296]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7660***
*Originally created by **Don Redford** at 2022-08-31 21:06:25 UTC.*

In a query tool tab after I have done a query I scroll down to a record and highlight it to use the data in another tab. I go to the other query tool tab and when I come back to the original tab the table is reset to the top. This is very annoying having to re-scroll down to the record I want to look at.

**Comment by pravesh-sharma** [comment]
Tested on latest code and is fixed.
