### ISSUE TITLE
pgAdmin 4 v6.13 Docker does not work (RM #7662)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5298]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7662***
*Originally created by **Vy Donhu** at 2022-09-01 07:56:39 UTC.*

pgAdmin 4 v6.13 Docker does not work (Docker PostgreSQL 14.5 and pgAdmin 4 version 6.13)

**Comment by nikhil-mohite** [comment]
Hi Vy Donhu,
Your Docker Compose file specifies 8080 for the external port, not port 80. `8080:5050` should be `80:5050`

**Comment by adityatoshniwal** [comment]
No response from user, closing.
