### ISSUE TITLE
v6.13 breaks using PostgreSQL v9.6 (unable to view list of tables/functions/sequences/etc) (RM #7667)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5303]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7667***
*Originally created by **Adrian Heath** at 2022-09-02 08:49:34 UTC.*

Trying to open list of tables/functions/etc fails with one of the following error messages

Error Message:ERROR:  column rel.relispartition does not exist
LINE 9:     AND NOT rel.relispartition
                    ^

Error Message:ERROR:  column "backend_type" does not exist
LINE 16:     backend_type,
             ^

I realise PostgreSQL v9.6 is now end of life/unsupported but a comment in the 6.13 release notes that versions upto and including 9.6 was no longer supported would have saved me the bother of upgrading from 6.12.

We are in the process of migrating our services from our own servers running in a third party data centre to a cloud based solution so do not plan to upgrade the version of PostgreSQL on our machines.

Can a note be added to the release notes stating earliest version of PostgreSQL supported.

**Comment by FaharAbbasRizvi** [comment]
An older server warning is still displayed if the user connects with the EPAS/PG 9.6 server and then connects with any supported server pg/EPAS 10 onwards.

**Comment by akshay-joshi** [comment]
Unable to reproduce the issue. Fahar has tested for an older version and reopened the issue.

**Comment by FaharAbbasRizvi** [comment]
This issue is resolved and not able to reproduce the issue again as discussed with Akshay.
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-19/
