### ISSUE TITLE
Add HA options to AWS deployment (RM #7668)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5304]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7668***
*Originally created by **Aditya Toshniwal** at 2022-09-02 11:39:00 UTC.*

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-28/
