### ISSUE TITLE
TAB doesn't move in the data editor text fields to the next field, making input extremely slow (RM #7671)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5307]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7671***
*Originally created by **Peter Gervai** at 2022-09-03 15:36:29 UTC.*

Since a few versions it is impossible to enter [text] data without clicking (and it is excessively slow and annoying now), since TAB will  not save and advance string fields anymore. I have to find the mouse, click the button OK, then move back to the keyboard again and again.

I have tried a lot of keyboard combos to no avail. How can I enter data with keyboard only? Text fields especially. And I would appreciate the combo for advance-right as well as advance-down... both is pretty common usage.

It worked in older versions, more or less. 
Entering a number usually worked immediately and tab and enter as well. 
Entering a string is not possible unless clicked or pressed enter first, but then enter inserts linefeed (it's okay, but still I'd prefer shift+enter or ctrl+enter as every other web applications do), and TAB used to move to the next field on the right.

**Comment by adityatoshniwal** [comment]
To be tested with #7705.

**Comment by pravesh-sharma** [comment]
All issues have been addressed except the enter key still puts a new line. We can save on the enter key press and use ctrl/cmd+enter for a new line.

**Comment by anilsahoo20** [comment]
Shift+Enter for new line and Enter will save the text for the Data output cell.

Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-03/
Package: arm64, pip wheel
Environment: macOs Ventura 13.5.1
