### ISSUE TITLE
Cannot set a data field "default", makes it impossible to copy tuples with PK or SERIAL (RM #7672)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5308]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7672***
*Originally created by **Peter Gervai** at 2022-09-03 15:38:22 UTC.*

I see no way to set a data field in the editor to "default". The problem is that copying anything with PK or SERIAL will fill it with duplicate data and if I simply empty the fields it become NULL instead of "none", and the update fails.

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-28/
