### ISSUE TITLE
Can not install pgadmin4 by pip because of psutil 5.9.2 bug (RM #7675)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5311]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7675***
*Originally created by **Taehyun Hwang** at 2022-09-05 06:38:15 UTC.*

Currently, pgAdmin4 requires psutil==5.* in requirements.txt (https://github.com/postgres/pgadmin4/blob/master/requirements.txt)

However, the following psutil 5.9.2 updates prevent pgadmin4 from installing by pip. It crashes.

It should be fixed using Flask-SocketIO <= 5.9.1

Thanks.

**Comment by akshay-joshi** [comment]
@ Taehyun

We have pinned the version of psutil to 5.9.3 and Flask-SocketIO<=5.2.0. Please test on the next release which will be on coming Thursday 17th.

**Comment by khushboovashi** [comment]
No response from the author.

**Comment by HwangTaehyun** [comment]
Hi! I'm @HwangTaehyun!
Thank you!
Is there some contribution list of pgadmin? I would like to know that!
@akshay-joshi @khushboovashi
