### ISSUE TITLE
Constraints creation dialog column names do not refresh after changing names in the table (RM #7677)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5313]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7677***
*Originally created by **Alexey Karaev** at 2022-09-05 08:29:45 UTC.*

PostgreSQL version: 14.5
Operating system:   Windows 10
Description:       

I want to report an issue PostreSQL 14.5, pgAdmin 6.12. OS: Win 10.

1) Table created with 2 columns: column1 and column2
2) Opened dialog Constraints -> Create -> FOREIGN KEY...
3) Opened the list of the column names in the dialog Columns -> Local
Column.
4) Saw the correct names: column1 and column2.
5) Closed the dialog without saving
6) Renamed column names into: fk_column1, fk_column2
7) Repeated the steps 2 and 3
8) Saw the OLD names: column1 and column2 - they are not refreshed

The only way to refresh that column names inside constraints dialog is:
reopen the database (close and open pgAdmin).

Thank you for your support.

**Comment by nikhil-mohite** [comment]
No response from the author, hence closing it.
