### ISSUE TITLE
pgAdmin 4 Server Could Not be Contacted (RM #7679)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5315]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7679***
*Originally created by **Joseph Piarulli** at 2022-09-05 16:31:12 UTC.*

Cannot open pgAdmin4 v6.13
PostGre v.14 installed no issues
Windows 11 64-bit
Desktop Mode
Unchecked fixed port number (after trying standard port numbers 5432, 5433, 6432, etc).
Fatal error does not allow application to start up at all, installed older version of pgAdmin (v5.2 to maintain useability).

**Comment by nikhil-mohite** [comment]
No response from the author, hence closing it.
