### ISSUE TITLE
schema permission (RM #7681)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5317]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7681***
*Originally created by **Roshan aby** at 2022-09-06 05:42:49 UTC.*

As far as I can see using psql, when a role (let's just say the role name is TEMP) does not have permission for USAGE on the schema, TEMP cannot view the schema but pgadmin somehow can view it, and also the column datatypes of each table by expanding one table -> expanding columns and right-clicking on each column and going to its properties. Not only that, it can even view the constraints, triggers, and indexes present in the table. So if Postgres is not giving information about it, where exactly pgadmin is scooping up the information?

**Comment by nikhil-mohite** [comment]
No response from the author, hence rejecting it.
