### ISSUE TITLE
UI is acting weird with graphs (RM #7682)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5318]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7682***
*Originally created by **Roshan aby** at 2022-09-06 06:15:34 UTC.*

i just upgraded my pgadmin from 6.8 to 6.12 and the DASHBOARD is acting weird with its graphs
here is the video link : https://youtu.be/W8538wB-UaM      (this is a unlisted video, so you need the link to view it)

**Comment by nikhil-mohite** [comment]
No response from the author, hence rejecting it.
