### ISSUE TITLE
slow query run (RM #7685)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5320]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7685***
*Originally created by **Roshan aby** at 2022-09-06 18:15:20 UTC.*

even for a simple statement for a very small table like
<pre><code class="sql">
select * from table_name;
</code></pre>
takes like 10 to 30 seconds which when done in psql gets done in couple of milliseconds
i noticed it today when i upgraded pgadmin from version 6.8 to version 6.12.
In the pic uploaded, you can see that the execution time even for this small table is more than 3 seconds which dont make sense as when i did simliar stuff in psql, it was in fraction of a second.

**Comment by nikhil-mohite** [comment]
No response from the author, hence rejecting it.

**Comment by ianturton** [comment]
Not sure why you would need a video of pgadmin being slow - I can confirm that upgrading to 6.12 really slows down simple queries. This is on windows, I don't see the same Ubuntu (though that's 6.14). My feeling it that the autocomplete gets stuck some times but that is just a guess as I get `loading` windows getting left behind sometimes.
