### ISSUE TITLE
Make notistack notification with a fixed height and width (RM #7686)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5321]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7686***
*Originally created by **Akshay Joshi** at 2022-09-07 08:56:38 UTC.*

Alos, check if we can show a progress bar to show timeouts.

**Comment by akshay-joshi** [comment]
We have set the max width. Having fixed width and height are not possible due to the dynamic content of the message, hence closing.
