### ISSUE TITLE
Dialog flashes up as PgAdmin Starts (RM #7689)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5322]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7689***
*Originally created by **Paul Farry** at 2022-09-08 03:43:34 UTC.*

When first launching the application on windows a dialog pops up for a fraction of a second. (see attached image)

Not sure what it was so I screen recorded to actually get the frame.

Please see the attached image. 

It doesn't seem to impact the running of the application, just a little disconcerting.

**Comment by PaulFarry** [comment]
I believe I may have 2 version of pgadmin installed, but I only use 1 of them, the default one installed with postgres itself, and then the one I install and maintain, I've never used the pgadmin from Postgres directly afaik (not even sure how I can choose to not install that one)

**Comment by PaulFarry** [comment]
This solved the issue. Thanks
