### ISSUE TITLE
Restroring the dvdrental database (RM #7694)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5324]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7694***
*Originally created by **HELEN OGWU** at 2022-09-09 15:13:18 UTC.*

I get the error when trying toi restore  Utility file not found. Please correct the Binary Path in the Preferences dialog'

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
