### ISSUE TITLE
Partitioned table generate script (RM #7700)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5330]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7700***
*Originally created by **Tiziano Abbatelli** at 2022-09-12 15:03:12 UTC.*

Hi, 
in a partition if select Scripts => Create script i have this message "argument of type 'Response' is not iterable"
Can't view the table DDL

I have the issue with 4+6.13 version in old 4.-6.12 version the tools works

**Comment by akshay-joshi** [comment]
[PartitionedTable.sql.zip](https://github.com/pgadmin-org/pgadmin4/files/9597284/PartitionedTable.sql.zip)

**Comment by akshay-joshi** [comment]
Hi @Tiziano

Still, I am not able to reproduce the issue and after analyzing your DDL it is not a partitioned table.

**Comment by adityatoshniwal** [comment]
No response from user, closing.
