### ISSUE TITLE
pgadmin4 fails to start (RM #7701)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5331]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7701***
*Originally created by **- -** at 2022-09-12 22:21:12 UTC.*

I'm on Ubuntu 22.04.1 LTS. When i install pgadmin4 i get version 6.13
When i start pgadmin after a while i get

The pgAdmin 4 server could not be contacted:
<pre>
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/flip101/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - USER: flip101
  - LANGUAGE: en_GB:en
  - LC_TIME: en_US.UTF-8
  - XDG_SESSION_TYPE: x11
  - SHLVL: 0
  - HOME: /home/flip101
  - DESKTOP_SESSION: ubuntu-xorg
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GTK_MODULES: gail:atk-bridge
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - LC_MONETARY: en_US.UTF-8
  - MANAGERPID: 4298
  - SYSTEMD_EXEC_PID: 4763
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 3472371
  - IM_CONFIG_PHASE: 1
  - MANDATORY_PATH: /usr/share/gconf/ubuntu-xorg.mandatory.path
  - LOGNAME: flip101
  - _: /usr/bin/dbus-update-activation-environment
  - rvm_bin_path: /home/flip101/.rvm/bin
  - JOURNAL_STREAM: 8:42094
  - DEFAULTS_PATH: /usr/share/gconf/ubuntu-xorg.default.path
  - IRBRC: /home/flip101/.rvm/rubies/ruby-2.6.3/.irbrc
  - RUBY_VERSION: ruby-2.6.3
  - XDG_SESSION_CLASS: user
  - USERNAME: flip101
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - WINDOWPATH: 2
  - PATH: /home/flip101/.rvm/gems/ruby-2.6.3/bin:/home/flip101/.rvm/gems/ruby-2.6.3@global/bin:/home/flip101/.rvm/rubies/ruby-2.6.3/bin:/home/flip101/.cargo/bin:/home/flip101/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/flip101/.rvm/bin
  - PAPERSIZE: letter
  - SESSION_MANAGER: local/flip101-Lenovo-IdeaPad-S340-14IWL:@/tmp/.ICE-unix/4740,unix/flip101-Lenovo-IdeaPad-S340-14IWL:/tmp/.ICE-unix/4740
  - INVOCATION_ID: ed4dc891906b42f0a3134fb74904f475
  - XDG_RUNTIME_DIR: /run/user/1000
  - LC_ADDRESS: en_US.UTF-8
  - XDG_MENU_PREFIX: gnome-
  - DISPLAY: :1
  - MY_RUBY_HOME: /home/flip101/.rvm/rubies/ruby-2.6.3
  - LANG: en_GB.UTF-8
  - LC_TELEPHONE: en_US.UTF-8
  - XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - XAUTHORITY: /run/user/1000/gdm/Xauthority
  - XDG_SESSION_DESKTOP: ubuntu-xorg
  - XMODIFIERS: @im=ibus
  - SSH_AGENT_LAUNCHER: gnome-keyring
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - SHELL: /bin/zsh
  - LC_NAME: en_US.UTF-8
  - QT_ACCESSIBILITY: 1
  - GDMSESSION: ubuntu-xorg
  - rvm_prefix: /home/flip101
  - GEM_HOME: /home/flip101/.rvm/gems/ruby-2.6.3
  - LC_MEASUREMENT: en_US.UTF-8
  - GPG_AGENT_INFO: /run/user/1000/gnupg/S.gpg-agent:0:1
  - LC_IDENTIFICATION: en_US.UTF-8
  - rvm_version: 1.29.9 (latest)
  - GJS_DEBUG_OUTPUT: stderr
  - QT_IM_MODULE: ibus
  - QT_QPA_PLATFORM: xcb
  - GEM_PATH: /home/flip101/.rvm/gems/ruby-2.6.3:/home/flip101/.rvm/gems/ruby-2.6.3@global
  - PWD: /home/flip101
  - XDG_DATA_DIRS: /usr/share/ubuntu-xorg:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu-xorg:/etc/xdg
  - LC_NUMERIC: en_US.UTF-8
  - LC_PAPER: en_US.UTF-8
  - rvm_path: /home/flip101/.rvm
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 42941
  - PGADMIN_INT_KEY: b61273d3-e5ca-49c3-8aca-6e6634e1148c
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.007 Sec
Failed to launch pgAdmin4. Error:
Error: spawn /usr/pgadmin4/venv/bin/python3 ENOENT
</pre>

symlink: /usr/pgadmin4/venv/binpython3 -> /usr/bin/python3.8
is not working because python3.8 is not installed.

pgadmin4 package depends on pgadmin4-server package
pgadmin4-server package depends on python3 (not specifically python3.8)

when i fix the symlink to point to installed version /usr/bin/python3
/usr/bin/python3 is in turn a symlink pointing to /usr/bin/python3.10

i get the following error while starting pgadmin

<pre>
Total spawn time to start the pgAdmin4 server: 0.004 Sec
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgAdmin4.py", line 38, in <module>
    import config
  File "/usr/pgadmin4/web/config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 23, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'
</pre>

All the environment variables etc are still the same except for: GIO_LAUNCHED_DESKTOP_FILE_PID, PGADMIN_INT_PORT, PGADMIN_INT_KEY

**Comment by oussemabhouri** [comment]
Did you find a solution for it?
