### ISSUE TITLE
[UI][ERD]: Getting error on saving the table in ERD (RM #7709)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5333]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7709***
*Originally created by **Nikhil Mohite** at 2022-09-14 05:49:11 UTC.*

Steps:
1. Generate ERD for a database having few tables.
2. Try to add a new column to an existing table.
3. Go to edit column -> Variables tab -> Add variable
4. Click on the Save button.
5. Getting error *Cannot read properties of undefined (reading 'getLinks')* __
6. But the column is getting added even getting error on the dialog and the dialog is not getting closed

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
----
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-19/
