### ISSUE TITLE
'ServerManager' Error Assist

### ISSUE THREAD

**Issue by csatpute** [pgadmin-org/pgadmin4#5335]
hello team,
I have installed the pgadmin on my system , but when trying to connect to our server I m getting below error. however , while trying to connect using old version 12, using psql shell Im able to connect it, can you please advise whats the issue for it
 'ServerManager' Object has no attribute 'user_info'

**Comment by nikhil-mohite** [comment]
Hi @csatpute ,
what is the version of PostgreSQL, pgAdmin you are using?

**Comment by adityatoshniwal** [comment]
No response from user, closing.
