### ISSUE TITLE
"save results to file " before the data transfer is completed, there is no prompt

### ISSUE THREAD

**Issue by daydayup863** [pgadmin-org/pgadmin4#5338]
pgadmin4 6.13  

SERVER_MODE=on

When the download results too large, about 100MB,  clicking "save results to file" it seems that there is no job, I think, when I click the button, there should be a prompt

pgadmin4 5.6 will display Downloading Results...

**Comment by FaharAbbasRizvi** [comment]
I have tested with 166 MB and now downloading result is displayed properly.
