### ISSUE TITLE
uwsgi + nginx db backup does not work (RM #7580)

### ISSUE THREAD

**Issue by ravermeister** [pgadmin-org/pgadmin4#5340]
Hi, 
unfortunately this issue is still not resolved. 
As I had mentioned earlier the python path isn't correctly determined here: https://github.com/pgadmin-org/pgadmin4/blob/5a5da5f7206805168d0822ed7ea1efe5c4c5212b/web/pgadmin/misc/bgprocess/processes.py#L269
The Scenario of this issue is as follows:
1. python is installed **system wide**
```shell
[raver7@finlay ~]$ which python
alias python='python3.9'
	/usr/bin/python3.9
```
2. The UWSGI installation was done via `pip install --user uwsgi` 
```shell
[raver7@finlay ~]$ ls -l /home/raver7/.local/bin/
insgesamt 1260
-rwxrwxr-x. 1 raver7 raver7     223 22. Aug 10:51 pip
-rwxrwxr-x. 1 raver7 raver7     223 22. Aug 10:51 pip3
-rwxrwxr-x. 1 raver7 raver7     223 22. Aug 10:51 pip3.9
-rwxrwxr-x. 1 raver7 raver7 1276576 17. Jul 08:57 uwsgi

```
3. pgadmin3 was installed using a virtualenv in `/home/raver7/share/pgadmin`:
```shell
[raver7@finlay ~]$ source /home/raver7/share/pgadmin/bin/activate
(pgadmin) [raver7@finlay ~]$ echo $VIRTUAL_ENV
/home/raver7/share/pgadmin

``` 
4. So the *correct* Python path would be inside the virtualenv folder:
```
(pgadmin) [raver7@finlay ~]$ ls -l $VIRTUAL_ENV/bin
insgesamt 88
-rw-r--r--. 1 raver7 raver7 1904  2. Jun 12:02 activate
-rw-r--r--. 1 raver7 raver7  853  2. Jun 12:02 activate.csh
-rw-r--r--. 1 raver7 raver7 1993  2. Jun 12:02 activate.fish
-rw-r--r--. 1 raver7 raver7 8834  2. Jun 12:02 Activate.ps1
-rwxrwxr-x. 1 raver7 raver7  237 16. Sep 09:57 alembic
-rwxrwxr-x. 1 raver7 raver7  245 16. Sep 09:57 chardetect
-rwxrwxr-x. 1 raver7 raver7  238 16. Sep 09:57 email_validator
-rwxrwxr-x. 1 raver7 raver7  232 16. Sep 09:57 flask
-rwxrwxr-x. 1 raver7 raver7 1719 16. Sep 09:57 jp.py
-rwxrwxr-x. 1 raver7 raver7  237 16. Sep 09:57 mako-render
-rwxrwxr-x. 1 raver7 raver7  268 17. Jul 09:25 normalizer
-rwxrwxr-x. 1 raver7 raver7  240 16. Sep 09:58 pgadmin4
-rwxrwxr-x. 1 raver7 raver7  245 27. Aug 11:18 pip
-rwxrwxr-x. 1 raver7 raver7  245 27. Aug 11:18 pip3
-rwxrwxr-x. 1 raver7 raver7  245 27. Aug 11:18 pip3.9
-rwxrwxr-x. 1 raver7 raver7  246 16. Sep 09:57 pybabel
drwxrwxr-x. 2 raver7 raver7   31 16. Sep 09:57 __pycache__
lrwxrwxrwx. 1 raver7 raver7    9  2. Jun 12:02 python -> python3.9
lrwxrwxrwx. 1 raver7 raver7    9  2. Jun 12:02 python3 -> python3.9
lrwxrwxrwx. 1 raver7 raver7   18  2. Jun 12:02 python3.9 -> /usr/bin/python3.9
-rwxrwxr-x. 1 raver7 raver7  245 16. Sep 09:57 qr
-rwxrwxr-x. 1 raver7 raver7  240 16. Sep 09:57 sqlformat
-rwxrwxr-x. 1 raver7 raver7  242 16. Sep 09:57 sshtunnel
-rwxrwxr-x. 1 raver7 raver7  232  2. Jun 12:03 wheel
```

I've tested with the mentioned Version https://ftp.postgresql.org/pub/pgadmin/pgadmin4/snapshots/2022-09-12/pgadmin4-6.13-py3-none-any.whl and I get the Error which correctly says it couldn't find the python executable at the determined directory:
![image](https://user-images.githubusercontent.com/6666963/190588244-786215b2-ad19-4494-a337-3ad7c7c04ffd.png)

In my Opinion the best solution would be to check if pgadmin is running from within a **virtualenv** by checking if the System Environment Variable  `$VIRTUAL_ENV` exists, and then for the existance of `$VIRTUAL_ENV/bin/python`

_Originally posted by @ravermeister in https://github.com/pgadmin-org/pgadmin4/issues/5230#issuecomment-1249063445_

**Comment by ravermeister** [comment]
as workaround I've symlinked the Python executable inside the uwsgi bin folder:
```shell
[raver7@finlay ~]$ ls -l .local/bin/
insgesamt 1260
-rwxrwxr-x. 1 raver7 raver7     223 22. Aug 10:51 pip
-rwxrwxr-x. 1 raver7 raver7     223 22. Aug 10:51 pip3
-rwxrwxr-x. 1 raver7 raver7     223 22. Aug 10:51 pip3.9
lrwxrwxrwx. 1 raver7 raver7      18 16. Sep 10:23 python -> /usr/bin/python3.9
-rwxrwxr-x. 1 raver7 raver7 1276576 17. Jul 08:57 uwsgi
```

**Comment by yogeshmahajan-1903** [comment]
Hi @ravermeister ,

Kindly add '--py-sys-executable' parameter while spawning pgadmin using uwsgi which overrides override sys.executable value. Unfortunately there is no way to get python environment value that is passed while spawning uwsgi process (using -H) in python script. 'VIRTUAL_ENV' is not found in os.environ.


`<user>@ubuntu:~$  /home/<user>/.local/bin/uwsgi --socket /tmp/pgadmin4_cmd.sock  --chmod-socket=666  --plugin python3   -H /usr/pgadmin4/venv  --wsgi-file /usr/pgadmin4/web/pgAdmin4.wsgi  --processes 1  --threads 25  --chdir /usr/pgadmin4/web/   --manage-script-name  --mount /pgadmin=pgAdmin4:app --py-sys-executable /usr/pgadmin4/venv/bin/python
`

**Comment by ravermeister** [comment]
I'll try and report back. Additionally I found this solution: https://stackoverflow.com/a/18021303

**Comment by ravermeister** [comment]
It works by adding `py-sys-executable = $(HOME)/share/pgadmin/bin/python` (`$(HOME)/share/pgadmin` is my virtualenv directory)

to my uwsgi config. Maybe it wood be a good idea to document that for the uwsgi howto: https://www.pgadmin.org/docs/pgadmin4/latest/server_deployment.html#nginx-configuration-with-uwsgi
