### ISSUE TITLE
Open URL Redirect Vulnerability

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#5343]
Currently, when pgAdmin is running in server mode and user opens the pgAdmin URL, it opens login page with redirect URL to /browser of pgAdmin using `next` param.
The vulnerability allows a remote attacker to redirect victims to arbitrary URL.

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the candidate build for v6.14

**Comment by marthasimons7777** [comment]
Thanks for fix it [👍](https://business-review.eu/tech/online/best-essay-paper-help-websites-in-2023-240014)
