### ISSUE TITLE
Log in to PgAdmin web interface with username and now with email.

### ISSUE THREAD

**Issue by xzizka** [pgadmin-org/pgadmin4#5348]
Hello,

I am trying to setup a PgAdmin in Kubernetes (Docker) using [official docker image](https://hub.docker.com/r/dpage/pgadmin4) version 6.13. 
I set the env variables like this:
```
export PGADMIN_DEFAULT_EMAIL='pg51-owner'
export PGADMIN_DEFAULT_PASSWORD='41R0d.....lg'
```
But when I try to log in, I see in the log the following error:
```
[2022-09-21 15:16:35 +0000] [86] [DEBUG] POST /authenticate/login
The email address is not valid. It must have exactly one @-sign.
```
I found, that there is a check for a [valid email](https://github.com/pgadmin-org/pgadmin4/blob/8459a45d72c31198191a9d612b7f1b43bb802fc3/web/pgadmin/authenticate/internal.py#L101) during the login process.

**Goal:** I want to be able to log in to PgAdmin using an username and not email address. 

Is it necessary to set something more, that the ENV variable `PGADMIN_DEFAULT_EMAIL`?

Thank you

**Comment by adityatoshniwal** [comment]
@xzizka It doesn't need to be an actual email id. It should be syntactically a valid email address. If the email Id doesn't exist then that's fine.
