### ISSUE TITLE
toast error notification shows for ~1 second

### ISSUE THREAD

**Issue by dangelsaurus** [pgadmin-org/pgadmin4#5364]
V6.14 Desktop, Windows 10 - issued a truncate via r**ight click -> truncate** while pg_dump was running. Of course the operation was blocked by the dump, however the toast notification displayed for less than 1 second. Not sure if this is just related to warning toast messages, as others seem to stick around.

**Comment by FaharAbbasRizvi** [comment]
This is  tested in the latest snapshot build:
