### ISSUE TITLE
pgAdmin 4 version 6.13, 6.14 on Windows: Cannot add new row.

### ISSUE THREAD

**Issue by donhuvy** [pgadmin-org/pgadmin4#5365]
pgAdmin 4 version 6.14 : Cannot add new row.

![add_new_row](https://user-images.githubusercontent.com/1328316/192124209-364d3424-4621-4338-afe5-d41ed1329407.png)

I also checked with version 6.13 . The quality of software is very bad, many bugs.

**Comment by adityatoshniwal** [comment]
@donhuvy You need to have a primary key in the table to allow adding, deleting or updating rows.
