### ISSUE TITLE
After click in different position, Context menu cannot hide.

### ISSUE THREAD

**Issue by donhuvy** [pgadmin-org/pgadmin4#5366]
Windows 11 pro x64, pgAdmin 4 version 6.13 , After click in different position, Context menu cannot hide.

![image](https://user-images.githubusercontent.com/1328316/192124425-30b9b5e0-5901-46b8-9f7a-be2f955ea0c5.png)

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-05/
