### ISSUE TITLE
pgAdmin4 v.6.14 - unable to start

### ISSUE THREAD

**Issue by kraynopp** [pgadmin-org/pgadmin4#5371]
Unable to start:

Traceback (most recent call last):
  File "/usr/local/bin/pgadmin4", line 5, in <module>
    from pgadmin4.pgAdmin4 import main
  File "/usr/local/lib/python3.9/dist-packages/pgadmin4/pgAdmin4.py", line 38, in <module>
    import config
  File "/usr/local/lib/python3.9/dist-packages/pgadmin4/config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/local/lib/python3.9/dist-packages/pgadmin4/pgadmin/__init__.py", line 28, in <module>
    from flask_login import user_logged_in, user_logged_out
  File "/usr/local/lib/python3.9/dist-packages/flask_login/__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "/usr/local/lib/python3.9/dist-packages/flask_login/login_manager.py", line 24, in <module>
    from .utils import (login_url as make_login_url, _create_identifier,
  File "/usr/local/lib/python3.9/dist-packages/flask_login/utils.py", line 13, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/usr/local/lib/python3.9/dist-packages/werkzeug/security.py)

pip list:

Package             Version
------------------- --------------
aeidon              1.9
alabaster           0.7.8
alembic             1.4.3.dev0
appdirs             1.4.4
apt-xapian-index    0.49
asn1crypto          1.4.0
atomicwrites        1.4.0
attrs               20.3.0
Automat             20.2.0
Babel               2.8.0
backcall            0.2.0
bcrypt              3.1.7
beautifulsoup4      4.9.3
blinker             1.4
Brlapi              0.8.2
Brotli              1.0.9
certifi             2020.6.20
chardet             4.0.0
click               7.1.2
colorama            0.4.4
configobj           5.0.6
constantly          15.1.0
cryptography        3.3.2
cupshelpers         1.0
cycler              0.10.0
dbus-python         1.2.16
decorator           4.4.2
defer               1.0.6
diff-match-patch    20200713
distro              1.5.0
distro-info         1.0
dnspython           2.0.0
docutils            0.16
email-validator     1.1.1
Endgame-Singularity 1.0
entrypoints         0.3
ExifRead            2.3.2
Flask               1.1.2
Flask-Babel         0.12.2
Flask-BabelEx       0.9.4
Flask-Compress      1.4.0
Flask-Gravatar      0.4.2
Flask-Login         0.5.0
Flask-Mail          0.9.1
Flask-Migrate       2.6.0
Flask-Paranoid      0.2.0
Flask-Principal     0.4.0
Flask-Security-Too  4.0.0
Flask-SQLAlchemy    2.1
Flask-WTF           0.14.3
fonttools           4.19.1
fs                  2.4.12
git-cola            3.9
html5lib            1.1
httplib2            0.18.1
hyperlink           19.0.0
idna                2.10
imagesize           1.2.0
importlib-metadata  1.6.0
incremental         17.5.0
iniconfig           0.0.0
iniparse            0.4
ipython             7.20.0
ipython-genutils    0.2.0
itsdangerous        1.1.0
jedi                0.18.0
jeepney             0.6.0
Jinja2              2.11.3
keyring             22.0.1
keyrings.alt        4.0.2
kiwisolver          1.3.1
l20n                4.0.0a1
libvirt-python      7.0.0
louis               3.16.0
lxml                4.6.3
Mako                1.1.3
Markdown            3.3.4
MarkupSafe          1.1.1
matplotlib          3.3.4
mock                4.0.3
mod-python          3.5.0
more-itertools      4.2.0
mpmath              0.0.0
multidict           5.1.0
notify2             0.3
numpy               1.19.5
olefile             0.46
packaging           20.9
parso               0.8.1
passlib             1.7.4
pbr                 5.5.0
pexpect             4.8.0
phply               1.2.5
pickleshare         0.7.5
Pillow              8.1.2
pip                 20.3.4
pluggy              0.13.0
ply                 3.11
polib               1.1.0
prompt-toolkit      3.0.14
py                  1.10.0
pyasn1              0.4.8
pyasn1-modules      0.2.1
pycairo             1.16.2
pycountry           20.7.3
pycryptodomex       3.9.7
pycups              2.0.1
pycurl              7.43.0.6
pyenchant           3.2.0
pygame              1.9.6
Pygments            2.7.1
PyGObject           3.38.0
PyHamcrest          1.9.0
pyinotify           0.9.6
pyOpenSSL           20.0.1
pyparsing           2.4.7
PyQt5               5.15.2
PyQt5-sip           12.8.1
PySimpleSOAP        1.16.2
pysmbc              1.0.23
pytest              6.0.2
pytest-arraydiff    0.3
pytest-doctestplus  0.9.0
pytest-remotedata   0.3.2
python-apt          2.2.1
python-dateutil     2.8.1
python-debian       0.1.39
python-debianbts    3.1.0
python-editor       1.0.3
python-Levenshtein  0.12.2
pytz                2021.1
pyxdg               0.27
QtPy                1.9.0
reportbug           7.10.3+deb11u1
reportlab           3.5.59
requests            2.25.1
requests-toolbelt   0.9.1
roman               2.0.0
ruamel.yaml         0.16.12
ruamel.yaml.clib    0.2.2
scipy               1.6.0
SecretStorage       3.3.1
service-identity    18.1.0
setuptools          52.0.0
simplegeneric       0.8.1
simplejson          3.17.2
six                 1.16.0
snowballstemmer     2.1.0
soupsieve           2.2.1
speaklater          1.4
Sphinx              3.4.3
SQLAlchemy          1.3.22
sympy               1.7.1
toml                0.10.1
traitlets           5.0.5
translate-toolkit   3.3.2
Twisted             20.3.0
ufoLib2             0.11.1
unattended-upgrades 0.1
urllib3             1.26.5
vobject             0.9.6.1
wcwidth             0.1.9
webencodings        0.5.1
Werkzeug            1.0.1
wheel               0.34.2
WTForms             2.2.1
xdg                 5
yarl                1.6.3
zipp                1.0.0
zope.interface      5.2.0

**Comment by kraynopp** [comment]
I'm sorry... I have added invalid pip list.

Correct pip list:
Package                 Version
----------------------- ---------
alembic                 1.7.6
Authlib                 0.15.5
azure-common            1.1.28
azure-core              1.24.2
azure-identity          1.9.0
azure-mgmt-core         1.3.1
azure-mgmt-rdbms        10.1.0
azure-mgmt-resource     21.0.0
azure-mgmt-subscription 3.0.0
Babel                   2.9.1
bcrypt                  3.2.0
bidict                  0.21.4
blinker                 1.4
boto3                   1.20.54
botocore                1.23.54
Brotli                  1.0.9
certifi                 2021.10.8
cffi                    1.15.0
chardet                 4.0.0
click                   8.0.3
cryptography            3.4.8
dnspython               2.2.0
email-validator         1.1.3
eventlet                0.33.0
Flask                   2.1.3
Flask-Babel             2.0.0
Flask-Compress          1.10.1
Flask-Gravatar          0.5.0
Flask-Login             0.5.0
Flask-Mail              0.9.1
Flask-Migrate           3.1.0
Flask-Paranoid          0.2.0
Flask-Principal         0.4.0
Flask-Security-Too      4.1.2
Flask-SocketIO          5.1.1
Flask-SQLAlchemy        2.5.1
Flask-WTF               1.0.0
greenlet                1.1.2
h11                     0.13.0
httpagentparser         1.9.2
idna                    2.10
importlib-metadata      4.12.0
isodate                 0.6.1
itsdangerous            2.0.1
Jinja2                  3.0.3
jmespath                0.10.0
ldap3                   2.9.1
Mako                    1.1.6
MarkupSafe              2.0.1
msal                    1.18.0
msal-extensions         0.3.1
msrest                  0.7.1
oauthlib                3.2.0
paramiko                2.9.2
passlib                 1.7.4
pgadmin4                6.14
Pillow                  9.0.1
pip                     20.3.4
portalocker             2.4.0
psutil                  5.9.0
psycopg2-binary         2.9.3
pyasn1                  0.4.8
pycparser               2.21
PyJWT                   2.4.0
PyNaCl                  1.5.0
pyotp                   2.6.0
python-dateutil         2.8.2
python-engineio         4.3.1
python-socketio         5.5.1
pytz                    2021.3
qrcode                  7.3.1
requests                2.25.1
requests-oauthlib       1.3.1
s3transfer              0.5.2
setuptools              52.0.0
simple-websocket        0.5.0
simplejson              3.17.6
six                     1.16.0
speaklater3             1.4
SQLAlchemy              1.4.31
sqlparse                0.4.2
sshtunnel               0.4.0
typing-extensions       4.3.0
ua-parser               0.10.0
urllib3                 1.26.8
user-agents             2.2.0
Werkzeug                2.1.2
wheel                   0.34.2
wsproto                 1.0.0
WTForms                 3.0.1
zipp                    3.8.1

**Comment by akshay-joshi** [comment]
Duplicates of #5285

pgAdmin's requirements.txt have the following:
Werkzeug==2.0.3; python_version <= '3.6'
Werkzeug==2.1.2; python_version >= '3.7'

**Comment by kraynopp** [comment]
/# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

/# pip list | grep Werkzeug
Werkzeug                2.1.2

/# pgadmin4 
Traceback (most recent call last):
  File "/usr/local/bin/pgadmin4", line 5, in <module>
    from pgadmin4.pgAdmin4 import main
  File "/usr/local/lib/python3.9/dist-packages/pgadmin4/pgAdmin4.py", line 38, in <module>
    import config
  File "/usr/local/lib/python3.9/dist-packages/pgadmin4/config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/local/lib/python3.9/dist-packages/pgadmin4/pgadmin/__init__.py", line 28, in <module>
    from flask_login import user_logged_in, user_logged_out
  File "/usr/local/lib/python3.9/dist-packages/flask_login/__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "/usr/local/lib/python3.9/dist-packages/flask_login/login_manager.py", line 24, in <module>
    from .utils import (login_url as make_login_url, _create_identifier,
  File "/usr/local/lib/python3.9/dist-packages/flask_login/utils.py", line 13, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/usr/local/lib/python3.9/dist-packages/werkzeug/security.py)

What's wrong? Reopen issue, please.
