### ISSUE TITLE
Why show the username and password when disabled

### ISSUE THREAD

**Issue by andyquinterom** [pgadmin-org/pgadmin4#5386]
I've been having a couple minor issues with some users that get confused with the disabled Username/Password login method. We use a SSO for pgAdmin so the user has to click on the bottom button instead of writing their email and password.

This is a question. Is it possible to automatically start OAuth2 when the user hits the homepage or is it impossible.

If it's not possible then perhaps we could do somethings like the following in the `login_user.html`.

```html
{% if not (config.OAUTH2 in config.AUTHENTICATION_SOURCES or config.KERBEROS in config.AUTHENTICATION_SOURCES) and config.AUTHENTICATION_SOURCES | length == 1 %}
    {{ render_username_with_errors(login_user_form.email, "text") }}
    {{ render_field_with_errors(login_user_form.password, "password") }}
    <button name="internal_button" class="btn btn-primary btn-block btn-login" type="submit" value="{{ _('Login') }}">{{ _('Login') }}</button>
{% endif %}
```

**Comment by andyquinterom** [comment]
![image](https://user-images.githubusercontent.com/51521150/193127034-c7118f0c-b223-459c-bf48-c3799ac327d4.png)

![image](https://user-images.githubusercontent.com/51521150/193127110-6c7f16c8-8761-416a-9976-b026382b0fd3.png)

**Comment by dpage** [comment]
I can see the utility in this, however we'd need to make it optional behaviour as some installations may use multiple authentication methods.

**Comment by pravesh-sharma** [comment]
Tested in latest code and is working.
