### ISSUE TITLE
pg admin not opening 

### ISSUE THREAD

**Issue by Dhruv-Rayat1** [pgadmin-org/pgadmin4#5391]
pgAdmin does not open, it keeps returning this error: `Failed to connect to the server: "Connection refused" - request URL: "http://127.0.0.1:42631/misc/ping?key=dc767950-d1d0-4871-b140-b9031bbc87e4"`

I am not sure as to what is causing this error my python version is: 3.10.7

Information:
- OS: Arch Linux
- Installed via yay (aur) `yay -S pgadmin4`
![image](https://user-images.githubusercontent.com/90363421/193445974-e19eca82-fefd-43d5-bbc7-cda38640a66c.png)

**Comment by dpage** [comment]
The mention of QCoreApplication at the top of your screenshot indicates that you are using a very old version of pgAdmin, that was never supported with Python 3.10, and hasn't been supported at all in a long time. Please upgrade to 6.14 - you may need to run it in Docker or similar as we don't actually support Arch Linux.
