### ISSUE TITLE
Problem installing pgadmin in Unbuntu 20.04.1

### ISSUE THREAD

**Issue by mdaljian** [pgadmin-org/pgadmin4#5393]
I am encountering an error installing pgadmin in Unbuntu 20.04.1, apparently caused by a problem with the public key not being available:  Err:5 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/jammy pgadmin4 InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8881B2A8210976F2

I followed the steps here, to install pgadmin: https://www.pgadmin.org/download/pgadmin-4-apt/

I encountered a problem at the first step, 
         sudo curl https://www.pgadmin.org/static/packages_pgadmin_org.pub > /etc/apt/trusted.gpg.d/packages_pgadmin_org.pub

![Screenshot from 2022-10-02 17-10-46](https://user-images.githubusercontent.com/45743602/193480320-f56aa49b-40e5-4836-91b0-3b45296f56c6.png)

Since I understand the curl to essentially be a copy, and the issue appearing to be a lack of permission in the folder, I added write permission to /etc/apt/trusted.gpg.d and copied packages_pgadmin_org.pub.

I then ran the second step, 
     sudo sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
and received an error at line 5, that the key is not available:

![Screenshot from 2022-10-02 17-08-07](https://user-images.githubusercontent.com/45743602/193480434-fb20b4f5-e89e-4f74-ad7e-befa040cf12b.png)

I also ran into a problem with the instructions for installing postgresql here: https://www.postgresql.org/download/linux/ubuntu/, because of the deprecation of apt-key, but this looks to be a different problem (though I would suggest that the instructions for postrgesql installation should be updated for Umbuntu 20.04 and later).

Thanks for any advice or adjustments that you can provide.

**Comment by yogeshmahajan-1903** [comment]
@mdaljian 
Please use below - command as of now to add key to system- 
sudo curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add

**Comment by dpage** [comment]
Yogesh and I looked at this, and we've now updated the instructions at https://www.pgadmin.org/download/pgadmin-4-apt/ and in the various READMEs generated for snapshot and QA builds.
