### ISSUE TITLE
Close all panels / Close other panels

### ISSUE THREAD

**Issue by wussup** [pgadmin-org/pgadmin4#5394]
Please add the possibility to close all panels / close other panels in the context menu of the panel here (like in Google Chrome):

![image](https://user-images.githubusercontent.com/4366584/193559558-7548f15f-2dc8-47bc-b7d2-415c245345b5.png)

**Comment by SmallhillCZ** [comment]
+1 and `close all panels to the right`

**Comment by adityatoshniwal** [comment]
This will be implemented with #6479.

**Comment by pravesh-sharma** [comment]
Feature implemented and working as expected. Verified on today's snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-11-02/yum/

OS - Rocky Linux 9.2 (Blue Onyx)
Mode - Desktop
