### ISSUE TITLE
Error while connecting to postgres db from local port forwarded

### ISSUE THREAD

**Issue by Martenz** [pgadmin-org/pgadmin4#5399]
pgAdmin version: 6.13

LOG error:
**ERROR: column "backend_type" does not exist LINE 16: backend_type, ^**

**Comment by adityatoshniwal** [comment]
@Martenz What is the PostgreSQL version you're using ?

**Comment by Martenz** [comment]
> @Martenz What is the PostgreSQL version you're using ?

Unfortunately quite old version that we might update .. but still in use. Thanks 

PostgreSQL 9.6.24 on x86_64-pc-linux-gnu, compiled by Debian clang version 12.0.1, 64-bit

**Comment by Martenz** [comment]
@adityatoshniwal 

We went back to PgAdmin ver. 6.10 and it works if it can help.
thanks again

**Comment by adityatoshniwal** [comment]
@Martenz pgAdmin has stopped support for PostgreSQL v9.6 and below from v6.13. You need to upgrade PG to v10 or more to use latest.

**Comment by Martenz** [comment]
@adityatoshniwal thanks for your time on this. I will ask to update.

regards
