### ISSUE TITLE
Won't start - Crashes after protracted wait with the opening screen.

### ISSUE THREAD

**Issue by GeraldPulver** [pgadmin-org/pgadmin4#5403]
I  occasionally,  find myself unable to start pgadmin4 on AWS.  It pauses for a good while after I start, then crashes with a Fatal Error.

Typically, after a while, I uninstall/reinstall the latest version and it works.  However, that might just be because time has passed.

Here's the lastest _Fatal Error_    (after two reinstalls, including removal of all traces from the system.
The pgAdmin 4 server could not be contacted:
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "D:\Users\pulver_g\AppData\Local\Programs\pgAdmin 4\v6\python\python.exe"
Runtime Config File: "D:\Users\pulver_g\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "D:\Users\pulver_g\AppData\Local\Programs\pgAdmin 4\v6\web\config.py"
Webapp Path: "D:\Users\pulver_g\AppData\Local\Programs\pgAdmin 4\v6\web\pgAdmin4.py"
pgAdmin Command: "D:\Users\pulver_g\AppData\Local\Programs\pgAdmin 4\v6\python\python.exe -s D:\Users\pulver_g\AppData\Local\Programs\pgAdmin 4\v6\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: D:\Users\pulver_g\AppData\Roaming
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_6164_FIQZCWWBYKISOCEN
  - CHROME_RESTART: NW.js|Whoa! NW.js has crashed. Relaunch now?|LEFT_TO_RIGHT
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: EC2AMAZ-0LG0IT7
  - ComSpec: C:\Windows\system32\cmd.exe
  - HOMEDRIVE: D:
  - HOMEPATH: \Users\pulver_g
  - LOCALAPPDATA: D:\Users\pulver_g\AppData\Local
  - LOGONSERVER: \\AWS-CF19296333
  - NUMBER_OF_PROCESSORS: 2
  - OS: Windows_NT
  - Path: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Amazon\cfn-bootstrap\;D:\Users\pulver_g\AppData\Local\Microsoft\WindowsApps;
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PGADMIN_INT_KEY: 7d9f89a0-3da6-4ee7-9d55-51a94c1f0f1b
  - PGADMIN_INT_PORT: 49570
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
  - PROCESSOR_LEVEL: 6
  - PROCESSOR_REVISION: 5507
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\AWS Tools\PowerShell\
  - PUBLIC: C:\Users\Public
  - SESSIONNAME: Console
  - STXHD_ACCOUNT_ID: 697148468905
  - STXHD_INSTANCE_ID: i-049622147c1c10bf1
  - STXHD_PERFORMANCE: SPEED
  - STXHD_REGION: us-east-1
  - SystemDrive: C:
  - SystemRoot: C:\Windows
  - TEMP: D:\Users\pulver_g\AppData\Local\Temp\1
  - TMP: D:\Users\pulver_g\AppData\Local\Temp\1
  - USERDNSDOMAIN: CORP.AMAZONWORKSPACES.COM
  - USERDOMAIN: CORP
  - USERDOMAIN_ROAMINGPROFILE: CORP
  - USERNAME: pulver_g
  - USERPROFILE: D:\Users\pulver_g
  - windir: C:\Windows
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.009 Sec
2022-10-05 14:27:28,258: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance.

 * Serving Flask app 'pgadmin' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

**Comment by adityatoshniwal** [comment]
Hi @GeraldPulver,

Can you please share OS details and system architecture (32/64 bit) ?

**Comment by nikhil-mohite** [comment]
No response from the author, hence closing it.
