### ISSUE TITLE
Cross-site scripting vulnerability

### ISSUE THREAD

**Issue by khushboovashi** [pgadmin-org/pgadmin4#5405]
pgAdmin 4 contains a cross-site scripting vulnerability at some places.

- Reproduction Steps:

  Go to Connection tab of "Object-Register-Server", enter 
  "<iframe srcdoc="<script>alert(document.domain)</script>">" 
  in the Host name/address field and press the "save" button.
  Then XSS occurs.

  Also, if you enter the above setting example in the path 
  entry field on the "Tools-Storage Manager" screen and try 
  to transition, XSS occurs in the same way.

  However, both are Self-XSS because external attacks are difficult.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-10-11/
