### ISSUE TITLE
Programmatic access to PgAdmin4 REST APIs?

### ISSUE THREAD

**Issue by flewellyn** [pgadmin-org/pgadmin4#5414]
This may be an odd question: I'm working on developing a web application that will create PostgreSQL databases and set them up for users.  I would like to use PgAdmin4 running in server mode (UI possibly in an iframe) to provide the users with a tool to manage their schemas and perform queries.  

Is there a way that I could programmatically access PgAdmin4's REST APIs to do things like add users, set up their server lists, and so forth?  I know that PgAdmin4 uses Flask internally, but how usable is that from outside of the PgAdmin4 UI?

**Comment by adityatoshniwal** [comment]
Hi @flewellyn,

Officially, pgAdmin team does not support external REST APIs for pgAdmin. However, you can check the browser console network tab and figure the out the APIs which are being used along with the required headers and may be try to mimic them.
