### ISSUE TITLE
UI is unusable with large SQL file

### ISSUE THREAD

**Issue by lukos** [pgadmin-org/pgadmin4#5415]
I am trying to execute a script in pgadmin 4 (6.14) but the UI is unusable with a file that is 450K lines long (roughly 450MB).

Navigating is really slow to react, e.g. page down takes around 500ms, trying to shift-select sections and it can take up to around 10-15 seconds to select around 2000 rows. Find-and-replace is really slow and unresponsive e.g. sometimes the find next button takes 10 seconds to update.

I tried to run the entire script and I get a string length error but since I don't get a line number, I cannot find out which insert is broken, which is why I tried to run a few thousand rows at a time using shift-select but it is too slow.

Starting to execute the entire script takes around 20 seconds and sometimes it just crashes and pgadmin exits.

WIndows 10 i7-6800K with 32GB RAM so not a system resources issue.

Maybe there are just some intelliense things I can disable to make it run properly but at the moment, I cannot use it.

**Comment by Florian-Sabonchi** [comment]
Hello do you have an sampel dump to repoduce

**Comment by lukos** [comment]
Sorry, the SQL I had contains lots of personal data so can't upload it. I doubt there is anything specific about the SQL, just the size of the file since it is slow and unresponsive even before I have attempted to execute anything. If anything, the SQL execution is very fast.

**Comment by simon-kempster** [comment]
Plain Text Mode may help (under Preferences / Query Tool / Editor), but that's a very big file.  You may be better off running psql.exe from the command line.

**Comment by pravesh-sharma** [comment]
Hi @lukos,

I tried with a 300 MB SQL file and pgAdmin works fine. Can you please try with the latest version of [pgAdmin 4](https://www.pgadmin.org/download/)

**Comment by khushboovashi** [comment]
No response from the author, closing the issue.
