### ISSUE TITLE
Cannot connect to server - How do I fix this?

### ISSUE THREAD

**Issue by rhjohnso9** [pgadmin-org/pgadmin4#5419]
![image](https://user-images.githubusercontent.com/114174663/194783585-de320074-8c49-4866-ac55-6c95135d305c.png)

**Comment by Olajide-jacobs** [comment]
![16653757879139133786163988622469](https://user-images.githubusercontent.com/115443188/194799058-d0ead00a-c8d7-4f85-9773-d763cf479d47.jpg)

Pls, help me too, how do I fix this?

**Comment by yogeshmahajan-1903** [comment]
@rhjohnso9 ,

Error indicates that either postgres is not running or port where postgres is running(5432) is refusing connection.
Can you please check connection with  psql is working.

**Comment by yogeshmahajan-1903** [comment]
Closing the issue as no response from author.
