### ISSUE TITLE
PG Admin - DB Crash

### ISSUE THREAD

**Issue by karthikeyanKulandaivelu** [pgadmin-org/pgadmin4#5423]
pgAdmin Version:  9.6
Running: In Server
Steps to Reproduce: Just shutdown the system which is running postgres : 9.6
Frequency: Very rare.
Operating system and version details: Windows 10

![IMG_0110](https://user-images.githubusercontent.com/104614806/195072833-1202e0b8-ffed-4bac-8a97-a54b3c10fd6e.jpg)
![IMG_0112](https://user-images.githubusercontent.com/104614806/195072850-2886669b-b80e-4063-a52a-febfb5829a72.jpg)

**Comment by dpage** [comment]
That error message comes directly from PostgreSQL and indicates there is corruption in your database. You will need to take corrective action to fix that, possibly a restore from backup. I would also test your storage devices to ensure they are functioning correctly.

There is nothing pgAdmin can do to fix (or cause) this I'm afraid.
