### ISSUE TITLE
Permissions issue with key file after uploading for SSL connection

### ISSUE THREAD

**Issue by tony-12345** [pgadmin-org/pgadmin4#5424]
Using pgAdmin in Web mode. I am trying to register a server connection using client certificates. In the SSL tab I have uploaded the necessary files and selected them. When attempting to connect, I get an error about the key file not having restricted permissions.

<img alt="unnamed" src="https://user-images.githubusercontent.com/93441228/195172391-ab929761-0472-408b-8769-35a7147e263b.png">

I can confirm, on the server in /var/lib/pgadmin/storage/[user]/, the permissions on the key file are not correct.

<img alt="unnamed (1)" src="https://user-images.githubusercontent.com/93441228/195172666-b0eeecd7-741e-48df-8e2b-4b5d1910556f.png">

The files appear to be getting 644 permissions, where as the [user] directory is getting 700 permissions. I can manually fix this for myself, but real users will not have access to change the permissions, nor should they have to. Is this a problem in the code where the file permissions are being set incorrectly? Or is this a configuration problem on my end? I have tried to search the source code to find how this is happening, but I'm out of my league.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build.
