### ISSUE TITLE
Filtered Rows not working

### ISSUE THREAD

**Issue by pravesh-sharma** [pgadmin-org/pgadmin4#5427]
Filtered Rows from browser toolbar is not working

Env details:-
MacOS 12.6

Issue occurring in latest code and latest snapshot build.

Attached screen recording for reference.

https://user-images.githubusercontent.com/111979571/195265919-4edbb562-bcb5-44b6-9383-5405a633a2af.mov

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-10-17/
