### ISSUE TITLE
Role's parameters are not shown in role properties dialog

### ISSUE THREAD

**Issue by koreiko** [pgadmin-org/pgadmin4#5429]
Parameters tab in riole's properties does not display the role's parameters.  in version 6.x
An example from version 4.x
![image](https://user-images.githubusercontent.com/35965264/195381749-2a47b496-4306-4d6f-8885-7ea7c8b5e398.png)

The same role in the same dialog version 6.x
![image](https://user-images.githubusercontent.com/35965264/195382002-ee4fe240-b40a-4d09-8e89-3ef720eeba48.png)

While the "script as" dialog shows this parameter in version 6.x:
![image](https://user-images.githubusercontent.com/35965264/195382529-d861118b-8155-464a-b223-9e0414491c04.png)

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots
