### ISSUE TITLE
pgAdmin on Kubernetes - "The referrer does not match the host"

### ISSUE THREAD

**Issue by anthonator** [pgadmin-org/pgadmin4#5432]
We're trying to host pgAdmin 6.14 on Kubernetes. The application deploys fine but after logging in we get the following error.

```
The referrer does not match the host.
174.138.117.142 - - [12/Oct/2022:20:16:13 +0000] "GET /misc/bgprocess/ HTTP/1.1" 400 128 "https://.../browser/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
2022-10-12 20:16:13,373: ERROR	pgadmin:	400 Bad Request: The referrer does not match the host.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 273, in protect
    self._error_response("The referrer does not match the host.")
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
```

We don't use Cloudflare but we do use Istio in our cluster and the application sits behind a self-hosted [Teleport](https://goteleport.com/) instance.

We've also set the environment variable `PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION` to `False`.

**Comment by anthonator** [comment]
We're using the `dpage/pgadmin4` Docker image.

**Comment by Kaczuc** [comment]
If you are using reverse proxy disable Cache Assets I had the same problem

**Comment by anthonator** [comment]
I was able to get around this by setting `PGADMIN_CONFIG_WTF_CSRF_ENABLED` to `False`. We have enough layers of security that I feel comfortable disabling this but definitely not a great solution. Had to dig into `Flask-WTF` to figure this out.

**Comment by nikhil-mohite** [comment]
Hi @anthonator,

Are you using a load balancer or dynamic IP for pgAdmin?

**Comment by anthonator** [comment]
We’re using Kubernetes so it naturally sits behind a load balancer. We use Istio for networking. We also use [Teleport](https://goteleport.com/) to access all internal tools.

**Comment by chimisu** [comment]
@anthonator I had the same issue,did u solve it?

**Comment by chimisu** [comment]
> If you are using reverse proxy disable Cache Assets I had the same problem

how to disable Cache Assets?I'm using nginx as the proxy.

**Comment by anthonator** [comment]
> @anthonator I had the same issue,did u solve it?

@chimisu  see https://github.com/pgadmin-org/pgadmin4/issues/5432#issuecomment-1276749272

**Comment by doebi** [comment]
I had the same issue when running `dpage/pgadmin4` behind a nginx reverse proxy with HTTP Basic Auth.

For the record if you want to achieve sth like that here is what you need to do:


#### ENV vars
Ensure these environment variables are set for your container:
```
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=somepassword
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
```

For some reason you cannot omit the EMAIL and PASSWORD although they will not be used, when you enable the `webserver`authentication.


#### pgadmin config
Create and mount a `config.py` with this content:
```
AUTHENTICATION_SOURCES = ['webserver']
WEBSERVER_AUTO_CREATE_USER = True
WEBSERVER_REMOTE_USER = 'X-Forwarded-User'
```
Details on the options and where to mount, can be found here: [The config.py File](https://www.pgadmin.org/docs/pgadmin4/latest/config_py.html#config-py)


#### nginx config
And lastly your nginx config should look something like this. The important part is the `X-Forwarded-User` header.
```
  auth_basic           "password required";
  auth_basic_user_file /etc/nginx/.htpasswd;

  location / {
    proxy_pass http://pgadmin;
    proxy_set_header X-Forwarded-User $remote_user;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
```

Took me a while to fiddle this information together...

**Comment by yogeshmahajan-1903** [comment]
@anthonator 
Hi, 
I am not able to reproduce the issue.
Here is yaml config where pgadmin is reverse proxies using Nginx.

`apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: pgadmin
spec:
 serviceName: pgadmin-service
 podManagementPolicy: Parallel
 replicas: 1
 updateStrategy:
   type: RollingUpdate
 selector:
   matchLabels:
     app: pgadmin
 template:
   metadata:
     labels:
       app: pgadmin
   spec:
     terminationGracePeriodSeconds: 10
     hostname: pgadmin
     containers:
       - name: pgadmin
         image: dpage/pgadmin4:6.16
         imagePullPolicy: Always
         env:
         - name: PGADMIN_DEFAULT_EMAIL
           value: user@domain.com
         - name: PGADMIN_DEFAULT_PASSWORD
           value: SuperSecret
         - name: PGADMIN_CONFIG_CONSOLE_LOG_LEVEL
           value: '10'
         - name: PGADMIN_CONFIG_LOGIN_BANNER
           value: '"Authorised users only!"'
         - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
           value: 'True'
         - name: PGADMIN_CONFIG_WTF_CSRF_ENABLED
           value: 'True'           
         ports:
         - name: http
           containerPort: 80
           protocol: TCP
         volumeMounts:
         - name: pgadmin-config
           mountPath: /pgadmin4/servers.json
           subPath: servers.json
           readOnly: true
         - name: pgadmin-data
           mountPath: /var/lib/pgadmin
     volumes:
     - name: pgadmin-config
       configMap:
         name: pgadmin-config
 volumeClaimTemplates:
 - metadata:
     name: pgadmin-data
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 3Gi

---

apiVersion: v1
kind: Service
metadata:
 name: pgadmin-service
spec:
 ports:
 - protocol: TCP
   port: 80
 selector:
   app: pgadmin
 type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;

          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /pgadmin {
            proxy_pass http://pgadmin-service/;
            proxy_http_version 1.1;
            proxy_set_header X-Script-Name /pgadmin;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
     labels:
       app: nginx
   spec:
     terminationGracePeriodSeconds: 10
     containers:
       - name: nginx
         image: nginx:1.16.1
         ports:
         - name: http
           containerPort: 80
           protocol: TCP
         volumeMounts:
           - name: nginx-conf
             mountPath: /etc/nginx/nginx.conf
             subPath: nginx.conf
             readOnly: true
     volumes:
       - name: nginx-conf
         configMap:
           name: nginx-conf
           items:
             - key: nginx.conf
               path: nginx.conf

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: nginx `

**Comment by adityatoshniwal** [comment]
@anthonator Try tweaking the below default config parameters of pgAdmin:
```
# Reverse Proxy parameters
# You must tell the middleware how many proxies set each header
# so it knows what values to trust.
# See https://tinyurl.com/yyg7r9av
# for more information.

# Number of values to trust for X-Forwarded-For
PROXY_X_FOR_COUNT = 1

# Number of values to trust for X-Forwarded-Proto.
PROXY_X_PROTO_COUNT = 1

# Number of values to trust for X-Forwarded-Host.
PROXY_X_HOST_COUNT = 0

# Number of values to trust for X-Forwarded-Port.
PROXY_X_PORT_COUNT = 1

# Number of values to trust for X-Forwarded-Prefix.
PROXY_X_PREFIX_COUNT = 0
```

**Comment by anthonator** [comment]
@adityatoshniwal I have tried tweaking those with no luck. Honestly, those properties feel very nebulous to me and I felt like I was just randomly making changes. I don't know how to accurately figure out those values.

**Comment by yogeshmahajan-1903** [comment]
@anthonator 
Can you please share yaml file to reproduce the issue?

**Comment by adityatoshniwal** [comment]
> @adityatoshniwal I have tried tweaking those with no luck. Honestly, those properties feel very nebulous to me and I felt like I was just randomly making changes. I don't know how to accurately figure out those values.
@anthonator I am assuming your pgAdmin is behind multiple levels of reverse proxy. By default pgAdmin is set to support one level of reverse proxy. If the level increases then you might face issues. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host). The settings are nothing but allowed levels. Try setting all the values to something like 4 or 5.

**Comment by adityatoshniwal** [comment]
> @adityatoshniwal I have tried tweaking those with no luck. Honestly, those properties feel very nebulous to me and I felt like I was just randomly making changes. I don't know how to accurately figure out those values.

@anthonator I am assuming your pgAdmin is behind multiple levels of reverse proxy. By default pgAdmin is set to support one level of reverse proxy. If the level increases then you might face issues. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host). The settings are nothing but allowed levels. Try setting all the values to something like 4 or 5

**Comment by pravesh-sharma** [comment]
No response from author hence closing.

**Comment by ai2ys** [comment]
I am facing the same Error when running pgadmin in GitHub codespaces.

Is there an option that works without setting `PGADMIN_CONFIG_WTF_CSRF_ENABLED=False`?

**Comment by NathanAP** [comment]
I know this is old but if this helps someone, it will be worth it:

```conf
server {
        listen 1234;

        location /pgadmin/ {
            auth_basic "Restricted Access";
            auth_basic_user_file /etc/nginx/.htpasswd;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;

            proxy_set_header X-Script-Name /pgadmin;
            proxy_set_header X-Scheme $scheme;
            proxy_pass http://pgadmin/;
            proxy_redirect off;
        }
    }
```

This is my load balancer (using dockerized nginx, pgadmin with GCP). The idea is that if I try to access `:5050/pgadmin` (or any other service like Grafana on 3000), it will be redirected to `:1234` (or any other you want), then ask for authentication and then send to the original path it should.

**Comment by n0099** [comment]
If you are using http(s) ports other than the one registered in [IANA](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt):
```
# workaround for non-standard port https://github.com/pgadmin-org/pgadmin4/issues/5432
proxy_set_header X-Forwarded-Port $server_port;
```
