### ISSUE TITLE
What happened to "Execute Script" in earlier pgAdmin versions?

### ISSUE THREAD

**Issue by marclallen** [pgadmin-org/pgadmin4#5436]
I don't know about anyone else, but I use my DB IDE for troubleshooting as well as other things.  Quite often, I'm adding debug-style selects inside a block of code to see intermediate results, etc.

Earlier versions of pgAdmin used to have an "execute script" type command which would send each command independently and put each result into it's own window.  

Why was that removed, and can it be put back?  Or am I missing something?

**Comment by dpage** [comment]
It's just "Scripts" in pgAdmin 4 (and if there's only one available, it will be directly on the context menu, not on a sub menu):

<img width="480" alt="Screenshot 2022-10-17 at 11 36 31" src="https://user-images.githubusercontent.com/316438/196156831-d8ae64d5-c26e-45f2-b418-36db8bd111ed.png">

**Comment by dpage** [comment]
Oh, wait - did you mean the scripting functionality in the Query Tool?

**Comment by marclallen** [comment]
Yes.  I'm sorry.. that's exactly what I meant.  The pgAdmin3 (I think) had the ability to execute everything in the window as separate requests and opened up tabs for each result set.

**Comment by dpage** [comment]
Execute (pg)Script in the query tool was for executing "meta" scripts that wrapped SQL: https://github.com/pgadmin-org/pgadmin3/blob/master/docs/en_US/pgscript.rst. For a (simple) example:

```
DECLARE @I;
SET @I = 0;
WHILE @I < 2
BEGIN
   SELECT version();

   SET @I = @I + 1;
END
```

It wouldn't open a result grid for each SELECT though. pgAdmin III didn't have that capability at all - and neither does pgAdmin 4, though it is on the TODO list.

**Comment by marclallen** [comment]
Huh?  :(  Drat.  So sorry for bothering you then.  I'd been a long time since I worked with PG, and maybe back then I used multiple tools.  I just don't recall.

I did look on the TODO and didn't see anything that seemed relevant, but there are a lot of items and I probably missed it.

I hope it's high-ish in the list, as I hate having to use multiple tools for this.

Thanks for taking the time.
