### ISSUE TITLE
Pg admin closing automatically when clicked on data output or message tab 

### ISSUE THREAD

**Issue by sh7-git-user** [pgadmin-org/pgadmin4#5437]
After data is loaded in data output tab if we click on message /data output tab the app automatically closes for pgadmin4 latest version

**Comment by nikhil-mohite** [comment]
Hi @sh7-git-user ,

Can you please share OS and pgAdmin version details, I am not able to reproduce the issue with the latest pgAdmin v6.14 on macOS.

**Comment by sh7-git-user** [comment]
Hi @nikhil-mohite 64 bit os windows 10-10.0.19044-SPO
pgadmin4 version 6.14

**Comment by nitram9** [comment]
As of pgAdmin v4.9, there is a new default setting that automatically closes the "Object Explorer" sidebar when looking at a query. This can be disabled by going to **File >> Preferences >> Miscellaneous >> User Interface >> Layout**

Switching from **Workspace** to **Classic** reverts to the <v4.9 behavior. 
The different options are described as follows:

> Choose the layout that suits you best. pgAdmin offers two options: the Classic layout, a longstanding and familiar design, and the Workspace layout, which provides distraction free dedicated areas for the Query Tool, PSQL, and Schema Diff tools.


![Image](https://github.com/user-attachments/assets/ef09562b-74f4-49e4-bfe4-9b7960f04f54)
