### ISSUE TITLE
Geometry Viewer map icon deactivates (Windows)

### ISSUE THREAD

**Issue by anthonydb** [pgadmin-org/pgadmin4#5446]
Environment: Windows 11, PostgreSQL 15.0, pgAdmin 6.14. Installed via EDB installer.

While working with geo data/PostGIS using pgAdmin, I've encountered a situation where the map icon that appears atop a geo column in the results grid is not clickable, and thus the Geometry Viewer does not launch and display the map.

I can fix the problem by shutting down and restarting pgAdmin. In that case, when I rerun the same query, the map icon becomes clickable and launches the viewer as expected.

However, I notice that subsequently in my session (and I don't know what actions trigger this behavior), the map icon again becomes unclickable, requiring another pgAdmin restart to fix. This is new behavior and I have noticed it only on Windows at this point.

**Comment by FaharAbbasRizvi** [comment]
@anthonydb I am not able to reproduce the issue on Windows 11, Can you please try the latest release and let us know?

**Comment by anthonydb** [comment]
@FaharAbbasRizvi 

This issue appears to have resolved. Tested with PostgreSQL 15.1 and pgAdmin 6.18. 

Thanks!
