### ISSUE TITLE
Merge https://github.com/EnterpriseDB/pgadmin4-treeview to pgadmin4

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#5449]
Keeping this as a fork has no added advantage. In fact, it only increases efforts to make any change in the pgAdmin tree as all the devs do not have permission to make changes.
This should be part of pgAdmin repo.

**Comment by adityatoshniwal** [comment]
@dpage There is no upstream. The upstream you're talking of is just a demo repo. The original react-aspen repo is not the the upstream here.

**Comment by adityatoshniwal** [comment]
@dpage The upstream repo here is - https://github.com/zikaari/react-aspen-demo. And not the original react-aspen lib.

**Comment by dpage** [comment]
Hmm, OK. So are you proposing a full integration, or simply vendorising the code? I would be against vendorising it - if we're doing that, it's more beneficial to the wider world for us to just move it to a public repo.

**Comment by adityatoshniwal** [comment]
@dpage Not vendorising.  https://github.com/zikaari/react-aspen-demo is for reference on how react-aspen can be used. We've directly forked it initially. But the code can be moved to pgAdmin now.

**Comment by dpage** [comment]
OK, feel free to submit a PR then :-p

**Comment by adityatoshniwal** [comment]
This is done.
