### ISSUE TITLE
Document the contents of servers.json

### ISSUE THREAD

**Issue by mgedmin** [pgadmin-org/pgadmin4#5452]
https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html says

> PGADMIN_SERVER_JSON_FILE
> 
> Default: /pgadmin4/servers.json
> 
> Override the default file path for the server definition list. See the /pgadmin4/servers.json mapped file below for more information.

and then

> /pgadmin4/servers.json
>
> If this file is mapped, server definitions found in it will be loaded at launch time. This allows connection information to be pre-loaded into the instance of pgAdmin in the container. Note that server definitions are only loaded on first launch, i.e. when the configuration database is created, and not on subsequent launches using the same configuration database.

but it doesn't document the format of the server definitions.

Doing a search for 'servers.json' on the docs site finds only a changelog page with a link to an issue about correcting the servers.json pathname in the documentation.

I cannot believe that the format is not documented anywhere, so I must be bad at searching.  Can you please update this page to link to the servers.json format documentation?

**Comment by adityatoshniwal** [comment]
@mgedmin Its documented here - https://www.pgadmin.org/docs/pgadmin4/latest/import_export_servers.html#json-format

**Comment by adityatoshniwal** [comment]
I am reopening to link the json format link in the container deployment page.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the candidate build.
