### ISSUE TITLE
Bad URL redirection after authentication

### ISSUE THREAD

**Issue by harmin-parra** [pgadmin-org/pgadmin4#5454]
I want to access pgadmin through this URL `http://localhost/` instead of   `http://localhost/pgadmin4`

1. Modify files `/etc/apache2/conf-available/pgadmin4.conf` and `/etc/apache2/conf-enabled/pgadmin4.conf` with the following content :

```
WSGIDaemonProcess pgadmin processes=1 threads=25 python-home=/usr/pgadmin4/venv
WSGIScriptAlias / /usr/pgadmin4/web/pgAdmin4.wsgi

<Directory /usr/pgadmin4/web/>
    WSGIProcessGroup pgadmin
    WSGIApplicationGroup %{GLOBAL}
    Require all granted
</Directory>
```

2. Restart apache

3. Open browser at `http://localhost`

4. Get authenticated

Result;
After authentication, I get redirected to an error web page at `http://localhost/pgadmin4`

**Comment by adityatoshniwal** [comment]
@harmin-parra  You'll need to change the `/usr/pgadmin4/web/pgAdmin4.wsgi` file as well. Try removing below line
```
os.environ['SCRIPT_NAME'] = '/pgadmin4'
```

**Comment by adityatoshniwal** [comment]
Reopening this. pgAdmin4.wsgi will be replaced on every release, so changing it to fix the issue is not appropriate.

**Comment by khushboovashi** [comment]
Fix didn't work for RHRL 9. Apache version 2.4.53.

**Comment by yogeshmahajan-1903** [comment]
This issue is fixed and verified. Redirection issue after failed login is not due to this, hence reopening #6704
