### ISSUE TITLE
Search objects improvement (column "parent object")

### ISSUE THREAD

**Issue by ecerichter** [pgadmin-org/pgadmin4#5458]
In the “search object” window, would be nice to add “Parent” object reference.
For instance, in the prt below, one cannot tell at the first sight that column belongs to what table:

![image](https://user-images.githubusercontent.com/2746089/196928821-e32694f0-3968-4903-8ef0-56c3350519e8.png)

IMHO, would be nice to have a “Parent” coumn in table above.

Regards,
ER

**Comment by adityatoshniwal** [comment]
This actually looks like a bug to me. The browser path should show the complete path of the object on the tree, which naturally will include the parents.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-11-07/
