### ISSUE TITLE
no email and password setup

### ISSUE THREAD

**Issue by matteonicoli93** [pgadmin-org/pgadmin4#5459]
Hi everyone,

I install pgadmin4 on python from "pip install pgadmin4" (pgadmin4-6.15) on windows 10 from anaconda env.
When I run "pgadmin4" from the terminal, it runs but doesn't ask me to setup email and password.
The process starts nominally and I can reach the page on the browser but can not perform the login.
How can I fix or setup it afterward?

Thanks

**Comment by yogeshmahajan-1903** [comment]
Hi,

Can you please check if db file already exist at location - '/var/lib/pgadmin'. If yes, it means initial configuration has been already in place.

**Comment by adityatoshniwal** [comment]
@matteonicoli93 On windows it should be in `%APPDATA%/pgadmin4`

**Comment by matteonicoli93** [comment]
Hi guys,

thanks in advance:)
I find out only the following db file "C:\Users\{username}\AppData\Roaming\pgadmin\pgadmin4.db".
Should I delete it? but if I delete it, doesn't crash afterward, and can I run it again as usual?

**Comment by adityatoshniwal** [comment]
@matteonicoli93 pgAdmin will re-create the DB file just like new installation.
