### ISSUE TITLE
Password not stored for shared servers

### ISSUE THREAD

**Issue by fire2** [pgadmin-org/pgadmin4#5460]
On a clean installation of PgAdmin with LDAP authentication in server mode, based on the official Docker image version 6.15 I have the following issue:

1) Add a shared server as admin. Log out.
2) Login as an unprivileged user, set server Username under Properties > Connection.
3) Try to connect inserting the password and saving it ("Save password" checkbox) -> it works.
4) Disconnect server (or logout) then re-connect to server, the following error shows:

<img width="751" alt="Screenshot 2022-10-21 at 09 46 27" src="https://user-images.githubusercontent.com/7990315/197144001-2ae97f3f-9643-40fc-89e8-6745a253bcb2.png">

Note: this works fine for normal servers created by the unprivileged user, passwords are stored and not asked for again. The issue only occurs with shared servers (created by admin).

**Comment by net-expertise** [comment]
Same issue with Oauth authentication

**Comment by bputt-e** [comment]
same problem with webserver auth

**Comment by yogeshmahajan-1903** [comment]
@fire2 , @net-expertise  @bputt-e 
I could not reproduce the issue with 6.18 release. Could you please test with latest release once ?

**Comment by fire2** [comment]
> @fire2 , @net-expertise @bputt-e I could not reproduce the issue with 6.18 release. Could you please test with latest release once ?

I just tried on version 6.18 and issue persists, only the error message is now different: 
<img width="740" alt="Screenshot 2022-12-23 at 11 44 03" src="https://user-images.githubusercontent.com/7990315/209322668-1c7fabc0-40a2-4ee3-b50a-dabb9c659b2d.png">

**Comment by adityatoshniwal** [comment]
@fire2 This looks similar to https://github.com/pgadmin-org/pgadmin4/issues/5487. The fix will be available in v6.19.

**Comment by akshay-joshi** [comment]
Tested with source code working fine.
