### ISSUE TITLE
Allow adding custom CA to docker container

### ISSUE THREAD

**Issue by frenos** [pgadmin-org/pgadmin4#5462]
I have a Homelab running with a custom CA that is not universally trusted.
When trying to setup login with OAuth2 to my keycloak service pgAdmin is complaining about a self-signed certificate in the chain.
It works when I inherit from the dockerimage and add my custom ca.

I propose to add an option to the official docker image to allow mounting a custom ca certificate.
A possible solution could look like this:
- establish a path in the container for the new ca cert, for example `/custom-ca.crt`
- add another step to `entrypoint.sh` checking if `/custom-ca.crt` exists. If true, copy cert to `/usr/local/share/ca-certificates/` and run `update-ca-certificates`.

**Comment by yogeshmahajan-1903** [comment]
@frenos Try sending the environment variable PGADMIN_CONFIG_CA_FILE to the docker image.
PGADMIN_CONFIG_CA_FILE = <path to custom ca cert>
Please refer to the https://www.pgadmin.org/docs/pgadmin4/6.15/container_deployment.html#environment-variables

**Comment by frenos** [comment]
Setting the ENV or even directly setting the CA_FILE in my .py config did not work for oauth. Skimming the code it seems that value is never passed to authlib at all.
Setting `CURL_CA_BUNDLE` (an ENV for authlib which is used by pgadmin for the oauth) works fine. This might also solve #5492 @FunLow
