### ISSUE TITLE
Hitting Enter on Query column creates empty row and opens an uncloseable popup window

### ISSUE THREAD

**Issue by durumdara** [pgadmin-org/pgadmin4#5463]
Version 6.15 / Application Mode Desktop / NW.js Version 0.62.2

I experienced a strange thing from the previous 2-4 versions.
Query, result grid.
Formerly when I pushed Enter key on a string field (cell) a popup editor appeared to modify, or see the content.

Now the Enter key creates an extra, half empty row, and opens the editor popup window.
I can't close this editor by canceling or reopening the query. It remains. I can close it when I close the Query tab too.

Double mouse click works well, only the Enter changed somehow.

**Comment by durumdara** [comment]
![PGAdmin_Enter_Bug](https://user-images.githubusercontent.com/116592015/197603334-beedc25f-4719-48bd-9f62-b30ace6a116f.jpg)

The column type is Text, the result is ReadOnly (retreived by a function).

**Comment by adityatoshniwal** [comment]
@durumdara I tried all possible ways to reproduce this, but not able to. Can you share a screen recording on some dummy data ?

**Comment by durumdara** [comment]
Dear Aditya!

It's very interesting problem. Sometimes I got, sometimes not. Sometimes I have 2 dummy popup windows with two or more half-empty rows...
Windows 11, PGAdmin Last Version, PG 11 DataBase on Linux.
I tried to reproduce it for you, but firstly I failed...

Pleae wait to my next report and don't delete this ticket. 

I will try to reproduce in the future, but it seems to be harder than I thought.

Thank you for your patient!

**Comment by durumdara** [comment]
I tried to copy the "function" (which returns rows), where I experienced this problem, but the newest version didn't produce errors... :-(

So I thought that this problem is caused by only the "function which generates onfly data". 
On normal tables I don't get this in my tests.

But today I also get this problem with a normal table... (select * from ph where name like 'Gen%')

1. I selected the host column by left-rigth buttons. 
2. I pushed the Enter, and nothing happened.
3. I pushed it again, but the problem appeared. 

Which is:

1. The original row (I had only one) is "duplicated"
2.  The duplicated version is halfly contains data. The others cells are empty.
3.  The extra row's number is empty
4.  When I go left, I see two rows.
5.  When I go right (this is new!), after some cells the duplication vanishes, I can see only one row(!)
6.  When I go left, the duplication appears.
7.  The editor cannot closeable, and won't vanish.
8.  The editor shows another cell's value and not that was actual when I pushed the Enter...
9.  12 Angry Men... :-(

So the theory that this generated by only a special row returning function is seems to be false.
This also could happen with normal tables.

One extension:
Commonly I used the SQL editor with remarks. So I worked with a query, and if I want to use another, I remark the not needed lines with -- or /* */.
This means that the Query editor contains many remarks in the top of the SQL.
This (in the past) confused the "Save results to file" button. 

For example:
```
/* 
select * from pg_tables where...
select...
*/
select blah from blue
```

Maybe also this cause the problem here?

I will try to attach pictures (but the data is sensivite).

**Comment by durumdara** [comment]
![PGAdmin_Enter_Bug_01_Dup](https://user-images.githubusercontent.com/116592015/198252690-442c5950-5216-4671-bcc2-b12b7c510ada.jpg)

![PGAdmin_Enter_Bug_02_GoRightNoDup](https://user-images.githubusercontent.com/116592015/198252758-75c89783-01fc-410e-b589-3ab40bdc96c2.jpg)

Otherwise the table where I got these problems contains text fields with long strings.
It's maybe important, maybe not.

**Comment by durumdara** [comment]
I will try to create a demo table to you in the next days.

**Comment by durumdara** [comment]
[PGAdmin_Enter_Bug.zip](https://github.com/pgadmin-org/pgadmin4/files/9880588/PGAdmin_Enter_Bug.zip)

@adityatoshniwal 

1. Start the SQL, this creates the table and fills up with values. Only one row.
2. Open a new Query Window.
3. Write the SQL: select * from tmp_pgentbug
4. Execute.
5. Go down and focus (click once) to c3 column.
6. Use right cursor button and move to c5 field (varchar 64). The long text field must be visible.
7. Hit Enter.
8. Sometimes the Editor isn't appear. If appeared you can see other columns' value (a text field).
9. This Editor is uncloseable in normal way.
10. The drawing of the row is duplicated.

Environment: Win11, 64 bit. PGAdmin Last release.

Beware: the problem is maybe hectic, and starts with normal way - everything is working, and later the Enter isn't working, or creates a wrong editor.

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-11-15/
