### ISSUE TITLE
Query Editor freezing

### ISSUE THREAD

**Issue by 3ddark** [pgadmin-org/pgadmin4#5465]
![screen](https://user-images.githubusercontent.com/5977787/197963703-ccc5c110-5f6d-4064-878f-7af6293f48fd.gif)
If I using close(X) button top right corner on the query editor. Screen freezing 10-15 seconds. But I using Remove Panel on the right click menu no freezing.

Version 6.15
Application Mode Desktop
NW.js Version 0.62.2
Browser Chromium 99.0.4844.84
Operating System Windows-10-10.0.22621-SP0

**Comment by simon-kempster** [comment]
I have this same issue on Windows Server 2019 version 1809.  It wasn't present in the previous version.  One of the pgadmin4.exe instances goes to 100% CPU usage (on one core) for approximately 15 seconds, regardless of how much data is in either the query panel or the results panel.

**Comment by joanix** [comment]
Same issue on Windows 11 Pro 21H2. In some cases the "hang" is longer than 15s. The task consuming "lots of CPU" is nwjs

**Comment by NeilGallacherSQL** [comment]
Same issue of freezing usually several seconds but sometimes much longer. The freeze seems to get progressively longer the longer I am working. 

Version 6.15
Application Mode Desktop
NW.js Version 0.62.2
Browser Chromium 99.0.4844.84
Operating System Windows-10-10.0.22623-SP0

**Comment by chlangjou** [comment]
Same issue here, 

Version 6.15
Application Mode Desktop
NW.js Version 0.62.2
Browser Chromium 99.0.4844.84
Operating System Windows-10-10.0.19044-SP0

**Comment by margrit2103** [comment]
Same issue here,

Entry in pgadmin4.log:
"2022-11-03 11:29:08,382: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance."

Version 6.15
Application Mode Desktop
NW.js Version 0.62.2
Browser Chromium 99.0.4844.84
Operating System Windows-10-10.0.19044-SP0

**Comment by sudeep-quantelai** [comment]
Same issue on Ubuntu 20.04.5

Version: 6.15
Application Mode: Desktop
NW.js Version: 0.62.2
Browser: Chromium 99.0.4844.84
Operating System: Linux-5.15.0-52-generic-x86_64-with-glibc2.29

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build
