### ISSUE TITLE
Unable to compare the schema's between two instances

### ISSUE THREAD

**Issue by VenkatVaraPrasad369** [pgadmin-org/pgadmin4#5467]
Unable to compare the schema's between two instances where the postgresql was installed and configured. It was taking too long to respond.  

Is there anything to version control the postgresql database. like committing the schema (SPs, functions, tables) changes to a version control like git. If so please suggest that

**Comment by adityatoshniwal** [comment]
Hi @VenkatVaraPrasad369,

Can you please state the exact issue ? Screenshots and logs will help to understand better.

**Comment by VenkatVaraPrasad369** [comment]
I have installed Postgresql in two different linux machines (aws-instances). When I was trying to compare the schema between them using pgadmin-v4 (tools-schema diff), I was unable to get the difference in DDL Comparison (Source - Target - Difference).

**Comment by adityatoshniwal** [comment]
@VenkatVaraPrasad369  `unable to get the difference in DDL Comparison` is not enough to know what the issue is. Please provide the exact error you're getting with help of screenshot or logs.

**Comment by pravesh-sharma** [comment]
No response from author hence closing
