### ISSUE TITLE
Oauth2: Allow to use other claims than mail/email as username

### ISSUE THREAD

**Issue by lmaraite** [pgadmin-org/pgadmin4#5468]
It would be really nice to customize the Oauth2 claim, which is used for the username. Until now the email or mail claim are used by default and are not configurable. There are cases, e.g. if you use AzureAD where you want to use another id like the oid as unique username.

**Comment by yogeshmahajan-1903** [comment]
This is working fine. User can configure claim that should be used as user in Oauth2 configuration.
