### ISSUE TITLE
On partion table missing tablespace

### ISSUE THREAD

**Issue by pentolone** [pgadmin-org/pgadmin4#5470]
We use partitioning over different file system/disk, so we create tablespaces according to our infrastructure.

When clicking over a partion table and menu SQL, in the generated script all the subtables belonging to the master table do not have the tablespace clause at the end.

**Comment by pravesh-sharma** [comment]
@FaharAbbasRizvi I checked using psql and we can not create partition table with other Tablespace than the default one in PG10

**Comment by FaharAbbasRizvi** [comment]
This is tested in the snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-12-09/
