### ISSUE TITLE
Typing in user password field moves focus to SSH tunnel password field in connect dialog

### ISSUE THREAD

**Issue by dboehmer** [pgadmin-org/pgadmin4#5471]
When I try to connect to a server through SSH I am prompted for both the identity file password for the SSH tunnel as well as the PostgreSQL user password. Typing in the 2nd field moves the focus the 1st field once. I need to click into the 2nd field again—then it keeps focus.

![Screenshot_20221026_233550](https://user-images.githubusercontent.com/116007/198143206-bffce3c4-5057-4d22-9207-a94149b2b6fc.png)
Screenshot: focus in 1st field after typing two characters of 2nd password

How to reproduce:
1. open PgAdmin
1. click on a server to connect that has SSH tunnel configured
1. press <kbd>Tab</kbd> to move to 2nd password field (without entering an SSH tunnel password)
1. start typing
1. after ~1 second focus moves to 1st password field
1. press <kbd>Tab</kbd> to move focus to 2nd password field
1. typing does now work fine

I am using PgAdmin 6.15 from the apt repository on Debian Bullseye.

**Comment by pravesh-sharma** [comment]
Issue fixed, verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-11/yum/

Env
OS - Rocky Linux 9
Mode - Desktop
