### ISSUE TITLE
Unable to dump the postgres schema

### ISSUE THREAD

**Issue by VenkatVaraPrasad369** [pgadmin-org/pgadmin4#5474]
I was unable to dump the postgres schema using the below mentioned command. 

I just logged into linux server and i have installed postgres init, but when i run various commands as mentioned below:-

#pg_dump -s dbname  > /var/pg_dump/sdump.dmp
#pg_dump -s dbname  > sdump.dmp
#pg_dump  -U username --clean --schema-only > /var/pg_dump/sdump.sql
#pg_dump  -U username --clean --schema-only > sdump.sql

still i was unable to get the file in the mentioned directory. Is there any way to do this.
If so please suggest.

**Comment by yogeshmahajan-1903** [comment]
It seems issue is related to postgres server. For postgres server support you can chose one option from [here](https://www.postgresql.org/support/).

If you want to perform above activity with user interface, use pgAdmin to dump server data, -
1.Add server to pgAdmin
2.Then take backup.
[Here](https://www.pgadmin.org/docs/pgadmin4/6.15/index.html) is documentation about installing pgAdmin, adding server, etc.
