### ISSUE TITLE
Switch "Save unsaved query changes" in "Preferences" does not affect when the query tool is opened in a separate window

### ISSUE THREAD

**Issue by IIIIIME2IIIII** [pgadmin-org/pgadmin4#5475]
When the option Preferences->Browser->Tab settings->Open in new browser tab 
containig "Query Tool" (e.g. when the "Query Tool" opens in separate window),
value of option Preferences->Query Tool->Options->Prompt to save unsaved query changes?
is always ignored, and prompt is raised every time on closing window.

**Comment by IIIIIME2IIIII** [comment]
Thanks a lot!

**Comment by nikhil-mohite** [comment]
@IIIIIME2IIIII ,

You need to disable the setting 'Confirm on close or refresh?' from preferences -> Browser -> Display, for this as the Query tool will get open in a new browser tab. (Fix will be available in the next release or you can try the daily snapshot build from   https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/, snapshot build are not tested you may face some issues)

**Comment by akshay-joshi** [comment]
Reopen it for Testing.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/
