### ISSUE TITLE
Unable to run in kubernates

### ISSUE THREAD

**Issue by ermakovm** [pgadmin-org/pgadmin4#5483]
I'm trying to start pgadmin in kubernates.

I have this error in logs
```
/entrypoint.sh: line 65: /venv/bin/python3: Operation not permitted
/entrypoint.sh: line 88: /venv/bin/python3: Operation not permitted
/entrypoint.sh: exec: line 96: /venv/bin/gunicorn: Operation not permitted
```
I'm using the dpage/pgadmin4 Docker image

**Comment by EvertonSA** [comment]
this is definitely not enough info for someone to help you. Im using dpage helm chart and everything works fine.

**Comment by pravesh-sharma** [comment]
No response from author hence closing
