### ISSUE TITLE
[BUG] Not able to use QueryTool when user have @ in the name - Azure PSQL Single Servers 

### ISSUE THREAD

**Issue by EvertonSA** [pgadmin-org/pgadmin4#5486]
Currently, Azure Postgres Single Servers generate users with @ sign that have the instance name.

https://learn.microsoft.com/en-us/azure/postgresql/single-server/how-to-create-users

even though I create a user called everton, the username is everton@myinstancename.

pgadmin4 is successfully is able to connect to the instance but when using query editor, it fails to process the correct user due to the mask applied here https://github.com/pgadmin-org/pgadmin4/blob/d38d0ce805c66abd9bdbdb87980810b02cfb0f6a/web/pgadmin/utils/constants.py#L38

**Comment by EvertonSA** [comment]
edit: also, we notice that this error only happen on shared server definitions, it does not happen when we add manually. when adding manually, the connection looks like this:

![image](https://user-images.githubusercontent.com/30481051/199491657-2b35d0d6-8ea4-44af-9e65-b4e4d6bb1b7b.png)

but when doing it by shared server definition it looks like this:

![image](https://user-images.githubusercontent.com/30481051/199491827-ffb064f8-76d7-460e-aaf5-ebfbe52173db.png)

**Comment by EvertonSA** [comment]
@akshay-joshi thanks for the info, will try to reproduce and provide more details

**Comment by yogeshmahajan-1903** [comment]
@EvertonSA
This issue will be fixed in 6.16 release which is planned for tomorrow.
This is fixed in #5533
