### ISSUE TITLE
Failed to decrypt the saved password

### ISSUE THREAD

**Issue by dev3fyfy** [pgadmin-org/pgadmin4#5487]
i face this error when saved password to server db and  relogin agin to account , it don't save password and display this message 
Failed to decrypt the saved password. Error: 'utf-8' codec can't decode byte 0xcd in position 2: invalid continuation byte.
![iScreen Shoter - 20221101183154207](https://user-images.githubusercontent.com/92525726/199531533-64791ca2-fe3e-4400-bee0-9b147cfe7a87.jpg)

**Comment by yogeshmahajan-1903** [comment]
@dev3fyfy Can you please share special characters used as part of password?

**Comment by dev3fyfy** [comment]
> @dev3fyfy Can you please share special characters used as part of password?

I just use normal letters and numbers in this password

**Comment by yogeshmahajan-1903** [comment]
@dev3fyfy Have you switched from Desktop to server mode or vice-versa?

**Comment by dev3fyfy** [comment]
> @dev3fyfy Have you switched from Desktop to server mode or vice-versa?

no, this happen with me in server mode

**Comment by pravesh-sharma** [comment]
Hi @dev3fyfy 
Are you using shared server? if yes are you getting this error for non privileged user or admin user.
Since when this error started occurring?
Can you please share the pgAdmin logs?

**Comment by ramank775** [comment]
I am facing same issue with 6.16, I am using docker image to host the pgadmin server behind nginx proxy

> Hi @dev3fyfy Are you using shared server? if yes are you getting this error for non privileged user or admin user. Since when this error started occurring? Can you please share the pgAdmin logs?

I am using shared server, and facing problem with both admin as well as non privileged users.
Only the user who created the server is able to use the saved password.

FYI: All the users are using the same database user and password to connect. is that's  issue?

**Comment by ramank775** [comment]
Is there any update on this issue?

If no one is working on this, i am willing to work on this but might need some guidance to start.

**Comment by adityatoshniwal** [comment]
@ramank775 Sure. Please checkout the README and https://www.pgadmin.org/development/ on how to setup pgAdmin dev environment and contribute.

**Comment by ramank775** [comment]
Thanks @adityatoshniwal.
I have setup the code base and started debugging the issue.

My initial finding
- If both the users shared the same password, this issues doesn't occur. (The user login password).
  My initial guess over here is the password is encrypted with password of the admin who has configured the shared server.

**Comment by ramank775** [comment]
Hi @adityatoshniwal I have raised the PR with the fix. can you please review

**Comment by FaharAbbasRizvi** [comment]
Tested in the Candidate build for v6.19.

**Comment by ccurvey** [comment]
I am now getting this error in v8.14

**Comment by yogeshmahajan-1903** [comment]
@ccurvey 
Can you please try clear saved password by right clicking server > Clear Saved password option and resave it?

**Comment by ccurvey** [comment]
No joy.

1. Try to open server...get error
2. Enter correct password...get connected
3. Clear password for server
4. Close PgAdmin4
5. Reopen PgAdmin4
6. Try to open server...am asked for password.  (expected)
7. Enter password, check the save password box...get connected
8. Close PgAdmin4
9. Reopen PgAdmin4
10. Try to open server...get error

I'm happy to generate/send logs if they are available....

**Comment by yogeshmahajan-1903** [comment]
@ccurvey 
What is you pgadmin version. What is pgadmin mode?(server/desktop) Can you please share logs?

**Comment by ccurvey** [comment]
> @ccurvey What is you pgadmin version. What is pgadmin mode?(server/desktop) Can you please share logs?

PgAdmin 4, version 8.12
Desktop Mode
Ubuntu 24.04, fully patched

the last few bits of the log are:

> 2024-10-15 10:03:19,616: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
> 2024-10-15 10:04:29,030: ERROR	pgadmin:	'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte
> Traceback (most recent call last):
>   File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg3/connection.py", line 252, in _decode_password
>     password = password.decode()
>                ^^^^^^^^^^^^^^^^^
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte
> 2024-10-15 10:04:29,033: ERROR	pgadmin:	Could not connect to server(#1) - 'dai6'.
> Error: Failed to decrypt the saved password.
> Error: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte
