### ISSUE TITLE
"remove panel" removing wrong panel!

### ISSUE THREAD

**Issue by fjf2002** [pgadmin-org/pgadmin4#5490]
* Open multiple panels (for example query tools). Type different stuff in them to be able to distinguish them later.
* Right-click on the tab of an inactive panel and choose "remove panel"

Instead of the panel that you clicked on, the active panel gets removed :-(

**Comment by pravesh-sharma** [comment]
Did some research to check the feasibility of it. However, wcDocker (library used for tabs) has this as default behaviour and changing this behaviour would require changes in other libraries on which wcDocker is dependant.

**Comment by adityatoshniwal** [comment]
Remove panel will be replaced with "Close" and will work on the apt. tab in #6479
