### ISSUE TITLE
post gis

### ISSUE THREAD

**Issue by MORAWA-dev** [pgadmin-org/pgadmin4#5491]
I don't see postgis template on this latest version
<img width="1680" alt="Screenshot 2022-11-03 at 01 29 14" src="https://user-images.githubusercontent.com/72025891/199626912-0f3adedc-8c2c-40b3-bce0-60610ebcdde1.png">

**Comment by yogeshmahajan-1903** [comment]
@MORAWA-dev  Can you please elaborate the issue? If you want to add PostGIS extension to the database , it should be added from create option in Extensions Node.
Template dropdown populates only databases list which can be used as template.

**Comment by pravesh-sharma** [comment]
No response from author hence closing.
