### ISSUE TITLE
Query Tool edit window scrolling is (sometimes) broken

### ISSUE THREAD

**Issue by usernamesareaholdoverfromthe90s** [pgadmin-org/pgadmin4#5494]
Test case

1. Create a query that is wider than the edit window.  In the attached screenshot the last couple of characters in the query are "= -1" but we can only see "="
2. Do some other stuff in other tabs <-- this is the vague part of the test case
3. Come back to the query tab
4. Try to see the last few characters of the query, by either....
5. Using the horizontal scrollbar.   <-- still can't see the last couple of characters
6. Clicking on the text so you get an input cursor, and then using the arrows or the End key to move it to the end.  <-- still can't see the last couple of characters OR the input cursor

![image](https://user-images.githubusercontent.com/117369461/199742560-8e75ca4c-2be5-481b-9751-49cee0b44cc5.png)

After a while of switching to other tabs and then back to the query tab, the problem eventually resolves itself (i.e., the scrollbar now shows that the visible window is a smaller percentage of the content width, and can be slid over as expected).   But clearly, there's a window sizing / horizontal scrollbar issue

**Comment by anilsahoo20** [comment]
Hi @usernamesareaholdoverfromthe90s 
I tried with multiple ways to reproduce the issue, but it was not happening. 
Can you please share the exact steps by which we can reproduce the issue and the version of pgAdmin 4?

Thanks

**Comment by usernamesareaholdoverfromthe90s** [comment]
I did provide the exact steps in the original case.  The challenge (as noted in step #2) is that this seems to be an intermittent bug that involves switching tabs, or interaction with other windows.  That is the frustrating nature of debugging intermittent issues.

Is it happening today?  No.  Has it happened on multiple occasions?  Yes.

**Comment by adityatoshniwal** [comment]
This is fixed with CodeMirror upgrade.
