### ISSUE TITLE
Query History date/time only in US format

### ISSUE THREAD

**Issue by simon-kempster** [pgadmin-org/pgadmin4#5495]
![Capture](https://user-images.githubusercontent.com/99345210/199780543-216648c5-8a4d-4116-b780-4a9f2ba544d4.JPG)

Windows Server 2019, pgAdmin 6.15, desktop mode.

Connect to a database.  Open Query Tool.  Go to Query History.  Date and time of historic queries shown only in US format, regardless of local machine's regional settings.

**Comment by akshay-joshi** [comment]
@simon-kempster 

I have tested it with the latest code and it is working fine. 
Testing scenario:

- Start the pgAdmin in UTC + 5:30 (India).
- Run a few queries. 
- Change the system's timezone to UTC + 1 (Berlin)
- Check the query history.

<img width="1383" alt="Berlin" src="https://user-images.githubusercontent.com/1632882/202643415-da33224c-27d6-4791-9ff6-6d1471a8dcb5.png">

- Change the system's timezone to UTC + 11 (Sydney)
- Start the pgAdmin and check the query history 

<img width="1381" alt="Sydney" src="https://user-images.githubusercontent.com/1632882/202643430-179414cd-c4cd-4942-9144-1d8ab96cf079.png">

Can you please provide steps to reproduce this?

**Comment by adityatoshniwal** [comment]
@akshay-joshi Probably he's indicating the format of date. Currently pgAdmin will show in MM/DD/YYYY format only.

**Comment by simon-kempster** [comment]
Sorry, I should have been clearer: I was referring to the format of the date, not the timezone.  My PC's date format is set to dd/mm/yyyy but the query history date format is always mm/dd/yyyy.  The screenshot taken is the original post was on 3rd November 2022, not 11th March 2022, so I would expect to see the date as 3/11/2022 not 11/3/2022.

**Comment by akshay-joshi** [comment]
@simon-kempster 

It seems to be not a pgAdmin issue. I have tried on OSX by changing the region from India to the United States and the format of the date changed as per the system's locale. I have tested it on Desktop mode and Server Mode (Chrome, Firefox, and Safari browsers). Please refer to the screenshots
<img width="1596" alt="English-India" src="https://user-images.githubusercontent.com/1632882/203489169-3abe4b9a-f495-4127-a2b5-646937aa9e39.png">
<img width="1601" alt="English-US" src="https://user-images.githubusercontent.com/1632882/203489183-2fe2878b-7b45-43dd-8d07-5e06147449dd.png">
   
In pgAdmin, we have used the **[toLocaleDateString()](https://www.w3schools.com/jsref/jsref_tolocaledatestring.asp)** function to represent Date.

Can you please update us on the following:
1. On which Operating System you are running pgAdmin?
2. In which mode (server/desktop) pgAdmin is running?
3. What is the system's locale?

**Comment by simon-kempster** [comment]
2 of those 3 were in my initial post.
1. Windows Server 2019
2. Desktop mode
3. United Kingdom

**Comment by akshay-joshi** [comment]
Hi @simon-kempster 

Yes, I am able to reproduce the issue on Windows in Desktop mode and Server mode. [toLocaleDateString()](https://www.w3schools.com/jsref/jsref_tolocaledatestring.asp) is not returning the date based on the system's locale in Chrome and Microsoft Edge, while it is returning the date in the correct format in Firefox. Please refer to the screenshot below:

<img width="1582" alt="Windows" src="https://user-images.githubusercontent.com/1632882/203499143-98ca326c-5f4e-4d0d-9d98-aba287822b12.png">

**We will try to fix this in Desktop mode**, but in the Server mode user will have to add the locale/language in the [Chrome](chrome://settings/languages) and [Edge](edge://settings/languages) and then select the "Display Google Chrome/Edge in this language" to resolve the issue.

**Comment by FaharAbbasRizvi** [comment]
Tested in Desktop and Server mode on the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-11-2
