### ISSUE TITLE
Issue with podman an firewalld on fedora 35

### ISSUE THREAD

**Issue by mccuskk** [pgadmin-org/pgadmin4#5500]
Hi

I have followed the instructions for running the docker image although I am on Fedora 35 so I am actually using podman. What I have come accross is that it overrides at least some of my firewall settings (maybe all).

With the container running I can access git-daemon remotely and log in to postgresql, neither of which should be possible given my firewall settings.

Reloading my firewalld rules immediately restores the previous behaviour. Any thoughts on what could be happening?

Many thanks

Kieran

**Comment by pravesh-sharma** [comment]
@mccuskk This doesn't seems to be a pgAdmin issue. pgAdmin does not change any firewall setting.
