### ISSUE TITLE
Use native menus via NWjs in desktop mode

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#5503]

**Comment by yogeshmahajan-1903** [comment]
Please find the issues found while primary testing - 

1.Opening query tool in new tab is not working. Give blank Window
2.4 additional lines in Help Manu after Quick search
3.Online help is not working
4.Backup/Restore menu not enabled on selecting database
5.Tool bar is not in accordance with theme.
6.Blank screen shown sometimes on clicking menu on linux platform.

**Comment by yogeshmahajan-1903** [comment]
Some more issues - 
1.Online help is not working.
2.When option from File > Lock layout is changed its not reflecting in preference.
3.Order of submenus in Menu bar are different from context sub-menus.
4.Trigger submenu 'Disable All' is enabled though all triggers are disabled.
