### ISSUE TITLE
Incorrect view of text[] fields in query and table results. When use other then UTF8 (win1251) codepage and symvols

### ISSUE THREAD

**Issue by Elvish** [pgadmin-org/pgadmin4#5504]
Exec simple query:
`SELECT 'Кириллица' a,ARRAY['Кириллица'] b,'{Кириллица}'::text c,'{Кириллица}'::text[] d;`
or same query with codepage information:
`SELECT'Кириллица' a,ARRAY['Кириллица'] b,'{Кириллица}'::text c,'{Кириллица}'::text[] d, pg_client_encoding(), (SELECT pg_encoding_to_char(encoding) server_encode FROM pg_database WHERE datname = current_database());`

In example text there are non latin simvols. 
Anyone expects a result оf two equal cells:  
'Кириллица'	'{Кириллица}'	'{Кириллица}'	'Кириллица}'...
but PgAdmin4 gives the result:
'Кириллица'	'{РљРёСЂРёР»Р»РёС†Р°}'	'{Кириллица}'	'{РљРёСЂРёР»Р»РёС†Р°}'

In my case it was cyrillic alphabet in codepage win1251, server and database codepage was utf8. 
I test auto convert text and text[] by low level in C++ program. The server convert type TEXT and TEXT[] both and correctly.
If I create/use any table with text and convert TEXT to TEXT[] - in PgAdmin4 it output wrong text.
For example this code:
```
CREATE TEMP TABLE t(n text);
INSERT INTO t VALUES ('{Буквы}');
SELECT n,n::text[] FROM t;
```
This code produce output:
 '{Буквы}'	'{Р‘СѓРєРІС‹}'
This is incorrect!

There is same problem. In my database in utf8 there are a lot of symbols in UTF8 without WIN1251 representation. I can't see this tables and texts in PgAdmin4.

In PgAdmin3 - all work correctly. And no any problems of text and text[].

Issue was in:
PgAdmin4 version: 6.15
NW.js Version: 0.62.2
Browser: Chromium 99.0.4844.84
Operating System: Windows-10-10.0.19044-SP0

![image](https://user-images.githubusercontent.com/2465301/200280742-02faa4b9-b954-40b5-a155-8c4275a082b5.png)
![image](https://user-images.githubusercontent.com/2465301/200280882-e2eed660-5562-4ba1-b10a-8b49aa6ea6e9.png)

**Comment by khushboovashi** [comment]
Fahar, please test with the psycopg build.

**Comment by FaharAbbasRizvi** [comment]
This issue is fixed in the latest psycog3
