### ISSUE TITLE
Internal server error displayed if CSV field separator and CSV quote character contain ""  and User tries to download Save Result to File

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#5505]
Internal server error displayed if CSV field separator and CSV quote character contain ""  and User tries to download Save Result to File.

Please note that this error message is not displayed with other special characters.

Steps
1. Go into preferences>Query Tool>CVS/Text output
2.  Write "" in CSV field separator and CSV quote character
3. Click on Save button
4. Click on Table and view data
5. Click on  download Save Result to File
6. Following Error message

Successfully run. Total query runtime: 2 secs 23 msec.
14 rows affected.INTERNAL SERVER ERROR

<img width="1762" alt="Screen Shot 2022-11-07 at 4 11 15 PM" src="https://user-images.githubusercontent.com/43006122/200303327-0d3a456c-db59-443f-950d-355342f4b007.png">
<img width="1789" alt="Screen Shot 2022-11-07 at 4 11 48 PM" src="https://user-images.githubusercontent.com/43006122/200303362-aeca7b81-f74a-4fd9-b70d-d583cd4e5fbd.png">

**Comment by pravesh-sharma** [comment]
The reason for this issue is that we can not use string of more than 1 character as delimiter or quote character.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-11-29/
