### ISSUE TITLE
pgAdmin update required AZURE_CREDENTIAL_CACHE_DIR in config_local.py

### ISSUE THREAD

**Issue by dgilman** [pgadmin-org/pgadmin4#5513]
Hello, just did an update from pgadmin4 6.8 to 6.15. I had to add AZURE_CREDENTIAL_CACHE_DIR to my config_local.py. Up until now, I was OK with following the default recommendations from [the docs](https://www.pgadmin.org/docs/pgadmin4/latest/server_deployment.html) which just had you define LOG_FILE, SQLITE_PATH, SESSION_DB_PATH and STORAGE_DIR.

I think the bug here is that the docs should be updated to mention that AZURE_CREDENTIAL_CACHE_DIR should be defined as well.

**Comment by pravesh-sharma** [comment]
We should explore how we can set STORAGE_DIR dependant config variables automatically without user needing to set it manually.

**Comment by khushboovashi** [comment]
Working fine. Tested with the wheel package. Ref:  https://developer.pgadmin.org/builds/2022-11-30-1/
