### ISSUE TITLE
ERROR: Conf pgadmin4 does not exist

### ISSUE THREAD

**Issue by benny12312311** [pgadmin-org/pgadmin4#5514]
When I run  sudo /usr/pgadmin4/bin/setup-web.sh,

it shows "ERROR: Conf pgadmin4 does not exist".

And I cannot access http://127.0.0.1/pgadmin4

I have no idea what happened.
Please help me

**Comment by pravesh-sharma** [comment]
Hi @benny12312311 

The error comes when the command `a2enconf pgadmin4` fails. Looks like there is some issue with your apache installation. Can you try clean installing apache and then try to run the script again ?

**Comment by khushboovashi** [comment]
No response from the author.
