### ISSUE TITLE
Connection to pgAdmin server has been lost on browser version -- how to reconnect

### ISSUE THREAD

**Issue by txjmb** [pgadmin-org/pgadmin4#5515]
I frequently get disconnections from pgAdmin server on browser version while running long queries, even though server is up and not experiencing errors.  The message is "Connection to pgAdmin server has been lost".  It appears to be a client-side disconnect.  However, there appears to be no way to reconnect the query tab on the browser to the backend query on the PgAdmin server when this happens.  

Not sure if this is a bug, or if there is a workaround/setting I need to change.

I'm running PgAdmin 6.15 server on Docker.  I've experienced this issue with latest versions of Chrome and Edge.  Let me know if you need more information.

**Comment by pravesh-sharma** [comment]
Hi @txjmb 

Can you please share the pgAdmin docker logs?

**Comment by khushboovashi** [comment]
No response from the author.
