### ISSUE TITLE
Cannot copy results from Data Output tab

### ISSUE THREAD

**Issue by CoryAlbrecht** [pgadmin-org/pgadmin4#5516]
PGAdmin4 6.15 in Docker on Debian Bullseye, pulled just now
Chrome 107.0.5304.110 (Official Build) (64-bit)
Ubuntu 22.04 LTS

When trying to use ctrl+c or the button to copy selected data from table displayed in the Data Output tab, a small red warning appears saying "Does not have clipboard access".

![image](https://user-images.githubusercontent.com/8172909/201486907-7b61f179-4db6-46f1-9dc3-6dfcb2c59a22.png)

Toggling chrome://flags/#clipboard-unsanitized-content has no effect.

**Comment by khushboovashi** [comment]
No response from the author.

**Comment by CoryAlbrecht** [comment]
Clipboard access is already enabled, so this suggestion does not work.
