### ISSUE TITLE
Error in Running in Desktop mode in the runtime, pgadmin4-6.15

### ISSUE THREAD

**Issue by aroudgar** [pgadmin-org/pgadmin4#5517]
I am using the latest version, pgadmin4-6.15 in Desktop mode and I get the following error. Server mode runs as expected:

[Sat Nov 12 09:28:19.993608 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812] 2022-11-12 09:28:19,972: ERROR\tpgadmin:\t'browser.forgot_password'
[Sat Nov 12 09:28:19.993655 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812] Traceback (most recent call last):
[Sat Nov 12 09:28:19.993661 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
[Sat Nov 12 09:28:19.993665 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     rv = self.dispatch_request()
[Sat Nov 12 09:28:19.993669 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
[Sat Nov 12 09:28:19.993672 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Sat Nov 12 09:28:19.993676 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/flask_security/decorators.py", line 449, in decorated
[Sat Nov 12 09:28:19.993701 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     return fn(*args, **kwargs)
[Sat Nov 12 09:28:19.993705 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/flask_security/views.py", line 206, in login
[Sat Nov 12 09:28:19.993709 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     return _security.render_template(
[Sat Nov 12 09:28:19.993713 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/flask_security/utils.py", line 1064, in default_render_template
[Sat Nov 12 09:28:19.993716 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     return render_template(*args, **kwargs)
[Sat Nov 12 09:28:19.993719 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/flask/templating.py", line 154, in render_template
[Sat Nov 12 09:28:19.993723 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     return _render(
[Sat Nov 12 09:28:19.993727 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
[Sat Nov 12 09:28:19.993730 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     rv = template.render(context)
[Sat Nov 12 09:28:19.993733 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
[Sat Nov 12 09:28:19.993737 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     self.environment.handle_exception()
[Sat Nov 12 09:28:19.993740 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
[Sat Nov 12 09:28:19.993743 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     raise rewrite_traceback_stack(source=source)
[Sat Nov 12 09:28:19.993747 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/web/pgadmin/templates/security/login_user.html", line 1, in top-level template code
[Sat Nov 12 09:28:19.993750 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     {% extends "security/panel.html" %}
[Sat Nov 12 09:28:19.993757 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/web/pgadmin/templates/security/panel.html", line 2, in top-level template code
[Sat Nov 12 09:28:19.993834 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     {% from "security/fields.html" import render_field_with_errors, render_username_with_errors %}
[Sat Nov 12 09:28:19.993838 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/web/pgadmin/templates/base.html", line 76, in top-level template code
[Sat Nov 12 09:28:19.993842 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     {% block body %}{% endblock %}
[Sat Nov 12 09:28:19.993848 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/web/pgadmin/templates/security/panel.html", line 28, in block 'body'
[Sat Nov 12 09:28:19.993852 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     {% block panel_body %}{% endblock %}
[Sat Nov 12 09:28:19.993856 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/web/pgadmin/templates/security/login_user.html", line 18, in block 'panel_body'
[Sat Nov 12 09:28:19.993859 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     <div class="col-7"><span class="help-block">{{ _('<a href="%(url)s" class="text-white">Forgotten your password</a>?', url=url_for('browser.forgot_password')) }}</span></div>
[Sat Nov 12 09:28:19.993876 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/flask/helpers.py", line 309, in url_for
[Sat Nov 12 09:28:19.993880 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     appctx.app.inject_url_defaults(endpoint, values)
[Sat Nov 12 09:28:19.993883 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/flask/app.py", line 1812, in inject_url_defaults
[Sat Nov 12 09:28:19.993887 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     func(endpoint, values)
[Sat Nov 12 09:28:19.993890 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/web/pgadmin/__init__.py", line 843, in add_internal_version
[Sat Nov 12 09:28:19.993894 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     urls = [url for url in app.url_map.iter_rules(endpoint)]
[Sat Nov 12 09:28:19.993908 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]   File "/opt/software/pgadmin4-6.15/python/lib/python3.10/site-packages/werkzeug/routing.py", line 1536, in iter_rules
[Sat Nov 12 09:28:19.993912 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812]     return iter(self._rules_by_endpoint[endpoint])
[Sat Nov 12 09:28:19.993915 2022] [wsgi:error] [pid 29661] [remote 174.1.63.107:42812] KeyError: 'browser.forgot_password'

I checked all python modules version and they seem all the same as in  DEPENDENCIES file. 
Thank you for your time.

**Comment by yogeshmahajan-1903** [comment]
Can you please check on latest version 6.16. I am not able to reproduce the issue.

**Comment by pravesh-sharma** [comment]
No response from author hence closing.
