### ISSUE TITLE
PGAdmin4 6.15 randomly crashing and freezing on Windows 11 22H2 

### ISSUE THREAD

**Issue by ADun3306x** [pgadmin-org/pgadmin4#5519]
PGAdmin4 6.15 randomly crashing and freezing on Windows 11 22H2 - Running queries, changing tabs, entering data.
Prior versions did not have these issues

**Comment by adityatoshniwal** [comment]
Duplicates #5465. The fix will be available in 6.16 which is planned to be released this week.
