### ISSUE TITLE
Syntax error when trying to change a language in the definition tab after creating a procedure

### ISSUE THREAD

**Issue by casluxd** [pgadmin-org/pgadmin4#5520]
Version of pgAdmin: 4
Obtained from: snap
Running on: Desktop
System: Ubuntu 20.04
Reproduce problem: Created a procedure, but in the definition tab, the language was saved as sql. In the code tab, the language would be plpgsql. When trying to change the language to plpgsql in the definition tab, receive a syntax error

You can see where the problem started here: https://stackoverflow.com/questions/74425496/is-type-casting-the-problem-in-my-procedure-call

**Comment by adityatoshniwal** [comment]
@pravesh-sharma Please check this.

**Comment by adityatoshniwal** [comment]
@casluxd Can you share the screenshot of the error ? And the modified SQL generated in the SQL tab of edit dialog ?

**Comment by khushboovashi** [comment]
No response from the author.
