### ISSUE TITLE
Uncaught (in promise) TypeError: e is undefined exeception displayed on Server mode

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#5521]
Tested on Ubuntu 18.04 and Centos 7 64

I am getting an error message when comparing schema diff on server mode through rpm 
Uncaught (in promise) TypeError: e is undefined
    parseApiError http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    e http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    u http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    _invoke http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    _ http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    T http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    i http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    promise callback(http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1))
    l http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    r http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    r http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    We http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    c http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    promise callback*c http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    value http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    promise callback*value http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    onClick http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61500:1
    We http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    Ke http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    kr http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    kr http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    Br http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    Pr http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    De http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    Pr http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    Pr http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    qt http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    Jt http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    unstable_runWithPriority http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    Vi http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    Le http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109
    Yt http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61500:109

**Comment by FaharAbbasRizvi** [comment]
<img width="1748" alt="Screen Shot 2022-11-14 at 1 05 06 PM" src="https://user-images.githubusercontent.com/43006122/201614477-caef66f2-ce02-40f4-86f0-d3520fd73c80.png">

**Comment by akshay-joshi** [comment]
Looks similar to #4416
