### ISSUE TITLE
Evaluate Flask-Migrate 4.0.0

### ISSUE THREAD

**Issue by musicinmybrain** [pgadmin-org/pgadmin4#5525]
[Flask-Migrate](https://pypi.org/project/Flask-Migrate/) has just released version 4.0.0.

Please consider the following:

- Review the [change log](https://github.com/miguelgrinberg/Flask-Migrate/blob/v4.0.0/CHANGES.md#flask-migrate-change-log) for this release.
- Review the use of Flask-Migrate in [`web/pgadmin/setup/db_upgrade.py`](https://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/setup/db_upgrade.py) (the only place it is used in this project).
- Decide whether the dependency specifications can be loosened to allow version 4.x:

https://github.com/pgadmin-org/pgadmin4/blob/c5e9aa6357aee37986ce25b3775f6aa6111e84d7/DEPENDENCIES#L30

https://github.com/pgadmin-org/pgadmin4/blob/c5e9aa6357aee37986ce25b3775f6aa6111e84d7/requirements.txt#L16

**Comment by musicinmybrain** [comment]
Has anyone had a chance to take a look a this? It seems like it should be fine, but it’s not immediately obvious to me how to test it.

**Comment by dpage** [comment]
I don't see any pressing need to upgrade from the release notes - certainly there is no mention of any security fixes that I can spot. Why do you feel this needs to be prioritised?

**Comment by musicinmybrain** [comment]
I’m delaying upgrading the `python-flask-migrate` package in the development version (Rawhide) of Fedora Linux because the `pgadmin4` package pins the older version. I can keep doing that, but preferably for weeks or months rather than indefinitely.

The version pin could be loosened as a downstream patch if necessary, but I’m not sure how to actually test compatibility.

**Comment by dpage** [comment]
Akshay, please ensure this is handled in the next round of dep updates. Thanks.

**Comment by musicinmybrain** [comment]
> Akshay, please ensure this is handled in the next round of dep updates. Thanks.

I appreciate it!

**Comment by akshay-joshi** [comment]
On Mon, Jan 16, 2023 at 3:48 PM Dave Page ***@***.***> wrote:

> Akshay, please ensure this is handled in the next round of dep updates.
> Thanks.
>
   Sure will check

**Comment by anthraxx** [comment]
Justed wanted to note that on Arch Linux we now run into the same issue, compatibility with 4.0.x would be greatly appreciated.

**Comment by dpage** [comment]
Just as a general note: 4.x is a new major version that breaks backwards compatibility. OS packagers should really make it a separate package from the previous version; that would a) resolve the problem with pgAdmin, and b) stop an OS package update from breaking any user code that's using the older version of Flask-Migrate.

**Comment by anthraxx** [comment]
@dpage unfortunately thats not really how it can work in the python ecosystem, as the destination paths are colliding and python has no concept of multi version installations. Hence it would introduce conflicting packages, which is what is to be avoided. Adding separate packages for previous versions is not an average option that can be used, except for native libraries where co existing versions with different SONAME can co exist easily.

**Comment by khushboovashi** [comment]
Checked with the latest version and no issues found.

**Comment by akshay-joshi** [comment]
Check with Flask-Migrate 4.0.4, working fine.

**Comment by musicinmybrain** [comment]
Thanks again for looking at this!
