### ISSUE TITLE
Uncaught TypeError: t is undefined Message displayed on schema diff through inspect element for server mode

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#5529]
I am getting the following error on schema diff through inspect element but now schema diff is working fine 

Uncaught TypeError: t is undefined
    h http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    ResizeObserverCallback* http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    ma http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Rl http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    unstable_runWithPriority http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Vi http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Ol http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    yl http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Ki http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    unstable_runWithPriority http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Vi http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Ki http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    $i http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    pl http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Ms http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Ye http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    e http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    u http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    _invoke http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    _ http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    T http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    l http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    promise callback*T http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    l http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    promise callback*T http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    l http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    r http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    r http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    We http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    c http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    promise callback*c http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    value http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    promise callback*value http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    onClick http://127.0.0.1/pgadmin4/static/js/generated/schema_diff.js?ver=61600:1
    We http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Ke http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    kr http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    kr http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Br http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Pr http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    De http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Pr http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Pr http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    qt http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Jt http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    unstable_runWithPriority http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Vi http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Le http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109
    Yt http://127.0.0.1/pgadmin4/static/js/generated/vendor.others.js?ver=61600:109

**Comment by FaharAbbasRizvi** [comment]
<img width="1787" alt="Screen Shot 2022-11-15 at 4 11 49 PM" src="https://user-images.githubusercontent.com/43006122/201910361-030ca4fa-11b7-4b2c-a873-c840ca2c4767.png">

**Comment by pravesh-sharma** [comment]
@FaharAbbasRizvi The issue is not reproducible, I tried on different env but did not get this error.
