### ISSUE TITLE
Get blur when multiple modals open

### ISSUE THREAD

**Issue by sreetam-nt** [pgadmin-org/pgadmin4#5531]
Whenever I right-click a table's properties, a modal appears. Whenever I open another property window, it gets overlapping. There should be a feature that automatically closes the older properties window when we open another.  

![Screenshot from 2022-11-15 17-00-43](https://user-images.githubusercontent.com/88495410/201910881-e660cf52-a168-4e1b-b9ef-c5d5bd86bc1c.png)

**Comment by adityatoshniwal** [comment]
It is bad UX to replace existing dialog. People generally open multiple table/other dialogs side-by-side for reference.

**Comment by sreetam-nt** [comment]
@adityatoshniwal Thanks for the clarification.
