### ISSUE TITLE
Client cert location not stored on shared servers

### ISSUE THREAD

**Issue by net-expertise** [pgadmin-org/pgadmin4#5532]
On a clean installation of PgAdmin in server mode, based on the official Docker image version 6.15 I have the following issue:

1. Add a shared server in chart eg:
`serverDefinitions:
  enabled: true
  servers:
    grafana:
      Name: "grafana"
      Group: "Shared"
      Host: "10.1.1.1"
      Port: 5432
      MaintenanceDB: "postgres"
      Username: "admin"
      SSLMode: "prefer"
      Shared: true
      SSLCert: "/grafana/postgresql.crt"
      SSLKey: "/grafana/postgresql.key"
      SSLRootCert: "/grafana/root.crt"
      SSLCompression: 0
`

2. Login as an unprivileged user, check server settings under Properties > SSL.
    Client certificate key ans Root certificate are there but Client certificate is missing, although the file is there, I can browse and select it.

![pg_missing_client_cert](https://user-images.githubusercontent.com/86559027/201906766-cc3604ef-34a7-41b4-bc1f-2058206522cc.png)

**Comment by akshay-joshi** [comment]
After the implementation of #4728, this issue should be fixed automatically.

**Comment by nikhil-mohite** [comment]
Resolved, verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-27/
Platform: macOS Monterey 12.6
Mode: Desktop
