### ISSUE TITLE
Query tool not working on shared servers

### ISSUE THREAD

**Issue by net-expertise** [pgadmin-org/pgadmin4#5533]
On a clean installation of PgAdmin in server mode, based on the official Docker image version 6.15 I have the following issue:

1. Add a shared server in chart eg:
`serverDefinitions:
  enabled: true
  servers:
    grafana:
      Name: "grafana"
      Group: "Shared"
      Host: "10.1.1.1"
      Port: 5432
      MaintenanceDB: "postgres"
      Username: "admin"
      SSLMode: "prefer"
      Shared: true
      SSLCert: "/grafana/postgresql.crt"
      SSLKey: "/grafana/postgresql.key"
      SSLRootCert: "/grafana/root.crt"
      SSLCompression: 0
`
2. Logged in as an unprivileged oauth user, I can browse to schema -> tables, click on View/Edit Data, it is showing the data.
If I click on query tool, and run a simple SELECT * from my_table (any table that has data), I am getting 0 of 0 rows
Note the connection status icon remains desperately "unplugged" as opposed to when I go to "view data".
The behaviour is the same if I click on the query tool button in the top bar.
Creating a new connection doesn't help either.
This works just fine on a non-shared server.

![pg_unplugged](https://user-images.githubusercontent.com/86559027/201934742-3251f9ae-a5e1-4260-8785-a34636c0fafd.png)

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
