### ISSUE TITLE
INSERT into sharedservers table fails when using Docker deploy with a custom Postgres 13 database

### ISSUE THREAD

**Issue by countessellis** [pgadmin-org/pgadmin4#5535]
I'm using the newest snapshot for dpage/pgadmin4 in Kubernetes, with a custom Postgres 13 database for a backend. This functionality isn't in 6.15, the newest stable image, hence using the snapshot. Everything seems to work fine except for sharing servers. When I set a server as shared, INSERT fails with the following error:

<html><body>

sqlalchemy.exc.ProgrammingError:  (psycopg2.errors.DatatypeMismatch) column "save_password" is of type  boolean but expression is of type integer
--

</body>
</html>

It looks like save_password is a bool in the sharedserver table but an int in the server table, and it's trying to insert into both as an int:

'save_password': 1

I wasn't sure if I should submit this as an issue to this repo or to dpage/pcadmin4 in github, so if I'm submitting it to the wrong repo, I apologize in advance.

**Comment by countessellis** [comment]
When I alter the column to integer, sharing the cluster is successful.

**Comment by pravesh-sharma** [comment]
While testing found this an issue - 
If user tries to save password with external database config it throws error.

Steps to reproduce -
1. Setup external config database
2. Try connecting to any database server and select **save password**
3. Disconnect from the connected server and try connecting again, it will open the password prompt with an error

Attached screenshot for reference
<img width="1791" alt="Screenshot 2022-11-17 at 2 05 36 PM" src="https://user-images.githubusercontent.com/111979571/202422042-1f404ebe-c343-4628-82f6-bf951d46882a.png">

**Comment by pravesh-sharma** [comment]
This issue is fixed.

Verified on docker container with external database for configuration.
Docker image used - https://hub.docker.com/layers/dpage/pgadmin4/2022-11-17-1/images/sha256-c208524cc9e54f6b901a22ee4a1266ebf03d2626ba2f1815028ca80a89d4cdd8?context=explore
