### ISSUE TITLE
Improve error message shown when user try to access table/db object to which user does not have access.

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#5539]
Improve error message shown when user try to access table/db object to which user does not have access.
1.Create a table with superuser e.g. postgres.
`CREATE TABLE IF NOT EXISTS public.dept
(
    deptno numeric(2,0) NOT NULL,
    dname character varying(14) COLLATE pg_catalog."default",
    loc character varying(13) COLLATE pg_catalog."default",
    CONSTRAINT dept_pk PRIMARY KEY (deptno),
    CONSTRAINT dept_dname_uq UNIQUE (dname)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.dept
    OWNER to postgres;`

2.Create normal user.
`CREATE ROLE yogesh WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  CREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'password';`

3.Connect to Server with normal user.
4.Naviagte to properties panel.
5.Select table created in first step.
6.An error message shown - Permission denied for a table. Dialogue title - INTERNAL SERVER ERROR. 
<img width="1790" alt="Screenshot 2022-11-16 at 1 54 57 PM" src="https://user-images.githubusercontent.com/16016019/202129098-f1ea5652-f9ed-42e0-a889-c6e8187928bd.png">

7.Naviagte to sql tab, Error shown - Request failed with status code 500 - Dialogue title - Failed to retrieve data from server.
<img width="1791" alt="Screenshot 2022-11-16 at 1 52 58 PM" src="https://user-images.githubusercontent.com/16016019/202129128-54cf4f81-e0b2-498e-abe6-332d5e42ed58.png">

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-11-30/
