### ISSUE TITLE
Query tool is on the wait state if user rename schema and click on generate script with schema diff

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#5542]
Candidate build v6.16

Steps
1. Create two databases with sample and sample2 
2. execute pg-sample.sql on both databases and rename some objects in sample2 database
3. Open schema diff
4. select source and target databases without selecting any schema
5. Click on compare
6.  schema diff open with objects successfully
7. Now go into sample2 database and rename schema with public2
8. Now Click on compare again
9. schema diff open with objects successfully
10. Select all objects and click on generate script
11. query tool is on the wait state

Expected Result:
Generate script should be working if the user renames the schema and click on compare

<img width="1786" alt="Screen Shot 2022-11-16 at 2 46 22 PM" src="https://user-images.githubusercontent.com/43006122/202147561-b9a40f1a-fda6-40ee-98f6-eb026c231ec2.png">
<img width="1776" alt="Screen Shot 2022-11-16 at 2 47 24 PM" src="https://user-images.githubusercontent.com/43006122/202147613-821e1984-2346-4a7c-8409-d06b108dfe88.png">

**Comment by adityatoshniwal** [comment]
Simple steps to reproduce:
1. Rename a schema.
2. Click on query tool button.

**Comment by adityatoshniwal** [comment]
Related to #5559.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-06/
