### ISSUE TITLE
Properties dialogue does not get close in case of attach partition on clicking save button.

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#5543]
1.Create a partition table.
2.Datach the partition
3.Now again open properties dialogue for partitioned table.
4.Naviagte to partition tab.
5.Click on Add icon to add new partition.
6.Select 'Attach' operation & select partition from dropdown.
7.Enter the other required values.
8.Click on save.
9.Dialogue does not get close. If user clicks again on 'Save' button, user gets error, partition already exists.
<img width="1114" alt="Screenshot 2022-11-16 at 5 28 19 PM" src="https://user-images.githubusercontent.com/16016019/202174935-255ec6a4-3f6c-40f5-91b4-b7d562fd4d91.png">

10.Also applied for death partition from partition tab of table dialogue.

**Comment by pravesh-sharma** [comment]
Tested in candidate build and issue not reproducible hence closing.
