### ISSUE TITLE
Application is not supported on this Mac

### ISSUE THREAD

**Issue by 2bf-edson-hernandez** [pgadmin-org/pgadmin4#5544]
I'm trying to distribute the [pgAdmin 4 v6.15](https://www.postgresql.org/ftp/pgadmin/pgadmin4/v6.15/macos/) using a MDM, in order to do that I need to create a .PKG, I installed the pgAdmin using the downloadable .DMG and generated the .PKG with the resultant .APP

The process isn't working for M1 neither for Intel. Trying to install the generated .PKG in the same device that has just been generated resulted in the following error:

![Cursor_and_New_Issue_·_pgadmin-org_pgadmin4](https://user-images.githubusercontent.com/110247470/202221932-505ba53e-0ff2-46bd-8e67-5a8e0cfee00c.png)

Is there any chance that someone can assist me with this matter ?

**Comment by adityatoshniwal** [comment]
@2bf-edson-hernandez pgAdmin does not support M1 yet (work in progress).
Please share Mac OS details on Intel

**Comment by 2bf-edson-hernandez** [comment]
MacOS Monterrey 12.1

**Comment by lukecater** [comment]
Don't know if this helps or not but I had the same issue with version 6.14. Issue persisted on both Intel and Silicon running Big Sur and Monterey. I tried again with 6.15 and got the same results. When I package I set the ownership to root:wheel. I receive the same error message. Out of curiosity I set the permission to the current user logged in:wheel and it immediately became available.

We have rolled back to 6.5.

As were primarily a multi user environment it would be handy to have this resolved.

**Comment by lukecater** [comment]
Update I also tried reverting back to root:wheel with 777 and that worked to just not sure of the implications of the app running with 777. It opened ;-)

**Comment by khushboovashi** [comment]
This is not related to pgAdmin but something to do with your machine. https://discussions.apple.com/thread/4607662, this might be helpful.

**Comment by lukecater** [comment]
Hello khushboovashi,
We have 130+ Macs exhibiting the same behaviour with the latest versions of pgAdmin. From my testing. The App doesn't like multi users using it. If using the DMG it works fine for the single user that downloads it. However when another user logs in get the message. Only when I chmod to 777 will it work for all users. 

Is this the same for you @2bf-edson-hernandez
