### ISSUE TITLE
Allow connection to CockroachDB Cloud

### ISSUE THREAD

**Issue by dvasdekis** [pgadmin-org/pgadmin4#5547]
Hi all,

I'm trying to connect to CockroachDB Cloud, a free distributed cloud database. The conneciton string is of the form `postgresql://username:password@free-tier8.aws-ap-southeast-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dgolden-mermaid-3114` and they provide their own root CA, which I've copied [here](https://github.com/dvasdekis/images/blob/master/cockroach_root.crt).

Everything seems OK, but upon trying to connect, I get this message:
![Error message on connect](https://raw.githubusercontent.com/dvasdekis/images/0ffe794c5aef3d2880f8322d70d1ba6c41173078/20221117_cdb_pgadmin4_issue.PNG)

It seems that CockroachDB wants me to specify the cluster parameter somehow (i.e. `options=--cluster%3Dgolden-mermaid-3114`)

Is there any way I can do this via PGAdmin4?

**Comment by adityatoshniwal** [comment]
Hi @dvasdekis,
Although pgAdmin does not support CockroachDB, there is a request #4728 to allow custom connection options. I believe once #4728 is implemented, you can proceed further.
Closing this issue.

Thanks.
