### ISSUE TITLE
Editor position is not correct when editing data from result grid

### ISSUE THREAD

**Issue by pravesh-sharma** [pgadmin-org/pgadmin4#5548]
If we change the position of result grid to left side and then edit any data the position of editor box is not correct.
Attached screenshot
<img width="1791" alt="Screenshot 2022-11-17 at 11 29 41 AM" src="https://user-images.githubusercontent.com/111979571/202368751-bf37fd0c-7e7e-479b-b126-6bced018c48f.png">

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build :
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-11-28
