### ISSUE TITLE
Save password is not working for shared server for non-privileged user.

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#5550]
Save password is not working for shared server for non-privileged user.
1.Create shared server with admin user.
2.Login with normal user & try to connect shared server.
3.Enter password & check the checkbox for 'Save Password'. Server will be connected after clicking ok.
4.Disconnect server.
5.Try reconnecting server, again password is asked.

**Comment by pravesh-sharma** [comment]
Issue already raised #5460
