### ISSUE TITLE
Running Docker in Client Mode

### ISSUE THREAD

**Issue by natohutch** [pgadmin-org/pgadmin4#5555]
I always deploy/run pgadmin using the docker container. When used for local development work it makes sense to enable client mode as opposed to server to save time setting up auth etc.

**Comment by adityatoshniwal** [comment]
@natohutch Did you try passing `PGADMIN_CONFIG_SERVER_MODE=False` to docker env params?

**Comment by natohutch** [comment]
Thanks Aditya, that's the issue I'm facing. I tried that earlier but am still told I need to input the server params.
"You need to define the PGADMIN_DEFAULT_EMAIL and PGADMIN_DEFAULT_PASSWORD or PGADMIN_DEFAULT_PASSWORD_FILE environment variables."

**Comment by adityatoshniwal** [comment]
@natohutch Even if you provide the PGADMIN_DEFAULT_EMAIL and PGADMIN_DEFAULT_PASSWORD, they will be ignored. So try passing some dummy email and password along with PGADMIN_CONFIG_SERVER_MODE.

**Comment by khushboovashi** [comment]
No response from the author.
