### ISSUE TITLE
PSQL Tool doesn't exist

### ISSUE THREAD

**Issue by nusound** [pgadmin-org/pgadmin4#5561]
When I right click on any database I don't have a PSQL Tool option. I tried to change ENABLE_PSQL option to True, but nothing happened. 

This is what I use:

Version 6.16
Application Mode Server
Current User
uroshni77@gmail.com
Browser Chrome 107.0.0.0
Operating System Linux-5.15.0-53-generic-x86_64-with-glibc2.29
pgAdmin Database File /var/lib/pgadmin/pgadmin4.db
Log File /var/log/pgadmin/pgadmin4.log

From terminal:

pg_lsclusters
Ver Cluster Port Status Owner    Data directory              Log file
14  main    5432 online postgres /var/lib/postgresql/14/main /var/log/postgresql/postgresql-14-main.log
15  main    5433 online postgres /var/lib/postgresql/15/main /var/log/postgresql/postgresql-15-main.log

Also I have another issue, maybe it's related - I can't open a .tar file PGSdmin doesn't see it...

**Comment by adityatoshniwal** [comment]
@nusound How did you set ENABLE_PSQL?

**Comment by nusound** [comment]
I opened config.py in with the terminal and changed it to true but it didn't help. Sorry, I didn't say it clearly enough in the question.

**Comment by adityatoshniwal** [comment]
> I opened config.py in with the terminal and changed it to true but it didn't help. Sorry, I didn't say it clearly enough in the question.

@nusound It is not recommended to change the config.py as it will be replaced when the new version is installed. Please refer the document - https://www.pgadmin.org/docs/pgadmin4/latest/config_py.html#the-config-py-file.
Also, did you restart the pgAdmin server after change in config?

**Comment by nusound** [comment]
Not sure. How do I do that? I mean I restarted Postgres in the terminal and
pgAdmin in the browser, is that the same?

**Comment by adityatoshniwal** [comment]
Hi @nusound,
Browser restart will not help. You need to restart your apache server where pgAdmin instance is running.
try command `systemctl restart apache2`

**Comment by nusound** [comment]
Thanks, that helped, it's there now. Cheers!

**Comment by adityatoshniwal** [comment]
@nusound Glad it worked! Don't forget to change your config based on https://www.pgadmin.org/docs/pgadmin4/latest/config_py.html#the-config-py-file else you may lose your changes.
