### ISSUE TITLE
Statistics "Total Size" sort - non-human sorting

### ISSUE THREAD

**Issue by naxels** [pgadmin-org/pgadmin4#5564]
Hi team,

In Pgadmin 4 (6.16), when you go to a Statistics tab and it has Total Size and start sorting,
it sorts the non-human way:

Example: Databases->(database)->Schemas->(schema)->Tables, Statistics tab
![image](https://user-images.githubusercontent.com/3195443/203538530-84b8ca8a-ac81-4be8-af62-68157ec2aaa8.png)

Could this be changed to human sorting?

Thank you!

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build.
