### ISSUE TITLE
pgAdmin 4 crashing after sometime

### ISSUE THREAD

**Issue by Javadebi** [pgadmin-org/pgadmin4#5565]
I'm really mad because I have lost so many SQL queries due this bug. It just crashes randomly after running SQL doesn't matter what type of SQL it is. it just crashes.

Version
6.15
Application Mode
Desktop
Current User
pgadmin4@pgadmin.org
NW.js Version
0.55.0
Browser
Chromium 92.0.4515.107
Operating System
Windows-10-10.0.20348-SP0

**Comment by akshay-joshi** [comment]
@Javadebi 
Can you please try on the latest pgAdmin 4 v6.16 as we have updated the NWjs?

**Comment by Javadebi** [comment]
@akshay-joshi Thank updating pgAdmin 4 to v6.16 actually fixed the issue.
