### ISSUE TITLE
Asking for private security contact

### ISSUE THREAD

**Issue by Frycos** [pgadmin-org/pgadmin4#5571]
Hi pgadmin team,

according to the [GitHub Coordinated Disclosure recommendations](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/about-coordinated-disclosure-of-security-vulnerabilities), I'd ask you to please provide a private communication channel to disclose a critical vulnerability. There's no SECURITY.md (security policy) in your project so this seems to be the preferred way. I also wrote to security@postgresql.org for a security contact in parallel.

Greetings!

**Comment by akshay-joshi** [comment]
@dpage 
Can you please look into this? We need to set up some security policies in GitHub.

**Comment by dpage** [comment]
security@postgresql.org is what we've always used, however I have also now setup security@pgadmin.org, and added references to that to the README in the source code, and to the website.

**Comment by adityatoshniwal** [comment]
> [security@postgresql.org](mailto:security@postgresql.org) is what we've always used, however I have also now setup [security@pgadmin.org](mailto:security@pgadmin.org), and added references to that to the README in the source code, and to the website.

@dpage Can't we add this to a SECURITY.md file? It is a widely used practice.

**Comment by andy778** [comment]
I think you have most of the information needed and more ?
https://github.com/ossf/scorecard/blob/main/docs/checks.md#security-policy
