### ISSUE TITLE
potential memory leak

### ISSUE THREAD

**Issue by clockrun** [pgadmin-org/pgadmin4#5576]
I have observed that our installation of pgadmin on Kubernetes would crash sometimes, the exit code is 137, which means out of memory. I tired to assign more memory (2 GB as limit as of now) but it doesn't help.

From Grafana, I can see that the memory usage is kept at constant level for a long time.
<img width="1846" alt="Screenshot 2022-11-26 at 12 38 21" src="https://user-images.githubusercontent.com/227283/204072582-8f9b4e50-f759-4045-955a-417af385b257.png">

At the same time, there is no large data set transfer.
<img width="1277" alt="Screenshot 2022-11-26 at 12 47 14" src="https://user-images.githubusercontent.com/227283/204072701-3bd38f67-3dc4-4d2f-823d-c65b9795531f.png">

**Comment by khushboovashi** [comment]
Please try to close the Dashboard tab and monitor. Let us know the result.

**Comment by adityatoshniwal** [comment]
@clockrun Are you saying the Grafana graphs are for server side and not the client?

**Comment by clockrun** [comment]
yes.

**Comment by akshay-joshi** [comment]
@clockrun 

Can you please test this on the latest version?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
