### ISSUE TITLE
ERD Tool - Generate SQL

### ISSUE THREAD

**Issue by OggVorbis69** [pgadmin-org/pgadmin4#5577]
# pgAdmin 4
### Version details
```
ALLOW_SAVE_PASSWORD = True
ALLOW_SAVE_TUNNEL_PASSWORD = False
APP_COPYRIGHT = "Copyright (C) 2013 - 2022, The pgAdmin Development Team"
APP_ICON = "pg-icon"
APP_NAME = "pgAdmin 4"
APP_RELEASE = 6
APP_REVISION = 16
APP_SUFFIX = ""
APP_VERSION = "6.16"
```

**Script generated from a diagram.**

Adding a string value as a default to a TEXT or VARCHAR column results in an INVALID script - the text is not surrounded by ' '.

  Example of the generated script:
```
CREATE TABLE IF NOT EXISTS a.dropme
(
    text_with_defaule text DEFAULT DefaultValue,
    vaarchal_col character varying(33) NOT NULL DEFAULT xxx
); 
```
### Observed: 
the DEFAULT values: 'DefaultValue' and 'xxx' are lacking quotes in the generated script resulting in an execution error
### Expected: 
Executable script

**Comment by adityatoshniwal** [comment]
Looks like a bug in table SQL (ERD reuses it).

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-05/

**Comment by dpage** [comment]
Hmm, I missed this issue first time round. The original behaviour is correct - the default value is an expression, not a string. Automatically quoting it is most definitely wrong.
