### ISSUE TITLE
ERD TOOL: New Table ERD functionality hangs

### ISSUE THREAD

**Issue by MichaelDBA** [pgadmin-org/pgadmin4#5584]
PGAdmin4 6.16 added a new feature to show the ERD based on clicking the ERD option on the table's popup menu.  On my large database with over 2000 tables and 1200 foreign keys all in the public schema, it hangs with message:
`Fetching schema data ......`

Nothing is running in pg_stat_activity while it shows the message above.  It already ran the SQL behind the scenes that completed pretty fast and took only a few seconds.

Using PG version 14.4 in AWS RDS.

**Comment by adityatoshniwal** [comment]
Hi @MichaelDBA,
1. How long did you wait?
2. Try changing the File->Preferences->ERD tool->Options->Table Relation Depth to 1 or 2 and see if it responds.

**Comment by MichaelDBA** [comment]
First time without changing ERD options (default=-1) I waited 2 hours before cancelling it.  I changed depth to 1 and it returned in 25 seconds.  I then changed it to 2 and it showed the fetching schema data message for about 10 minutes, and then the cursor turned into a cross of arrow pointers with nothing in the background and stayed that way for 1 hour before I cancelled that as well.

**Comment by adityatoshniwal** [comment]
@MichaelDBA Query execution is done on the PostgreSQL server, it doesn't mean that the data is available to the client immediately. There can be network latency as well if the data is huge. I am suspecting some cyclic dependency. I will add some more logging and will share the python code file to you. You can help by replacing it in your installation.

**Comment by adityatoshniwal** [comment]
Hi @MichaelDBA,
1. Please download the the attached file and remove the ext .txt and paste it to path  - `<pgadmin>/web/pgadmin/tools/erd/utils.py`. [utils.py.txt](https://github.com/pgadmin-org/pgadmin4/files/10323308/utils.py.txt)
3. Enable the logs https://www.pgadmin.org/faq/#8 and set log level to INFO.
4. Restart pgAdmin and generate ERD for table.
5. Share the logs.
6. You can then disable the logging to avoid unnecessary logs.

**Comment by khushboovashi** [comment]
No response from the author, so closing.

**Comment by MichaelDBA** [comment]
You specified to download the attached file to a directory that does not exist on my system, 
<pgadmin>/web/pgadmin/tools/erd/utils.py

I have the desktop version, not the web version.

**Comment by adityatoshniwal** [comment]
@MichaelDBA the code base for desktop or web is same. You will find the path in installed directory.
