### ISSUE TITLE
Is it possible to connect to Oracle or MySql databases with pgAdmin ?

### ISSUE THREAD

**Issue by prakash-yemineni** [pgadmin-org/pgadmin4#5588]
I want to integrate pgAdmin with MySql or Oracle database and want to create tables in those databases, is it possible ?

**Comment by adityatoshniwal** [comment]
@prakash-yemineni pgAdmin is a management tool for [PostgreSQL](https://www.postgresql.org/) and derivative relational databases such as [EnterpriseDB's](https://www.enterprisedb.com/) EDB Advanced Server.

**Comment by prakash-yemineni** [comment]
It means we cannot connect to other databases Right ?
