### ISSUE TITLE
After upgrade to 6.16, SSL logins no longer work

### ISSUE THREAD

**Issue by bruceredmon** [pgadmin-org/pgadmin4#5595]
our pgconf.hba is set to require SSL connectivity.  Connections from 6.9 worked just fine.  After upgrade to 6.16 I now receive the error that the client certificate is no longer valid when nothing has changed on the DB end.

**Comment by yogeshmahajan-1903** [comment]
Can you please try connecting same server using psql? If you are getting same error, then issue should be with certificates not with pgAdmin.

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing.
