### ISSUE TITLE
Updating server node info removes the clear saved password menu

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#5598]
I have a server with saved password. Below is the context menu.
<img width="438" alt="Screenshot 2022-12-01 at 12 21 47 PM" src="https://user-images.githubusercontent.com/31855755/204985530-c992a974-5b18-41e7-b82f-0d26b7132cda.png">

Now, I edited the server to change something and saved. The clear saved password menu disappears. It appears only on refreshing the server group node.
<img width="444" alt="Screenshot 2022-12-01 at 12 22 13 PM" src="https://user-images.githubusercontent.com/31855755/204985708-3943d31f-ab94-43c6-a75e-57c5548aa6db.png">

**Comment by pravesh-sharma** [comment]
Verified on latest candidate build. 
Env - Ubuntu 22.04
