### ISSUE TITLE
Error during connect to AWS RDS

### ISSUE THREAD

**Issue by ZedZipDev** [pgadmin-org/pgadmin4#5605]
OS:Windows 10
AWS RDS PostgreSQL : 9.6.23
PgAdmin4:6.17 
0.70.1

After the latest update I receive 

You have connected to a server version that is older than supported by pgAdmin. This may cause pgAdmin to break in strange and unpredictive ways....

```
Failed to retrieve data from the server: 
ERROR: column "backend_type" does not exist LINE 16: backend_type,

```

The previous version 6.2 worked ok.

How to fix it?

**Comment by adityatoshniwal** [comment]
@ZedZipDev pgAdmin has removed support for PG 9.6 and below from pgAdmin v6.13. So you can either stick to v6.12 or upgrade your PG server.

**Comment by ZedZipDev** [comment]
@adityatoshniwal Thank you. 
I cannot update my server because it is AWS RDS PG 9.6  and it is not in my hands.

I had and old pgAdmin and have followed proposed link to install the new version, after the installation I detected the error.
