### ISSUE TITLE
Invalid collation create script for PG15

### ISSUE THREAD

**Issue by MichaelDBA** [pgadmin-org/pgadmin4#5606]
In PG15, the CREATE SCRIPT for Collations is wrong.

```
-- PG 14: CREATE COLLATION IF NOT EXISTS sample.french  (LC_COLLATE = 'fr', LC_CTYPE = 'fr')
-- PG 15: CREATE COLLATION IF NOT EXISTS sample.french
```
You get a syntax error if you try to create the PG15 version of a collation definition.  You need to provide the provider and locale like this:
`CREATE COLLATION test.french (provider = icu, locale = 'fr');`

 - OS: Windows 11
 - Version: 6.17
 - Mode: [Desktop]
 - Browser: chrome
 - Package type: executable download from pgadmin4

Fix hint: rely on the new **pg_collation** column, **colliculocale** (PG15), instead of **collcollate** (PG14 and lower).

**Comment by nikhil-mohite** [comment]
@MichaelDBA ,

I am able to create the COLLATION with pg-15, not getting any error.
CREATE SQL from creat collation dialog.
<img width="646" alt="Screenshot 2022-12-05 at 3 38 37 PM" src="https://user-images.githubusercontent.com/69510038/205610724-099cbbd5-9403-4447-990d-ae32855831ab.png">

can you please provide more details on it?

**Comment by akshay-joshi** [comment]
@MichaelDBA 

We have fixed the issue by getting columns for PG15 like the below: 
COALESCE(c.collcollate, c.colliculocale) AS lc_collate, COALESCE(c.collctype, c.colliculocale) AS lc_type.

Now create scripts will work as it works for PG14 and lower. For other parameters like provider, deterministic, and version we have created a new feature request #5611

**Comment by MichaelDBA** [comment]
Thanks! Feel free to close this issue.

**Comment by FaharAbbasRizvi** [comment]
Tested on the latest snapshot build and working fine.
