### ISSUE TITLE
The Release notes links on the https://www.pgadmin.org/download/pgadmin-4-source-code/ page are broken

### ISSUE THREAD

**Issue by tolgaulas** [pgadmin-org/pgadmin4#5607]
I am sorry  I could not be sure wheter this should be here or in pgweb repo which has no issues :)

The release notes links which point to https://git.postgresql.org/gitweb/?p=pgadmin4.git;a=blob_plain;f=README , are all broken as they return 404 - No such project

**Comment by adityatoshniwal** [comment]
Hi @tolgaulas,

pgAdmin is moved from the postgresql git org to pgadmin-org to allow using git issues and PRs.
Here is the new link - https://raw.githubusercontent.com/pgadmin-org/pgadmin4/master/README.md

**Comment by adityatoshniwal** [comment]
@akshay-joshi Looks like release notes link is broken - https://www.pgadmin.org/download/pgadmin-4-source-code/

**Comment by dpage** [comment]
This is now fixed.
