### ISSUE TITLE
Add support for provider, deterministic, version and RULES parameter while creating Collation.

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#5611]
Add new controls for provider, deterministic, and version in the **Definition** tab of the collation dialog.

**Comment by anilsahoo20** [comment]
1. if control has some default value, then control must show that default value when we initially see the control if some other controls are not dependents on the current one. provider default value is libc, deterministic default value is true according to the Postgres documentation, but it is empty.
2. wrong sql gets generated for different combination of selection of control.
3. Rules control is getting disabled on selection of provider icu and deterministic true
4. Properties tab shows Rules as i, but no rule is given while creating the collation
5. After giving LC_TYPE, LC_collate in create dialog, it asks for locale, but as per docs, if locale given then the foremer 2 controls not needed, if former 2 given then locale not needed.


![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/f4f67492-6621-44b8-81e7-476133abfb61)
![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/cc69381a-dbc7-4bbf-9d7e-0749cfd06468)
![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/2af506e6-192f-4395-8932-9c6113a8a53f)
![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/d61590c1-e66c-46a4-9338-b08c5d18bc69)
![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/52f8ae89-3cbb-40bd-a75d-cbdfa1c5f2fd)

**Comment by anilsahoo20** [comment]
@JyotiEdb 
I found that the locale provide is empty in edit dialog, but in properties tab it is showing up. Can you check this.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-04-01/
Environment: macOs ventura 13.5.1
package: arm64
