### ISSUE TITLE
No Release File Error for Debian Bullseye Version

### ISSUE THREAD

**Issue by goktugerol-dev** [pgadmin-org/pgadmin4#5617]
From this link: https://www.pgadmin.org/download/pgadmin-4-apt/
I try to install pgadmin to **Linux Debian (Bullseye)**. And I get these errors from the terminal when I create the file repository.

![Screenshot 2022-12-08 5 05 05 AM](https://user-images.githubusercontent.com/92269361/206338851-36e611d1-a014-4b3e-acdb-31dbe3d7c92c.png)

So I cannot continue on installation.
Could you please fix the issue?

**Comment by khushboovashi** [comment]
On Thu, Dec 8, 2022 at 7:39 AM Goktug Erol ***@***.***> wrote:

> From this link: https://www.pgadmin.org/download/pgadmin-4-apt/
> I try to install pgadmin to *Linux Debian (Bullseye)*. And I get these
> errors from the terminal when I create the file repository.
>
> [image: Screenshot 2022-12-08 5 05 05 AM]
> <https://user-images.githubusercontent.com/92269361/206338851-36e611d1-a014-4b3e-acdb-31dbe3d7c92c.png>
>
> As per your logs, the first line suggests that lsb_release -cs was not
found and I don't know why, but you can replace $(lsb_release -cs) with
bullseye in the command and try again.

**Comment by goktugerol-dev** [comment]
@khushboovashi 

I tried and it gives me not found error again.

`sh: 1: bullseye: not found`
`sh: 1: cannot create /etc/apt/sources.list.d/pgadmin4.list: Directory nonexistent`

**Comment by khushboovashi** [comment]
$(lsb_release -cs) gives the codename of the current operating system, in your case it's bullseye. 
So, by replacing the $(lsb_release -cs ) with bullseye directly, it should work and the package is already exist at the location.

The one thing I noticed in your log that /etc/apt/sources.list.d directory is not exist, so try to create the directory, replace  $(lsb_release -cs) with bullseye and try.
