### ISSUE TITLE
Bug when there is a change/diff in the ACLs

### ISSUE THREAD

**Issue by kapilagarwal007** [pgadmin-org/pgadmin4#5622]
**Describe the bug**

Customer is using the schema compare process in PG Admin 4 version 6.12 today on two databases and I ran into a problem. Under the Compare button, there are two check boxes for Ignore Owner and Ignore Whitespace.
Kindly refer below screen-shot for your reference, customer has checked each of these and still list all objects as different even though the only difference is the owner of the object.

**Reproduced**

We  have tried to test this at our local machine, and we are able to pin-point the issue here as below..

When you perform any manual GRANTS on table, then the relacl value of that table (which stores the details about the Access privileges) get updated. Hence, when you run schema_diff after manually executing the grant then the value of relacl gets updated in accordance of your (permitted) user and you see a difference in schema even you choose to ignore the owner.

**To Reproduce**

Below are the sql to reproduce the issue.

create user u1;
create user u2;
create database db1;
create database db2;
\c db1 
create schema sm1;
create table sm1.account (id bigint NOT NULL, programname varchar(20) NOT NULL,CONSTRAINT accountprogram_pkye PRIMARY KEY (id))with (OIDS=FALSE) TABLESPACE pg_default;
alter table sm1.account owner to u1;
\c db2
create schema sm2;
create table sm2.account (id bigint NOT NULL, programname varchar(20) NOT NULL,CONSTRAINT accountprogram_pkye PRIMARY KEY (id))with (OIDS=FALSE) TABLESPACE pg_default;
alter table sm2.account owner to u2;
\c db1
grant ALL on TABLE sm1.account to u1;
\c db2 
grant ALL on TABLE sm2.account to u2;

<img width="2048" alt="pgadmin" src="https://user-images.githubusercontent.com/67349983/207544313-a489c7b1-cd7c-441c-9dfb-7a578700f330.png">

<img width="2048" alt="pgadmin-1" src="https://user-images.githubusercontent.com/67349983/207544351-34d5e1bb-3031-43d4-a7c2-a82edb977757.png">

**Expected behaviour**

If we are selecting ignore owner it should not show any difference in schema related to the owner output.

**Screenshots**

Attached screen shots of two comparisons that customer completed, one without the ignore options, one with the ignore options.
Each compare shows the same information.

![PostgresCompareIgnore](https://user-images.githubusercontent.com/67349983/206417415-9b8d13d0-4c86-4b92-bc58-6ea20409e100.png)

![PostgresCompareAll](https://user-images.githubusercontent.com/67349983/206417464-3aa6bfc4-7182-4104-b7fd-4ebeff40f79f.png)

**Desktop (please complete the following information):**
 - OS: centos7
 - Version:  pgadmin4 6.12
 - Mode: server
 - Browser (if running in server mode): chrome 
 - Package type: RPM

**Comment by naveedkarajgi** [comment]
Hi Team, 

Below are the sql to reproduce the issue.

`
create user u1;
create user u2;
create database db1;
create database db2;
\c db1 
create schema sm1;
create table sm1.account (id bigint NOT NULL, programname varchar(20) NOT NULL,CONSTRAINT accountprogram_pkye PRIMARY KEY (id))with (OIDS=FALSE) TABLESPACE pg_default;
alter table sm1.account owner to u1;
\c db2
create schema sm2;
create table sm2.account (id bigint NOT NULL, programname varchar(20) NOT NULL,CONSTRAINT accountprogram_pkye PRIMARY KEY (id))with (OIDS=FALSE) TABLESPACE pg_default;
alter table sm2.account owner to u2;
\c db1
grant ALL on TABLE sm1.account to u1;
\c db2 
grant ALL on TABLE sm2.account to u2;
`

<img width="2048" alt="Do not ignore owner" src="https://user-images.githubusercontent.com/85238476/206555514-1ee3c993-5000-4477-941c-86c6e30ba658.png">
<img width="2048" alt="Ignore owner" src="https://user-images.githubusercontent.com/85238476/206555560-49b807fa-0a83-4fe7-916c-2fb4c3dde00f.png">

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-05/

**Comment by dhananjayjejurkar** [comment]
Hi @FaharAbbasRizvi , 
3days back @akshay-joshi mentioned about 6.19 version. However, your above-mentioned link redirects us to the 6.18 version. Hence, can we ask the customer to use the 6.18 latest snapshot for testing it?

**Comment by adityatoshniwal** [comment]
@dhananjayjejurkar The above link is for nightly builds. It is not recommended to use nightly builds unless required as it may contain untested code. 6.19 will be released by next week.

**Comment by akshay-joshi** [comment]
@dhananjayjejurkar 

The link provided by Fahar is of the snapshot(nightly) build, so it will show version 6.18 as we change the version when we will create the candidate build.
