### ISSUE TITLE
Actions performed on tree node does not update context/ menu bar options

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#5626]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Actions performed on tree node does not update context/ menu bar options

**To Reproduce**

1. Create a table with trigger.
2. Consider all triggers are disabled.
3. Enable all triggers from context menu.
4. Check context menu updated or not.
5. Enable All is still enabled.

**Expected behavior**

Expected Enable all should be disabled and Disable all should be enabled.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

<img width="746" alt="Screenshot 2022-12-09 at 2 08 08 PM" src="https://user-images.githubusercontent.com/16016019/206660250-f3bcd1e4-234c-4ea9-8444-548ec37758a5.png">
<img width="744" alt="Screenshot 2022-12-09 at 2 07 23 PM" src="https://user-images.githubusercontent.com/16016019/206660272-7eb652bd-60c1-4619-804a-8a0bedf0bea1.png">

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-05/
