### ISSUE TITLE
Trigger submenu 'Enable All' is enabled though all triggers are enabled.

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#5627]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

**To Reproduce**

1. Create a table with trigger.
2. Enable the all trigger.
3. Refresh the page.
4.Trigger submenu 'Enable All' is enabled though all triggers are enabled after refresh also.
**Expected behavior**

Trigger submenu 'Enable All' should be disabled as all triggers are enabled.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**
<img width="740" alt="Screenshot 2022-12-09 at 2 02 25 PM" src="https://user-images.githubusercontent.com/16016019/206659267-eb49332c-c05f-478b-853a-53810f7a5b0d.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey] - Does not matter.
 - Version: [e.g. 6.15] - 6.16
 - Mode: [e.g Desktop or Server] - Any mode
 - Browser (if running in server mode): [e.g. chrome, safari] - Does not matter
 - Package type: [e.g. RPM, DEB, Python, Container, etc.] - Does not matter

**Additional context**

**Comment by FaharAbbasRizvi** [comment]
This is fixed and tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-03/
