### ISSUE TITLE
Listening on the wrong scheme for port 443?

### ISSUE THREAD

**Issue by khteh** [pgadmin-org/pgadmin4#5628]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**
I deploy a kubernetes `Statefulset` and found the following log:
```
NOTE: Configuring authentication for SERVER mode.

pgAdmin 4 - Application Initialisation
======================================

----------
Loading servers with:
User: me@email.com
SQLite pgAdmin config: /var/lib/pgadmin/pgadmin4.db
----------
Added 1 Server Group(s) and 1 Server(s).
[2022-12-04 06:08:56 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-12-04 06:08:56 +0000] [1] [INFO] Listening at: http://[::]:443 (1)
[2022-12-04 06:08:56 +0000] [1] [INFO] Using worker: gthread
[2022-12-04 06:08:56 +0000] [93] [INFO] Booting worker with pid: 93
```
Isn't the `http` scheme wrong for port `443`?
**Describe the bug**

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]: Ubuntu 22.10
 - Version: [e.g. 6.15] latest docker image tag
 - Mode: [e.g Desktop or Server] Kubernetes cluster `Statefulset`
 - Browser (if running in server mode): [e.g. chrome, safari] Chrome
 - Package type: [e.g. RPM, DEB, Python, Container, etc.] Container

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
@khteh 
Can you please share your Kubernetes config file? It seems port mentioned is 443 causing this issue.

**Comment by khteh** [comment]
> @khteh Can you please share your Kubernetes config file? It seems port mentioned is 443 causing this issue.

Updated my post.

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing.
