### ISSUE TITLE
BigAnimal "authentication is aborted"

### ISSUE THREAD

**Issue by sszhao1020** [pgadmin-org/pgadmin4#5629]
**Describe the bug**
We can’t establish BigAnimal session at pgAdmin. The screen recording as below:

https://user-images.githubusercontent.com/89435179/206669508-21aa7f56-90ad-42df-a562-b5808df5246a.mp4

**To Reproduce**
Register -> Deploy Cloud Instance -> Choose BigAnimal and complete the authentication
then **close the prompted window**.
I will be shown authentication successfully but then **Authentication is aborted**.

**Expected behavior**
I would like to see authentication is successful

My pgAdmin version 
![image](https://user-images.githubusercontent.com/89435179/206670618-e5918f6e-aed1-4683-b018-d6e353f539fc.png)

If I didn't close the prompted window, it seems authentication will be successful

**Comment by yogeshmahajan-1903** [comment]
Working fine.
