### ISSUE TITLE
AWS ALB Ingress

### ISSUE THREAD

**Issue by khteh** [pgadmin-org/pgadmin4#5632]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**
How to get this to work behind AWS ALB ingress? Tried all combinations of (HTTP / HTTPS) but none of them work. There is no target registered with the ALB target group at all.

**Describe the bug**

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
@khteh 
Could you please elaborate the issue? How are you deploying the pgAdmin? If possible , kindly share deploy config.

**Comment by adityatoshniwal** [comment]
No response from the user. Closing.
