### ISSUE TITLE
The real type is NaN. Error querying data.

### ISSUE THREAD

**Issue by ChenQing-888** [pgadmin-org/pgadmin4#5634]
**Describe the bug**

pgAdmin4 error when real type is NaN :Cannot read properties of undefined (reading 'notifies')
**To Reproduce**

1.  Add data with real type NaN to the table
2.  SELECT * FROM [table]
3.  See the error

**Expected behavior**

I have a pgAdmin4 version 6 server, query real type NaN, can display the data.

**Error message**
<html>
<body>
<div class="jss29" style="box-sizing: inherit; height: 843.984px; color: rgb(212, 212, 212); font-family: Roboto, &quot;Helvetica Neue&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.14994px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(33, 33, 33); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="dock-layout" style="box-sizing: inherit; overflow: hidden; position: relative; height: 843.984px;"><div class="dock-box dock-vbox" data-dockid="+1" style="box-sizing: border-box; align-items: stretch; display: flex; flex-direction: column; height: 843.984px; position: absolute; width: 1196px; min-width: 404px; min-height: 6px; flex: 200 1e+06 200px;"><div class="dock-panel dock-style-default" data-dockid="+6" style="box-sizing: border-box; background: rgb(255, 255, 255); border: none; color: rgba(0, 0, 0, 0.85); position: relative; min-width: 200px; min-height: 1px; flex: 200 1e+06 200px;"><div class="dock dock-top" style="box-sizing: border-box; display: flex; height: 421.5px; position: absolute; width: 1196px; overflow: hidden; flex-direction: column; border-radius: inherit;"><div class="dock-content-holder" style="box-sizing: inherit; flex: 1 1 auto; height: 0px;"><div class="dock-content dock-content-top dock-content-animated" style="box-sizing: inherit; transition: none 0s ease 0s; height: 390.5px; width: 1196px; display: flex; flex-direction: row; margin-left: -1196px;"><div id="id-messages" role="tabpanel" aria-hidden="false" class="dock-tabpane dock-tabpane-active" aria-labelledby="rc-tabs-2-tab-id-messages" style="box-sizing: inherit; flex: 0 0 auto; height: 390.5px; outline: none; overflow: hidden; position: relative; width: 1196px; color: rgb(212, 212, 212); background-color: rgb(33, 33, 33);"><div class="dock-pane-cache" style="box-sizing: inherit; height: 390.5px; width: 1196px;"><div class="jss52" tabindex="0" style="box-sizing: inherit; outline: none; color: rgb(212, 212, 212); height: 390.5px; padding: 5px 10px; overflow: auto; font-size: 12px; font-family: &quot;Source Code Pro&quot;, SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; user-select: text; white-space: pre-wrap; background-color: rgb(33, 33, 33);">Cannot read properties of undefined (reading 'notifies')</div></div></div><div id="id-notifications" role="tabpanel" aria-hidden="true" class="dock-tabpane" aria-labelledby="rc-tabs-2-tab-id-notifications" style="box-sizing: inherit; flex: 0 0 auto; animation-duration: 0.5s; animation-name: dock-fadeOut; height: 0px; outline: none; overflow: hidden; position: relative; width: 1196px; color: rgb(212, 212, 212); background-color: rgb(33, 33, 33); visibility: hidden;"><div class="dock-pane-cache" style="box-sizing: inherit; height: 0px; width: 1196px;">
</div></div></div></div></div></div></div><div class="dock-box dock-fbox" style="box-sizing: border-box; align-items: stretch; display: flex; pointer-events: none; z-index: 1060; height: 843.984px; position: absolute; width: 1196px;"></div><div class="dock-box dock-mbox dock-mbox-hide" style="box-sizing: border-box; align-items: stretch; display: flex; height: 843.984px; width: 1196px; z-index: 1080; animation: 0.2s ease 0s 1 normal none running dock-mbox-hide; opacity: 0; pointer-events: none; visibility: hidden; position: absolute;"></div></div></div><div class="MuiBox-root jss34 jss30" style="box-sizing: inherit; display: flex; flex-wrap: wrap; border-top: 1px solid rgb(74, 74, 74); align-items: center; user-select: text; background-color: rgb(48, 48, 48); color: rgb(212, 212, 212); font-family: Roboto, &quot;Helvetica Neue&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.14994px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">
</body>
</html>

**Desktop (please complete the following information):**
 - OS: Windows-10-10.0.18363-SP0
 - Version: 6.17
 - Mode:Desktop
 - Browser (if running in server mode): Chromium 107.0.5304.88
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Screenshots**

![20221212153856](https://user-images.githubusercontent.com/71283077/206988767-7c355979-b030-4ee5-a01c-56879c964621.png)

![20221212152844](https://user-images.githubusercontent.com/71283077/206986333-7688b4f5-e40e-40fc-abfb-12a0ae900191.png)

**Comment by nikhil-mohite** [comment]
Hi @ChenQing-888 ,
I am not able to reproduce the issue with the given steps, can you please share a screenshot of the error?
