### ISSUE TITLE
Please update boto3/botocore dependencies

### ISSUE THREAD

**Issue by ShaheedHaque** [pgadmin-org/pgadmin4#5640]
**Describe the bug**

The dependencies on boto3, and possibly botocore, are very old. The result is that when I try to install what I need using pip3, pip3 ends up spending more than a minute walking back thorough dozens, or possibly hundereds of version of boto3 looking for one that will satisfy pgAdmin4.

**To Reproduce**

1. Install something that depends on boto3 and pgAdmin4.
2. Watch pip3 download many versions of boto3 till it satisfies the requirement in DEPENDENCIES.

**Expected behavior**

It would be very useful if the DEPENDENCIES entry for boto3 and botocore were updated, so that the pip3 resolution process is reasonably short. (I suppose, more generally, it would be helpful if at intervals, the wider set were updated too).

**Error message**

No errors, just lots of output like this:
```
Collecting boto3
  Downloading boto3-1.26.27-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 2.3 MB/s eta 0:00:00
  Downloading boto3-1.26.26-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 3.4 MB/s eta 0:00:00
  Downloading boto3-1.26.25-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 3.6 MB/s eta 0:00:00
  Downloading boto3-1.26.24-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 3.3 MB/s eta 0:00:00
  Using cached boto3-1.26.23-py3-none-any.whl (132 kB)
  Using cached boto3-1.26.22-py3-none-any.whl (132 kB)
  Using cached boto3-1.26.21-py3-none-any.whl (132 kB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of boto3 to determine which version is compatible with other requirements. This could take a while.
  Using cached boto3-1.26.20-py3-none-any.whl (132 kB)
  Using cached boto3-1.26.19-py3-none-any.whl (132 kB)
  Using cached boto3-1.26.18-py3-none-any.whl (132 kB)
...
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.10
 - Mode: Server
 - Package type: Python

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
This is working fine. Verified on candidate build.
