### ISSUE TITLE
Geometry Viewer no popup or no data on click on geometry

### ISSUE THREAD

**Issue by pmcdonough-fp** [pgadmin-org/pgadmin4#5641]
When using the "Geometry Viewer" in pgadmin v 6.17, clicking on a drawn geometry does 1 of 2 things:
1) Nothing - no popup or anything  - this may have been the case for 6.15 only though
2) Window pops up, but the data is blank.

When using earlier versions, clicking on the drawn geometry will bring up row data in a popup window.

**To Reproduce**
First make sure postgis is installed in your database or install it.

Open query window and execute query:
SELECT 'some text' text_field, 
       ST_GEOMFROMTEXT( 'POLYGON((-118.16616991320866 34.02459478089593,-118.16614592877986 34.02467476110228,-118.16506040529346 34.024449074993974,-118.16508439069494 34.024369095004296,-118.16616991320866 34.02459478089593))', 4326) AS sample_geom

Choose the sample_geom column in "Data Output" tab.  Choose the geometry viewer to view all geometry data.  Click on the geometry ( Hubbard Street ).

**Expected behavior**

A popup opens with column text_field and "some text" as a value.

**Error message**
No error messages

**Screenshots**
Old:
![image](https://user-images.githubusercontent.com/54870413/207471947-b9a8a663-5129-44c3-9fe2-61b8b4c321c2.png)

New: just no popup - click and nothing pops up.

**Desktop (please complete the following information):**
Windows 10 Pro - 10.0.19042 Build 19042

PGAdmin
Version 6.17
Application Mode Desktop
Current User pgadmin4@pgadmin.org
NW.js Version 0.70.1
Browser Chromium 107.0.5304.88
Operating System Windows-10-10.0.19042-SP0

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-04/
