### ISSUE TITLE
importing data from pgadmin.db sqlite database to postgresql

### ISSUE THREAD

**Issue by ayadahm** [pgadmin-org/pgadmin4#5642]
Hi 
After introducing pgadmin4 ver. 16.6 where one can use an external postgresql as a database for pgadmin4 instead of sqlite.
I wonder if there is a smooth way for importing the existing data from sqlite to postgreSQL?
There is many third parties software to migrating but   I wonder if there is a native way for doing that in PostgreSQL ?

Many thanks for the great work.

Regards
Ayad Mohamed

**Comment by adityatoshniwal** [comment]
@ayadahm Migrating the SQLite DB to PostgreSQL DB is out of the scope of pgAdmin. You will get better help on stackoverflow or PostgreSQL support.
Closing the ticket.
