### ISSUE TITLE
ERD one to one relationship

### ISSUE THREAD

**Issue by pedroska777** [pgadmin-org/pgadmin4#5648]
**Describe the solution you'd like**
Currently ERD not showing 1-1 relationship.

**Describe alternatives you've considered**
I applied Unique on the foreign key but still at the time of ERD it is showing as 1 to many.

**Additional context**

**Comment by adityatoshniwal** [comment]
Duplicates #5128.
Please note, there is no change in the SQL for 1-1 relationship. It is same as 1-M, only difference is the Fk is unique.

**Comment by pedroska777** [comment]
This comment was for modification in ERD visualization. ERD shows 1-1
relationship as 1 to many.
