### ISSUE TITLE
Please provide the libpq-dev package along with the libpq5 in the ftp.postgresql.org repository

### ISSUE THREAD

**Issue by AlexeySalmin** [pgadmin-org/pgadmin4#5650]
**Describe the bug**

Currently the https://ftp.postgresql.org repo provides the libpq5 package but not the matching libpq-dev. This results in errors when trying to install the libpq-dev on Ubuntu 20.04 because the version from the Ubuntu repo is too old.

As a workaround you can force-downgrade the libpq5 to match the Ubuntu version, but potentially this may cause issues with the pgadmin4 because it relies on this package as well.

`sudo apt-get install libpq5=12.5-0ubuntu0.20.04.1`

The best solution is to always provide the matching version of the "-dev" package along with the library, this way they're always in sync.

**To Reproduce**

```
$ sudo apt-get install libpq-dev
. . .
The following packages have unmet dependencies:
 libpq-dev : Depends: libpq5 (= 12.12-0ubuntu0.20.04.1) but 15.1-1.pgdg20.04+1 is to be installed
```

```
$ apt-cache policy libpq5
libpq5:
  Installed: 15.1-1.pgdg20.04+1
  Candidate: 15.1-1.pgdg20.04+1
  Version table:
 *** 15.1-1.pgdg20.04+1 500
        500 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4/main amd64 Packages
        100 /var/lib/dpkg/status
     15.0-1.pgdg20.04+1 500
        500 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4/main amd64 Packages
     14.5-1.pgdg20.04+1 500
        500 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4/main amd64 Packages
     14.4-1.pgdg20.04+1 500
        500 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4/main amd64 Packages
     14.3-1.pgdg20.04+1 500
        500 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4/main amd64 Packages
     14.2-1.pgdg20.04+1+b1 500
        500 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4/main amd64 Packages
     14.2-1.pgdg20.04+1 500
        500 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4/main amd64 Packages
     14.1-2.pgdg20.04+1 500
        500 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4/main amd64 Packages
     12.12-0ubuntu0.20.04.1 500
        500 http://fr.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     12.2-4 500
        500 http://fr.archive.ubuntu.com/ubuntu focal/main amd64 Packages

$ apt-cache policy libpq-dev
libpq-dev:
  Installed: (none)
  Candidate: 12.12-0ubuntu0.20.04.1
  Version table:
     12.12-0ubuntu0.20.04.1 500
        500 http://fr.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     12.2-4 500
        500 http://fr.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Expected behavior**

The package libpq-dev 15.1-1.pgdg20.04+1 is installed.

**Error message**

` libpq-dev : Depends: libpq5 (= 12.12-0ubuntu0.20.04.1) but 15.1-1.pgdg20.04+1 is to be installed`

**Additional context**

https://stackoverflow.com/questions/63785462/problems-instaling-libpq-dev-in-ubuntu-20-04

**Comment by mirumu** [comment]
I've been running into this too on Ubuntu 22.04. Even when force downgraded, Ubuntu will upgrade libpq5 back to the https://ftp.postgresql.org/ version the next time updates apply. This automatically uninstalls libpq-dev once again. Need to apply a hold on libpq5 to stop the cycle. I've been developing code that links against libpqxx with libpq as a dependency so need the dev package.
