### ISSUE TITLE
Fails to start on Kubernetes

### ISSUE THREAD

**Issue by splix** [pgadmin-org/pgadmin4#5653]
Trying to run 

Trying to run it with kubernetes v1.24.6 + containerd. It doesn't start and gives only the following error:

```
/entrypoint.sh: line 65: /venv/bin/python3: Operation not permitted
/entrypoint.sh: line 88: /venv/bin/python3: Operation not permitted
/entrypoint.sh: exec: line 96: /venv/bin/gunicorn: Operation not permitted
```

Then the pod stops. There seems to be no way to inject any other command to check what's going on inside the container.

I'm using [rowanruseler/pgadmin4](https://github.com/rowanruseler/helm-charts/tree/master/charts/pgadmin4 ) Helm chart which is based on [dpage/pgadmin4](https://hub.docker.com/r/dpage/pgadmin4) Docker.

The only configuration I have is:
```
persistentVolume:
  existingClaim: MYPV

containerPorts:
  http: 8080

env:
  variables:
    - name: PGADMIN_DISABLE_POSTFIX
      value: true
```

Also tried different `securityContext` and `containerSecurityContext` options but no luck.

**Comment by splix** [comment]
I was able to sneak into the container. It seems that there is something wrong with `python3`:

```
/pgadmin4 $ /venv/bin/python3 version
sh: /venv/bin/python3: Operation not permitted
```

Or if run it via `kubectl exec`:
```
OCI runtime exec failed: exec failed: unable to start container process: exec /usr/bin/python3: operation not permitted: unknown
```

I've tried different versions of the Docker and a runnable Python3 was found only at `docker.io/dpage/pgadmin4:4.15`. I.e. the version `docker.io/dpage/pgadmin4:4.16` gives the error. But version `4.15` works. All versions in `6.x` and `5.x` are failing with the same error

**Comment by splix** [comment]
The problem is in the line:
```
    setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/python3.10 && \
```

It seems that it doesn't work with some of the security features of the modern Kubernetes.

If I remove that line and make a new Docker image it can be started.

**Comment by adityatoshniwal** [comment]
@dpage Any idea on this?

**Comment by dpage** [comment]
Some quick Googling indicates that a pod security policy may be required to enable CAP_NET_BIND_SERVICE: https://www.golinuxcloud.com/kubernetes-securitycontext-capabilities/#Create_Pod_Security_Policy

I'm not overly familiar with Kubernetes though so don't know enough to comment authoritatively. I'd suggest having @yogeshmahajan-1903 try it out.

**Comment by splix** [comment]
I can confirm it works with `CAP_NET_BIND_SERVICE`. Previously, it wasn't allowed in my Kubernetes cluster but I think it should work with default config.

Helm config should have the following to run it:
```
containerSecurityContext:
  enabled: true
  capabilities:
    add:
      - NET_BIND_SERVICE
```

**Comment by yogeshmahajan-1903** [comment]
CAP_NET_BIND_SERVICE us used to add or remove Linux Capabilities from the Pod and Container so the container can be made more secure from any kind of intrusion. This gives the /usr/bin/python3* binary the ability to bind to privileged ports without being root.
However there are some known limitation, can be checked [here](https://docs.docker.com/engine/security/rootless/).
We will not revert this changes, hence closing the issue.

**Comment by ralph089** [comment]
Please reconsider putting that additional capability into the Dockerfile. Right now, the Image is not usable for us, because of the required `NET_BIND_SERVICE` capability. We run the application under an unprivileged port, but we need to give the container that capability, otherwise the application does not start.

**Comment by louisgls** [comment]
As a temporary fix you can build your custom image and remove the setcap : 
`FROM dpage/pgadmin4:latest

USER 0
RUN setcap -r /usr/bin/python3.10
USER pgadmin
`

**Comment by ralph089** [comment]
@louisgls thank you. This is exactly what we did, unfortunately this increases maintenance effort, what we try to avoid.
