### ISSUE TITLE
Schema diff creates owner changes when 'ignore owner' selected

### ISSUE THREAD

**Issue by king2** [pgadmin-org/pgadmin4#5655]
I have several databases, each of them belongs to some user (dev user and dev database and few prod databases each with its own user/website).

Use case for schema diff is:
 - make changes in dev database (and dev code)
 - check changes
 - do schema diff and apply schema changes to prod databases to make them compatible with new website code

But when I trying to do schema diff it ignories owner difference when comparing, but still generates SQL code with owner changes.
I do not want all other databases to have dev user as owner, I want just to add fields, change comments and similar things to be applied to target databases, having owner set to its original database user.

I think it is an error, because it can give inconsistent/unexpected results - changed owner in changed tables, and old owner in unchanged ones (cannot imagine use case for this behavior).

So, maybe PgAdmin should:
 - or respect 'ignore owner' tick when comparing AND when generating SQL code
 - or have separate ticks, for example 'ignore owner when comparing' and 'ignore owner in script' or something like this

I saw similar issues, but such issues was closed without any explanations :(

**Comment by akshay-joshi** [comment]
Hi @king2 

Are there any ACL changes as well for the objects that show the owner statement? We have a similar kind of issue #5622. 
Can you please check and confirm so that we can mark this one as a duplicate?

**Comment by nikhil-mohite** [comment]
related #5622

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-05/
