### ISSUE TITLE
[ UX ] ( ERD ) : Dialogs could honor the resize efforts/preference of the user

### ISSUE THREAD

**Issue by daguitosama** [pgadmin-org/pgadmin4#5659]
**Stop having to keep resizing Dialogs to fit content once you have done it the for first time**

When a Dialog shows up in the ERD tool, and the user resize that dialog window to give more room to the content, that size preference should not be thrown away when closing the dialog, should be collected and used when the user open up a new dialog, giving it as default new size. That way the user did not need to keep resizing those Dialogs again and again every time.

**Alternatives I have considered**
I will explain thinking in a component composition way, hopping that there is actually a Dialog component.

New additions to the Dialog component to achieve the desired effect.
 - new resize observer which trigger onResize fn
 - onResize: sizePreference = currentSize
 - onMounted: if sizePreference then currentSize = sizePreference
 
 If people find this useful i will be glad to do the job and make a PR, so please let me know.

**Additional context**

In this capture the user has resized the Dialog to fit all relevant content
<img width="1280" alt="Screenshot 2022-12-19 at 16 51 08" src="https://user-images.githubusercontent.com/34744883/208531384-b348fa6d-33b8-4648-a34f-e0ec2b51a5b2.png">

But next time the user opens the Dialog that size preference and effort is gone
<img width="1280" alt="Screenshot 2022-12-19 at 16 52 04" src="https://user-images.githubusercontent.com/34744883/208531556-438d0c33-fd30-4a7d-9bb4-997157c48604.png">

**Comment by adityatoshniwal** [comment]
@daguitosama You can raise a PR if you're willing to work on it.

**Comment by daguitosama** [comment]
O thanks, don't have much time lately but will do my best to find a spot to collaborate. PG Admin is awesome.

**Comment by daguitosama** [comment]
Hi im trying to spin up the dev environment, but im finding a little difficult, I have done nothing yet but following the Readme instructions till point 6 and I have all ready 9K file changes in Git, what's the best place to ask for help with the dev setup ?

**Comment by khushboovashi** [comment]
Have you followed the steps under "Configuring the Python Environment"?

**Comment by pravesh-sharma** [comment]
It will be taken care of in #3241.
