### ISSUE TITLE
Border is added for dropdown once option is selected

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#5661]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

In a dialogue containing multiple dropdown, when value is selected a border is added around it.

**To Reproduce**

1. Open create database dialogue
2. Navigate to Definition tab, try selecting value for dropdown.
3. 
**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

<img width="701" alt="Screenshot 2022-12-19 at 1 27 18 PM" src="https://user-images.githubusercontent.com/16016019/208609300-b3242b9f-6acc-472f-9809-ebe1521d4ed8.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by pravesh-sharma** [comment]
Tested on candidate [build](https://developer.pgadmin.org/builds/2023-01-09-2/) and is fixed.
