### ISSUE TITLE
Save results to file (F8 Save) writes empty CSV file 

### ISSUE THREAD

**Issue by Adventurer2021** [pgadmin-org/pgadmin4#5670]
**Description:**        

Query produced 3,789,839 records (16 columns). However, when I attempted to write the output using PgAdmin4 (F8 Save results to file) the process went into the "Downloading results..." (which took about 2.5 minutes) and then the file manager window opened to select destination folder and file name and file type. I chose Microsoft Excel comma separated file type. I clicked "save" and the window closed and I was back to PgAdmin4 but the file written had zero data in it. I received no errors from pgAdmin4. 

Running queries that produced much less data out I've had no issues writing the file. I can create the output file using [SQLWorkbench](https://www.sql-workbench.eu/) without issue. 

**pgAdmin4 "About":**

Version 6.15
Application Mode: Desktop
Current User: [pgadmin4@pgadmin.org](mailto:pgadmin4@pgadmin.org)
NW.js Version: 0.55.0
Browser: Chromium 92.0.4515.107
Operating System: Windows-10-10.0.22621-SP0
pgAdmin Database File: C:\Users\rick\AppData\Roaming\pgadmin\pgadmin4.db
Log File: C:\Users\rick\AppData\Roaming\pgadmin\pgadmin4.log

**PostgreSQL Information:**
pgAdmin4 : Version 6.15
PostgreSQL version: 14.6

**DB Information:**
Backends: 3
Xact committed: 41491283
Xact rolled back: 26
Blocks read: 225704661
Blocks hit: 257119624
Tuples returned: 2243809230
Tuples fetched: 1260856171
Tuples inserted: 99624501
Tuples updated: 7569412
Tuples deleted: 3123
Size: 430.91 GB

**System information:**
Operating system: Microsoft Windows 11 Pro Version	10.0.22621 Build 22621
System Manufacturer	Dell Inc.
System Model	XPS 8940
System Type	x64-based PC
System SKU	09C5
Processor	11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz, 2501 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	Dell Inc. 2.10.0, 9/14/2022
Installed Physical Memory (RAM)	64.0 GB
Total Physical Memory	63.6 GB
Available Physical Memory	47.7 GB
Total Virtual Memory	67.6 GB
Available Virtual Memory	51.6 GB
Page File Space	4.00 GB
**SSD storage:**
Drive	C:
Description: Local Fixed Disk
Compressed: No
File System: NTFS
Size:	3.64 TB (4,000,007,057,408 bytes)
Free Space: 2.61 TB (2,866,484,924,416 bytes)
Volume Name: Local Disk

**Comment by adityatoshniwal** [comment]
@pravesh-sharma Can you please test this once?

**Comment by pravesh-sharma** [comment]
Issue seems to be related to chrome as I am able to download file of around 900 MB with all data. 
A [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1159676&q=CSV&can=2) has already been raised for it.

**Comment by adityatoshniwal** [comment]
Duplicates #3369.
