### ISSUE TITLE
Import/Export section problem

### ISSUE THREAD

**Issue by onurkanbakirci** [pgadmin-org/pgadmin4#5672]
**About the bug**

In the `Import/Export Data` tab's `Columns` section, if there is no column selected pgAdmin should automatically add all columns by default as described below of the input as a hint text. 

<img width="703" alt="Screen Shot 2022-12-23 at 12 21 31" src="https://user-images.githubusercontent.com/50163185/209309713-de7497b1-7fb6-4006-818d-801818b2bdad.png">

But this not work. If i dont select column and then press the `OK` button, pgAdmin throws an error.

<img width="703" alt="Screen Shot 2022-12-23 at 12 25 22" src="https://user-images.githubusercontent.com/50163185/209309799-5d7f047b-f1f0-46df-a101-9fb72e4f8d4e.png">

**Comment by pravesh-sharma** [comment]
Hi @onurkanbakirci,

can you please share the pgAdmin version. Also, which mode(server/desktop) you are using?

**Comment by pravesh-sharma** [comment]
This issue is already fixed in #4957 on version 6.9, hence closing.
