### ISSUE TITLE
Quert Tool fails to syntax highlight WITH keyword

### ISSUE THREAD

**Issue by gavanschneider** [pgadmin-org/pgadmin4#5676]
pgAdmin4 Version 6.18 (4280.88)
Desktop mode
iMac; AppleM1; MacOS 13.1 (22C65)

Replication:
Using Query Tool, type SQL statement, and include WITH clause

Issue:
The "WITH" keyword does not get syntax highlighting, but 
the statement is otherwise ok
Attached screenshot says it better

Seasons greetings
[pgAdmin4_with_syntax_highlight_issue.pdf](https://github.com/pgadmin-org/pgadmin4/files/10299294/pgAdmin4_with_syntax_highlight_issue.pdf)

**Comment by pravesh-sharma** [comment]
Issue is fixed on latest release of codemirror and also tested on latest version of pgAdmin. Attached screenshot for reference.
<img width="823" alt="Screenshot 2023-06-02 at 5 52 13 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/6e1c236a-ef1c-46c2-b9b3-8a779679fd82">
