### ISSUE TITLE
Backup feature not works correctly

### ISSUE THREAD

**Issue by onurkanbakirci** [pgadmin-org/pgadmin4#5677]
**Describe the bug**

When i try to backup base table as an sql file in pgAdmin 4, it's not works correctly. It's only backup some metadata instead table info and data inside of table(i have already selected include data option before backup).

<img width="449" alt="Screen Shot 2022-12-25 at 18 36 03" src="https://user-images.githubusercontent.com/50163185/209474011-c1302563-71f2-44f8-92e5-d4fee6d9ddf1.png">

**To Reproduce**

<img width="700" alt="Screen Shot 2022-12-25 at 18 39 28" src="https://user-images.githubusercontent.com/50163185/209474095-f809b336-7e52-4647-9aa0-a70296f6bc0a.png">

<img width="697" alt="Screen Shot 2022-12-25 at 18 38 00" src="https://user-images.githubusercontent.com/50163185/209474071-e1d8465f-e57a-4efa-b4ea-dd665b3c2651.png">

<img width="703" alt="Screen Shot 2022-12-25 at 18 38 07" src="https://user-images.githubusercontent.com/50163185/209474083-22e935dd-be6f-40cf-8cda-3e0ba131dac1.png">

**Comment by adityatoshniwal** [comment]
Hi @onurkanbakirci,

This works fine for me (tested 6.18). You can also check the command in process details. Below are the screenshots:
<img width="709" alt="Screenshot 2022-12-26 at 11 24 18 AM" src="https://user-images.githubusercontent.com/31855755/209508954-ffe682f3-5207-49df-8295-d452bce9ec6b.png">
<img width="1107" alt="Screenshot 2022-12-26 at 11 25 14 AM" src="https://user-images.githubusercontent.com/31855755/209508951-2fef35b0-481e-4a46-95eb-644faeb74b88.png">

**Comment by onurkanbakirci** [comment]
Hi @adityatoshniwal 

Thank's for your response. Is your table base table? Because this problem occurs in base tables not regular tables.

**Comment by adityatoshniwal** [comment]
@onurkanbakirci 
In that case, please share the table DDL.

**Comment by khushboovashi** [comment]
Closing as no response from the author.
