### ISSUE TITLE
Simpler Sidebar & Decluttering

### ISSUE THREAD

**Issue by sphinxrave** [pgadmin-org/pgadmin4#5682]
**Describe the solution you'd like**

PGAdmin4 is overtly verbose about database features that are used extremely rarely, making it hard to navigate a larger database, resulting in an overall unfriendly sidebar. Configuring default view by ticking and unticking Node Type is too indirect, and once hidden, showing/finding a Node again is also difficult. PGAdmin4 could consider one of the following:

- A 'show all' toggle which will show all Node types that has been 'hidden'. This can sit next to the Query panel / View Data / Filtered Rows buttons at the top of the sidebar. 
- A 'hide(/show) this Node type' button in the Right Click Context menu of each Node to hide the node or show the node. 
- Start off by default-hiding some Node Types that are commonly hidden. Most users are not going to touch Languages, Extensions, FTS Dictionaries or Synonyms. 
   - As an advanced ask, remember which nodes have been hidden at a path level, so you can keep the Trigger Node open for one schema and closed for another schema (etc). 
 

**Describe alternatives you've considered**

Considered designs from IntelliJ, DBeaver, and other DB tools. Some don't care to build UI for pg-specific internal objects, so PGadmin4 is definitely better, but IntelliJ for instance puts views and tables first, which is where I go 99% of the time when I'm opening a db tool, so it'll be nice to have a usage-prioritized/user-centric design instead of a utilitarian listing.

**Comment by anilsahoo20** [comment]
Hi @sphinxrave 
You could try Preference>Browser>Dislplay> Show empty object collections? If turned off, then all object collections which are empty will be hidden from browser tree.
