### ISSUE TITLE
get "Too many values to unpack(expected 2)" error when click on database 

### ISSUE THREAD

**Issue by geohuz** [pgadmin-org/pgadmin4#5684]
click the database name on the left and I always get "Too many values to unpack(expected 2)" popup and right click on db properties dialog, can't type any thing inside the dialog, it looks readonly.

The pgversion is 15

**Comment by adityatoshniwal** [comment]
@geohuz What is the pgAdmin version?

**Comment by geohuz** [comment]
@adityatoshniwal, it is the latest version: pgadmin version 6.18

**Comment by adityatoshniwal** [comment]
@geohuz Can you
1. try disconnect and re-connecting the server.
2. Please also share the pgAdmin logs.
3. Share database DDL.

**Comment by geohuz** [comment]
@adityatoshniwal, I just tried quit pgadmin and reconnect the server, the database which has the popup is an old db created in postgresql14, I took in a db dump in sql format and rerun it on 15, and the popup doesnt' happen in the default db with 15. Unfortunately I dont' know how to take pgadmin log, here is the screenshot:
<img width="1012" alt="Screenshot 2023-01-06 at 21 24 22" src="https://user-images.githubusercontent.com/730770/211022117-85aa33a8-61bf-4c9b-b4d7-64c0d9f90e95.png">

when I click the ``life_org`` db I got the popup, but it is ok for geohuz&postgres db. And it is still ok to unfold the life_org tree and operate on objects inside it.

**Comment by adityatoshniwal** [comment]
@geohuz Can you please try one more thing? Remove the server from pgAdmin and add again. Let us know the result.

**Comment by geohuz** [comment]
@adityatoshniwal I tried to remove the server and recreated, unfortunately the problem doesn't get resolved.

**Comment by adityatoshniwal** [comment]
@geohuz Please share the pgAdmin logs.

**Comment by khushboovashi** [comment]
Can you please provide the logs ?  Go to File -> Runtime -> View Log.

**Comment by geohuz** [comment]
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3"
Runtime Config File: "/Users/geohuz/Library/Preferences/pgadmin/runtime_config.json"
pgAdmin Config File: "/Applications/pgAdmin 4.app/Contents/Resources/web/config.py"
Webapp Path: "/Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
pgAdmin Command: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3 -s /Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
Environment: 
  - MallocNanoZone: 0
  - USER: geohuz
  - COMMAND_MODE: unix2003
  - __CFBundleIdentifier: org.pgadmin.pgadmin4
  - PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
  - LOGNAME: geohuz
  - SYSTEM_VERSION_COMPAT: 0
  - SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.V4lSBTU6YR/Listeners
  - HOME: /Users/geohuz
  - SHELL: /bin/zsh
  - TMPDIR: /var/folders/jz/hdk4ttl90y519ynv27w6rx8w0000gn/T/
  - __CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
  - XPC_SERVICE_NAME: application.org.pgadmin.pgadmin4.137585379.137596968
  - XPC_FLAGS: 0x0
  - PGADMIN_INT_PORT: 64643
  - PGADMIN_INT_KEY: f1144664-dac2-4dee-bdad-b6bce4ee93c2
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.003 Sec
2023-01-25 18:51:11,321: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance.

 * Serving Flask app 'pgadmin' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 3.211 Sec
------------------------------------------
Total launch time of pgAdmin4: 3.304 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:64643/?key=f1144664-dac2-4dee-bdad-b6bce4ee93c2

**Comment by nikhil-mohite** [comment]
@geohuz ,

Did you take the log after the error or before the error?

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing the issue.
