### ISSUE TITLE
When using a passwordless key for ssh tunnel, the password prompt shouldn't appear

### ISSUE THREAD

**Issue by aseques** [pgadmin-org/pgadmin4#5686]
I am using a rsa key to use the ssh tunnel feature, so I can connect to the postgres host from a known ip address. Everything works, but every time I open the connection there's a prompt asking for the identity file password.
Since it doesn't have any I click Ok and connects, but I cannot save the password (since none is written) 
![imatge](https://user-images.githubusercontent.com/555542/209936882-a4df21a5-d1a3-48d5-a13a-e72efea91bc1.png)
Ideally pgadmin should either detect that the identity file is passwordless or allow to save an empty password.

**Comment by adityatoshniwal** [comment]
Hi @aseques,
The save password for SSH tunnel is disabled by default for security reasons.
To enable it, set ALLOW_SAVE_TUNNEL_PASSWORD = True in config_system.py and restart pgAdmin. https://www.pgadmin.org/docs/pgadmin4/development/config_py.html

Thanks.
