### ISSUE TITLE
Unable to setup pgadmin on subdomain of website in docker images.

### ISSUE THREAD

**Issue by shivamkb17** [pgadmin-org/pgadmin4#5689]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Hi, I recently Installed pgadmin in through docker-compose, pgadmin working perfectly through the IP and Port, But When I used the NGINX reverse proxy, Sometimes it gives error of too much redirect, or sometime, pgadmin starts loading for long time. also after refreshing the page, account logged out, again and again, I have tried to fix it, Also read complete documentation, But I didn't find any solution. 

**To Reproduce**

1. Go to 'Setup Docker Installation, and Setup reverse proxy using the NGINX Proxy manager.'
2. Click on 'Go to your subdomain'
3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/76581658/210031685-6523cfef-b86a-4597-b05c-d02c17c52df7.png)
![image](https://user-images.githubusercontent.com/76581658/210031747-e4ae50e8-7bfa-4393-a1fd-1830bc0cc377.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Version: Latest and 6.15
 - Mode: server
 - Browser (if running in server mode): Chrome and firefox
 - Package type: docker

**Additional context**
My Docker
[pgadmin-docker-compose.txt](https://github.com/pgadmin-org/pgadmin4/files/10323057/pgadmin-docker-compose.txt)
 Compose file

**Comment by adityatoshniwal** [comment]
Hi @shivamkb17,
Many users are using a similar setup and it is working fine for them. Make sure you've followed all steps from https://www.pgadmin.org/docs/pgadmin4/6.18/container_deployment.html#http-via-nginx.
Please share the nginx conf as well.

**Comment by shivamkb17** [comment]
I am using NGINX Proxy manager, Now my issue is resolved. 
I only turn off the force SSL and HTTP/2 Support and HSTS .
