### ISSUE TITLE
Close windows by escape key

### ISSUE THREAD

**Issue by emoxam** [pgadmin-org/pgadmin4#5691]
No ability to close windows by escape key, it clould be usefull instead of pointing the mouse cursor.
Thanks

**Comment by adityatoshniwal** [comment]
@emoxam Which window exactly? Screenshot?

**Comment by emoxam** [comment]
Server properties for example

**Comment by adityatoshniwal** [comment]
@emoxam Server properties is not a modal window (which generally allows escape close). It is a floating window which can be docked with other tabs.

**Comment by emoxam** [comment]
Group properrties, add new server, enter DB password dialog, anter app password dialog i guess there is now windows i can close by escape! Can we have hotkey to close it ?

**Comment by emoxam** [comment]
is "add Close window by escape key shortcut" ok ?

**Comment by khushboovashi** [comment]
Subject should be "Create shortcut for object properties dialog."

**Comment by avispt** [comment]
I have a big need for it at the search model, would love to have it
