### ISSUE TITLE
The latest version is not available on Arch Linux and pacman

### ISSUE THREAD

**Issue by amirhossein-fzl** [pgadmin-org/pgadmin4#5694]
The latest version of pgadmin that is in pacman is version 4.30. Please update in arch linux and pacman. You can see the package in the link below and make sure...

https://archlinux.org/packages/community/x86_64/pgadmin4/

Thankfull ❤️🙏

**Comment by dpage** [comment]
The pgAdmin team do not maintain Arch Linux packages. Please request an update from them directly - the maintainer’s name is listed in the link you provided.
