### ISSUE TITLE
schema compare problem

### ISSUE THREAD

**Issue by MichaelDBA** [pgadmin-org/pgadmin4#5695]
Please add another filter option: DCL.
I got thousands of tables with a thousand table differences only due to different DCL definition on the respective schemas.  This not only includes ownership differences, but especial DCLs like GRANTS.  Please enable us to filter those out when computing table diffs.

Also, if you can enable saving the output to file, that would be very helpful.

**Comment by akshay-joshi** [comment]
Related to #5759

**Comment by akshay-joshi** [comment]
Will be implemented as a part of #5759
