### ISSUE TITLE
Role is used instead of username when adding a new server

### ISSUE THREAD

**Issue by pr2git** [pgadmin-org/pgadmin4#5702]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When **adding a new server** in the list we have to fill in the (Register -> Server...)  we have to fill in the: Username and role

Problem when connecting to the server the role is sent as instead of the Username, so I am unable to connect to server that I need to add into PgAdmin.

The problem doesn't happens with already existing servers.

**To Reproduce**

1. In group right click choose add Server...
2. Fill in the needed information into Connection tab
3. Define the Username (myuser)
4. Define a role (in my exemple role is dba)
5. Save the setup
6. Connect to the server
7. Try to access for exemple to postgres DB

ERROR:

FATAL: LDAP authentication failed for user "dba" connection to server at "XXXXXXXXXX" (123.123.123.123), port 5432 failed: FATAL: no pg_hba.conf entry for host "XXXXXXXXXX", user "dba", database "postgres", SSL off

Problem is that my user is not "dba" but "myuser"  "dba" is the role my user should use.

On already existing servers this problem doesn't pop-up it happens only on newly added server.
So the problem is at the creation of the server into PgAdmin 6.18 role is save for the Username field.

**Expected behavior**

The field Username must be used and not the role one.

**Error message**

FATAL: LDAP authentication failed for user "dba" connection to server at "XXXXXXXXXX" (123.123.123.123), port 5432 failed: FATAL: no pg_hba.conf entry for host "XXXXXXXXXX", user "dba", database "postgres", SSL off

user defined is not dba but myuser, in my case dba is the role I need to use.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04.1 LTS
 - Mode: Desktop
 - Package type: installed from apt

**Comment by pr2git** [comment]
Hi, I was happy to see a new release of PgAdmin but this major bug is not yet resolved and include in it.

I use my login and then I need to take another role to grant the read-only, read-write or DBA role this is no longer possible since you send the role instead of the login name to the remote server.
Do you realise that it is no longer possible to create a valid new server that we can connect to in PgAdmin GUI?
Only existing servers are working fine.

This is a Major bug making PgAdmin totally unusable in my organisation.

**Comment by adityatoshniwal** [comment]
After digging, possible solution would be to run `SET ROLE` command after connecting with username just how psql tool works uses roles.

**Comment by pr2git** [comment]
Please check how was stored data when creating a new host in version 6.17 for exemple.
In 6.17 (and below) you store the Username properly and the Role the option. The role is to perform automaticly the set role. This was always working fine in PgAdmin until 6.17 (even in version 4).

Since 6.18 you are no longer storing the Username but you are storing the role as Username (this is the major bug) in PgAdmin internal server DB which is wrong. So when connection you are using the role and no longer the username!

Former created servers are working fine only newly created servers are affected by this bug. So the problem is in the Create Server function that now wrongly store the field Role as Username,  Username must be used to login and Role must be used to create the set role!

I insist on already defined servers in PgAdmin (the one created before 6.18 the connection is working fine!). With the newly added server PgAdmin is trying to connect to the server with the role defined and not the username (which is wrong).

So this is a pure PgAdmin GUI bug that mix up Username and Role when storing a new server. All the logics to connect is still correct.  If it was a bug in the connection logic I would no longer be able to use the existing servers.

To explain you, when you connect to one of our servers with a login you get no access right on any database, you explicitly need to perform a set role. And the access role defined cannot be used to login, they are pure access role.

So I am connecting with my login: pr2 which is authenticated with the LDAP and then PgAdmin perform a set role dbro;

Here is how my username is defined:

CREATE ROLE pr2 WITH
  LOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;
  
GRANT dbro TO pr2;

Here is how the role dbro is defined:

CREATE ROLE dbro WITH
  NOLOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

So I connect to the server with pr2 and get only login right then set role dbro to get access (of course we have several possible role).

Now PgAdmin is storing the Role as username for newly added server and then try to log with the role instead of the Username which is wrong. Already defined servers are not affected by this bug introduced since 6.18 only newly added servers are.

The main advantage of PgAdmin was this was foreseen by default for a given Username to perform the role defined in the GUI.

**Comment by pravesh-sharma** [comment]
https://user-images.githubusercontent.com/111979571/216249568-eb5c681e-ccd1-42ab-b734-8d64d816916e.mov

@adityatoshniwal  Tried testing on today's snapshot and facing this issue.

**Comment by adityatoshniwal** [comment]
@pravesh-sharma Once merged, please also test shared servers.

**Comment by pravesh-sharma** [comment]
Issue fixed. Also checked for shared servers.
Tested on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-03/
