### ISSUE TITLE
Different minimum password lengths in use

### ISSUE THREAD

**Issue by cklein05** [pgadmin-org/pgadmin4#5705]
**Different parts of the application operate with different minimum password lengths**

Both _Change User Password_ dialog and _Password Reset Form_ (after clicking _Forgotten your password?_) require passwords which are at least 8 characters long. In contrast, the _User Management_ dialog (as an Admin user) as well as `setup.py` (while creating the initial Admin user) happily consume passwords that are at least 6 characters long.

The documentation of the _Change User Password_ dialog [(see here)](https://www.pgadmin.org/docs/pgadmin4/6.18/change_user_password.html) recommends to use at least 6 characters for a password:

> Ensure that your password is an adequate length; 6 characters should be the absolute minimum number of characters in the password.

**To Reproduce**

1. Create a new internal user with a password which is _only_ 6 characters long.
2. Log in as that user and change its password using the _Change Password_ dialog.
3. The _Change User Password_ dialog requires a password which is at least 8 characters long.
4. The _Reset Password Form_ also requires password which is at least 8 characters long. 
5. As an Admin user in _User Management_ dialog you could still set this user's password to a token >= 6 characters long.

**Expected behavior**

All parts of the application should recommend and enforce passwords with the same length. Ideally, the minimum length of passwords for internal pgAdmin 4 users **should be configurable** in `config.py` et al.

**Comment by nikhil-mohite** [comment]
If the user changed the  `SECURITY_PASSWORD_LENGTH_MIN=10` then it will be applied to the `change password dialog` only, not to other dialogs like the `User management ` password field. need to add config to make it consistent throughout the application.

**Comment by adityatoshniwal** [comment]
In that case, lets not add it to config.py.

**Comment by pravesh-sharma** [comment]
> In that case, lets not add it to config.py.

Can we keep SECURITY_PASSWORD_LENGTH_MIN to some other file?

**Comment by dpage** [comment]
Err, no. config.py is exactly where it needs to go, along with the other security config, that can then be overridden in config_local.py, config_distro.py, and config_system.py.

Figuring out how to get the value to the frontend is the correct solution - not moving it elsewhere.

**Comment by yogeshmahajan-1903** [comment]
@pravesh-sharma 
Also please make sure config parameter is considered while setting up initial user account. Currently it is hardcoded in user_info.py.

**Comment by nikhil-mohite** [comment]
Resolved, Verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-02/
OS: CentOS 7
Mode: Server Mode
