### ISSUE TITLE
pgadmin4 v6 very poor rendering performance

### ISSUE THREAD

**Issue by ShaolanTech** [pgadmin-org/pgadmin4#5708]
DID your guys realy use pgadmin, or just release a new version without rechecking ? after upgrade to v6, the sql editor keeps in a very-low-responding mode, for example, i typed a letter "a", and a second later, it would be slowly displayed on the screen. 
use js to simulate desktop environment is realy a bad idea, or  just makes pgadmin a website as default!
so please work harder on the user's experience!

**Comment by adityatoshniwal** [comment]
@ShaolanTech,

pgAdmin is an open source free to use tool, has limited resources and depends on code contributions. Although we have hundreds of automated test cases running we do release candidate builds for testing before the actual release and expect from users like you to test and raise any concerns before the release.
You can raise the issues with steps and pgAdmin team will fix it based on available resources and priority. Or, you are free to raise a pull request with the fix.

Thanks.
