### ISSUE TITLE
pgAgent jobs steps ands schedule nodes don't show on Mac 12.1 pgAdmin 6.18

### ISSUE THREAD

**Issue by robe2** [pgadmin-org/pgadmin4#5716]
**Describe the bug**

On Windows 10 pgAdmin 6.18 when I expand a pgAgent job step , I see nodes Schedules and Steps.
When expand the same job in Mac 12.1 using same version of pgAdmin, no steps show

**To Reproduce**

1. Go to pgAgent
2. Click on a Job
3. Click the arrow next to the job to expand to see the schedule and steps

**Expected behavior**
Should show steps as it does on windows, like below

![WindowsExpandShowsSteps](https://user-images.githubusercontent.com/4734450/210828935-2d49b100-635f-49d3-b65f-19baf69b325d.png)

On Mac doesn't expand the tree

![MacExpandDoesNothing](https://user-images.githubusercontent.com/4734450/210829179-8192e2ba-b5cc-4097-9e45-466acee9c1ee.png)

This is for any job, but the above is a specific sample

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OSX 12.1
 - Version: [6.18], does the same for earlier versions as well, so not a new issue
 - Mode: Desktop
 - Package type: DMG from https://www.postgresql.org/ftp/pgadmin/pgadmin4/v6.18/macos/

**Additional context**

The server with pgAgent on it is PostgreSQL 15 Windows 2022 Server (but I suspect it is not specific to the server).

**Comment by robe2** [comment]
Okay it's one of my friends having the issue.  I'll have her check her logs on Mac.

**Comment by robe2** [comment]
[pgAdmin4Mac.log](https://github.com/pgadmin-org/pgadmin4/files/10376450/pgAdmin4Mac.log)
Attached is her log file

**Comment by khushboovashi** [comment]
Can you please provide the logs ? 

Go to File -> Runtime -> View Log.
In the log, you'll find something like - Application Server URL: http://127.0.0.1:51547/?key=b2a3bb1a-9b1b-43b9-a9b3-7089784aad26.
Copy the URL and paste in browser and run.
Now open the browser console and try to expand the job.
Share the browser console logs.

**Comment by robe2** [comment]
<img width="908" alt="Screen Shot 2023-01-26 at 20 53 19" src="https://user-images.githubusercontent.com/4734450/215032776-44ae7f2f-b3f7-48af-aefd-dbe3e4842b32.png">

Is the above what you had in mind.  

When you expand the job, nothing comes out of the console but what that shows.  Or should there be a file somewhere?

**Comment by nikhil-mohite** [comment]
@robe2 ,

We will need to check this on call, please let us know your availability.

**Comment by robe2** [comment]
@nikhil-mohite  you have time on Monday.  I'm in East Coast and so if the person having the issue.

I think she is available too on Monday anytime from 10 AM - 5 PM EST.  If you are available I can send you or you can send me an invite.

**Comment by robe2** [comment]
@nikhil-mohite I spoke with Haiyao - she said anytime this week 9 AM - 5PM Boston time = 2 PM - 10 PM UTC

**Comment by nikhil-mohite** [comment]
@robe2 ,

Can we schedule a call on 1st March, between 2 PM to 3 PM UTC? If it is suitable for you I will share the meeting invite.

**Comment by adityatoshniwal** [comment]
No response from user. Closing.
