### ISSUE TITLE
Is it necessary to be connected to a database to use the ERD-Tool?

### ISSUE THREAD

**Issue by Markus-** [pgadmin-org/pgadmin4#5721]
I am on Mac OS and installed pgadmin4 6.18 through brew.

I just want to use the ERD-Tool to create a new database. I just can open it if I am connected to a server and an existing database. Otherwise the ERD-Tool is greyed out.

Works as designed?

Regards
Markus

**Comment by adityatoshniwal** [comment]
@Markus- ERD needs certain information like schemas, data types from a database. So, yes. A database is needed for creating the ERD. You can create an empty DB and create ERD on it.
Thanks.
