### ISSUE TITLE
Remove signal based implementation for desktop application to improve performance.

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#5723]
**Describe the solution you'd like**

With the latest pgAdmin4 we are using native menus for desktop applications, so now we can remove the signal base implementation for runtime menus  View logs, Zoom In, Zoom Out, etc.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-01/

OS - macOS monterey 12.6.3
mode - Desktop
