### ISSUE TITLE
Treenode will not expand

### ISSUE THREAD

**Issue by kflo-coder** [pgadmin-org/pgadmin4#5726]
Within the past 6 months, my installations of pgAdmin will no longer expand to show me the database(s) within a particular server.  This appears to be a client issue on my Windows PC only, as others can use pgAdmin on their machines to connect to the same servers.  I have tried uninstalling/reinstalling pgAdmin multiple times.  I have attached a short screen capture video demonstrating the issue.  I have enabled logging, but cannot identify anything that looks like an error or exception within them.  I'm obviously amenable to providing any additional logs or information to help resolve this issue.

https://user-images.githubusercontent.com/122488315/211916526-905646fe-5ea0-4261-8876-a432845d61cb.mp4

**Comment by khushboovashi** [comment]
Which version of pgAdmin are you using?

**Comment by kflo-coder** [comment]
Using the latest version as of this date (6.18)
![image](https://user-images.githubusercontent.com/122488315/212116944-3a6086f4-b16d-463f-93db-0c2f57459d7a.png)

Also of note is that this first started happening several months ago (version 6.14 or thereabouts, I think, but not positive).  When it did, I uninstalled the new version and re-installed the old one.  Doing so did not fix the issue.

**Comment by khushboovashi** [comment]
Can you please provide the logs ? 

Go to File -> Runtime -> View Log.
In the log, you'll find something like - Application Server URL: http://127.0.0.1:51547/?key=b2a3bb1a-9b1b-43b9-a9b3-7089784aad26.
Copy the URL and paste in browser and run.
Now open the browser console and try to expand the server.
Share the browser console logs.

**Comment by kflo-coder** [comment]
Could you please point me to the logging documentation that you'd like me to be following?  I enabled logging, but after following the steps you provided, nothing additional was written to the log.  It's late on a Friday night, so perhaps I made a mistake, but send me the instructions just so I can double-check...

Thank you!

**Comment by nikhil-mohite** [comment]
@kflo-coder ,

We will need browser console logs (UI logs), for that you need to follow the above mentioned steps.

**Comment by kflo-coder** [comment]
My apologies; misread the instructions.  Here's the console log (Edge browser is my current default browser).  Seems clear that the problem is the 401 I'm encountering.  I've tried a few of suggestions mentioned when Googling that issue, to no avail thus far.  Suggestions?

[127.0.0.1-1675209310569.log](https://github.com/pgadmin-org/pgadmin4/files/10552044/127.0.0.1-1675209310569.log)

**Comment by nikhil-mohite** [comment]
@kflo-coder,

can you please try with latest version v6.19?

**Comment by kflo-coder** [comment]
@nikhil-mohite 
I had already installed version v6.19 without success.  Same result as with the others.

**Comment by adityatoshniwal** [comment]
@kflo-coder Please follow https://github.com/pgadmin-org/pgadmin4/issues/5726#issuecomment-1398274214 for 6.19.

**Comment by kflo-coder** [comment]
Sure, here you go...
[127.0.0.1-1675645383931.log](https://github.com/pgadmin-org/pgadmin4/files/10636559/127.0.0.1-1675645383931.log)

**Comment by adityatoshniwal** [comment]
Looks like some issue at https://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/browser/static/js/node.js#L178

**Comment by yogeshmahajan-1903** [comment]
@kflo-coder ,

Could you please check this on latest version 6.20 released yesterday?

**Comment by kflo-coder** [comment]
@yogeshmahajan-1903 
Version 6.20 did not resolve the issue.  Attached is the log from the latest version.
[127.0.0.1-1676303223402.log](https://github.com/pgadmin-org/pgadmin4/files/10723810/127.0.0.1-1676303223402.log)

**Comment by kflo-coder** [comment]
@yogeshmahajan-1903 **Please advise.**  This issue is NOT resolved, despite your marking it as such without confirming with me in advance.

**Comment by nikhil-mohite** [comment]
Hi @kflo-coder,

We tried but unable to reproduce the issue, can you please try removing the server group and try adding again ?
If you are still facing issue please share the logs located at the location mentioned here [https://www.pgadmin.org/faq/#8](https://www.pgadmin.org/faq/#8)
