### ISSUE TITLE
Debian package for bullseye does not define a dependency to <= python-3.9

### ISSUE THREAD

**Issue by stefanhh0** [pgadmin-org/pgadmin4#5727]
**Describe the bug**

The debian bullseye package for pgadmin4, that is hosted in: 
https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/bullseye/dists/pgadmin4/

depends on python-3.9, however, that is not reflected in the package dependencies. 
It is possible to uninstall python-3.9 in debian on testing and unstable and that breaks the pgadmin4 package.

**To Reproduce**

```
$ dpkg -I /var/cache/apt/archives/pgadmin4-server_6.18_amd64.deb
[...]
Depends: python3, libpq5 (>= 11.0), libgssapi-krb5-2
```

**Expected behavior**

A dependency to python3 (<= 3.9) would prevent that problem 

**Desktop (please complete the following information):**

 - OS: Debian GNU/Linux bookworm/sid
 - Version: 6.18
 - Mode: Desktop
 - Package type:DEB

**Additional context**

https://github.com/pgadmin-org/pgadmin4/issues/4466
https://github.com/pgadmin-org/pgadmin4/issues/5681

**Comment by dpage** [comment]
We depend on the system-default version of python3, and the control file is the same for all versions of Python/Debian, hence no version number is included at present.

As noted in other tickets, we do not directly support testing versions of OS releases as we have limited resources and they are a moving target. We would probably accept a patch that checks the version of Python during the build, and includes it in the control file automatically for the current platform, but that won't help a testing user who then tries to install on a slightly newer version of the OS than we built on.
