### ISSUE TITLE
View Create Script not allowed

### ISSUE THREAD

**Issue by MichaelDBA** [pgadmin-org/pgadmin4#5731]
You need to be a superuser or a user with CREATEDB role to be able to view the CREATE SCRIPTS when you right-mouse click on an object to see its definition.  I log in with a role that is a member of a role with the CREATEDB role, but it still will not allow the user to see  the CREATE SCRIPT unless that user has the CREATEDB role directly.

1. Go to any schema and click functions, then right click on any function and select SCRIPTS.  The only choice available is SELECT SCRIPT, not CREATE SCRIPT.

I would expect the user to be able to see the CREATE SCRIPT since that user is a member of a role with the CREATEDB system role.

 - OS: Windows 11]
 - PGADMIN version 6.18
 - Mode: Desktop
- PG Version 14.5

**Comment by khushboovashi** [comment]
Hi,

I am not able to reproduce this issue. Can you please share the DDL of the role and the parent member role also ?

**Comment by MichaelDBA** [comment]
CREATE ROLE dbadmin_grp WITH INHERIT NOBYPASSRLS CREATEDB IN ROLE pg_read_all_data, pg_read_all_settings, pg_read_all_stats, pg_stat_scan_tables, pg_write_all_data, pg_signal_backend;
GRANT TEMPORARY ON DATABASE mydatabase TO dbadmin_grp;

CREATE ROLE dbadmin WITH PASSWORD 'mypassword' LOGIN INHERIT NOBYPASSRLS CONNECTION LIMIT -1;
GRANT dbadmin_grp to dbadmin;

-- PGADMIN does not allow dbadmin to view create script unless CREATEDB is directly assigned to him.
-- SO I DO THIS AS A WORKAROUND UNTIL THIS IS FIXED.
ALTER ROLE dbadmin WITH CREATEDB;

**Comment by akshay-joshi** [comment]
Hi @MichaelDBA 

I am not able to reproduce the issue with the latest version 6.20. I have run the same SQL provided by you and logged in to the database server as a 'dbadmin' user. Please refer to the screenshots below: 
<img width="614" alt="Screenshot 2023-02-21 at 12 08 35 PM" src="https://user-images.githubusercontent.com/1632882/220267147-fe66c68f-7f3d-45aa-9feb-df05432bd247.png">

<img width="829" alt="Screenshot 2023-02-21 at 12 09 06 PM" src="https://user-images.githubusercontent.com/1632882/220267209-1d555864-352b-4888-9931-e0c6ec4a9d4b.png">

<img width="423" alt="Screenshot 2023-02-21 at 12 09 32 PM" src="https://user-images.githubusercontent.com/1632882/220267249-e38219c6-7a2d-422a-b19a-39fb08773427.png">

**Comment by akshay-joshi** [comment]
Closing the issue due to no response from the author.
