### ISSUE TITLE
pgAdmin users who are authenticated can access each other's directories and files by providing relative paths

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#5734]
**Describe the bug**
pgAdmin users who are authenticated can access each other's directories and files by providing relative paths.

**To Reproduce**

1. Start pgAdmin in the Server mode. You need to create two users 'user1@xyz.com' and 'user2@xyz.com'.
2. Login as user1 and export some servers. Provide the file name as 'servers.json'
3. Login as user2 and Import servers with user2 and set the JSON file name as '../user1_xyz.com/servers.json'.
4. It reads the file and shows the servers to import.

**Expected behavior**
By providing relative paths, users should not be able to access each other's directories and files.

**Desktop (please complete the following information):**
 - OS: [All]
 - Version: [6.18]
 - Mode: [Server]

**Comment by yogeshmahajan-1903** [comment]
Issue is verified on candidate build. Users gets Access Denied error on accessing each other's directory.
