### ISSUE TITLE
Change wording of new connection error "Crypt key missing" or prompt user to create master password

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [pgadmin-org/pgadmin4#5735]
## **Describe the solution you'd like**

When pgAdmin is newly installed and a master password is not initially set, and if the user attempts to add a new connection, a cryptic error message "Crypt key missing" shows up.

Improve this so that it's clear that a master password should be set up.

## **Describe alternatives you've considered**

Alternate solution would be to display a pop-up prompting the user to create a master password at that time instead of displaying the error message.

## **Additional context**

This issue is common enough that it gets a highly rated answer (which I also just upvoted today) https://stackoverflow.com/questions/70000324/what-is-crypt-key-missing-error-in-pgadmin4-and-how-to-resolve-it

**Comment by manngo** [comment]
Seriously, who thought “Crypt key missing” was a suitable way of saying “Please set master password”? Maybe it should have said “You should have set a master password, but not that you haven’t, bad luck”.

**Comment by memark** [comment]
Lost a good amount on time on this today, trying all kinds of weird settings. Then eventually googling and ending up on the above SO question and answer.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-15/

Env - macOS Monterey 12.6.3 (Desktop mode)
