### ISSUE TITLE
cpu usage is high

### ISSUE THREAD

**Issue by vincen** [pgadmin-org/pgadmin4#5737]
Environment:
mac os version: 12.16.2. cpu:i7-2.5GHz, Mem: 16G.
pgAdmin4 version: 6.18

Description:
cpu usage is high when pgAdmin4 is running.
like the picture below, the CPU usage remains at 40% ~ 50% 

<img width="823" alt="image" src="https://user-images.githubusercontent.com/378205/212466046-4c6b7fc6-62a4-40cc-bab4-c61a3c414a2c.png">

**Comment by khushboovashi** [comment]
Can you please close the Dashboard tab and try ?

**Comment by vincen** [comment]
> Can you please close the Dashboard tab and try ?

yes, it's useful for me, and thank you for your help.
