### ISSUE TITLE
pgAdmin 4 Database: field setting.value too short

### ISSUE THREAD

**Issue by cklein05** [pgadmin-org/pgadmin4#5746]
**The field `value` of table `setting` in pgAdmin's database may be too short**

I'm seeing these errors in PostgreSQL's log: (this pgAdmin uses PostgreSQL for it's database)

```
[...] ERROR:  value too long for type character varying(1024)
[...] STATEMENT:  INSERT INTO setting (user_id, setting, value) VALUES (3, 'Browser/Layout', '{"floating":[], [...]
```
Seems like the length of the JSON value for setting `Browser/Layout` may exceed 1024 characters (in my case it consists of 1077 characters). Actually, this setting never gets saved in that case.

**To Reproduce**

1. Statement fails whenever a property of the `Browser/Layout` setting has changed
2. e. g. Clicking on one of the tabs _Dashboard_, _Properties_, _SQL_, etc.

**Expected behavior**

Column should be wide enough to hold even long JSON values.

**Solutions**

This pgAdmin installation uses PostgreSQL for it's database, so changing the columns width to (e. g.) 2048 resolves the problem (of course). You could consider changing the `setting` table's `value` column width to a much larger value. Alternatively, you could use something like an _unbounded_ column (`text` in PostgreSQL, SQLite should have something similar - aren't SQLite's datatypes no more than syntactic sugar anyway?)

**Comment by nikhil-mohite** [comment]
The browser layout is getting rest to the default value with an external database (PostgreSQL).
 1. Open the older pgAdmin 4 version and change some browser layouts.
 2. Now open the latest pgAdmin 4 version, and check the browser layout changes are now reset to default and that changes done earlier were not preserved. (snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-25/)

**Comment by nikhil-mohite** [comment]
Resolved, Verified on the latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-31/
OS: macOS Monterey 12.6
Mode: Desktop (Expretal DB Postgres)
