### ISSUE TITLE
Schema Diff (version 6.19) no content refresh in Source, Target and Difference fields.

### ISSUE THREAD

**Issue by ddjuric1** [pgadmin-org/pgadmin4#5747]
Schemes Differences - "Walking" through the Objects which are different on schemas with the up-arrow and down-arrow buttons, the content of the  Source, Target and Difference fields does not change, as it changes when we mouse-click to Object.

**Comment by ddjuric1** [comment]
@akshay-joshi  what Not Refined means in this in this particular case? Should I add more clarification?
Browsing trough shema differences can be very tiring if you have to do it with the mouse instead of the up/down keys.

Regards

**Comment by akshay-joshi** [comment]
@ddjuric1 "Not Refined" is a project. We do refinement of the new issues logged and place them in the appropriate projects.

**Comment by nikhil-mohite** [comment]
Resolved, Verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-16/
OS: macOS Monterey 12.6
Mode: Desktop

**Comment by nikhil-mohite** [comment]
Resolved, and verified on candidate build 6.21: https://developer.pgadmin.org/builds/2023-03-01-1/
OS: macOS Monterey 12.6
Mode: Desktop
