### ISSUE TITLE
Support PostgreSQL deployment on google cloud from pgAdmin.

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#5750]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nikhil-mohite** [comment]
Issues found in testing:
1. Don’t allow `storage capacity` under the `storage section` in decimal numbers it will fail in the deployment (e.g: provide value 10.1 it will fail in deployment) also make this field number only currently it is allowing string values to be entered.
2. On ubuntu 22.04 next button is not getting enabled until we hover over it in the Credential step
    1. Open pgAdmin and select the server group node from a tree
    2. Go to Object menu -> Register Deploy cloud instance
    4. Select Google Could SQL
    5. Select the client's secret file
    6. And click on the button “Click here to authenticate yourself to Google”
    7. login to the google account and click on Allow 
    8. It will redirect to the pgAdmin window now check “Next” button is disabled even after successful authentication 
    9. hover on the “Next” button it will get enabled 
3. Add Cluster name validation, Google SQL does not allow capital letters & any special characters in the instance names. (You can check the google SQL UI for more details, also add the max length validation google SQL support only 97 characters in the name)
4. If a user selected high availability, the primary and secondary zones should not be the same. (or add an option `any different from primary` in the secondary zone dropdown)
5. Reference link for creating client secret (on `credentials step`) is getting opened in the pgAdmin window itself so it is causing issues after this user is not able to use pgAdmin 
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/69510038/225604253-9e1480c3-6523-4a54-940a-93c67fd5a36c.png">

6. UI validation issue with Storage:
    1. Add all the required fields and check next button is enabled 
    2. Now click on the close button (X button in the select field) in the `Storage type` field in the `Storage section`
    3. Check if it is showing an error on UI but the `Next` button is still enabled
    4. Click on `Next` will navigate to the `Database details` step add the required details and click on next will show the blank screen.
7. UI validation issue with Availability:
    1. Add all the required fields and enable the `High availability?` and select the `Secondary availability zone` from the dropdown.
    2. click on the `Next` button 
    3. Now click on the `Back` button and `disable` the `High availability?` and again `enable` it check it is showing the error msg to select the `Secondary availability zone` but the `Next` button is still enabled.
    4. If the user clicks on the `Next` button it is not throwing any error on the UI and the user can navigate to the last step

8. Connect to deployed instance and select `cloudesqladmin` database from the tree getting an error `pg_hba.conf rejects connection to the server `
<img width="674" alt="Screenshot 2023-03-16 at 5 59 48 PM" src="https://user-images.githubusercontent.com/69510038/225618167-a0e0876e-1e1c-4267-90cf-a5549ff70c93.png">

**Comment by yogeshmahajan-1903** [comment]
> Issues found in testing:
> 
> 1. Don’t allow `storage capacity` under the `storage section` in decimal numbers it will fail in the deployment (e.g: provide value 10.1 it will fail in deployment) also make this field number only currently it is allowing string values to be entered.

Done

> 2. On ubuntu 22.04 next button is not getting enabled until we hover over it in the Credential step
>    
>    1. Open pgAdmin and select the server group node from a tree
>    2. Go to Object menu -> Register Deploy cloud instance
>    3. Select Google Could SQL
>    4. Select the client's secret file
>    5. And click on the button “Click here to authenticate yourself to Google”
>    6. login to the google account and click on Allow
>    7. It will redirect to the pgAdmin window now check “Next” button is disabled even after successful authentication
>    8. hover on the “Next” button it will get enabled

Not able to reproduce.

> 3. Add Cluster name validation, Google SQL does not allow capital letters & any special characters in the instance names. (You can check the google SQL UI for more details, also add the max length validation google SQL support only 97 characters in the name)

Done

> 4. If a user selected high availability, the primary and secondary zones should not be the same. (or add an option `any different from primary` in the secondary zone dropdown)

Done

> 5. Reference link for creating client secret (on `credentials step`) is getting opened in the pgAdmin window itself so it is causing issues after this user is not able to use pgAdmin
> 
> <img alt="image" width="1728" src="https://user-images.githubusercontent.com/69510038/225604253-9e1480c3-6523-4a54-940a-93c67fd5a36c.png">
> 

Done

> 6. UI validation issue with Storage:
>    
>    1. Add all the required fields and check next button is enabled
>    2. Now click on the close button (X button in the select field) in the `Storage type` field in the `Storage section`
>    3. Check if it is showing an error on UI but the `Next` button is still enabled
>    4. Click on `Next` will navigate to the `Database details` step add the required details and click on next will show the blank screen.

Done

> 7. UI validation issue with Availability:
>    
>    1. Add all the required fields and enable the `High availability?` and select the `Secondary availability zone` from the dropdown.
>    2. click on the `Next` button
>    3. Now click on the `Back` button and `disable` the `High availability?` and again `enable` it check it is showing the error msg to select the `Secondary availability zone` but the `Next` button is still enabled.
>    4. If the user clicks on the `Next` button it is not throwing any error on the UI and the user can navigate to the last step

Done

> 8. Connect to deployed instance and select `cloudesqladmin` database from the tree getting an error `pg_hba.conf rejects connection to the server `
> 
> <img alt="Screenshot 2023-03-16 at 5 59 48 PM" width="674" src="https://user-images.githubusercontent.com/69510038/225618167-a0e0876e-1e1c-4267-90cf-a5549ff70c93.png">
> 

Users are not allowed to connect cloudesqladmin database. It is for internal purposes for Google cloud.

> 9. Showing different values for instance type on the `Review` step
>    
>    1. Select instance type 1vCPU, 4GB now go to the `Review` step and check it is showing a different value for it
> 
> <img alt="Screenshot 2023-03-17 at 11 52 34 AM" width="965" src="https://user-images.githubusercontent.com/69510038/225829272-dbd9d138-296b-4183-9e19-a3262e3f4901.png">
> 

Done

> 10. Validation issue in Authentication:
>     
>     1. Select a valid `Client secret file` and complete the authentication process.
>     2. Now again select the wrong client secret file and check it throws an error the first time and then shows authentication successfully and `Next` is enabled, it uses the older authentication to finish the deployment.

Done

> 11. Authentication issue if we change cloud provider(This issue not specific to Google Cloud SQL)

Done

>     1. Open the Deployment cloud instance dialog.
>     2. Select any cloud provider (Taking Google Cloud SQL example here)
>     3. go to the next step and complete the authentication process.
>     4. now click on the `Back` button will go to the previous step
>     5. Select the other cloud provider (e.g: Select EDB BigAnimal)
>     6. Click on the `Next` button it will go to the `Credential` step but the `Next` button on that step is already enabled even though we have not completed any authentication process for a newly selected cloud provider.
>     7. click on next will go to the next step.
>     8. Expected behavior, If the user changes the cloud provider then authentication should not be bypassed for the new cloud provider and the user should not allow going to the next step until the authentication for the selected cloud provider is completed.

Done

**Comment by nikhil-mohite** [comment]
Issues found in testing:
1. Validation issue with the authentication process
    1. Select Google Cloud SQL Click on the `Next` button 
    2. In the Credentials step select the `Client secret file` and click on `Click here to authenticate yourself to Google`
    3. It will open a new window for the authentication process, now switch to the pgAdmin main window and check that the `Next` button is enabled without completing the authentication process. It should be disabled until the user completes the authentication process. 
![image](https://user-images.githubusercontent.com/69510038/226557214-b9e50098-5ee2-44e3-b865-8040ae3645ab.png)

**Comment by nikhil-mohite** [comment]
> 2\. select

Resolved, Verified on snapshot: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/
OS: Windows 10
Mode: Desktop

**Comment by nikhil-mohite** [comment]
> > Issues found in testing:
> > 
> > 1. Don’t allow `storage capacity` under the `storage section` in decimal numbers it will fail in the deployment (e.g: provide value 10.1 it will fail in deployment) also make this field number only currently it is allowing string values to be entered.
> 
> Done

Resolved 

> 
> > 2. On ubuntu 22.04 next button is not getting enabled until we hover over it in the Credential step
> >    
> >    1. Open pgAdmin and select the server group node from a tree
> >    2. Go to Object menu -> Register Deploy cloud instance
> >    3. Select Google Could SQL
> >    4. Select the client's secret file
> >    5. And click on the button “Click here to authenticate yourself to Google”
> >    6. login to the google account and click on Allow
> >    7. It will redirect to the pgAdmin window now check “Next” button is disabled even after successful authentication
> >    8. hover on the “Next” button it will get enabled
> 
> Not able to reproduce.
> 
> > 3. Add Cluster name validation, Google SQL does not allow capital letters & any special characters in the instance names. (You can check the google SQL UI for more details, also add the max length validation google SQL support only 97 characters in the name)
> 
> Done

Resolved 

> 
> > 4. If a user selected high availability, the primary and secondary zones should not be the same. (or add an option `any different from primary` in the secondary zone dropdown)
> 
> Done

Resolved 

> 
> > 5. Reference link for creating client secret (on `credentials step`) is getting opened in the pgAdmin window itself so it is causing issues after this user is not able to use pgAdmin
> > 
> > <img alt="image" width="1728" src="https://user-images.githubusercontent.com/69510038/225604253-9e1480c3-6523-4a54-940a-93c67fd5a36c.png">
> 
> Done
> 

Resolved 

> > 6. UI validation issue with Storage:
> >    
> >    1. Add all the required fields and check next button is enabled
> >    2. Now click on the close button (X button in the select field) in the `Storage type` field in the `Storage section`
> >    3. Check if it is showing an error on UI but the `Next` button is still enabled
> >    4. Click on `Next` will navigate to the `Database details` step add the required details and click on next will show the blank screen.
> 
> Done
> 

Resolved 

> > 7. UI validation issue with Availability:
> >    
> >    1. Add all the required fields and enable the `High availability?` and select the `Secondary availability zone` from the dropdown.
> >    2. click on the `Next` button
> >    3. Now click on the `Back` button and `disable` the `High availability?` and again `enable` it check it is showing the error msg to select the `Secondary availability zone` but the `Next` button is still enabled.
> >    4. If the user clicks on the `Next` button it is not throwing any error on the UI and the user can navigate to the last step
> 
> Done
> 

Resolved 

> > 8. Connect to deployed instance and select `cloudesqladmin` database from the tree getting an error `pg_hba.conf rejects connection to the server `
> > 
> > <img alt="Screenshot 2023-03-16 at 5 59 48 PM" width="674" src="https://user-images.githubusercontent.com/69510038/225618167-a0e0876e-1e1c-4267-90cf-a5549ff70c93.png">
> 
> Users are not allowed to connect cloudesqladmin database. It is for internal purposes for Google cloud.
> 
> > 9. Showing different values for instance type on the `Review` step
> >    
> >    1. Select instance type 1vCPU, 4GB now go to the `Review` step and check it is showing a different value for it
> > 
> > <img alt="Screenshot 2023-03-17 at 11 52 34 AM" width="965" src="https://user-images.githubusercontent.com/69510038/225829272-dbd9d138-296b-4183-9e19-a3262e3f4901.png">
> 
> Done
> 

Resolved 

> > 10. Validation issue in Authentication:
> >     
> >     1. Select a valid `Client secret file` and complete the authentication process.
> >     2. Now again select the wrong client secret file and check it throws an error the first time and then shows authentication successfully and `Next` is enabled, it uses the older authentication to finish the deployment.
> 
> Done
> 

Still able to reproduce the issue with latest snapshot

> > 11. Authentication issue if we change cloud provider(This issue not specific to Google Cloud SQL)
> 
> Done
> 
> > ```
> > 1. Open the Deployment cloud instance dialog.
> > 2. Select any cloud provider (Taking Google Cloud SQL example here)
> > 3. go to the next step and complete the authentication process.
> > 4. now click on the `Back` button will go to the previous step
> > 5. Select the other cloud provider (e.g: Select EDB BigAnimal)
> > 6. Click on the `Next` button it will go to the `Credential` step but the `Next` button on that step is already enabled even though we have not completed any authentication process for a newly selected cloud provider.
> > 7. click on next will go to the next step.

Resolved 

> > 8. Expected behavior, If the user changes the cloud provider then authentication should not be bypassed for the new cloud provider and the user should not allow going to the next step until the authentication for the selected cloud provider is completed.
> > ```
> 
> Done

Issue no 10 is reproducible with the latest snapshot: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/
OS: Windows 10
Mode: Desktop

**Comment by nikhil-mohite** [comment]
Issues found in testing:
1. Unable to complete google authentication if pgAdmin is running in the server mode and SCRIPT name is configured.
2. On Ubuntu 22 platform Incorrect error (status code 500) is shown when an invalid client secret JSON file is provided for authentication.

**Comment by nikhil-mohite** [comment]
Resolved, and verified on the latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-29/
OS: macOS (Monterey 12.6), Ubuntu 22.04.1, Windows 10
Mode: Desktop (On Windows, Ubuntu, and mac), Server Mode (On Ubuntu)

**Comment by nikhil-mohite** [comment]
> Issues found in testing:
> 
> 1. Unable to complete google authentication if pgAdmin is running in the server mode and SCRIPT name is configured.
> 2. On Ubuntu 22 platform Incorrect error (status code 500) is shown when an invalid client secret JSON file is provided for authentication.

Resolved
