### ISSUE TITLE
Upgrading from 6.8 to later turns on validation checks for email and password for local development

### ISSUE THREAD

**Issue by ankittrehan2000** [pgadmin-org/pgadmin4#5752]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Upgrading pgAdmin from 6.8 to a later version seems to turn on validation checks for `PGADMIN_DEFAULT_EMAIL` and `PGADMIN_DEFAULT_PASSWORD` environment variables set in the dockerfile. (e.g using postgres@test.invalid as an email address for local development causes the authentication to error with `Email/Username is invalid`. But using any other valid domain that ends in `.com` doesn't show the error. 

Is there some way to turn this off that I am missing or was updated?

**To Reproduce**

1. Make sure you are on `6.8` or later
2. Go to pgAdmin login page on your local development server
3. Try logging in using the `PGADMIN_DEFAULT_EMAIL` (postgres@test.invalid)
4. See the error

**Expected behavior**

Expected to be able to login with credentials defined in the Docker file. 

**Error message**

`Email/Username is invalid`

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Version: 6.9 or later
 - Mode: Server
 - Browser (if running in server mode): Chrome
 - Package type: Container

**Additional context**

This login used to work before attempting to update to anything after pgadmin 6.8

**Comment by adityatoshniwal** [comment]
Hi @ankittrehan2000,

What is the bug here? pgAdmin has increased email ID validation. Please use a correct email id.
Please note, the email ID is validated for the structure only. The email ID exists or not is not checked.

Thanks.
