### ISSUE TITLE
Query tool prompts for unsaved changes even no changes have been made

### ISSUE THREAD

**Issue by natha1818** [pgadmin-org/pgadmin4#5756]
Reproduce issue:
1. open Query Tool
2. click 'open file' icon and open a file
  -> _'save file' icon in toolbar is highlighted by default even before any changes occurred._
3. click 'open file' icon to open another file
  -> _prompts for 'Unsaved changes - Are you sure you want to discard the current changes?'_

Tested on following config:
PGAdmin version 6.19
OS: Windows 10 Pro version 22H2 (OS build 19045.2486)

**Comment by anilsahoo20** [comment]
Verified. Tested on Snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-16/

Environment: macOS Monterey 12.6.3 (Desktop mode)

**Comment by anilsahoo20** [comment]
Verified on candidate build 6.21: https://developer.pgadmin.org/builds/2023-03-01-1/
OS: macOS Monterey 12.6.3
Mode: Desktop

**Comment by nikhil-mohite** [comment]
Resolved, Verified on candidate build: https://developer.pgadmin.org/builds/2023-03-08-1/
OS: macOS Monterey 12.6
Mode: Desktop
