### ISSUE TITLE
pgAdmin 6.19 can't resize left (vertical) windows

### ISSUE THREAD

**Issue by ddjuric1** [pgadmin-org/pgadmin4#5758]
In pgAdmin 6.19 we can't resize left (vertical) windows where connections,databases,schemas and object are.
Looks like the left to right 1/3 ratio is fixed as a fix for the flickering issue. 
Could it that ratio of 1/3 be parametrized? It would be very convenient.

**Comment by adityatoshniwal** [comment]
@ddjuric1 It can be resized. Did you lock your layout using File->Lock Layout->Full lock?

**Comment by ddjuric1** [comment]
@adityatoshniwal you right. It can be resized. But, I tried to unlock it trough Preferences options, and it did,t do that way (probably after restarting pgAdmin it do). It works if you unlock it through File->Lock Layout immediately. 

Thx

Regards

**Comment by adityatoshniwal** [comment]
I can confirm its a bug. Changing the preference should immediately reflect.
Thanks.

**Comment by anilsahoo20** [comment]
Verified. Tested on Snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-16/

Environment: macOS Monterey 12.6.3(Desktop Mode)

**Comment by anilsahoo20** [comment]
Verified on candidate build 6.21: https://developer.pgadmin.org/builds/2023-03-01-1/
OS: macOS Monterey 12.6.3
Mode: Desktop
