### ISSUE TITLE
pgAdmin 6.19 Cannot drag table name (or column) to query window

### ISSUE THREAD

**Issue by PaulFarry** [pgadmin-org/pgadmin4#5761]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

You can no longer drag a Table or Column to the query window and have the text inserted for you.

**To Reproduce**

1. open a query window for the current database
2. highlight a table in the left panel
3. start typing... select * from ..
4. Drag the table from the left panel to the query window

**Expected behavior**

Previously you could do the above process and the name of the schema.table or column would appear in the query window.

**Error message**
-No error, just you cannot drag

**Desktop (please complete the following information):**
 - OS:  Windows 10,
 - Version: 6.19
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: Installer

**Additional context**

**Comment by M-M-M-M** [comment]
I have the same issue with 6.19 on MacOS.

**Comment by anilsahoo20** [comment]
Verified with candidate build. 
Candidate build link: https://developer.pgadmin.org/builds/2023-02-06-1/

**Comment by M-M-M-M** [comment]
Fixed on 6.20 (at least for MacOS)
