### ISSUE TITLE
Schema Diff: Issue when trigger names are same but trigger function body is different

### ISSUE THREAD

**Issue by kblum007** [pgadmin-org/pgadmin4#5762]
When comparing two tables that:

- Have exactly the same DLL (see files source_dll.txt and target_dll.txt)
- Have identical trigger DLL (see trigger_definition.txt), calling the **same trigger function**  
- The body of the **trigger function** is different in this case by comments only (see source_trigger_dll.txt and target_trigger_dll.txt)
- (In my case) the trigger function is in a different schema

Schema Diff reports the two tables are different, and the script generator simply recreates the trigger (see generated_script_ddl.txt) with no reference or action to the trigger function.

I understand from the documentation that Schema Diff does not resolve dependencies. However, the behavior, in this case, is inconsistent. Schema Diff seems to understand that the trigger functions are different, but
--  The DDL comparison for the source and target are identical
--  The difference/generated script doesn't address the actual solution

[source_ddl.txt](https://github.com/pgadmin-org/pgadmin4/files/10458919/source_ddl.txt)
[target_ddl.txt](https://github.com/pgadmin-org/pgadmin4/files/10458921/target_ddl.txt)
[trigger_definition.txt](https://github.com/pgadmin-org/pgadmin4/files/10458979/trigger_definition.txt)
[source_trigger_dll.txt](https://github.com/pgadmin-org/pgadmin4/files/10458920/source_trigger_dll.txt)
[target_trigger_dll.txt](https://github.com/pgadmin-org/pgadmin4/files/10458916/target_trigger_dll.txt)
[generated_script_ddl.txt](https://github.com/pgadmin-org/pgadmin4/files/10458918/generated_script_ddl.txt)

**Comment by akshay-joshi** [comment]
@kblum007 

You seem to compare two schemas in your case, which is 'cmdb', which contains both tables and triggers. Your trigger function is in a different schema that is not included in the comparison, so this behavior is expected, but we will investigate. 

Schema diff resolves dependencies between schemas. Create a trigger_function in 'cmdb', and it will be selected automatically when the table object is selected.
 
Meanwhile, you can compare the whole database, schema diff will show the trigeer_function that you can select and generate the scripts.

**Comment by kblum007** [comment]
I understand the different schemas. It’s that if Schema Diff is only looking at the current schema’s objects then why is it presenting the objects as “different” when the only thing that is different about them is the trigger function in another schema? It’s inconsistent with the expected behavior.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-27/).

Env:
OS - macOS Sonoma 14.4.1
Mode - Desktop
