### ISSUE TITLE
Keyboard hotkey to open query tool and search object stopped working

### ISSUE THREAD

**Issue by birgersp** [pgadmin-org/pgadmin4#5763]
**Describe the bug**

After updating from 6.18 to 6.19, I noticed that the hotkey Shift+Alt+Q (to open query tool) no longer works.

This has been working ever since I first installed PGAdmin, about a year ago. I have been updating once or twice per month, and this error definitely appeared between 6.18 and 6.19.

I also tried changing the hotkey to Ctrl+Q, but still the query tool won't open when I hit the keys.

**To Reproduce**

1. In the left pane, click on a database
2. Hit Shift+Alt+Q
3. Observe how the query tool didn't open

**Expected behavior**

I expect the query tool to open.

**Error message**

(No error message)

**Screenshots**

![image](https://user-images.githubusercontent.com/5260237/213678427-be60749a-7791-4ad9-a165-9f2276f2d73b.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 - Based on Ubuntu 20.04
 - Version: 6.19
 - Mode: Desktop
 - Package type: DEB

**Additional context**

(None)

**Comment by pravesh-sharma** [comment]
Issue fixed. verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-07/
