### ISSUE TITLE
Utility not found: Failed to fetch Utility information error displayed if user Click on Maintenance for index  in Materialized view

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#5764]
- OS: [All]
 - Version: [6.19]
 - Mode: [Desktop and Server]
 
Utility not found: Failed to fetch Utility information error displayed if user Click on Maintenance for index create in Materialized view however if a user creates an index on the table and clicks on Maintenance then no error message is displayed.

Steps to reproduce
1. Go to Materialized view
2. Create it
3. Click on Index and create an index on the same Materialized view
4. Utility not found: Failed to fetch Utility information error displayed

**Expected behaviour**

Maintenance should be successful for the index in  Materialized view.

**Error message**

Utility not found: Failed to fetch Utility.

<img width="1744" alt="Screen Shot 2023-01-20 at 4 19 55 PM" src="https://user-images.githubusercontent.com/43006122/213685201-9aa0798d-cf8d-4fc4-bf73-67053727a3c3.png">

**Comment by pravesh-sharma** [comment]
Issue resolved. Tested on snapshot build at https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-16/

Env - macOS Monterey 12.6.3 (Desktop mode)

**Comment by pravesh-sharma** [comment]
Verified on candidate [build](https://developer.pgadmin.org/builds/2023-03-01-1/)
