### ISSUE TITLE
apt upgrade reverts config.py

### ISSUE THREAD

**Issue by mquinnatlasroofingcom** [pgadmin-org/pgadmin4#5765]
When upgrading pgadmin4 from 6.17 to 6.19 via the apt packages from the pgadmin repository, the config.py file is reverted back to its defaults.  This is done without asking or offering to save the existing file.  So, all ldap authentication and other settings are removed.

To reproduce:
run 6.17 with a customized config.py file
apt update && apt upgrade
notice your config.py no longer has custom settings

Saving a copy of config.py and overwriting the default config after the update seems to work but who knows if that will cause other problems down the road.

I'm running this in an ubuntu 20.04 lxc container.

**Comment by dpage** [comment]
Yes, this is by design, as documented: https://www.pgadmin.org/docs/pgadmin4/6.19/config_py.html
