### ISSUE TITLE
Adding DROP CONSTRAINT IF EXISTS to ERD generated sql

### ISSUE THREAD

**Issue by NihilumPlays** [pgadmin-org/pgadmin4#5770]
When creating an ERD from an existing database and generating the sql for that, all the constrains that exists will be created again without any checking if they exist, resulting in an error when you execute the script. So I have to manually edit the generated sql to remove the sql creating the existing constraints to be able to run the script.

It would be nice if the generate script function added drop constraint if exists so you dont need to manually remove those.

Example, this sql generated by my ERD, gives me an error because the constraint already exists:
> ALTER TABLE IF EXISTS public.module_addon_twitch_tokens
   > ADD CONSTRAINT tokens_module_id_fkey FOREIGN KEY (module_id)
   > REFERENCES public.modules (id) MATCH SIMPLE
   > ON UPDATE NO ACTION
   > ON DELETE NO ACTION;

But adding this before it, will make it work as expected:
> ALTER TABLE IF EXISTS public.module_addon_twitch_tokens DROP CONSTRAINT IF EXISTS tokens_module_id_fkey;

**Comment by nikhil-mohite** [comment]
Resolve, Verified on latest snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-11-20/
OS: macOS (Sonoma 14.1)
