### ISSUE TITLE
Clear Saved password should be disabled if the user already clear the password

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#5773]
- OS: ALL
 - Version: [6.19]
 - Mode: [e.g Desktop and Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [All]
 

Clear Saved password should be disabled if the user already clear the password

Steps to reproduce the behaviour:
1. Go to Server 
2. select save password
3. provide a password
4. Click on Ok
5. Password saved successfully
6. Now go to the Object
7. Click on Clear Saved Password
8. Save password cleared successfully
9. Again go to the Object
10. Click on Clear Saved Password ->this should be disabled

**Expected behaviour**

If the user Click on Clear saved password then this option should be disabled

<img width="1738" alt="Screen Shot 2023-01-24 at 4 00 20 PM" src="https://user-images.githubusercontent.com/43006122/214274894-428ee8ae-97d2-4767-bebd-2de2a305d550.png">

**Comment by pravesh-sharma** [comment]
Issue resolved. Tested on latest snapshot build at https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-16/

Env - macOS Monterey 12.6.3

**Comment by pravesh-sharma** [comment]
Verified on candidate [build](https://developer.pgadmin.org/builds/2023-03-01-1/)
