### ISSUE TITLE
Browser tree state is not remembered when reopening PGAdmin

### ISSUE THREAD

**Issue by natha1818** [pgadmin-org/pgadmin4#5777]
Browser tree state is not recalled when reopening PGAdmin v6.19.
In PGAdmin v6.18 (and probably earlier), when you started PGAdmin it would expand browser tree to the location you left when quiting PGAdmin the last time.

Tested on following config:
PGAdmin version 6.19
OS: Windows 10 Pro version 22H2 (OS build 19045.2486)

Remark: similar to #4898

**Comment by nikhil-mohite** [comment]
@natha1818 ,

can you please share a short video for this?

**Comment by natha1818** [comment]
Here you have...

https://user-images.githubusercontent.com/28142574/215085671-158d4dc4-49ac-462c-af5b-082e55996f18.mp4

**Comment by FaharAbbasRizvi** [comment]
This issue is still reproducible on the latest snapshot build.

https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-20/
