### ISSUE TITLE
Functions as Default values are executed during creation of new table

### ISSUE THREAD

**Issue by marcusry** [pgadmin-org/pgadmin4#5778]
Hi all, 

after upgrading to pgadmin4-server/pgadmin4 6.19 we are experiencing some issues when setting up tables. Function calls for default values, like now(), seem to be interpreted directly with the according result becoming the default value.

**Steps to reproduce the behavior:**

1: Table creation
![grafik](https://user-images.githubusercontent.com/117862006/214335638-eee07c32-d044-46c8-9633-26de55be744b.png)

2: Looking into table properties after creation --> function calls for default values are replaced with their result
![grafik](https://user-images.githubusercontent.com/117862006/214335832-1653ee71-72f6-47f3-b7bc-7350b51f485d.png)

3: These static values are applied when new rows are added
![grafik](https://user-images.githubusercontent.com/117862006/214335896-2d1f2fd4-bffb-4ba1-966a-a11dd503d63f.png)

**Expected behavior**

Expected behavior is that the links to the specific functions are stored not the values from the execution at time of table creation

**Error message**

No error message

**Server environment:**
 - OS: Ubuntu 20.04 LTS
 - Version: 6.19
 - Server Mode using Apache2 as webserver
 - Client access via: Firefox 102.7 esr, Chrome 
 - Installation using deb-packages --> deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4 main

Best wishes

Marcus and Johannes

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
