### ISSUE TITLE
Upgrading from pgadmin web 4 6.18 to 6.19 sees an anonymous user object in setup.py server replacement

### ISSUE THREAD

**Issue by dosfslib** [pgadmin-org/pgadmin4#5780]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

In the latest release of pgadmin-web 6.19-1 we see an error when using the import server command 

in 6.18 

 /usr/pgadmin4/venv/bin/python3 /usr/pgadmin4/web/setup.py --load-server /etc/commandcenter/pgadmin_servers.json --replace
----------
Loading servers with:
User: support@example.org
SQLite pgAdmin config: /var/lib/pgadmin4/pgadmin4.db
----------
Added 1 Server Group(s) and 1 Server(s).

in 6.19 

  ----------
  Loading servers with:
  User: support@example.org
  SQLite pgAdmin config: /var/lib/pgadmin4/pgadmin4.db
  ----------
  'AnonymousUser' object has no attribute 'username'

**To Reproduce**

1. Install pgadmin4-web 6.19 on latest redhat 8.7
2. sudo -E -u pgadmin /usr/pgadmin4/venv/bin/python3 /usr/pgadmin4/web/setup.py
with valid environment variables PGADMIN_SETUP_EMAIL and PGADMIN_SETUP_PASSWORD
to initialize the environment
4. Import the server settings using /usr/pgadmin4/venv/bin/python3 /usr/pgadmin4/web/setup.py --load-server /etc/commandcenter/pgadmin_servers.json --replace
5. See the error seen above 

**Expected behavior**

It should display same message as 6.18 stated above.

**Error message**

  'AnonymousUser' object has no attribute 'username'

**Desktop (please complete the following information):**
 - OS: RHEL 8.7
 - Version: 8.7
 - Mode: Server
 - Browser (if running in server mode): chrome
 - Package type: RPM

**Additional context**

Similar to this https://stackoverflow.com/questions/75182421/pgadmin4-6-19-anonymoususer-object-has-no-attribute-username

**Comment by yogeshmahajan-1903** [comment]
This duplicate of https://github.com/pgadmin-org/pgadmin4/issues/5751 . Fix will be available in 6.20 release.
Currently you use daily snapshot build to verify.
Alternatively, you can import/export servers options from UI. Tools > Import/Export Servers.
