### ISSUE TITLE
Shortcuts stopped working on the 'Browser' panel

### ISSUE THREAD

**Issue by osnofa** [pgadmin-org/pgadmin4#5782]
**Describe the bug**

The shortcuts on the Browser panel to the left stopped working after upgrading to 6.19 on the Windows executable.

**To Reproduce**

1. Select a database in the Browser panel
2. Try to refresh using the 'F5' shortcut

Another example:
1. Select a database in the Browser panel
2. Try to open the Query Tool using the 'ALT+SHIFT+Q' shortcut

**Expected behavior**

In the first example, it should update the list of objects inside the database.
In the second, it should open a Query Tool in the main panel.

**Error message**

It does nothing.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 22H2 (Build: 19045.2546)
 - Mode: Desktop
 - Package type: Windows executable

**Comment by nikhil-mohite** [comment]
Duplicate #5763
