### ISSUE TITLE
error with special caracter in password

### ISSUE THREAD

**Issue by yukimushide** [pgadmin-org/pgadmin4#5785]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

a user try to connect via LDAP configuration
pgadmin say that the password is not correct.

actually i try to reproduce the bug with a other account and found the caracter that'is not working is the "µ" 

**To Reproduce**

create a ldap user ans set a password with the letter µ in it
try to connect

**Expected behavior**

you should not be able to connect

**Comment by pravesh-sharma** [comment]
Raise an issue in the library flask security https://github.com/Flask-Middleware/flask-security/issues/767
