### ISSUE TITLE
Query tool database reconnect issue

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#5787]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Query tool database reconnect issue

**To Reproduce**

1. Open query tool
2. Execute some queries (e.g: select * from sample)
3. Disconnect the server from the browser tree. (Password is saved for server)
4. Now try to execute the same query in the already opened Query tool, getting a server disconnected warning
5. <img width="624" alt="Screenshot 2023-01-27 at 12 11 40 PM" src="https://user-images.githubusercontent.com/69510038/215025154-70e80a7c-9a14-45eb-9f82-1fc62078f0aa.png">
6. But after clicking on Continue it is throwing an error
7. <img width="1235" alt="image" src="https://user-images.githubusercontent.com/69510038/215026449-0f3edaa6-cfa5-4a27-8c32-fcb4677e74ec.png">

**Expected behavior**
It should connect to the server as the password is already present or ask for a password if the password is not present and connect to server and execute the query.

**Error message**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey(12.6)
 - Version: v6.19
 - Mode: Desktop
 - Browser N/A

**Comment by anilsahoo20** [comment]
If we disconnect the server from Browser tree, then the main connection is closed, so password is saved or not does not matter, User has to manually connect the server and then click on continue on the warning dialog and it will run the query in query tool.
