### ISSUE TITLE
Dashboard session table show ?? character for non-utf8 characters

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#5788]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Dashboard tab session table shows non-utf8 characters as ??

**To Reproduce**

1. Create a database with a name containing non-utf8 characters.
2. Select the newly created DB now go to Dashboard -> Sessions.
3. Check the Application column it is showing ?? for non-utf8 characters.
4. <img width="1791" alt="Screenshot 2023-01-27 at 12 32 31 PM" src="https://user-images.githubusercontent.com/69510038/215029090-92931c4c-dbe8-4d90-83e1-0c17fd8156e5.png">

**Expected behavior**

It should show the name of the database similar to the browser tree

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Version: v6.19
 - Mode: Desktop
 - Browser (if running in server mode): N/A

**Comment by anilsahoo20** [comment]
It is mentioned in the PostgreSQL documentation that "Only printable ASCII characters may be used in the application_name value. Other characters will be replaced with question marks (?)". 
Attaching the PostgreSQL documentation link here for reference. 
Link: https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-APPLICATION-NAME
