### ISSUE TITLE
FK columns shown in wrong order after recreation

### ISSUE THREAD

**Issue by FranzAjM** [pgadmin-org/pgadmin4#5789]
pgAdmin version 6.19 - Desktop - Windows 10

I had to recreate in **table1** the PK to reorder its column (Old order: **col2, col1**. New order: **col1, col2**). So I:

1. dropped an existing FK in **table2** pointing to **table1**
2. dropped and added again the PK in **table1** with the new column order **col1, col2**
3. added again the FK in **table2**, with the new column order, matching the one of the new PK, **col1, col2**

pgAdmin in the UI still shows the old order of the columns in the FK. Even after refreshing or restarting. Querying pg_constraint I checked that the FK has the new order (and other clients show the new order) but the pgAdmin UI still displays the old column order in the FK.

The wrong order is shown both in the Properties modal of the table and in the SQL view

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-24/

Env - macOS ventura 13.3.1 (Desktop mode)
