### ISSUE TITLE
Can't create trigger "AFTER UPDATE OF" with pgadmin

### ISSUE THREAD

**Issue by InitialCrow** [pgadmin-org/pgadmin4#5790]
**Describe the bug**

Hello, ty for your work, just litle bug if you create trigger with trigger function set "after" with "column" on "update"  cause name of trigger empty warning and cant fill input when this configuration of trigger is selected if I change after to before I cant write in name and if I delete column I cant to but I cant create AFTER UPDATE OF trigger cause of bug on empty name I just write trigger on psql query and it work so its just bug of checkin rules on PGADMIN input triggers

**To Reproduce**

1. Go to 'table and trigger section'
2. Right click to 'create trigger'
3. Fill 'name input' and fill function with trigger function input
4. Click and set before to "trigger" input
5. SET update to "event" input
6. choose one column
7. bug should come with message to fill name we prompted of step 1

**Expected behavior**

Create the "AFTER UPDATE OF" trigger

**Error message**

'name' is required

**Screenshots**
![Capture d’écran du 2023-01-27 17-22-24](https://user-images.githubusercontent.com/15141692/215138687-e5496f79-3a0d-4c54-82e7-d0474cf3536a.png)

![Capture d’écran du 2023-01-27 17-22-43](https://user-images.githubusercontent.com/15141692/215138739-06f50b21-8da6-49e5-8b69-d7ad0c9a2cfe.png)

![Capture d’écran du 2023-01-27 17-22-52](https://user-images.githubusercontent.com/15141692/215138756-3eff50fd-6d7e-4d1b-b8e3-7b454556d605.png)

![Capture d’écran du 2023-01-27 17-23-05](https://user-images.githubusercontent.com/15141692/215138787-0c23ba87-ed36-4eb5-b725-81a952ef18fa.png)

![Capture d’écran du 2023-01-27 17-23-15](https://user-images.githubusercontent.com/15141692/215138864-79468ec0-4cdf-4051-a072-1bfcd37f6582.png)

![Capture d’écran du 2023-01-27 17-23-38](https://user-images.githubusercontent.com/15141692/215138895-9fe3da9f-071d-4bb4-9850-e12efb9f156f.png)

**Desktop (please complete the following information):**

 - OS: ubuntu 22.10 kinetic
 - Version: 6.19
 - Mode: Desktop
 - Package type: APT

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-23/

Env - macOS Monterey 12.6.3 (Desktop mode)

**Comment by InitialCrow** [comment]
TY guys for your work

**Comment by pravesh-sharma** [comment]
Verified on candidate [build](https://developer.pgadmin.org/builds/2023-03-01-1/)
