### ISSUE TITLE
v6.19 mac os unable to re-establish connection to remote db after changing wifi networks

### ISSUE THREAD

**Issue by LucasMoskun** [pgadmin-org/pgadmin4#5792]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
If I switch wifi networks, I am no longer able to make queries. Queries eventually timeout:
```
ERROR: could not receive data from server: Operation timed out
SSL SYSCALL error: Operation timed out
```
 I am forced to close and re-open the application. Refreshing does not work. I did not experience this behavior in v6.18

**To Reproduce**

1. Open pgadmin4 v6.19 macos
2. Connect to a remote database
3. Make a query
4. Switch wifi to different network
5. Try to make query
6. Query will timeout

**Expected behavior**

I expect pgadmin 4 to be able to handle changing wifi networks since it could in previous version 6.18.

**Error message**

If possible, include the full, unedited text of any error messages displayed.
```
ERROR: could not receive data from server: Operation timed out
SSL SYSCALL error: Operation timed out
```

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Version: v6.18
 - Mode: Desktop
 - Package type: downloaded packaged installer from: https://www.pgadmin.org/download/pgadmin-4-macos/

**Comment by pravesh-sharma** [comment]
Hi @LucasMoskun,

I am not able to reproduce the issue. Can you please try on the latest version of pgAdmin4?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
