### ISSUE TITLE
Replace the ChartJS charting lib

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#5794]

**Comment by adityatoshniwal** [comment]
https://www.npmjs.com/package/echarts Looks like the lib to go with. It is comparatively faster than Chart.js and has all the features which Chart.js provides.

**Comment by adityatoshniwal** [comment]
Please test on windows for CPU usage.

**Comment by khushboovashi** [comment]
Tested on candidate build, working fine on Mac and Windows 12 Server.
