### ISSUE TITLE
Quick search issue

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#5796]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
Quick search not showing menu items from the object menu.

**To Reproduce**

1. Select any table from the browser tree
2. Go to Help -> Quick search
3. Now type the _table_ keyword in the search input
4. Check it is not showing any menu item in suggestions.
5. <img width="1790" alt="image" src="https://user-images.githubusercontent.com/69510038/215471183-fbfc44a0-ac53-48e7-ad32-e0dd02e81abb.png">

**Expected behavior**

It should show the sub-menus from the object menu in suggestions. This is working as expected in pgAdmin version 6.18
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/69510038/215471481-a9777238-b6fe-43c5-8d50-96a842f1d174.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Version: 6.19
 - Mode: Desktop
 - Browser (if running in server mode): N/A

**Comment by pravesh-sharma** [comment]
Issue resolved. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-01/

Platform -  macOS monterey 12.6.3
Mode - Desktop
