### ISSUE TITLE
pgadmin4 k8s browser doesn't show any server from /pgadmin4/servers.json mounted from ConfigMap

### ISSUE THREAD

**Issue by khteh** [pgadmin-org/pgadmin4#5798]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

pgadmin4:latest doesn't show any server on the browser. `/pgadmin4/servers.json` is mounted properly and I can see the content from inside the pod.

**Describe the bug**

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey] Ubuntu 22.10
 - Version: [e.g. 6.15] latest
 - Mode: [e.g Desktop or Server] k8s statefulset
 - Browser (if running in server mode): [e.g. chrome, safari] chrome
 - Package type: [e.g. RPM, DEB, Python, Container, etc.] Container

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
This duplicate of #5751  . Fix will be available in 6.20 release.
Currently you use daily snapshot build to verify.
Alternatively, you can import/export servers options from UI. Tools > Import/Export Servers.
