### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by elavy-harris** [pgadmin-org/pgadmin4#5802]
**Describe the bug**

I recently upgraded pgAdmin from 6.18 to 6.19. I added a database to a server, then started getting the following error when clicking on "Databases":
```
Failed to retrieve data from the server.
Request failed with status code 500
```

I tried reverting to 6.18, and the problem persists. I can still get to the individual databases, but I have to get past the error first.

I did a Wireshark capture and found a query call where an error is being returned. Here's the query I captured:

[pgAdmin bad query 2023-01-31.txt](https://github.com/pgadmin-org/pgadmin4/files/10549134/pgAdmin.bad.query.2023-01-31.txt)

The reported error was:
```
    Type: Error
    Length: 92
    Severity: ERROR
    Text: ERROR
    Code: 42601
    Message: syntax error at or near ")"
    Position: 1953
    File: scan.l
    Line: 1176
    Routine: scanner_yyerror
```

**To Reproduce**

I don't know how to reproduce this.

**Expected behavior**

No error.

**Error message**

```
Failed to retrieve data from the server.
Request failed with status code 500
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 6.19
 - Mode: Desktop

**Comment by elavy-harris** [comment]
If it matters, my server is running Postgres 14.2.

**Comment by adityatoshniwal** [comment]
Hi @elavy-harris,

I checked the code and the SQL being executed for you does not exist. It was removed. Can you uninstall pgAdmin and install again?

Thanks.

**Comment by elavy-harris** [comment]
Uninstall/reinstall (deleting `C:\Users\username\AppData\Local\Programs\pgAdmin 4\v6` in the interim) seems to have resolved the issue.  Thanks.
