### ISSUE TITLE
Query Tool "stripping" spaces on text column display

### ISSUE THREAD

**Issue by Carl12065** [pgadmin-org/pgadmin4#5803]
**Describe the bug**

When a data value of a text column is displayed in the query results pane, the appearance is that leading spaces are stripped off the value.  Copy/pasting the cell to the editor pane shows that spaces however, but my use case is adding commas to integer values and I would like the result to be right-justified for the place digits to line up.

Note that this "stripping" also appears if there are multiple spaces between the first (non-blank) character and a subsequent value.

This is discussed with screenshots (copied below) in the pgadmin-support thread entitled "Query results display of text with leading spaces?" originally posted on 1/30/2023.  The responder suggested it was a bug.

**To Reproduce**

1:  Use this query as an example.
`select val, to_char(val, '9,999,999,999') as val_formatted
from ( values (123),(12345678) ) vals(val);`

2:  Run it with psql and observe output is right justified for the val_formatted column.

3:  Run the query in pgAdmin4.  You will see that the val_formatted column is not right-justified.

**Expected behavior**

The value displayed in the grid should be exactly what is returned from the database.

**Error message**

None.

**Screenshots**

psql output:
![image](https://user-images.githubusercontent.com/124095696/215884989-70d5d1c0-2305-4dde-8b81-dac0fc20e5b1.png)

pgAdmin4 display:
![image](https://user-images.githubusercontent.com/124095696/215885068-c208c61d-0baf-48c0-93c2-8861eae54c3b.png)

And example pgAdmin4 result with the addition of a leading character to the val_formatted expression:
![image](https://user-images.githubusercontent.com/124095696/215885321-818b9e2d-c4d0-411b-8247-fe96934f16fb.png)

**Desktop**
 - OS: Fedora Linux 37
 - Version: pgAdmin4 version 6.19
 - Mode: Desktop
 - Browser (if running in server mode): n/a
 - Package type: RPM (Fedora 37 repository)

**Additional context**

None.

**Comment by nikhil-mohite** [comment]
Resolved, and verified on candidate build 6.21: https://developer.pgadmin.org/builds/2023-03-01-1/
OS: macOS Monterey 12.6
Mode: Desktop
