### ISSUE TITLE
psql should assume role set in server properties

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#5807]
**Describe the bug**
psql is not taking the role set in the server properties.
When a role is set in server properties, the role is assumed when a new connection is created. Currently, this is happening for query tool but not for psql.

**To Reproduce**

1. Set the role in the server properties.
2. Open psql
3. Execute sql - SELECT current_user, session_user;

**Expected behavior**
SELECT current_user, session_user should return otherrole, postgres.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Version: 6.19
 - Mode: Desktop

**Comment by pr2git** [comment]
I report the same bug in release 6.18 and it is now fixed in release 6.20.

**Comment by adityatoshniwal** [comment]
Still not working for me in v6.20.

**Comment by pr2git** [comment]
Delete your current server and create it again.
The bug was that they saved the role as username, so if you create a server with 6.18 or 6.19 your are impacted by the bug, in 6.20 the usernale and role are properly saved so you need to create it again.

**Comment by pr2git** [comment]
So do you explain that existing servers were working but newly added were not?
If it was a bug like you describe the existing servers won't work.
By the way I am happy that it is now fixed in 6.20. :-)

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-11-13/
Environment: macOs Ventura 13.5.1
Package: arm64 and pip wheel
