### ISSUE TITLE
User Management is very slow

### ISSUE THREAD

**Issue by yleguern** [pgadmin-org/pgadmin4#5809]
**Describe the bug**

When padmin user list grows (I have more than one hundred) the user management is very slow (it hangs for 20-30 seconds or more)

**To Reproduce**

1. Unzip the [pgadmin4.zip file](https://github.com/pgadmin-org/pgadmin4/files/10559597/pgadmin4.zip) (it contains a docker-compose.yml file and an sql file)
2. Start `postgresql` & `pgadmin4` thanks to docker-compose : 
```
docker compose up -d
```
3. Wait 10-20 seconds and then insert 100 users in database
```
docker container exec -i $(docker-compose ps -q postgres) psql --username=admin pgadmin < insert-users.sql
```
4. Open `pgadmin4` in browser (http://localhost/)
5. Login with `admin@gmail.com` / `admin`
6. Goto the User Management panel -> you have to wait 30 seconds or so to use the panel
7. Try to search for a user -> it's very slow

**Desktop (please complete the following information):**
 - OS: [OSX monterey]
 - Version: [6.19]
 - Mode: [Server]
 - Browser: [chrome]
 - Package type: [Container]

**Comment by khushboovashi** [comment]
Duplicates #5768
