### ISSUE TITLE
Sequence Properties does not save OWNED BY tablename.columnname

### ISSUE THREAD

**Issue by SNiedinger** [pgadmin-org/pgadmin4#5810]
As a user when I want to change the properties of a sequence via the Sequence property dialog, 
when I load the properties the Definition tab shows the correct OWNED BY values for the sequence
when I save the sequence properties, the sequence OWNED BY details are lost.

E.g. any serial column with a sequence

pgAdmin v 6.19

**Comment by khushboovashi** [comment]
I am not able to reproduce this issue. Please provide the sample DDL to reproduce the issue also provide the PostgreSQL version.

**Comment by SNiedinger** [comment]
**DDL before saving the Sequence generated by pgAdmin**. (The Definition tab Owned By group is correctly showing the table and column owner)

`CREATE SEQUENCE IF NOT EXISTS crm.persons_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1
    OWNED BY persons.id;

ALTER SEQUENCE crm.persons_id_seq
    OWNER TO postgres;

GRANT SELECT, USAGE ON SEQUENCE crm.persons_id_seq TO "MasterSISAdministrator";

GRANT ALL ON SEQUENCE crm.persons_id_seq TO postgres;`

----

**DDL after saving the sequence generated by pgAdmin** (Just renamed the sequence and saved) 

`CREATE SEQUENCE IF NOT EXISTS crm.persons_id_seqxxx
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE crm.persons_id_seqxxx
    OWNER TO postgres;

GRANT SELECT, USAGE ON SEQUENCE crm.persons_id_seqxxx TO "MasterSISAdministrator";

GRANT ALL ON SEQUENCE crm.persons_id_seqxxx TO postgres;`

**Comment by pravesh-sharma** [comment]
The modified SQL generated by properties dialog is removing owned by property.

**Comment by robe2** [comment]
I have the same issue, though the sql I see is different from above described.

To replicate the issue, create a table such as:

```
CREATE TABLE test(id serial, name text);
```

Use the pgAdmin sequence UI to edit the current value.

The sql it generates is:

```
ALTER SEQUENCE IF EXISTS public.test_id_seq OWNED BY NONE; 
SELECT setval('public.test_id_seq', 2, true);
```

This issue does not happen with sequences generated via GENERATED BY

e.g.

```
CREATE TABLE test(id integer GENERATED BY DEFAULT AS IDENTITY, name text);
```

Use the pgAdmin UI to edit the sequence object backing it.

it generates just the sequence update

```
SELECT setval('public.test_id_seq', 2, true);
```

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-24/
Env - macOS Monterey 12.6.3 (Desktop mode)

**Comment by akshay-joshi** [comment]
Working fine on [candidate build](https://developer.pgadmin.org/builds/2023-03-01-1/)
