### ISSUE TITLE
Unexpected errors on "User Management" panel

### ISSUE THREAD

**Issue by yleguern** [pgadmin-org/pgadmin4#5817]
**Describe the bug**

In the `User Management` panel, when you click on the "`+`" button (`Add Row`):

1. An `Email cannot be empty` error prompts immediately (I did not even get a chance to type in anything)
2. The error notification covers the input fields (cf screenshot)

**Expected behavior**

1. Errors should not be displayed when the focus is still on input fields
2. The errors should not hide the input fields
3. The search bar and the "`+`" button should remain visible even if the user scrolls down the list
4. A click on the  "`+`" button should scroll the window to input fields

**Screenshots**

<img width="978" alt="pgadmin" src="https://user-images.githubusercontent.com/11351012/216391444-f455cf51-1575-4662-b947-5ddd37e6d818.png">

**Desktop (please complete the following information):**
 - OS: `OSX monterey`
 - Version: `6.19`
 - Mode: `Server`
 - Browser: `chrome`
 - Package type: `Container`

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build
