### ISSUE TITLE
Persistent way for server connection configuration in docker

### ISSUE THREAD

**Issue by doebi** [pgadmin-org/pgadmin4#5818]
**Describe the bug**

I am running pgadmin in a docker. From time to time I have the container be recreated, which results in a complete loss of the server configuration. Having to add a server via the GUI on a daily basis is time consuming and a generally needless task to do, in this otherwise automated world.

I am looking for a way to configure a server configuration declarative, either with environment variables or a configuration file mounted. It's just these few parameters: name, hostname, db and password. Any other dockerized database-tool provides a way to define these with env variables.

Thanks.

**Comment by adityatoshniwal** [comment]
Hi @doebi,

Checkout https://www.pgadmin.org/docs/pgadmin4/6.19/container_deployment.html#mapped-files-and-directories.
You can either mount the complete pgAdmin data dir from outside, so that it will persist across docker restarts.
Or you can map /pgadmin4/servers.json to load initial servers when docker starts.

Thanks.

**Comment by doebi** [comment]
Thanks, however this is only helpful in theory.

Mounting the complete data dir '/var/lib/pgadmin' results in an obvious permission error in the container. Your documentation does not state which uid the pgadmin user has inside the container, this is needed to set permissions correctly.

Mounting a "servers.json" file is handy when provisioning but requires a "servers.json" file. Exporting it from a running instance is kinda tricky, since the only export method is saving it to a file on disk. In the case of docker, this means saving a file somewhere in the container. Of course it is possible to retrieve it through common approaches, but it is far from straightforward.
Crafting a "servers.json" file by hand, i realized that it may not contain passwords, which makes it overall useless for my use case.

I am using pgadmin as a developer tool in a local and shared dev environment. The environment itself is assumed trusted and protected from outside. I appreciate the security concerns of your team, but in this scenario it only adds unnecessary complications and overhead. 

Generally my feedback to your tool is: **powerful, but not thought-trough**.

In many cases pgadmin misses the point, next to the previously discussed server-configuration headaches, here is what I find misleading:

The first thing I see - after logging in - is a dashboard of system resources and a collapsed filetree starting at "servers". What I expect from a db tool is to see my database structure, meaning tables with their columns and an easy way to execute SQL on them.

To be able to see my tables in pgadmin I have to traverse the tree **7 levels**
`Servers>myServer>Databases>myDatabase>Schemas>public>Tables>myTable`

Yet, a simple click, does not reveal data, for that I have to use a context menu and somewhere at the end i find "View/Edit Data>All Rows"

Awesome, I finally have a view that is common from db tools. "SQL at the top, and data rows at the bottom". But the next struggle is ahead: the SQL at the top may not be edited. It is read-only!? So if I want to refine my query with a simple where clause, I have to find a way of opening a new query screen and either copy the SQL or write my own query from scratch.


Whether you accept this feedback or not is up to you, but I got the hint: pgadmin is not the right tool for me and i shall move on.

**Comment by adityatoshniwal** [comment]
HI @doebi,

The permissions required is mentioned on the same page - https://www.pgadmin.org/docs/pgadmin4/6.19/container_deployment.html#mapped-files-and-directories.
If you're willing raise suggestions/improvements then we can work on them (can't commit the timeline due to limited resources) or maybe you can raise PR. It is an open-source tool and largely depends on feedback from users like you. We're open to suggestions.

Thanks.

**Comment by pataquets** [comment]
For reference, I've had success using a remote Postgres as configuration store by setting the `PGADMIN_CONFIG_CONFIG_DATABASE_URI` env var to an external database as described [here](https://www.pgadmin.org/docs/pgadmin4/latest/external_database.html).
