### ISSUE TITLE
Invalid JSON Causes pgAdmin to Become Non Responsive

### ISSUE THREAD

**Issue by augustuscl** [pgadmin-org/pgadmin4#5822]
One of our developers was attempting to edit JSON in a JSONB field inside of pgAdmin.  He accidentally added an extra comma, tried to save that to the database, and got an error saying the JSON was invalid.  He then attempted to correct the error and the pgAdmin pane went white.  Any attempt to do anything with the visible controls amounted to nothing.  He ended up exiting pgAdmin.

- The developer initially caused this error with desktop pgAdmin 6.13 running under CentOS.
- He and I reproduced the error with desktop pgAdmin 6.14 running under Windows 10.
- From home I reproduced the error with desktop pgAdmin 6.19 running under Fedora 37.
  - In pgAdmin 6.19, the interface at least gave a red X showing where the invalid JSON could be corrected before locking up the application.

All three tests were using recent patched versions of PostrgreSQL 13.

Below are the steps to reproduce the problem:
```
-- 1 - Create test table.

CREATE TABLE test1
(
  aaa JSONB
);

ALTER TABLE test1
ADD CONSTRAINT test1_pk PRIMARY KEY (aaa);

-- 2 - Insert valid JSON.

INSERT INTO test1 VALUES ('{ "abc": 12, "def": 7}'::JSONB);

-- 3 - Verify data is there by running the query in pgAdmin.

SELECT   *
FROM     test1
ORDER BY aaa;

-- 4: Attempt to edit JSON directly in pgAdmin to something valid, press "OK", and save.  This works.

-- 5: Attempt to edit JSON directly in pgAdmin to something invalid.
--   a: Add a comma after the 7.
--   b: Press "OK".
--   c: Press the database save button.  An SQL error appears briefly in the lower right hand corner, but at the moment all appears to still be working.
--   d: Attempt to correct the invalid JSON.
--   e: Press "OK".
--   f: Press the database save button.  At this point the panel goes all white and any attempts to regain control eventually requires the restart of pgAdmin.
```

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-23/ 
Env - macOS Monterey 12.6.3 (Desktop mode)

**Comment by augustuscl** [comment]
Also verified using the Windows 10 snapshot in desktop mode: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-23/

Big thanks!

**Comment by pravesh-sharma** [comment]
Verified on candidate [build](https://developer.pgadmin.org/builds/2023-03-01-1/)
