### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/*/.pgadmin'

### ISSUE THREAD

**Issue by NikGor** [pgadmin-org/pgadmin4#5823]
Can't start just installed pgadmin4 on my Ubuntu:

![image](https://user-images.githubusercontent.com/91221003/216764292-589d7c01-57d5-4cea-a35c-efbf040d467f.png)

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/niko/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - LC_TIME: ru_RU.UTF-8
  - USER: niko
  - XDG_SESSION_TYPE: x11
  - SHLVL: 0
  - HOME: /home/niko
  - DESKTOP_SESSION: ubuntu
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GTK_MODULES: gail:atk-bridge
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - LC_MONETARY: ru_RU.UTF-8
  - MANAGERPID: 1915
  - SYSTEMD_EXEC_PID: 2259
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 6184
  - LOGNAME: niko
  - JOURNAL_STREAM: 8:34844
  - XDG_SESSION_CLASS: user
  - USERNAME: niko
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - WINDOWPATH: 2
  - PATH: /home/niko/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
  - PAPERSIZE: a4
  - SESSION_MANAGER: local/niko-GP72-2QE:@/tmp/.ICE-unix/2240,unix/niko-GP72-2QE:/tmp/.ICE-unix/2240
  - INVOCATION_ID: 50740441ff454325b71f2ab3356cf680
  - LC_ADDRESS: ru_RU.UTF-8
  - XDG_RUNTIME_DIR: /run/user/1000
  - XDG_MENU_PREFIX: gnome-
  - DISPLAY: :1
  - LANG: ru_RU.UTF-8
  - LC_TELEPHONE: ru_RU.UTF-8
  - XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - XAUTHORITY: /run/user/1000/gdm/Xauthority
  - XDG_SESSION_DESKTOP: ubuntu
  - XMODIFIERS: @im=ibus
  - SSH_AGENT_LAUNCHER: gnome-keyring
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - LC_NAME: ru_RU.UTF-8
  - SHELL: /usr/bin/zsh
  - QT_ACCESSIBILITY: 1
  - GDMSESSION: ubuntu
  - LC_MEASUREMENT: ru_RU.UTF-8
  - LC_IDENTIFICATION: ru_RU.UTF-8
  - GPG_AGENT_INFO: /run/user/1000/gnupg/S.gpg-agent:0:1
  - GJS_DEBUG_OUTPUT: stderr
  - QT_IM_MODULE: ibus
  - PWD: /home/niko
  - XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
  - LC_NUMERIC: ru_RU.UTF-8
  - LC_PAPER: ru_RU.UTF-8
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 35269
  - PGADMIN_INT_KEY: 3a23c593-014f-4052-bbaf-ac986302bb3c
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.007 Sec
ERROR  : Failed to create the directory /home/niko/.pgadmin:
           [Errno 13] Permission denied: '/home/niko/.pgadmin'
HINT :   Create the directory /home/niko/.pgadmin, ensure it is writeable by
         'niko', and try again, or, create a config_local.py file
         and override the SQLITE_PATH setting per
         https://www.pgadmin.org/docs/pgadmin4/6.19/config_py.html

Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgadmin/setup/data_directory.py", line 33, in create_app_data_directory
    is_directory_created = _create_directory_if_not_exists(
  File "/usr/pgadmin4/web/pgadmin/setup/data_directory.py", line 20, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/home/niko/.pgadmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgAdmin4.py", line 93, in <module>
    app = create_app()
  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 265, in create_app
    create_app_data_directory(config)
  File "/usr/pgadmin4/web/pgadmin/setup/data_directory.py", line 46, in create_app_data_directory
    sys.exit(1)
NameError: name 'sys' is not defined

**Comment by yogeshmahajan-1903** [comment]
@NikGor ,
1.How did you install pgAdmin in Desktop mode?
2.With which user you have installed pgAdmin?

**Comment by pravesh-sharma** [comment]
No response from author. Hence closing the issue.
