### ISSUE TITLE
Drag-n-drop doesn't work anymore in  6.19

### ISSUE THREAD

**Issue by Harm-Olthof** [pgadmin-org/pgadmin4#5835]
It was possible to drag-n-drop tables, views & columns from the browser in the query tool edit area, saving you to type out fully qualified names for tables, views etc as well as columnames.
this does not seem to work anymore in 6.19

**Comment by khushboovashi** [comment]
This issue is fixed and will be available in the next release 6.20.

**Comment by Harm-Olthof** [comment]
@khushboovashi thanks for quick followup!
