### ISSUE TITLE
Getting "Fatal Error - The application server could not be contacted." when trying to open the pgadmin tool.

### ISSUE THREAD

**Issue by soumyajitaccenture** [pgadmin-org/pgadmin4#5836]
The tool is installed in a VM. 
Tool version - 4.15
Operating System - Windows Server 2019 Datacenter
This error occurs when we open the tool and this occurs every monday and the users are not able to access the pgadmin tool for some time.

**Comment by adityatoshniwal** [comment]
Hi @soumyajitaccenture,

Please try on the latest version. 4.15 is very old and not supported.

Thanks.

**Comment by pravesh-sharma** [comment]
No response from author. Hence closing the issue.
