### ISSUE TITLE
Login dialog does not show up

### ISSUE THREAD

**Issue by olovb51** [pgadmin-org/pgadmin4#5837]
See https://www.pgadmin.org/download/pgadmin-4-macos/
Since [pgAdmin 4 v6.16](https://www.postgresql.org/ftp/pgadmin/pgadmin4/v6.16/macos/) (released Nov. 19, 2022) the login dialog does not show up. 
I run MacOS High Sierra version 10.13.6 (17G14042)
I can still run pgAdmin 4 v6.15.

**Comment by adityatoshniwal** [comment]
@olovb51 It is not very clear what the issue is. Please share some screenshots.

**Comment by olovb51** [comment]
The screenshot from pgAdmin 4 v6.15 with login dialog looks like this

![login-pgAdmin4 - v6 15](https://user-images.githubusercontent.com/70908380/217479240-47bd85f4-18a0-4d58-b90e-593888e4a6c0.png)

This window & the login dialog does not show up in pgAdmin 4 v6.16 to v6.19.

![no login-pgAdmin4 - v6 19](https://user-images.githubusercontent.com/70908380/217480945-b2f4338d-4c55-4343-9ba9-dcb131ec35da.png)

**Comment by VAndAl37** [comment]
I have the same problem with version 6.20, and the login window doesn't show up on my Mac OS High Sierra version 10.13.6.
Version 6.15 works fine.

**Comment by akshay-joshi** [comment]
pgAdmin 4 doesn't support macOS 10.14 and below. Refer to the link https://www.pgadmin.org/download/pgadmin-4-macos/

**Comment by olovb51** [comment]
I understand. Just a question if you are so kind: PgAdmin 4 v. 6.15 works on MacOS version 10.13.6. From PgAdmin 4 v. 6.16 the window does not show up. Is the change in window launch essential for pgAdmin to work at all?

**Comment by akshay-joshi** [comment]
@VAndAl37 and @olovb51 

pgAdmin 4 runtimes use NWjs. NWjs 0.62.0/0.63.0 onwards is crashing on High Sierra. Please refer to [7946](https://github.com/nwjs/nw.js/issues/7946). pgAdmin 4 v6.15 uses NWjs v0.62.0 so it is working on OSX High Sierra.

**Comment by olovb51** [comment]
Thanks for explaining 👍

**Comment by VAndAl37** [comment]
Thank you for the clarification.
