### ISSUE TITLE
Create Scripts not working properly! 

### ISSUE THREAD

**Issue by ugurlu2001** [pgadmin-org/pgadmin4#5839]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
When creatin new scripts via Browser (Tree) > Right Click Table > Scripts > Create Script ; PgAdmin adding "single quotes (') " to generated script. Previous version that i used of PgAdmin no problem.  Probably bug part is including 'DEFAULT's keywords 

Example of 2 parts (original and last) : 
CREATE TABLE IF NOT EXISTS public.stone_positions -- no problem, old version
(
    id integer NOT NULL DEFAULT nextval('stone_positions_id_seq'::regclass),
...
...

CREATE TABLE IF NOT EXISTS public.stock_positions -- with bug, new version. 
(
    id integer NOT NULL DEFAULT 'nextval('stock_positions_id_seq'::regclass)', -- check this part 
    zaman timestamp without time zone NOT NULL DEFAULT '('now'::text)::timestamp without time zone', -- check this part 
...
...

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by adityatoshniwal** [comment]
@ugurlu2001 The issue is fixed and will be available in upcoming release 6.20 (planned this week).

**Comment by ugurlu2001** [comment]
Thanks :)
