### ISSUE TITLE
Docker deployed pgadmin 6.16 to 6.19  hangs 

### ISSUE THREAD

**Issue by albertmatyi** [pgadmin-org/pgadmin4#5840]
**Describe the bug**

PgAdmin connection hangs

We notice that hangs presumably on a deadlock with the query:
```
SELECT oid, pg_catalog.format_type(oid, NULL) AS typname FROM pg_catalog.pg_type WHERE oid IN (23, 23, 23, 1043, 1043, 25, 1114, 1114, 1043, 1043, 1082, 1043, 1043, 25, 23, 23, 1043, 16, 1043, 1082, 1082) ORDER BY oid;
```

At this point all we can do is reset the whole instance by restarting the pod + resetup the persisted connection (which is not persisted)

**To Reproduce**

Cannot give exact steps to reproduce it as it always works "for a while" and then it locks up for some reason

1. Deploy to k8s 
2. Set up connection to a single database
3. Interact w the database (tabs are left open long time in browsers)

**Expected behavior**

1. pgadmin works for all users

**Error message**

1. Pgadmin is responsive BUT
2. Cannot connect to the server anymore
3. Even if we try to setup the connection again

**Screenshots**

![image](https://user-images.githubusercontent.com/1370078/217611436-0ad603eb-2c05-49ff-bdd4-7c6a807bf62e.png)

**Desktop:**
 - OS: OSX and linux users
 - Version: 6.16, 6.17, 6.18, 6.19
 - Mode: Server
 - Browser: chrome/safari/firefox
 - Package type: Container

**Additional context**

1. We deploy pgadmin to kubernetes into a cluster in an AWS VPC 
2. Database is RDS Postgres v11
3. We use ingress(nginx) based reverse proxying w Google OAuth2 enabled

Deployment config

```
[...k8s deployment yml]
 containers:
      - name: pgadmin
        # tested 6.17 and 6.18 ; did not work / lost access to db every now and again
        image: dpage/pgadmin4:6.19
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: some@email.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: somepass
        # - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
          # value: 'False'
        - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
          # The default value for this parameter is internal. 
          # To enable OAUTH2 authentication, you must include oauth2 in the list of values for this parameter. 
          # you can modify the value as follows:
          # [‘oauth2’, ‘internal’]: pgAdmin will display an additional button for authenticating with oauth2
          value: "[ 'oauth2' ]"
        - name: PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER # Set the value to True if you want to automatically
          # create a pgAdmin user corresponding to a successfully authenticated Oauth2 user. 
          # Please note  that password is not stored in the pgAdmin database.
          value: 'True'
        - name: PGADMIN_CONFIG_OAUTH2_CONFIG
          value: "[{
    'OAUTH2_NAME': 'google',
    'OAUTH2_DISPLAY_NAME': 'Google',
    'OAUTH2_SERVER_METADATA_URL': 'https://accounts.google.com/.well-known/openid-configuration',
    'OAUTH2_CLIENT_ID': 'our id,
    'OAUTH2_CLIENT_SECRET': 'our secret',
    'OAUTH2_TOKEN_URL': 'https://oauth2.googleapis.com/token',
    'OAUTH2_AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/auth',
    'OAUTH2_API_BASE_URL': 'https://openidconnect.googleapis.com/v1/',
    'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
    'OAUTH2_ICON': 'fa-google',
    'OAUTH2_BUTTON_COLOR': '#0000000',
    'OAUTH2_SCOPE': 'openid email profile',
}]"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
```

** Analyzing locked up queries **

```
select
  blockinga.pid AS blocking_pid
  , blockingl.virtualtransaction
  , blockingl.transactionid
  ,now() - blockinga.query_start AS locking_duration
  , COALESCE(blockingl.relation::regclass::text,blockingl.locktype) as locked_item
  ,blockingl.mode as blocking_mode
  , blockinga.query as blocking_query
  , blockinga.query_start as query_started_at
  , blockinga.usename
  , blockinga.application_name

FROM pg_catalog.pg_locks blockingl
JOIN pg_stat_activity blockinga ON blockingl.pid = blockinga.pid

WHERE blockinga.datname = current_database()
and blockingl.granted 
and (now() - blockinga.query_start) > interval  '1 minute'
order by (now() - blockinga.query_start) desc
```

The pgprocesss is blocked:

![image](https://user-images.githubusercontent.com/1370078/217614699-7f45adaf-762a-4355-b9f0-26d75a104c46.png)

Actual results CSV
[long_held_locks_2023-02-08T17_33_20.671894Z.csv](https://github.com/pgadmin-org/pgadmin4/files/10688571/long_held_locks_2023-02-08T17_33_20.671894Z.csv)

**Comment by nigzak** [comment]
Observed the same with Docker PgAdmin dpage/pgadmin4:6.19 using OAUTH login method.
(

- open PgAdmin
- let it be open
- random later open again in another tab where you need to connect again to the DB 
- click on the DB to connect
- PgAdmin asks for credentials 
- .. and then loads endless (also have had: empty error screen message, ask again for password)

Workaround I found is the same 
- re-deploy the image or 
- make a rolling restart.
We even have different environments (DEV, INT, PROD) where it happens random on all stages; sometimes on all together.

Please check this issue, it is very painful to handle - even because you can run in the wrong direction (like me) first thinking that the DB has some problems because PgAdmin is still responsive ...

**Comment by nigzak** [comment]
Hi together,

there is a newer version is available (6.20) which could be solving this issue, there seems to be a similar - or exact this one (?)
[Issue #5567](https://github.com/pgadmin-org/pgadmin4/issues/5567) - Fix orphan database connections resulting in an inability to connect to databases.

Release notes V6.20 link => https://www.pgadmin.org/docs/pgadmin4/6.20/release_notes_6_20.html

**Comment by yogeshmahajan-1903** [comment]
'Gateway time out' error generally occurs due to nginx/proxy configuration. This does not look like a pgadmin issue.
Kindly refer [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) link for more information.

**Comment by dpage** [comment]
Gateway timeouts most often occur when the server behind the proxy (i.e. pgAdmin) doesn't respond in time.

**Comment by albertmatyi** [comment]
Possible duplicate: https://github.com/pgadmin-org/pgadmin4/issues/5567 

Testing with 6.20 to confirm (might take a couple of days)

**Comment by albertmatyi** [comment]
Didn't experience lockups anymore.

**Comment by ocallaghane** [comment]
> #5567



> Observed the same with Docker PgAdmin dpage/pgadmin4:6.19 using OAUTH login method.
> 
> * open PgAdmin
> * open DB and do something (it really does not mind WHAT you do as it seems)
> * let it be open
> * random later open again in another tab where you need to connect again to the DB
> * click on the DB to connect
> * PgAdmin asks for credentials
> * .. and then loads endless (also have had: empty error screen message, ask again for password)
> 
> **HINT: if it is the same query/result as original here from the creator of this ticket I cannot confirm or deny ... I don't know how to get it because the DB connection with pgadmin is gone with this issue and we normally don't use bash or else to read something.**
> 
> Workaround I found is the same
> 
> * re-deploy the image or
> * make a rolling restart.
> 
> We even have different environments (DEV, INT, PROD) where it happens random on all stages; sometimes on all together (on all stages multiple persons are working)
> 
> does NOT help
> 
> * logout manually
> * delete cookies/cash
> * any action in pgadmin UI
> 
> Please check this issue, it is very painful to handle - even because you can run in the wrong direction (like me) first thinking that the DB has some problems because PgAdmin is still responsive ...

@nigzak Did you manage to get this resolved?  Very similar issue to the one you described here. we're on 6.17

**Comment by nigzak** [comment]
Hi @ocallaghane 

I was not able to fix it finally.
I have updated to PgAdmin 6.21 - but it still happens sporadic with this version, but at least not that often as it happened with 6.19 ...

with 6.19 it was like happening multiple times per day, with 6.21 it happens 1-3 times per week; but we are currently not using pgadmin that often so I cannot tell you if it is because we are using it temporary rarely or if it got improved.

At all - it still happens currently with latest version sadly ...

**Comment by nigzak** [comment]
Warning: this issue still happens with 6.21 today
workaround still the same: rollout restart or re-deployment
