### ISSUE TITLE
Constant Interface Lag

### ISSUE THREAD

**Issue by matthew-a-dunlap** [pgadmin-org/pgadmin4#5841]
**Describe the bug**

The interface seems to stutter randomly but also constantly. If you go to click something, it'll usually take .25 seconds to respond. If you type text, it'll usually take .25 seconds to enter text.

Previously I was using an older version of pgadmin 4 that only had the web interface, and that had no lag.

It seems like it may be somewhat better when I'm not connected to a server. The only server I'm using is local, there is very little going on inside it schema/table wise. And the lag happens for things that shouldn't be server dependent (like typing text into the query editor).

I appreciate this is an open source project so I understand if this is just the way it is, but I figured I should report it.

**To Reproduce**

Steps to reproduce the behavior: Launch application.

**Expected behavior**

Less interface lag and choppyness.

**Desktop (please complete the following information):**
 - OS:  2019 MacBook Pro (Intel) running MacOS 13.2
 - Version: 6.19
 - Mode: Desktop

**Comment by edocod1** [comment]
Inside of Preferences > Display, disable "Show activity" and "Show graphs". Does it improve?

**Comment by matthew-a-dunlap** [comment]
Yes this did help! Thanks a lot @edocod1 . 

Maybe these features should be disabled by default if they cause issues even on a recent/beefy machine?

**Comment by adityatoshniwal** [comment]
@matthew-a-dunlap @edocod1 We've fixed issue related to performance in dashboard graphs with 6.20 released yesterday. Can you please try with 6.20 once?

**Comment by matthew-a-dunlap** [comment]
@adityatoshniwal @akshay-joshi It seems like the fix solved my issue. I'll keep using the newest version and report back if I run into any more issues. Glad it was able to be fixed quickly :)
