### ISSUE TITLE
Additional logging for login for keeping track of who is using shared pgadmin instance

### ISSUE THREAD

**Issue by paulmilbank** [pgadmin-org/pgadmin4#5842]
**Describe the solution you'd like**

I would like additional logging around the logins so I can keep track of users who are logging in to a shared PGAdmin instance

**Describe alternatives you've considered**

I currently replace the internal.py and oauth2.py files here https://github.com/pgadmin-org/pgadmin4/tree/master/web/pgadmin/authenticate with ones that contain the additional logging as part of our container build process. This breaks every few releases as I need to update my changes against the latest pgadmin code.

**Additional context**

I am happy to make a PR for this if that would be useful. I have added my logging at info level and the default level seems to be warning. I believe this means most users will not see the additional logging.

**Comment by adityatoshniwal** [comment]
Hi @paulmilbank,

You can raise the PR. We can review and merge it.

Thanks.

**Comment by paulmilbank** [comment]
Thanks very much, PR raised now.

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
