### ISSUE TITLE
pgadmin4 v6.20 fails when postgres password ends with exclamation point

### ISSUE THREAD

**Issue by nuclearaaron** [pgadmin-org/pgadmin4#5847]
This worked fine in previous versions (v6.19 and prior). The new connection configuration throws errors and refuses to log in when the postgres password ends in an exclamation point. Changing the postgres user password to something without exclamation point resolves the issue.

Error is:

invalid dsn: missing "=" after "!" in connection info string

**Comment by akshay-joshi** [comment]
Hi @nuclearaaron 

I have tested with pgAdmin 4 v6.20 and the issue is not reproducible to me. Please refer screenshots below:

<img width="893" alt="Screenshot 2023-02-10 at 3 12 33 PM" src="https://user-images.githubusercontent.com/1632882/218060554-c839f862-6ac3-44bb-b131-3b7570a0e152.png">

<img width="710" alt="Screenshot 2023-02-10 at 3 14 14 PM" src="https://user-images.githubusercontent.com/1632882/218060618-6024f5db-0d5b-41d9-9e55-9d35853781d5.png">

**Comment by ozhilyaev** [comment]
Probably the issue I experienced has the same root.
I successfully used pgpass.conf as a password source with v.6.19 and older. After I upgraded up to 6.20, the authorization issue occurred.

**Comment by nuclearaaron** [comment]
OK. Update: The original password also had a single quote in it  { ' }. It was a randomly chosen strong password to meet security requirements. I can reproduce the issue using the attached docker-compose in a simple test case. Adjust the dpage/pgadmin4 tag to move back and forth with versions (clearing directories to start fresh).
[docker-compose.yaml.txt](https://github.com/pgadmin-org/pgadmin4/files/10709286/docker-compose.yaml.txt)

**Comment by AnthonyLeis** [comment]
It is improper string escaping. Our random, strong pw has a single quote in it, and the issue is reproducible on any connection dialog that asks for the pw as it allows arbitrary arguments to be passed to the connection attempt. This is a security vulnerability, and you should down grade until it is remediated.

**Comment by akshay-joshi** [comment]
Hi All

I have altered the database password to use special characters and it is working fine with v6.20. Please refer to the screenshot below:
<img width="664" alt="Screenshot 2023-02-13 at 11 29 36 AM" src="https://user-images.githubusercontent.com/1632882/218382387-3e506c20-a75b-4346-a642-9e282d29fdf2.png">
<img width="708" alt="Screenshot 2023-02-13 at 11 30 17 AM" src="https://user-images.githubusercontent.com/1632882/218382396-e0146107-186b-429f-9dab-b5825b410a9c.png">

**Comment by akshay-joshi** [comment]
OK, I am able to reproduce the issue when we close and restart the pgAdmin again. Will look into it.

**Comment by akshay-joshi** [comment]
Hi All

We have fixed the issue, can someone please test the new fix by following any one method:

1. Install v6.20, and copy the content from [Latest File](https://raw.githubusercontent.com/pgadmin-org/pgadmin4/master/web/pgadmin/utils/driver/psycopg2/server_manager.py) and paste at the appropriate location '<installation_path>/web/pgadmin/utils/driver/psycopg2/server_manager.py'. Launch the pgAdmin 4 and test the password issue.
2. Take the backup of your '.db' file on the safer side, download and install the snapshot build tomorrow from 'https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-14/'. **Note** this is the nightly build so not fully tested the other feature, use this build only to test the password issue.

**Comment by aybhalala** [comment]
Same issue with "\". Using 6.20/latest via docker.

**Comment by nuclearaaron** [comment]
> Hi All
> 
> We have fixed the issue, can someone please test the new fix by following any one method:
> 
>     1. Install v6.20, and copy the content from [Latest File](https://raw.githubusercontent.com/pgadmin-org/pgadmin4/master/web/pgadmin/utils/driver/psycopg2/server_manager.py) and paste at the appropriate location '<installation_path>/web/pgadmin/utils/driver/psycopg2/server_manager.py'. Launch the pgAdmin 4 and test the password issue.
> 
>     2. Take the backup of your '.db' file on the safer side, download and install the snapshot build tomorrow from 'https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-14/'. **Note** this is the nightly build so not fully tested the other feature, use this build only to test the password issue.

Yes--this fixed the issue. I did it in a docker sandbox play container and it worked without resetting passwords.

**Comment by yogeshmahajan-1903** [comment]
This is working fine.

**Comment by yogeshmahajan-1903** [comment]
Working fine.
