### ISSUE TITLE
ERD tool is not launching through system catalogs table

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#5849]
**Desktop (please complete the following information):**
 - OS: [All]
 - Version: [e.g. 6.20]
 - Mode: [Desktop and Server]
 - Package type: [All]
 

The ERD tool is not launching through the system catalogs table, ERD tool option should be disabled or it should be allowed.

1. Go to system catalog
2. Click on the Table node
3.  Click on ERD Tool table through right Click or on ERD tool through Tools
4. No result displayed

**Expected behavior**

After Launching ERD tool through catalogs either it should be launched or it should be disabled.

**Error message**

No Result is displayed if the user launches ERD through the system catalogs

<img width="1719" alt="Screen Shot 2023-02-10 at 12 43 00 PM" src="https://user-images.githubusercontent.com/43006122/218032081-42307b94-f72c-4c35-bbc5-1605ea68bdd2.png">

**Comment by RohitBhati8269** [comment]
It's working fine as expected.

**Tested and verified on snapshot build:** [](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-20/)
**OS:** [All]
**Mode:** [Desktop and Server]
**Package type:** [All]
