### ISSUE TITLE
Ctrl+C to copy table/column name

### ISSUE THREAD

**Issue by miqmago** [pgadmin-org/pgadmin4#5854]
Would be awesome if Ctrl+C could copy to clipboard the name of the selected table or column in tree view.

**Describe alternatives you've considered**

[Drag and drop already works](https://github.com/pgadmin-org/pgadmin4/issues/5835) but on some laptops with small trackpad it can be difficult.

**Comment by anilsahoo20** [comment]
Verified for the snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-31/
Environment: macOs Ventura 13.3
