### ISSUE TITLE
Incorrect Create Script - Does not show NULLS NOT DISCRETE

### ISSUE THREAD

**Issue by Wildweasel24** [pgadmin-org/pgadmin4#5855]
**Describe the bug**

When creating a new table in pg15.2 with a UNIQUE CONSTRAINT using NULLS NOT DISCRETE, the constraint is created ok, and works correctly, but neither the SQL tab nor the CREATE SCRIPT show that the NULLS NOT DISCRETE option has been used. 

**To Reproduce**

1. CREATE TABLE test (
    test1 integer,
    test2 text,
    CONSTRAINT test_uniques UNIQUE NULLS NOT DISCRETE (test2)  ) ;

2. Select table "test" on the tree, view the SQL tab for table "test".

3. Select menu option Scripts/CREATE Script for table "test", view the script.

**Expected behavior**

Both SQL tab and CREATE Script should show the above script, including the NULLS NOT DISCRETE text.

Both show:

CREATE TABLE IF NOT EXISTS public.test
(
    test1 integer,
    test2 text COLLATE pg_catalog."default",
    CONSTRAINT test_uniques UNIQUE (test2)
)

TABLESPACE pg_default;

**Error message**

None

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - Debian 11 Testing
 - 6.19/6.20
 - Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - .deb

**Additional context**

Standard pg backup tools etc do show usage of NULLS NOT DISCRETE, the issue is Pgadmin4 specific. 

There is no option when creating a table through the Pgadmin interface to choose NULLS NOT DISCRETE for a unique Constraint.

**Comment by anilsahoo20** [comment]
Feature implemented and verified on Snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-16/

Environment: macOS Monterey 12.6.3
