### ISSUE TITLE
Version check broken in 6.20

### ISSUE THREAD

**Issue by benedikt-bartscher** [pgadmin-org/pgadmin4#5856]
**Describe the bug**

PGAdmin recommends me to update to Version 6.20 which i already did. See screenshot

**To Reproduce**

1. Update from pgadmin 6.19 to 6.20
2. Log in

**Expected behavior**

No update notice

**Screenshots**

![image](https://user-images.githubusercontent.com/31854409/218330131-db63f0a8-53ba-4cfa-a307-00572ae44890.png)

**Comment by akshay-joshi** [comment]
Hi @benedikt-bartscher 

I am not able to reproduce the issue, can you please share the screenshot of the about dialog?

**Comment by benedikt-bartscher** [comment]
No screenshot but this is the data in the "About pgAdmin" Dialog:
```
Version
6.2
Application Mode
Server
Current User
******@domain.com
Browser
Chrome 87.0.4280.144
Operating System
Linux-5.15.0-1023-aws-x86_64-with
pgAdmin Database File
/var/lib/pgadmin/pgadmin4.db
Log File
/dev/null
```

**Comment by akshay-joshi** [comment]
@benedikt-bartscher 

It clearly shows that the version of the pgAdmin 4 is 6.2, not 6.20. Can you please check the server dialog and verify whether the 'SSL' tab is showing or not? How you have upgraded to v6.20 using RPM or Debian?

**Comment by akshay-joshi** [comment]
Closing the issue due to no response from the author.
