### ISSUE TITLE
ssl certificate not exists

### ISSUE THREAD

**Issue by MarcoEvasi** [pgadmin-org/pgadmin4#5860]
Win 10 desktop
After installing 4.6.20 when connecting to server I get this error:
"connection to server at xxx failed: root certificate file "D:PWrds--ca-su-south-1-2019-root.pem"does not exists ..."
and you can notice thath the root certificate file path is writtent withouth "\\", even if in Properties>Parameters>Root certificate the file path is well written: "D:\PW\rds--ca-su-south-1-2019-root.pem".
So guessing that the error is due to missing "\\" in the path, I moved the root file in D:, where no "\\" are needed in path, and after that I could connect.

**Comment by BrianWaganerSTL** [comment]
I've got a user that is experiencing the issue.  And the work around was to put all the certs into the root directory.  We checked the last few versions and they seemed to have the same bug.

**Comment by MarcoEvasi** [comment]
Hello Brian, with previous releases I didn't have the issue (I regurarly update at every release).

**Comment by rbrooklyn** [comment]
> Hello Brian, with previous releases I didn't have the issue (I regurarly update at every release).

Confirming this. Been using pgadmin on Windows for a couple of years now. Only version 6.20 has this bug. Versions prior did not have this issue.

**Comment by akshay-joshi** [comment]
Hi All 

We have moved the SSL controls into the Parameters tab as a part of feature #4728. We migrate the old SQLite data to the new format. Recently we have fixed #5847, which may fix this problem. 

Someone, please test the new fix by following any one method:

1. Install v6.20, and copy the content from [Latest File](https://raw.githubusercontent.com/pgadmin-org/pgadmin4/master/web/pgadmin/utils/driver/psycopg2/server_manager.py) and paste at the appropriate location '<installation_path>/web/pgadmin/utils/driver/psycopg2/server_manager.py'. Launch the pgAdmin 4 and test the password issue.
2. Take the backup of your '.db' file on the safer side, download and install the snapshot build tomorrow from 'https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-14/'. 

**Note** This is the nightly build so not fully tested the other feature, use this build only to test the certificate issue. The fix will be available in the next release on 9th March 2023.

**Comment by COWI-MI** [comment]
installing `pgadmin4-6.20-x64.exe` from https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-22/ fixed the connection to server with cert for me.

**Comment by pravesh-sharma** [comment]
As mentioned by user issue is resolved, hence closing.
