### ISSUE TITLE
Not able to input passwords or wrong claim that they are wrong (6.20)

### ISSUE THREAD

**Issue by BolverBlitz** [pgadmin-org/pgadmin4#5862]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When the promt to enter my passwort for a DB pops up it sometimes tells me my password is wrong, sometimes it just reapers without any info.
It looks like only passwords with special characters are affected because pure alphanumeric once still work as expected.
A example password is `\Pq#_!&yu7J@P5%PtG\;SA!,hT:jb9a=`
This password works within pg from nodeJS, aswell as some PG VSCode extention, just not in pgAdmin (6.20) therfor i assume its correct.
it also works on my other PC with PGAdmin 6.7 installed.
I´ve seen Issue #5847 and it seems connected, however the other passwords that don´t work do not end with = or ! for example `.....Z@urk]y)[8aBe` they don´t even contain those at all.

**To Reproduce**

1. Add a DB
2. Write your passwort into the promt

**Expected behavior**

Some kind of error or in the case where it claims its wrong, it should log in because its not wrong.

**Error message**

Either nothing at all or whats shown in the screenshot.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/35345288/218920503-1f45a905-f41f-4415-8606-cfba68bd6639.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by pethrowilo** [comment]
It could be that, user input be erroneously encoded in 4.20, e.g. back slashes '\'.
My test indicates that, replacing character '\' with '\\', fixes authentication error.
This should not happen.

**Comment by akshay-joshi** [comment]
Hi All

We have fixed a similar issue #5847, can someone please test the new fix by following any one method:

1. Install v6.20, and copy the content from [Latest File](https://raw.githubusercontent.com/pgadmin-org/pgadmin4/master/web/pgadmin/utils/driver/psycopg2/server_manager.py) and paste at the appropriate location '<installation_path>/web/pgadmin/utils/driver/psycopg2/server_manager.py'. Launch the pgAdmin 4 and test the password issue.

2. Take the backup of your '.db' file on the safer side, download and install the snapshot build tomorrow from 'https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-02-14/'. 

**Note** This is the nightly build so not fully tested the other feature, use this build only to test the password issue.

**Comment by BolverBlitz** [comment]
@akshay-joshi I´ve replaced the file mentioned and it fixed this issue completly

Using the nightly build (Still sais 6.20 in the about info though) also works for all my DBs

**Comment by akshay-joshi** [comment]
Duplicate of #5847
