### ISSUE TITLE
Unstable formating in query result CSV export

### ISSUE THREAD

**Issue by ish1mura** [pgadmin-org/pgadmin4#5867]
Hi!

When exporting data to CSV, the following problems occur with the format of the data uploaded to the file:
* the fractional part of numbers is added/disappeared
  * in one case `1`, in another `1.00`
* the number of zeros at the end of the fractional part changes
  * in one case `1.00`, in another `1.000000`
* small fractional numbers are presented either in standard form or in exponential form (same problem in Query Tool)
  * `3.3e-05` instead of `0.000033`
* quotes around numbers, dates and strings appear randomly
  * `"6.0000"` instead of `6.0000`

At the same time, the data is displayed correctly in the query tool.

Because of these problems, it is not possible to compare data in the merge tools (WinMerge, Meld, KDiff).

**Version**

* 6.20 (installed from PIP in venv)
* Runned through UWSGI and nginx

**To Reproduce**

1. Run query in Query Tool
2. Press button `Save results to file (F8)`

**Screenshots**

![image](https://user-images.githubusercontent.com/16444298/219354202-cb1b25aa-8167-4394-93f3-6511a8ac341e.png)
![image](https://user-images.githubusercontent.com/16444298/219354838-770bc764-e004-414e-82fa-57bc16fec28e.png)

**Comment by pravesh-sharma** [comment]
Hi @ish1mura,

I tried reproducing the issue by creating the table with same data types and inserting the data but not able to reproduce (attached screenshot). Can you please help me with some more information like
1. How data was imported to table (if it is imported from a file does that file contains the data in this format) ?
2. If possible can you share some dummy data which can help me reproduce the issue.

**Comment by ish1mura** [comment]
Hi, @pravesh-sharma 
Look attached SQL-script.
Paste `fn_test_get` function result with commented randoms to the left, then uncomment randoms and paste result to the right.
[csv_bug.txt](https://github.com/pgadmin-org/pgadmin4/files/11129767/csv_bug.txt)

**Comment by pravesh-sharma** [comment]
Hi @ish1mura

I followed the steps given by you but not able to reproduce the issue, can you please try with a new version of pgAdmin4.

**Comment by nikhil-mohite** [comment]
No response from the author, hence closing it.
