### ISSUE TITLE
SQL displayed for publication is missing row filters.

### ISSUE THREAD

**Issue by bctrigg** [pgadmin-org/pgadmin4#5868]
Using PgAdmin4 6.20 / Postgres 15.2

Create a table per the example in https://www.postgresql.org/docs/current/logical-replication-row-filter.html.: 

CREATE TABLE t1(a int, b int, c text, PRIMARY KEY(a,c));

Create a publication per the example:

CREATE PUBLICATION p1 FOR TABLE t1 WHERE (a > 5 AND c = 'NSW');

Select the publication in PgAdmin, SQL tab shows the following, rows filters have been removed:

-- Publication: p1

-- DROP PUBLICATION IF EXISTS p1;

CREATE PUBLICATION p1
    FOR TABLE public.t1
    WITH (publish = 'insert, update, delete, truncate', publish_via_partition_root = false);

**Comment by akshay-joshi** [comment]
Basic testing is done on candidate build https://developer.pgadmin.org/builds/2023-05-30-1/
