### ISSUE TITLE
Running 'Explain Analyze' on Query Tool panel goes to hangup

### ISSUE THREAD

**Issue by exedx7** [pgadmin-org/pgadmin4#5872]
pgAdmin
Version : 6.19
Application Mode : Desktop
Current User :pgadmin4@pgadmin.org
NW.js Version : 0.72.0
Browser : Chromium 109.0.5414.87
Operating System : Windows-10-10.0.19045-SP04.19
---
When running explain plan for merge statement the Query Tool hangs. The panel is emptied and cannot be killed (only pgAdmin restart helps !).
--
here is an example merge to recreate problem:
MERGE
INTO  RECON_RECORD 
USING (
	SELECT  recon.paid_dt, recon.id AS rid
    FROM    RECON_RECORD recon 
	) org
ON (id = org.rid)
WHEN MATCHED 
THEN UPDATE SET   paid_dt = current_timestamp;

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
<img width="1787" alt="Screenshot 2023-02-24 at 9 17 40 AM" src="https://user-images.githubusercontent.com/16016019/221087232-48b81842-8ad2-4b2e-a274-c2a0f7a64be1.png">

**Comment by yogeshmahajan-1903** [comment]
Working fine.
