### ISSUE TITLE
CPU utilization out of proportion for pgAdmin4 6.20

### ISSUE THREAD

**Issue by brsa** [pgadmin-org/pgadmin4#5875]
**Describe the bug**

I noticed my laptop fan spinning loudly without much activity going on, so I finally checked with top to find "exe" utilizing 4 % or even up to > 40 % CPU. Turns out to be pgAdmin4:

erwin@brsaadv3:~$ ps -ww  4733
    PID TTY      STAT   TIME COMMAND
   4733 ?        Sl     1:11 /proc/self/exe --type=renderer --crashpad-handler-pid=4669 --enable-crash-reporter=, --user-data-dir=/home/erwin/.config/pgadmin4 --nwapp-path=/usr/pgadmin4/bin --nwjs --extension-process --change-stack-guard-on-fork=enable --first-renderer-process --no-sandbox --no-zygote --disable-gpu-compositing --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=5 --time-ticks-at-unix-epoch=-1676859296832407 --launch-time-ticks=538407259 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,9471432155019911965,17209948673374105220,131072

**To Reproduce**

Just starting pgAdmin4, before even entering the primary PW, I see ~ 4 % of CPU utilization. ~ 4 - 6 % while idling with an open connection. A simple "SELECT 1;" gets me up to 15 - 40 %.

**Expected behavior**

The program should have hardly any CPU utilization while doing nothing.

**Desktop (please complete the following information):**

Version 6.20
Application Mode Desktop
Current User pgadmin4@pgadmin.org
NW.js Version 0.72.0
Browser Chromium 105.0.5195.102
Operating System Linux-5.15.0-60-generic-x86_64-with-glibc2.29

---
Package type: DEB

Regards
Erwin

**Comment by yogeshmahajan-1903** [comment]
@brsa 
I am not able to reproduce the issue. PFA SS. What is your machine configuration?
<img width="1221" alt="Screenshot 2023-03-13 at 3 03 12 PM" src="https://user-images.githubusercontent.com/16016019/224662371-c66c2826-c980-4956-935e-5c60cdb85f13.png">

**Comment by khushboovashi** [comment]
No response from the author.
