### ISSUE TITLE
My interface has lost browser options. I don't know how to reset it. Clicking reset layout has no effect

### ISSUE THREAD

**Issue by boyzhou99** [pgadmin-org/pgadmin4#5878]
My interface has lost browser options. I don't know how to reset it. Clicking reset layout has no effect

macos version  10.15.7.     pgAdmin version  6.20

![image](https://user-images.githubusercontent.com/8043277/220042758-44a44f1d-f53b-493d-906f-5c02658759b4.png)

**Comment by adityatoshniwal** [comment]
@boyzhou99 Do you mean the left side browser tree? Can you share the full screenshot?

**Comment by akshay-joshi** [comment]
Closing issue, as no response from the author.
