### ISSUE TITLE
Can't connect to a database using service config file

### ISSUE THREAD

**Issue by palmerj** [pgadmin-org/pgadmin4#5889]
**Describe the bug**

I can not connect to a database using only the service config file specified. I get "could not translate host name "None" to address: nodename nor servname provided, or not known". This used to be possible with prior versions of PgAdmin 4. 

Note I can connect with the same service file with other client tools. e.g `pgcli service=bde-replica`

**Screenshots**

<img width="705" alt="Screen Shot 2023-02-22 at 1 21 32 pm" src="https://user-images.githubusercontent.com/580022/220504746-08149056-b109-41e6-a2d4-327c3bbc1c9f.png">
<img width="705" alt="Screen Shot 2023-02-22 at 1 21 15 pm" src="https://user-images.githubusercontent.com/580022/220504757-e16f5eb3-c236-4845-abeb-946513d0a949.png">

**Desktop (please complete the following information):**
 - OS: [e.g. OSX monterey]
 - Version: [12.6]
 - Mode: [e.g Desktop]
 - Package type: [DMG file from website]

**Comment by tschmitt** [comment]
While building out a new MacBook Pro M1, I am seeing this as well with 6.20.
This may be a regression since 6.19, as I have a MBP Intel running 6.19 and using a service works correctly.
Here is an amplifying screen shot. 
<img width="943" alt="image" src="https://user-images.githubusercontent.com/491150/220814825-f205ab12-8bef-4c3f-8a5c-bd2a00f27b79.png">

**Comment by yogeshmahajan-1903** [comment]
Not able to register new server using service file. Getting error - 
```2023-02-27 12:22:17,352: ERROR	pgadmin:	'ServerManager' object has no attribute 'passfile'
Traceback (most recent call last):
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Code/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 1157, in create
    status, errmsg = conn.connect(
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Code/pgadmin4/web/pgadmin/utils/driver/psycopg3/connection.py", line 308, in connect
    passfile = manager.passfile if manager.passfile else None
AttributeError: 'ServerManager' object has no attribute 'passfile'
```

**Comment by yogeshmahajan-1903** [comment]
Working fine.
