### ISSUE TITLE
PgAdmin SSL tab is gone, moved all values to parameters instead?

### ISSUE THREAD

**Issue by nigzak** [pgadmin-org/pgadmin4#5893]
In PgAdmin 6.20 the SSL tab is gone and all values are moved to "parameters" tab.
This is more difficult to configure and I did not find at least a CR to change this?

Source PgAdmin: image: dpage/pgadmin4:6.20
If I remember correct - **but I am NOT sure** - in 6.19 the tab was still there

![image](https://user-images.githubusercontent.com/102737855/220874084-f35cf05b-e675-437b-bb36-58616a484146.png)

![image](https://user-images.githubusercontent.com/102737855/220874314-2ecb8ed5-e77d-4768-8bbb-dd0103635e66.png)

Expected behaviour (screenshot is from older local version!)

![image](https://user-images.githubusercontent.com/102737855/220874656-a09cef72-04f0-41ac-98cb-9be7492048a0.png)

**Comment by yogeshmahajan-1903** [comment]
@nigzak 
We have changed this in version 6.20. SSL tab is merged with parameters now.
