### ISSUE TITLE
SSH Connection

### ISSUE THREAD

**Issue by zzzzz0001** [pgadmin-org/pgadmin4#5897]
**Describe the bug**
I will get to the point directly
Server IP address - 192.168.0.115
We have a server (the username of that OS is "server") and we have a client (the username of that OS is "client").
The server and client can be linked in two ways.

1. Server user password
2. Private Public Key Relationship (also got a password)

in the terminal, if you connect to the server using a client with the code
`ssh server@192.168.0.115`
it would prompt for the password for the private key which. If I deny by clicking "cancel" in the pop-up screen, then it would prompt to ask me for the password of the user "server" which is in the server pc. And I can type it and it connects using the password than the key.

In PGAdmin,I registered the SERVER under SERVERS in pgadmin with "Password" like in this pic - 
![image](https://user-images.githubusercontent.com/86714683/221429099-a1857c42-2408-467e-a8c4-97105bfbc7ac.png)

After finishing up the details, when I try to connect, what happens is that it tries to connect using the second method which is **Private Public Key Relationship** and a pop-up appears for me to type the password for the key, which is not what I want. I want the PGAdmin to use the password I just gave in the last text area where we could put the password. So when I cancel it as I did for the terminal, the terminal asked me for the normal password whereas pgadmin ends in an error: **Failed to create the SSH tunnel Error. Could not establish session to SSH gateway**

This error happens because of that pop-up that comes up, so if we move the ssh private key from ~/.ssh folder in ubuntu, then it would normally just use the password I gave directly and connect it.

**To Reproduce**

I will put a video on youtube for you to view it in a better manner. The number of steps would be really long to just follow up.
Here is the link: https://youtu.be/YEpvFp0lBJw

In the video, I have clearly explained the problem. I think the video would be more helpful than a text in this situation.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 amd64
 - Version: 6.2
 - Mode: Desktop
 - Package type: Not sure but I used **apt** to install it

**Comment by akshay-joshi** [comment]
@zzzzz0001 

I am unable to reproduce this issue with latest version v7.3. I have tested with the Identity file and Password both.
**My test scenario:**
Base Machine: OSX
VM 1 (Windows): pgAdmin v7.3 running
VM 2 (Fedora 37): Database Server(pg 15) installed.

Create a private/public key combination on Windows from which we want to connect to the database server. Copy the public key into the authorized_keys of the Base machine(OSX). 
<img width="703" alt="Screenshot 2023-06-23 at 4 19 40 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/d34fe66b-2223-4654-984e-1c2682043b08">
<img width="604" alt="Screenshot 2023-06-23 at 4 20 21 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/11ed1d99-c04b-4c5a-ba95-a7a3763b25f1">

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing ticket.
