### ISSUE TITLE
Upgrade SQLAlchemy and dependent packages

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#5901]
Update SQLAlchemy, Flask, Flask-SQLAlchemy and Werkzeug to current versions.

**Comment by FaharAbbasRizvi** [comment]
I am getting following error message if Click on Change password through User  using server mode using Debian package

<img width="1790" alt="Screen Shot 2023-03-20 at 11 37 35 AM" src="https://user-images.githubusercontent.com/43006122/226265433-fec0769c-c3d6-4c9e-b1ed-5060061cab3e.png">

**Comment by FaharAbbasRizvi** [comment]
I am also facing an issue if User clicks on forgotten your password:

<img width="796" alt="Screen Shot 2023-03-20 at 5 25 10 PM" src="https://user-images.githubusercontent.com/43006122/226339768-bec95636-87d3-4a93-95e4-8a83532e0e44.png">

**Comment by FaharAbbasRizvi** [comment]
Candidate builds for v 7.0 tested on all supported platforms in fresh and upgrades scenarios so closing this ID.
