### ISSUE TITLE
Count query triggered on massive partitioned table when estimated count is -1

### ISSUE THREAD

**Issue by guanzo** [pgadmin-org/pgadmin4#5904]
**Describe the bug**

This table row count query is triggered when the estimated count is -1. 

https://github.com/pgadmin-org/pgadmin4/blob/89a2e427f3885c1c93ef94024e713157905519e1/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/templates/tables/sql/default/get_table_row_count.sql#L1

That is, when the return value of the below query is -1.

```sql
SELECT reltuples AS estimate FROM pg_class WHERE relname = 'table_name';
```

The code's intent is to only send a count query if the estimated count is lower than some threshold (default is 2000). Since -1 will always be lower than the configured threshold, a count query is always sent. 

This is affecting my production db that has a partitioned table with billions of rows. I can't ever have count queries running on this table.

**To Reproduce**

1. Produce a table that will return -1 for the estimated count. Based on my testing, partition parent tables can return -1 for the estimated row count.
2. Perform a UI action that will trigger a count query. In my case, I attempted to open the "Properties" menu when right clicking the partition parent table in the object explorer. I suspect you can also click "Count Rows" in the same context menu.

**Expected behavior**

The count query should only be sent if the estimated count is >=0 and <= `table_row_count_threshold`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 6.20
 - Mode: Desktop 
 - Package type: .exe

**Additional context**

According to this [article](https://postgrespro.com/blog/pgsql/5969296):
> The value reltuples = −1 (in PostgreSQL 14 and higher) helps us distinguish between a table that has never had statistics collected for it and a table that just doesn't have any rows.

Relevant code section:
https://github.com/pgadmin-org/pgadmin4/blob/89a2e427f3885c1c93ef94024e713157905519e1/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/utils.py#L615-L622

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-15/

Env - macOS Monterey 12.6.3 (Desktop mode)
