### ISSUE TITLE
File name is not changing on query tool editor tab if opens up another file immediately

### ISSUE THREAD

**Issue by anilsahoo20** [pgadmin-org/pgadmin4#5909]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

In the query tool editor tab, the file name is not changing if we open up another file. It is showing the old file's name, that makes confusion if we are editing the other file or the old file.

**To Reproduce**

1. Open a file in query tool editor and call it file_1.
2. Make some changes on the file_1 or can skip this step.
3. Check the query tool editor tab that shows the file_1
4. Click on open file button.
5. On the unsaved changes popup click 'YES' or or can skip this step if skipped step-2
6. Open another file named as file_2
7. If you check the query tool editor tab that still shows file_1 not file_2 as we opened file_2
8. If we make any change on the query in file_2, we can see the tab is now showing file_2.

**Expected behavior**

The query tool editor tab must show the new file that we opened immediately

**Screenshots**

file_1 content:
<img width="809" alt="Screenshot 2023-03-02 at 1 05 07 PM" src="https://user-images.githubusercontent.com/122535205/222361693-d1ab8ae5-ca66-4205-bb77-6c1187b15aef.png">

file_2 content: check query tool tab, it shows file_1.sql
<img width="805" alt="Screenshot 2023-03-02 at 1 06 49 PM" src="https://user-images.githubusercontent.com/122535205/222362158-ff87fd89-cd3b-447e-992f-dc68bf9eccc1.png">

after making some change in file_2:
<img width="812" alt="Screenshot 2023-03-02 at 1 11 10 PM" src="https://user-images.githubusercontent.com/122535205/222362901-e07a52cd-e66b-4129-8053-c687f92eaf22.png">

**Desktop (please complete the following information):**
 - OS: OSX monterey 12.6.3
 - Version: 6.21
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Comment by nikhil-mohite** [comment]
Resolved, Verified on candidate build: https://developer.pgadmin.org/builds/2023-03-08-1/
OS: macOS Monterey 12.6
Mode: Desktop
