### ISSUE TITLE
pgAdmin v6.20 reconnects to all databases in server after connection lost

### ISSUE THREAD

**Issue by jhartmann123** [pgadmin-org/pgadmin4#5919]
**Describe the bug**

After upgrading from v6.16 to v6.20, when a query window times out via the idle timeout, reconnecting causes pgAdmin to reconnect to all databases in the server, even those you were not connected to previously.

On one of our servers this causes about 40 new connections. All queries afterwards are painfully slow: they take~20 seconds+ for queries that execute within a few ms on the server.

To fix this, you need to disconnect and reconnect manually from the server.

**To Reproduce**

1. Connect to a server that has a few databases. Use a user that is allowed to connect to those databases.
2. Open a query window and run a simple query
3. Wait a bit until the idle timeout is reached (or do sth. else to loose the connection, eg. kill the pgAdmin sessions)
4. Run the query again. 
pgAdmin now needs some seconds to notice that it has lost connection to the server. IIRC that was basically instant before (in pgAdmin 6.16)
5. The dialog to reconnect pops up. Confirm it to reconnect to the database.

pgAdmin now also needs unusually long to reconnect. Your milage may vary depending on the number of databases on the server.

Note on the dashboard: pgAdmin is now connected to all databases. This is not reflected in the browser tree.

6. Right click on the server in the browser and click refresh
Note: All databases show up as connected.

**Expected behavior**

pgAdmin should only reconnect to the databases it was connected to before the timeout.

**Screenshots**

Status before, only connected to one database:
![image](https://user-images.githubusercontent.com/20248188/223696392-86a29149-b872-49cc-98f1-5797fdef525c.png)

Wait for the idle timeout, run the query again. The connection warning appears, but takes ~5 seconds (iirc that was way faster in previous versions):
![image](https://user-images.githubusercontent.com/20248188/223693941-f182102a-84d8-47f4-a141-effc6ff48bf8.png)

Reconnecting now needs 25s to complete for this specific server. This isn't a network issue at this point.

The dashboard now bugs out for me, it doesn't show any sessions anymore. As stated above, queries are now painfully slow, that query below took 20 seconds to complete. pgAdmin now has 37 connections (yes, from my IP), which is not reflected in the DB browser:
![image](https://user-images.githubusercontent.com/20248188/223695879-7c28cae0-0579-4b33-a84e-7b26ce739817.png)

After refreshing the databases, they show as being connected:
![image](https://user-images.githubusercontent.com/20248188/223696206-4f644b36-20fd-49ed-9500-72af91fc91e0.png)

Disconnecting from the server and reconnecting again brings pgAdmin back to a normal, usable state.

**Additional context**

Docker image `dpage/pgadmin4:6.20`

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on docker image :https://hub.docker.com/layers/dpage/pgadmin4/snapshot/images/sha256-bb29a10cff942764342d19ec0a293d0ff9c6d828bbdd167478f2b3e2694e62a7?context=explore

Env - Docker for desktop on macOS (12.6.3)
