### ISSUE TITLE
Bug (usability) with Copy-and-Paste of table rows

### ISSUE THREAD

**Issue by usernamesareaholdoverfromthe90s** [pgadmin-org/pgadmin4#5921]
Test case:

1. Drill down to a table that has multiple rows of data
2. Right-click, click "View/Edit Data" | "All Rows"
3. Scroll to the bottom of the results table
4. Select the last row (or, actually, any row)
5. Click the "Copy" icon (above the results list)
6. Click the "Paste" icon (above the results list)

(Apparent) BUG: Nothing happens except a blue border forms around the row number of the line *above* the one I just selected.   See screenshot (where I copied/pasted row 2533, and it now highlights row number 2532).   But I do notice that the status bar says now says "Changes staged: Added 1".  But there's been nothing added! 

![image](https://user-images.githubusercontent.com/117369461/223741292-f5f6c402-0bde-4684-8133-8fddcbff3f8b.png)

Yet, it turns out that the row actually was added *way* at the top of the results list, and was given a row number of "1+".   I.e., scroll up 2500 lines and you'll see the newly-added row.   But this is completely non-intuitive behaviour because the change in the results list was made off screen, and indeed the change of highlighting in the row number makes this feel like something should have happened in the vicinity of line 2532.

Also, inserting the pasted row at the top is a very weird choice as it changes the row numbers of the existing rows.   I think this is the source of the incorrect row number highlighting after the paste.  I.e., in my test case, I actually copied row number 2532, but then because pgAdmin inserted the pasted row at the top of the results list, row number 2532 became row number 2533.   The background styling for the copied row (now 2533) is still correct, but then you drew the blue border around the *old* row number (2532).

EXPECTED BEHAVIOUR:
One of three options:

- (Optimal) add the new row immediately under the row that was copied-and-pasted, so that the copied row is there as reference.  Scroll one line, if necessary, to ensure that the newly-added is visible.  This feels similar to how most other apps do pasting, e.g., if you select a row in a spreadsheet or word document and copy it and then paste it, it'll be inserted below the caret/selected item. 
- (Okay) add the new row to bottom of the list (which is somewhat logical, because you're effectively appending to a list, and it has no impact on any of the existing row numbers), but scroll to the bottom of the list
- (Worst) add the new row to the top of the list (which is illogical because it is completely unexpected, and because it changes the existing row numbers), but scroll to the top of the list so the user can see (and edit) the newly-added row

**Comment by pravesh-sharma** [comment]
Issue fixed. verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-28/

Environment - macOS Monterey 12.6.3 (Desktop mode)
