### ISSUE TITLE
Clear PK on Copy-and-Paste of table rows

### ISSUE THREAD

**Issue by usernamesareaholdoverfromthe90s** [pgadmin-org/pgadmin4#5922]
Test case:

1. Drill down to any table (with existing rows) that has an auto-generated PK (e.g., determined by a Sequence)
2. Right-click on table, and select "View/Edit Data" | "All rows"
3. Select any row in the results list
4. Click the "Copy" icon (above the results list)
5. Click the "Paste" icon (above the results list)
6. Find the newly-pasted row (see bug #5921)

Note, that the copied row's PK has been included in the newly-pasted row.

So the first thing you have to do, EVERY TIME you copy and paste a row, is select the PK in the new row, and delete it.  Otherwise, when you click "Save Data Changes" you'll get a small error notification that the row could be saved because the PK is already in use.

Could you please change the paste behaviour to blank out the PK, since it always needs to be blanked out, anyway?

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-27/
