### ISSUE TITLE
pgAdmin slows down after several days.

### ISSUE THREAD

**Issue by usernamesareaholdoverfromthe90s** [pgadmin-org/pgadmin4#5923]
I've noticed that pgAdmin starts to run slower and slower as time goes on (e.g., over a couple of days).

E.g., I just did a "View/Edit Data" | "First 100 rows" from a tiny table (only has 35 rows).   It takes about 10 seconds to create the new View/Edit pane, and then 10-15 seconds to run the query. 

If I then close pgAdmin, re-open it, and then re-run the query, it only takes about a second to create the new pane, and only 300 ms to run the query.

I am on version 6.20, running on Windows 10.   I tend to leave my PC running all the time (for weeks on end), but it does goes to sleep when I step away for a while.

**Comment by akshay-joshi** [comment]
@usernamesareaholdoverfromthe90s 

Can you please test on the latest version?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
