### ISSUE TITLE
Unable to reset layout in pgAdmin 4 

### ISSUE THREAD

**Issue by sebasim** [pgadmin-org/pgadmin4#5925]
Hello! I messed up the layout of pgAdmin and now my screen looks like this (picture). I've tried the reset layout button but it's not working (it doesn't do anything), I've tried uninstalling and re installing the app but no luck still.

Could you please help me with this? 
![image](https://user-images.githubusercontent.com/89761941/223878424-5d28c26b-28b1-4cdf-a2ba-207cbe784ec7.png)

**Comment by adityatoshniwal** [comment]
Hi @sebasim,
This will be a bit tricky but can you follow below steps and share the logs please:
1. Go to File -> Runtime -> View Log.
2. In the log, you'll find something like - Application Server URL: http://127.0.0.1:51547/?key=b2a3bb1a-9b1b-43b9-a9b3-7089784aad26.
3. Copy the URL and paste in browser and run.
4. Now open the browser console.
5. Share the browser console logs.

**Comment by sebasim** [comment]
Hi Adita. Thanks for the response. Here it goes: 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/89761941/225058527-ec1acdeb-b871-4f84-a55a-b05f30179e3d.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/89761941/225058736-35601c93-5796-4d5b-b711-5b7b1fe0b576.png">

**Comment by jingling2022** [comment]
I have same situation. Even though I uninstalled and reinstalled pgAdmin 4(6.21) for many times, it always shows Properties and SQL panels only... when I try to add Dashboard panel by clicking right button hover on the top of panel, not working...
![Screenshot 2023-03-31 at 6 15 34 PM](https://user-images.githubusercontent.com/122052516/229248690-dabf805e-6ecf-4be9-8d86-446ce0325050.png)

**Comment by adityatoshniwal** [comment]
Hi @sebasim @jingling2022,

Can you please try:
1. Close pgAdmin.
2. Empty the directory - `/Users/<user>/Library/Application Support/pgAdmin 4`
3. Start pgAdmin.

Thanks.

**Comment by melzein23** [comment]
Hi 
I'm experiencing the same issues too. Reinstalling PG admin does not work. Is there a solution for this yet?


![Screenshot 2023-04-05 at 9 00 05 PM](https://user-images.githubusercontent.com/130010779/230246666-749734e9-3c33-4474-9df7-e084265f5d1e.png)

**Comment by adityatoshniwal** [comment]
Hi @melzein23,
Can you try if this works - https://github.com/pgadmin-org/pgadmin4/issues/5925#issuecomment-1493808562

**Comment by sebasim** [comment]
Hi @adityatoshniwal. That didn't work for me :(. Is there an alternative? 

Thanks btw!

**Comment by adityatoshniwal** [comment]
Hi @sebasim , @melzein23 , @jingling2022,

Please go to `<userhome>/.pgadmin` directory and remove/rename `pgadmin4.db` file and restart pgAdmin. I tried with one of the user yesterday who was facing similar issue and it worked for him.

Thanks.

**Comment by jingling2022** [comment]
https://github.com/pgadmin-org/pgadmin4/issues/5925#issuecomment-1493808562 did not work for me neither... I will try this way https://github.com/pgadmin-org/pgadmin4/issues/5925#issuecomment-1512453829, btw, how can I reach <userhome>/.pgadmin directory? is it inside /Users/<user>/Library/Application Support/pgadmin?

**Comment by jingling2022** [comment]
Do I need to install postgreSQL to use pgAdmin?

**Comment by adityatoshniwal** [comment]
Hi @jingling2022,
.pgadmin will be inside OS users home directory. You can go to home dir using `cd ~`.
And no you do not need to install PostgreSQL to use pgAdmin.

**Comment by jingling2022** [comment]
I did not see pgadmin.db in my home directory...

**Comment by jingling2022** [comment]
Do you know is there any other similar tool I can use instead of pgAdmin 4?

**Comment by adityatoshniwal** [comment]
> I did not see pgadmin4.db in my home directory...

As I mentioned in the comment - https://github.com/pgadmin-org/pgadmin4/issues/5925#issuecomment-1512453829, its inside `<userhome>/.pgadmin`.

**Comment by jingling2022** [comment]
Wow~! It is working now! Finally! Thank you so much for your help!

**Comment by adityatoshniwal** [comment]
this is fixed.

**Comment by thayeray** [comment]
Can you please reopen this, or let me know so I can create a new issue? I have tried versions 8.5 and 8.6 for Arm64 and have not been able to reset the layout. After clicking on reset layout in the dropdown menu there is no dialog asking whether or not to reset the layout. I have tried pressing "return" with no effect. I tried emptying the 'Application Support/pgadmin 4' directory and renaming the pgadmin4.db and restarting, also with no effect. 
I am able to run it "fine" in a web browser using the server Application Server URL provided at the bottom of the log (pgAdmin 4/Runtime/View log...) pasted into a web browser. Fine means that everything works except that I can not use autocompletion (control space) or "Reset Layout".

**Comment by adityatoshniwal** [comment]
Hi @thayeray,
Reset layout doen't reload the complete app anymore. As the name suggests, it only resets the layout to default. So the confirmation is removed.

**Comment by thayeray** [comment]
On my machine, on opening the ap, it loads zoomed in on the top left of the window, making the default completely unusable. Reset layout would then scale the window so that all of the widgets were visible at a usable scale.  What do I do if the default is unusable? This is a long standing problem, the fix for which was reset layout.



    On Friday, May 24, 2024 at 12:39:41 AM EDT, Aditya Toshniwal ***@***.***> wrote:  
 
 


Hi @thayeray,
Reset layout doesn't reload the complete app anymore. As the name suggests, it only resets the layout to default. So the confirmation is removed.

**Comment by adityatoshniwal** [comment]
Hi @thayeray,
One of the user fixed it by clicking the menu - File/pgAdmin4->Runtime->Actual Size.
Try once.

**Comment by thayeray** [comment]
Great that works and makes sense. Thank you!


    On Friday, May 24, 2024 at 08:03:40 AM EDT, Aditya Toshniwal ***@***.***> wrote:  
 
 


Hi @thayeray,
One of the user fixed it by clicking the menu - File/pgAdmin4->Runtime->Actual Size.
Try once.
