### ISSUE TITLE
auto theme based on OS preferences

### ISSUE THREAD

**Issue by AbhimanyuAryan** [pgadmin-org/pgadmin4#5932]
I found that in the theme section, you can switch to a dark/light theme but there's no option to follow the OS colour scheme. Can we have an automatic colour scheme based on the OS scheme(MacOS)

**Comment by RohitBhati8269** [comment]
Tested and verified on candidate build: [candidate-build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-18/)
Environment: MacOs

**Comment by RohitBhati8269** [comment]
Re-tested and verified on candidate build: [candidate-build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-24/)
Environment: macOS/Windows
