### ISSUE TITLE
pgAdmin does not respond while trying to Add or Set a new Server?

### ISSUE THREAD

**Issue by gudeso2023** [pgadmin-org/pgadmin4#5933]
Dear Community,

I am using Mac, My PG Admin (latest version) does not respond while trying to Add or Set up a new Server. I tried to remove and re-install it serval times but it won't work. I also followed these steps including deleting the cache files etc. on my Mac. I can confirm that PostGres works well and can be connected from QGIS DB Manager.

Check for updates: Make sure you have the latest version of PG Admin installed. You can check for updates by opening PG Admin, clicking on the "Help" menu, and selecting "Check for Updates".

Check your system requirements: Ensure that your Mac meets the minimum requirements for PG Admin. You can check the system requirements on the PG Admin website.

Restart PG Admin: Sometimes, restarting PG Admin can resolve issues. Close PG Admin completely, then try opening it again and adding or setting a new server.

Try running as administrator: On a Mac, you can try running PG Admin with administrator privileges. Right-click on the PG Admin icon, select "Get Info", and then check the box next to "Run as administrator".

Clear cache and temp files: Clearing the cache and temporary files can sometimes resolve issues with PG Admin. You can do this by going to the PG Admin folder on your Mac and deleting the cache and temp folders.

Any other advice?

Regards O

**Comment by adityatoshniwal** [comment]
@gudeso2023 Please share OS, pgAdmin version details. It would be helpful if you can share some screenshots or screen recording.

**Comment by iMoses** [comment]
I'm experiencing even worse issues. Add/Set new Server won't respond, as well as the file menu Preference and Rest Layout (and active Tools). It started when I upgraded to 6.21 but now going back to 6.20, 6.19, or 6.18 (my original) won't change anything and the app is basically unsable :|
OS is Windows 10 64

**Comment by patiiice** [comment]
Same thing as iMoses here. Since in installed 6.21, the query editor wont open as well as preferences or any other functionnality that uses a popup. Reverting to previous versions does not work either. Even 6.16, which was working well before i upraded does not work anymore

**Comment by iMoses** [comment]
I ended up removing the `../AppData/Roaming/pgadmin` directory which seems to have worked.

**Comment by patiiice** [comment]
Thanks for the advice. i was hoping i wouldn't have to do this since i'll probably have to create all my connections

**Comment by nikhil-mohite** [comment]
Hi @patiiice ,
Please share OS, pgAdmin version details. It would be helpful if you can share some screenshots or screen recording.

**Comment by PoojaR-Training** [comment]
there's same issue with me :(

**Comment by PoojaR-Training** [comment]
same issue with me :(

**Comment by akshay-joshi** [comment]
@PoojaR-Training 

Please share OS and pgAdmin version details. It would be helpful if you can share some screenshots or screen recordings.

**Comment by nikhil-mohite** [comment]
No response from author, hence closing it.

**Comment by gudeso2023** [comment]
RMIT Classification: Trusted

You can close the ticket

Dr Ori Gudes

RMIT University, Centre for Urban Research<https://www.rmit.edu.au/research/centres-collaborations/centre-for-urban-research>
Building 8, Level 11, La Trobe St, Melbourne VIC 3000 - Mail: RMIT University, GPO Box 2476, Melbourne VIC 3001
Ph: +61 401197227<tel:+61401197227> ***@***.******@***.***> ORCID: https://orcid.org/0000-0002-2102-885X
My list of publications (as of  March 2023): https://tinyurl.com/ya36nhnv


From: Nikhil Mohite ***@***.***>
Date: Friday, 21 April 2023 at 9:16 pm
To: pgadmin-org/pgadmin4 ***@***.***>
Cc: Ori Gudes ***@***.***>, Mention ***@***.***>
Subject: Re: [pgadmin-org/pgadmin4] pgAdmin does not respond while trying to Add or Set a new Server? (Issue #5933)

Closed #5933<https://github.com/pgadmin-org/pgadmin4/issues/5933> as not planned.
