### ISSUE TITLE
CREATE Script error

### ISSUE THREAD

**Issue by BoopalanSJB** [pgadmin-org/pgadmin4#5935]
I use pgAdmin version 6.15.

Whenever I try to get script of a table with constraints, I get error
"index_constraint/sql/#120005#/get_constraint_cols.sql"
(Right click on table -> Scripts -> CREATE Script)

When I try the same on a table without constraints, I'm not getting any
error, and able to get the table script.

Please help me to fix the issue.

**Comment by akshay-joshi** [comment]
@BoopalanSJB 

Can you please provide the DDL for Table with Indexs on it?

**Comment by BoopalanSJB** [comment]
It is just a test table, with below DDL. There is no index, but it has an primary key.



-- Table: public.tab1

-- DROP TABLE IF EXISTS public.tab1;

CREATE TABLE IF NOT EXISTS public.tab1
(
    slno integer NOT NULL,
    CONSTRAINT tab1_pkey PRIMARY KEY (slno)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tab1
    OWNER to postgres;

**Comment by BoopalanSJB** [comment]
Actually this issue exists on a particular PC only. In another PC, I have same pgAdmin version 6.15, and there I don't face this issue.

So looking for options to fix this pgAdmin issue, on the particular machine, where I have issue.

**Comment by adityatoshniwal** [comment]
Hi @BoopalanSJB,

Can you please try uninstall pgAdmin completely and then install again? There may be some out of sync SQL file which may be causing the problem. Your pgAdmin server data will not be lost on uninstall.

Thanks.

**Comment by adityatoshniwal** [comment]
@BoopalanSJB Once you uninstall pgAdmin, please make sure to remove any remaining installation files in installed path.

**Comment by khushboovashi** [comment]
No response from the author.

**Comment by BoopalanSJB** [comment]
I found the actual issue and the fix required.

In the particular PC, where the issue exits, the installation path of "pgAdmin" has 250+ characters, which exceeds Windows "MAXPATH" limit.

Once pgAdmin is uninstalled and reinstalled on a shorter installation path, the issue doesn't reoccur.

Hope this helps somebody.

**Comment by adityatoshniwal** [comment]
Thank you @BoopalanSJB. Alternative solution can be to increase the limit -  https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation
