### ISSUE TITLE
Please build apt package for Debian Bookworm

### ISSUE THREAD

**Issue by sylvainterrien** [pgadmin-org/pgadmin4#5936]
Please build apt package for Debian Bookworm.

I have read #5681 and understand that building continuously for _testing_ versions would be too much work or resource consumption, but I think now is the good time to start building for Bookworm : today it enters in Hard Freeze, the 3rd of 4 milestones that will make it Debian 12, the new _stable_ release (more details about this process : https://release.debian.org/testing/freeze_policy.html).

This means that build tools are now stable in Bookworm, e.g. Python default version is 3.11 and this will not change.

Bookworm becoming _stable_ also means Bullseye, now _stable_, will become _oldstable_ and Buster, now _oldstable_ will become _oldoldstable_, so it is probably OK to stop building for Buster.

Thanks.

**Comment by dpage** [comment]
A Debian 12 build worker has been added to the build farm, so assuming there are no build issues (there are a few at the moment, as we transition from v6.x to v7.x), snapshots should start being generated from tonight.

Buster is supported until June 30th 2024, so we won't be dropping that for 15 months or so.
