### ISSUE TITLE
Information for outdated pgAdmin goes to PostgreSQL instead of pgAdmin

### ISSUE THREAD

**Issue by asashour** [pgadmin-org/pgadmin4#5937]
**Describe the bug**

The dialog for showing outdated pgAdmin points to https://www.enterprisedb.com/downloads/postgres-postgresql-downloads, but it should be https://www.pgadmin.org/download/ isntead.

**To Reproduce**

1. Open pgAdmin 6.12
2. There is adialog of oudated version

**Expected behavior**

The 'here' should point to pgAdmin download/info.

**Error message**

The link goes to PostgreSQL download instead.

**Screenshots**

![image](https://user-images.githubusercontent.com/2410127/224544081-84ce0fa8-81bf-4d3b-8ca0-951a3069b97b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 6.12
 - Mode: Desktop

**Additional context**

**Comment by dpage** [comment]
If you got your copy of pgAdmin bundled with the PostgreSQL installer, then that is the correct URL. The update notifier knows what distribution you are using, and will direct you to the appropriate update for the installer you originally used.
