### ISSUE TITLE
Issue when dump servers with version 6.21

### ISSUE THREAD

**Issue by marcusricardoaguiar** [pgadmin-org/pgadmin4#5947]
- I am having the following issue when trying to run dump-servers with version 6.21:

```
[root@pgadmin4-instance-1 ~]# source /usr/pgadmin4/venv/bin/activate
(venv) [root@pgadmin4-instance-1 ~]# python /usr/pgadmin4/web/setup.py --dump-servers /var/lib/pgadmin/db_output.json --user pgadmin4@test.com

----------
Dumping servers with:
User: pgadmin4@biltcard.com
SQLite pgAdmin config: /var/lib/pgadmin/pgadmin4.db
----------
'AnonymousUser' object has no attribute 'username'
(venv) [root@pgadmin4-instance-1 ~]# 
```

**Comment by akshay-joshi** [comment]
@marcusricardoaguiar 

I am unable to reproduce this issue if we provide a user which doesn't exist for example in my case 'pgadmin4@test.com', pgadmin displays the message 'The specified user ID (pgadmin4@test.com) could not be found.' And if we provide a valid user then all the servers belonging to that user are dumped into the respective JSON file.
<img width="963" alt="Screenshot 2023-03-23 at 4 43 33 PM" src="https://user-images.githubusercontent.com/1632882/227188332-1dd84c87-f3fc-4c2f-8d9c-19de33c6d2ba.png">


Looking at the error it seems that somehow username is not there for one or more servers. Can you please confirm?

**Comment by marcusricardoaguiar** [comment]
Hi @akshay-joshi , I don't think that's the case because if I use the pgadmin4 with version 6.18 and try to use the same JSON file to load the servers, everything works fine. Actually, I believe that this situation happens because:
 - I had installed version 6.18 with some servers already loaded.
 - I upgrade to version 6.21 and tried to load a few more servers.
In this case, it always fails when using version 6.21.

I believe if you try this approach it will also fail for you.

Thanks!

**Comment by akshay-joshi** [comment]
@marcusricardoaguiar 

I am getting confused here, in the initial issue description you mentioned dump servers and used the command "--dump-servers" and now it is about load servers. Can you please share some screenshots, JSON file, or any one entry of a single server in JSON format where it is failing?

Using which version of pgadmin4 have you created the JSON file?

**Comment by marcusricardoaguiar** [comment]
@akshay-joshi , sorry. I meant to say dump. The following JSON is the one I've been trying to use when using dump-servers command:
```
{
  "Servers": {
    
    "1": {
      "Id": "pg-test",
      "Group": "Shared Bilt DBs",
      "Name": "pg-test",
      "Host": "pg-test.aivencloud.com",
      "Port": 15568,
      "MaintenanceDB": "defaultdb",
      "DBRestriction": "defaultdb",
      "Username": "developers",
      "PassFile": "/db_passwd_developers.pgpass",
      "SSLMode": "require",
      "Shared": true
    },
    "2": {
      "Id": "pg-test2",
      "Group": "Shared Bilt DBs",
      "Name": "pg-test2",
      "Host": "pg-test2.aivencloud.com",
      "Port": 15568,
      "MaintenanceDB": "defaultdb",
      "DBRestriction": "defaultdb",
      "Username": "developers",
      "PassFile": "/db_passwd_developers.pgpass",
      "SSLMode": "require",
      "Shared": true
    }
 }
}
```

Other than this, the only important screenshot I have to share is this one:
```
[root@pgadmin4-instance-1 ~]# source /usr/pgadmin4/venv/bin/activate
(venv) [root@pgadmin4-instance-1 ~]# python /usr/pgadmin4/web/setup.py --dump-servers /var/lib/pgadmin/db_output.json --user pgadmin4@test.com

----------
Dumping servers with:
User: pgadmin4@biltcard.com
SQLite pgAdmin config: /var/lib/pgadmin/pgadmin4.db
----------
'AnonymousUser' object has no attribute 'username'
(venv) [root@pgadmin4-instance-1 ~]# 
```

So, just to summarize the issue:
 - Previously, we were using version V6.18 and we use the JSON above to add server 1 in pgadmin4.
 - Last week, I updated to version V6.21 and, after that, I tried to add server 2 in pgadmin4.

Actually, to create the JSON file, I just did it manually. I've followed the pgadmin documentation and manually define it.

Thanks, and let me know if you need any additional information.

**Comment by akshay-joshi** [comment]
@marcusricardoaguiar 

If you are dumping the server then the JSON file is used as the output file, dump server is used to create the JSON file from the existing servers in the pgadmin4.db file, so there is no point in checking the JSON file. 

Please read https://www.pgadmin.org/docs/pgadmin4/6.21/import_export_servers.html#exporting-servers. Also, we need to identify why the user name is different in the command it is "**pgadmin4@test.com**" and in the output it is "**User: pgadmin4@biltcard.com**".

Please check the following:

- Run the command without --user, is this working?
- Check all the servers have usernames provided?
-  Have you manually changed the pgadmin4.db file?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.

**Comment by marcusricardoaguiar** [comment]
Sorry, I was out these days and I wasn't able to provide further details. I'm going to create a new ticket with further details.
