### ISSUE TITLE
GitHub tag for 6.21 not created

### ISSUE THREAD

**Issue by vedantmgoyal2009** [pgadmin-org/pgadmin4#5949]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Title says it

**To Reproduce**

1. Visit https://github.com/pgadmin-org/pgadmin4/tags
2. Look for v6.21 tag

**Expected behavior**

A tag for v6.21 should be there.

**Error message**

_No response_

**Screenshots**

_No response_

**Additional context**

_No response_

**Comment by akshay-joshi** [comment]
Done
