### ISSUE TITLE
Docker PGADMIN_LISTEN_ADDRESS='localhost'

### ISSUE THREAD

**Issue by Bastilla123** [pgadmin-org/pgadmin4#5951]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

I have download latest docker image over docker pull dpage/pgadmin4. Then i want that request are only available on localhost. I run sudo docker run -p 5150:80 -e PGADMIN_LISTEN_ADDRESS='localhost'  -e "PGADMIN_DEFAULT_EMAIL=mail@mail.de" -e "PGADMIN_DEFAULT_PASSWORD=StrongPassword" -d dpage/pgadmin4

but when i make curl -L -k htp://localhost:5150 then i get "Connection reset by peer"

when i delete PGADMIN_LISTEN_ADDRESS='localhost' PgAdmin works like a charm but is also available on complete network...

I configure that pgadmin only available on localost but on localhost i don't get a response from curl

1.  docker pull dpage/pgadmin4
2. sudo docker run -p 5150:80 -e PGADMIN_LISTEN_ADDRESS='localhost'  -e "PGADMIN_DEFAULT_EMAIL=mail@mail.de" -e "PGADMIN_DEFAULT_PASSWORD=StrongPassword" -d dpage/pgadmin4
3. curl -L -k htp://localhost:5150

**Expected behavior**

**Error message**

Repsonse from Curl

**Screenshots**

**Desktop (please complete the following information):**
Latest Docker Container from your Repo

**Additional context**

**Comment by MHenn1g** [comment]
Hey @Bastilla123 ,
I guess what happens by setting PGADMIN_LISTEN_ADDRESS='localhost' is that you limit the docker container to listen on its internal interface, which will only be reachable from within the container itself.

What you could do instead is to redirect the port via docker means to be available only on your docker host like so:
```
docker run -p 127.0.0.1:5150:80 \
  -e "PGADMIN_DEFAULT_EMAIL=mail@mail.de" \
  -e "PGADMIN_DEFAULT_PASSWORD=StrongPassword" \
  -d dpage/pgadmin4
```
This way, you should be able to reach the port on localhost, but not via the hosts IP:

```
> ifconfig en0
        inet 192.168.178.33 netmask 0xffffff00 broadcast 192.168.178.255


> curl http://192.168.178.33:5150/login
curl: (7) Failed to connect to 192.168.178.33 port 5150: Connection refused


> curl http://localhost:5150/
<!doctype html>
<html lang=en>
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to the target URL: <a href="/login?next=%2F">/login?next=%2F</a>. If not, click the link.
```

**Comment by Bastilla123** [comment]
Works. Thank you veery much
