### ISSUE TITLE
Error while executing continue in debugging session after some time of debug execution.

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#5953]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Error while executing continue in debugging session after some time of debug execution.
There are infinite API requests are done for /dbugger/message/ API, when a function 

**To Reproduce**

Steps to reproduce the behaviour:
1.Create a function - 
```
CREATE OR REPLACE FUNCTION public.test12(
	)
    RETURNS text
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
              BEGIN
                RAISE INFO 'This is a test function';
                RAISE NOTICE '<img src="x" onerror="console.log(1)">';
                RAISE NOTICE '<h1 onmouseover="console.log(1);">';
                RETURN 'Hello, pgAdmin4';
              END;
            
$BODY$;

ALTER FUNCTION public.test12()
    OWNER TO postgres;
```
2.Start debugging that function.
3.Check network tab.

**Expected behaviour**
Debugger should not send infinite AI requests.

**Screenshots**

<img width="1776" alt="Screenshot 2023-03-15 at 11 27 22 AM" src="https://user-images.githubusercontent.com/16016019/225220349-251d6e13-91af-4e30-8604-882abe7e4b4a.png">
<img width="1792" alt="Screenshot 2023-03-15 at 11 24 57 AM" src="https://user-images.githubusercontent.com/16016019/225220362-3977d26f-7e47-4843-9bb8-88af892b90d7.png">

**Desktop (please complete the following information):**
Dev env

**Additional context**

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on candidate build https://developer.pgadmin.org/builds/2023-04-03-2/

Env - macOS 12.6.4 (Desktop mode)
