### ISSUE TITLE
Dashboard graphs - Dark theme font color

### ISSUE THREAD

**Issue by mah-emad** [pgadmin-org/pgadmin4#5958]
up to 6.19 the graphs color (font & lines) when using dark theme was correct (white). since 6.20 the color (font & lines) is black which is hard to see against the dark background

**To Reproduce**

1. Change the theme to dark
2. Check dashboard to find the dark color (font & lines) against the dark background

**Expected behavior**

in dark mode, font & lines color should be white.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 6.20 / 6.21
 - Mode: Desktop

**Comment by long76** [comment]
upvote

**Comment by FaharAbbasRizvi** [comment]
This is fixed and tested in the latest snapshot build.

<img width="1620" alt="Screen Shot 2023-03-27 at 10 29 10 AM" src="https://user-images.githubusercontent.com/43006122/227849263-408e649f-c7a8-4eb7-91f1-185107e0c0fc.png">
