### ISSUE TITLE
Error trying to backup postgres database in Amazon Cloud

### ISSUE THREAD

**Issue by r4nddd** [pgadmin-org/pgadmin4#5959]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Using the pgadmin 6.21 backup dialog I receive an error trying to create a backup of a postgress DB in Amazon cloud.

....\pgAdmin 4\v6\web\pgadmin\tools\backup\__init__.py", line 409, in create_backup_objects_job
    if timeout and timeout > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to the Pgadmin dialogue
2. Click on the name and enter a name
3. Use for format "tar"
4. Press backup

**Expected behaviour**

Successful backup

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/8312589/225356683-8e1eb31e-4ced-4dc0-b51f-27ed12812963.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 6.21
 - Mode: [e.g Desktop or Server]

**Additional context**

**Comment by adityatoshniwal** [comment]
I can reproduce the issue if Connection timeout is added in Server dialog -> Parameters.

@r4nddd You can remove the parameter meanwhile and try.

**Comment by r4nddd** [comment]
Hello @adityatoshniwal it is working now that I removed the timeout parameter. 

Thank you

**Comment by FaharAbbasRizvi** [comment]
This is tested on all supported versions on the latest snapshot builds.
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-31/
