### ISSUE TITLE
Set "ALLOW_SAVE_TUNNEL_PASSWORD = True" in default configuration

### ISSUE THREAD

**Issue by mark-orion** [pgadmin-org/pgadmin4#5971]
**Describe the solution you'd like**
The fact that saving tunnel passwords is disabled by default is very inconvenient. It even shows up in this issue tracker again and again. And I notice that PGSQL servers or PGADMIN sometimes disconnect the tunnel leading to interrupted or unsaved work. I have never experienced that problem with password saving enabled.
So I would like to request that the option to save tunnel passwords is enabled by default:
This means "ALLOW_SAVE_TUNNEL_PASSWORD" is set to "True" in the default configuration.

**Comment by nikhil-mohite** [comment]
@mark-orion ,

Due to some security considerations, this can not be set to True by default.
