### ISSUE TITLE
Help on pgAdmin server connection

### ISSUE THREAD

**Issue by jip3131** [pgadmin-org/pgadmin4#5976]
Hi
I try to connect to my local account ut whatever I put I have the message 'Name' cannot be empty
![pgAdmin](https://user-images.githubusercontent.com/128472799/226575322-0cdfab4f-273f-476f-9bd3-2ec11a331d91.jpg)
Is anybody can explain me how to connect to my local server please?

**Comment by adityatoshniwal** [comment]
Hi @jip3131,

You need to provide a display name for the server in the "Name" field of General tab.

Thanks.

**Comment by adityatoshniwal** [comment]
Hi @jip3131,
"Crypt key is missing" means you have not entered/set the master password when pgAdmin asked for it at start. You can restart pgAdmin and set the master password.
The error message is improved in upcoming v7.0 version.

Thanks.

**Comment by jip3131** [comment]
Thanks, you are right
Now, new problem with the port

![image](https://user-images.githubusercontent.com/128472799/226588412-025f982a-d7f5-4461-a128-445a403ed8a5.png)

**Comment by adityatoshniwal** [comment]
Hi @jip3131,

This is not a pgAdmin problem. Make sure your server is reachable and you're entering the correct hostname and port.

**Comment by jip3131** [comment]
Yes the server is reachable
![image](https://user-images.githubusercontent.com/128472799/226594506-54576034-11d0-4719-99f7-592cd6120a58.png)
And I execute an netstat -ano -p tcp CMD in order to see the port for 127.0.01
![image](https://user-images.githubusercontent.com/128472799/226594772-df43a2d5-1fd8-4c7b-95d8-65f4013042f9.png)
But when I change the port number I have the same problem
![image](https://user-images.githubusercontent.com/128472799/226595065-f02d846e-b3f0-48fd-a648-ef4e7451f62a.png)

**Comment by adityatoshniwal** [comment]
@jip3131 By server I mean PostgreSQL server. The localhost is reachable mostly.

**Comment by jip3131** [comment]
sorry but i just want to use postregre on my own computer
So I try to apply, the tutorial below
https://www.javatpoint.com/connect-to-a-postgresql-database-server

**Comment by jip3131** [comment]
Hi
It's the same problem
![image](https://user-images.githubusercontent.com/128472799/227563260-ece34dad-a6b8-4ffe-ae00-69e374e02e13.png)

**Comment by akshay-joshi** [comment]
@jip3131 

It means it is not the pgadmin4 error, please check what's wrong with your PostgreSQL. Is the service running on the 5432 port or some other? Closing the issue.

**Comment by jip3131** [comment]
No when I start the service, it stop immediately
![image](https://user-images.githubusercontent.com/128472799/227854175-c75fc067-1a4e-4054-be03-13ec17831dc8.png)
And for information I have allowed the port 5432 in the firewall
But every time, I try to connect, I have a message error
![image](https://user-images.githubusercontent.com/128472799/227854331-e8e96c02-5c4d-41fa-93ab-6fa34a91818c.png)
