### ISSUE TITLE
Treenode will not expand

### ISSUE THREAD

**Issue by kflo-coder** [pgadmin-org/pgadmin4#6003]
Please reference the issue reported here:  https://github.com/pgadmin-org/pgadmin4/issues/5726#issue-1529691029

That issue was closed as resolved, but it is not resolved.  I posted additional comments to that effect, but to no avail.  I could not see a way to reopen the bug report, so I'm creating a new one.

I am using the most recent version of pgAdmin as of this date (v6.21), and the issue persists.

![image](https://user-images.githubusercontent.com/122488315/227284769-e67c1205-67f0-433d-a3dc-7150f43d1023.png)

**Comment by nikhil-mohite** [comment]
Hi @kflo-coder,

We tried but could not reproduce the issue, can you please try removing the server group and adding again?
If you are still facing the issue please share the logs located at the location mentioned here [https://www.pgadmin.org/faq/#8](https://www.pgadmin.org/faq/#8)

**Comment by kflo-coder** [comment]
@nikhil-mohite Thanks for the reply.  I am still facing this issue.  Removing and re-adding the servers don't make a difference, nor does the location of the server.  I have a local instance of PostgreSQL installed, along with several on virtual machines.  All demonstrate the same behavior when I run pgAdmin on my PC.

Attached is the requested log file, enabled at the DEBUG log level.  I tried collapsing/expanding the server node multiple times
[pgadmin4.log](https://github.com/pgadmin-org/pgadmin4/files/11127582/pgadmin4.log)

**Comment by anilsahoo20** [comment]
Hi @kflo-coder 
Can you please try on the pgAdmin4 v7.0 once?

**Comment by kflo-coder** [comment]
Hi, @anilsahoo20.

Just tried uninstalling v6 and installed v7.0.  No difference; same result. as what was happening on v6.x.

**Comment by adityatoshniwal** [comment]
Hi @kflo-coder, are you seeing any errors in `File->Runtime->View Log`?

**Comment by kflo-coder** [comment]
@adityatoshniwal None that I can see; this has been truly baffling.  Attached the log...  
[pgadmin4.1681771417789.log](https://github.com/pgadmin-org/pgadmin4/files/11256414/pgadmin4.1681771417789.log)

**Comment by khushboovashi** [comment]
@kflo-coder, we can have a screen-sharing session, so that I can understand the issue. 
Let me know your availability, I am in the IST timezone.

**Comment by kflo-coder** [comment]
@khushboovashi That sounds good to me.  I'm in the Eastern Daylight Time timezone.

**Comment by khushboovashi** [comment]
On Wed, Apr 19, 2023 at 6:23 AM kflo-coder ***@***.***> wrote:

> @khushboovashi <https://github.com/khushboovashi> That sounds good to me.
> I'm in the Eastern Daylight Time timezone.
>
Tomorrow (20th April) @ 6:30 PM IST  (9:00 AM EDT)?

**Comment by kflo-coder** [comment]
@khushboovashi 
That works; thank you!

**Comment by khushboovashi** [comment]
Zoom Call details:

https://enterprisedb.zoom.us/j/98810469344?pwd=M0dsSlB2aWVpRDhaVjI0bGJqM1krUT09

Meeting ID: 988 1046 9344
Passcode: 212957

**Comment by khushboovashi** [comment]
Hi @kflo-coder,

Please email me, so I can share the Zoom details.

**Comment by kflo-coder** [comment]
Thanks for @khushboovashi for meeting with me this morning on this issue.

In summary, she helped resolve the issue. The problem was simply that the preferences under Preferences > Browser > Nodes were set to disabled...  for EVERY node.  I never made this change; it seems to have happened during one of the upgrades a year ago. Once reenabling those settings, alas, everything rendered as expected again. So, thanks @khushboovashi for double-checking the obvious thing.

A big part of what was misleading was this:  she repeated many of the debugging exercises that I had done on my own, including checking the HTTP traffic during the attempts to render the nodes under the server node. Of particular note in this was the response to request to render the nodes showed nothing in the response:  `{"success":1,"errormsg":"","info":"","result":null,"data":[]}`

If there is anything to recommend coming out of this, it's perhaps to ask that something could be rendered in the log indicating that data _was_ returned, but that pgAdmin settings are keeping them hidden.

**Comment by khushboovashi** [comment]
pgAdmin will give the indication if the user has disabled all the server's children from the preferences.

**Comment by FaharAbbasRizvi** [comment]
when the user hides all nodes, the indication message response time is very fast while reading the message it disappears, I think we should increase the response time

**Comment by adityatoshniwal** [comment]
@FaharAbbasRizvi  I did change yesterday to keep the notification open until closed. Please verify again.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-23/
