### ISSUE TITLE
Add "Ignore tablespace" to Schema Diff

### ISSUE THREAD

**Issue by jflambert** [pgadmin-org/pgadmin4#6004]
**Describe the solution you'd like**

In the "Compare" button dropdown (which has Ignore owner/whitespace) I would like to have a new "Ignore tablespace" option.

Some of my database tables have an explicit `TABLESPACE pg_default;` setting and some others don't have it declared at all. I'm not sure why. Of course, not declaring tablespace is equivalent to using pg_default. I'm using various docker flavours, some from timescaledb, some from debian, some on alpine. That must be why.

**Describe alternatives you've considered**

I'm not even sure I can redeclare tablespace post initdb. For now I just ignore these diffs, but I get a lot of false flags.

**Additional context**

Worth mentioning that even though there is a difference, the Difference panel doesn't show an instruction.

![image](https://user-images.githubusercontent.com/11539524/227340545-18aa9cd7-7d30-4fda-a2b4-847108bae8de.png)

**Comment by stanhu** [comment]
I would like this too! I have over 5000 lines in a diff with `ALTER X SET TABLESPACE pg_default;`.

**Comment by yogeshmahajan-1903** [comment]
Working fine
