### ISSUE TITLE
UI Graphs

### ISSUE THREAD

**Issue by ColaKola** [pgadmin-org/pgadmin4#6016]
Add metric prefixes only for the coordinate plane of graphs with large values. The interpretation of the style of points should be left unchanged.
For example Tuples out 500 000 as 500k, 1 000 000 as 1M, 1 500 000 as 1.5M.
![изображение](https://user-images.githubusercontent.com/14040388/227593677-61e447df-604c-487c-8057-c1384449a705.png)

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on the latest snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-11-08/).

Env:
OS - macOS Sequoia (15.1)
Mode - Desktop
