### ISSUE TITLE
Geometry Viewer renders geometry incorrectly after trying to view 3D or non-4326 SRID geometry

### ISSUE THREAD

**Issue by brendan33** [pgadmin-org/pgadmin4#6017]
**Describe the bug**

When viewing geometry which the Geometry Viewer is unable to render (e.g 3D points or non-4326 geometry) it seems to corrupt the viewer and from then on it plots all valid geometry in the wrong location.
It is not immediately obvious that the viewer is broken because it will still plot geometry, but in the wrong place. Restarting the viewer and plotting the exact same data will then plot it correctly.

**To Reproduce**

1. Open the Query Tool for a database with the PostGIS extension
2. Run this query to create a 3D point in London `SELECT ST_GeomFromText('POINT(-0.222 51.475 0)',4326)`
3. Click `View all geometries in this column` button 
![image](https://user-images.githubusercontent.com/45767170/227587505-b1df30ea-0ec5-48f6-b742-68d1ccaf7cbf.png)
4. You will see a blank map with a message saying `3D geometries not rendered`  (THIS IS NOT THE ERROR)
5. Modify your query to convert or create a 2D point which the Geometry Viewer should be able to render e.g:
 `SELECT ST_Force2D(ST_GeomFromText('POINT(-0.222 51.475 0)',4326))`
or
 `SELECT ST_GeomFromText('POINT(-0.222 51.475)',4326))`
6. Click `View all geometries in this column` button 
![image](https://user-images.githubusercontent.com/45767170/227587505-b1df30ea-0ec5-48f6-b742-68d1ccaf7cbf.png)
7. The point plots in the wrong location. 
8. At this point, any geometry you view in this Query Tool shows in the wrong place. Try selecting any geometry from any existing table which you know is valid and it will be wrong. I have spent a lot of time at this point scratching my head wondering what's wrong with my geometry, especially when doing complex manipulations or transformations as whatever you try (even if code is valid) it plots incorrectly.
9. Open a new Query Tool, paste the same query from step 5 and run and the point is in correct location which proves there is something wrong with the Geometry Viewer in the other Query Tool.

**Expected behavior**

The Geometry viewer should not break after attempting to view 3D geometry. Especially when running a completely different and valid query.

**Error message**

No error message is shown.

**Screenshots**
After trying to view a 3D geom the 2D point is in the wrong location:
![image](https://user-images.githubusercontent.com/45767170/227589991-99daccfc-3baf-46fd-8629-370d43d10dff.png)

Opening a new Query Tool and immediately viewing the 2D point works as expected:
![image](https://user-images.githubusercontent.com/45767170/227589604-3f702dc6-bfd7-4bd1-b0b8-d361f80ac381.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PGAdmin Version: 6.21
 - Postgres Version: Ubuntu 12.4-1.pgdg18.04+1
 - PostGIS Version: 3.0
 - Mode: Desktop
 - Browser (if running in server mode): n/a
 - Package type: Standard Windows exe installer

**Additional context**

This actually started happening quite a few versions back (maybe even up to a year ago possibly), but I only recently figured out the steps that cause it.
I have a table which has 3D geometries and 50% of the time I run a `SELECT` statement on it I forget to add `ST_Force2D` so I now experience the above scenario when I know when making this mistake before, I corrected it and the viewer was always fine.
A few other things:
- If you manually close the Geometry Viewer tab instead of the Query Tool tab, that also fixes the issue.
- The exact same thing happens when you first try to plot a non-4326 SRID geometry and then transform it to 4326 that should plot correctly, but doesn't. e.g try without the transform, and then with it `SELECT ST_Transform(ST_GeomFromText('POINT(460000 160000)', 27700), 4326)`

It seems like some invalid configuration is being remembered even after running a new query when in previous PGAdmin versions something must have been reset when running each query.

**Comment by alvasilvao** [comment]
Hi,

I have experienced the same error. Are there any leads on how to solve this?

**Comment by dataspun** [comment]
I've experience the same as well.  The workaround is suitable (new query window) but obviously a bug deserving a fix.

**Comment by adityatoshniwal** [comment]
Workaround is to close the geometry viewer and click on view geometry button.

**Comment by yogeshmahajan-1903** [comment]
Working fine.
