### ISSUE TITLE
pgadmin4 6.21: keywords like "SERIAL" or "VARCHAR" are not being highlighted

### ISSUE THREAD

**Issue by F3Qz** [pgadmin-org/pgadmin4#6018]
I recently downloaded the `6.21` version of `pgadmin4`, but encountered an error that is bothering me. Every time I write keywords like `SERIAL` or `VARCHAR` (which used to be highlighted in **yellow** until the 6.12 version) they continue to appear in the same color as `non-keywords`, such as `column_name`, as it follows:
![image](https://user-images.githubusercontent.com/73968775/227780053-1649625d-451e-45ec-add3-205e15774dbd.png)

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot.
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-30

**Comment by FaharAbbasRizvi** [comment]
@F3Qz https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-31/
