### ISSUE TITLE
Tools menu toggle "pause replay of wal" and "resume replay of wal"

### ISSUE THREAD

**Issue by Reinder22** [pgadmin-org/pgadmin4#6026]
If setup a master / dual slave synchronous postgresql 15 configuration.

When I toggle form the Tools menu of the right mouse button on the server and i toogle the "pause replay of wal" I never be able to " hit the button "resume replay of wal".

Work-around from the sql-query tool from the postgres database, run select resume replay of wal.
The status wil be changed.  The command "SELECT pg_get_wal_replay_pause_state()" gives the correct answer.

**Comment by nikhil-mohite** [comment]
Menu Options are getting enabled and disabled with the right success message, but if we execute the `Resume Replay of WAL` and `Pause Replay of WAL` multiple time pgAdmin tree stop working, and other feature depending on the tree also stop working e.g: unable to open `Query Tool`, Enable/ Disable of Menus from `Browser toolbar` is not working on tree node selection.

**Comment by nikhil-mohite** [comment]
Resolved, and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-25/
OS: macOS 
Mode: Desktop
