### ISSUE TITLE
pgAdmin prompts for password when a tunnel is configured with a non-password protected private key

### ISSUE THREAD

**Issue by imcdona** [pgadmin-org/pgadmin4#6032]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

pgAdmin prompts for password when a tunnel is configured with a non-password protected private key.

**To Reproduce**

1. Register a new connection
2. Fill out the required Postgres server information and credentials
3. Click on the 'SSH Tunnel' tab
4. Select 'Use SSH tunneling'
5. Fill out the fields for 'Tunnel host', 'Username' and 'Port'
6. For 'Authentication' select 'Identify file'
7. Select a previously uploaded private key that's not password protected. In this case the private key has a '.txt' extension. (not sure if that's relevant or not)
8. Leave the password blank as the private key is not password protected
9. Select 'Save' and note that you are now connected to Postgres via the SSH tunnel
10. Disconnect from the server
11. Attempt to reconnect and note that you are asked for the password for the SSH tunnel. Enter anything in the password field and select okay. Note the connection is established.

**Expected behavior**

pgAdmin shouldn't prompt for the password to a non-password protected identity file when connecting.

**Error message**

N/A

**Official Docker image:**
```
Version 6.21
Application Mode Server
Current User
Browser Firefox 111.0
Operating System Linux-4.18.0-372.16.1.el8_6.0.1.x86_64-x86_64-with
pgAdmin Database File /var/lib/pgadmin/pgadmin4.db
Log File /dev/null
```

**Comment by akshay-joshi** [comment]
It's been difficult to identify whether the identity file is having password or not. If it's working after providing any password or blank password then should not be a problem.

**Comment by odoo-sh** [comment]
@akshay-joshi applying blank password is working. But this shouldn't be the case. An identity file without password shouldn't be prompted for password.

**Comment by akshay-joshi** [comment]
@odoo-sh 

We haven't figured out any way to identify whether an identity file is having password or not. Is there any way to identify it? 
If it is please suggest us, will try to fix this issue.

**Comment by oliver-dungey** [comment]
Why have you closed this one? There is an easy fix - just enable the 'Save Password' checkbox even if a user hasn't put in a password. Internally it can store the setting as a key without a value.

**Comment by Santhosh-Yabx** [comment]
please use the key in .pem format instead of .ppk

**Comment by Santhosh-Yabx** [comment]
@oliver-dungey as i'm googling for my issue , found this blog similar to my issue. Posted here my solution. not to any specific.


"pgAdmin prompts for password when a tunnel is configured with a non-password protected private key"

**Comment by Eninspace** [comment]
worked with pem format, I used `ssh-keygen -p -m PEM -f your_key.file` to change my key in openssh format

**Comment by hertell** [comment]
> 
> We haven't figured out any way to identify whether an identity file is having password or not. Is there any way to identify it? If it is please suggest us, will try to fix this issue.

@akshay-joshi Are you still looking for a solution to this? Chek the return value of
ssh-keygen -y -P "" -f "sshkeyfile" &>/dev/null
and you will know wether the keyfile needs a password or not

**Comment by vimutti77** [comment]
It's a bit annoying every time it prompts for a password. Allowing to 'Save Password' on blank password would help a lot.

**Comment by jaowork** [comment]
Still a problem in 2025. It is also misleading in that it requires a key in openssh format and doesn't throw an actual correct error when the key is in ppk format
