### ISSUE TITLE
Debugger Error "Error while polling result." if user click on setbreak point twice

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6059]
- OS: [e.g. All]
 - Version: [e.g. 7.0]
 - Mode: [All]
 - Package type: [All]

"Error while polling result." if user click on setbreak point twice

**To Reproduce**

1. Launch Debugger
2. Click on set break point 
3. Again Click on set break point
4. pop up message displayed There is another debugger session displayed and that is expected
5. Now Debugger Error "Error while polling result." is displayed and that is the issue

**Expected behavior**

No error message was displayed related to connection polling of the user clicking on setbreak point twice

**Screenshots**

<img width="1778" alt="Screen Shot 2023-03-31 at 9 02 58 AM" src="https://user-images.githubusercontent.com/43006122/229019968-41f875fe-447f-4f4f-8992-e213486d98b2.png">

**Comment by adityatoshniwal** [comment]
This is not reproducible with latest version. Closing.
