### ISSUE TITLE
Debugger should be disabled on system catalogs

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6060]
**Describe the bug**

If the user goes into the pg_catalogs and expands the procedure node then "raise_application_error" is also displayed but if the user tries to debug it, the user can do it, the debugger should be disabled for system catalogs

**To Reproduce**

1. Go to PostgreSQL_catalogs(pg_catlogs)
2. Right Click on a procedure3.  select debugger and click on click on debug
4. No result is displayed

**Expected behavior**

Debugger should be disabled on system catalogs.

**Screenshots**

<img width="1779" alt="Screen Shot 2023-03-31 at 9 32 04 AM" src="https://user-images.githubusercontent.com/43006122/229025073-741c4a99-eda5-4789-887c-1ab86e123a32.png">

**Desktop (please complete the following information):**
 - OS: [All]
 - Version: [tested on v6.21 and above]
 - Mode: [All]
 - Package type: [All]

**Comment by RohitBhati8269** [comment]
It's working fine as expected.

**Tested and verified on snapshot build:** [](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-20/)
**OS:** [All]
**Mode:** [Desktop and Server]
**Package type:** [All]
