### ISSUE TITLE
Few query tool shortcuts not working

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#6065]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

A few shortcuts in the query tool are not working 

**To Reproduce**
List of shortcuts   (keys can be different on user setup I am using default keys):
1. Connection status -> Accesskey + t : Not performing anything 
2. Execute options -> Accesskey + x: not working and also `showing wrong shortcuts` on UI
3. Find options -> Accesskey + n : not working
4. Row limits -> Acesskey + r :  : not working
5. Download Results is working only if we click on the Data output panel and press the shortcut, but if we are on the query tool tab it is not working (But other shortcuts like delete & paste rows work even query tool tab has selected no need to click  on Data output panel)
6. Shift Panel: this is working but it just highlights the panel title (In the older version if we switch panels from quay editor to scratch pad it is getting selected and the user can directly start typing now the cursor is not showing so user need to click to write)

**Expected behavior**

Shortcuts should work and should not show the wrong shortcut keys on the UI

**Desktop (please complete the following information):**
 - OS: OSX Ventura (13.3)
 - Version: Latest snapshot https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-31/
 - Mode: Desktop

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-21/
