### ISSUE TITLE
When Service specified in Server dialog, certain other fields should be optional

### ISSUE THREAD

**Issue by spkendall** [pgadmin-org/pgadmin4#6074]
**Describe the solution you'd like**

When registering a new server and I specify a service name in the Service field, I am still required to specify Host, Port, and Username. This should be optional, since all of those values could be in the .pg_service.conf file.

**Describe alternatives you've considered**

Currently the only alternative is to specify all the values, even though they should not be needed.

**Additional context**

My entries in .pg_service.conf look like this:

```
[devserver-admin-postgres]
host=devserver.local
port=5432
sslmode=require
user=admin
dbname=postgres
```

It should not be necessary to specify any of these values in pgAdmin when I tell pgAdmin to use the devserver-admin-postgres service

**Comment by adityatoshniwal** [comment]
Hi @spkendall,

What is the version of pgAdmin are you using? I tested on v6.21 and it works as expected.

**Comment by spkendall** [comment]
I opened this issue based on 6.20, where it worked (for me) exactly as I described.

I just upgraded to 6.21, and, as you said, it works the way I want it to.

Sorry for the confusion, and thank you!
