### ISSUE TITLE
When registering a new server fails, don't disable the Save button

### ISSUE THREAD

**Issue by spkendall** [pgadmin-org/pgadmin4#6075]
**Describe the solution you'd like**

When registering a new server fails, Save is disabled until the dialog values are changed. This happens whether the failure is because of wrong input (which might require changes to the input) or an error upstream of pgAdmin, such as a network failure or the server being down. Save shouldn't be disabled after a Save error message unless pgAdmin is sure that no further attempts could possibly succeed.

**Describe alternatives you've considered**

The alternative is to make a null change (e.g., space-backspace) to some field in the dialog, but this is tiresome when diagnosing a problem with the network or the server.

**Additional context**

1. Register a new server which is currently down
2. Click Save and get the error message "Unable to connect to server..."
3. Start up the server specified in step 1
4. Try to click Save

**Comment by anilsahoo20** [comment]
Tested and verified on latest snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-27/

Environment: macOS Ventura 13.3
