### ISSUE TITLE
[pgAgent] Remove Search objects and psql tool menus from context menu

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6077]
**Desktop (please complete the following information):**
 - OS: [All]
 - Version: [Tested on 6.21 and Above]
 - Mode: [All]
 - Package type: [All]
**Describe the bug**

If the user Clicks on pgAgent Jobs and selects Search objects, the "Not found"  error is displayed; if the user selects the Search object and PSQL Tool under pgAgent jobs, no result is displayed.

**To Reproduce** 

Scenario 1:
1. Go to pgAgent
2. Click on pgAgent Jobs3. Click on Search objects
3. Search objects open but a message "Not found" is also displayed

Scenario 2.
1. Go to pgAgent
2. Create New pgAgent Jobs
3. Job created successfully
4.  Click on a particular job
5. Right Click Search object and PSQL Tool
6. No Result is displayed

**Expected behavior**

The result should be displayed if the user selects the Search object and PSQL Tool

**Screenshots**

<img width="1473" alt="Screen Shot 2023-04-03 at 11 14 05 AM" src="https://user-images.githubusercontent.com/43006122/229428051-23dc3f8f-30d7-4370-a2f5-dbc0f0644f9c.png">
<img width="1782" alt="Screen Shot 2023-04-03 at 11 13 12 AM" src="https://user-images.githubusercontent.com/43006122/229428131-f62b4360-6f6e-44f3-bd17-8bd126c7ee87.png">

**Comment by adityatoshniwal** [comment]
This is not implemented yet. Duplicates #3441

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-25/
