### ISSUE TITLE
Windows 10 not showing pgAdmin icon on taskbar

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#6080]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Open pgAdmin 4 on windows it is not showing the pgAdmin 4 icon on the taskbar

**To Reproduce**
This issue is related to the latest version of NWjs (0.74) issue [https://github.com/nwjs/nw.js/issues/8039](https://github.com/nwjs/nw.js/issues/8039)

<img width="121" alt="image" src="https://user-images.githubusercontent.com/69510038/229447685-1d9260cf-7043-4bbd-a387-9ebe147feb3b.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: latest snapshot: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-03/
 -  Mode: Desktop

**Comment by garagusopdfs** [comment]
This happens also in the SDK, and in version 0.75

**Comment by adityatoshniwal** [comment]
Please try the workaround suggested here - https://github.com/nwjs/nw.js/issues/8039#issuecomment-1528510777

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-18/
