### ISSUE TITLE
Shared Servers - unique usernames

### ISSUE THREAD

**Issue by nigzak** [pgadmin-org/pgadmin4#6084]
**Describe the solution you'd like**
Add a shared server and having unique usernames per logged-in user instead of shared username

**Describe alternatives you've considered**
No one

**Additional context**
If same server is used in one pgadmin on multiple accounts it is not always common to share same username over all accounts.
Ex: Server A is used from all users, each user has a unique username/password for it
=> it is not possible to use shared servers because the "last user" who changes the userid overwrites it for the others

**Comment by adityatoshniwal** [comment]
Hi @nigzak,

pgAdmin shared server do not share username. Username has to be specified by each pgAdmin user and is stored separately for each pgAdmin user.
I cannot reproduce what you're saying.

Thanks.

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
