### ISSUE TITLE
Servers => duplicate Server context menu

### ISSUE THREAD

**Issue by nigzak** [pgadmin-org/pgadmin4#6085]
**Describe the solution you'd like**
There should be a context menu for cloning a server configuration
Server <right click> => clone server

**Describe alternatives you've considered**
No one

**Additional context**
If you working with different usernames ("rights") in the database you have to manually clone the servers to avoid you always working with the highest rights

ex:
admin-account
readonly-account

If I want to configure stuff I need to use admin account
If I want to make a "select ..." I can use the readonly-account - for this I have 1:1 to clone the admin server and user different username/password

If I have more rights it can get to more duplicated servers.
This is as today messy because I have to configure all servers manually multiple times ...

HINTS: 

- would also be nice to clone a "shared server" to a "local server" (like a "copy template")
- certificates should also be copied if configured, this should include COPY if it is not existing in dedicated account ("shared server clone"; ex: root server certificate)

**Comment by johnmreynolds** [comment]
This is definitely one of the biggest annoyances I have with pgadmin. I found this from searching for whether there is any way of doing this.

**Comment by pravesh-sharma** [comment]
Tested and is working as expected. Verified on candidate build https://developer.pgadmin.org/builds/2024-01-08-1/

Env 
OS - Rocky 8
Mode - Desktop and server
