### ISSUE TITLE
Drag and drop on publication object

### ISSUE THREAD

**Issue by anilsahoo20** [pgadmin-org/pgadmin4#6086]
**Describe the solution you'd like**

Currently drag and drop on node objects are working for all other required node objects except publication node object.
While creating subscription for a publication, drag and drop can be used in place of writing the whole publication name by the user.

**Describe alternatives you've considered**

CTRL+C AND CTRL+V  works for copying the name of the publication node object.

**Comment by pravesh-sharma** [comment]
Issue fixed verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-15/).

Env:
OS - Rocky Linux 9
Mode - Desktop
