### ISSUE TITLE
Cannot drag table names or column names from tree view into the Query tool

### ISSUE THREAD

**Issue by JonathonWebster** [pgadmin-org/pgadmin4#6089]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

I recently upgraded from postgres 12 to 15.  In the new PGAdmin4 interface, I can no longer drag table names or column names from tree view into the Query tool.  This requires me to type out everything manually.

**To Reproduce**

1. Go to Query tool
2. try to click and drag a table name into the query tool window (allowing you to use it for writing sql)
3. notice it doesn't work

**Expected behavior**

It doesn't work

**Error message**

no error message

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 home
 - Version: 22H2
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: I don't know

**Additional context**

I used the browser version of PGAdmin4 when I was on Postgres12. now the new PGAdmin4 is a desktop application.

**Comment by adityatoshniwal** [comment]
Hi @JonathonWebster,
I am guessing pgAdmin was also upgraded which is shipped with PG server installers of EDB. The issue was fixed in v6.20.
You can uninstall pgAdmin shipped with PG15 and install the latest separately from https://www.pgadmin.org/download/

Thanks.

**Comment by JonathonWebster** [comment]
Awesome, thank you so much!

*Jonathon Webster*
Product, Marketing & Analytics
