### ISSUE TITLE
Query tool connections are not getting closed on closing query tool panel(FF specific)

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#6092]
**Describe the bug**

Query tool connections are not getting closed on closing query tool panel(FF specific).

**To Reproduce**

1.Open Query tool.
2.Check DB connections in dashboard tab. New connection added for query tool.
3.Close query tool.
4.Check DB connections in dashboard tab.
Connection created for query tool is still present.

**Expected behavior**

DB connection should be closed on closing query tool/ERD tab.

**Error message**

NA

**Screenshots**

NA

**Desktop (please complete the following information):**
Dev env but only on Firefox

**Additional context**

Related to #5894

**Comment by adityatoshniwal** [comment]
There is no workaround/solution at the moment due to limitations of FireFox browser. Chrome and other browsers works fine.
