### ISSUE TITLE
Shared Servers: Can not disable "Shared?" button and missing password field

### ISSUE THREAD

**Issue by ghost** [pgadmin-org/pgadmin4#6094]
I'm using the latest version of pgAdmin4 (6.21).

The only change I've made was adding the string `ALLOW_SAVE_PASSWORD = False` to the end of the **/usr/pgadmin4/web/config.py** file;

Registering a new server with "Shared?" option enabled and successfully connect, after disconnect from it the "Shared?" option is grayed out.

If I go to: Right Click Server Name -> Properties... -> Connections:
There is no password field and the interface shows an error message: "Please enter a valid value for parameter."

If I make login with another user, I was directly redirected to the connection setting interface. Which shows the error message "Username must be specified."

Navigating to the "Connection" section, there is no password field either.

**Comment by pravesh-sharma** [comment]
The issue is fixed on the latest version of pgAdmin 4.
