### ISSUE TITLE
security_invoker not showing up in definition for table views

### ISSUE THREAD

**Issue by JesseVelden** [pgadmin-org/pgadmin4#6099]
**Describe the bug**
The view definition pgAdmin doesn't show if a PostgreSQL 15 view is defined `with (security_invoker=true)`

**To Reproduce**
1. Go to a DB View which has `security_invoker` turned on
2. Look at the SQL Tab
3. The view definition doesn't show if it is defined with a `security_invoker`

**Expected behavior**
That the definition shows `with (security_invoker=...)` when it is turned on

**Desktop:**
 - Version: 6.21
 - Mode: Desktop

**Additional context**
It seems like even the `definition` column in the `pg_views` table doesn't show it.
I've asked a question about this at [StackOverflow as well](https://stackoverflow.com/questions/75909367/postgresql-check-if-security-invoker-is-turned-on-on-view) and the only way I could check if it is turned on is by looking at the `pg_class` table and the `reloptions` column. 

Example SQL statement I use now to check it:
```sql
select 
  relname, 
  case 
    when lower(reloptions::text)::text[] && array['security_invoker=1','security_invoker=true','security_invoker=on'] 
      then true else false
  end as security_invoker
from pg_class
  join pg_catalog.pg_namespace n on n.oid = pg_class.relnamespace
where n.nspname = 'public' and relkind='v';
```

**Comment by pravesh-sharma** [comment]
This has already been implemented #6371.

@JesseVelden Please install the latest version of pgAdmin 4 from https://www.postgresql.org/download/
