### ISSUE TITLE
Create database... Collations not shown

### ISSUE THREAD

**Issue by Bykiev** [pgadmin-org/pgadmin4#6102]
Hi, I'm new to Postgres and PgAdmin.

I need to create a database with predefined collation, but on Definition tab only 3 collations are shown, but if I'll query from `pg_collation` there are 741, how to use them during creation DB?

**Comment by adityatoshniwal** [comment]
Hi @Bykiev,
pg_collation will include all the collations - user defined and pg system defined. pgAdmin by default hides system defined objects. You can this from `File->Preferences->Browser->Display->Show system objects?`. You need to refresh the collation node to reflect the change.

Thanks.

**Comment by Bykiev** [comment]
Thank you, I've enabled this option, but what do you mean by refreshing the collation node?

**Comment by adityatoshniwal** [comment]
@Bykiev If the collations node is already opened then right click and selected refresh.

**Comment by Bykiev** [comment]
Thanks, still no any other collations when creating a new database...

**Comment by adityatoshniwal** [comment]
@Bykiev OK I got it. The other collations are under pg_catalog schema. To go to pg_catalog schema, go to
`[database]->Catalogs->PostgreSQL catalog->Collations`.

**Comment by Bykiev** [comment]
Yes, I see theme here, but still can't use them while creating a new database

**Comment by adityatoshniwal** [comment]
@Bykiev Those collations are used when creating database objects and not for creating a database.

**Comment by Bykiev** [comment]
Thank you!
