### ISSUE TITLE
pgadmin4 don't support pgAgent

### ISSUE THREAD

**Issue by Wangdamao01** [pgadmin-org/pgadmin4#6104]
use docker deploy pgadmin4。
image version  dpage/pgadmin4

The web version was not found pgAgent
![image](https://user-images.githubusercontent.com/107663606/230701364-3633793e-a63f-439b-8daf-2108e787e4c2.png)
but I want to use the pgAgent function, pgAgent plug-in how to install in the container

**Comment by yogeshmahajan-1903** [comment]
@Wangdamao01 
Kindly add extension to maintenance database. You can either add from extension node or using query tool & refresh the browser tree.

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
