### ISSUE TITLE
Cannot See Servers from pgadmin4

### ISSUE THREAD

**Issue by chintalapudikrishna** [pgadmin-org/pgadmin4#6106]
Hi Teams,

Need Help, I recently configured pgadmin4 and now I'm not able to see Servers option in the under browser, also no options are working (eg Prefences etc.). Kindly let me know what could have gone wrong in Configurations
Please check the attached screenshot
![image](https://user-images.githubusercontent.com/21332720/230711104-23bbf5e2-5fdb-461a-a61b-46bd04f16520.png)

**Comment by yogeshmahajan-1903** [comment]
@chintalapudikrishna 
Can you please try File > Reset layout option. Also what is pgAdmin version?

**Comment by chintalapudikrishna** [comment]
> @chintalapudikrishna Can you please try File > Reset layout option. Also what is pgAdmin version?

Hi @yogeshmahajan-1903, yes tried that too. but no links in the console are working and I'm Using PgAdmin4 V6.16

**Comment by yogeshmahajan-1903** [comment]
> > @chintalapudikrishna Can you please try File > Reset layout option. Also what is pgAdmin version?
> 
> Hi @yogeshmahajan-1903, yes tried that too. but no links in the console are working and I'm Using PgAdmin4 V6.16

Could you please try latest version 6.21?
Also what is the OS & pgAdmin mode(Server/Desktop)? If possible could you please share logs. Steps to enable/view logs are mentioned [here](https://www.pgadmin.org/faq/#8).

**Comment by hektordaniel** [comment]
Hi 

I have the same issue I unfold the datbase objects suddenly browser is empty. I have upgraded to last version and issue is still present.

![image](https://user-images.githubusercontent.com/73377361/231347330-12e482e3-0256-49d4-bda9-7dadad802e07.png)

**Comment by chintalapudikrishna** [comment]
> > > @chintalapudikrishna Can you please try File > Reset layout option. Also what is pgAdmin version?
> > 
> > 
> > Hi @yogeshmahajan-1903, yes tried that too. but no links in the console are working and I'm Using PgAdmin4 V6.16
> 
> Could you please try latest version 6.21? Also what is the OS & pgAdmin mode(Server/Desktop)? If possible could you please share logs. Steps to enable/view logs are mentioned [here](https://www.pgadmin.org/faq/#8).

Hi @yogeshmahajan-1903 , Update: it is working for me after upgrading to V6.21. Thank you  for the support

**Comment by akshay-joshi** [comment]
Issue resolved, as per the author.
