### ISSUE TITLE
“Schema Diff "  Invalid function

### ISSUE THREAD

**Issue by jcjgithub** [pgadmin-org/pgadmin4#6108]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
version: 6.20
pg version: PostgreSQL 14.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
os: win10

**To Reproduce**

![image](https://user-images.githubusercontent.com/66168320/230753822-e7393cd5-63ba-4dfe-b158-07aaff7e2a39.png)
![image](https://user-images.githubusercontent.com/66168320/230753842-cbcbfa7f-93b1-4998-ad70-8ec49cbe152f.png)
![image](https://user-images.githubusercontent.com/66168320/230753857-3c3168c5-14a5-4286-8d38-af3141eb220d.png)
![image](https://user-images.githubusercontent.com/66168320/230753938-da30bf10-f4ce-46fe-95ad-d7155834f326.png)
![image](https://user-images.githubusercontent.com/66168320/230753947-b4a979ef-0ec9-4b31-a622-54f1018ee200.png)

The comparison yielded no results even though aj_test is not same.

**Comment by akshay-joshi** [comment]
@jcjgithub 

Can you please provide the DDL for the 'aj_test' table of both the databases?

**Comment by akshay-joshi** [comment]
@jcjgithub 

Please check the Filters option
<img width="261" alt="Screenshot 2023-04-10 at 12 13 19 PM" src="https://user-images.githubusercontent.com/1632882/230843267-cd387170-5062-496d-b8d1-f81e66fac23d.png">
