### ISSUE TITLE
Version 7.0 CSV export from Query Tool results does not include all columns

### ISSUE THREAD

**Issue by anthonydb** [pgadmin-org/pgadmin4#6122]
**Describe the bug**

I ran a query that is in the form of multiple CTEs, e.g.

```
WITH table_a AS (....),
     table_b AS (....)
SELECT * FROM table_a JOIN table_b ON a.id = b.id;
```

The query runs properly giving expected results. However, when I download the results to CSV by clicking the download icon, the resulting CSV only includes columns from the first CTE, `table_a`.

**To Reproduce**

Unfortunately, I cannot share the query as it is proprietary. But it is in the form noted above.

**Expected behavior**

In prior versions, all columns would export to CSV

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1
 - Mode: Desktop

**Comment by khushboovashi** [comment]
Hi @anthonydb,

Thanks for the testing 7.0 build. We have fixed the reported issues of the 7.0 release. We will share the latest candidate builds by tomorrow, so requesting you to please test it and confirm whether it is fixed or not.

**Comment by akshay-joshi** [comment]
@anthonydb 

Can you please test the issue on the Candidate build available at [Here](https://developer.pgadmin.org/builds/2023-04-11-2/)?

**Comment by FaharAbbasRizvi** [comment]
Closing this issue as per the confirmation of the user.
