### ISSUE TITLE
pgadmin4 package for Debian 12 (Bullseye) needs to be updated to use Python 3.11

### ISSUE THREAD

**Issue by passthejoe** [pgadmin-org/pgadmin4#6124]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

pgAdmin4 won't run on Debian 12 (Bookworm) because system Python is version 3.11 and not 3.9.

**To Reproduce**

Install pgAdmin4 on a Debian 12 system using pgAdmin.org instructions

Run pgAdmin4

**Expected behavior**

pgAdmin4 opens and allows access to the database.

**Error message**

Failed to launch pgAdmin4. Error:
Error: spawn /usr/pgadmin4/venv/bin/python3 ENOENT

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 12 (Bookworm)
 - Mode: Desktop
 - Package type: DEB

**Additional context**

pgAdmin4 runs fine in Debian 11 (Bullseye) because that system uses Python 3.9. The package for Debian 12 (Bookworm) needs to be modified to work with Python 3.11.

**Comment by adityatoshniwal** [comment]
Hi @passthejoe,
pgAdmin will support bookworm from v7.0 which is planned to be released this week. You can check the platform support herer - https://www.pgadmin.org/download/pgadmin-4-apt/
Duplicates #5936 
Thanks.

**Comment by passthejoe** [comment]
Thank you.

**Comment by passthejoe** [comment]
Is it possible to reopen this bug? Version 7 moved to my Debian 12 system today, and it still requires Python 3.9, but system Python is 3.11.  pgAdmin4 still won't run and gives the same error message:

```
Failed to launch pgAdmin4. Error:
Error: spawn /usr/pgadmin4/venv/bin/python3 ENOENT
```

**Comment by FaharAbbasRizvi** [comment]
root@debian:/usr/pgadmin4/venv/bin# python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by dpage** [comment]
The Debian 12 build quite clearly uses Python 3.11 (this is from the build server):

```
jenkins@pgabf-debian-12:~/workspace/pgadmin4-deb-build/label/debian-12/debian-build/server/usr/pgadmin4/venv/bin$ ./python --version
Python 3.11.2
```

Please share the contents of your repo config file, as it sounds like you've installed packages for a different version of Debian.

**Comment by passthejoe** [comment]
On Fri, Apr 14, 2023 at 1:25 AM Dave Page ***@***.***> wrote:

> The Debian 12 build quite clearly uses Python 3.11 (this is from the build
> server):
>
> ***@***.***:~/workspace/pgadmin4-deb-build/label/debian-12/debian-build/server/usr/pgadmin4/venv/bin$ ./python --version
> Python 3.11.2
>
> Please share the contents of your repo config file, as it sounds like
> you've installed packages for a different version of Debian.
>

Thanks for looking into this for me. Your reply gave me a clue. This system
started as a Debian 11 system with pgAdmin4 and was upgraded to Debian 12.

But the repository configuration file for pgAdmin4 remained the same, and
that's why I still had a build for Python 3.9, even with pgAdmin4 version 7.

To fix this, I deleted /etc/apt/sources.list.d/pgadmin4.list and re-created
the repository configuration file per the instructions at
https://www.pgadmin.org/download/pgadmin-4-apt/, and now pgAdmin4 works on
my Debian 12 system. I added a few steps to the recipe for Debian systems
that had pgAdmin4 on Debian 11 that have upgraded to Debian 12:

# Instructions to get pgAdmin4 working on a Debian system upgraded
from version 11 (Bullseye) to 12 (Bookworm)

# Remove the non-functioning pgAdmin4 package and clean up with autoremove

$ sudo apt remove pgadmin4

$ sudo apt autoremove

# Remove old sources.list file for pgAdmin4 that was previously
installed on Debian 11:

$ sudo rm /etc/apt/sources.list.d/pgadmin4.list

# Set up the pgAdmin 4 repository
#
# Install the public key for the repository (if not done previously --
you shouldn't have to do this if you already had pgAdmin4 installed on
Debian 11):
$ curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub |
sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg

# Create the repository configuration file:
$ sudo sh -c 'echo "deb
[signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg]
https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs)
pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'


# Install pgAdmin


# Install for both desktop and web modes:
$ sudo apt install pgadmin4

# Install for desktop mode only:
$ sudo apt install pgadmin4-desktop

# Install for web mode only:
$ sudo apt install pgadmin4-web

# Configure the webserver, if you installed pgadmin4-web:
$ sudo /usr/pgadmin4/bin/setup-web.sh

Thank you again for looking at this issue and helping me figure it out.

**Comment by claudep** [comment]
Same issue here, looks like `sudo apt install --reinstall pgadmin4-server` was enough to make it work again on my system.
