### ISSUE TITLE
Unable to load the properties of fts template and fts parser in system catalogs 

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6127]
Unable to load the properties of fts template and fts parser in system catalogs however the user can see properties of these objects on schema. This issue is also reproducible in older v21 releases.

**To Reproduce**

1. Go to catlogs 
2. Go to PostgreSQL catalogs 
3. Expand  fts template and fts parser
4. click on particular fts
5.  right click and select properties
6. empty dialog is displayed

**Expected behavior**

properties should be displayed for fts template and fts parser in system catalogs.

<img width="1782" alt="Screen Shot 2023-04-13 at 2 17 18 PM" src="https://user-images.githubusercontent.com/43006122/231716339-88d5d716-a98d-43f3-8554-695c3089914a.png">

**Desktop (please complete the following information):**
 - OS: [All]
 - Version: [6.21 and 7.0]
 - Mode: [All]
 - Package type: [All]

**Comment by adityatoshniwal** [comment]
It occurs for MView, View->Rules as well.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-19/
