### ISSUE TITLE
send email error: ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)

### ISSUE THREAD

**Issue by chendelin1982** [pgadmin-org/pgadmin4#6134]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

I use my own Mail Server, when I reset password my Email from forget password. the error below
```
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)
```
![image](https://user-images.githubusercontent.com/16741975/232019480-0631f97c-c44b-481c-bcd2-9c376c41a2c1.png)

**Comment by anilsahoo20** [comment]
@FaharAbbasRizvi can you please test this.

**Comment by FaharAbbasRizvi** [comment]
I am getting the following error message on the latest candidate build:
----
<img width="1307" alt="Screen Shot 2023-05-02 at 12 49 37 PM" src="https://user-images.githubusercontent.com/43006122/235609967-65ececed-ef48-4222-b272-79e14da04cb2.png">

**Comment by adityatoshniwal** [comment]
Hi @chendelin1982,

What is the TLS version your email server is using? From python 3.10, the older TLS versions are deprecated as a security improvement-https://bugs.python.org/issue43998. There is nothing pgAdmin can do here as the libs do not allow configuring this.

**Comment by khushboovashi** [comment]
No response from the author, closing the issue.
