### ISSUE TITLE
Editing a database object de-selects it on the tree.

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#6136]
**Describe the bug**
Editing a database objects de-selects it on the tree.

**To Reproduce**

1. Select a database and open the edit dialog.
2. Change the comment and save.
3. The selected database node is de-selected.

**Expected behavior**

The tree selection should be maintained.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 7.0
 - Mode: Desktop

**Comment by nikhil-mohite** [comment]
Resolved, Verified on candidate build: https://developer.pgadmin.org/builds/2023-05-30-1/
OS: macOS (Ventura 13.3)
Mode: Desktop
