### ISSUE TITLE
Crash pgAdmin4 7.0 after re-migration tables

### ISSUE THREAD

**Issue by DZ8540** [pgadmin-org/pgadmin4#6138]
**Describe the bug**
After dumping database and re-migration all tables, when you going to refresh view in table, app going to crash. 

**To Reproduce**

1. Choose someone table, click right mouse button and choose `view/edit data`, then choose `all rows`
2. Wipe or dump all tables (for example via command line), then create the same name table
3. Click on `Execute/Refresh (F5)` button in `PgAdmin4`
4. See crashing application

**Expected behavior**

Application don't going to crash.

**Error message**

Without any messages and dialogs.

**Desktop (please complete the following information):**
 - OS: OSX Ventura 13.0.1
 - Version: 7.0
 - Mode: Desktop
 - Package type: Application

**Comment by pravesh-sharma** [comment]
Issue fixed. verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-27/

Env - macOS Ventura 13.3.1 (Desktop mode)

**Comment by adityatoshniwal** [comment]
Fix with commit https://github.com/pgadmin-org/pgadmin4/commit/4746fbd34674574bec09113d0240618301fdcebf

**Comment by akshay-joshi** [comment]
Reopen for Testing

**Comment by anilsahoo20** [comment]
Issue fixed. verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-23/

Env - macOS Ventura 13.3 (Desktop mode)
