### ISSUE TITLE
The Release notes links on the https://www.pgadmin.org/download/pgadmin-4-source-code/ page are broken

### ISSUE THREAD

**Issue by rgl** [pgadmin-org/pgadmin4#6140]
**Describe the bug**

It seems the issue https://github.com/pgadmin-org/pgadmin4/issues/5607 has resurfaced because the release info links at https://www.pgadmin.org/download/pgadmin-4-source-code/ are broken.

For example, they point to https://github.com/pgadmin-org/pgadmin4/blob/REL-v7_0/README.md (which is 404) and I think it should point to https://www.pgadmin.org/docs/pgadmin4/latest/release_notes.html or https://www.pgadmin.org/docs/pgadmin4/latest/release_notes_7_0.html.

**Comment by dpage** [comment]
Fixed.
