### ISSUE TITLE
Properties tab not getting updated if we update selected node from tree

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#6158]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
The properties tab is not updated if the user updates node data

**To Reproduce**

1. Select the Properties tab 
2. Select any node from tree and open the edit node dialog
3. Change a few things and save 
4. Check updated properties are not getting updated on Properties Tab

**Expected behavior**

Updated changes should get reflected on the Properties tab

**Desktop (please complete the following information):**
 - OS: OSX 
 - Version: 7.0
 - Mode: Desktop and Server
 - Browser (if running in server mode): All
 - Package type: All

**Comment by yogeshmahajan-1903** [comment]
Working fine.
