### ISSUE TITLE
PGadmin crashing with Postgres sql

### ISSUE THREAD

**Issue by adnetmilind** [pgadmin-org/pgadmin4#6160]
We are getting the error when we are executing the insert, update & delete command in Pgadmin application. The application crashes on that time.
[pgadmin4.log](https://github.com/pgadmin-org/pgadmin4/files/11283538/pgadmin4.log)

**Comment by akshay-joshi** [comment]
@adnetmilind 

After analysing the log file it is not much clear, can you please provide the DDL of the table and insert, update & delete command. Which version of pgAdmin and PostgreSQL are you using?

**Comment by adityatoshniwal** [comment]
Closing as no response from the user.
