### ISSUE TITLE
Negative values in dashboard graphs?

### ISSUE THREAD

**Issue by metropolisStar** [pgadmin-org/pgadmin4#6169]
**Describe the bug**

What happened if the values in graphs on Dashboard was negative numbers? Is it a bug, or has it an explainable reason? Thanks.

**Screenshots**
![dash_negative](https://user-images.githubusercontent.com/124900856/233642550-29a06598-94e7-45c2-8ff9-2447b2a62c53.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 (22621.1555)
 - Version: 7.0
 - Mode: Desktop

**Comment by adityatoshniwal** [comment]
@metropolisStar Are you still seeing this issue with latest version?

**Comment by khushboovashi** [comment]
No response from the author, closing the issue.
