### ISSUE TITLE
Getting an error please help on 'sudo apt install pgadmin4'

### ISSUE THREAD

**Issue by sirbor** [pgadmin-org/pgadmin4#6170]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package pgadmin4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
 please help

**Comment by florian-sabonchi** [comment]
I think you are wrong pgadmin can not be installed from apt

**Comment by florian-sabonchi** [comment]
https://computingforgeeks.com/how-to-install-pgadmin-4-on-ubuntu/?utm_content=cmp-true
