### ISSUE TITLE
Can't pull Docker image for version 7.0, 7, latest and snapshot

### ISSUE THREAD

**Issue by juanlumnorange** [pgadmin-org/pgadmin4#6176]
**Describe the bug**

When we try to pull the docker image we get an error due to the manifest version.

**To Reproduce**

1. 'docker pull docker.io/dpage/pgadmin4:7.0'
3. See the error

**Expected behavior**

The docker image has been pulled.

**Error message**

```
7.0: Pulling from dpage/pgadmin4
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'
```

**Screenshots**

![image](https://user-images.githubusercontent.com/131442775/233922918-446bef31-84c0-4b1b-9ca7-e8b13235174a.png)

**Comment by akshay-joshi** [comment]
Hi @juanlumnorange 

I am not able to reproduce this issue. Tried on MAC OSX
<img width="658" alt="Screenshot 2023-04-24 at 12 57 54 PM" src="https://user-images.githubusercontent.com/1632882/233928227-01a65192-75b8-42bc-8ceb-4c8fe789faea.png">

**Comment by juanlumnorange** [comment]
Hi, 

We're running it in an alpine alpine 3.12 with docker 19.0313

**Comment by akshay-joshi** [comment]
@dpage 

Can you please look into this?

**Comment by Mauti404** [comment]
I have the same issue on my project, I tried pulling specific image version (pgadmin4:2021-12-15-2 for example) and I managed to pull the image. I think @dpage change the mediatype in the lastest versions.

**Comment by MartinHeisig** [comment]
run into similiar problem while trying to retrieve the pgadmin image from docker hub:

> docker pull dpage/pgadmin4:7.1
> 7.1: Pulling from dpage/pgadmin4
> manifest for dpage/pgadmin4:7.1 not found

same for dpage/pgadmin4:7 and dpage/pgadmin4:latest

**Comment by pravesh-sharma** [comment]
It seems that your docker version is too old. Please upgrade your docker to something recent and try again.
