### ISSUE TITLE
PSQL is not working if PGUSER env variable is set other than Postgres user and service file is used for server connection.

### ISSUE THREAD

**Issue by khushboovashi** [pgadmin-org/pgadmin4#6180]

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/

Env:
1. macOS ventura (13.3.1) Desktop mode
2. Ubuntu 2.04 Desktop mode
