### ISSUE TITLE
pgAdmin V 6.21 Duplicates Databases

### ISSUE THREAD

**Issue by Chae-Rie** [pgadmin-org/pgadmin4#6186]
Version: 6.21
Desktop Version
NW.js Version 0.72.0
Browser: Chromium 109.0.5414.87
OS: Windows-10-10.0.22621-SP0

##Usage: Connecting to a Postgres 14 Database on WSL2 machine which runs OpenSUSE Leap 15.4

After logging in on pgAdmin with masterpassword, everything went fine until I clicked on "Servers" to connect with my Server and so on with my database. I get prompted, as usual for my credentials but after that I registered something strange.
In the server list every database on that Server got duplicated. Maybe just an GUI Bug. I could cast queries on both of them seperately. 

Like so:
| Servers(1)
 +\ Servername X
   ++\ Databases (1)
     +++\ my_db
       ++++\ Casts, Catalogs, Schemas etc.
   ++\ Databases (1)
     +++\ my_db
       ++++\ Casts, Catalogs, Schemas etc.
 

But it should only be like:
| Servers(1)
 +\ Servername X
   ++\ Databases (1)
     +++\ my_db
       ++++\ Casts, Catalogs, Schemas etc.

After restarting pgAdmin it displayed all correctly again. 
There is no big severity on this one.

**Comment by akshay-joshi** [comment]
Related to #6043

**Comment by Chae-Rie** [comment]
Because I am using it everyday at work and kept updating as well so I got the most recent version installed: I've never got the same bugged behavior again, so it seem to be fixed. 
For the sake of completeness -> checked it explicitly again yesterday. 
I'm going to close this ticket with this comment, aight?
