### ISSUE TITLE
pgadmin4 version 7.0 server deployment with uwsgi error

### ISSUE THREAD

**Issue by enrymari** [pgadmin-org/pgadmin4#6192]
Can't server deploy pgadmin4 with uwsgi due to error in mounting app. Previus version works.

1. run the command: 'uwsgi --socket /var/lib/pgadmin/uwsgi/pgadmin4.sock --uid www-data --gid www-data --processes 1 --threads 25 --chdir /var/lib/postgresql/pgadmin4/lib/python3.10/site-packages/pgadmin4/ --master --pidfile /var/lib/pgadmin/uwsgi/uwsgi-master.pid --procname pgAdmin-on-uWSGI --plugins python310 --mount /pgadmin4=pgAdmin4:app'
2. See the output: 
compiled with version: 11.2.0 on 21 March 2022 11:00:44
os: Linux-5.15.0-70-generic #77-Ubuntu SMP Tue Mar 21 14:02:37 UTC 2023
nodename: z08alinux08
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/lib/postgresql
writing pidfile to /var/lib/pgadmin/uwsgi/uwsgi-master.pid
detected binary path: /usr/bin/uwsgi-core
setgid() to 33
setuid() to 33
chdir() to /var/lib/postgresql/pgadmin4/lib/python3.10/site-packages/pgadmin4/
your processes number limit is 15233
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/lib/pgadmin/uwsgi/pgadmin4.sock fd 3
Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Python main interpreter initialized at 0x559aa486b090
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 647728 bytes (632 KB) for 25 cores
*** Operational MODE: threaded ***
mounting pgAdmin4:app on /pgadmin4
Traceback (most recent call last):
  File "/var/lib/postgresql/pgadmin4/lib/python3.10/site-packages/pgadmin4/./pgAdmin4.py", line 102, in <module>
    app = create_app()
  File "/var/lib/postgresql/pgadmin4/lib/python3.10/site-packages/pgadmin4/pgadmin/__init__.py", line 335, in create_app
    babel.init_app(app, locale_selector=get_locale)
TypeError: Babel.init_app() got an unexpected keyword argument 'locale_selector'
unable to load app 0 (mountpoint='/pgadmin4') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 677090)
spawned uWSGI worker 1 (pid: 677092, cores: 25)

If run without uwsgi don't see any error.

**Comment by akshay-joshi** [comment]
@enrymari 

Can you please provide the output of the command `pip freeze`?

**Comment by enrymari** [comment]
Sorry! I'm new to Python, but i think the installation run without errors; even the setup is free to errors. Only when i run pgadmin4 with uwsgi can show that error.
In the meanwhile, i setup the previus version that works well, because i need manage postregresql database in my production server.
If you think i'd give more information, please give me istructions in what i'll must do. Thanks!

**Comment by khushboovashi** [comment]
Hi @enrymari,

Follow the below commands and provide the output of `pip freeze`.

$> source /var/lib/postgresql/pgadmin4/bin/activate
$> pip freeze

**Comment by enrymari** [comment]
Here is the output of the 'pip freeze' command:
alembic==1.10.4
Authlib==1.2.0
azure-common==1.1.28
azure-core==1.26.4
azure-identity==1.12.0
azure-mgmt-core==1.4.0
azure-mgmt-rdbms==10.1.0
azure-mgmt-resource==23.0.0
azure-mgmt-subscription==3.1.1
Babel==2.12.1
bcrypt==4.0.1
bidict==0.22.1
blinker==1.6.2
boto3==1.26.130
botocore==1.29.130
Brotli==1.0.9
cachetools==5.3.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cryptography==40.0.2
dnspython==2.3.0
email-validator==2.0.0.post2
eventlet==0.33.3
Flask==2.2.5
flask-babel==3.1.0
Flask-Compress==1.13
Flask-Gravatar==0.5.0
Flask-Login==0.6.2
Flask-Mail==0.9.1
Flask-Migrate==4.0.4
Flask-Paranoid==0.3.0
Flask-Principal==0.4.0
Flask-Security-Too==5.1.2
Flask-SocketIO==5.3.4
Flask-SQLAlchemy==3.0.3
Flask-WTF==1.1.1
google-api-core==2.11.0
google-api-python-client==2.86.0
google-auth==2.17.3
google-auth-httplib2==0.1.0
google-auth-oauthlib==1.0.0
googleapis-common-protos==1.59.0
greenlet==1.1.2
httpagentparser==1.9.5
httplib2==0.22.0
idna==3.4
isodate==0.6.1
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
ldap3==2.9.1
Mako==1.2.4
MarkupSafe==2.1.2
msal==1.22.0
msal-extensions==1.0.0
msrest==0.7.1
oauthlib==3.2.2
paramiko==3.1.0
passlib==1.7.4
pgadmin4==7.1
Pillow==9.5.0
portalocker==2.7.0
protobuf==4.23.0
psutil==5.9.5
psycopg==3.1.8
psycopg-binary==3.1.8
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
PyJWT==2.6.0
PyNaCl==1.5.0
pyotp==2.8.0
pyparsing==3.0.9
pypng==0.20220715.0
python-dateutil==2.8.2
python-engineio==4.4.1
python-socketio==5.8.0
pytz==2023.3
qrcode==7.4.2
requests==2.28.2
requests-oauthlib==1.3.1
rsa==4.9
s3transfer==0.6.1
six==1.16.0
speaklater3==1.4
SQLAlchemy==2.0.12
sqlparse==0.4.4
sshtunnel==0.4.0
typing_extensions==4.5.0
ua-parser==0.16.1
uritemplate==4.1.1
urllib3==1.26.15
user-agents==2.2.0
Werkzeug==2.2.3
WTForms==3.0.1

**Comment by enrymari** [comment]
Here is the output of the 'pip freeze' command:
alembic==1.10.4
Authlib==1.2.0
azure-common==1.1.28
azure-core==1.26.4
azure-identity==1.12.0
azure-mgmt-core==1.4.0
azure-mgmt-rdbms==10.1.0
azure-mgmt-resource==23.0.0
azure-mgmt-subscription==3.1.1
Babel==2.12.1
bcrypt==4.0.1
bidict==0.22.1
blinker==1.6.2
boto3==1.26.130
botocore==1.29.130
Brotli==1.0.9
cachetools==5.3.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cryptography==40.0.2
dnspython==2.3.0
email-validator==2.0.0.post2
eventlet==0.33.3
Flask==2.2.5
flask-babel==3.1.0
Flask-Compress==1.13
Flask-Gravatar==0.5.0
Flask-Login==0.6.2
Flask-Mail==0.9.1
Flask-Migrate==4.0.4
Flask-Paranoid==0.3.0
Flask-Principal==0.4.0
Flask-Security-Too==5.1.2
Flask-SocketIO==5.3.4
Flask-SQLAlchemy==3.0.3
Flask-WTF==1.1.1
google-api-core==2.11.0
google-api-python-client==2.86.0
google-auth==2.17.3
google-auth-httplib2==0.1.0
google-auth-oauthlib==1.0.0
googleapis-common-protos==1.59.0
greenlet==1.1.2
httpagentparser==1.9.5
httplib2==0.22.0
idna==3.4
isodate==0.6.1
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
ldap3==2.9.1
Mako==1.2.4
MarkupSafe==2.1.2
msal==1.22.0
msal-extensions==1.0.0
msrest==0.7.1
oauthlib==3.2.2
paramiko==3.1.0
passlib==1.7.4
pgadmin4==7.1
Pillow==9.5.0
portalocker==2.7.0
protobuf==4.23.0
psutil==5.9.5
psycopg==3.1.8
psycopg-binary==3.1.8
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
PyJWT==2.6.0
PyNaCl==1.5.0
pyotp==2.8.0
pyparsing==3.0.9
pypng==0.20220715.0
python-dateutil==2.8.2
python-engineio==4.4.1
python-socketio==5.8.0
pytz==2023.3
qrcode==7.4.2
requests==2.28.2
requests-oauthlib==1.3.1
rsa==4.9
s3transfer==0.6.1
six==1.16.0
speaklater3==1.4
SQLAlchemy==2.0.12
sqlparse==0.4.4
sshtunnel==0.4.0
typing_extensions==4.5.0
ua-parser==0.16.1
uritemplate==4.1.1
urllib3==1.26.15
user-agents==2.2.0
Werkzeug==2.2.3
WTForms==3.0.1

**Comment by enrymari** [comment]
Here is the output of the 'pip freeze' command:
alembic==1.10.4
Authlib==1.2.0
azure-common==1.1.28
azure-core==1.26.4
azure-identity==1.12.0
azure-mgmt-core==1.4.0
azure-mgmt-rdbms==10.1.0
azure-mgmt-resource==23.0.0
azure-mgmt-subscription==3.1.1
Babel==2.12.1
bcrypt==4.0.1
bidict==0.22.1
blinker==1.6.2
boto3==1.26.130
botocore==1.29.130
Brotli==1.0.9
cachetools==5.3.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cryptography==40.0.2
dnspython==2.3.0
email-validator==2.0.0.post2
eventlet==0.33.3
Flask==2.2.5
flask-babel==3.1.0
Flask-Compress==1.13
Flask-Gravatar==0.5.0
Flask-Login==0.6.2
Flask-Mail==0.9.1
Flask-Migrate==4.0.4
Flask-Paranoid==0.3.0
Flask-Principal==0.4.0
Flask-Security-Too==5.1.2
Flask-SocketIO==5.3.4
Flask-SQLAlchemy==3.0.3
Flask-WTF==1.1.1
google-api-core==2.11.0
google-api-python-client==2.86.0
google-auth==2.17.3
google-auth-httplib2==0.1.0
google-auth-oauthlib==1.0.0
googleapis-common-protos==1.59.0
greenlet==1.1.2
httpagentparser==1.9.5
httplib2==0.22.0
idna==3.4
isodate==0.6.1
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
ldap3==2.9.1
Mako==1.2.4
MarkupSafe==2.1.2
msal==1.22.0
msal-extensions==1.0.0
msrest==0.7.1
oauthlib==3.2.2
paramiko==3.1.0
passlib==1.7.4
pgadmin4==7.1
Pillow==9.5.0
portalocker==2.7.0
protobuf==4.23.0
psutil==5.9.5
psycopg==3.1.8
psycopg-binary==3.1.8
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
PyJWT==2.6.0
PyNaCl==1.5.0
pyotp==2.8.0
pyparsing==3.0.9
pypng==0.20220715.0
python-dateutil==2.8.2
python-engineio==4.4.1
python-socketio==5.8.0
pytz==2023.3
qrcode==7.4.2
requests==2.28.2
requests-oauthlib==1.3.1
rsa==4.9
s3transfer==0.6.1
six==1.16.0
speaklater3==1.4
SQLAlchemy==2.0.12
sqlparse==0.4.4
sshtunnel==0.4.0
typing_extensions==4.5.0
ua-parser==0.16.1
uritemplate==4.1.1
urllib3==1.26.15
user-agents==2.2.0
Werkzeug==2.2.3
WTForms==3.0.1

**Comment by akshay-joshi** [comment]
@enrymari 

How did you install pgAdmin 4?

**Comment by enrymari** [comment]
> @enrymari
> 
> How did you install pgAdmin 4?

This are my steps:

- source pgadmin4/bin/activate
- pip install pgadmin4
- python3 setup.py

after, i test with:  python3 pgAdmin4.py
and everything was fine.

The troubles begin with uwsgi...

**Comment by yogeshmahajan-1903** [comment]
@enrymari 
Can you please try running below command with root user ?
```
uwsgi --socket /var/lib/pgadmin/uwsgi/pgadmin4.sock --processes 1 --threads 25 --chdir /var/lib/postgresql/pgadmin4/lib/python3.10/site-packages/pgadmin4/  --mount /pgadmin4=pgAdmin4:app
```

**Comment by enrymari** [comment]
Hi, i run the command:
uwsgi --socket /var/lib/pgadmin4/uwsgi/pgadmin4.sock --processes 1 --threads 25  --chdir /var/lib/postgresql/pgadmin/lib/python3.10/site-packages/pgadmin4/ --mount /pgadmin4=pgAdmin4:app

with this output:
*** Starting uWSGI 2.0.20-debian (64bit) on [Fri Jun  9 09:48:03 2023] ***
compiled with version: 11.2.0 on 21 March 2022 11:00:44
os: Linux-5.15.0-74-generic #81-Ubuntu SMP Fri May 12 15:05:17 UTC 2023
nodename: z08alinux08
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/lib/postgresql
detected binary path: /usr/bin/uwsgi-core
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
chdir() to /var/lib/postgresql/pgadmin/lib/python3.10/site-packages/pgadmin4/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/lib/pgadmin4/uwsgi/pgadmin4.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 323864 bytes (316 KB) for 25 cores
*** Operational MODE: threaded ***
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** uWSGI is running in multiple interpreter mode ***
!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!
no request plugin is loaded, you will not be able to manage requests.
you may need to install the package for your language of choice, or simply load it with --plugin.
!!!!!!!!!!! END OF WARNING !!!!!!!!!!
spawned uWSGI worker 1 (and the only) (pid: 670846, cores: 25)

so, i added --plugin python3, and this is the output:
*** Starting uWSGI 2.0.20-debian (64bit) on [Fri Jun  9 09:48:49 2023] ***
compiled with version: 11.2.0 on 21 March 2022 11:00:44
os: Linux-5.15.0-74-generic #81-Ubuntu SMP Fri May 12 15:05:17 UTC 2023
nodename: z08alinux08
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/lib/postgresql
detected binary path: /usr/bin/uwsgi-core
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
chdir() to /var/lib/postgresql/pgadmin/lib/python3.10/site-packages/pgadmin4/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/lib/pgadmin4/uwsgi/pgadmin4.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Python main interpreter initialized at 0x563766d5b7e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 323864 bytes (316 KB) for 25 cores
*** Operational MODE: threaded ***
mounting pgAdmin4:app on /pgadmin4
Traceback (most recent call last):
  File "/var/lib/postgresql/pgadmin/lib/python3.10/site-packages/pgadmin4/./pgAdmin4.py", line 102, in <module>
    app = create_app()
  File "/var/lib/postgresql/pgadmin/lib/python3.10/site-packages/pgadmin4/pgadmin/__init__.py", line 335, in create_app
    babel.init_app(app, locale_selector=get_locale)
TypeError: Babel.init_app() got an unexpected keyword argument 'locale_selector'
unable to load app 0 (mountpoint='/pgadmin4') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 670878, cores: 25)

**Comment by adityatoshniwal** [comment]
Closed as per user confirmation.
