### ISSUE TITLE
Query Tool Title Does Not Change After "Save as", Until A New Change is Made

### ISSUE THREAD

**Issue by isosphere** [pgadmin-org/pgadmin4#6193]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

The title of the open Query Tool updates when a change is made after using the "Save As" feature. There is no feedback to the user about this update of the title until a change is made. This is confusing if you make a change after a long period, or if you have a complicated workflow that pgAdmin is one piece of, resulting in shifts of focus. 

**To Reproduce**

1. Open an existing SQL file in a Query Tool
2. Save As under a different file name
3. Notice that the active Query Tool title[^1] has not changed
4. Wait an arbitrary amount of time
5. Make any change to the SQL in the active Query Tool

**Expected behavior**

The Query Tool title[^1] should immediately change after the Save As operation successfully completed. 

[^1]: In this image I have highlighted in yellow what I am referring to as "Query Tool title"
![image](https://user-images.githubusercontent.com/163370/234697736-7c5bbc29-0651-42e5-9760-50cf8bd5cc7c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 7.0
 - Mode: Desktop
 - Package type: pgAdmin.org download - x64 Windows binary

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on today's snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-25/)

Env -
OS - macOS Sonoma (14.1.2)
Mode - Desktop
