### ISSUE TITLE
Error when trying to open the query tool

### ISSUE THREAD

**Issue by marcusricardoaguiar** [pgadmin-org/pgadmin4#6205]
I am having the following issue when trying to open the query tool with version above 7.0:

![test](https://user-images.githubusercontent.com/8216333/235215264-9df6a868-37d8-4b09-9c63-2cb931c6045a.png)

I'm using a debian instance, version 11.

**Comment by marcusricardoaguiar** [comment]
When checking the developers tool, I can see these issues:
![image](https://user-images.githubusercontent.com/8216333/234878342-a78e1dc1-7417-44d8-ac91-c1f01bd1a2db.png)

**Comment by adityatoshniwal** [comment]
Hi @marcusricardoaguiar,
The pgAdmin default config for `X_FRAME_OPTIONS` is `"SAMEORIGIN"`. Did you change this config param?

**Comment by marcusricardoaguiar** [comment]
Hi @adityatoshniwal , Yes! I've already tried both other options for this parameter. I've tried `X_FRAME_OPTIONS = "ALLOW-FROM origin"` and `X_FRAME_OPTIONS = ""`. Is there anything else I should change in pgadmin4 parameters? This is my current configuration:

```
SERVER_MODE=True
MASTER_PASSWORD_REQUIRED=False
ALLOW_SAVE_PASSWORD=True
AUTO_DISCOVER_SERVERS=False
X_FRAME_OPTIONS = "ALLOW-FROM origin"
AUTHENTICATION_SOURCES = ['oauth2', 'internal']
OAUTH2_CONFIG = [
    {
        'OAUTH2_NAME': 'Google',
        'OAUTH2_DISPLAY_NAME': 'Google',
        'OAUTH2_CLIENT_ID': '<google_iap_client_id>',
        'OAUTH2_CLIENT_SECRET': '<google_iap_client_secret>',
        'OAUTH2_TOKEN_URL': 'https://oauth2.googleapis.com/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/v2/auth/identifier',
        'OAUTH2_SERVER_METADATA_URL': 'https://accounts.google.com/.well-known/openid-configuration',
        'OAUTH2_API_BASE_URL': 'https://openidconnect.googleapis.com/v1/',
        'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
        'OAUTH2_SCOPE': 'openid email profile',
        'OAUTH2_ICON': 'fa-google',
        'OAUTH2_BUTTON_COLOR': '#FF0000'
    }
]
OAUTH2_AUTO_CREATE_USER = True
```

**Comment by marcusricardoaguiar** [comment]
This is the test result with the parameter:
![test](https://user-images.githubusercontent.com/8216333/235224802-b9209307-735d-4fb7-82ce-7c051bf4a057.png)

**Comment by marcusricardoaguiar** [comment]
Oh, NVM. I've just found out what's going on. My config file `/etc/apache2/conf-available/ssl-params.conf` had a `DENY` value defined for this parameter. :smile:

**Comment by adityatoshniwal** [comment]
Hi @marcusricardoaguiar I am closing this as this is not a pgAdmin issue.
