### ISSUE TITLE
Error deleting rows

### ISSUE THREAD

**Issue by stefansundin** [pgadmin-org/pgadmin4#6206]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

I am unable to delete rows. Server is PostgreSQL 15.2. The table is using uuids as the primary key.

**To Reproduce**

1. Connect to server.
2. Find a database table and view the data.
3. Select a row and mark it for deletion.
4. Click "Save Data Changes"
5. See red error in bottom right corner: `trailing junk after numeric literal at or near "4d" at character 61`
6. See the full error in the postgresql log output:
   ```
   ERROR:  trailing junk after numeric literal at or near "4d" at character 61
   STATEMENT:  DELETE FROM public."user"
      WHERE id IN
      (d799a908-4df0-4ce9-ba51-01e25c2077c0);
   ```

**Expected behavior**

The rows should be deleted without error.

**Error message**

```
ERROR:  trailing junk after numeric literal at or near "4d" at character 61
STATEMENT:  DELETE FROM public."user"
   WHERE id IN
      (d799a908-4df0-4ce9-ba51-01e25c2077c0);
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Version: 7.0
 - Mode: Desktop

**Additional context**

Looks like the `DELETE` statement just needs to quote the uuids. I am still able to `UPDATE` rows just fine.

**Comment by adityatoshniwal** [comment]
Duplicates #6130
