### ISSUE TITLE
v6.21: /browser page shows "loading" forever.

### ISSUE THREAD

**Issue by kidpooh1608** [pgadmin-org/pgadmin4#6209]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
/browser page shows "loading" forever.
It's loading some js scripts and receive responses with 429 code
These scripts can be loaded after a few refresh.

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/17811646/235055662-14b3c5ec-1c75-4fc2-930e-b92935ec9bc0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: 6.21
 - Mode: Server
 - Browser (if running in server mode): Chrome, Firefox, Safari
 - Package type: Container

**Additional context**

**Comment by akshay-joshi** [comment]
@kidpooh1608 

Can you please share the docker/container logs?

**Comment by kidpooh1608** [comment]
@akshay-joshi This is how the issue is reproduced:
- deploy pgadmin behind a nginx with rate limit setting:
nginx.conf
```
user       phuong;  ## Default: nobody
worker_processes  5;  ## Default: 1
error_log  logs/error.log;
pid        logs/nginx.pid;
worker_rlimit_nofile 8192;

events {
  worker_connections  4096;  ## Default: 1024
}

http {
  index    index.html index.htm index.php;

  default_type application/octet-stream;
  log_format   main '$remote_addr - $remote_user [$time_local]  $status '
    '"$request" $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log   logs/access.log  main;
  sendfile     on;
  tcp_nopush   on;
  server_names_hash_bucket_size 128; # this seems to be required for some vhosts

  limit_req_zone $binary_remote_addr zone=mylimit:512m rate=10000000r/s;

  server { # simple load balancing
    listen          80;
    server_name     neko.com;
    access_log      logs/neko.com.access.log main;

    location / {
        limit_req zone=mylimit;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass      http://127.0.0.1:8080;
    }
  }
}
```
![image](https://user-images.githubusercontent.com/17811646/235295885-b9687839-cf29-4b75-b14f-f98a25cc889c.png)
[pgadmin.log](https://github.com/pgadmin-org/pgadmin4/files/11358820/pgadmin.log)
pgadmin back to normal if rate limit setting is removed.

**Comment by kidpooh1608** [comment]
@akshay-joshi it seems there are multiple requests "/js/...js" at the same time. that's why 2nd request can't be passed even the rate limit is very small. Is it possible to enhance it or is there any workaround?

**Comment by khushboovashi** [comment]
@kidpooh1608, set worker_processes  to 1 and try once.

**Comment by kidpooh1608** [comment]
> @kidpooh1608, set worker_processes to 1 and try once.

I tried and there was nothing different. @khushboovashi :(

**Comment by adityatoshniwal** [comment]
Hi @kidpooh1608,
You probably need to set the `burst` param of nginx as well along with rate limit. Please check  - https://www.nginx.com/blog/rate-limiting-nginx/#bursts for more info. Please let us know if it works.

Thanks.

**Comment by kidpooh1608** [comment]
@adityatoshniwal yes, it works with burst=6 which has delays between requests on nginx side,
but the problem is pgadmin is being deployed behind a load balancer which doesn't support similar burst setting in my system. It's a big thanks if there are settings inside pgadmin which allow delays between js requests (or other kind of requests).
Thank you,
