### ISSUE TITLE
Increment "autoIncrement" column when copy and paste a new row via UI

### ISSUE THREAD

**Issue by DZ8540** [pgadmin-org/pgadmin4#6220]
**Describe the solution you'd like**

Increment "autoIncrement" column when copy and paste a new row via UI

![image](https://user-images.githubusercontent.com/50152205/235203844-aeb89361-efcb-4f64-8a17-c9e9b73f8988.png)

**Comment by adityatoshniwal** [comment]
Hi @DZ8540,

We've fixed a similar issue here https://github.com/pgadmin-org/pgadmin4/issues/5922 where pgAdmin will keep the autoincrement column blank and use default value of the column on copy-paste. pgAdmin cannot show the new increment  value as it is generated by PG after inserting.
Does this work for you? The fix will be available in v7.1 planned this week.

Thanks.

**Comment by DZ8540** [comment]
Yo @adityatoshniwal 

Yes this is solved my issue, thanks, then i'm going to close this issue :)
