### ISSUE TITLE
Allow shared server to share username

### ISSUE THREAD

**Issue by ViliusS** [pgadmin-org/pgadmin4#6229]
**Describe the solution you'd like**

Currently shared servers do not allow to share username. I'm not familiar with why it was designed this way but I think it is a miss. In multi-user environments where pgAdmin container is prebuilt with shared server list, pgpass file and OAuth authentication it is impossible for the users to have clean login experience. Everything works except for username which needs to be provided by every users for every JSON imported Postgres server.

**Describe alternatives you've considered**

There is no alternative AFAIK.

**Comment by yogeshmahajan-1903** [comment]
@dpage 
What do you suggest?

**Comment by boronine** [comment]
I went through many iterations of trying to automatically provision servers + passwords for OAuth2 users in my pgAdmin instance and finally found a working hack.

This is a Dockerfile snippet that assumes `pgadmin_passfile` is provided as a Docker compose secret:

```dockerfile
FROM dpage/pgadmin4:7.1
# ...
COPY servers.json /servers.json
USER root
RUN echo "            os.system(f'cp /run/secrets/pgadmin_passfile {storage_dir}/pgpassfile; chmod 600 {storage_dir}/pgpassfile; /venv/bin/python3 setup.py --load-servers /servers.json --user {usr.username};');" >> /pgadmin4/pgadmin/utils/paths.py
USER pgadmin
```

This hack is taking advantage of the fact that the `create_users_storage_directory` is called after a new OAuth2 user logs in: https://github.com/pgadmin-org/pgadmin4/blob/REL-7_1/web/pgadmin/utils/paths.py

**Comment by ViliusS** [comment]
Nice hack.

It has one problem though. The imported servers are not really shared, they are copies for each user. In most cases that's probably fine, but when you want to manage server definition from one central place that could be problem.

**Comment by boronine** [comment]
@ViliusS you are right. Actually my approach is to treat our pgAdmin container as stateless and reprovision when servers or anything else changes. Toward this end I have another hack to get rid of the `VOLUME` directive that pgAdmin container wants to set up for you:

```dockerfile
FROM dpage/pgadmin4:7.1 AS base

FROM scratch AS novolume
COPY --from=base / /
WORKDIR /pgadmin4
USER pgadmin
EXPOSE 443/tcp 80/tcp
ENTRYPOINT ["/entrypoint.sh"]

FROM novolume AS prod
# ...
```

Of course this means user preferences get nuked, so this is not for everyone.

**Comment by ViliusS** [comment]
> Of course this means user preferences get nuked, so this is not for everyone.

Yep, exactly for that reason I'm using a persistent store.

Anyway, it's good to know I'm not the only one struggling to implement pgAdmin in a "modern" workflow. The more popular this issue gets, bigger chances are something will change.

**Comment by dpage** [comment]
> @dpage
> What do you suggest?

It's not a great security practice to share usernames, but as people are clearly doing it, and adding support for pre-populating the username doesn't really add any security holes that I can see, I think we can do this.

**Comment by EvertonSA** [comment]
as per my understanding implementing https://github.com/pgadmin-org/pgadmin4/pull/6298 the only change needed is in this line https://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/browser/server_groups/servers/__init__.py#L379

something like:

```
username=data.username
```

this solved my problem of passing the username on shared server definitions.

**Comment by n0-ware** [comment]
I +1 this one. We are combating bad password sharing practices by creating a "passwordless" pgadmin. We've pre-shared the entire list of some 350+ databases to all our users and use a `pgpassfile` two `../../` above the `storage` directory to keep it safe. 

The only remaining problem is that users don't have any usernames when they first log in and retrieve the shared servers. I've combated this by writing a cron job to re-populate usernames to all the shared servers as a probably terrible but effective way around this. 

I tried adjusting the `username=data.username` value, and while successful, it does not seem to work in our deployment. Possible my knowledge of python or containers is to blame. If a reader of this issue wants it, here is the SQL and the cron. 

Some SQL update file like `update_sharedserver.sql`

```sql
-- Update the "sharedserver" table with the appropriate username that matches "server"
UPDATE sharedserver
SET username = (
    SELECT server.username
    FROM server
    WHERE server.name = sharedserver.name
)
WHERE EXISTS (
    SELECT 1
    FROM server
    WHERE server.name = sharedserver.name
);
```

Add a file like `run_sqlite_update.sh`

```bash
#!/bin/bash
sqlite3 /path/to/mapped/var/lib/pgadmin/pgadmin4.db < /path/to/update_sharedserver.sql
```

Chmod it

`chmod +x /home/pgadmin/scripts/run_sqlite_update.sh`

Add the cron with `crontab -e` as `root`

```bash
*/5 * * * * /path/to/run_sqlite_update.sh
```

**Comment by nikhil-mohite** [comment]
Found the Following issues in testing:

- Issue 1: 
    - Create a new shared server with a `Shared Username` parameter
    - Login with another user and check shared server is showing try to connect it, it asks for a username.
    - It should not ask for a username as we have already provided while sharing the server
    - This issue is only reproducible with the newly added server (Don’t refresh after the server is created), If we shared alredy created servers issue is not reproducible
    

- Issue 2:

    - The `Shared Username` field is not visible in the `Properties panel` if the user creates a new shared server with the `Shared Username` field.
    - It is not sharing the `Shared username`, after refreshing the server group it shows the `Shared username` field empty on `Properties Panel`.

**Comment by nikhil-mohite** [comment]
Resolved, Verified on latest snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-10-16/
OS: macOS (Ventura 13.3)
Package: pip whl.
