### ISSUE TITLE
usernames / roles not double quoted when assigning privileges 

### ISSUE THREAD

**Issue by ercdvs** [pgadmin-org/pgadmin4#6234]
**Describe the bug**

When a table is owned by someone with a username of user.name, the resulting SQL statement when assigning privileges does not double quote the user properly, causing an error 

**To Reproduce**
![image](https://user-images.githubusercontent.com/6096665/235709772-e5bd547e-b48e-41a9-a4a6-e854aa46238b.png)

![image](https://user-images.githubusercontent.com/6096665/235710098-9d0b5731-fb95-495c-bb77-006fd2e10640.png)

**Error message**
![image](https://user-images.githubusercontent.com/6096665/235710258-b5181473-14de-4f6b-826b-ad62749b6eaf.png)

**Expected behavior**
Expected behavior is to have double quotes around the role name 

![image](https://user-images.githubusercontent.com/6096665/235710389-24419129-bcc4-449d-b477-cd73ebbf8e72.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 7.0
 - Mode: Desktop

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on candidate build https://developer.pgadmin.org/builds/2023-05-03-1/ 

Env - Ubuntu 22.04 (Desktop mode)
