### ISSUE TITLE
Support keychain on Mac OS to save (master) password(s)

### ISSUE THREAD

**Issue by scspijker** [pgadmin-org/pgadmin4#6238]
**Describe the solution you'd like**

PgAdmin4 currently requires a master password on Mac OS. Disabling this feature is cumbersome.
PgAdmin4 on Mac OS should support the keychain and/or disable the master password feature by default.

**Describe alternatives you've considered**

- Turning off master passwords on every new install, too cumbersome
- Using a master password (and saving it in the keychain myself), too cumbersome

**Additional context**

Implementing your own encryption / password saving scheme feels like a severely outdated methodology.
This has made me drop PgAdmin as my main Postgres client after many years.

**Comment by dpage** [comment]
Work on this is already nearing completion, and is being tracked under #5123.
