### ISSUE TITLE
Locale bug

### ISSUE THREAD

**Issue by MonoChromeBlaster** [pgadmin-org/pgadmin4#6239]
Hello,

I did create a database with encoding LATIN1:

CREATE DATABASE template_latin1
WITH OWNER = postgres
      TEMPLATE = template0
      ENCODING = 'LATIN1'
      LC_COLLATE = 'de_DE'
      LC_CTYPE = 'de_DE';

However, in pgAdmin 4 7.0 under 'Properties' the fields for 'Collation'
and 'Character type' are empty.
When I want to create a new database with LATIN1 as encoding locale
de_DE is not available.

In the past you could create a LATIN1 database with Locale de_DE with
pgAdmin if there is at least one of those in the cluster already.

Could you fix this, please?

Thank you very much!

Best regards,

Peter

**Comment by yogeshmahajan-1903** [comment]
@MonoChromeBlaster 
Could you please run below query and check available LC_CTYPE & LC_COLLATE?
```
SELECT pg_catalog.current_setting('lc_ctype') as cname
UNION
SELECT pg_catalog.current_setting('lc_collate') as cname
```

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
