### ISSUE TITLE
PSQL Tool pretty useless without command line options / customization possibilities

### ISSUE THREAD

**Issue by MonoChromeBlaster** [pgadmin-org/pgadmin4#6241]
**Describe the solution you'd like**

If I open psql via pgAdmin it just opens a psql shell / command line.

So there's no way to change the code page (on Windows) or choose any available options when calling psql, change the prompt etc.

So it would be nice if you could add commands to execute before executing psql etc.

**Describe alternatives you've considered**

I just check the psql version and start it from command line directly as I hardly open psql via pgAdmin 4.

**Comment by yogeshmahajan-1903** [comment]
@MonoChromeBlaster 
Could you please try setting psqlrc.conf on system?  psqlrc.conf will be used by psql.

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
