### ISSUE TITLE
No password prompt but "428 Precondition Required" if server has no password saved yet in 7.0

### ISSUE THREAD

**Issue by Matthias-Wagner** [pgadmin-org/pgadmin4#6242]
**Describe the bug**

When connecting to a server that has been loaded either through servers.json or created manually, the prompt to enter the user password is not shown anymore in 7.0 but instead a generic "Precondition Required" message is being shown (on Firefox) or an empty box without any text (on Chrome).

**To Reproduce**

1. Ensure there is a server without stored password, e.g. by disconnecting and clicking Clear Password.
2. Connect to the server

**Expected behavior**

A prompt that allows to enter a password and whether to save it should be shown, like in 6.21 and before.

**Error message**

"Precondition Required".
The actual request https://someserver/db/browser/server/connect/1/2 that returns 428 has the following data (username replaced):
{"success":0,"errormsg":"","info":"","result":{"server_label":"main_manual","username":"THEUSERNAME","errmsg":null,"service":null,"prompt_password":true,"allow_save_password":true},"data":null}

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 7.0
 - Mode: Server
 - Browser (if running in server mode): Firefox 112.0.2, Chrome 112.0.5615.138, Chrome 113.0.5672.64
 - Package type: Docker Container in AWS ECS

**Additional context**

PGAdmin is behind an NGINX reverse proxy which is behind AWS ALB. NGINX location:
location ~ ^/db/ {
        add_header       Referrer-Policy "origin,strict-origin" always;
        proxy_set_header X-Script-Name /db;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header Host $host;
        proxy_cookie_path / "/db/; Secure;";
        proxy_pass http://PGADMIN_HOST:PGADMIN_PORT;
        proxy_redirect off;
    }

Reverting to 6.21 solved the issue with otherwise no changes.

**Comment by yogeshmahajan-1903** [comment]
@Matthias-Wagner 
Issue is not reproducible at our end. Could you clearing cache?

**Comment by Matthias-Wagner** [comment]
I revisited the issue. It seems to be caused by the NGINX charset and charset_types settings:

charset UTF-8;
charset_types text/html text/xml text/plain text/vnd.wap.wml application/javascript application/rss+xml application/json;

Removing application/json for the /db/ location fixed the issue. Seems the code handling the response is not anymore able to handle the content type "application/json; charset=UTF-8".

**Comment by adityatoshniwal** [comment]
Axios is updated to latest version.
