### ISSUE TITLE
Cannot view properties for some object types in Catalog schema

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#6244]
**Describe the bug**

The properties tab is blank for FTS Parser, FTS Template, MView, View->Rules nodes of catalog schema.

**To Reproduce**

1. Open Catalogs -> PostgreSQL Schema
2. Select the collections and child of the nodes mentioned.
3. See the error in console.

**Expected behavior**

properties should be visible.

**Comment by FaharAbbasRizvi** [comment]
The issue is already reported:
https://github.com/pgadmin-org/pgadmin4/issues/6127

**Comment by adityatoshniwal** [comment]
OK. Duplicates #6127.
