### ISSUE TITLE
PgAdmin4 7.1 Prevent installation by Norton Security

### ISSUE THREAD

**Issue by skulluglify** [pgadmin-org/pgadmin4#6246]
PgAdmin4 7.1 from https://www.pgadmin.org/download/

that no have description about developer on inside installer, that prevent installation by Norton Security, 
previous version work like PgAdmin4 7.0, 

[screenshot](https://drive.google.com/file/d/1QV_japQBNeQEFC_zxgv0mL_BY3S6rUJp/view?usp=share_link)

**Comment by yogeshmahajan-1903** [comment]
@skulluglify 
As per screenshot shared , Norton is blocking an action by pgadmin. It does not say anything about develop description.
We checked at our end & pgadmin installers are signed & safe.

**Comment by skulluglify** [comment]
thanks for the answer, sorry to bother your time.
