### ISSUE TITLE
Query incorrectly shows no data when I type query manually

### ISSUE THREAD

**Issue by mattStayner** [pgadmin-org/pgadmin4#6250]
When I first start PGAdmin and manually type a query, no results are returned. However, if I right-click on the table and use "filter" with the exact same query, then results are returned. [See here](https://utilisync.clarityflow.com/c/917bcc1f8df7b3346c318bb06). Once I run the second query, then I'm able to open a new table and manually type the query and it works, but the original tab still doesn't work, even when the query is exactly the same. I started having issues with this when I upgraded to version 7.0

**Comment by adityatoshniwal** [comment]
This issue is same as #6163. I will close this as duplicate.
