### ISSUE TITLE
Incompatible type when opening Query Tool in server mode

### ISSUE THREAD

**Issue by countessellis** [pgadmin-org/pgadmin4#6252]
**Describe the bug**

When opening the Query tool from the console, I get the following error:

(psycopg.errors.UndefinedFunction) operator does not exist: integer = character varying\nLINE 3: ..._id = $2::INTEGER AND sharedserver.servergroup_id = $3::VARC...\n 

Looking at the rest of the message, in the parameters to the sharedserver query, servergroup_id_1 is being provided as a string, not an integer:

'servergroup_id_1': '6'

In the table, the field that is matching is an integer.

I see this behaviour in both 7.0 and 7.1.

**To Reproduce**

1. Deploy PGAdmin4 docker image, in server mode, with a postgres backend database (likely same error running in server mode in a non-docker deploy).
2. Connect to a server, then right click on the database you want to query against.
3. Right click and choose Query Tool.

**Expected behavior**

The Query Tool opens.

**Error message**

{"success":0,"errormsg":"(psycopg.errors.UndefinedFunction) operator does not exist: integer = character varying\nLINE 3: ..._id = $2::INTEGER AND sharedserver.servergroup_id = $3::VARC...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\n[SQL: SELECT sharedserver.id AS sharedserver_id, sharedserver.osid AS sharedserver_osid, sharedserver.user_id AS sharedserver_user_id, sharedserver.server_owner AS sharedserver_server_owner, sharedserver.servergroup_id AS sharedserver_servergroup_id, sharedserver.name AS sharedserver_name, sharedserver.host AS sharedserver_host, sharedserver.port AS sharedserver_port, sharedserver.maintenance_db AS sharedserver_maintenance_db, sharedserver.username AS sharedserver_username, sharedserver.password AS sharedserver_password, sharedserver.save_password AS sharedserver_save_password, sharedserver.role AS sharedserver_role, sharedserver.comment AS sharedserver_comment, sharedserver.discovery_id AS sharedserver_discovery_id, sharedserver.db_res AS sharedserver_db_res, sharedserver.bgcolor AS sharedserver_bgcolor, sharedserver.fgcolor AS sharedserver_fgcolor, sharedserver.service AS sharedserver_service, sharedserver.use_ssh_tunnel AS sharedserver_use_ssh_tunnel, sharedserver.tunnel_host AS sharedserver_tunnel_host, sharedserver.tunnel_port AS sharedserver_tunnel_port, sharedserver.tunnel_username AS sharedserver_tunnel_username, sharedserver.tunnel_authentication AS sharedserver_tunnel_authentication, sharedserver.tunnel_identity_file AS sharedserver_tunnel_identity_file, sharedserver.tunnel_password AS sharedserver_tunnel_password, sharedserver.shared AS sharedserver_shared, sharedserver.connection_params AS sharedserver_connection_params, servergroup_1.id AS servergroup_1_id, servergroup_1.user_id AS servergroup_1_user_id, servergroup_1.name AS servergroup_1_name \nFROM sharedserver LEFT OUTER JOIN servergroup AS servergroup_1 ON servergroup_1.id = sharedserver.servergroup_id \nWHERE sharedserver.name = %(name_1)s::VARCHAR(128) AND sharedserver.user_id = %(user_id_1)s::INTEGER AND sharedserver.servergroup_id = %(servergroup_id_1)s::VARCHAR AND sharedserver.osid = %(osid_1)s::INTEGER \n LIMIT %(param_1)s::INTEGER]\n[parameters: {'name_1': 'common', 'user_id_1': 2, 'servergroup_id_1': '6', 'osid_1': 33, 'param_1': 1}]\n(Background on this error at: https://sqlalche.me/e/20/f405)","info":"","result":null,"data":null}

**Desktop (please complete the following information):**
 - OS: Any client, but using Windows 10, server running in with pgage/pgadmin4 docker image
 - Version: 7.0 and 7.1
 - Mode:Server
 - Browser Firefox and Chrome
 - Package type: Container

**Comment by jodonovan-kv** [comment]
Seeing the same issue after upgrading from 6.19 to 7.2. This is now preventing us from using shared servers.

In our case if a user tries to open either  the **Query tool** or **View Data** They will get:

```
{
    "success": 0,
    "errormsg": "(psycopg.errors.UndefinedFunction) operator does not exist: integer = character varying
        LINE 3: ..._id = $2::INTEGER AND sharedserver.servergroup_id = $3::VARC...
                                                             ^
        HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
        [SQL: SELECT sharedserver.id AS sharedserver_id, sharedserver.osid AS sharedserver_osid, sharedserver.user_id AS sharedserver_user_id, sharedserver.server_owner AS sharedserver_server_owner, sharedserver.servergroup_id AS sharedserver_servergroup_id, sharedserver.name AS sharedserver_name, sharedserver.host AS sharedserver_host, sharedserver.port AS sharedserver_port, sharedserver.maintenance_db AS sharedserver_maintenance_db, sharedserver.username AS sharedserver_username, sharedserver.password AS sharedserver_password, sharedserver.save_password AS sharedserver_save_password, sharedserver.role AS sharedserver_role, sharedserver.comment AS sharedserver_comment, sharedserver.discovery_id AS sharedserver_discovery_id, sharedserver.db_res AS sharedserver_db_res, sharedserver.bgcolor AS sharedserver_bgcolor, sharedserver.fgcolor AS sharedserver_fgcolor, sharedserver.service AS sharedserver_service, sharedserver.use_ssh_tunnel AS sharedserver_use_ssh_tunnel, sharedserver.tunnel_host AS sharedserver_tunnel_host, sharedserver.tunnel_port AS sharedserver_tunnel_port, sharedserver.tunnel_username AS sharedserver_tunnel_username, sharedserver.tunnel_authentication AS sharedserver_tunnel_authentication, sharedserver.tunnel_identity_file AS sharedserver_tunnel_identity_file, sharedserver.tunnel_password AS sharedserver_tunnel_password, sharedserver.shared AS sharedserver_shared, sharedserver.connection_params AS sharedserver_connection_params, servergroup_1.id AS servergroup_1_id, servergroup_1.user_id AS servergroup_1_user_id, servergroup_1.name AS servergroup_1_name 
        FROM sharedserver LEFT OUTER JOIN servergroup AS servergroup_1 ON servergroup_1.id = sharedserver.servergroup_id 
        WHERE sharedserver.name = %(name_1)s::VARCHAR AND sharedserver.user_id = %(user_id_1)s::INTEGER AND sharedserver.servergroup_id = %(servergroup_id_1)s::VARCHAR AND sharedserver.osid = %(osid_1)s::INTEGER 
        LIMIT %(param_1)s::INTEGER]
        [parameters: {"name_1": "DS - postgres", "user_id_1": 5, "servergroup_id_1": "3", "osid_1": 11, "param_1": 1}]
        (Background on this error at: https://sqlalche.me/e/20/f405)",
    "info": "",
    "result": null,
    "data": null
}
```

**Comment by Dagon-** [comment]
Upgraded to 7.5 from 6.x. I'm now seeing this with shared DB's. Same errors are those already reported.

**Comment by ssaslavsky** [comment]
I just deployed 7.5 from docker, and I can see this issue too
whith this bug, Shared servers functionality is useless for us

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the last snapshot build for Docker.
