### ISSUE TITLE
Register Server: an arbitrary SQL query can be fired while setting the role

### ISSUE THREAD

**Issue by khushboovashi** [pgadmin-org/pgadmin4#6253]
Reproduction steps:

  1. Register the server
  2. Fill in the Host name/address, port, maintenance database, and username
  3. Enter any role that exists in the system followed by arbitrary 
 
SQL commands, eg.

    joe; RESET ROLE; CREATE TABLE pwned()

What should happen:

  Error: role "joe; RESET ROLE; CREATE TABLE pwned()" does not exist

What actually happens:

  Connection to the database with the login role rather than the
intended role and a new "pwned" table in the default schema.

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-09/
