### ISSUE TITLE
Password Exec properties not included in import/export servers

### ISSUE THREAD

**Issue by markdonohue** [pgadmin-org/pgadmin4#6258]
**Describe the bug**

When you use "Tools", "Import/Export Servers..." to export servers to a json file, the server properties "Password exec command" and "Password exec expiration (seconds)" (server.passexec_* fields) are not included in the export file (and likewise are not imported).

**To Reproduce**

1. Set "Password exec command" and "Password exec expiration (seconds)" for a server
2. Click on "Tools", "Import/Export Servers..."
3. Export the server
4. Notice those fields are missing in the json

**Expected behavior**

Fields should be included in the json file on export, and likewise set on import.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 7.1
 - Mode: Desktop

**Additional context**

This is useful to hand configurations for server landscapes to new colleagues in cases where external password management is used and integrated into pgAdmin (e.g. Hashicorp Vault).

An example on how to potentially fix this, in "web/pgadmin/utils/__init__.py", if you add the following lines, the fields are included on import/export...

Add to dump_database_servers:
```
            add_value(attr_dict, "PasswordExecCommand", server.passexec_cmd)
            add_value(attr_dict, "PasswordExecExpiration", server.passexec_expiration)
```
Add to load_database_servers:
```
            new_server.passexec_cmd = obj.get("PasswordExecCommand", None)
            new_server.passexec_expiration = obj.get("PasswordExecExpiration", None)
```

**Comment by adityatoshniwal** [comment]
This duplicates #6247.

**Comment by markdonohue** [comment]
> This duplicates #6247.

Incorrect, this is NOT a duplicate of #6247.  They are both related to passexec, but are different:
#6247 is about password information not being passed to psql when using passexec.
This bug #6258 is about passexec configuration details not being included in the import/export of server configurations.

The code snippets in the aforementioned bugs provide a example of the issue and code and potential solution approach. 
 Please re-open this bug and consider for an upcoming sprint.

**Comment by adityatoshniwal** [comment]
@markdonohue I see. I misread it. Reopening.

**Comment by FaharAbbasRizvi** [comment]
This is tested and fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-18/
