### ISSUE TITLE
Message Request failed with status code 500 is displayed if Cancel the active query with a non-maintenance DB

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6261]
If select Active Session only Cancel the active query and click on the yes button for confirmation, I am getting the "Request failed with status code 500" error message.

This is reproducible if the user on the dashboard for a non-maintenance DB

**To Reproduce**

1. Create any  new database 
2. Add new server and on MaintainceDB select the newly created server
3. Server connected succesfully
4. Go to Dashboard and select Active Session only
5. Cancel the active query and click on the yes button for confirmation
6. See the error

status code 500 message.

**Expected behavior**

No Error should be displayed if the user Cancel the active query with  non-maintenance DB

**Screenshots**

<img width="1005" alt="Screen Shot 2023-05-08 at 4 04 22 PM" src="https://user-images.githubusercontent.com/43006122/237063411-3402d78a-1bd1-4b04-a29d-4b8cd4f9f972.png">

<img width="1002" alt="Screen Shot 2023-05-08 at 4 04 31 PM" src="https://user-images.githubusercontent.com/43006122/237063451-469b47f2-6577-423a-9663-46261552886f.png">

**Desktop (please complete the following information):**
 - OS: [All]
 - Version: [7.1]
 - Mode: [All]
 - Package type: [All]

**Comment by adityatoshniwal** [comment]
This is fixed with latest version.
