### ISSUE TITLE
OAUTH2_USERNAME_CLAIM is not respected

### ISSUE THREAD

**Issue by omerfsen** [pgadmin-org/pgadmin4#6267]
**Describe the bug**

On https://www.pgadmin.org/docs/pgadmin4/development/oauth2.html  it states that we can use 
OAUTH2_USERNAME_CLAIM as username but default value is email. 

Our environment on Azure AD is that we have not defined emails but when we try to logon with OAUTH enabled we are getting error "An email Id is required to login into PgAdmin. Please update your Oauth2 Profile"

We are setting it on our ConfigMap as (mailNickName or userPrincipalName ) we still get the same error

**To Reproduce**

On AD, on your LDAP attribute for user delete email attr. And try to logon.

**Expected behavior**

Able to logon with alternate Attrribues (such as mailNickName or userPrincipalName) 

**Error message**

An email Id is required to login into PgAdmin. Please update your Oauth2 Profile

**Screenshots**

An email Id is required to login into PgAdmin. Please update your Oauth2 Profile
![image](https://github.com/pgadmin-org/pgadmin4/assets/29705627/edd9d651-7847-4b80-9a5e-327aef76bc03)

**Comment by yogeshmahajan-1903** [comment]
@omerfsen 
What is the pgAdmin 4 version? Could you please share oAuth2 config?

**Comment by omerfsen** [comment]
@yogeshmahajan-1903 It was 6.21 but i think you fixed this issue now right ?
