### ISSUE TITLE
pgAdmin4 throws error of simplejson if on release v7.0 or v7.1

### ISSUE THREAD

**Issue by bmaehr** [pgadmin-org/pgadmin4#6268]
**Describe the bug**

pgAdmin4 throws error of simplejson if starting on Windows on release v7.0 and v7.1.

**To Reproduce**

1. Installe release 7.1 of pgadmin4 
2. Start pgAdmin4.exe

**Expected behavior**

No Error message should be displayed if user launches pgAdmin4 

**Error message**

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "D:\prog\programmieren\pgAdmin\python\python.exe"
Runtime Config File: "C:\Users\bmaehr\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "D:\prog\programmieren\pgAdmin\web\config.py"
Webapp Path: "D:\prog\programmieren\pgAdmin\web\pgAdmin4.py"
pgAdmin Command: "D:\prog\programmieren\pgAdmin\python\python.exe -s D:\prog\programmieren\pgAdmin\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\bmaehr\AppData\Roaming
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_29176_AOETKWQQATQNYUFX
  - CHROME_RESTART: NW.js|NW.js ist abgestürzt. Jetzt neu starten?|LEFT_TO_RIGHT
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: WORKSTATION
  - ComSpec: C:\windows\system32\cmd.exe
  - DOCKER_TOOLBOX_INSTALL_PATH: D:\prog\system\docker
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - FP_NO_HOST_CHECK: NO
  - GIT_SSH: D:\prog\netzwerk\TortoiseGIT\bin\TortoiseGitPlink.exe
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\bmaehr
  - JAVA_HOME: D:\prog\java\jdk17x64
  - LOCALAPPDATA: C:\Users\bmaehr\AppData\Local
  - logging.path: Z:/Temp/log/
  - LOGONSERVER: \\WORKSTATION
  - M2_HOME: D:\prog\java\maven
  - M2_REPO: D:\projekte\maven-repository
  - NUMBER_OF_PROCESSORS: 20
  - OneDrive: C:\Users\bmaehr\OneDrive
  - OS: Windows_NT
  - PANGO_WIN32_NO_UNISCRIBE: anything
  - Path: D:\prog\programmieren\pgAdmin\runtime;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PowerShell\7\;C:\Program Files\dotnet\;D:\prog\netzwerk\TortoiseGIT\bin;D:\prog\netzwerk\Git\cmd;D:\prog\programmieren\yarn\bin\;D:\prog\netzwerk\TortoiseSVN\bin;D:\prog\java\jdk10x64\bin;D:\prog\java\maven\bin;C:\Users\bmaehr\AppData\Local\Microsoft\WindowsApps;C:\Users\bmaehr\.dotnet\tools;C:\Users\bmaehr\AppData\Local\Microsoft\WindowsApps;C:\Users\bmaehr\.dotnet\tools;C:\Users\bmaehr\AppData\Local\Yarn\bin;D:\prog\programmieren\nodejs;D:\prog\programmieren\yarn\bin;D:\prog\system\docker;
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PGADMIN_INT_KEY: 08d6919e-c62d-4968-8372-fe5e7959297b
  - PGADMIN_INT_PORT: 59292
  - PGADMIN_SERVER_MODE: OFF
  - POWERSHELL_DISTRIBUTION_CHANNEL: MSI:Windows 10 Pro
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
  - PROCESSOR_LEVEL: 6
  - PROCESSOR_REVISION: 9702
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\windows\system32\WindowsPowerShell\v1.0\Modules\
  - PUBLIC: C:\Users\Public
  - SESSIONNAME: Console
  - SPRING_APPLICATION_JSON: {"logging.path": "Z:/Temp/log/", "ftpserver.homeDirectory": "Z:/Temp/log/", "fileAccess.homeDirectory": "D:/projekte/mvb/pubx_documents", "pubx.importer.importdir": "D:/projekte/mvb/pubx_documents/importer"}
  - SVN_SSH: D:\prog\netzwerk\TortoiseGIT\bin\TortoiseGitPlink.exe
  - SystemDrive: C:
  - SystemRoot: C:\windows
  - TEMP: C:\Users\bmaehr\AppData\Local\Temp
  - TMP: C:\Users\bmaehr\AppData\Local\Temp
  - USERDOMAIN: Workstation
  - USERDOMAIN_ROAMINGPROFILE: Workstation
  - USERNAME: bmaehr
  - USERPROFILE: C:\Users\bmaehr
  - VBOX_MSI_INSTALL_PATH: D:\prog\system\vbox\
  - VS140COMNTOOLS: D:\prog\programmieren\vs2015\Common7\Tools\
  - windir: C:\windows
  - ZES_ENABLE_SYSMAN: 1
  - __PSLockDownPolicy: 0
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.012 Sec
Traceback (most recent call last):
  File "D:\prog\programmieren\pgAdmin\web\pgAdmin4.py", line 102, in <module>

    app = create_app()
  File "D:\prog\programmieren\pgAdmin\web\pgadmin\__init__.py", line 549, in create_app
    authenticate.init_app(app)
  File "D:\prog\programmieren\pgAdmin\web\pgadmin\authenticate\__init__.py", line 340, in init_app
    AuthSourceRegistry.load_modules(app)
  File "D:\prog\programmieren\pgAdmin\web\pgadmin\authenticate\registry.py", line 31, in load_modules
    from . import oauth2 as module
  File "D:\prog\programmieren\pgAdmin\web\pgadmin\authenticate\oauth2.py", line 14, in <module>
    from authlib.integrations.flask_client import OAuth
  File "D:\prog\programmieren\pgAdmin\python\lib\site-packages\authlib\integrations\flask_client\__init__.py", line 3, in <module>
    from .apps import FlaskOAuth1App, FlaskOAuth2App
  File "D:\prog\programmieren\pgAdmin\python\lib\site-packages\authlib\integrations\flask_client\apps.py", line 2, in <module>
    from ..requests_client import OAuth1Session, OAuth2Session
  File "D:\prog\programmieren\pgAdmin\python\lib\site-packages\authlib\integrations\requests_client\__init__.py", line 1, in <module>
    from .oauth1_session import OAuth1Session, OAuth1Auth
  File "D:\prog\programmieren\pgAdmin\python\lib\site-packages\authlib\integrations\requests_client\oauth1_session.py", line 2, in <module>
    from requests import Session
  File "D:\prog\programmieren\pgAdmin\python\lib\site-packages\requests\__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "D:\prog\programmieren\pgAdmin\python\lib\site-packages\requests\exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "D:\prog\programmieren\pgAdmin\python\lib\site-packages\requests\compat.py", line 40, in <module>
    from simplejson import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'simplejson' (unknown location)

**Desktop (please complete the following information):**
 - OS: WINDOWS 10
 - Installation not to the default directory

**Additional context**

Seems to be related to https://github.com/pgadmin-org/pgadmin4/issues/6088

Removing it and installing v6.21 on the same machine in the same directory works fine.

**Comment by yogeshmahajan-1903** [comment]
@bmaehr 
Could you please try cleaning old installation directory of 6.21(in your case - D:\prog\programmieren\pgAdmin) and then install 7.0/7.1 version?

**Comment by bmaehr** [comment]
> @bmaehr Could you please try cleaning old installation directory of 6.21(in your case - D:\prog\programmieren\pgAdmin) and then install 7.0/7.1 version?

Thank you. I deleted also the folders in AppData/Local and AppData/Roaming - dont't know if that was necessary - and reinstalled it and it started to work. Thank you.
