### ISSUE TITLE
Allow spawning of connections via command line

### ISSUE THREAD

**Issue by lcmgh** [pgadmin-org/pgadmin4#6272]
When connecting to AWS database instances a recommended approach is to authenticate via IAM roles. With help of the AWS CLI or the SDK users can request a temporary password. This becomes quite cumbersome as there is no IAM integration within pgadmin and other db clients. To workaround that issue a common approach is to launch the db client via a script that fetches the auth token and then passes the credentials to the db program to initiate the desired connection. 

With pgadmin there is no option to spawn the app with a desired connection via the command line. Other clients do support that: https://aws.amazon.com/de/blogs/database/using-iam-authentication-to-connect-with-pgadmin-amazon-aurora-postgresql-or-amazon-rds-for-postgresql/

This doc also outlines the process via the GUI and shows how it can be done with other db programs. You can see that there are currently 20 (!) steps necessary in order to setup the connection.

**Comment by yogeshmahajan-1903** [comment]
@lcmgh 
This feature is already implemented as part of #3491.
Hence closing the ticket.
You can generate a token by mentioning command below in Server Register Dialogue > Advanced > Password exec command
aws --profile MyProfile rds generate-db-auth-token --hostname myhost.rds.amazonaws.com --port 5432 --region my-region --username my_user

**Comment by lcmgh** [comment]
@yogeshmahajan-1903 I see that IAM based authentication is supported as part of https://github.com/pgadmin-org/pgadmin4/issues/3491 but I can't see how this enables me to spawn and establish a connection from the command line?

**Comment by adityatoshniwal** [comment]
@lcmgh You can use Import servers from command line - https://www.pgadmin.org/docs/pgadmin4/7.1/import_export_servers.html#importing-servers to load a json file of connection details. https://github.com/pgadmin-org/pgadmin4/issues/6258 will allow you to add the password exec as well.
