### ISSUE TITLE
Binary and Docker image support for s390x

### ISSUE THREAD

**Issue by ksdeekshith** [pgadmin-org/pgadmin4#6273]
**Describe the solution you'd like**

It would be helpful if we have the support of pgadmin4 s390x support for the docker image. 

Any Idea or suggestion on how should I proceed further to make it support on s390x?

**Comment by yogeshmahajan-1903** [comment]
Supporting this platform will involve a lost of testing efforts. Currently we do not have bandwidth for the same.
