### ISSUE TITLE
Wrong copy: "dependant" instead of "dependent"

### ISSUE THREAD

**Issue by delectomorfo** [pgadmin-org/pgadmin4#6278]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

There's a text saying "No dependant information" in the "Dependents" tab. The word "dependant" does not exist in English.

**To Reproduce**

Open pgAdmin
Click the Dependents tab
See the error

**Expected behavior**

It should say "dependent" instead of "dependant".

**Error message**

No dependant information is available for the selected object.

**Screenshots**

<img width="512" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/162250/6a7ba69b-b368-4bd0-b971-d52fb96c1e90">

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Version: OS 12.5.1 / pgAdmin 6.10
 - Mode: Desktop
 - Browser (if running in server mode): N/A
 - Package type: DMG

**Additional context**

N/A

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-23/
