### ISSUE TITLE
SQL tab of view with field comments contains "comment on column" statements without quotes

### ISSUE THREAD

**Issue by kraynopp** [pgadmin-org/pgadmin4#6280]
SQL tab of view contains following:

CREATE OR REPLACE VIEW public.testviewcomments
 AS
 SELECT testtablecomments.field
   FROM testtablecomments;
ALTER TABLE public.testviewcomments
    OWNER TO postgres;
COMMENT ON VIEW public.testviewcomments
    IS 'View comment';
COMMENT ON COLUMN public.testviewcomments.field
    IS Field comment;

But the last statement should be:
COMMENT ON COLUMN public.testviewcomments.field
    IS 'Field comment';

**Comment by pravesh-sharma** [comment]
Issue resolved. verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-23/

Env - macOS Ventura 13.3.1 (Desktop mode)
