### ISSUE TITLE
VarChar Field Sizes are missing from Query's Grid header

### ISSUE THREAD

**Issue by durumdara** [pgadmin-org/pgadmin4#6281]
In the newer version of the PGAdmin the VarChar Field Sizes are missing from the Query's grid header.

Version 7.1
NW.js Version 0.72.0

In the older versions I could see the sizes, like varchar(40).

It was very helpful, because sometimes the grid contained joined columns where was hard to identify the real source table.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-05-18/
