### ISSUE TITLE
Some fields are repeating in the table DDL SQL

### ISSUE THREAD

**Issue by durumdara** [pgadmin-org/pgadmin4#6284]
Dear Developers!

We saw in the new version that some fields repeat in the table's DDL SQL, which is impossible at PGSQL side.
For exmaple:

```
    vric_qtr double precision,

    vric_kd integer NOT NULL DEFAULT nextval('vric_kd_seq'::regclass),

    vric_kd integer NOT NULL DEFAULT nextval('vric_kd_seq'::regclass),

    CONSTRAINT pk_...

```

Version 7.1
Application Mode Desktop
NW.js Version 0.72.0
Browser Chromium 109.0.5414.87
Operating System Windows-10-10.0.22621-SP0

In EMS PostgreSQL manager I don't see the repeats, and this Query's result is also good:

`SELECT *
  FROM information_schema.columns
 WHERE table_schema = 'public'
   AND table_name   = 'vric';
`

**Comment by yogeshmahajan-1903** [comment]
@durumdara 
Could you please share table DDL, we are not able to reproduce issue at our end.

**Comment by durumdara** [comment]
I'm sorry about it. I can't create same table anomaly in another database.
It exists only in one.
Could you help me how you can create the table DDL? Which SQL statements you used?
Maybe I find the differences based on these SQL-s.
Thank you!

**Comment by durumdara** [comment]
@yogeshmahajan-1903 
Could you send me an SQL wich able to generate the table DDL created by the PGAdmin?
Maybe I can find the source of the problem. Thanks!

**Comment by pravesh-sharma** [comment]
Hi @durumdara,

Tried with the provided SQL on latest version of pgAdmin and it is not reproducible.

<img width="1162" alt="Screenshot 2023-05-26 at 4 53 11 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/de41e632-bfd7-4b08-a52d-8e51ff807fc4">

**Comment by durumdara** [comment]
> Hi @durumdara,
> 
> Tried with the provided SQL on latest version of pgAdmin and it is not reproducible.
> 

Hello!

In this version I see the duplication yet. :-(

Version 7.2 / NW.js Version 0.76.1 / Browser Chromium 113.0.5672.64 / Operating System Windows-10-10.0.22621-SP0

In EMS manager this is normal...  It happens only in one database... :-(

I in the next week I will try to dump the structure and I will check it. Maybe I can provide you some info about it.

**Comment by durumdara** [comment]
As I think I found some suspicious from the dump.
There are two sequences in the background, not one!
I think this cause the repeating!

```
CREATE SEQUENCE public.vric_vric_kd_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.vric_vric_kd_seq OWNED BY public.vric.vric_kd;


CREATE SEQUENCE public.vric_vric_kd_seq1
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.vric_vric_kd_seq1 OWNED BY public.vric.vric_kd;


```

**Comment by durumdara** [comment]
Yes, that is the source of the problem.
Finally I dropped vric_vric_kd_seq1 and the DDL SQL is seems to be ok.
But this thing is a bug - you show the column twice.

**Comment by akshay-joshi** [comment]
@durumdara 

I have tried to reproduce the issue with all the given scenarios. Created two sequences 'public.vric_vric_kd_seq' and 'public.vric_vric_kd_seq1' still unable to reproduce it.

What is the version of PostgreSQL? We can't fix it until it is reproducible.

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
