### ISSUE TITLE
if connection is lost but data need to be loaded on demand, then loading indicator will not disappear

### ISSUE THREAD

**Issue by clockrun** [pgadmin-org/pgadmin4#6291]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
if connection is lost but data need to be loaded on demand, then loading indicator will not disappear

**To Reproduce**

1. write a SQL to load a lot of data
2. wait for some time until connection was disconnected because of idle timeout or other reason
3. scroll result table

**Expected behavior**
no data should be loaded, or dialog was popup to hint user to connect again

**Error message**
A message toast appear indicate it is loading data and displayed there forever

**Screenshots**
<img width="258" alt="Screenshot 2023-05-17 at 13 23 46" src="https://github.com/pgadmin-org/pgadmin4/assets/227283/308001db-5347-4d08-b40b-39e73d39d132">

I would expect below dialog to open and let user to build connectoin again
<img width="598" alt="Screenshot 2023-05-17 at 13 27 44" src="https://github.com/pgadmin-org/pgadmin4/assets/227283/8b0ab682-50cb-417e-87ff-bd88f75b2484">

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 13.3
 - Mode: Server
 - Browser (if running in server mode): Chrome
 - Package type: Container

**Additional context**

**Comment by FaharAbbasRizvi** [comment]
This is tested in the candidate build for 7.4
