### ISSUE TITLE
Can't connect to pgadmin4 -- internal server error

### ISSUE THREAD

**Issue by Rufooooo** [pgadmin-org/pgadmin4#6296]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

On updating to version 7.1, I can no longer connect to the server to login.  The apache error message says 
                      File "/usr/pgadmin4/venv/lib64/python3.11/site-packages/psycopg/pq/__init__.py", line 106, in mport_from_libpq
                      [wsgi:error]` [pid 37382:tid 37537] [remote 192.168.1.75:35318]     raise ImportError(
                      [wsgi:error]` [pid 37382:tid 37537] [remote 192.168.1.75:35318] ImportError: no pq wrapper available.

   
**To Reproduce**
1. Install (or reinstall) pgadmin4 7.1
(I am using postgresql 12 on linux (fedora 37), pgadmin4 rpms installed from pgdg and pgadmin4 repos.)
2. type into browser address of pgadmin4 server
3. See the error.

**Expected behavior**
See the login screen for pgadmin4

**Error message**
[Thu May 18 09:40:13.792982 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278] mod_wsgi (pid=37382): Failed to exec Python script file '/usr/pgadmin4/web/pgAdmin4.wsgi'.
[Thu May 18 09:40:13.793030 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278] mod_wsgi (pid=37382): Exception occurred processing WSGI script '/usr/pgadmin4/web/pgAdmin4.wsgi'.
[Thu May 18 09:40:13.793769 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278] Traceback (most recent call last):
[Thu May 18 09:40:13.794926 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]   File "/usr/pgadmin4/web/pgAdmin4.wsgi", line 38, in <module>
[Thu May 18 09:40:13.794960 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]     from pgAdmin4 import app as application
[Thu May 18 09:40:13.794970 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]   File "/usr/pgadmin4/web/pgAdmin4.py", line 102, in <module>
[Thu May 18 09:40:13.794974 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]     app = create_app()
[Thu May 18 09:40:13.794977 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]           ^^^^^^^^^^^^
[Thu May 18 09:40:13.794983 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]   File "/usr/pgadmin4/web/pgadmin/__init__.py", line 548, in create_app
[Thu May 18 09:40:13.794986 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]     driver.init_app(app)
[Thu May 18 09:40:13.794993 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]   File "/usr/pgadmin4/web/pgadmin/utils/driver/__init__.py", line 27, in init_app
[Thu May 18 09:40:13.794996 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]     DriverRegistry.load_modules(app)
[Thu May 18 09:40:13.795002 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]   File "/usr/pgadmin4/web/pgadmin/utils/driver/registry.py", line 20, in load_modules
[Thu May 18 09:40:13.795005 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]     from . import psycopg3 as module
[Thu May 18 09:40:13.795011 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]   File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg3/__init__.py", line 21, in <module>
[Thu May 18 09:40:13.795025 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]     import psycopg
[Thu May 18 09:40:13.795032 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]   File "/usr/pgadmin4/venv/lib64/python3.11/site-packages/psycopg/__init__.py", line 9, in <module>
[Thu May 18 09:40:13.795036 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]     from . import pq  # noqa: F401 import early to stabilize side effects
[Thu May 18 09:40:13.795039 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]     ^^^^^^^^^^^^^^^^
[Thu May 18 09:40:13.795045 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]   File "/usr/pgadmin4/venv/lib64/python3.11/site-packages/psycopg/pq/__init__.py", line 114, in <module>
[Thu May 18 09:40:13.795048 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]     import_from_libpq()
[Thu May 18 09:40:13.795054 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]   File "/usr/pgadmin4/venv/lib64/python3.11/site-packages/psycopg/pq/__init__.py", line 106, in import_from_libpq
[Thu May 18 09:40:13.795058 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278]     raise ImportError(
[Thu May 18 09:40:13.795074 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278] ImportError: no pq wrapper available.
[Thu May 18 09:40:13.795077 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278] Attempts made:
[Thu May 18 09:40:13.795080 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278] - couldn't import psycopg 'c' implementation: /usr/pgadmin4/venv/lib64/python3.11/site-packages/psycopg_c/pq.cpython-311-x86_64-linux-gnu.so: undefined symbol: PQpipelineStatus
[Thu May 18 09:40:13.795084 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278] - couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
[Thu May 18 09:40:13.795086 2023] [wsgi:error] [pid 37382:tid 37560] [remote 192.168.1.75:45278] - couldn't import psycopg 'python' implementation: 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux fedora 37
 - Version: 37
 - Mode: Desktop
 - Browser (if running in server mode): firefox (both for remote and local login)
 - Package type: RPM from pgadmin4 and pgdg repos

**Additional context**

**Comment by danielhedinn** [comment]
I have the same issue (same stack trace) on Windows 11 22H2 after upgrading to pgAdmin 7.1.

**Comment by akshay-joshi** [comment]
@Rufooooo 
Can you please tell us which libpq version is used?

**Comment by akshay-joshi** [comment]
@danielhedinn 

From which version you have upgraded to 7.1?

**Comment by danielhedinn** [comment]
I downgraded to 7.0 and that is working fine. Before that I was running 6.*, I cannot remember the exact minor version. But I can confirm that 7.0 works fine.

**Comment by akshay-joshi** [comment]
@danielhedinn 

We haven't changed anything related to psycopg or libpq in v7.1, it should work if v7.0 works. We are unable to reproduce this issue.

**Comment by danielhedinn** [comment]
I re-tried installing 7.1, that worked wonders. Pardon this, probably my bad.

**Comment by khushboovashi** [comment]
@Rufooooo,

What is the installed location of both the libpq.so files?

Thanks,
Khushboo

**Comment by Rufooooo** [comment]
> @Rufooooo,
> 
> What is the installed location of both the libpq.so files?

/usr/pgsql-12/lib/libpq.so.5.12

and

/usr/lib64/libpq.so.5.15

**Comment by yogeshmahajan-1903** [comment]
@danielhedinn 
We are not able to reproduce the issue.
Can you please try installing postgresql-client-<pg_verssion> library and try again?

**Comment by Rufooooo** [comment]
> @danielhedinn We are not able to reproduce the issue. Can you please try installing postgresql-client-<pg_verssion> library and try again?

Over the last several weeks, I installed/reinstalled postgresql15-15.3 and pgadmin4-7.4 rpms from PGDG-fedora.  At some point, the problem was resolved.  I can't say exactly what changed.

Thanks for your efforts and time to work on this.  It was (and still is) quite baffling, and I appreciate your attention to my request.
