### ISSUE TITLE
Feature Request - Please add a line separator between two tabs in PgAdmin4

### ISSUE THREAD

**Issue by satish-chef** [pgadmin-org/pgadmin4#6302]
Hello Team.  I am using pgAdmin 4 on Mac.  I am on the latest version 7.1.  This is a feature request to add a line separator to differentiable between two tabs in the UI tool.  When I open query tool for two databases present in the same RDS instance, it becomes difficult to visualize the two separate tabs.  I cannot share the snapshot for security reasons but I hope you get the idea.

**Comment by adityatoshniwal** [comment]
@satish-chef To be frank it is not clear what the requirement is. Can you share screenshot with imp details blurred/hidden?

**Comment by khushboovashi** [comment]
No response from the author, closing the issue.
