### ISSUE TITLE
Error message is displayed if user create new database with pgbouncer port 6432

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6304]
Error message is displayed if user create new database with pgbouncer port 6432

**To Reproduce**

Steps to reproduce the behaviour:
1. Install PostgreSQL 15 and Install pgbouncer through StackBuilder
2. Launch pgAdmin4
3. Add a New server
4. Provide the name
5.  In the Connection field, select port 6432 and maintainceDB select postgres and add New server
6. Server added successfully
7. create new database pgbouncer
8. Following error message is displayed:
**invalid command 'SET DateStyle=ISO; SET client_min_messages=notice; SELECT set_config('bytea_output','hex',false) FROM pg_settings WHERE name = 'bytea_output'; SET client_encoding='UTF8';', use SHOW HELP;**
9. create another database pgbouncer1
10. Following error message is displayed:
**connection failed: :1), port 6432 failed: FATAL: no such database: pgbouncer1**

Please note that databases should be created successfully through psql if port is 6432.

**Expected behavior**

If the user connects with pgbouncer 6432 port then the database should be created.

**Screenshots**

<img width="1009" alt="Screen Shot 2023-05-22 at 1 31 31 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/eaa79522-cd66-4f7c-9425-957ebb9004f1">
<img width="1003" alt="Screen Shot 2023-05-22 at 1 36 04 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/0c45b526-74c9-416f-9a81-53294a3a14c1">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 7.1]
 - Mode: [All
 - Package type: [Any]

**Comment by pravesh-sharma** [comment]
Tested with PSQL and observed the same behaviour. Closing.


![Image](https://github.com/user-attachments/assets/90cc0a1d-56d0-46fa-882f-674de2cf81ec)
