### ISSUE TITLE
When PGAdmin lost the connection (because of hibernation), the SQL SELECT (Query) turns to COMMAND (No data output)

### ISSUE THREAD

**Issue by durumdara** [pgadmin-org/pgadmin4#6307]
Dear Developers!

I experienced this problem many times.

I opened more databases. For each DBs I opened SQL Query windows.
select * from nnn limit 10;

Later I had to hibernate the machine. When I opened it again and I try to execute the query, I got only the textual result about execution - not the data:

select * from nnn limit 10;
Query returned successfully in 299 msec.
No data output.

When this happened, I never get data in this Query window. 
I have open a new, copy the SQL statement and after F5 I will get the result.

Version
7.1
Application Mode
Desktop
Current User
pgadmin4@pgadmin.org
NW.js Version
0.72.0
Browser
Chromium 109.0.5414.87
Operating System
Windows-10-10.0.22621-SP0

**Comment by grietine** [comment]
Same issue on my side!

pgAdmin version: 7.3

**Comment by pravesh-sharma** [comment]
Hi @durumdara,

Please test the latest version and check if it is still reproducible. If you still face the issue can you please share the logs?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
