### ISSUE TITLE
unable to dnf update pgadmin4 after upgrade to fedora38

### ISSUE THREAD

**Issue by frankarinnet** [pgadmin-org/pgadmin4#6311]
**Describe the bug**
After upgrading from fedora-37 to fedora-38, I can no longer update pgadmin using dnf.

**To Reproduce**

* upgrade from fedora-37 to fedora-38 (probably irrelevant)
* run *dnf update*
* see dnf update complain

**Expected behavior**

Dnf should apply updates to pgadmin.

**Error message**

The error I get is:
*Error: Failed to download metadata for repo 'pgAdmin4': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried*

And the cause seems to be:
*Status code: 404 for https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/fedora/fedora-38-x86_64/repodata/repomd.xml (IP: XXXX:XXXX:XXX:1::246)*

Of interest the uri: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/fedora/  has sub-directories for fedora-37 (among others), but nothing for fedora-38.

I've attached as a file a log of the full error and a small amount of context: [dnf_output.txt](https://github.com/pgadmin-org/pgadmin4/files/11533245/dnf_output.txt)

**System information:**
 - OS: fedora-38
 - Version: whatever should be latest
 - Mode: desktop
 - Package type: rpm

**Additional context**

I think that work associated with https://github.com/pgadmin-org/pgadmin4/issues/6259 was supposed to fix this, but didn't seem to.

**Comment by adityatoshniwal** [comment]
Hi,

pgAdmin for Fedora38 will be available from next release which is v7.2.

Thanks.
