### ISSUE TITLE
Unable to update row with View/Edit Data when primary key type is bytea

### ISSUE THREAD

**Issue by shuaixr** [pgadmin-org/pgadmin4#6316]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Unable to update row with View/Edit Data when primary key type is bytea

**To Reproduce**

First run the following sql to create tables and data.
```
CREATE TABLE IF NOT EXISTS public.test
(
    id bytea NOT NULL,
    name text COLLATE pg_catalog."default",
    CONSTRAINT test_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.test
    OWNER to postgres;

INSERT INTO public.test(
	id, name)
	VALUES (decode('DEADBEEF', 'hex'), 'A');
```

Then use the View/Edit Data of pgadmin to modify the data and save it.
Pgadmin Alert: Data saved successfully.
Get the data again, the data has not been updated

**Expected behavior**

Data is updated

**Error message**

No error message

**Screenshots**

**Desktop (please complete the following information):**
Version 7.1
Application Mode Server
Browser Chrome 113.0.0.0
Operating System Linux-5.10.0-21-amd64-x86_64-with

**Additional context**

**Comment by pravesh-sharma** [comment]
bytea data is not fetched by query tool since it is a binary data. We will disable edit in such cases.

**Comment by adityatoshniwal** [comment]
Related to #3199
