### ISSUE TITLE
pgAdmin update notice linking to postgres update not pgadmin update

### ISSUE THREAD

**Issue by jennjunod** [pgadmin-org/pgadmin4#6318]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When starting pgAdmin 4 v 6.19 there is a notice given "You are currently running version 6.19 of pgAdmin 4, however the current version is 6.20.

Please click here for more information"

The current here hyperlink goes to [Download PostgreSQL](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads) not [the homepage for pgAdmin](https://www.pgadmin.org/) or [Download page](https://www.pgadmin.org/download/)

**To Reproduce**

Start pgAdmin

When starting pgAdmin 4 v 6.19 there is a notice given "You are currently running version 6.19 of pgAdmin 4, however the current version is 6.20.

Please click here for more information"

The current here hyperlink goes to [Download PostgreSQL](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads) 

**Expected behavior**

When starting pgAdmin 4 v 6.19 there is a notice given "You are currently running version 6.19 of pgAdmin 4, however the current version is 6.20.

Please click here for more information"

Here should go to [the homepage for pgAdmin](https://www.pgadmin.org/) or [Download page](https://www.pgadmin.org/download/)

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

![2023-05-23_14-19-04 (3)](https://github.com/pgadmin-org/pgadmin4/assets/77285384/fc0cd7bf-5605-42cc-b67d-aacbc6364f73)

**Desktop (please complete the following information):**
 - OS: OSX Ventura 
 - Version: 13.4
 - Mode: Laptop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by FaharAbbasRizvi** [comment]
@jennjunod 

Can you please uninstall PostgreSQL and install the latest PostgreSQL 15 on https://www.enterprisedb.com/downloads/postgres-postgresql-downloads?

Please note that I can see pgAdmin4 7.1 version.

![Screenshot 2023-05-23 at 11 08 28 PM](https://github.com/pgadmin-org/pgadmin4/assets/43006122/1e77d853-7594-43c5-8953-09fc5e0efebf)

**Comment by adityatoshniwal** [comment]
Hi @jennjunod,
You don't need to uninstall PostgreSQL. The pgAdmin 6.19 you're having must be what is shipped with PostgreSQL installers. Currently, the latest pgAdmin shipped with PostgreSQL is still at v6.20. That is the reason it is showing you v6.20.
What you can do is, using PostgreSQL uninstaller remove pgAdmin and download the latest pgAdmin separately from pgadmin website.

**Comment by akshay-joshi** [comment]
@jennjunod 

Whenever pgAdmin is installed using PostgreSQL installers, the download link will point to https://www.enterprisedb.com/downloads/postgres-postgresql-downloads and if it is downloaded and installed from the community website then it point to https://www.pgadmin.org/download/

So this is expected behaviour.
