### ISSUE TITLE
Databases list incorrectly classifies database as system object if its oid is < 16383

### ISSUE THREAD

**Issue by AndrewAWhite** [pgadmin-org/pgadmin4#6320]
**Describe the bug**

The pgadmin browser does not display my database unless the "show system objects" and "show template databases" options are checked in the preferences.

**To reproduce**

To reproduce this:

1. Starting with a new postgres instance, create some tables in the default database named "postgres".
2. Rename the database to "invisible".
3. Unset the database as a template: `ALTER DATABASE invisible WITH is_template=false;`
4. Re-create the default database: `CREATE DATABASE postgres TEMPLATE template1;`
5. Register this server in pgadmin.

The "invisible" database will not be visible unless "Show system objects" and "Show template databases" are checked within the preferences.

**Expected behaviour**

The non-system, non-template database should display by default.

**Additional context**

I _think_ this is due to the following line:

https://github.com/pgadmin-org/pgadmin4/blob/1e7517dc987e2af8294ac314a0b57a2f98bd15e7/web/pgadmin/browser/server_groups/servers/databases/__init__.py#L276

Since the database started as the "postgres" database, it has an oid that is < the DATABASE_LAST_SYSTEM_OID constant set in [pgadmin4](https://github.com/pgadmin-org/pgadmin4/tree/7ab096d87f0e8c2cd1b7ca52e632ef61de86db42)/[web](https://github.com/pgadmin-org/pgadmin4/tree/7ab096d87f0e8c2cd1b7ca52e632ef61de86db42/web)/[pgadmin](https://github.com/pgadmin-org/pgadmin4/tree/7ab096d87f0e8c2cd1b7ca52e632ef61de86db42/web/pgadmin)/[utils](https://github.com/pgadmin-org/pgadmin4/tree/7ab096d87f0e8c2cd1b7ca52e632ef61de86db42/web/pgadmin/utils)/constants.py

**Comment by pravesh-sharma** [comment]
Hi @AndrewAWhite 

The default database `postgres` is system generated database. Even if you rename it will not change its status. pgAdmin as an exception shows the postgres database independent of `show system objects` flag. If you rename it won't work.
