### ISSUE TITLE
How to fix the screen

### ISSUE THREAD

**Issue by Divyesh1805** [pgadmin-org/pgadmin4#6333]
![Screenshot 2023-05-29 154612](https://github.com/pgadmin-org/pgadmin4/assets/102990085/d2fab0b0-32a8-4f30-a53b-4424faa353d2)

the side tool bar and all is not coming up! Tried everything!

**Comment by adityatoshniwal** [comment]
Duplicates #6266.
Please install v7.2 for the fix.
