### ISSUE TITLE
Connection does not close on closing psql tool

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#6334]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Connection does not close on closing psql tool
**To Reproduce**

1.Open psql tool.
2.Check the connection created for psql tool in dashboard tab
3.Close psql tool.
4.Again check dashboard tab, connection is NOT closed.

**Expected behavior**

DB connection should have closed.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by adityatoshniwal** [comment]
@yogeshmahajan-1903  is this happening for firefox or desktop?

**Comment by nikhil-mohite** [comment]
Issues are reproducible on Firefox only as it is unable to close the socket connection after the panel close.

**Comment by adityatoshniwal** [comment]
This is a limitation of FireFox and there is not solution/workaround. Other browsers work fine.
