### ISSUE TITLE
Unable to connect through Pgbouncer after upgrading from 6.21 to 7.1 

### ISSUE THREAD

**Issue by amitabhkant** [pgadmin-org/pgadmin4#6340]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
Version 7.1 is unable to connect through pgbouncer, while on the same environment (same server/pgbouncer/desktop) version 6.21 connects happily. 7.1 produces the following error:

codec not available in Python: 'UNICODE'

There is no change in the postgresql server (version 12), pgbouncer or even the mac. 

Can't even register a new server where the connection goes through pgbouncer. Tried deleting the previous connection and registering a new server (through pgabouncer as passthru) shows the same error. 

Connections directly to Postgres servers are working fine.

**To Reproduce**

Try connecting to postgres through pgbouncer using version 7.1, and then again through version 6.21

**Expected behavior**

Connection through pgboucer should go normally as has been in the previous versions

**Error message**

codec not available in Python: 'UNICODE'

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 MacOS Ventura 13.3.1

 - Version: [e.g. 6.15]
 7.1

 - Mode: [e.g Desktop or Server]
 Desktop
 
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]
 DMG package

**Comment by khushboovashi** [comment]
@amitabhkant, please send the full log trace. To enable logging please refer, https://www.pgadmin.org/faq/#8

**Comment by amitabhkant** [comment]
[pgadmin4.log](https://github.com/pgadmin-org/pgadmin4/files/11626184/pgadmin4.log)

Please find the log attached

**Comment by amitabhkant** [comment]
Just checked with the recently released 7.2, and the issue persists.

**Comment by amitabhkant** [comment]
> @amitabhkant have a look at this topic, you'll find some workarounds: [psycopg/psycopg#122](https://github.com/psycopg/psycopg/issues/122)

I am not well versed with Python to implement the changes mentioned in the issue you linked. I have reverted back to 6.21 for the time being as it works for me. Will test again once a new version comes out.

**Comment by FaharAbbasRizvi** [comment]
Hi @amitabhkant 

Could you please verify it on the latest snapshot builds?
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-21/

**Comment by amitabhkant** [comment]
@FaharAbbasRizvi The snapshot build is not opening up on my mac (Ventura 13.4). It installs ok, but opening the app does not open up any window

**Comment by FaharAbbasRizvi** [comment]
Hi @amitabhkant 

Can you please let me know which .dmg file you are using?

Please note that [pgadmin4-7.3-arm64.dmg] is not supported yet. kindly use [pgadmin4-7.3-x86_64.dmg] only.

**Comment by amitabhkant** [comment]
I was using pgadmin4-7.3-arm64.dmg, will try x86 now

**Comment by amitabhkant** [comment]
Did try the x86 version, problem remains the same.

**Comment by amitabhkant** [comment]
[pgadmin4.log](https://github.com/pgadmin-org/pgadmin4/files/11815966/pgadmin4.log)
This is the log file @FaharAbbasRizvi

**Comment by khushboovashi** [comment]
@amitabhkant, thanks for the log. We have fixed the issue. Please verify it with tomorrow's snapshot build.

**Comment by FaharAbbasRizvi** [comment]
@amitabhkant Here is the URL of the latest snapshot build location https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-22/

**Comment by amitabhkant** [comment]
@FaharAbbasRizvi The latest snapshot works with pgbouncer now

**Comment by FaharAbbasRizvi** [comment]
Closing the issue as per user comments.
