### ISSUE TITLE
Can't use tunnel settings after upgrade to 7.2 from 7.1

### ISSUE THREAD

**Issue by Drblack101** [pgadmin-org/pgadmin4#6341]
Everything was fine this morning before I did the upgrade (old version is 7.1). After upgrading to 7.2, I can't connect to the remote DB server via tunnel settings. The password window keep popping out to ask me enter ssh tunnel user password and the DB user password even I've entered the correct password. 

Re-launching the 6.21 version of pgadmin V4, no problem to connect to remote DB through the same settings.

**Comment by EFrankel-ITEP** [comment]
I have the same issue on Linux Mint 20.3 (Una). I get a message that ServerManager does not have 'manager' with "Failed to decrypt the SSH tunnel password." When I first opened 7.2 after upgrading, I saw the password conversion dialog and it indicated that it converted successfully.

**Comment by claudiobgit** [comment]
Same issue on Ubuntu 22.04 Desktop after upgrading from 7.1.

**Comment by pravesh-sharma** [comment]
Issue fixed. verified on candidate build https://developer.pgadmin.org/builds/2023-06-05-1/
