### ISSUE TITLE
PgAdmin 7.2 failed to take the defined role

### ISSUE THREAD

**Issue by pr2git** [pgadmin-org/pgadmin4#6342]
Hi,

Again a problem with user that need to take another role when connecting to database.

I connect with my LDAP account but in order to be able to access a DB I need to take a specific role.

With PgAdmin 7.2 it no longer works, I have:  failed to setup the role dba and it prompt for the password I enter the correct password and same error. There is no evidence of a problem in the postgresql.log on the server.

![OnMorePgAdmin7 2_bug_with_role](https://github.com/pgadmin-org/pgadmin4/assets/13857365/f31fb20c-94e0-4b07-976d-fdb4c23a5e79)

Small precision the Master Password that I am using is different from the one used in the LDAP, I hope that you didn't mix up the Master Password with the user one.

I returned to PgAdmin 7.1 and everything is fine.

**Comment by khushboovashi** [comment]
Hi @pr2git,

Can you please share your server properties dialog ? 
Also, please share detailed steps to reproduce this issue?

Thanks,
Khushboo

**Comment by pr2git** [comment]
Please read this issue:

https://github.com/pgadmin-org/pgadmin4/issues/5702

And you will get all the details to reproduce it, I always use the same setup.

Thanks

**Comment by anilsahoo20** [comment]
Issue fixed and verified.
Tested on candidate build: https://developer.pgadmin.org/builds/2023-06-05-1/
