### ISSUE TITLE
pdAgent MAC Administrator

### ISSUE THREAD

**Issue by ceciliaiacometta** [pgadmin-org/pgadmin4#6343]
After downloading Postgres and pgAdmin I have a new user in my Mac which substitute my previous. It is Administrator User and I do not have my one anymore. It is also with passwords I have never set and I don’t know I can not do anything on my computer
Please
It is urgent, I need to have my computer with my administrator user back

**Comment by akshay-joshi** [comment]
It is not a pgAdmin issue, you can report this to the maintainer of the PostgreSQL installers.
