### ISSUE TITLE
Explain details are HTML escaped

### ISSUE THREAD

**Issue by Fox32** [pgadmin-org/pgadmin4#6352]
**Describe the bug**

Output of the "Filter" row in the explain details are HTML escaped.
This makes it hard to read the expression.

**To Reproduce**

1. Open a query window and run a query that filters something
2. Use explain
3. Click on the node that is performing the filtering to open the details table
4. Look at the "Filter" row, the expressions contains HTML escape sequences.

**Expected behavior**

Values should be displayed in human readable text, like:

```
(("workspaceId")::text = 'YhTz4DjVXod'::text)
```

**Error message**

Instead HTML escape sequences are embedded:

```
((&quot;workspaceId&quot;)::text = &#39;4YhTz4DjVXod&#39;::text)
```

**Screenshots**

<img width="1198" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/648527/5ec1e9b9-7326-496b-9895-be982943ad4f">

**Desktop (please complete the following information):**
 - OS: OSX monterey
 - Version: 7.2 (but also 7.0 and 7.1)
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by FaharAbbasRizvi** [comment]
This is tested in the Candidate Build for 7.4
