### ISSUE TITLE
 Queries with temporary tables in the same transaction

### ISSUE THREAD

**Issue by woliveir** [pgadmin-org/pgadmin4#6354]
Since version 7.1 of pgadmin4 an error occurs in queries with temporary tables in the same transaction, example for reproduction:

**To Reproduce**

1. Go to 'Tools'
2. Click on 'Query Tool'
3. Execute

```sql 
-- pgadmin4:  version 7.1 and 7.2
CREATE TEMPORARY TABLE test(today) ON COMMIT DROP AS
  VALUES(CURRENT_DATE)
;

SELECT
  *
FROM
  test
;

-- output error message
-- > The specified object could not be found.
```

**Expected behavior**

show test table rows in the Data Output.

**Screenshots**
![image](https://github.com/pgadmin-org/pgadmin4/assets/16959203/caa5c255-35f3-424c-af93-c447ed3780ab)

**Desktop:**
 - OS: Linux Ubuntu/Bionic (18.04 LTS)
 - Version: pgadmin 7.2
 - Mode: Server
 - Browser: chrome, firefox
 - Package type: Docker Container

**Comment by adityatoshniwal** [comment]
Fixed with commit https://github.com/pgadmin-org/pgadmin4/commit/4746fbd34674574bec09113d0240618301fdcebf

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-21/

Env - macOS Ventura (13.4) Desktop mode.
