### ISSUE TITLE
Preview images are missing in Preferences > Miscellaneous > Themes

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#6363]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Preview images are missing in Preferences > Miscellaneous > Themes

**To Reproduce**

Preview images are missing in Preferences > Miscellaneous > Themes

**Expected behavior**

**Error message**

<img width="1001" alt="Screenshot 2023-06-05 at 1 56 18 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/08b8270a-3e2f-454c-894d-5995fb95c088">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-13/
