### ISSUE TITLE
Query Tool/ PSQL tool tab title not getting updated on database rename

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#6364]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

If the user updates the database name and opens the Query tool/PSQL tool the updated name is not getting reflected in the tab title

**To Reproduce**

1. Select any database node from Browser Explorer 
2. Open the edit dialog
3. Change the database name and save.
4. Now open the Query tool or PSQL tool
5. Check Query tool/PSQL tool tab title is showing an older database name.

**Expected behavior**

The updated database name should be shown in the tab title after the database name update

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Version: 7.3
 - Mode: Desktop
 - Browser (if running in server mode): N/A
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build.
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-03/
