### ISSUE TITLE
DROP DATABASE can now take the option FORCE to drop a database even if other users are connected.

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#6367]
Available from PG version 13 onwards.

**Comment by nikhil-mohite** [comment]
Tested on latest candidate build as per test plan.
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-21/
OS: macOS (Ventura 13.3)
Mode: Desktop
