### ISSUE TITLE
Add all new like_options while creating a table.

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#6377]

**Comment by khushboovashi** [comment]
{ INCLUDING | EXCLUDING } { COMMENTS | CONSTRAINTS | DEFAULTS | IDENTITY | INDEXES | STATISTICS | STORAGE | ALL }

From the above syntax, we have not implemented EXCLUDING and ALL options, but without these options too, the implementation fulfils the requirement of ALL and EXCLUDING.

So, closing the ticket and someone feels these options should be there can reopen it.
