### ISSUE TITLE
Add "USING <method>" option while creating a table. 

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#6378]

**Comment by FaharAbbasRizvi** [comment]
@pravesh-sharma 

If the user tries to create a new table and selects the default method heap then syntax error is displayed:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-09-12/
<img width="1302" alt="Screen Shot 2023-09-12 at 5 08 45 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/9b4c3ab5-e3fc-4ad8-ba0f-54db63ef808b">
<img width="1311" alt="Screen Shot 2023-09-12 at 5 08 57 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/d93925fc-f3cb-409b-8445-8ef845d17dba">

**Comment by anilsahoo20** [comment]
Access method once given for partitioned child table while creating table is not coming in properties if we go through table. else it is visible if we go through Partitions node object.(For all PG versions)

MSQL is not getting generated for edit table -> partition child table to any other access method.(For PGv15 and above as alter access method is available in PGv15 and above)
<img width="1728" alt="Screenshot 2023-09-18 at 4 22 02 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/122535205/474b9d37-989b-40ff-9307-710cfaba623f">
<img width="1728" alt="Screenshot 2023-09-18 at 4 23 15 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/122535205/2cfca8b7-5ac7-43e4-b564-09e6ffccd52e">
<img width="1728" alt="Screenshot 2023-09-18 at 4 23 52 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/122535205/104c63c7-207d-4330-8fc7-1d27731db414">
<img width="1728" alt="Screenshot 2023-09-18 at 4 24 03 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/122535205/09dac0ad-7fa1-457f-8fd0-5b85b63d34ef">

**Comment by pravesh-sharma** [comment]
@anilsahoo20 

I have fixed #1 and for the time being we have disabled access method drop down from partitions tab when opening table properties as we do not allow any change from there.

**Comment by anilsahoo20** [comment]
Tested and verified on candidate build: https://developer.pgadmin.org/builds/2023-09-18-1/
Environment: OSX ventura 13.4.1
