### ISSUE TITLE
Add support for ALTER VIEW ... RENAME COLUMN ... syntax

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#6380]

**Comment by akshay-joshi** [comment]
ALTER TABLE ... RENAME COLUMN works for Views as well, so it's a one-liner change to enable the name field in views.

**Comment by nikhil-mohite** [comment]
Resolved and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-23/
OS: macOS (Sonoma 14.1)
Mode: Desktop
