### ISSUE TITLE
Add "BYPASSRLS|NOBYPASSRLS" option while creating a Role.

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#6392]

**Comment by psztoch** [comment]
SQL tab ignore this flag:
```
CREATE ROLE testrole WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;
```
Add `NOBYPASSRLS` or `BYPASSRLS` at end.

It is bug. Please repair.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-18/
Package: arm64
Environment: macOs Ventura 13.5.1
