### ISSUE TITLE
Add new/missing options to the VACUUM command from v11.

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#6397]
Add the following options:

1. DISABLE_PAGE_SKIPPING,
2. SKIP_LOCKED, 
3. INDEX_CLEANUP, 
4. TRUNCATE, 
5. PROCESS_TOAST, 
6. PARALLEL 
7. PROCESS_MAIN
8. BUFFER_USAGE_LIMIT
9. SKIP_DATABASE_STATS
10. ONLY_DATABASE_STATS

**Comment by FaharAbbasRizvi** [comment]
This is verified on the latest snapshot build on all supported platforms.
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-08-04/
