### ISSUE TITLE
Foreign Table Module new functionality for PG 11 and above (RM #1759)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#640]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1759***
*Originally created by **Karen Blatchley** at 2016-09-27 11:55:51 UTC.*

 New functionality added in PG 11 for this module as below:

- ALTER [ COLUMN ] col_name SET STORAGE { PLAIN | EXTERNAL | EXTENDED | MAIN }
- DISABLE TRIGGER [ trigger_name | ALL | USER ]
- ENABLE TRIGGER [ trigger_name | ALL | USER ]
- ENABLE REPLICA TRIGGER trigger_name
- ENABLE ALWAYS TRIGGER trigger_name
- SET WITH OIDS
- SET WITHOUT OIDS

To add this functionality we need to add Columns, Triggers and Constraints as separate Nodes under the Foreign Table Node.

**Comment by akshay-joshi** [comment]
Found the following issues:
1) Statistics is disabled in edit mode.
2) Only change the datatype of any column from the table dialog. Check MSQL it will create unnecessary syntax for "DROP NOT NULL" and "SET STATISTICS" is shown.
3) Create any foreign table with one column and then open the properties dialog of that table add a new column with the 'bigint' datatype and check the SQL tab, the unnecessary 'NULL' keyword is there. Check the same with the columns properties dialog, syntax is correct.
4) Create any foreign table. Add a new column, set comment, Constraints, Variables, and options, and check the SQL tab. No SQL is visible for the above-mentioned parameters.
5) Unable to change any parameter of the column from the Foreign tables properties dialog. Create any foreign table with one or two columns. Open the properties dialog and go to the columns tab. Try to edit any property of a column like a comment, Constraints, Variables, or Options nothing works.
6) Changing the Type is not working for the normal table as well.
7) Trigger SQL is missing when selecting a foreign table and clicking on the SQL tab.
8) Correct constraint type is not selected for the column when the table's properties dialog is opened.
9) The column's SQL is not correct when selecting any foreign table and clicking on the SQL tab. Create a foreign table with one generated column, check the SQL tab. NULL keyword is added to all the columns.

**Comment by yogeshmahajan-1903** [comment]
> Found the following issues:
> 
> 1. Statistics is disabled in edit mode.
Fixed.

> 2. Only change the datatype of any column from the table dialog. Check MSQL it will create unnecessary syntax for "DROP NOT NULL" and "SET STATISTICS" is shown.
Fixed

> 3. Create any foreign table with one column and then open the properties dialog of that table add a new column with the 'bigint' datatype and check the SQL tab, the unnecessary 'NULL' keyword is there. Check the same with the columns properties dialog, syntax is correct.
It was added intentionally for backward compatibility in 9.4. Now it is not required hence fixed this issue.

> 4. Create any foreign table. Add a new column, set comment, Constraints, Variables, and options, and check the SQL tab. No SQL is visible for the above-mentioned parameters.
Fixed.

> 5. Unable to change any parameter of the column from the Foreign tables properties dialog. Create any foreign table with one or two columns. Open the properties dialog and go to the columns tab. Try to edit any property of a column like a comment, Constraints, Variables, or Options nothing works.
Fixed.

> 6. Changing the Type is not working for the normal table as well.
Not able to reproduce.

> 7. Trigger SQL is missing when selecting a foreign table and clicking on the SQL tab.
Fixed.

> 8. Correct constraint type is not selected for the column when the table's properties dialog is opened.
Fixed.

> 9. The column's SQL is not correct when selecting any foreign table and clicking on the SQL tab. Create a foreign table with one generated column, check the SQL tab. NULL keyword is added to all the columns.
Fixed. Same as point 3.

**Comment by pravesh-sharma** [comment]
Found below issues after testing:-

1. Create a foreign table with a column set constant GENERATED with the expression check SQL tab no SQL visible for constraint.
2. Constraint SQL is not correct in the table SQL tab, but it is correct in the column SQL tab
3. If we change column storage, its SQL is not visible in the table SQL tab.
4. Select a foreign table node and go to Object -> Triggers not option is enabled. The same is working on a normal table (the context menu option for triggers is also not available in the foreign table).

**Comment by pravesh-sharma** [comment]
Tested on the latest source code feature is working as expected and all the issues reported have been fixed.

Env-
OS - macOS Ventura 13.6
Mode - Desktop
