### ISSUE TITLE
Add "USING method" while creating a Materialized View.

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#6400]

**Comment by FaharAbbasRizvi** [comment]
If a user modifies the access method nothing happens, the behaviour should be consistent like the table  
<img width="1318" alt="Screen Shot 2023-09-12 at 5 22 25 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/cef47dff-2fbe-4ee7-9394-2608809b84fe">
<img width="1320" alt="Screen Shot 2023-09-12 at 5 22 45 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/5749d969-f5ff-45f6-9094-f60c54fb130f">

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-09-18/
Environment: MacOs ventura 13.4.1
