### ISSUE TITLE
Backup Object allow select/deselect objects (RM #1761)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#642]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1761***
*Originally created by **Karen Blatchley** at 2016-09-27 11:57:19 UTC.*

Allow to select/deselect objects under the object backup operation.

**Comment by akshay-joshi** [comment]
@nikhil-mohite 

Please look into 

1. --table-and-children >= 16
2. --exclude-table-and-children >= 16
3. --exclude-table-data-and-children >= 16
4. --exclude-table-data >= 11

**Comment by yogeshmahajan-1903** [comment]
Issues found while testing - 
1.When all nodes are collapsed & you select schema node, table node remains partially selected.
<img width="702" alt="Screenshot 2023-09-14 at 2 22 57 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/a20f8421-1b45-4fe2-aebc-3f7cdcec203b">

2.When paren node is expanded continuing to above operation, Child selection is not visible
<img width="748" alt="Screenshot 2023-09-14 at 2 25 06 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/07e0dc12-171a-4b0c-9be9-297a37711507">

3.When I select any child , it scrolls to parent.

**Comment by yogeshmahajan-1903** [comment]
4.Checkbox state is NOT remembered on switch tab. Select some node in Objects tab & switch the tab > Uncheck one of the checkbox, all objects are deflected.

**Comment by yogeshmahajan-1903** [comment]
All issues reported above are resolved.
