### ISSUE TITLE
Function 'Detach Panel' for query tool window fails on second detached window

### ISSUE THREAD

**Issue by riuttner** [pgadmin-org/pgadmin4#6421]
## Description

Under windows10, detaching a query tool window works for the first detached window only: The first detached window appears as floating above of the background and can be used as expected (including executing, moving around by dragging title bar and closing). Any further query tool window existing in the tool background is broken when you try to detach it:

- It is shown as floating, but empty unstructured area. At least the title bar is taken correctly as it was before detaching.
- The window can be resized and moved, but does not show any content.
- Even the close button does not work (nothing happens).

## Steps to reproduce the behavior

1. Open PgAdmin in standard layout and log in.
2. Create 2 query tools and add some contents to them.
3. Execute menu function `Detach Panel` for first query tool by mouse context menu (right click) on tool tab. The behaviour is as expected.
4. Detach the second query tool by same mouse context menu action. The window is detached, but does not show any structure or content and cannot be closed by 'X' button.

## Expected behaviour

All detached query tool windows should be created in a way like the very first one and stay usable.

## Desktop

Data reported by `Help -> About pgadmin4`:

Version
7.3
Application Mode
Desktop
NW.js Version
0.76.1
Browser
Chromium 113.0.5672.64
Operating System
Windows-10-10.0.19045-SP0

**Comment by adityatoshniwal** [comment]
The layout system is completely changed from v8.0. This bug is not relevant/reproducible anymore and it is recommended to upgrade to latest.

Closing this.
