### ISSUE TITLE
Clarify License Information: pgAdmin 4 is released under the PostgreSQL Licence

### ISSUE THREAD

**Issue by djkazunoko** [pgadmin-org/pgadmin4#6423]
It is hard to tell that pgAdmin4 is a PostgreSQL Licence by reading the following LICENSE file.
https://github.com/pgadmin-org/pgadmin4/blob/master/LICENSE

I suggest that you modify the license information as follows.

```diff
pgAdmin 4

Copyright (C) 2013 - 2023, The pgAdmin Development Team
+ This software is released under the PostgreSQL licence.
```

Additional text was taken from the Dockerfile and Makefile.

**Comment by adityatoshniwal** [comment]
@dpage  What do you think on this?
