### ISSUE TITLE
No connect existing server connection and no modal window prompt for password

### ISSUE THREAD

**Issue by hugbe8** [pgadmin-org/pgadmin4#6424]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
No modal window prompt for password and no connect existing server connection.
Only the fresh server creatly can open. After disconnect the server connect is no longer fonctionnal.
Visually the entity in the left pane related to the server is flashing and not opening.

I rolled back to version 7.2 and the server connect works fine.

**To Reproduce**

**Expected behavior**
Be able to open a server and enter the password, on a server previously created with valid parameters.

**Error message**
No error message on log

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Version: 7.3
 - Mode: Desktop
 - Browser; n/a
 - Package type: deb

**Additional context**

**Comment by adityatoshniwal** [comment]
Hi @hugbe8,

Can you share some screenshot or screen recording?

**Comment by nikhil-mohite** [comment]
No response from the author, closing it

**Comment by hugbe8** [comment]
Sorry for not being able to answer your questions at time.
The problem is still present under version 7.8, here is an image as requested.

![image](https://github.com/pgadmin-org/pgadmin4/assets/1155637/ea56926a-15c3-4ceb-8eb2-41f09adb1a9c)

[Capture vidéo du 2023-11-01 14-05-33.webm](https://github.com/pgadmin-org/pgadmin4/assets/1155637/831f9222-4af4-4444-bd7b-0b97de4deb59)

**Comment by nikhil-mohite** [comment]
Hi @hugbe8 ,

Can you please share pgadmin logs from `File-> Runtime -> View Log`

**Comment by pravesh-sharma** [comment]
No response from the author, closing.
