### ISSUE TITLE
Pgadmin4 installation problems

### ISSUE THREAD

**Issue by ddw256** [pgadmin-org/pgadmin4#6425]
By blindly following scripts, I have been successful in installing Postgresql14 and have been able to access it via psql.
I have been totally unsuccessful in doing the same with pgadmin4. I get to the part to invoke Firefox and connect to localhost:5000, when it bombs out. 
from bash:
pgadmin4
Starting pgAdmin 4. Please navigate to http://127.0.0.1:5050 in your browser.
2023-06-11 22:51:55,970: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance.
 * Serving Flask app 'pgadmin'
 * Debug mode: off

I am running Linux Mint 21.1 on a Lenovo laptop T450 with an Intel processor, using Firefox 114.
I have been following the lack of progress of my more knowledgeable buddy who subsequently changed to Mariadb .
Help Please?

**Comment by khushboovashi** [comment]
Hi @ddw256,

Which script did you follow?
Send the error logs. Refer to https://www.pgadmin.org/faq/#8 to enable logging.

**Comment by nikhil-mohite** [comment]
No response from author, closing it
