### ISSUE TITLE
ERD tool fails to draw some relations in downloaded image

### ISSUE THREAD

**Issue by javinosearas** [pgadmin-org/pgadmin4#6429]
When downloading this design  [db-schema-v0.5.1.pgerd.zip](https://github.com/pgadmin-org/pgadmin4/files/11720097/db-schema-v0.5.1.pgerd.zip) from the ERD tool as an image it fails to draw some of the relations. This is illustrated by the two images below:

This one is generated by the ERD tool:
![db-schema-v0 5 1 pgerd](https://github.com/pgadmin-org/pgadmin4/assets/130481552/96f5f8f4-6d1c-4a80-bae2-8e6e5ed61269)

This one is a screenshot of the ERD tool:
![db-schema-v0 5 1 pgerd-screenshot](https://github.com/pgadmin-org/pgadmin4/assets/130481552/15aacd55-5a39-44e1-b042-f3beb03001fd)

As you can see some lines are missing. It looks like there is a limitation in the x and y coordinates for where it will draw the relation lines. Have tried to move some elements around and then the lines that are moved inside the 'invisible' border appears on the output.

Currently using pgadmin 4 v7..3  but the same problem is present also in earlier versions.

|Version details| |
|---|---|
| Version |  7.3 |
| Application Mode | Desktop |
| Current User | pgadmin4@pgadmin.org |
| NW.js Version | 0.76.1 |
| Browser | Chromium 113.0.5672.64 |
| Operating System | Windows-10-10.0.22621-SP0 |

**Comment by adityatoshniwal** [comment]
Duplicates #4995.
