### ISSUE TITLE
PSQL not working if the database name have ' and ".

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#6431]

**Comment by FaharAbbasRizvi** [comment]
I have tested with all special characters and no issue is found during verification on the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-14/

**Comment by adityatoshniwal** [comment]
Fixed with commit https://github.com/pgadmin-org/pgadmin4/commit/4746fbd34674574bec09113d0240618301fdcebf
