### ISSUE TITLE
Update app bundle built to use notarytool instead of altool

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#6441]
Per Apple:

> We’re reaching out because you recently used the altool command-line utility to notarize your macOS software with Apple. As announced last year at [WWDC22](https://developer.apple.com/videos/play/wwdc2022/10109), if you’re still using altool with the Apple notary service, you should transition to the notarytool command-line utility as soon as possible. Notarizing software with altool was deprecated in Xcode 13, and the Apple notary service will no longer accept uploads from altool as of November 1, 2023. Existing notarized software will continue to function properly. 
> 
> For information on notarizing your apps, read [TechNote TN3147: Migrating to the latest notarization tool](https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool?changes=_3_3).

Note that notarytool also has a --wait option that can replace our current polling for results.

**Comment by scottt** [comment]
I think this has been resolved by @akshay-joshi  in PR #6919.

**Comment by akshay-joshi** [comment]
Yes
