### ISSUE TITLE
Unable to complete installation on Windows

### ISSUE THREAD

**Issue by linda-metcalfe** [pgadmin-org/pgadmin4#6442]
I tried versions 6.21 and 7.3 and have the same issues with both installations.  pgAdmin 4

1.  Selected the 'install for me' option
2.  Clicking the Next button on the Welcome screen does nothing.  The only way to navigate past this screen is to use the Enter key.
3. Once I get to the License agreement page, it's impossible to select the 'I accept the agreement' radio button even after scrolling thru the entire license agreement.  So there is no way to complete the installation.
4. Clicking the Back button on the license agreement page also does nothing.
5. Clicking the Cancel button on the license agreement page also does nothing.

Windows 10 Enterprise, Desktop
Version 10.0.19045

**Comment by adityatoshniwal** [comment]
@linda-metcalfe This seems to be very rare, none of the users faced such an issue. Can you please share the screen recording to help us understand?

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing ticket.
