### ISSUE TITLE
v7.2+ fails to launch: procedure entry point DiscardVirtualMemory could not be located

### ISSUE THREAD

**Issue by azlconsulting** [pgadmin-org/pgadmin4#6444]
pgAdmin v7.2 and v7.3 both fail to launch with the screenshotted error.

Uninstalling and re-installed pgAdmin v7.1 launches without a problem.

![image](https://github.com/pgadmin-org/pgadmin4/assets/66295979/6d5812df-3c94-40d2-b749-cd903d108cdd)

- Windows Server 2012 R2 Standard 64-bit
- Downloaded from https://www.pgadmin.org/download/pgadmin-4-windows/
- Installed for all users to C:\Program Files\pgAdmin

**Comment by adityatoshniwal** [comment]
@azlconsulting,
Per https://www.pgadmin.org/download/pgadmin-4-windows/, Window Server 2012 is not supported.
