### ISSUE TITLE
MAINTAIN privilege should be added while creating new privileges for the grant option

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6445]
MAINTAIN privilege should be added while creating new privileges for the grant option and it also should be visible on the security tab under the privileges section for the created object.

**Comment by FaharAbbasRizvi** [comment]
PG/EPAS 16.

**Comment by akshay-joshi** [comment]
Feature has been reverted and not available in PG 16
