### ISSUE TITLE
CREATE TABLE ... STORAGE ... syntax should be added while creating table

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6450]
Version:
PG/EPAS 16

CREATE TABLE ... STORAGE ... syntax should be added while creating table

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-31/
Environment: macOs Ventura 13.5.1
Package:arm64
