### ISSUE TITLE
VACCUM (Maintainence): Add PROCESS_MAIN, BUFFER_USAGE_LIMIT, SKIP_DATABASE_STATS and ONLY_DATABASE_STATS

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6453]
Add PROCESS_MAIN, BUFFER_USAGE_LIMIT, SKIP_DATABASE_STATS and ONLY_DATABASE_STATS

Version:
PG/EPAS 16

**Comment by akshay-joshi** [comment]
Will be implemented as part of #6397
