### ISSUE TITLE
SchemaDiff Tool is throwing "more than one row returned by a subquery used as an expression" error.

### ISSUE THREAD

**Issue by naveenjul29** [pgadmin-org/pgadmin4#6462]
SchemaDiff Tool is throwing "more than one row returned by a subquery used as an expression" error when comparing two databases.

**Comment by naveenjul29** [comment]
attaching the screenshot for your reference

![image](https://github.com/pgadmin-org/pgadmin4/assets/67134199/99404d6f-9cf8-4c1f-8bb8-3bffe6c029f7)

**Comment by akshay-joshi** [comment]
@naveenjul29 

Can you please identify and provide the DDL for which objects it is failing? Also, provide the logs pgAdmin4 -> Runtime -> View log...

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing ticket.
