### ISSUE TITLE
Tooltip in Object Explorer Stuck Open

### ISSUE THREAD

**Issue by anthonydb** [pgadmin-org/pgadmin4#6463]
I have been adding servers to a new install of pgAdmin, and while doing so I apparently hovered over something that triggered a tooltip. That tooltip is now stuck in view with no way to dismiss it aside from Reset Layout.

<img width="400" alt="Screenshot 2023-06-16 at 9 23 32 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/273891/27c5a92e-1f26-490e-bfd2-3d14ae85f48f">

**To Reproduce**

I'm not entirely sure -- I was adding servers and clicking in that area of the UI.

**Expected behavior**

A tooltip should disappear when mouse moves elsewhere.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4
 - Version: 7.3
 - Mode: Desktop

**Comment by adityatoshniwal** [comment]
This is fixed with latest version.
