### ISSUE TITLE
FK not taken into account on DROP AND CREATE order of autogenerated SQL scripts from ERD tool

### ISSUE THREAD

**Issue by plpagadorfdez** [pgadmin-org/pgadmin4#6465]
Hi.

I'm using the ERD tool in pgadmin 4 for designing a datamodel where some relations have foreign keys (FK) referencing other relations. I marked the option "With DROP Table" next to the "Generate SQL" button to be able to recreate (update) the database everytime I modify something, but the order of the DROPs and CREATEs in the autogenerated script returns an error because of FK between relations.

In the screenshots attached, you can see one example of a table with a FK to the main "signals" table.

![2023-06-18 19_48_59-pgAdmin4_erdtool_fkexample](https://github.com/pgadmin-org/pgadmin4/assets/121381953/8ae11e71-f2c8-4d76-91a3-e32d76468768)

However, in the autogenerated script the "signals" table is the first one to be dropped and created.

![2023-06-18 19_49_27-pgAdmin4_autogenerated_script](https://github.com/pgadmin-org/pgadmin4/assets/121381953/1b2bc18d-c92d-4e08-a2ce-eaee259db872)

This cause the following error when running (there are a bunch of other FK to that "signals" table):

```
ERROR:  constraint fk_signalAssetJoin_signalid on table "signalAssetJoin" depends on table signals
constraint fk_rtData_signalid on table "rtData" depends on table signals
constraint fk_mqtt_signals_signalid on table mqtt_signals depends on table signals
constraint fk_modbus_signals_signalid on table modbus_signals depends on table signalscannot drop table signals because other objects depend on it
```

The autogenerated script should be starting from the non-referenced tables, then so on "in cascade" (let's say the new non-referenced tables). Thanks!

Best regards!

**Comment by adityatoshniwal** [comment]
this is fixed with #5770
