### ISSUE TITLE
Unable to connect to server: connection timeout expired

### ISSUE THREAD

**Issue by dtarakanova** [pgadmin-org/pgadmin4#6467]
**Describe the bug**

Hello, adding new server causes message: Unable to connect to server: connection timeout expired
Firewall is off. Password is correct

**To Reproduce**

1. Go to pgAdmin -> Add new Server -> fill in the form like on the screenshots attached
2. Press Save 

**Expected behavior**

Expected - server creation without any issues

**Error message**

Unable to connect to server: connection timeout expired

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/108654168/fa51c089-f4c8-4df9-8624-179f01eb14be)
![image](https://github.com/pgadmin-org/pgadmin4/assets/108654168/6fb9f77f-84a4-4276-b750-0fe92b5d484a)

**Desktop (please complete the following information):**
 - Windows 11, version 22H2
 - PgAdmin Version: 7.3
 - Mode: Desktop
 - Package type: Windows

**Comment by adityatoshniwal** [comment]
HI @dtarakanova,
Looks like your server is not reachable. Please check all server details are valid or may be try connecting with psql once.

**Comment by Wingto** [comment]
I met timeout as well, and i install it again and again, it's still timeout..

![Uploading image.png…]()

**Comment by yogeshmahajan-1903** [comment]
@Wingto 
Looks like your server is not reachable. Please check all server details are valid or may be try connecting with psql once.

**Comment by andrey-helldar** [comment]
UPD: In my case, the problem was an IP subnet conflict. A docker container is available on the local network with the same subnet that pgAdmin created.

Solutions two:

1. Recreate and connect the subnet until the issued address does not conflict;
2. Change the pool of addresses issued by the docker.

### Solution 1
```bash
docker network rm dev_dev
docker network create dev_dev
docker network connect dev_dev dev-pgadmin-1
```
Cons: needs to be done every time a conflict occurs.

### Solution 2

Unix:
```bash
nano /etc/docker/daemon.json
```

Windows:
```bash
%USERPROFILE%\.docker\daemon.json
```

Or using a Docker Desktop > Settings > Docker Engine:
![image](https://github.com/pgadmin-org/pgadmin4/assets/10347617/4874faf5-5e76-462a-a1aa-a3b3f94e08f9)

Adding an address pooll:
```json
{
  "default-address-pools":[
    {"base":"10.66.0.0/16","size":24},
    {"base":"10.77.0.0/16","size":24}
  ]
}
```
And once we create a network:
```bash
docker network rm dev_dev
docker network create dev_dev
docker network connect dev_dev dev-pgadmin-1
```

**Comment by anilsahoo20** [comment]
No response from author, hence closing it.

**Comment by Abdelrhman-Samir-99** [comment]
Hello, I had the same issue and it turned out that I had to install PostgreSQL as well.
You can find it here: https://www.postgresql.org/download

**Comment by Abdelrhman-Samir-99** [comment]
And basically, the issue I had is that pgAdming trying to connect to something that does not exist, that's why it was timing out.

**Comment by optonpo** [comment]
i've spent hours repeating about 10 possible solutions to this problem. Glad to see so many others have the same issue.

**Comment by optonpo** [comment]
> No response from author, hence closing it.

This drives me insane. Closed is closed. Unanswered ≠ closed. Unanswered==the author has likely found more luck searching Youtube for a workaround. Or better yet, spent days learning a solution AND building a video to show others. Bless the "non responders."

**Comment by OnlyTs** [comment]
> HI @dtarakanova, Looks like your server is not reachable. Please check all server details are valid or may be try connecting with psql once.

How to make it reachable?

**Comment by syedfarhan-596** [comment]
> HI @dtarakanova, Looks like your server is not reachable. Please check all server details are valid or may be try connecting with psql once.

May be changing the port (data/postgresql.conf) to something else would work  in my case it worked

**Comment by specialprocedures** [comment]
I came here before remembering I'd set up IP-based access limits, and needed to enable SSH tunneling.

**Comment by nvdovin** [comment]
I have same issue, guys. What have I do to fix it?!

**Comment by s1139341TimDeRuijter** [comment]
i had the same issue. this is the fix: Go to services and find postgresql and hit start. 
![image](https://github.com/pgadmin-org/pgadmin4/assets/146927941/81a0af89-6432-4eb7-b361-51c888101209)

**Comment by nvdovin** [comment]
Guys, is it actual for now?
I fix my issue with it! let me show how I did it!
You have to edit your "pg_hba.conf" file. Change peer on md5 in it...
It really helps me

**Comment by madhurydv** [comment]
Hey can you please elaborate what changes you made in "pg_hba.conf" file i am facing the same issue i tried reinstalling many times but nothing worked. my server runs properly and i tried running it on SQL shell(psql) and it was running without a problem. it only causes issues when i try to run it on the pgAdmin i enter the password and it says "connection timeout expired"

**Comment by nvdovin** [comment]
> Hey can you please elaborate what changes you made in "pg_hba.conf" file i am facing the same issue i tried reinstalling many times but nothing worked. my server runs properly and i tried running it on SQL shell(psql) and it was running without a problem. it only causes issues when i try to run it on the pgAdmin i enter the password and it says "connection timeout expired"

Sure, look:
I found my config file by path:

`/etc/postgresql/<your postgresql version>/main` 

After it I've open it by sudo _(because common user haven't permissions to open and chage it)_ by

`sudo vim pg_hba.conf`

And, surely, we have to change some parts in this file (changes on the screeshot)

_Everywhere, where you see md5_

![image](https://github.com/pgadmin-org/pgadmin4/assets/124635282/8e7200c3-be72-482e-95bc-b60db052886f)

**Comment by nvdovin** [comment]
Sorry, bro.
I just saw your reply. Look, I showed all in topic

**Comment by ericthomas1** [comment]
This error also occurs when trying to connect, from behind a VPN, to an Azure Database for PostgreSQL. So...what is the fix in this case?

**Comment by kalluu-ck** [comment]
In my case, I need to do these 3 steps on the server to open the connection (from local pgAdmin4 to PostgreSQL in Windows Server):

- C:\Program Files\PostgreSQL\<version>\data\postgresql.conf
=> Set `listen_addresses = '*'`

- C:\Program Files\PostgreSQL\<version>\data\pg_hba.conf
=> Add to the bottom this line: `host    all             all             0.0.0.0/0               md5`
 
- Open **Open Windows Defender Firewall with Advanced Security** and create new **Inbound Rule** to allow access on port 5432 for TCP protocol

**Comment by uazure** [comment]
I'm experiencing the same issue in the following config:
windows client. tried versions of pgadmin 9.9, 9.5, 8.14
Connected via vpn (pritunl) to aws. Ensured that TCP connection to database host on 5432 establishes. Checked via wireshark for the traffic on the vpn's virtual interface, I see that client and server exchange some packets, but after a default timeout of 10 seconds I get the error that connection timeout expired.

The rest of my colleagues doesn't have issues with connecting pgadmin (on mac and on windows) to the same server with same creds and same vpn tunnel.
