### ISSUE TITLE
Add checkbox "IF EXISTS" to "DROP" switch in Backup Dialog

### ISSUE THREAD

**Issue by Bartaty** [pgadmin-org/pgadmin4#6478]
Version: 7.1

When I create plain backup with switch "**Include DROP DATABASE statement**" (Backup Dialog > Options tab > Queries field box) it's include DROP lines to .sql file, but importing works only on same DB. If I import this backup to empty or other DB, process failed because some schemas/views/tables etc. does non exist.

In this case I need to use **--if-exists** flag to create backup in command line.

Please add checkbox "**IF EXISTS**" around switch "**Include DROP DATABASE statement**"

**Comment by akshay-joshi** [comment]
Will be taken care of as a part of #6417
