### ISSUE TITLE
The message "Current database has been moved or renamed to ". Click on the OK button to refresh the database name." is displayed if the user tries to debug on the database containing single and double quotes

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6482]
The message "Current database has been moved or renamed to ". Click on the OK button to refresh the database name." is displayed if the user tries to debug on the database containing single and double quotes. However, the user did not rename or moved such kind of database.

**To Reproduce**

1. create the following database
CREATE DATABASE """"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
2. create the following extension and function in the above database
 CREATE EXTENSION pldbgapi;

CREATE FUNCTION public.a_pgadmin4()
    RETURNS "char"
    LANGUAGE 'plpgsql'
   
AS $BODY$
begin
return 1;
end;
$BODY$;

ALTER FUNCTION public.a_pgadmin4()
    OWNER TO postgres;
3. extension and function created
4. Go to the newly created function and Right Click on Debugging and Debug
5. Pop-up message displayed:(See the error)
6. Current database has been moved or renamed to ". Click on the OK button to refresh the database name.

**Expected behavior**

Debugger should be working fine without any unexpected message

**Screenshots**
<img width="1012" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/a65a3d80-d733-4241-858c-b14f2c633b15">

**Desktop (please complete the following information):**
 - OS: [ALL]
 - Version: [7.3]
 - Mode: [e.g Desktop or Server]
 - Package type: [ALL]

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on latest snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-09-29/)

Env-
OS - macOS 13.6 (Ventura)
Mode - Desktop
