### ISSUE TITLE
Natively Support Azure AD Authentication

### ISSUE THREAD

**Issue by grh-ericcsinger** [pgadmin-org/pgadmin4#6486]
**Describe the solution you'd like**
Full support for AzureAD authentication when connecting to a server, with automatic token refresh.

**Describe alternatives you've considered**

Right now, the only way to utilize Azure AD authentication, is by manually generating an AD token and connecting to a server with that token.  While it works, Microsoft token lifetime is only 1 hour, which makes it very difficult to be productive and leverage AzureAD authentication.

**Comment by adityatoshniwal** [comment]
Hi @grh-ericcsinger,
Did you try Password Exec which was introduced with https://github.com/pgadmin-org/pgadmin4/pull/5430?
Please check https://www.pgadmin.org/docs/pgadmin4/7.3/server_dialog.html how to configure Password Exec Command and Expiration.

**Comment by grh-ericcsinger** [comment]
it's funny you mention that.  I just discovered that and have it working reasonably well late last night.  However, I kind of feel like that is a work around or an alternative, but not really a solution.  I would still see a lot of value in a native authentication option.

**Comment by nikhil-mohite** [comment]
There is no plan to natively support Azure Ad authentication.

**Comment by sirTangale** [comment]
why would azure even bother they are trying to self promote managed services over self hosted

**Comment by skel0** [comment]
Hi,

Password Exec Command and Expiration are settings only enabled for pgAdmin desktop. Is there any workaround for pgAdmin server? 

Is there any chance to get "token refresh" for Azure AD implemented in the pgAdmin server to connect to PostgreSQL servers? Is it possible to request this enhancement?


Thanks!
