### ISSUE TITLE
Database connection should be restored in query tool if user drop and re-create database with same name

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#6487]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Connection to the database with the database should be restored.

**To Reproduce**

1. Create database 'test_db1'
2. open query tool for the newly created database
3. now execute some queries
4. Now delete the 'table_db1' (Delete form database collection node using  Delete(Force)) option
5. Re-create the database with the same name 'test_db1'
6. Now try to execute the query in the already opened query tool 
7. It shows an error in Messaged Tab: 
<img width="992" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/69510038/dc0e955f-1e75-48fc-b4c0-6ecb226c9ad9">

**Expected behavior**

Query should be fet executed without any error

**Desktop (please complete the following information):**
 - OS: macOS (Ventura 13.3)
 - Version: V-7.3
 - Mode: Desktop

**Comment by pravesh-sharma** [comment]
Issue fixed.
