### ISSUE TITLE
Database name is missing in notification message if database name contains special characters

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#6488]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Database name is missing in notification message if database name contains special characters

**To Reproduce**

1. Create Database with name <script>alert('Hi')</script>
2. Open query tool for same database node.
3. Try to delete it from the context menu using the "Delete" option and click on OK to delete the database.
4. It shows an error unable to delete the database as other sessions using it, check it is showing double quotes("") instead of the database name.
<img width="678" alt="Screenshot 2023-06-21 at 3 14 48 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/69510038/c7cbf921-059b-4d8b-99f0-d17504029f1c">

5. If we try the same steps with the database name without special characters it is working fine.

**Expected behavior**

It should show the database name instead of just double quotes ("")

**Desktop (please complete the following information):**
 - OS: macOS (Ventura 13.3)
 - Version: 7.13
 - Mode: Desktop

**Comment by anilsahoo20** [comment]
While testing for the above issue please test the below issue:
1. Query tool with active transaction going on and the options in preferences for query tool like auto commit, prompt to show rollback/commit dialog, save query change dialog with either ON/OFF and try to close the panel, it will show a dialog for `Close query tool?`

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-08/

Env - 
OS - macOS 14.1.1 (Sonoma)
Mode - Desktop
