### ISSUE TITLE
Distribute macOS application for Apple M1 (arm64)

### ISSUE THREAD

**Issue by jwosty** [pgadmin-org/pgadmin4#6496]
**Describe the solution you'd like**

Currently, you only offer an x86-64 Mac application, which can indeed run on an Apple M1 machine, but it would be nice to be able to install an app compiled for M1. I see there is already an arm64 Docker image, so it sounds like it should be possible.

**Describe alternatives you've considered**

* Just run the macOS x86_64 app (what I've been doing)
* Use the arm64 docker image

**Comment by adityatoshniwal** [comment]
Duplicates #4888.
