### ISSUE TITLE
Cannot backup a database if pgpass file is used

### ISSUE THREAD

**Issue by ViliusS** [pgadmin-org/pgadmin4#6499]
**Describe the bug**

If pgAdmin connection is configured to use pgpass to connect to the database the backup via GUI fails.

**To Reproduce**

1. Create pgAdmin server which uses `passfile` connection parameter.
2. Right click on any database and choose 'Backup'.
3. Backup will fail with an error that there is no password supplied.

**Expected behavior**

Backup should not fail.

**Error message**

```
pg_dump: [archiver (db)] connection to database "db" failed: connection to server at "postgresql" (10.99.212.240), port 5432 failed: fe_sendauth: no password supplied
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 7.0
 - Mode: Server
 - Package type: Container

**Comment by nikhil-mohite** [comment]
All env variables should be set in `process.py` so it will work for all tools

**Comment by akshay-joshi** [comment]
Please test Backup, Restore, Maintenance, Import Export Data, Refresh MView with this issue

**Comment by pravesh-sharma** [comment]
Issue fixed  verified on latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-12/

**Comment by nikelborm** [comment]
Maybe related:
https://github.com/pgadmin-org/pgadmin4/issues/6741#issuecomment-1722212595
