### ISSUE TITLE
Query Tool widow goes blank if user try to generate graph on result.

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#6500]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

If the user tries to generate Line Chart or any other graph Query tool window goes blank

**To Reproduce**

1. Open the Query tool for any database containing a few tables
2. Execute the select query on a table containing a few records (The table should contain the primary key as we need to add a few records and one, not null column)
3. Now add a record on UI using the `Add row` option, keep not-null fields null
4. Click on save, it will show an error `violates not-null constraints`
5. Now go to the `Graph Visualiser` tab and select `X Axis` and `Y Axis`
6. Click on the `Generate` button
7. Now check whole Query tool window goes blank and you can’t perform any operations, closing the query tool window is also not working.
8. Need to use `Rest Layout` to close opened Query Tool window

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

getting the following error in the browser console
<img width="500" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/69510038/45b46efa-f809-4cda-a260-c1f0b6065234">

**Desktop (please complete the following information):**
 - OS:  macOS (Ventura 13.3)
 - Version: 7.3
 - Mode: Both
 - Browser (if running in server mode): Chrome

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
