### ISSUE TITLE
Query tool auto-complete is not working after server reconnect

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#6501]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

The query tool auto-complete is not working after reconnect

**To Reproduce**

1. Open Query Tool and execute some queries.
2. Disconnect and reconnect the server from Object Explorer
3. Now on the previously opened query tool check auto-complete is not working.
4. It will show some cached data but try different queries with different schema.
5. Also check the API call it always returns empty values
(Query tool is working fine user can execute the queries, only auto complete is not working)

**Expected behavior**

It should work after reconnecting to the server.

**Desktop (please complete the following information):**
 - OS: macOS (Ventura 13.3)
 - Version: 
 - Mode: Both

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-05/
