### ISSUE TITLE
Query tool restore connection fails

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#6502]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

The query tool is unable to restore the connection

**To Reproduce**

1. Open the Query tool
2. execute some queries 
3. Disconnect the server from the object explorer
4. Try to execute a query on an already opened Query Tool
5. It shows a connection dialog to create a new session
![image](https://github.com/pgadmin-org/pgadmin4/assets/69510038/d079ef1e-a515-46a8-81b9-d5dd873518d7)
6. Click on `Connect` and check it shows an error in the Query tool `Messages` tab 
<img width="1026" alt="Screenshot 2023-06-26 at 4 27 03 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/69510038/7447fd9c-e4e6-48d8-9d9f-06023e2b8b83">
7. Query tool unable to restore the connection
(Note: If the user connects to the server from `Object Explore` then it is able to restore the connection)

**Expected behavior**

connection to the server should be restored in a new session

**Desktop (please complete the following information):**
 - OS: macOS (Ventura 13.3)
 - Version: [e.g. 6.15]
 - Mode: Both

**Comment by khushboovashi** [comment]
@nikhil-mohite, if the password is stored, it should re-connect as per our old behaviour, but it will not if the password is not set for that server.

**Comment by khushboovashi** [comment]
The original behaviour is fixed as per my comment. It will be not connected if it is disconnected from browser tree.

**Comment by anilsahoo20** [comment]
The scenarios that are fixed for query tool are,

1. Server password->Saved->Maintenance DB->Execute query,Execute script, Explain, Explain analyze, Macro, Update connection, New connection, Open query tool in a new tab
2. Server password->Not Saved->Maintenance DB->Execute query,Execute script, Explain, Explain analyze, Update connection, New connection, Open query tool in a new tab
3. Server password->Saved->Other DB->Execute query,Execute script, Explain, Explain analyze, Macro, Update connection, New connection, Open query tool in a new tab
4. Server password->Not Saved->Other DB->Execute query,Execute script, Explain, Explain analyze, Update connection, New connection, Open query tool in a new tab
5. SSH Tunnel->Tunnel password->Server password->Saved->Maintenance DB->Execute query,Execute script, Explain, Explain analyze, Macro, Update connection, New connection, Open query tool in a new tab
6. SSH Tunnel->Tunnel password->Server password->Not Saved->Maintenance DB->Execute query,Execute script, Explain, Explain analyze, Update connection, New connection, Open query tool in a new tab
7. SSH Tunnel->Tunnel password->Server password->Saved->Other DB->Execute query,Execute script, Explain, Explain analyze, Macro, Update connection, New connection, Open query tool in a new tab
8. SSH Tunnel->Tunnel password->Server password->Not Saved->Other DB->Execute query,Execute script, Explain, Explain analyze, Update connection, New connection, Open query tool in a new tab
9. SSH Tunnel->Identity file->Server password->Saved->Maintenance DB->Execute query,Execute script, Explain, Explain analyze, Macro, Update connection, New connection, Open query tool in a new tab
10. SSH Tunnel->Identity file->Server password->Not Saved->Maintenance DB->Execute query,Execute script, Explain, Explain analyze, Update connection, New connection, Open query tool in a new tab
11. SSH Tunnel->Identity file->Server password->Saved->Other DB->Execute query,Execute script, Explain, Explain analyze, Macro, Update connection, New connection, Open query tool in a new tab
12. SSH Tunnel->Identity file->Server password->Not Saved->Other DB->Execute query,Execute script, Explain, Explain analyze, Update connection, New connection, Open query tool in a new tab
13. Server password->Password file->Other DB->Execute query,Execute script, Explain, Explain analyze, Update connection, New connection, Open query tool in a new tab
14. Server password->Password file->Maintenance DB->Execute query,Execute script, Explain, Explain analyze, Update connection, New connection, Open query tool in a new tab

The scenarios that are fixed for view/edit data tool are,
All the above scenarios with execute script button of View/Edit tool.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on latest snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-09-16/).

Env:
OS - macOS Sonoma (14.6.1)
Mode - Desktop

**Comment by pravesh-sharma** [comment]
Tested on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-09-19/) and the issue is fixed.
