### ISSUE TITLE
pgAdmin4 crashes if long query is already running and the user want to disconnect from Server

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6508]
pgAdmin4 crashes if the long query is already running and the user wants to disconnect from server. The user has to restart the pgadmin4.

**To Reproduce**

1. Go to query tool Windows and execute following query:

SELECT(
  SELECT concat_ws(' ',name_first, name_last) as generated
  FROM (
    SELECT string_agg(x,'')
    FROM (
      select start_arr[ 1 + ( (random() * 25)::int) % 16 ]
      FROM
      (
        select '{CO,GE,FOR,SO,CO,GIM,SE,CO,GE,CA,FRA,GEC,GE,GA,FRO,GIP}'::text[] as start_arr
      ) syllarr,
      -- need 3 syllabes, and force generator interpretation with the '*0' (else 3 same syllabes)
      generate_series(1, 3 + (generator*0))
    ) AS comp3syl(x)
  ) AS comp_name_1st(name_first),
  (
    SELECT x[ 1 + ( (random() * 25)::int) % 14 ]
    FROM (
      select '{Ltd,& Co,SARL,SA,Gmbh,United,Brothers,& Sons,International,Ext,Worldwide,Global,2000,3000}'::text[]
    ) AS z2(x)
  ) AS comp_name_last(name_last)
  )
FROM generate_series(1,10000000) as generator
2. Execution of query started
3. Now Disconnect the server:
4. The following message is displayed:
Connection to pgAdmin server has been lostConnection to pgAdmin server has been lost
5. Now try to connect server
6. Connection to the server has been lost
7. Now user has to restart the pgAdmin4

**Expected behavior**

If Any query is running and Disconnect the server then pgAdmin4 should behaviour properly

**Screenshots**
<img width="1261" alt="Screen Shot 2023-06-28 at 7 06 32 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/6edf83dd-f8c5-499d-83a0-e16b8107f039">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 7.4]
 - Mode: [e.g Desktop or Server]
 - Package type: [All]

**Additional context**

**Comment by FaharAbbasRizvi** [comment]
@khushboovashi 

Issue is still  reproducible on the latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-05/

**Comment by khushboovashi** [comment]
This issue is reproducible only on MacOS and with some queries. 
I don't think we can do much about this: Ref: https://bugs.python.org/issue44869

**Comment by Adventurer2021** [comment]
In my case, I wouldn't say "user wants to disconnect". In fact, when running a simple query on my system "select * from table" where my table is 8M records, pgAdmin 7.4 disconnects from the server. I had to reinstall pgAdmin 7.3 to get that query to run. 
Not sure why the title is "user wants to disconnect". This user certainly does NOT "want the pgAdmin to disconnect". It should be reworded to "pgAdmin V7.4 crashes when querying large tables". Unless of course my symptoms are different issue from the original report in this issue. 

pgAdmin about reports (before rolling back to V7.3):
pgAdmin: Version 7.4
Application Mode: Desktop
Current User: pgadmin4@pgadmin.org
NW.js Version: 0.77.0
Browser: Chromium 114.0.5735.91
Operating System: Windows-10-10.0.22621-SP0
DB: postgresql V15.3

Windows reports:
OS Name: Microsoft Windows 11 Pro
Version: 10.0.22621 Build 22621

**Comment by khushboovashi** [comment]
@Adventurer2021, try the latest snapshot build, https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-12/
The issue you mentioned is fixed.

**Comment by Adventurer2021** [comment]
That worked! Thanks!
