### ISSUE TITLE
Serious bug: changes made to wrong database

### ISSUE THREAD

**Issue by NessBird** [pgadmin-org/pgadmin4#6511]
Steps I followed. (I don't want to try to reproduce this, I'm afraid of what will happen, but I bet you can reproduce it easily enough.) I was following an established routine for copying my production database to a dev copy.

1. Delete DB **d2**. (I assume this isn't relevant, but I include it for completeness.)
2. Rename DB **development** to: **d2** using property dialog.
3. Copy DB **people_can_program** (the production DB) to **development**. This took several minutes.
4. Opened a Query Tool window from **development**. (It was definitely that one, it is still open now, and you can see it in the attached graphic.)
5. Ran SQL code: ALTER TABLE t_section_stage_avail RENAME TO jt_section_stage;
ALTER TABLE jt_section_stage RENAME COLUMN avail_date TO available_default_time;

Result: No changes to **development**. No changes to **people_can_program**. The requested changes were made to **d2**, despite the fact that I definitely requested they be made to **development**. While I was figuring out what happened, I tried running the changes again, and got the result indicated by the attached graphic. (ERROR:  relation "t_section_stage_avail" does not exist)
![changes_to_wrong_db](https://github.com/pgadmin-org/pgadmin4/assets/1731013/73105ab9-a6b9-4049-afcb-28aab7d83e4f)

Thanks for making pgadmin, it's a great system.

Ness

**Comment by adityatoshniwal** [comment]
Hi @NessBird,
This partially looks related to https://github.com/pgadmin-org/pgadmin4/issues/6364.

**Comment by anilsahoo20** [comment]
The issue is resolved. Verified on Snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-04/
Environment: macOs ventura 13.4.1
