### ISSUE TITLE
Remembering the MASTER_PASSWORD_REQUIRED setting

### ISSUE THREAD

**Issue by brsnik** [pgadmin-org/pgadmin4#6512]
**Describe the solution you'd like**

Having the MASTER_PASSWORD_REQUIRED setting remembered.
I understand it's for security reasons, but it becomes annoying having to be changed to False time and time again.

Maybe an ENV variable could be implemented.

**Comment by adityatoshniwal** [comment]
@brsnik Where are you setting it to False?

**Comment by brsnik** [comment]
> @brsnik Where are you setting it to False?

The `config.py` file.

**Comment by adityatoshniwal** [comment]
@brsnik, It is not recommended to change config.py file directly. This contains default settings and is replaced on every release. Please check https://www.pgadmin.org/docs/pgadmin4/latest/config_py.html on how to customise default settings.

**Comment by brsnik** [comment]
> @brsnik, It is not recommended to change config.py file directly. It contains default settings and is replaced on every release. Please check https://www.pgadmin.org/docs/pgadmin4/latest/config_py.html on how to customise default settings.

Did not know this. Thank you.

The page that pops up after clicking the help button on the master password prompt says `See The config.py File...`, but it's a broken for me: http://127.0.0.1:54926/help/help/config_py.html#config-py
