### ISSUE TITLE
Query editor returns error on any SQL query if connected through pgbouncer (pgadmin 7.4)

### ISSUE THREAD

**Issue by amitabhkant** [pgadmin-org/pgadmin4#6515]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

If I connect to postgres through pgbouncer using pgadmin, I am unable to run queries using query editor against any table if using pgadmin 7.4 . If I use pgadmin 6.21, it returns data successfully (using the same pgabouncer and postgres database). 

**To Reproduce**

Connect to postgres using pgbouncer

**Expected behavior**

7.4 should have returned data as version 6.21 does

**Error message**

missing FROM-clause entry for table "rel"
LINE 8: ...ER JOIN pg_catalog.pg_constraint con ON con.conrelid=rel.oid

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey] OSX Montery
 - Version: [e.g. 6.15] 7.4
 - Mode: [e.g Desktop or Server] Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.] dmg

**Additional context**

Attaching the logs
[pgadmin4_debug.log](https://github.com/pgadmin-org/pgadmin4/files/11908714/pgadmin4_debug.log)
[pgadmin4.log](https://github.com/pgadmin-org/pgadmin4/files/11908715/pgadmin4.log)

**Comment by nikhil-mohite** [comment]
Hi @amitabhkant ,
The issue is reproducible on Postgres 10 and below versions, and pgAdmin doesn’t support Postgres 10 and below versions, so pgAdmin does not guarantee it will work with 10 and below versions.

**Comment by Tostino** [comment]
Just got hit by this with my team upgrading to pgadmin 7.4.
We have an upgrade planned from Postgres 10, but it's not for a little while still.

**Comment by adityatoshniwal** [comment]
@Tostino the issue is fixed, will be available in next release.

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-19
