### ISSUE TITLE
pgAdming 4's ERD incapable of showing 1-1 relationships

### ISSUE THREAD

**Issue by Eekk2k2** [pgadmin-org/pgadmin4#6516]
I am having trouble with either creating a 1-1 relationship or having the ERD show it.

I have created two tables which are named "user" and "entity". In short you can think of "entity" as an interface from which a "user" and soon "team" inherit from. Every piece of user generated content is always linked to an entity. The way an "entity" is supposed to act is for each "user"(and "team" in the future) there will be one "entity". There will never be more that one entity per user/team nor will it ever be more that one user per entity, hence why I am targeting the 1-1 relationship. 

I have followed googled around and I believe I have the relationship set up correctly, with a foreign key pointing to the "user" and a unique key on the fk column. I may have just not done it correctly so I have added at the bottom the SQL generated and, if I managed to, the pgerd from the ERD so you can look through it to see if I have done anything wrong.

**To Reproduce**

I dont know, try and create a 1-1 relattionship ig? I believe I explained it well in the explaination above.

**Expected behavior**

Crows foot notation when a bar notation is expected.

**Error message**

No error messages

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Newer, I dont know how to find it
 - Mode: Desktop
 - Package type: I dont even know what this means

**Additional context**

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public."user"
(
    index serial NOT NULL,
    user_name character varying(32) COLLATE pg_catalog."default" NOT NULL,
    user_handle character varying(32) COLLATE pg_catalog."default" NOT NULL,
    user_guid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_password text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (user_guid)
        USING INDEX TABLESPACE "HushHushHush",
    CONSTRAINT user_user_email_key UNIQUE (user_email)
        USING INDEX TABLESPACE "HushHushHush",
    CONSTRAINT user_user_handle_key UNIQUE (user_handle)
        USING INDEX TABLESPACE "HushHushHush",
    CONSTRAINT user_user_guid_key UNIQUE (user_guid)
);

CREATE TABLE IF NOT EXISTS public.entity
(
    index bigserial NOT NULL,
    entity_guid character varying(255) NOT NULL,
    entity_owner_guid character varying(255) NOT NULL,
    PRIMARY KEY (entity_guid),
    CONSTRAINT entity_entity_owner_guid_key UNIQUE (entity_owner_guid)
);

ALTER TABLE IF EXISTS public.entity
    ADD CONSTRAINT fk_entity_owner_guid FOREIGN KEY (entity_owner_guid)
    REFERENCES public."user" (user_guid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

**Comment by adityatoshniwal** [comment]
Duplicates #5128.
