### ISSUE TITLE
Hue + Spark(with Sedona) + PgAdmin4 OR  PgAdmin4 + Spark(with Sedona)

### ISSUE THREAD

**Issue by MyqueWooMiddo** [pgadmin-org/pgadmin4#6517]
**Describe the solution you'd like**

I want PgAdmin4 's geometry viewer abitility to integrate with Hue . 
So I can run my Spark sql with Sedona extension(which has its own Geometry Types) to view my results in Hue .

OR

**Describe alternatives you've considered**

I want PgAdmin4 can establish Spark sql connection , then the Geometry Types can render to geometry viewer.

**Additional context**

NO

**Comment by nikhil-mohite** [comment]
Hi @MyqueWooMiddo,

pgAdmin only supports PostgreSQL and its derivative EDB PostgreSQL.

**Comment by MyqueWooMiddo** [comment]
> Hi @MyqueWooMiddo,
> 
> pgAdmin only supports PostgreSQL and its derivative EDB PostgreSQL.

Ok , there's a tool named Zeppelin can fulfill my request , Thx.
