### ISSUE TITLE
Connection to pgAdmin server has been lost when querying large result set

### ISSUE THREAD

**Issue by dangelsaurus** [pgadmin-org/pgadmin4#6520]
PGAdmin seems to be immediately failing whenever trying to run a query against a large result set.  This started with 7.4

**example**
`select * from <table> limit 100`  this work fine
`select * from <table> limit 10000` this will **immediately** fail resulting in `Connection to pgAdmin server has been lost`. 

It does seem to be dependent on how many column the table has, this table has 9 columns and required a large data set to fail, but tables with 20-30 columns will fail with lower limits.

![image](https://github.com/pgadmin-org/pgadmin4/assets/12521900/345dda76-24e7-4f00-9f8d-75c12f83aa8b)

 - OS: Windows 11
 - Version: 10.0.22621 Build 22621
 - Mode:  Desktop
 - PG Admin 7.4

**Comment by FaharAbbasRizvi** [comment]
Issue https://github.com/pgadmin-org/pgadmin4/issues/6508 is already reported

**Comment by dangelsaurus** [comment]
> Issue #6508 is already reported

cool, I read through that, and while it seemed similar, failed under different circumstances, but as long as it's related....

**Comment by Adventurer2021** [comment]
Windows 11, Postgres 15.3:
I had to drop back to pgAdmin version 7.3 to keep pgAdmin connected to the server as it disconnected when running SQL against large tables. In my particular case running a "select 8 from table" which was 8M records forced a disconnect. Glad to see #6508 addresses this.
