### ISSUE TITLE
secret store keyring integration on KDE KWallet

### ISSUE THREAD

**Issue by gpchelkin** [pgadmin-org/pgadmin4#6522]
**Describe the bug**

pgAdmin does not save to secret store keyring on KDE systems as it should after introducing #5123

**To Reproduce**

1. On Kubuntu or any distro with KDE install and run pgAdmin in desktop mode.
2. Register new connection to server and save password.
3. Open KWalletManager to see that there is no password saved.

On KDE, KDE Wallet (or KWallet) is used as main default keyring.
And [dbus-python](https://pypi.org/project/dbus-python) module needs to be installed as per https://github.com/jaraco/keyring:
> KDE4 & KDE5 [KWallet](https://en.wikipedia.org/wiki/KWallet) (requires [dbus](https://pypi.python.org/pypi/dbus-python))

So I did this:
```bash
sudo -s
cd /usr/pgadmin4/venv
bin/pip install dbus-python
```

And it works now.
So I guess it should be enough to just add [dbus-python](https://pypi.org/project/dbus-python) to  https://github.com/pgadmin-org/pgadmin4/blob/master/requirements.txt

**Expected behavior**

pgAdmin saves passwords to secret store keyring.

**Error message**

None.

**Screenshots**

After failure there are no passwords in KWalletManager.
After success (additional steps) there are some:
![image](https://github.com/pgadmin-org/pgadmin4/assets/920616/74c49f4b-9b86-44c4-9146-ad9bfe845e55)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 with KDE5 aka Kubuntu
 - Version: pgAdmin 4 7.4
 - Mode: Desktop
 - Package type: DEB

**Additional context**

I also added this to my `~/.config/python_keyring/keyringrc.cfg` just in case:
```ini
[backend]
default-keyring=keyring.backends.kwallet.DBusKeyring
```

**Comment by nikhil-mohite** [comment]
Hi @gpchelkin,

pgAdmin official doesn't support Kubuntu so pgAdmin does not guarantee it will work.

**Comment by gpchelkin** [comment]
@nikhil-mohite Ahem, this issue is not really tied to using Kubuntu. As I said, it will occur on any system (like Debian or Ubuntu, which are supported by pgAdmin) with KDE Plasma used as Desktop Environment. Which is not an unusual thing. And the fix I described is really easy to implement.
