### ISSUE TITLE
Cannot backup renamed schema

### ISSUE THREAD

**Issue by metropolisStar** [pgadmin-org/pgadmin4#6528]
**To Reproduce**

1. Create empty database
2. Restore this database from backup file
3. Rename schema in restored database (for example public to test)
4. Immediately after rename try to backup this schema
5. pg_dump: error: no matching schemas were found (generated running backup command in process watcher contains old name of schema)

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/124900856/5769a4e4-4e94-4df4-bdc1-5f809fc81b39)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 22621.1928
 - Mode: Desktop

**Additional context**

Reconnecting to restored database resolved this issue.

**Comment by pravesh-sharma** [comment]
This issue has been fixed. Verified on latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-12/
