### ISSUE TITLE
"Failed to setup role" with hyphens in name

### ISSUE THREAD

**Issue by Arawn-Davies** [pgadmin-org/pgadmin4#6531]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

At my organisation, we have roles setup, and one of these roles is "giscorp-pg-ict-admin". In pgAdmin 4 v6.21 I am able to connect using this role, specified in the server properties window, however when I use the same server .json list in pgAdmin 4 v7.3 it gives this error

```
Failed to setup the role syntax error at or near "-" LINE 1: SET ROLE TO giscorp-pg-ict-admin ^
```

I've tried to escape the role name by surrounding it in single and double quotes, but single quotes return the error:
```
Failed to setup the role the cursor is closed
```
and double quotes return the error:
```
Failed to setup the role "giscorp-pg-ict-admin"
```

**To Reproduce**

Setup a role with hyphens in the name, and set role using the specified role just created

**Expected behavior**

Log in as the specified role, as it works in pgAdmin v6

**Error message**

Single quotes return the error:
```
Failed to setup the role the cursor is closed
```
and double quotes return the error:
```
Failed to setup the role "giscorp-pg-ict-admin"
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version: 22H2 (19045.3086)
 - Mode: Desktop
 
**Additional context**
I'm fairly low on the organisational hierarchy so I won't be able to perform any workarounds, although they'll probably just tell us to stick with v6 for the time being.

Thank you!

**Comment by akshay-joshi** [comment]
Hi @Arawn-Davies 

I have tried the same scenario but am unable to reproduce it on v7.4.
<img width="600" alt="Screenshot 2023-07-06 at 9 43 52 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/43edadfb-10f0-422c-9f11-d6fd0db1ebc6">
<img width="862" alt="Screenshot 2023-07-06 at 9 44 57 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/fc7d6833-e409-48cb-9864-07e9a516c242">

Am I missing something?

**Comment by randombk** [comment]
Hi,

The issue is with the 'role' field, not the username field.

![image](https://github.com/pgadmin-org/pgadmin4/assets/1633923/b72cd442-bc01-4d07-85c5-0d0da793d09c)

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-14/
