### ISSUE TITLE
BUG - Filters are not working and query history is empty

### ISSUE THREAD

**Issue by mfaheemakhtar** [pgadmin-org/pgadmin4#6537]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Trying to filter the rows but it is only showing a message that query has returned successfully. The query does not update though. And if check query history, I see empty rows.

**To Reproduce**

1. Right click table -> View/Edit Data -> All Rows
2. Click on the "Sort/Filter" icon
3. Add a condition and apply.

**Expected behavior**

Expected to filter the data and show query history.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/17894982/c5147d8a-aad1-4e5c-acf0-187029239408)

![image](https://github.com/pgadmin-org/pgadmin4/assets/17894982/1e9bc54a-329d-466e-8106-d8fa7450f5d8)

![image](https://github.com/pgadmin-org/pgadmin4/assets/17894982/f01c574c-bc79-414d-9794-f87f7fa0f80d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2
 - Version: 7.4
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by TyDelean** [comment]
I'm voting on this bug, I also experience the same behaviour.

**Comment by nikhil-mohite** [comment]
Hi @mfaheemakhtar , @TyDelean ,
Can you please try with the latest snapshot build [https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-10/](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-10/), If issue still reproducible can you please share steps to reproduce and the logs located `pgAdmin 4 -> Runtime -> View logs`

**Comment by TyDelean** [comment]
Early testing suggests that this bug has been resolved by this snapshot. 8-10 attempts produced favourable results.

**Comment by FaharAbbasRizvi** [comment]
This is resolved and tested in the latest snapshot build
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-13/
