### ISSUE TITLE
Processes tab displays wrong Server name in some scenario 

### ISSUE THREAD

**Issue by khushboovashi** [pgadmin-org/pgadmin4#6538]
Steps to reproduce:

1. Try to deploy a cloud instance, which should fail
2. Now, try to deploy a valid cloud instance and check the process tab.
3. The server name will be replaced by the latest cloud instance's server name for all the listed process

<img width="1444" alt="Screenshot 2023-07-07 at 10 25 44 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/14345545/7961ac72-f611-45e7-a84c-23c676dcce14">

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
