### ISSUE TITLE
Editable query in View/Edit mode

### ISSUE THREAD

**Issue by kevinhikaruevans** [pgadmin-org/pgadmin4#6543]
**Describe the solution you'd like**

When I select a table -> View/Edit Data -> All Rows, I would like to be able to edit the query and rerun it. Currently, the query text is not editable. 

In MySQL Workbench (and also SSMS), I can right click a table -> "Select Rows" then edit the query. I would like this behavior in pgAdmin too.

**Describe alternatives you've considered**

Right now, I can right click the table and press the Query Tool. It's not ideal because I have to reenter in the same query.

**Additional context**

This is my first time using pgAdmin (and Postgres), but I'm coming from MS SQL Server (SSMS) and MySQL (Workbench), so I really have no clue where things are laid out yet. I'm still getting used to this and maybe there's some easy way to make the text editable.

This is the view I'm in:
![image](https://github.com/pgadmin-org/pgadmin4/assets/4730591/605c40b5-7439-482f-83de-45f560ab3f91)

**Comment by adityatoshniwal** [comment]
Duplicates #5908
