### ISSUE TITLE
Add Folder issue for adding a sub-folder inside a folder.

### ISSUE THREAD

**Issue by sanlinnaing** [pgadmin-org/pgadmin4#6544]
**Describe the bug**

I found this issue in Server Mode which is installed on Docker environment.
In Storage Manager, when creating a sub-folder inside a folder, it created a folder with parent folder + sub-folder name.
For Example, if we create file in `SubFolder2` in `/Folder1`, it created the folder `/Folder1SubFolder2`

**To Reproduce**

1. Go to 'Tool -> Storage Manager...'
2. Click on 'New Folder' button and add `Folder1`.
3. Double click on `Folder1` and click on "New Folder" button and add `SubFolder2`.
4. Double click on `SubFolder2` or "Go Back" button, see the error that `/Folder1SubFolder2` created.

**Expected behavior**

It should be created the SubFolder2 in Folder1 and full path should be `/Folder1/SubFolder2`.

**Error message**

There is no Error message.

**Screenshots**

Here is the screenshot of error result.
![Screenshot 2023-07-09 220339](https://github.com/pgadmin-org/pgadmin4/assets/10624135/5b28f2fc-0a09-443d-b499-5ef257dffd47)

**Desktop (please complete the following information):**
 - OS: Window 11
 - Version: 7.2
 - Mode: Server
 - Browser (if running in server mode): chrome
 - Package type: Container

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-13/
Environment: Latest docker image and pip wheel package
