### ISSUE TITLE
Ensure pgAdmin never makes network requests to Google etc.

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#6548]
I've been made aware of complaints that pgAdmin (I'm guessing Desktop mode, but please check Server mode too) makes HTTP requests to Google.

Please check in both Desktop and Server mode what network requests to anywhere other than pgadmin.org, Gravatar (if enabled), auth providers (if enabled) or the user's own hosts/cloud services are made (Wireshark or other tools can help with this), and make any changes required in our own code to prevent it.

If requests are coming from NWJS or other dependencies, please log appropriate tickets with those projects and add links to those tickets here.

No network requests should be made by pgAdmin to any servers that are unexpected or unnecessary to fulfil enabled functionality in pgAdmin itself.

**Comment by louis77** [comment]
This is what my network monitor shows me when I start PGadmin 4 on macOS Desktop:

![Bildschirmfoto 2023-07-10 um 09 53 47](https://github.com/pgadmin-org/pgadmin4/assets/1240462/09be62e6-c672-476e-b03a-3f2543c14d66)

**Comment by louis77** [comment]
@adityatoshniwal Little Snitch for macOS:
https://www.obdev.at/products/littlesnitch/index.html

**Comment by adityatoshniwal** [comment]
Looks like NW.js is doing it - https://github.com/nwjs/nw.js/issues/5865

**Comment by yogeshmahajan-1903** [comment]
This is fixed with migration to electron. Verify don windows with Wireshark.
<img width="1530" alt="Screenshot 2024-07-08 at 5 13 16 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/635b0bbf-122b-4d34-8959-7d9bc662cf54">
