### ISSUE TITLE
Error in messages tab 'list' object has no attribute 'strip' on auto complete.

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#6556]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Error in messages tab 'list' object has no attribute 'strip' on auto complete.

**To Reproduce**

1. Open query tool.
2. Enter query select * from pg & hit autocomplete keys.
3. Error shown in messages tab 'list' object has no attribute 'strip'

**Expected behavior**

Autocomplete should work & give suggestion.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

<img width="1792" alt="Screenshot 2023-07-11 at 4 12 52 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/af9ab182-3835-4510-a4b5-904ee4aa04fe">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by metropolisStar** [comment]
This issue occurs only once in new query tool when autocomplete hint is requested and list of tables is expected as a result.
The second and next requests on autocomplete hint in the same query tool is ok.
Version 7.4, Windows 11 Pro, Desktop mode

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-14/
