### ISSUE TITLE
ERD Tool can't load the saved pgerd file from Shared Storage

### ISSUE THREAD

**Issue by sanlinnaing** [pgadmin-org/pgadmin4#6558]
**Describe the bug**

I have saved the fild in Shared Storage. But when I load that file again, it shown error message that describe "cannot unpack non-iterable Response object"

**To Reproduce**

1. Go to 'ERD Tool'
2. Make a ER diagram and save it in Shared Storage.
3. Click on 'Load Project' button
4. Choose the file you saved in Shared Storage and click on 'Select' button.
5. check the error

**Expected behavior**

It should load the saved ER diagaram from Shared Storage

**Error message**

"cannot unpack non-iterable Response object"

**Screenshots**

![Screenshot 2023-07-11 231510](https://github.com/pgadmin-org/pgadmin4/assets/10624135/f32f8f7f-7921-414e-910c-a77649c10814)

**Desktop (please complete the following information):**
 - OS: Window 11
 - Version: 7.2
 - Mode: Server
 - Browser (if running in server mode): chrome
 - Package type: Container

**Comment by nikhil-mohite** [comment]
Resolved, Verified on the latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-19/
OS: macOS (13.3 Ventura)
