### ISSUE TITLE
Query tool: User can not close the query tool if user delete/force any database and recreate again and try to execute same query on same database

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6565]
The User can not close the query tool if the user delete/force any database and recreate again and try to execute same query on the same database

Here is the message that is displayed:

**(Commit confirmation message is displayed
The current transaction is not committed to the database. Do you want to commit or rollback the transaction?)**

Please note Only way to close the query tool is if the user uses the option reset layout.

**To Reproduce**

1.  create database huge
2. Create the following query:

create table temp1 (a numeric);
insert into temp1 (a) select random()*100 from generate_series(0,100000000)
3. Now execution has been started
4.  Now Right Click and Click Delete/Force
5.  database drops successfully and the message "Could not find the specified database." is displayed 
6. try to create a database huge on the same query tool windows it is displayed:
7.  Could not find the specified database.Could not find the specified database.
8. create a new database huge through right click
9. database created
10.  Try to open the same query tool
11. A message "Could not find the specified database." is displayed
12. Again execute the following query 
 
create table temp1 (a numeric);
insert into temp1 (a) select random()*100 from generate_series(0,100000000)
13. Now try to close the query tool windows
14.  A pop-up message is displayed The query text has changed. Do you want to save changes?
15.  Commit confirmation message is displayed
The current transaction is not committed to the database. Do you want to commit or rollback the transaction?
16. User can not close the query tool 

**Expected behavior**

The query tool should close successfully if the user delete/force the database and reuse the same database with same Query.

**Screenshots**

<img width="1309" alt="Screen Shot 2023-07-13 at 4 29 58 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/e2f51f45-f1ec-4a22-a731-92d8952858ac">
<img width="1329" alt="Screen Shot 2023-07-13 at 4 35 04 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/4766e884-cf4b-4815-93a4-3232712dfeab">
<img width="1293" alt="Screen Shot 2023-07-13 at 4 38 05 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/0648686d-8045-46b8-b648-d979f57381d9">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g.  7.4]

**Comment by anilsahoo20** [comment]
The issue has been fixed along with #6487.
