### ISSUE TITLE
PgAdmin 4 Query Tool data problem

### ISSUE THREAD

**Issue by ivan-dbadmin-pg** [pgadmin-org/pgadmin4#6566]
Hi, 
i have pgadmin 
Version 7.4  
Desktop
Nw.js Version 0.77
Browser Chromium 114.0.5735.91
Operating System Windows-10-10.0.19045-SP0
Installation file downloaded from : https://www.postgresql.org/ftp/pgadmin/pgadmin4/v7.4/windows/

From the latest updates I have found that PgAdmin 4, when I open a Query Tool window and execute a query, opens the "messages" tab, reporting the query execution times, and if I move to "Data Output", the data is not displayed of the executed query or data from previous queries remain displayed
Could it be a problem related to the Chromium version and/or the java version on my pc?

Thank you
Ivan

**Comment by pravesh-sharma** [comment]
Duplicates #6568 hence closing.

We have fixed this issue please download latest snapshot build from https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/ and try.
