### ISSUE TITLE
Data Output pane fails to render properly

### ISSUE THREAD

**Issue by PaulForgey-Discovery** [pgadmin-org/pgadmin4#6568]
macOS 12.6.7 (M1 Pro)
pgadmin4-7.4, downloaded from pgadmin.org download link

with large result sets, the "Data Output" tab in the results pane fails to render results, instead there is an oddly shaped rectangle and nothing more.

Downgrading back to 7.3 allowed me to get past the issue.

**Comment by pravesh-sharma** [comment]
Hi @PaulForgey-Discovery 

We have fixed the issue please download latest snapshot build from https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/ and try.

**Comment by anilsahoo20** [comment]
No response from author. So closing it.
