### ISSUE TITLE
Bug pg admin 4 - version  6.10

### ISSUE THREAD

**Issue by rte3711** [pgadmin-org/pgadmin4#6570]
Bonjour,

Je ne sais pas si c'est un bug ou un paramétrage mais pg4 se termine brutalement après des requêtes insert ou update.
Pas tout le temps mais fréquemment.
Si vous pouvez voir svp.
Merci.

**Comment by pravesh-sharma** [comment]
Hi @rte3711,

Can you please try upgrading to latest version of pgAdmin 4 and test?

**Comment by rte3711** [comment]
Hello @pravesh-sharma ,

Ok, I'll test this.
I'll come back in another issue if the bug still exists.
Thanks.

**Comment by akshay-joshi** [comment]
Closing it as the author will test and report again if issue exists
