### ISSUE TITLE
Pop-up notification from Object Explorer won't get dismissed automatically if Query Tool is opened

### ISSUE THREAD

**Issue by s101d1** [pgadmin-org/pgadmin4#6571]
**Describe the bug**

When the server or database is connected in Object Explorer window, the pop-up notification ("Server connected" or "Localhost/<db_name> - Database connected") at the bottom-right corner won't get dismissed if user opened Query Tool immediately after the pop-up notification appeared (see the screenshot below).

**To Reproduce**

1. After starting the pgadmin4, expand the server in Object Explorer window. The green "Server connected" or "Localhost/<db_name> - Database connected" pop-up notifications at bottom-right corner should appear.
1. Immediately open the Query Tool with shortcut key (Alt + Shift + Q).
1. The pop-up notification will linger and won't get dismissed automatically until either user put a cursor focus on the Object Explorer window (e.g. clicking any items in the Object Explorer) or user closed the pop-up notification manually.

**Expected behavior**

The pop-up notification should get dismissed automatically.

**Screenshots**

![The screenshot](https://i.imgur.com/myEXtZi.jpg)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21
 - Version: 7.4
 - Mode: Desktop
 - Package type: APT

**Additional Request**

Please add option to disable any pop-up notifications in Preferences. I personally don't like the pop-up notifications and would like to have an option to disable them entirely.

**Comment by adityatoshniwal** [comment]
This looks like a bug in the upstream notification lib. We'll need to upgrade the lib to latest which in turn depend on MUI to be upgraded.

**Comment by akshay-joshi** [comment]
Not fixed even after upgrading to MUI 5.

**Comment by adityatoshniwal** [comment]
Connect any database which is not connected. The notification stays longer than usual. Around 10-15 seconds.

![Image](https://github.com/pgadmin-org/pgadmin4/assets/31855755/be16ba15-55e4-435f-b0be-8848fc282cfc)

**Comment by yogeshmahajan-1903** [comment]
Working fine.
