### ISSUE TITLE
Facing error while opening -  Loading pgAdmin 4 v7.4...

### ISSUE THREAD

**Issue by Chaitanya222-prog** [pgadmin-org/pgadmin4#6573]
Please correct this on priority.
[](ur
<img width="499" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/126100424/f4aee512-d387-4ef0-bd5c-21f81b75e902">
l)

**Comment by Chaitanya222-prog** [comment]
Please provide the solution.

**Comment by FaharAbbasRizvi** [comment]
Hi @Chaitanya222-prog 

Meanwhile, you can uninstall pgAdmin using postgresql uninstaller(since it is shipped with it) and download it separately from https://www.pgadmin.org/download/
