### ISSUE TITLE
Please provide the solution.

### ISSUE THREAD

**Issue by Chaitanya222-prog** [pgadmin-org/pgadmin4#6574]
Please provide the solution.

_Originally posted by @Chaitanya222-prog in https://github.com/pgadmin-org/pgadmin4/issues/6573#issuecomment-1636685186_

**Comment by akshay-joshi** [comment]
@Chaitanya222-prog 

Fahar has already provided the solution in #6573

**Comment by Chaitanya222-prog** [comment]
Thanks for the solution.

**Comment by Chaitanya222-prog** [comment]
Thanksgiving
