### ISSUE TITLE
Keyboard shortcuts don't work when cells in the data output table has focus

### ISSUE THREAD

**Issue by stefansundin** [pgadmin-org/pgadmin4#6579]
**Describe the bug**

Keyboard shortcuts (such as Cmd+H, Cmd+M, and Cmd+Q) don't work when cells in the data output table has focus.

I have only tested on macOS, not sure if pgAdmin have global shortcuts on other operating systems.

**To Reproduce**

1. Open the data view of a table: In the Object Explorer sidebar, right click a table and navigate to `View/Edit Data` -> `All Rows`
2. Click on a cell in the table.
3. While the cell is focused, you can't use global macOS shortcut such as Cmd+M (minimize the window), Cmd+H (hide the window), or Cmd+Q (quit the application).
4. If you focus a whole row or a whole column, the shortcuts are working. The bug only seems to manifest when a cell is focused.

**Expected behavior**

Global keyboard shortcuts should always work. I often want to hide pgAdmin with Cmd+H to go back to other programs.

**Error message**

N/A

**Screenshots**

To make it extra clear, the red arrow in this screenshot shows what cells to focus to reproduce the issue.

![Screenshot](https://github.com/pgadmin-org/pgadmin4/assets/1991151/4e753db2-ac01-433b-8572-bf82fe1e5e15)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 13.4.1
 - Mode: Desktop

**Additional context**

N/A

**Comment by akshay-joshi** [comment]
@FaharAbbasRizvi 

Can you please test this?

**Comment by FaharAbbasRizvi** [comment]
@stefansundin 

I am not able to reproduce the issue on MAC OS X 12

Can you please try on the last release of pgAdmin4 v7.5?

**Comment by stefansundin** [comment]
Hello @FaharAbbasRizvi.

I am still able to reproduce on v7.5.

I made a screen recording which demonstrates the problem. Please let me know if you need more help in reproducing the issue.

The text in the scratch pad is:

> If focus is in the data table below then no shortcuts work, such as Cmd+M (which minimizes the window).
> 
> If the scratch pad is focused then the shortcuts work properly.


https://github.com/pgadmin-org/pgadmin4/assets/1991151/5c064de0-f1dd-4b03-ab06-7c909e9d97a8


Hope that helps!

**Comment by FaharAbbasRizvi** [comment]
If the user goes inside the output shortcut works while if the user only selects the output then the keyboard shortcut does not work.

**Comment by nikhil-mohite** [comment]
Resolved, Verified on snapshot: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-10-11/
OS: macOS (Ventura 13.3)

**Comment by adityatoshniwal** [comment]
Hi @stefansundin,
This is a known bug from the underlying lib used for data grid.
