### ISSUE TITLE
pg admin stuck on loading

### ISSUE THREAD

**Issue by Aniket121397** [pgadmin-org/pgadmin4#6580]
Whenever i open pgadmin 4 it gets stuck on loading I tried re installing it but it is not working. Can you please help me with a solution

**Comment by yogeshmahajan-1903** [comment]
@Aniket121397 
Can you please share pgAdmin version & screenshot. Also what is OS platform & pgAdmin mode?
If possible kindly share error logs. Refer [this](https://www.pgadmin.org/faq/) link to enable logging.

**Comment by anna0831** [comment]
<img width="768" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/139956479/e3f6c974-d668-445e-8bdd-e1994c8c5c75">
I'm sorry, I actually met the same problem. Could you please help me?  My operating system is Windows and my pgAdmin mode is pgAdmin 4 v7.4

**Comment by yogeshmahajan-1903** [comment]
@Aniket121397 
How did you install pgadmin? Have you downloaded from it from [this](https://www.pgadmin.org/download/pgadmin-4-windows/) link? or you are using EDB PostgreSQL installer. 
Also what is the windows version?

**Comment by anna0831** [comment]
I used the EDB PostgreSQL installer and my Windows version is Windows 11.

**Comment by yogeshmahajan-1903** [comment]
@anna0831 
This is known issue with EDB installers. Please download it from [here](https://www.pgadmin.org/download/pgadmin-4-windows/).

**Comment by anna0831** [comment]
I'm sorry. Could you please explain using the EDB installer?  I used to download it from the link you sent, but the problem showed up again.

**Comment by yogeshmahajan-1903** [comment]
@anna0831 

When you click on EDB PostgreSQL installer for installation, you get an option to select pgAdmin4. So have you installed pgAdmin with this EDB PostgreSQL installer? If yes, uninstall pgAdmin from control panel first & then try installing using exe file downloaded from [this](https://www.pgadmin.org/download/pgadmin-4-windows/) link.

**Comment by yogeshmahajan-1903** [comment]
Issue is resolved, hence closing ticket.

**Comment by at-akshat-2107** [comment]
I also Faced this Issue Yesterday and Now it is Resolved.

Follow below steps:

1. Install the Postgresql database from this link : https://www.postgresql.org/download/windows/
2. When Exe File Downloaded then you will show like below screen
![explorer_Opy4hM9hxe](https://github.com/pgadmin-org/pgadmin4/assets/116496758/71a35352-ebf4-4735-8c86-75c08c94f97e)
3. Now click on Next Button then,see below Screen
![explorer_qMp8166yB4](https://github.com/pgadmin-org/pgadmin4/assets/116496758/dc4b87ea-1391-4bfb-8e9b-54ee54a7bf12)
4. By default all options are checked, **Now uncheck pgadmin4 options(This is the rootcause of Error.)**
![explorer_BtYNgYWhzC](https://github.com/pgadmin-org/pgadmin4/assets/116496758/53528e13-7ab2-4aff-915e-edb439a4c737)
5. And Now Click on Next -Next -Next Button and then Complete the Installation Process for Windows OS.
Link:https://www.pgadmin.org/download/pgadmin-4-windows/
6. Now install Pgadmin4 IDE from Below Link and you will now not faced Error and IDE will be open and add Password which was created at the time of Installation of Postgresql of above.

![chrome_apNbt94COM](https://github.com/pgadmin-org/pgadmin4/assets/116496758/2915ba48-0dc9-49af-8940-30db4d1af290)
