### ISSUE TITLE
Inserting more than 10 values does not work correctly in "Edit/view", only parts end up in the table.

### ISSUE THREAD

**Issue by MichaMEG** [pgadmin-org/pgadmin4#6582]
Version
7.4
Application Mode
Server
Current User
xxxx
Browser
Firefox 115.0
Operating System
Linux-6.1.0-10-amd64-x86_64-with-glibc2.36

```
CREATE TABLE IF NOT EXISTS public.test_mp_pgadmin_insert
(
    id bigint NOT NULL DEFAULT nextval('test_mp_pgadmin_insert_id_seq'::regclass),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT test_mp_pgadmin_insert_pkey PRIMARY KEY (id)
)
```
add row (30 x)
![pgadmin4_Bug_Insert_1](https://github.com/pgadmin-org/pgadmin4/assets/14922375/3e17df0e-4da4-4719-adcd-bd96eda345e0)
"Save Data Changes" and select the table "Execute Refresh":
![pgadmin4_Bug_Insert_0](https://github.com/pgadmin-org/pgadmin4/assets/14922375/0cd4d5b4-9700-403f-a0b6-904b80c91c12)

**Comment by MichaMEG** [comment]
Not values, rows are meant:
Inserting more than 10 rows does not work correctly in "Edit/view", only parts end up in the table. 
Please fix, thank you :)

**Comment by yogeshmahajan-1903** [comment]
Working fine.
