### ISSUE TITLE
 No popup message is displayed related to the Disconnect server if user disconnects the server

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6589]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

No popup message is displayed related to the Disconnect server if the user executed a long query once and disconnects the server

**To Reproduce**

1. Install rpm on older release of pgadmin4
2. Reinstall rpm on the latest snapshot builds
3. Launch pgadmin4 on server mode
4. Add remote EPAS server
5. Launch query tool Windows
6. and execute select * from pg_sleep(62);
7.  Query executed in 1 minute and 2 seconds
8.  again execute select * from pg_sleep(62);
9.  When the query started Click on Disconnect server
10.  No popup message is displayed related to the Disconnect server
11. See the error

XHRGEThttp://127.0.0.1/pgadmin4/sqleditor/status/9376214
[HTTP/1.1 500 INTERNAL SERVER ERROR 2ms]

	
success	0
errormsg	"Transaction status check failed."
info	""
result	null
data	null

**Expected behavior**

The proper pop-up message is  displayed if the user disconnects the server after executing a long query

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

<img width="1267" alt="Screen Shot 2023-07-19 at 4 44 28 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/5352b937-7818-4468-9bd5-760bec8e8d51">

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version: [e.g. 7.4]
 - Mode: [Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [RPM]

**Comment by FaharAbbasRizvi** [comment]
I am facing a similar kind of issue on my Mac laptop.

I simply executed select * from pg_sleep(62) and tried to disconnect the server,  No pop-up message is displayed.
<img width="1299" alt="Screen Shot 2023-07-19 at 6 12 29 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/d7e26688-c5dd-4f1b-8713-549c71e5a49c">

**Comment by khushboovashi** [comment]
https://github.com/psycopg/psycopg/issues/608#issuecomment-1647634718

**Comment by khushboovashi** [comment]
Upstream fixed the issue. So, after confirming, closing it.
