### ISSUE TITLE
Schema diff results should be sorted

### ISSUE THREAD

**Issue by nighthawkv8** [pgadmin-org/pgadmin4#6595]
**Describe the solution you'd like**

The results after a schema diff (list of objects) can be filtered by comparison result (source only, target only etc) but inside these blocks the object names are not sorted at all. When comparing large databases with lots of tables this makes it nearly impossible to find a specific object. Objects inside the comparison result blocks should either be sorted by name or an additional filter to search for objects would be handy.

**Describe alternatives you've considered**

No alternatives available

**Additional context**

![grafik](https://github.com/pgadmin-org/pgadmin4/assets/17766212/21456c01-65e6-4894-928e-ce43368fe8a0)

**Comment by yogeshmahajan-1903** [comment]
Working fine.
