### ISSUE TITLE
PgAdmin 7.4 stuck on loading after installation

### ISSUE THREAD

**Issue by hassoeni** [pgadmin-org/pgadmin4#6597]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

After installing pgadmin 7.4 unable to open application it is stuck on loading for entire day. 

**To Reproduce**

1. Go to installation page and install postgres with pgadmin 
2. Click on application icon to open pgadmin 4 as administrator 
3. See the error 

see page with text loading pgadmin 7.4 

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by gianpierreba** [comment]
![pgadmin_issue](https://github.com/pgadmin-org/pgadmin4/assets/95022625/a3859528-6774-4229-9d48-4ae273e7181d)

**Comment by adityatoshniwal** [comment]
Duplicates #6580

**Comment by DurgaVandharani** [comment]
Facing the same problem.
![image](https://github.com/pgadmin-org/pgadmin4/assets/140507797/ec637575-c35a-4ada-a79c-0bfd9b4bfb85)

**Comment by gianpierreba** [comment]
@DurgaVandharani 
Duplicate
Go to -> https://github.com/pgadmin-org/pgadmin4/issues/6580
