### ISSUE TITLE
Graphical explain - arrow colouring (RM #1768)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#660]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1768***
*Originally created by **Karen Blatchley** at 2016-09-27 13:27:27 UTC.*

Arrow colouring based on the percentage of the cost, and time taken on each explain node.

**Comment by pravesh-sharma** [comment]
Feature already implemented. Closing.
