### ISSUE TITLE
pgAdmin 7.4 crashes when displaying large tables (>200'000 records)

### ISSUE THREAD

**Issue by MathiasZaja** [pgadmin-org/pgadmin4#6601]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

**To Reproduce**

1. Go to Tables: choose any large table
2. Right Click on View/Edit Data
3. See the error

**Expected behavior**

Rows displayed

**Error message**

If possible, include the full, unedited text of any error messages displayed.
Sequence of messages change:
Sometimes: postgres 'NoneType' object has no attribute 'pgconn'
Sometimes: kind of 000x10934834 error ...
Then: "connexion has been lost"
Sometimes follwed by "Network error" or "127.0.0.1 does not accept connexions"

**Screenshots**
First I uninstalled and reinstalled version 7.4 from file pgadmin4-7.4-x64.exe -> same error

Then I downgraded to version 7.3 and now everything works fine -> so no screenshots available

To provide screenshots I'd have to reinstall version 7.4.
I can do it IF YOU NEED IT, otherwise I'll stay with version 7.3 (I lost one day investigating)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 22H2
 - Mode: Desktop
 - Browser: chrome
 - Package type: ?

**Additional context**

**Comment by khushboovashi** [comment]
Hi @MathiasZaja,
Can you please test on the latest snapshot build? 
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-24/

**Comment by MathiasZaja** [comment]
Hi,
    
    I sent you pgadmin4-7.4-x64.exe.
    However I don't see it in sent items, cause of the e of the file.
    Let me know if you received it.
    
    Regards
    
    Le 25.07.2023 à 20:24, nikhilraj474 a
      écrit :
    
    
      
      @akshay-joshi
        @khushboovashi
        if you can share the exe for windows that would be great I was
        also facing the same issue I can test it.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were assigned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/pgadmin-org/pgadmin4/issues/6601#issuecomment-1650327378",
"url": "https://github.com/pgadmin-org/pgadmin4/issues/6601#issuecomment-1650327378",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    
    -- 
      Mathias Zajaczkowski
      Ubik S.A.
      Chemin du Signal 22
      1296 Coppet
      (+) 41 22 960 03 91
      ***@***.***

**Comment by MathiasZaja** [comment]
Sure,
      
      Here is the link to the W exe file:
      https://ubik.ch/pgadmin4-7.4-x64.exe (To big to be attached attached)
        
      I downloaded it from your site a I've been doing for years.
      I can provide you with the database dump, if you assure
      confidentiality.
      However I don't think the issue is related to my data since it
      works fine with version 7.3
      
      Regards
      
    
    Le 25.07.2023 à 20:24, nikhilraj474 a
      écrit :
    
    
      
      @akshay-joshi
        @khushboovashi
        if you can share the exe for windows that would be great I was
        also facing the same issue I can test it.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were assigned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/pgadmin-org/pgadmin4/issues/6601#issuecomment-1650327378",
"url": "https://github.com/pgadmin-org/pgadmin4/issues/6601#issuecomment-1650327378",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    
    -- 
      Mathias Zajaczkowski
      Ubik S.A.
      Chemin du Signal 22
      1296 Coppet
      (+) 41 22 960 03 91
      ***@***.***

**Comment by anilsahoo20** [comment]
Hi @MathiasZaja 
We have released pgAdmin 4 7.5. Please download it from www.pgadmin.org and  try it once.

**Comment by nikhilraj474** [comment]
Sorry for the delay tested for 3 days no issue at all till now it is working fine now

**Comment by khushboovashi** [comment]
Closing the issue as it is fixed and confirmed by user.
