### ISSUE TITLE
Query execution is failed with the message: Missing FROM-clause entry for table "rel"

### ISSUE THREAD

**Issue by durumdara** [pgadmin-org/pgadmin4#6603]
Hello!

PGAdmin 7.4

When I try to execute a Query (which was working well in 7.3), I get this error:

_missing FROM-clause entry for table "rel"
LINE 8: ...ER JOIN pg_catalog.pg_constraint con ON con.conrelid=rel.oid_

The server is:
PostgreSQL 10.5, compiled by Visual C++ build 1800, 64-bit

With PG11 (on Linux) I don't get this error message. In EMS PGSQL manager the Query is working fine.
My team member didn't upgrade, he has 7.2, and he can execute the same Query on 10.5

Thanks for the bug elimination!

Best regards
dd

**Comment by adityatoshniwal** [comment]
Duplicates #6515
