### ISSUE TITLE
Query window changed to unuseable after the network was down: pgobj.conn is None

### ISSUE THREAD

**Issue by durumdara** [pgadmin-org/pgadmin4#6604]
Hello!

PGAdmin 7.4
With the previous version I didn't get this error.

Sometimes I have to hibernate my machine and I left the PGAdmin opened.
Formerly when I had a Query window opened, I could execute the Query again with F5.
It said the connection is disconnected, and after that dialog I can reopen the Query.

Now in the same situation I can't use this Query window again, because I got this error (something like that):
pgobj.conn is None

Except:
When I disconnect from server, and connect again, then I can use F5 in that Query window again.
BUT: in the first time the data appears, I can see rows, and in the next second it vanishes and the grid have no rows.
In the 2. times of F5 the data appears again.

Best regards
dd

**Comment by khushboovashi** [comment]
Hi @durumdara, can you please test on the latest snapshot build? https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-24/

**Comment by durumdara** [comment]
Hello!

Sorry, I forgot to write the OS. I have Win11/64 bit. So I need PGAdmin setup binary for this OS.
Thank you!

BR
dd

**Comment by khushboovashi** [comment]
Use yesterday's snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-23/

**Comment by anilsahoo20** [comment]
Hi @durumdara 
We have released pgAdmin4 7.5. Please try it once.

**Comment by durumdara** [comment]
Hello! @anilsahoo20 
Sorry for late answer. I downloaded 7.5 it, and I tested. It seems to be ok!

**Comment by adityatoshniwal** [comment]
Thank you for confirming @durumdara. We're closing this.
