### ISSUE TITLE
Query finished successfully, but its still running

### ISSUE THREAD

**Issue by hben-align** [pgadmin-org/pgadmin4#6606]
Hi

Lately, pgadmin has started to do a lot of problems in the output section...

sometimes it fails to run and shows errors related to string size (although the second run works with no problem, errors like: ERROR:  message contents do not agree with length in message type "N" ),
but in this case, I see a bizarre behavior, 
I run plpgsql and I have RAISE INFO in it, it's working as expected, and after 16 minutes I get the same message twice and then a message that the query finished successfully and it stopped running:
![image](https://github.com/pgadmin-org/pgadmin4/assets/96145416/dcdcb98a-d07c-4dcc-821e-f6ee0c809728)

but if I look at the sessions running on the pg, I actually see that it's still running! and that it's active... 
just to make sure I ran the query to count how many rows my code needs to update and I see a decrease: 67555130
running it for a second time and I see another decrease: 67385113

and after those type of error occurs, if I don't open a new session window, it wont work anymore, everytime I'll run code in that session I'll get Query Finished Successfully without any error message or without the actual results

so something very strange is going over pgadmin...

![image](https://github.com/pgadmin-org/pgadmin4/assets/96145416/2b6d5b84-adee-47f0-9180-2453635168ae)
I cannot replicate it, its kinda random...

I don't see anything in the log file that is related to this issue...

**Comment by hben-align** [comment]
actually I can also see that in the session that I got "query returned successfully" the icon on the top-left is showing the the query is still active

![image](https://github.com/pgadmin-org/pgadmin4/assets/96145416/249a4262-5273-46b7-9544-a6526ae00503)

**Comment by khushboovashi** [comment]
@hben-align, we have fixed this issue. Please test the latest snapshot build to confirm whether this has been fixed. https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-24/

**Comment by hben-align** [comment]
@khushboovashi what do you mean?
Should I download the latest build and reinstall it?
it seems like the same version as I currently have

**Comment by khushboovashi** [comment]
@hben-align, I suggested installing the new snapshot build, which shows the same version as you have, but the issue is fixed. Ref: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-24/

**Comment by anilsahoo20** [comment]
Hi @hben-align,
We have released pgAdmin 4 7.5. Please download it from [www.pgadmin.org](http://www.pgadmin.org/) and try it once.

**Comment by adityatoshniwal** [comment]
Closing. No response from user.
