### ISSUE TITLE
Password is not saved

### ISSUE THREAD

**Issue by ebuzzz** [pgadmin-org/pgadmin4#6612]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

The password for the server is not saved, even though logging in works and the checkbox is checked.
I'm using a SSH Tunnel to connect to a remote server. I need to supply the password for the SSH Tunnel key, which I want. On a first attempt, I only see the SSH Tunnel password field. After entering it, I get the message `connection failed: fe_sendauth: no password supplied`. After also supplying the password for the Postgres account, and checking 'Save password' at the bottom field, I get into the server.

On disconnect and reconnect, the same procedure needs to be followed, rendering the Save password option useless.

**To Reproduce**

1. Setup a server with SSH Tunnel enabled
2. Connect to the server
3. Enter the SSH Tunnel password for the key
4. Wait for the password popup to return
5. Check the Save password checkbox for the server password
6. Enter the correct server password
7. Click OK

**Expected behavior**

The server password should be saved and re-used on future connections.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/4066914/33e237b8-1f8b-4642-b53d-c9a90a8a57fb)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 7.4
 - Mode: Desktop
 - Package type: Installer

**Additional context**

I've upgraded from pgAdmin 4.x and let pgAdmin migrate the servers for me.

**Comment by ebuzzz** [comment]
This issue seems to be related to the migrated servers. When I re-create the server, the password is stored correctly.

**Comment by nikelborm** [comment]
Maybe related:
https://github.com/pgadmin-org/pgadmin4/issues/6741#issuecomment-1722212595

**Comment by khushboovashi** [comment]
Hi @ebuzzz, please check with the latest version.

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing issue. Also issue is not reproducible at our end.
