### ISSUE TITLE
Ability to use ERD Tool without an existing database

### ISSUE THREAD

**Issue by spoco2** [pgadmin-org/pgadmin4#6614]
**Describe the solution you'd like**

I want to use PGAdmin to design my database that will be managed via ORM and not locally accessible. I want to design it from scratch in PGAdmin, and yet I can't create an ERD Diagram without connecting to an existing database. This makes using it to initially design a DB very limiting. I don't want to have to run a local database just to be able to create a diagram. Why can't I create and manage a PostGreSQL ERD using this tool with no _real_ database?

**Describe alternatives you've considered**

Other ERD tools, but they didn't have Postgresql specific typing for columns etc.

**Additional context**

I saw that PGAdmin had a very nice looking ERD tool, and so wanted to use it to design my DB, only to find I can't!

**Comment by adityatoshniwal** [comment]
HI @spoco2,

pgAdmin ERD needs PG connection mainly to fetch the column types. They are not hardcoded and are specific to the PostgreSQL server you're using. Some of the users create custom types and use them.
Every PostgreSQL server has at least one database `postgres` which you can use that to create the ERD.

Thanks
