### ISSUE TITLE
The ERD Tool dose not show all relationships when you download (export to png) a large ERD diagram.

### ISSUE THREAD

**Issue by Lil3p** [pgadmin-org/pgadmin4#6615]
pgAdmin Version :7.4
Application Mode : Desktop
OS: Windows 11

![Bug_ERD pgerd_1](https://github.com/pgadmin-org/pgadmin4/assets/12753362/2d6f7e20-f42b-436d-8bf5-09918220c45d)

ERD Source file below :
[Bug_ERD.zip](https://github.com/pgadmin-org/pgadmin4/files/12158102/Bug_ERD.zip)

**Comment by adityatoshniwal** [comment]
Duplicates #4995
