### ISSUE TITLE
Regarding the storage of database connection information

### ISSUE THREAD

**Issue by guomaoqiu** [pgadmin-org/pgadmin4#6616]
My container runs in k8s, and I mount the data to /pgadmin in the container through pv,

Why all the database connection information I added before is lost after I restart the service?

Where is it stored?

**Comment by adityatoshniwal** [comment]
Hi @guomaoqiu,
You'll need to map the `/var/lib/pgadmin` directory. Please check https://www.pgadmin.org/docs/pgadmin4/7.4/container_deployment.html

**Comment by adityatoshniwal** [comment]
Closing. No response from user.
