### ISSUE TITLE
Unable to Open PgAdmin 7.5 After Upgrade from 7.4 - Mac

### ISSUE THREAD

**Issue by lemorage** [pgadmin-org/pgadmin4#6625]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

I have been using PgAdmin 7.4 without any issues, but today I upgraded it to version 7.5. However, after the upgrade, I encountered a problem where PgAdmin 7.5 failed to open. Whenever I click on the application, it unexpectedly quits without displaying any error message or reason for the failure.

**To Reproduce**

1. I Uninstalled PgAdmin 7.4 from my Mac machine firstly.
2. And then I Installed PgAdmin 7.5 version.
3. I Attempted to open the application, but it quits unexpectedly.

**Expected behavior**

PgAdmin 7.5 should open successfully after the upgrade, allowing me to continue using the software without any issues.

**Error message**

No error messages or crash reports are displayed when the application quits unexpectedly, making it difficult to identify the root cause of the issue.

**Desktop (please complete the following information):**
 - OS: Mac M1 chip
 - Version: Ventura 13.2.1
 - Mode: Desktop

**Comment by adityatoshniwal** [comment]
@lemorage try clearing the files here - `~/Library/Application Support/pgAdmin 4`.

**Comment by lemorage** [comment]
@adityatoshniwal Yeah, that works to some extent. After I've cleaned all the files, it runs perfectly only for the first time. However, I'm facing an issue when trying to open it the second time; it keeps failing to open. Any thoughts on what might be causing this? Btw, I've attached the details of my problem in this [gist](https://gist.github.com/lemorage/5064d593eb9af55be7ea726c6e17e88c).

**Comment by thomashan** [comment]
`~/Library/Application Support/pgadmin 4/Default/Preferences` contains the json for default configuration.
Setting `.browser.app_window_placement.pgadmin-main.fullscreen` field to true seems to trigger this issue.
```
"browser": {
    "app_window_placement": {
      "pgadmin-main": {
       ...
        "fullscreen": true,
       ...
      }
    }
  },
```
I am just wondering why deciding to start up the app in fullscreen would trigger the whole app to terminate?!

**Comment by avalatea** [comment]
> @lemorage try clearing the files here - `~/Library/Application Support/pgAdmin 4`.

Want to add that I am experiencing this issue as well. Clearing the files seems to resolve the issue, but I would need to do this every time before I use pgAdmin. I assume files are created with every use which causes this problem again?

**Comment by adityatoshniwal** [comment]
Looks like an upstream issue - https://github.com/nwjs/nw.js/issues/7964

**Comment by anthonydb** [comment]
Is there a workaround for this issue? It's a little odd that the nw.js bug is almost a year old but reports just started cropping up recently.

**Comment by adityatoshniwal** [comment]
@anthonydb We've tested previous versions (from current) and found that the issue has started coming from NWjs v0.78 which is shipped with pgAdmin 7.5. We're not sure why, but NWjs v0.77 works fine which was shipped with pgAdmin 7.4. So in upcoming release, we're going to ship NWjs v0.77 to fix it.

**Comment by avalatea** [comment]
In case anyone needs a workaround until this is fixed:

```bash
# Uninstall pgadmin4 7.5
brew uninstall pgadmin4

# Save the pgadmin4 7.4 brew files locally as pgadmin4.rb
curl https://raw.githubusercontent.com/Homebrew/homebrew-cask/6e34ac7d01a257cf799fff6a811748ac74721877/Casks/pgadmin4.rb > pgadmin4.rb

# Download pgadmin4 again from the file
brew install -s pgadmin4.rb
```

**Comment by jestoncolelewis** [comment]
@avalatea thank you. This worked for me.

**Comment by adityatoshniwal** [comment]
Can anyone try v7.6? The issue is fixed.

**Comment by Nasa62** [comment]
> 

@adityatoshniwal 
Confirmed working:

Steps taken (no uninstalls or clearing caches or anything):
1. 7.4 confirmed working
2. Closed 7.4
3. Installed 7.5
4. Confirmed crash of 7.5
5. Installed 7.6
6. Runs successfully without crash 😄 thank you!

**Comment by thomashan** [comment]
@adityatoshniwal : Yes, the issue seems to be fixed from 7.6!
Thank you.

**Comment by ruby-stha** [comment]
Is there any fix or workaround for pgadmin installed with EDB?

**Comment by adityatoshniwal** [comment]
> Is there any fix or workaround for pgadmin installed with EDB?

Hi @ruby-stha,
You can uninstall the pgAdmin installed with EDB using the same PosgtreSQL installer and download pgAdmin separately.

**Comment by adityatoshniwal** [comment]
Closing this as issue seems to be fixed.

**Comment by konstantinKarzhanov** [comment]
I had a similar problem with pgAdmin 4 which was installed with EDB (PostgreSQL version 16.RC1). 

The solution was separate installation of pgAdmin 4 version 7.6

macOS: Monterey 
version: 12.6.2

**Comment by Psypriest** [comment]
> Can anyone try v7.6? The issue is fixed.

Just installed it yesterday and still seeing this issue. 

2.6 GHz 6-Core Intel Core i7
macOS Ventura
Version 13.3.1 (a

**Comment by ofirattia** [comment]
> @lemorage try clearing the files here - `~/Library/Application Support/pgAdmin 4`.

thanks, worked

**Comment by theAbiola** [comment]
This definitely worked for me. Thanks for the help. Cheers!

**Comment by ankitxstha-svg** [comment]
> [@lemorage](https://github.com/lemorage) try clearing the files here - `~/Library/Application Support/pgAdmin 4`.

thankyou it worked for me
