### ISSUE TITLE
OAUTH2 configuration not working

### ISSUE THREAD

**Issue by karthikselvarajanmd** [pgadmin-org/pgadmin4#6626]
**Describe the bug**

I am trying to get oauth2 setup (Okta) via the pgadmin4 helm chart and havnt been successful. The login page is up but with following issues:
- unable to login using default username and password. Get the following error:
`{"success":0,"errormsg":"'str' object has no attribute 'remove'","info":"","result":null,"data":null}`
- unable to see login with okta button but see 350+ login buttons:
<img width="1719" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/43188798/3f982241-0d3b-43d5-942a-44ab2b385755">

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Mode: [Server]
 - Browser (if running in server mode): [e.g. chrome]
 - Package type: Container

**Comment by adityatoshniwal** [comment]
@karthikselvarajanmd  Please share your OAUTH2 config.

**Comment by karthikselvarajanmd** [comment]
terraform values file is as below:
`image:
  tag: "7.4"

ingress:
  ## If true, Kubernetes Dashboard Ingress will be created.
  ##
  enabled: "True"
  ## Kubernetes Dashboard Ingress annotations
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: ${hostname}
      paths:
        - path: /
          pathType: Prefix

env:
  email: *****@*****.com
  password: "*****"
  variables:
    - name: MASTER_PASSWORD
      value: "True"
    - name: PGADMIN_DISABLE_POSTFIX
      value: "True"
    - name: PGADMIN_CONFIG_CONFIG_DATABASE_URI
      value: "'postgresql://*****:*****@*****:5432/*****'"
    - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
      value: "['oauth2', 'internal']"
    - name: PGADMIN_CONFIG_OAUTH2_CONFIG
      value: "[{'OAUTH2_NAME': 'Okta','OAUTH2_DISPLAY_NAME': 'OKTA','OAUTH2_CLIENT_ID': '${client_id}','OAUTH2_CLIENT_SECRET': '${client_secret}','OAUTH2_TOKEN_URL': '${token_url}','OAUTH2_AUTHORIZATION_URL': '${auth_url}','OAUTH2_USERINFO_ENDPOINT': 'oauth2/v1/userinfo','OAUTH2_SCOPE': 'email'}]"
    - name: PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER
      value: "True"`

**Comment by karthikselvarajanmd** [comment]
nvm - I got it to work.

Made a couple of changes like:
- NOT enclosing email in quotes
- adding OAUTH2_SCOPE, OAUTH2_SERVER_METADATA_URL and OAUTH2_API_BASE_URL

**Comment by adityatoshniwal** [comment]
Closing per user confirmation.
