### ISSUE TITLE
Limit query in pgadmin settings

### ISSUE THREAD

**Issue by sortega6** [pgadmin-org/pgadmin4#6629]
Hi Pgadmin team,

When we have a big table with a big number of fields () and a huge number of registries (+ 7 million) and we have:

- File --> Preferences --> Query Tool --> Graph Visualizer --> Row limit = 10
- File --> Preferences --> Query Tool --> Graph Visualizer Results Grid --> On demand record count = 10

Pgadmin consumes all avaliable memory and it dies.

¿Is there a way to limit queries so Pgadmin does not die in the process? (without using select * from table **limit** xxxx)

Thank you.

**Comment by anilsahoo20** [comment]
There is no way to set the limit, you need to use the limit clause. The on demand record count param is just used to limit the no. of rows to be displayed. Query will still fetch all the data before loading to the UI.

We have tried using this query, `select * from generate_series(1,170000000);`

<img width="1135" alt="Screenshot 2023-07-28 at 5 48 32 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/122535205/f089a006-8b4b-44f6-b2a6-874dd921ba65">
