### ISSUE TITLE
Pgadmin 7.5 won't start (macos 13.5)

### ISSUE THREAD

**Issue by aarongundel** [pgadmin-org/pgadmin4#6631]
Pgadmin 4 v 7.5 won't start for me.  I see the loading screen, then it abruptly crashes.  

**To Reproduce**

1. Attempt to start pgadmin 4

**Expected behavior**

Pgadmin 4 starts without error.  

**Error message**

There is no error message from the UI.  When I start from the command line, I see this.  

```
[8225:259:0728/113148.619424:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[8234:12291:0728/113153.839596:ERROR:cert_verify_proc_builtin.cc(623)] No net_fetcher for performing AIA chasing.
Received signal 11 SEGV_MAPERR 000000000020
 [0x000118742212]
 [0x000118735683]
 [0x000118742161]
 [0x7ff806fc25ed]
 [0x7ff806e13cc6]
 [0x00011d90d522]
 [0x00011db2a1f0]
 [0x00011db9a0db]
 [0x00011a48951a]
 [0x00011a4918d9]
 [0x00011b4204bd]
 [0x00011b41ec46]
 [0x00011db2bde5]
 [0x00011dba6c97]
 [0x00011d8dbcd5]
 [0x00011d8daf17]
 [0x00011af83259]
 [0x0001173f5cb0]
 [0x0001173f8494]
 [0x0001173f8927]
 [0x0001173f4a63]
 [0x000116f97179]
 [0x0001173f51c6]
 [0x000119247f90]
 [0x00011924d131]
 [0x0001192496d0]
 [0x00011933b1da]
 [0x00011924b799]
 [0x0001186eb4d2]
 [0x000118702a6e]
 [0x0001187024a9]
 [0x0001187030d5]
 [0x00011875cec3]
 [0x000118759a22]
 [0x00011875c6df]
 [0x7ff807070f2a]
 [0x7ff807070ecc]
 [0x7ff807070ca5]
 [0x7ff80706f92f]
 [0x7ff80706ef31]
 [0x7ff810aeff3d]
 [0x7ff810aefd4e]
 [0x7ff810aefaa8]
 [0x7ff80a10b25c]
 [0x7ff80a10a106]
 [0x0001181943f0]
 [0x000118759a22]
 [0x000118194369]
 [0x7ff80a0fc788]
 [0x00011875d4ac]
 [0x00011875c23c]
 [0x000118703459]
 [0x0001186ca15f]
 [0x0001165d8301]
 [0x0001165d9c92]
 [0x0001165d5a5a]
 [0x000117b111c4]
 [0x000117b12389]
 [0x000117b1219d]
 [0x000117b10867]
 [0x000117b10b03]
 [0x000113f8c930]
 [0x000107ce687e]
 [0x7ff806c3b41f]
[end of stack trace]
[0728/113154.515604:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)
[1]    8225 segmentation fault  /Applications/pgAdmin\ 4.app/Contents/MacOS/pgAdmin\ 4
```

**Desktop (please complete the following information):**
 - OS: Macos Ventura 13.5
 - Version: 7.5
 - Mode: Desktop
 - Package type: dmg

**Additional context**

I attempted to upgrade from 7.0.  I downgraded to 7.4 and had no problems after that.  My problem is only with 7.5.

**Comment by mjy78** [comment]
Same issue here. Venture 13.5, Version 7.5. Downgrading to v7.4 works.

**Comment by Shamoo100** [comment]
Same Issue here, Monterey 12.6.8

**Comment by Dellenoam** [comment]
At first everything worked, then it stopped for no apparent reason. Downgrading to version 7.4 also helped me.

**Comment by adityatoshniwal** [comment]
Duplicates #6625.

**Comment by khushboovashi** [comment]
@aarongundel, try clearing cache located at ~/Library/Application Support/pgAdmin 4.

**Comment by jlmoya** [comment]
Currently getting a screen that says:

Fatal Error

The pgAdmin 4 server could not be contacted:

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3"
Runtime Config File: "/Users/josemoya/Library/Preferences/pgadmin/runtime_config.json"
pgAdmin Config File: "/Applications/pgAdmin 4.app/Contents/Resources/web/config.py"
Webapp Path: "/Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
pgAdmin Command: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3 -s /Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
Environment: 
  - MallocNanoZone: 0
  - USER: xxxxxxx
  - COMMAND_MODE: unix2003
  - __CFBundleIdentifier: org.pgadmin.pgadmin4
  - PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
  - LOGNAME: josemoya
  - DISPLAY: /private/tmp/com.apple.launchd.qAZucdja1G/org.xquartz:0
  - SYSTEM_VERSION_COMPAT: 0
  - SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.J9KCMgHvIB/Listeners
  - HOME: /Users/xxxxxxx
  - SHELL: /opt/homebrew/bin/bash
  - TMPDIR: /var/folders/9g/wdn7gl9s15b3_r5vggg4yzvc0000gn/T/
  - __CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
  - XPC_SERVICE_NAME: application.org.pgadmin.pgadmin4.1669710066.1670506533
  - XPC_FLAGS: 0x0
  - PGADMIN_INT_PORT: 65112
  - PGADMIN_INT_KEY: 3aea8e70-4928-45ab-987f-180ea20cd52d
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.009 Sec
dyld[56995]: Library not loaded: @rpath/Versions/3.11/Python
  Referenced from: <A55E7B45-F1D8-31AB-BF35-98C9DD5D9B39> /Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/bin/python3.11
  Reason: tried: '/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/Python' (code signature in <514EFC82-C424-3863-84A8-E24FFD50343D> '/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/Python' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/Python' (code
 signature in <514EFC82-C424-3863-84A8-E24FFD50343D> '/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/Python' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/Python' (no such file, not in dyld cache)

<img width="789" alt="Screenshot 2023-07-31 at 4 39 09 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/1294464/a3314ea1-5694-45fc-b3a1-5cd3f5a2ac75">

**Comment by Nasa62** [comment]
> @aarongundel, try clearing cache located at ~/Library/Application Support/pgAdmin 4.

This was effective for me at least.

**Comment by abdulsalamcodes** [comment]
> try clearing cache located at ~/Library/Application Support/pgAdmin 4.

this works for me too.

Go to your Finder, please `Shift + Command + G` and paste the line `~/Library/Application Support/pgAdmin 4.`. Delete all the items found in the location.

Launch your pgAdmin 4 again, and that should work.

**Comment by hoike** [comment]
I had similar issue with PostgreSQL 15. pgAdmin worked fine but the next day, it wouldn't load. I finally installed PostgreSQL 17 in a different location. When I opened pgAdmin I discovered that I have 2 PostgreSQL servers, 15 and 17. I was able to log into the previous version 15 as well as the newly installed version 17. The default port for the newly installed version 17 is 5433.
