### ISSUE TITLE
pgAdmin 7.4 very unstable on Windows server 2022 with PostgreSQL 12

### ISSUE THREAD

**Issue by JosefMachytkaNetApp** [pgadmin-org/pgadmin4#6637]
**Describe the bug**
I worked last week repeatedly several hours in pgAdmin 7.4 with PostgreSQL 12 on Windows server 2022 using Teamviewer remote access. And unfortunately it was quite unpleasant experience because I had to restart pgAdmin every 15 to 20 minutes because it sort of stopped communicating with PostgreSQL without any reasonable error message. 

It simply did not processed DO scripts anymore and immediately reported "success" although it clearly did not do anything. After closing and starting pgAdmin again, all worked as expected for another 15 to 20 minutes. And then situation repeated itself. Client was watching, it was rather awkward experience. I cannot report any reasonable error message because nothing was shown. pgAdmin simply decided to skip run of the script and immediately reported successful run without any results at all.

**To Reproduce**
Try to run repeatedly DO scripts in pgAdmin which report a lot of RAISE NOTICE messages. My feeling was that pgAdmin could have some memory problems but no error message was shown. 

If you would be able to do something with it, it would be great.

**Comment by khushboovashi** [comment]
Hi @JosefMachytkaNetApp,

Please use the latest pgAdmin 4 v7.5. We have fixed many Query tool issues in the 7.5 release.
Download Ref: https://www.pgadmin.org/download/pgadmin-4-windows/

Thanks,
Khushboo

**Comment by JosefMachytkaNetApp** [comment]
AFAIKT version 7.5 is working nicely. Thank you.
