### ISSUE TITLE
stable API access to manage pgAdmin

### ISSUE THREAD

**Issue by rwahyudi** [pgadmin-org/pgadmin4#6638]
We are teaching students (non-IT people) to connect and manage Postgres databases. 
For every new student, we create student accounts and databases using internal authentication. 

We use a single instance of pgAdmin where students can log in and can see their database and the database that they have access to without having to setup anything. 

The process to create and manage multiuser pgAdmin is quite cumbersome and right now we doing it as the following : 

1. Login to pgadmin as admin 
2. Get the current user list & check if users are already created in pgAdmin
3. If the user does not exist create the user and check again if the user has been created successfully. 
4. Logout admin user 
5. Login as the student account 
6. Obtain top-level server group and create a connection to student's private database & shared databases
7. Set default preferences ( this is to hide a bunch of stuff so it does not confuse  the students as they are only interested in the table )

We managed to do all of the above using bash & curl
The issue is that it's been few times that upgrades break the script which makes me question if our approach is the the right way to go about this. 

What is the best way of managing pgAdmin users programmatically?

**Comment by khushboovashi** [comment]
Hi @rwahyudi,

You can use the `Shared servers` feature to share the connections with the users. This option is available only to admin users. Ref: https://www.pgadmin.org/docs/pgadmin4/7.5/server_dialog.html

For multi-user environments, many authentication methods are supported other than internal, like LDAP, OAuth2, etc., those you can use to avoid creating users manually. You can check the documentation for the same. Ref for LDAP: https://www.pgadmin.org/docs/pgadmin4/7.5/ldap.html

pgAdmin does not support API access to integrate with external scripts/apps directly, but the architecture is written in a way that you are able to use APIs through scripts.

Thanks,
Khushboo

**Comment by rwahyudi** [comment]
Hi @khushboovashi, 

We looked at a shared server but it does not provide the behavior that we want. 
We have a few hundred students and each student has their own private database that only they can have full access to. 

The reason we don't use LDAP is that we cant customize user preferences and pre-create the connection  before the user logs in 

>  pgAdmin does not support API access to integrate with external scripts/apps directly

Thanks for the confirmation! Our use cases seem to be edge cases so I don't expect this to get any traction.

**Comment by adityatoshniwal** [comment]
HI @rwahyudi,

Is this what you're looking for - https://github.com/pgadmin-org/pgadmin4/issues/2483?

**Comment by rwahyudi** [comment]
Hi @adityatoshniwal ,

Yes !! This is great news thank you!

That will solve the user account management part!
Once the user is created I might be able to use setup.py with --user option to create user database connection. 

The next missing part would be customizing user preference :D

**Comment by akshay-joshi** [comment]
Related #2483

**Comment by akshay-joshi** [comment]
Will implement as a part of #2483, hence closing it.

**Comment by khushboovashi** [comment]
> Hi @adityatoshniwal ,
> 
> Yes !! This is great news thank you!
> 
> That will solve the user account management part! Once the user is created I might be able to use setup.py with --user option to create user database connection.
> 
> The next missing part would be customizing user preference :D

What exactly do you need here? 
In the past, in which way have you used pref API?

**Comment by rwahyudi** [comment]
> What exactly do you need here?

- A customisable default preferences for new user.
- A way to customize preferences for new user

> In the past, in which way have you used pref API?

Currently I reverse engineered the process of user customizing their profile: 
1. Record user credentials 
2. Simulate login to pgadmin as the user 
3. Issue a PUT  command to /preferences 

```shell
curl $CURL "${HEADERS[@]}" -s -o /dev/null -X PUT \
                                -H "Content-Type: application/json" \
                                -H "Referer: ${PGADMIN_SERVER}/browser/" \
                                $PGADMIN_SERVER/preferences/ \
                                --data-raw $PREF
``` 


$PREF  would contain the following : 

`[{"category_id":7,"id":42,"mid":6,"name":"show_node_cast","value":false},{"category_id":7,"id":43,"mid":6,"name":"show_node_event_trigger","value":false},{"category_id":7,"id":44,"mid":6,"name":"show_node_extension","value":false},{"category_id":7,"id":45,"mid":6,"name":"show_node_foreign_data_wrapper","value":false},{"category_id":7,"id":46,"mid":6,"name":"show_node_foreign_server","value":false},{"category_id":7,"id":47,"mid":6,"name":"show_node_user_mapping","value":false},{"category_id":7,"id":48,"mid":6,"name":"show_node_language","value":false},{"category_id":7,"id":49,"mid":6,"name":"show_node_publication","value":false},{"category_id":7,"id":51,"mid":6,"name":"show_node_aggregate","value":false},{"category_id":7,"id":52,"mid":6,"name":"show_node_catalog_object","value":false},{"category_id":7,"id":53,"mid":6,"name":"show_node_collation","value":false},{"category_id":7,"id":54,"mid":6,"name":"show_node_domain","value":false},{"category_id":7,"id":55,"mid":6,"name":"show_node_domain_constraints","value":false},{"category_id":7,"id":56,"mid":6,"name":"show_node_foreign_table","value":false},{"category_id":7,"id":57,"mid":6,"name":"show_node_fts_configuration","value":false},{"category_id":7,"id":58,"mid":6,"name":"show_node_fts_dictionary","value":false},{"category_id":7,"id":59,"mid":6,"name":"show_node_fts_parser","value":false},{"category_id":7,"id":60,"mid":6,"name":"show_node_fts_template","value":false},{"category_id":7,"id":61,"mid":6,"name":"show_node_function","value":false},{"category_id":7,"id":62,"mid":6,"name":"show_node_trigger_function","value":false},{"category_id":7,"id":63,"mid":6,"name":"show_node_procedure","value":false},{"category_id":7,"id":64,"mid":6,"name":"show_node_operator","value":false},{"category_id":7,"id":65,"mid":6,"name":"show_node_package","value":false},{"category_id":7,"id":66,"mid":6,"name":"show_node_edbfunc","value":false},{"category_id":7,"id":67,"mid":6,"name":"show_node_edbproc","value":false},{"category_id":7,"id":68,"mid":6,"name":"show_node_edbvar","value":false},{"category_id":7,"id":70,"mid":6,"name":"show_node_synonym","value":false},{"category_id":7,"id":73,"mid":6,"name":"show_node_compound_trigger","value":false},{"category_id":7,"id":75,"mid":6,"name":"show_node_check_constraint","value":false},{"category_id":7,"id":76,"mid":6,"name":"show_node_exclusion_constraint","value":false},{"category_id":7,"id":77,"mid":6,"name":"show_node_foreign_key","value":false},{"category_id":7,"id":79,"mid":6,"name":"show_node_unique_constraint","value":false},{"category_id":7,"id":81,"mid":6,"name":"show_node_partition","value":false},{"category_id":7,"id":82,"mid":6,"name":"show_node_row_security_policy","value":false},{"category_id":7,"id":83,"mid":6,"name":"show_node_rule","value":false},{"category_id":7,"id":84,"mid":6,"name":"show_node_trigger","value":false},{"category_id":7,"id":87,"mid":6,"name":"show_node_mview","value":false},{"category_id":7,"id":88,"mid":6,"name":"show_node_catalog","value":false},{"category_id":7,"id":89,"mid":6,"name":"show_node_subscription","value":false},{"category_id":7,"id":90,"mid":6,"name":"show_node_pga_job","value":false},{"category_id":7,"id":91,"mid":6,"name":"show_node_pga_schedule","value":false},{"category_id":7,"id":92,"mid":6,"name":"show_node_pga_jobstep","value":false},{"category_id":7,"id":93,"mid":6,"name":"show_node_resource_group","value":false},{"category_id":7,"id":94,"mid":6,"name":"show_node_role","value":false},{"category_id":7,"id":95,"mid":6,"name":"show_node_tablespace","value":false}]`
