### ISSUE TITLE
pgAdmin stopped output of messages during procedure execution

### ISSUE THREAD

**Issue by istolarov** [pgadmin-org/pgadmin4#6643]
After v.6.21, when executing stored function, you no longer see output of std out messages until procedures ends execution. Then everything is printed at once. It was a nice feature to see what's going on while function was executing...

**Comment by adityatoshniwal** [comment]
HI @istolarov  Did you try pgAdmin 7.5?

**Comment by alessandroDrogal** [comment]
Same problem in pgAdmin 7.5

**Comment by akshay-joshi** [comment]
Duplicate of #6420
