### ISSUE TITLE
/usr/pgadmin4/bin/pgadmin4: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by miiichael** [pgadmin-org/pgadmin4#6649]
pgadmin4 fails to launch, presumably due to an unspecified dependency on libnss3.

**To Reproduce**

1. install pgadmin4-desktop on a fairly clean bookworm install
2. try to run pgadmin
3. error

**Expected behavior**

pgadmin launches

**Error message**

`/usr/pgadmin4/bin/pgadmin4: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`

**Desktop (please complete the following information):**
 - OS: Debian (but under Windows 10 WSL2)
 - Version: bookworm
 - Mode: Desktop
 - Browser (if running in server mode): didn't get that far, but would have been Chrome :P
 - Package type: deb

```
root@MS4CEDFBBDD3CA:~# apt-cache show --no-all-versions pgadmin4-{desktop,server} | grep Depends
Depends: pgadmin4-server (= 7.5), libatomic1, xdg-utils
Depends: python3, libpq5 (>= 11.0), libgssapi-krb5-2
root@MS4CEDFBBDD3CA:~# dpkg --no-pager -l pgadmin4-desktop pgadmin4-server libatomic1 xdg-utils python3 libpq5 libgssapi-krb5-2
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version        Architecture Description
+++-======================-==============-============-=============================================================================================================================================================================================================
ii  libatomic1:amd64       12.2.0-14      amd64        support library providing __atomic built-in functions
ii  libgssapi-krb5-2:amd64 1.20.1-2       amd64        MIT Kerberos runtime libraries - krb5 GSS-API Mechanism
ii  libpq5:amd64           15.3-0+deb12u1 amd64        PostgreSQL C client library
ii  pgadmin4-desktop       7.5            amd64        The desktop user interface for pgAdmin. pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL, the most advanced Open Source database in the world.
ii  pgadmin4-server        7.5            amd64        The core server package for pgAdmin. pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL, the most advanced Open Source database in the world.
ii  python3                3.11.2-1+b1    amd64        interactive high-level object-oriented language (default python3 version)
ii  xdg-utils              1.1.3-4.1      all          desktop integration utilities from freedesktop.org
```

**Additional context**

I don't think this is related to me running under WSL, but rather that pgadmin needs libnss3 but doesn't say so.

**Comment by miiichael** [comment]
Why would that help? The postgresql-client, obviously, does not provide libnss3.

Also, postgresql-client is already installed.
```
root@MS4CEDFBBDD3CA:~# dpkg -l|grep postgres
ii  postgresql-client                 15+248                          all          front-end programs for PostgreSQL (supported version)
ii  postgresql-client-15              15.3-0+deb12u1                  amd64        front-end programs for PostgreSQL 15
ii  postgresql-client-common          248                             all          manager for multiple PostgreSQL client versions
ii  postgresql-common                 248                             all          PostgreSQL database-cluster manager
root@MS4CEDFBBDD3CA:~# apt-cache show --no-all-versions $(dpkg -l|awk '/postgres/ {print $2}')|grep -e ^Package -e ^Depends -e ^$
Package: postgresql-client
Depends: postgresql-client-15

Package: postgresql-client-15
Depends: libpq5 (>= 15.3), postgresql-client-common (>= 182~), sensible-utils, libc6 (>= 2.34), liblz4-1 (>= 0.0~r127), libreadline8 (>= 6.0), libssl3 (>= 3.0.0), libzstd1 (>= 1.5.2), zlib1g (>= 1:1.1.4)

Package: postgresql-client-common
Depends: netbase, perl:any

Package: postgresql-common
Depends: adduser, debconf (>= 0.5.00) | debconf-2.0, libjson-perl, lsb-base (>= 3.0-3), postgresql-client-common (= 248), ssl-cert (>= 1.0.11), ucf, perl:any
```
You shouldn't rely on other packages to install your own dependencies for you.

**Comment by akshay-joshi** [comment]
Hi @miiichael 

pgAdmin 4 desktop mode is developed using [NW.js](https://nwjs.io/). NW.js uses libnss3.so file. On some googling, I have found one [solution](https://github.com/nwjs/nw.js/issues/3134#issuecomment-337608686) which is nothing but to install libnss3. 

We haven’t faced any such issue.

**Comment by miiichael** [comment]
Yes, I already know you can work around this by manually installing libnss3. My point is that the package manager (dpkg+apt) has the facility to allow packages (such as pgadmin) to specify their own dependencies so that users don't have to do extra manual steps in order to get stuff to work. 🙄 

It's probably not a common error because pgadmin is often installed on machines that already has something else installed (eg. web browsers) that depend on libnns3.

The pgadmin Debian package needs to specify that it depends on libnns3.

**Comment by Sophist-UK** [comment]
Having manually installed `libnss3` I get a similar message about `libasound2`.

**Comment by Sophist-UK** [comment]
Also needed to add `ln -s /usr/pgadmin4/bin/pgadmin4 /usr/bin` in order not to have to give the full path.

**Comment by yogeshmahajan-1903** [comment]
@Sophist-UK 
I am not able to reproduce issue after remove libnss3 also. Now pgAdmin uses electron instead of NW.js. libnss3 was dependency for NW.js. Can you please try installing snapshot from [here](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/)?

**Comment by bkvaiude** [comment]
I was able to get pgadmin4 to launch by installing the following packages:
```
  529  sudo apt-get install libnss3-dev
  531  sudo apt-get install libgbm-dev
  536  sudo apt-get install libasound-dev
```
