### ISSUE TITLE
SchemaDiffTool: utilities exclude the SET directive from the function header in compare mode.

### ISSUE THREAD

**Issue by firstDismay** [pgadmin-org/pgadmin4#6651]
Hi
Schema diff utilities exclude the SET directive from the function header in compare mode.
Reproducing the problem:
1. Create a copy of the database that has a function containing the SET directive
2. Modify the function and perform the comparison.
The resulting script lacks the SET directive in the function:

```
CREATE OR REPLACE FUNCTION bpd.class_del(
iid bigint)
    RETURNS void
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE SECURITY DEFINER PARALLEL UNSAFE
    <--SET search_path=bpd, err-->
AS $BODY$
```

**Comment by yogeshmahajan-1903** [comment]
Working fine.
