### ISSUE TITLE
Stylesheets are missing in source code of pgadmin4 7.x

### ISSUE THREAD

**Issue by epolkerman** [pgadmin-org/pgadmin4#6656]
Build pgAdmin4 7.x from source code. Source downloaded from https://www.pgadmin.org/download/pgadmin-4-source-code/

Used python venv for building all necessary python modules in requirements.txt. Configured pgAdmin4 to run in server mode with apache httpd as webserver.

**To reproduce**
Behaviour as described below is reproducable with all source code downloads for pgAdmin4 v7.x

**Expected behavior**

Expected to see the login page and be able to login. However I get a login page without any styling:
![login_page_without_style](https://github.com/pgadmin-org/pgadmin4/assets/42344784/8f6d1e7a-c185-4bc1-8b86-36a52176071e)

and after logging in it stucks in screen Loading pgAdmin4 v7.x:
![Stuck_on_screen](https://github.com/pgadmin-org/pgadmin4/assets/42344784/ae3e7a0a-61ee-4f23-8dce-81233bd9acf5)

**Error message**

In the error log of apache httpd following is listed:
[Fri Aug 04 10:57:06.150094 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372] 2023-08-04 10:57:06,145: ERROR\tpgadmin:\t404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[Fri Aug 04 10:57:06.150156 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372] Traceback (most recent call last):
[Fri Aug 04 10:57:06.152402 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
[Fri Aug 04 10:57:06.152727 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]     rv = self.dispatch_request()
[Fri Aug 04 10:57:06.152757 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
[Fri Aug 04 10:57:06.153076 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Fri Aug 04 10:57:06.153106 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 713, in <lambda>
[Fri Aug 04 10:57:06.153194 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
[Fri Aug 04 10:57:06.153218 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/flask/scaffold.py", line 331, in send_static_file
[Fri Aug 04 10:57:06.153234 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]     return send_from_directory(
[Fri Aug 04 10:57:06.153250 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/flask/helpers.py", line 590, in send_from_directory
[Fri Aug 04 10:57:06.153267 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
[Fri Aug 04 10:57:06.153283 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/werkzeug/utils.py", line 587, in send_from_directory
[Fri Aug 04 10:57:06.153299 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372]     raise NotFound()
[Fri Aug 04 10:57:06.153315 2023] [wsgi:error] [pid 9691:tid 139706603849472] [remote 10.255.0.2:37372] werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[Fri Aug 04 10:57:06.154972 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374] 2023-08-04 10:57:06,152: ERROR\tpgadmin:\t404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[Fri Aug 04 10:57:06.155017 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374] Traceback (most recent call last):
[Fri Aug 04 10:57:06.155036 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
[Fri Aug 04 10:57:06.155052 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]     rv = self.dispatch_request()
[Fri Aug 04 10:57:06.155068 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
[Fri Aug 04 10:57:06.155101 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Fri Aug 04 10:57:06.155119 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 713, in <lambda>
[Fri Aug 04 10:57:06.155136 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
[Fri Aug 04 10:57:06.155152 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/flask/scaffold.py", line 331, in send_static_file
[Fri Aug 04 10:57:06.155169 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]     return send_from_directory(
[Fri Aug 04 10:57:06.155185 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/flask/helpers.py", line 590, in send_from_directory
[Fri Aug 04 10:57:06.155201 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
[Fri Aug 04 10:57:06.155217 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]   File "/usr/pgpure/pgadmin4/venv/lib64/python3.9/site-packages/werkzeug/utils.py", line 587, in send_from_directory
[Fri Aug 04 10:57:06.155234 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374]     raise NotFound()
[Fri Aug 04 10:57:06.155250 2023] [wsgi:error] [pid 9691:tid 139706595456768] [remote 10.255.0.2:37374] werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Debugging in the browser (in this case Chrome) show a 404 on several stylesheets and js files:
![browser_debug](https://github.com/pgadmin-org/pgadmin4/assets/42344784/dbadd107-74b4-45c4-a4fb-7f2795c9be5d)

Clicking on e.g. style.ccs shows:
![browser_debug2](https://github.com/pgadmin-org/pgadmin4/assets/42344784/ea0c1732-a943-4c5c-bfc1-b5b8823e7538)

I checked the requested file path on de webserver, but there is no directory 'generated' with the requested stylesheets and js files in /web/pgadmin/static/js!!!

**Additional info**
I have compared the source code of pgAdmin4 v6.21 (because that works as expected) with the source code of v7.x

The source code of v6.21 has a directory `generated` in `/pgadmin4-6.21/web/pgadmin/static/js`
![source_code_v6 21](https://github.com/pgadmin-org/pgadmin4/assets/42344784/6a9cbad6-04ee-409d-99a7-5c17a5fb5556)

However the source code of v7.x does not have this directory.
![source_code_v7 5](https://github.com/pgadmin-org/pgadmin4/assets/42344784/f950b361-8c8c-43dc-92bf-41301ceb55d8)

**Desktop (please complete the following information):**
 - OS: Rocky Linux 8.8
 - Version: 7.x
 - Mode: Server with apache httpd
 - Browser: Chrome, Firefox
 - Package type: Python 3.9 venv build from source package

**Comment by akshay-joshi** [comment]
Hi @epolkerman 

We have removed the generated folder from 7.x. Please follow the steps mentioned in the README file to compile the source which will create the generated folder.
