### ISSUE TITLE
Use of Semantic Versioning for Docker images

### ISSUE THREAD

**Issue by ChrisJBurns** [pgadmin-org/pgadmin4#6658]
Could we follow a [Semantic Versioning ](https://semver.org/) for the tagging of the [Docker images](https://hub.docker.com/r/dpage/pgadmin4/)? As the versions themselves seem to be minor or major increments, I don't think there would be any harm in making semantic versioned Docker image tags. So `7.5` becomes `7.5.0`. This is because a lot of organisations may have multiple technical operators in place that basically form function around SemVer. Otherwise they'd be forced to have to specify custom regex's to recognise the pgadmin tag as a valid version.

**Comment by adityatoshniwal** [comment]
@dpage Should we implement this?

**Comment by dpage** [comment]
We can create an additional tag with .0 added to it - I don't see any problem with that.

We're not going to adopt SemVer though - both pgAdmin and PostgreSQL moved away from it years ago as it doesn't really fit the way we work.

**Comment by akshay-joshi** [comment]
As discussed and suggested by Dave we have added the tag with .0 from v8.11
