### ISSUE TITLE
PgAdmin 7.4 gives connection problems with Prostgresql 12

### ISSUE THREAD

**Issue by TTEgit** [pgadmin-org/pgadmin4#6659]
Hi,

I am using postgresql 12 and recently installed pGAdmin 7.4. When I use a query that gives many hits (over 186000) the connection to the server is lost. I installed version 7.2 again and the problem is solved.

When I run the same query directly on the server there is no problem. The problem only exists when I use PgAdmin on a remote computer.

Regards,
Simone Schipper
TTE consultants

**Comment by huangzhuohua** [comment]
this bug had fixed in 7.5, or you can downgrade to 7.3
