### ISSUE TITLE
OAUTH with Github fails

### ISSUE THREAD

**Issue by ThatDeveloper** [pgadmin-org/pgadmin4#6662]
**Describe the bug & To Reproduce**

Using `docker-compose` to run `dpage/pgadmin4:latest`.
Useing a volume to set `/pgadmin4/config_local.py` with:
```
AUTHENTICATION_SOURCES = ['oauth2']
OAUTH2_AUTO_CREATE_USER = True
OAUTH2_CONFIG = [{
    'OAUTH2_NAME': 'github',
    'OAUTH2_DISPLAY_NAME': 'Github',
    'OAUTH2_CLIENT_ID': 'xxx',
    'OAUTH2_CLIENT_SECRET': 'xxx',
    'OAUTH2_TOKEN_URL': 'https://github.com/login/oauth/access_token',
    'OAUTH2_AUTHORIZATION_URL': 'https://github.com/login/oauth/authorize',
    'OAUTH2_API_BASE_URL': 'https://api.github.com/',
    'OAUTH2_USERINFO_ENDPOINT': 'user',
    'OAUTH2_SCOPE': 'openid,email,profile,read:user,user:email',
    'OAUTH2_USERNAME_CLAIM': 'email',
    'OAUTH2_ICON': 'fa-github',
    'OAUTH2_BUTTON_COLOR': '#3253a8',
}]
```

I tried hundreds of combinations with `OAUTH2_SCOPE`. With spaces like in the docs, with and without single scopes, with full scopes, etc. But whenever I press "Login with Github" and authorize the OAUTH App, I get redirected back and see this:
![image](https://github.com/pgadmin-org/pgadmin4/assets/12497431/0aee5f3b-56ab-40d6-89fc-26b639930277)

**Expected behavior**

That it works and that there is no "None".

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04
 - Mode: Server
 - Browser (if running in server mode): Chrome
 - Package type: Container

**Comment by adityatoshniwal** [comment]
Hi @ThatDeveloper,
Your `OAUTH2_USERINFO_ENDPOINT` looks suspicious. `'OAUTH2_USERINFO_ENDPOINT': 'https://api.github.com/user'` works for me. Can you try this once?

**Comment by ThatDeveloper** [comment]
> Hi @ThatDeveloper, Your `OAUTH2_USERINFO_ENDPOINT` looks suspicious. `'OAUTH2_USERINFO_ENDPOINT': 'https://api.github.com/user'` works for me. Can you try this once?

Per your docs, it looks like it must be a word. https://www.pgadmin.org/docs/pgadmin4/latest/oauth2.html
`User Endpoint, ex: user (for github) and useinfo (for google)`

I just tried it and I get the same error. I verfified the change with `docker exec -it pgadmin cat config_local.py`


Would you be able to share the config you use that works for you?

**Comment by adityatoshniwal** [comment]
Hi @ThatDeveloper,
Below is the config which worked for me:
```
        'OAUTH2_NAME': 'Github',
        'OAUTH2_DISPLAY_NAME': 'Github',
        'OAUTH2_CLIENT_ID': 'xxxxxxx',
        'OAUTH2_CLIENT_SECRET': 'xxxxxxx',
        'OAUTH2_TOKEN_URL': 'https://github.com/login/oauth/access_token',
        'OAUTH2_AUTHORIZATION_URL': 'https://github.com/login/oauth/authorize',
        'OAUTH2_SERVER_METADATA_URL': None,
        'OAUTH2_API_BASE_URL': 'https://api.github.com/',
        'OAUTH2_USERINFO_ENDPOINT': 'https://api.github.com/user',
        'OAUTH2_USERNAME_CLAIM': None,
        'OAUTH2_ICON': 'fa-github',
        'OAUTH2_BUTTON_COLOR': '#0000ff',
```

**Comment by ThatDeveloper** [comment]
> Hi @ThatDeveloper, Below is the config which worked for me:
> 
> ```
>         'OAUTH2_NAME': 'Github',
>         'OAUTH2_DISPLAY_NAME': 'Github',
>         'OAUTH2_CLIENT_ID': 'xxxxxxx',
>         'OAUTH2_CLIENT_SECRET': 'xxxxxxx',
>         'OAUTH2_TOKEN_URL': 'https://github.com/login/oauth/access_token',
>         'OAUTH2_AUTHORIZATION_URL': 'https://github.com/login/oauth/authorize',
>         'OAUTH2_SERVER_METADATA_URL': None,
>         'OAUTH2_API_BASE_URL': 'https://api.github.com/',
>         'OAUTH2_USERINFO_ENDPOINT': 'https://api.github.com/user',
>         'OAUTH2_USERNAME_CLAIM': None,
>         'OAUTH2_ICON': 'fa-github',
>         'OAUTH2_BUTTON_COLOR': '#0000ff',
> ```

Hi @adityatoshniwal 

Sadly this does not work. With your config I get this:
![image](https://github.com/pgadmin-org/pgadmin4/assets/12497431/c84bc04a-1b25-43f9-800c-2bde29bd8ea0)

**Comment by yogeshmahajan-1903** [comment]
@ThatDeveloper 
Set 'OAUTH2_USERNAME_CLAIM': 'email', & try once.
If error persist, kindly share pgadmin logs.

**Comment by khushboovashi** [comment]
Hi,

On Wed, Aug 9, 2023 at 6:38 PM ThatDeveloper ***@***.***>
wrote:

> Hi @ThatDeveloper <https://github.com/ThatDeveloper>, Below is the config
> which worked for me:
>
>         'OAUTH2_NAME': 'Github',
>         'OAUTH2_DISPLAY_NAME': 'Github',
>         'OAUTH2_CLIENT_ID': 'xxxxxxx',
>         'OAUTH2_CLIENT_SECRET': 'xxxxxxx',
>         'OAUTH2_TOKEN_URL': 'https://github.com/login/oauth/access_token',
>         'OAUTH2_AUTHORIZATION_URL': 'https://github.com/login/oauth/authorize',
>         'OAUTH2_SERVER_METADATA_URL': None,
>         'OAUTH2_API_BASE_URL': 'https://api.github.com/',
>         'OAUTH2_USERINFO_ENDPOINT': 'https://api.github.com/user',
>         'OAUTH2_USERNAME_CLAIM': None,
>         'OAUTH2_ICON': 'fa-github',
>         'OAUTH2_BUTTON_COLOR': '#0000ff',
>
> Hi @adityatoshniwal <https://github.com/adityatoshniwal>
>
> Sadly this does not work. With your config I get this:
> [image: image]
> <https://user-images.githubusercontent.com/12497431/259416189-c84bc04a-1b25-43f9-800c-2bde29bd8ea0.png>
>
This means your GitHub account has no public email id set. Please set that
and check with the same config.

**Comment by ThatDeveloper** [comment]
Thank you. I tried both and I got it working. But with the above configuration, everyone who knows the URL of pgadmin and has a github account can sign in. How could I restrict it so only certain organization can?

**Comment by adityatoshniwal** [comment]
@ThatDeveloper Currently, organization is not supported. You can raise a separate request for that.
Closing this one.
