### ISSUE TITLE
The non-editable fields(Constrains and expression) should be in grey colour for the index

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6663]
The non-editable fields should be in grey colour for index.

**To Reproduce**

Scenarios 1:

1. Go to the query tool
And create the following Index

CREATE UNIQUE INDEX ab_in
    ON public.dept USING btree
    (deptno ASC NULLS LAST)
    INCLUDE(deptno)
    WITH (deduplicate_items=True)
;
2. Index created
3.  Go into the properties
4. Click on the definition
5.  See the constraints tab
6. It is not editable
7. But the colour is white and it should be grey

Scenarios 2:
1. create a new index and provide the name
2. Click on Columns
3.  deselect Is Expression
4. See the expression tab
5. it is not editable
6. It should be in grey colour

**Expected behavior**

The non-editable fields should be in grey colour

**Screenshots**

<img width="1513" alt="Screen Shot 2023-08-08 at 2 10 39 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/d84037a3-a195-45fd-b09d-2cd4681a9b61">
<img width="1510" alt="Screen Shot 2023-08-08 at 2 15 13 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/7610a720-01e7-4273-8afc-40a0ab679400">

**Desktop (please complete the following information):**
 - OS: [ALL]
 - Version: [e.g. 7.5]
 - Mode: [All]
 - Package type: [All]

**Comment by adityatoshniwal** [comment]
Since the mentioned fields are using CodeMirror SQL control, it will not be possible to change the background colors. Closing.
