### ISSUE TITLE
pgAdmin crashes when accessing the query history tab when the query history contains many items and/or large items

### ISSUE THREAD

**Issue by vnicolici** [pgadmin-org/pgadmin4#6666]
**Describe the bug**

I set the query history limit to 5000 (MAX_QUERY_HIST_STORED=5000), which in my case would keep about a week of history when I do a lot of queries. After accumulating history for a while, including some large history items, over 10 MB each, pgAdmin started crashing to desktop when accessing the query history tab.

**To Reproduce**

1. Set MAX_QUERY_HIST_STORED=5000
2. Open pgAdmin
3. Connect to a database
4. Open a query tool
5. Run thousands of queries on the same database, including some large SQL scripts, around 15 MB of SQL; by script I mean SQL queries separated by semicolons. You may want to start with the large scripts first, in case the history item size the trigger for the problem, not the number of history entries.
6. Attempt to access the query history tab - the app will crash
7. Reopen the app
8. Connect to the same database
9. Open a query tool
10. The app will try to show the query history, then it will crash again

**Expected behavior**

The app shouldn't crash to desktop and should display the query history.

**Error message**

There is no error message. The app just closes, after showing the "Fetching history..." message.

**Screenshots**

This is how it looks before crashing:

![image](https://github.com/pgadmin-org/pgadmin4/assets/2158971/fe3e430e-bfbb-4bdc-abe5-b966840c9722)

**Desktop (please complete the following information):**
 - OS: Windows 11 10.0.22621.1992
 - Version: 7.5 ; the issue can also be reproduced on pgAdmin 4 v7.3
 - Mode: Desktop
 - Browser (if running in server mode): N/A
 - Package type: Windows exe

**Additional context**

The log doesn't contain anything interesting, just these two lines recorded at each startup:

```
2023-08-08 16:45:27,358: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance.
2023-08-08 16:45:27,358: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
```

The Windows Event Viewer doesn't seem to show anything about the crash either.

The problem is 100% reproducible on my system.

I checked the query_history table from pgadmin4.db, there are currently 9582 records in the table, and 2359 of those records seem to be history entries from the affected database.

Unfortunately it seems that at some point pgAdmin stopped storing query history in JSON format in this table, which makes it harder to access the history with a SQLite database browser when the app is unable to do it. I now have to use a hex decoder to access the JSON from the pgadmin4.db database.

I'm not sure if the issue is caused by the number of items in the history, or the size of some of the items in the history, or both.

Running

```
select max(length(query_info)) from query_history;
```

returned 27324404. Since each char is encoded as two when converted to hex, it seems the JSON with the history for my largest SQL script is 13662202 bytes long. So the largest SQL script from the history is a bit under 14 MB (28 MB hex encoded).

Running 

```
select sum(length(query_info)) from query_history where sid = 18;
```

returns 122770206, so around 123 MB total hex encoded, which would be around 62MB of JSONs. sid 18 is the affected database. The other databases only have about 6MB of hex history in total (3 MB of JSON).

Since fixing this issue might take a while, what would be an workaround for this problem, that wouldn't involve losing the entire history? I could try to clear the larger entries from the SQLite query_history table, but I'm not sure if that could cause problems or not, and if I need to update the srno column as well after deleting the large items.

**Comment by adityatoshniwal** [comment]
Unfortunately, there is no workaround we can think of right now. I can may be check the code once and tell you the place where you can put some kind of limit for the number of records to be fetched.

**Comment by vnicolici** [comment]
OK, thanks, @adityatoshniwal . I'll experiment with deleting records manually from the history table, starting with the large ones.

**Comment by vnicolici** [comment]
I ran this:

```
delete from query_history where length(query_info) > 10000000;
```

which deleted 15 large history entries. It doesn't crash anymore after doing this, hopefully it won't cause other issues. So it doesn't seem to be the number of history entries causing the issue, but their size. I'll do a bit more troubleshooting to try to determine the exact cause.

**Comment by vnicolici** [comment]
I made a backup copy of the SQLite database, then deleted all the records from the query history table, then I ran a large script, about 15 MB. So now there is a single 30MB record in the query_history table (2x due to hex encoding), and the issue can still be reproduced. So it's clearly the size of the items, not the number of items causing the problem. I'll now try to determine the approximate size where this starts happening. Once I determine that, I'll try to see if two history items of half the size still cause the same problem.

**Comment by vnicolici** [comment]
I've been able to determine that a 2MB script (4MB hex encoded) doesn't cause the problem, but a 4MB script (8MB hex encoded) does. Running the 2MB script twice, creating 2 x 4MB history entries, for a total of 8MB hex encoded doesn't trigger the problem.

So, based on what I've seen so far, this has nothing to do with the MAX_QUERY_HIST_STORED parameter, the number of history entries, or the total size of the history entries. Instead, large individual history entries seem to trigger the problem, SQL scripts larger than 4MB (8MB hex encoded) for example.

Also, based on the behavior I observed, this happens when the query history tab tries to render the details pane on the right, which is very slow even for the 2MB scripts, and it crashes for the 4MB scripts.

As for possible solutions, I'm not sure. I guess the simplest one would be not to store items that are larger than a reasonable size in history, or truncate them to a smaller size. Perhaps 1MB would be a reasonable size. The other would be to store the complete item, but not render a preview for those over that size, or render only a partial preview.  Optimizing the preview pane to allow larger sizes might also be an option, but I'm not sure if it's feasible and if it's worth the effort.

**Comment by dpage** [comment]
I agree with not storing the query if the underlying issue is a dependency limitation that we cannot fix.

However, I would still store the history entry; just replace the SQL with something like:

`-- Query text not stored as it exceeds X MB`

**Comment by cmarrerodb** [comment]
I have de exact same problem and depend a lot of pgAdmin; haven´r been able to use it for the last few weeks; tried select max(length(query_info)) from query_history; but cant find query_history; query history is a very usefull tool, but i'd prefer to disabke it in order to continue using pgAdmin; can help?

**Comment by anilsahoo20** [comment]
Tested and verified on candidate build: https://developer.pgadmin.org/builds/2023-10-17-1/
Environment: macOSX Ventura 13.4.1
Package: arm64
