### ISSUE TITLE
PG Admin 4 Crashes Upon Launch (Mac) Days After Working Beautifully

### ISSUE THREAD

**Issue by jimmyjohns1900** [pgadmin-org/pgadmin4#6673]
PGAdmin 4 (pgadmin4-7.5-x86_64) was working just a week ago on my 2023 MacMini M2.  

Then, blaow! All of a sudden, I get this error when I'm trying to load up and the thing won't load past the friendly little blue and purple screen. 
![loadyjointicantpass](https://github.com/pgadmin-org/pgadmin4/assets/99456803/4dc9be2f-babc-431e-90df-bf59216e4cda)

🥺 My MacOS wasn't up to date, so I was like, aight, let me go ahead and update this joint. So now I'm on Ventura 13.5. Still the same problem! 🫨 ! I don't know what to do! I just want to learn about these joins. 

I've attached my full crash report. Please, HALP! I don't want to keep using DBeaver!
[crashreport-jont.pdf](https://github.com/pgadmin-org/pgadmin4/files/12317427/crashreport-jont.pdf)

**Comment by adityatoshniwal** [comment]
Duplicates #6625.

**Comment by briannaburrell** [comment]
I'm having the same issue currently! hopefully it Gets figured out

**Comment by mukhran** [comment]
I'm having the same issue. Mac M2. worked perfectly until yesterday. I updated yesterday and now it crushes, can't open
