### ISSUE TITLE
If user change any data type of any column in foreign table then column name "none" is displayed in SQL

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6674]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

**To Reproduce**

1. create the following SQL:
CREATE FOREIGN DATA WRAPPER fdw1;
CREATE SERVER fr
    FOREIGN DATA WRAPPER fdw1;
CREATE USER MAPPING FOR postgres SERVER fr;
CREATE FOREIGN TABLE IF NOT EXISTS public.tab1(
    abcd "char" NULL
)
    SERVER fr;

2. Now go into properties on tab1
3.  select column
4. change the datatype to bit
5. Go to SQL
6. following SQL is displayed:

ALTER FOREIGN TABLE IF EXISTS public.tab1
    RENAME COLUMN abcd TO None;

ALTER FOREIGN TABLE IF EXISTS public.tab1
    ALTER COLUMN None DROP NOT NULL;

ALTER FOREIGN TABLE IF EXISTS public.tab1
    ALTER COLUMN None TYPE bit;

ALTER FOREIGN TABLE IF EXISTS public.tab1
    ALTER COLUMN None SET STATISTICS -1;

**Expected behavior**

the data type should be changed successfully in the foreign table

**Screenshots**

<img width="1326" alt="Screen Shot 2023-08-11 at 11 07 06 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/83379e89-acc5-4a9b-8d2f-86c9143353b4">

**Desktop (please complete the following information):**
 - OS: [ALL]
 - Version: [7.5]
 - Mode: [All]
 - Package type: [ALL]

**Additional context**

**Comment by akshay-joshi** [comment]
Tested on snapshot build 2023-09-28
