### ISSUE TITLE
[feature request]  Add option to set custom binary and title for the psql tool

### ISSUE THREAD

**Issue by cocoonkid** [pgadmin-org/pgadmin4#6679]
**Describe the solution you'd like**

A setting where I could for example set pgcli binary path  to be used instead of psql.
And also change the title of the link in the main dashbaord.

pgcli is so much nicer :)

Thanks for your consideration

**Comment by nikhil-mohite** [comment]
HI @cocoonkid ,
There is no plan to implement this in the near future.
