### ISSUE TITLE
Table columns Properties view, add Data type

### ISSUE THREAD

**Issue by naxels** [pgadmin-org/pgadmin4#6685]
**Describe the solution you'd like**

In pgAdmin 4 v7.5, when you open (a server) -> Databases -> (a database) -> Schemas -> (a schema) -> Tables -> (a table) -> Columns.
All you see is the "Name" and "Comment" columns in the Properties tab, it would be very helpful to also see the Data type in a "Data type" column.
![image](https://github.com/pgadmin-org/pgadmin4/assets/3195443/aa5d4e94-531d-4766-ba82-4f5a8a322e88)

**Describe alternatives you've considered**

I tried checking the Table itself for the list of columns/types, but couldn't find it either.

Expanding the Columns section in the Object Explorer is a possibility but then you have to navigate to every single column to see the Definition data.

The only thing that easily works for getting all columns & types in 1 overview is:
Right click on the (a table) -> Properties -> Columns tab, however this is more of an edit tab/view:
![image](https://github.com/pgadmin-org/pgadmin4/assets/3195443/efd01394-818d-4491-b6b1-ef312619ee93)

More hands-on would be to Right click on the (a table) -> Scripts -> CREATE Script, but that takes even longer to populate and is not easy for non-admin users.

**Additional context**

I personally think that it would be very helpful to see the data type at a glance in the solution I propose as it's easy to navigate to and can tell you much more than just the column name.
Having to right click on every table (or generate DDL) 

We could argue, well then the other columns from the Right click -> Properties should also be visible and maybe that would be helpful to people as well.

Thank you very much for considering!

**Comment by adityatoshniwal** [comment]
This duplicates #2411.
