### ISSUE TITLE
Virtualenv pip install on FreeBSD 13.2 installs 6.21; error installing latest

### ISSUE THREAD

**Issue by pacija** [pgadmin-org/pgadmin4#6691]
**Describe the bug**

Following instruction on [Download](https://www.pgadmin.org/download/pgadmin-4-python/) page gives me pgadmin4 6.21.

`pip install pgadmin4==7.5` errors out.

**To Reproduce**

```
sudo -u pgadmin virtualenv /usr/local/www/testpg
source /usr/local/www/testpg/bin/activate.csh
sudo -u pgadmin pip install pgadmin4==7.5
```

**Expected behavior**

`pip install pgadmin4` should install latest version.
`pip install pgadmin4==7.5` should not error out.

**Error message**

```
INFO: pip is looking at multiple versions of psycopg[binary] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement psycopg-binary==3.1.9; extra == "binary" (from psycopg[binary]) (from versions: none)
ERROR: No matching distribution found for psycopg-binary==3.1.9; extra == "binary"
```

**Desktop (please complete the following information):**
 - OS: FreeBSD
 - Version: 13.2
 - Mode: Server
 - Browser (if running in server mode): N/A
 - Package type: Python

**Comment by adityatoshniwal** [comment]
@pacija  What is the python version?

**Comment by pacija** [comment]
```
% pkg info -x python
python39-3.9.17
```

```
(testpg) % sudo -u pgadmin pip list
Package    Version
---------- -------
pip        23.2.1
setuptools 68.0.0
sqlite3    0.0.0
Tkinter    0.0.0
wheel      0.41.0
```

**Comment by khushboovashi** [comment]
Please try the below command and let us know the output.
`pip install "psycopg[binary]"`

**Comment by pacija** [comment]
Here:

(pgdebug) me@mybox:~ % pip install "psycopg[binary]"
Collecting psycopg[binary]
  Obtaining dependency information for psycopg[binary] from https://files.pythonhosted.org/packages/01/27/89a0024ac7e7f872eccb5785707d4bc2162b8da8cb2fd4202813969a9952/psycopg-3.1.10-py3-none-any.whl.metadata
  Downloading psycopg-3.1.10-py3-none-any.whl.metadata (3.6 kB)
Collecting typing-extensions>=4.1 (from psycopg[binary])
  Obtaining dependency information for typing-extensions>=4.1 from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
  Downloading typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
INFO: pip is looking at multiple versions of psycopg[binary] to determine which version is compatible with other requirements. This could take a while.
Collecting psycopg[binary]
  Downloading psycopg-3.1.9-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.8/167.8 kB 3.2 MB/s eta 0:00:00
  Downloading psycopg-3.1.8-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.4/167.4 kB 6.2 MB/s eta 0:00:00
  Downloading psycopg-3.1.7-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.2/167.2 kB 14.2 MB/s eta 0:00:00
  Downloading psycopg-3.1.6-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.1/167.1 kB 38.1 MB/s eta 0:00:00
  Downloading psycopg-3.1.5-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.1/167.1 kB 39.3 MB/s eta 0:00:00
  Downloading psycopg-3.1.4-py3-none-any.whl (165 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.2/165.2 kB 40.8 MB/s eta 0:00:00
  Downloading psycopg-3.1.3-py3-none-any.whl (165 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.0/165.0 kB 38.4 MB/s eta 0:00:00
INFO: pip is still looking at multiple versions of psycopg[binary] to determine which version is compatible with other requirements. This could take a while.
  Downloading psycopg-3.1.2-py3-none-any.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 kB 16.5 MB/s eta 0:00:00
  Downloading psycopg-3.1.1-py3-none-any.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.4/164.4 kB 37.8 MB/s eta 0:00:00
  Downloading psycopg-3.1-py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.9/163.9 kB 40.6 MB/s eta 0:00:00
  Downloading psycopg-3.0.18-py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 32.8 MB/s eta 0:00:00
  Downloading psycopg-3.0.17-py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.3/143.3 kB 13.1 MB/s eta 0:00:00
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading psycopg-3.0.16-py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.2/143.2 kB 33.7 MB/s eta 0:00:00
  Downloading psycopg-3.0.15-py3-none-any.whl (144 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.1/144.1 kB 16.4 MB/s eta 0:00:00
  Downloading psycopg-3.0.14-py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 32.7 MB/s eta 0:00:00
  Downloading psycopg-3.0.13-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 34.0 MB/s eta 0:00:00
  Downloading psycopg-3.0.12-py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.1/143.1 kB 34.1 MB/s eta 0:00:00
  Downloading psycopg-3.0.11-py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 33.6 MB/s eta 0:00:00
  Downloading psycopg-3.0.10-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.1/142.1 kB 10.5 MB/s eta 0:00:00
  Downloading psycopg-3.0.9-py3-none-any.whl (141 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.8/141.8 kB 33.7 MB/s eta 0:00:00
  Downloading psycopg-3.0.8-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.2/142.2 kB 34.2 MB/s eta 0:00:00
  Downloading psycopg-3.0.7-py3-none-any.whl (141 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.7/141.7 kB 33.3 MB/s eta 0:00:00
  Downloading psycopg-3.0.6-py3-none-any.whl (141 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.7/141.7 kB 32.5 MB/s eta 0:00:00
  Downloading psycopg-3.0.5-py3-none-any.whl (141 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.1/141.1 kB 34.6 MB/s eta 0:00:00
  Downloading psycopg-3.0.4-py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 kB 34.9 MB/s eta 0:00:00
  Downloading psycopg-3.0.3-py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.0/141.0 kB 35.8 MB/s eta 0:00:00
  Downloading psycopg-3.0.2-py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 kB 34.5 MB/s eta 0:00:00
  Downloading psycopg-3.0.1-py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 34.8 MB/s eta 0:00:00
  Downloading psycopg-3.0-py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.8/140.8 kB 34.3 MB/s eta 0:00:00
ERROR: Cannot install psycopg[binary]==3.0, psycopg[binary]==3.0.1, psycopg[binary]==3.0.10, psycopg[binary]==3.0.11, psycopg[binary]==3.0.12, psycopg[binary]==3.0.13, psycopg[binary]==3.0.14, psycopg[binary]==3.0.15, psycopg[binary]==3.0.16, psycopg[binary]==3.0.17, psycopg[binary]==3.0.18, psycopg[binary]==3.0.2, psycopg[binary]==3.0.3, psycopg[binary]==3.0.4, psycopg[binary]==3.0.5, psycopg[binary]==3.0.6, psycopg[binary]==3.0.7, psycopg[binary]==3.0.8, psycopg[binary]==3.0.9, psycopg[binary]==3.1, psycopg[binary]==3.1.1, psycopg[binary]==3.1.10, psycopg[binary]==3.1.2, psycopg[binary]==3.1.3, psycopg[binary]==3.1.4, psycopg[binary]==3.1.5, psycopg[binary]==3.1.6, psycopg[binary]==3.1.7, psycopg[binary]==3.1.8 and psycopg[binary]==3.1.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    psycopg[binary] 3.1.10 depends on psycopg-binary==3.1.10; extra == "binary"
    psycopg[binary] 3.1.9 depends on psycopg-binary==3.1.9; extra == "binary"
    psycopg[binary] 3.1.8 depends on psycopg-binary<=3.1.8 and >=3.1.6; extra == "binary"
    psycopg[binary] 3.1.7 depends on psycopg-binary<=3.1.7 and >=3.1.6; extra == "binary"
    psycopg[binary] 3.1.6 depends on psycopg-binary==3.1.6; extra == "binary"
    psycopg[binary] 3.1.5 depends on psycopg-binary==3.1.5; extra == "binary"
    psycopg[binary] 3.1.4 depends on psycopg-binary==3.1.4; extra == "binary"
    psycopg[binary] 3.1.3 depends on psycopg-binary==3.1.3; extra == "binary"
    psycopg[binary] 3.1.2 depends on psycopg-binary==3.1.2; extra == "binary"
    psycopg[binary] 3.1.1 depends on psycopg-binary==3.1.1; extra == "binary"
    psycopg[binary] 3.1 depends on psycopg-binary==3.1; extra == "binary"
    psycopg[binary] 3.0.18 depends on psycopg-binary==3.0.18; extra == "binary"
    psycopg[binary] 3.0.17 depends on psycopg-binary==3.0.17; extra == "binary"
    psycopg[binary] 3.0.16 depends on psycopg-binary==3.0.16; extra == "binary"
    psycopg[binary] 3.0.15 depends on psycopg-binary==3.0.15; extra == "binary"
    psycopg[binary] 3.0.14 depends on psycopg-binary==3.0.14; extra == "binary"
    psycopg[binary] 3.0.13 depends on psycopg-binary==3.0.13; extra == "binary"
    psycopg[binary] 3.0.12 depends on psycopg-binary==3.0.12; extra == "binary"
    psycopg[binary] 3.0.11 depends on psycopg-binary==3.0.11; extra == "binary"
    psycopg[binary] 3.0.10 depends on psycopg-binary==3.0.10; extra == "binary"
    psycopg[binary] 3.0.9 depends on psycopg-binary==3.0.9; extra == "binary"
    psycopg[binary] 3.0.8 depends on psycopg-binary==3.0.8; extra == "binary"
    psycopg[binary] 3.0.7 depends on psycopg-binary==3.0.7; extra == "binary"
    psycopg[binary] 3.0.6 depends on psycopg-binary==3.0.6; extra == "binary"
    psycopg[binary] 3.0.5 depends on psycopg-binary==3.0.5; extra == "binary"
    psycopg[binary] 3.0.4 depends on psycopg-binary==3.0.4; extra == "binary"
    psycopg[binary] 3.0.3 depends on psycopg-binary==3.0.3; extra == "binary"
    psycopg[binary] 3.0.2 depends on psycopg-binary==3.0.2; extra == "binary"
    psycopg[binary] 3.0.1 depends on psycopg-binary==3.0.1; extra == "binary"
    psycopg[binary] 3.0 depends on psycopg-binary==3.0; extra == "binary"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by adityatoshniwal** [comment]
Hi @pacija,
Can you also try `pip install "psycopg[binary]==3.1.9"`?

**Comment by adityatoshniwal** [comment]
Hi @pacija,
It looks like the required version of psycopg-binary is not available for FreeBSD
pgAdmin team doesn't maintain the installers for FreeBSD. You'll have to wait for the maintainers to make it working.
Unfortunately, we can't help you here.
Thanks.

**Comment by arunas-devoro** [comment]
Why psycopg[binary] is a requirement? pip install psycopg works with no error!
Solution that worked for me:

- download pgadmin4.whl
- wheel unpack <pgadmin4.whl>
- edit METADATA file and remove "[binary]" from line where psycopq is listed as requirement
- wheel pack <pgadmin4.whl>
- pip install ./pgadmin4.whl

Enjoy and hope this requirement for having binary packages will be lifted at some point.
