### ISSUE TITLE
I am having an issue my PGAdmin 4 won't open at all

### ISSUE THREAD

**Issue by R9JJAYL** [pgadmin-org/pgadmin4#6692]
Everytime I try to open PGAdmin 4 on my 13.5 (22G74) Mac OS is just says that it shut unexpectadly, does anyone know how to resolve this? I have uninstalled/  reinstalled multiple times

**Comment by yogeshmahajan-1903** [comment]
@R9JJAYL 
Try clearing the files here - ~/Library/Application Support/pgAdmin 4. Related to #6625

**Comment by i8enn** [comment]
> Try clearing the files here - ~/Library/Application Support/pgAdmin 4. Related to #6625

@yogeshmahajan-1903, @R9JJAYL this helped on apple silicon, after latest update to 7.5.

**Comment by enderkus** [comment]
For this, I manually installed pgadmin 4 7.4 and the problem is solved for now. This seems to be the best solution until the update arrives.

**Comment by nikhil-mohite** [comment]
The issue is fixed in pgAdmin 4 version 7.6
Duplicate of #6625
