### ISSUE TITLE
Cannot close query tool window when connection to server is lost after a query

### ISSUE THREAD

**Issue by anibal-acosta** [pgadmin-org/pgadmin4#6693]
If you run a simple select query and then the connection to server is lost (for example, VPN disconnected or internet failure) when try to close the window the tool show a message to "cancel, rollback or commit", no mather what you choose, the window si not closed. Tested in Version Pgadmin 7.5

**Comment by anilsahoo20** [comment]
Hi @anibal-acosta 
Can you please try with the latest released pgAdmin 4 version?

You can download from [here](https://www.pgadmin.org/download/).

**Comment by pravesh-sharma** [comment]
No response from the author, hence closing the issue.
