### ISSUE TITLE
Windows could not  download pgadmin 6.9

### ISSUE THREAD

**Issue by PenghaoJiang** [pgadmin-org/pgadmin4#6697]
I found some functions that could not use in the pgadmin 7.5, and our university needs to use pgadmin 6.9 for our course. How to download pgadmin6.9 in windows

**Comment by khushboovashi** [comment]
pgAdmin v6.9 is a very old version, and we do not support it currently. You can create the feature request if you have any specific requirements which were working on the older versions.
