### ISSUE TITLE
Crash due to Flask 2.3 removing before_app_first_request method

### ISSUE THREAD

**Issue by jlayt** [pgadmin-org/pgadmin4#6703]
Running pgadmin4 on openSuse using distro packages for pgadmin4 v7.4, Python 3.11,  and Flask v2.3 crashes with the following error:

```
File "/usr/lib/python3.11/site-packages/pgadmin4/pgadmin/utils/__init__.py", line 62, in __init__
  self.before_app_first_request(create_module_preference)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AuthenticateModule' object has no attribute 'before_app_first_request'. Did you mean: 'before_app_request'?
```

The Flask 2.3 release notes state the method was removed in 2.3 after being deprecated in 2.2 https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0. Relevant PR seems to be https://github.com/pallets/flask/issues/4605.

Current usage is:

https://github.com/pgadmin-org/pgadmin4/blob/eee7e1ae5336e28cc563c1395dc269a228b6e738/web/pgadmin/utils/__init__.py#L62

**Comment by khushboovashi** [comment]
pgAdmin team does not maintain OpenSUSE distro packages, and pgAdmin needs Flask v2.2.*
Please get in touch with OpenSUSE package maintainers for this issue.

**Comment by jlayt** [comment]
Does this mean you don't plan to support Flask 2.3 ever?
