### ISSUE TITLE
Failed login on pgAdmin in sub-directory leads to invalid redirect

### ISSUE THREAD

**Issue by akinzler** [pgadmin-org/pgadmin4#6704]
**Describe the bug**

pgAdmin4 is installed in a sub-directory /pgadmin instead of /. Now open the login page and enter an invalid login. You are redirected to / (invalid path) instead of something in /pgadmin
Everything else works after successful login.

**System:**
 - Server OS: Linux Gentoo
 - Version: 7.5
 - Mode: Server
 - Browser (if running in server mode): [e.g. chrome, safari] Chrome 115
 - Package type: python venv
 - Running via uwsgi and nginx

**Comment by yogeshmahajan-1903** [comment]
Duplicate if #5454

**Comment by eiacopini** [comment]
```
pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
     - geonode
     - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    port:
      - "5050:80"
     expose:
      - "5050"

location /pgadmin4 {
       set $upstream pgadmin4:80;
      
        proxy_set_header X-Script-Name /pgadmin4
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_pass http://$upstream/;
        proxy_redirect off;
}
```
This configuration worked fine until yersterday. 
Installing the same thing on another server now I have redirect error.
https://domain.cloud/pgadmin4/login?next=%2Fpgadmin4%2F

Error: This page does not redirect properly

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-08-29
