### ISSUE TITLE
Handel PostgreSQL max connection error in pgAdmin 4 UI

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#6706]
**Describe the bug**

pgAdmin 4 UI showing enter password dialog if PostgreSQL throws max connection error.
(I have set `max_connections=10` in `postgresql.conf`)
**To Reproduce**

1. Open query tool and run the long-running query (e.g: select pg_sleep(600))
2. Keep opening the Query tools in pgAdmin (run long running query in every opened Query Tool) until you get the `max_connection` reached error at the backend (For 10 connections it will need around 7 query tools)
<img width="978" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/69510038/1508093d-5693-4913-8fcc-bea2473f0b42">

3. If a user tries to open a new query tool, pgAdmin 4 UI shows enter server password dialog
![image](https://github.com/pgadmin-org/pgadmin4/assets/69510038/66286d10-9acb-4bd9-bc84-757cb7b6d77a)

5. Server is already connected and PostgreSQL refusing connections due to max_connection reached.
6. Even we enter the correct password to reconnect it keeps showing the same dialog 

**Expected behavior**

pgAdmin 4 should show a proper error message on UI if reached the max connections of PostgreSQL and should not ask for the server password.

**Desktop (please complete the following information):**
 - OS: macOS(Ventura 13.3)
 - Version: 7.5
 - Mode: Desktop and Server
 - Browser (if running in server mode): All

**Additional context**

**Comment by khushboovashi** [comment]
Closing the issue as the displayed error is already very easy to understand.
