### ISSUE TITLE
Unable to launch pgAdmin 4: The procedure entry point DiscardVirtualMemory could not be located

### ISSUE THREAD

**Issue by AnsonL11** [pgadmin-org/pgadmin4#6707]
I just installed PostgreSQL 14. However it failed to launch pgAdmin 4.

Error message: The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library C:\Program Files\PostgreSQL\14\pgAdmin 4\runtime\nw.dll

Here is my windows version.
- Window eddition: Windows 8.1
- System: 64-bit Operation System, x64-based processor
- pgAdmin 4 version: version 0.78
- Error message: The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library C:\Program Files\PostgreSQL\14\pgAdmin 4\runtime\nw.dll

**Comment by adityatoshniwal** [comment]
HI @AnsonL11,
Since pgAdmin v7.0, windows 10 and above is supported. Win 8.1 is not supported. Please check- https://www.pgadmin.org/download/pgadmin-4-windows/

**Comment by Chico123** [comment]
I have same issue in windows server 2012, somebody can help me?

**Comment by adityatoshniwal** [comment]
> https://www.pgadmin.org/download/pgadmin-4-windows/

Check the OS support here - https://www.pgadmin.org/download/pgadmin-4-windows/
