### ISSUE TITLE
'NoneType' object has no attribute 'pgconn'

### ISSUE THREAD

**Issue by msahajar** [pgadmin-org/pgadmin4#6710]
I recently installed postgresql 15 and pgadmin 4 with it. My database has postgis extension. All I am trying to do is very simple query to view data in kml with the query as follows:
`select sa2_name21, st_askml(geom) from sa2_2021_aust_gda2020`
The query runs fine but gives me a pop up asking if new session should be started since teh connection has been disconnected, I click continue then displays the error message "'NoneType' object has no attribute 'pgconn'"
I understand this is a bug that others have reported too, but none of the solutions worked for me. 

My trial didn't stop here. I tried to run the query again before sending this issue. I got a new message "exception: access violation writing 0x000001398C75B000". I noticed others havecome across similar issue but all of them heavy code and mostly in python. I'm just using pgadmin4.

Are there any suggestions please?

**Comment by khushboovashi** [comment]
On Wed, Aug 23, 2023 at 11:16 AM msahajar ***@***.***> wrote:

> I recently installed postgresql 15 and pgadmin 4 with it. My database has
> postgis extension. All I am trying to do is very simple query to view data
> in kml with the query as follows:
> select sa2_name21, st_askml(geom) from sa2_2021_aust_gda2020
> The query runs fine but gives me a pop up asking if new session should be
> started since teh connection has been disconnected, I click continue then
> displays the error message "'NoneType' object has no attribute 'pgconn'"
> I understand this is a bug that others have reported too, but none of the
> solutions worked for me.
>
> My trial didn't stop here. I tried to run the query again before sending
> this issue. I got a new message "exception: access violation writing
> 0x000001398C75B000". I noticed others havecome across similar issue but all
> of them heavy code and mostly in python. I'm just using pgadmin4.
>
> Are there any suggestions please?
>
Download and Install pgAdmin from https://www.pgadmin.org/download/. I
would suggest waiting till tomorrow as we are releasing pgAdmin v7.6
tomorrow.

Thanks,
Khushboo

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing the issue.
