### ISSUE TITLE
Materialized view size fields in "Statistics" not human-readable

### ISSUE THREAD

**Issue by alund-catt** [pgadmin-org/pgadmin4#6712]
**Describe the bug**

When viewing the Statistics tab for a Materialized View, the "Table size" and "Indexes size" fields do not use a human-readable format. Similarly, the "Total Size" column on the Statistics tab when selecting the parent Materialized Views node in the Object Explorer is not human-readable.

**To Reproduce**

1. Select a Materialized View in the Object Explorer
2. Click on the "Statistics" tab
3. See the Table size and Indexes size fields are not formatted in a human-readable style.

**Expected behavior**

All "size" fields on the Statistics tab should use a human-readable format.

**Screenshots**

![mv](https://github.com/pgadmin-org/pgadmin4/assets/32678346/cca65570-a00a-4a26-bec2-38b723f78a69)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 7.5
 - Mode: Desktop

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-09-11/

**Comment by adityatoshniwal** [comment]
> This tweak broke the sorting.

@ColaKola  https://github.com/pgadmin-org/pgadmin4/issues/6459
