### ISSUE TITLE
`Tools` -> `ERD Tool` is unavailable when no database instance is selected

### ISSUE THREAD

**Issue by ckvv** [pgadmin-org/pgadmin4#6713]
Just open pgerd file, this feature does not need to be disabled

![截屏2023-08-24 17 44 04](https://github.com/pgadmin-org/pgadmin4/assets/30174970/d5aade92-70fa-408b-a678-7c43513705b9)

**Comment by adityatoshniwal** [comment]
Hi @ckvv,
A database connection is required for fetching types and some other meta information. In this case, we can use the default maintenance DB if a server is selected. However, it will still require that you're connected to the server.
