### ISSUE TITLE
schema diff  ignore owner is invalid

### ISSUE THREAD

**Issue by jcjgithub** [pgadmin-org/pgadmin4#6715]
*
OS : win 10
pgAdmin version:  v7.6
postgresql version: 14

![d8676df7ab0db2531fb7dc3970650fb](https://github.com/pgadmin-org/pgadmin4/assets/66168320/50da84e4-03a4-4d96-9a49-63236ed2669e)
![d76c333a7928948d6ce452b60739942](https://github.com/pgadmin-org/pgadmin4/assets/66168320/a4bb5ef1-286f-465e-8278-cd597fbabcb7)
Even if I choose to this as if these two tables are different and give the difference, the expectation should be that when I choose to ignore these two tables should be treated as if there is no difference

**Comment by yogeshmahajan-1903** [comment]
@jcjgithub 
Looking at options populate in compare dropdown, pgAdmin version is not 7.6. Can you please check you pgAdmin version? Also 7.6 version is released y'day. Please try to install it.

**Comment by akshay-joshi** [comment]
@jcjgithub 

As Yogesh mentioned above, it seems the pgAdmin version is not 7.6. In 7.6 we have added two new options "Ignore Tablespace" and "Ignore Grants".
<img width="995" alt="Screenshot 2023-08-25 at 10 50 04 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/31038782-c5aa-437c-8080-81010e576013">

When users select "Ignore Owner" Schema Diff will ignore the ALTER query for Owner and if user selects "Ignore Grants" then the schema diff tool will ignore Grant/Revoke queries.

**Comment by jcjgithub** [comment]
thanks , sorry I write it wrongly , I'm currently using 7.5
