### ISSUE TITLE
pgAdmin4 fails to launch on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by rkoktan** [pgadmin-org/pgadmin4#6716]
# pgadmin4 
Traceback (most recent call last):
  File "/usr/bin/pgadmin4", line 5, in <module>
    from pgadmin4.pgAdmin4 import main
  File "/usr/lib/python3.11/site-packages/pgadmin4/pgAdmin4.py", line 49, in <module>
    import config
  File "/usr/lib/python3.11/site-packages/pgadmin4/config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/lib/python3.11/site-packages/pgadmin4/pgadmin/__init__.py", line 49, in <module>
    from pgadmin import authenticate
  File "/usr/lib/python3.11/site-packages/pgadmin4/pgadmin/authenticate/__init__.py", line 91, in <module>
    blueprint = AuthenticateModule(MODULE_NAME, __name__, static_url_path='')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pgadmin4/pgadmin/utils/__init__.py", line 62, in __init__
    self.before_app_first_request(create_module_preference)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AuthenticateModule' object has no attribute 'before_app_first_request'. Did you mean: 'before_app_request'?

**To Reproduce**

Launch pgadmin4 from the command line.

**Expected behavior**

It ought to launch the browser window and provide a login prompt.

AttributeError: 'AuthenticateModule' object has no attribute 'before_app_first_request'. Did you mean: 'before_app_request'?

If possible, include the full, unedited text of any error messages displayed.

N/A

**Desktop (please complete the following information):**
 - OS: OpenSUSE Tumbleweed 
 - Version: VERSION="20230822"
 - Mode: Desktop
 - Browser (if running in server mode): FF
 - Package type: RPM

**Additional context**

I think the build in OBS is failing on account of this?
https://build.opensuse.org/package/show/server:database:postgresql/pgadmin4

If I edit line 62 of /usr/lib/python3.11/site-packages/pgadmin4/pgadmin/utils/__init__.py as the error message suggests and change...
self.before_app_first_request(create_module_preference)
... to read...
self.before_app_request(create_module_preference)
...  it fixes the issue.  Although now I get the "Loading pgAdmin 4 v7.4..." screen that never goes anywhere... but that's another issue...

**Comment by simotek** [comment]
Looks like Flask 2.2 depreciated the method and flask 2.3 removed it https://stackoverflow.com/questions/73570041/flask-deprecated-before-first-request-how-to-update

**Comment by nikhil-mohite** [comment]
Hi @rkoktan ,
pgAdmin 4 doesn’t support Flask-2.3 yet. It is pinned to 2.2 in `requirements.txt`
