### ISSUE TITLE
In-App Update Feature for Seamless Monthly Upgrades

### ISSUE THREAD

**Issue by MaximeDan** [pgadmin-org/pgadmin4#6719]
**Describe the solution you'd like**

I propose the addition of an in-app update feature that allows users to download and install updates directly from within the pgAdmin tool. This would streamline the process for end-users and would be especially useful given the frequent (approximately monthly) update cycle for pgAdmin.

**Describe alternatives you've considered**
The current notification system within pgAdmin informs users about available updates and provides a link to the download page. While helpful, this system still requires users to manually download and install updates. An enhancement to this existing feature could include direct links to incremental patches, rather than full application downloads, to make the update process quicker and less intrusive.

**Additional context**
Other database management tools like DBeaver already offer in-app update features, making it more convenient for users to maintain the latest versions. Implementing this feature could improve user satisfaction and enhance the overall user experience with pgAdmin.

**Comment by khushboovashi** [comment]
Duplicates #5766.
Closing the issue.
