### ISSUE TITLE
Incorrect format (no indent) of SQL stored functions/procedures

### ISSUE THREAD

**Issue by VBarzionov** [pgadmin-org/pgadmin4#6720]
Indent formatting for stored functions disappears in the SQL-tab on right panel on main screen.

Indents made by TAB-characters (not sure about spaces).
Indents are shown correcty in "SQL Query" window.

You can fix this issue by switching "Preferences/SQL Formating/Comma-first notation".
After restart pgAdmin the issue returns.

**To reproduce**
1. Open PgAdmin (Indents may start display correctly after sometime)
2. Choose view "SQL-tab" on the right panel
3. Click in on Stored Function which has Indents

**Expected behavior**
See code with indents

**Screenshots**
![image](https://github.com/pgadmin-org/pgadmin4/assets/33849682/f4b12bbc-6796-49b9-9864-a4710f0604ac)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version:  7.6 (starts from at least 7.2 may be earlier)
 - Mode: Desktop
 - Package type: MSI

**Comment by adityatoshniwal** [comment]
This is fixed with https://github.com/pgadmin-org/pgadmin4/pull/6804. Major preference related changes are done in this PR, and it has automatically fixed this issue.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-10-26/
Environment: macOsx Ventura 13.4.1
Package: arm64
