### ISSUE TITLE
How to change syntax color for tables?

### ISSUE THREAD

**Issue by brettembrey** [pgadmin-org/pgadmin4#6722]
Hi,

I recently downloaded pgadmin 7.6 and I noticed when running SQL queries that the table syntax color has changed to white instead of blue. Is there a way to change it back or change it to a different color on my local machine as I do not see an option inside pgadmin to do so. 

Thank you.

**Comment by yogeshmahajan-1903** [comment]
@brettembrey 
Can you please share the screen shot?

**Comment by brettembrey** [comment]
Sure here is a screen shot

**Comment by adityatoshniwal** [comment]
This is done for improvement in visibility and overall theme.
