### ISSUE TITLE
BUG : UI BUG TYPE CUROSER ERROR 

### ISSUE THREAD

**Issue by B2-krunalrana** [pgadmin-org/pgadmin4#6729]
### UI BUG 

https://github.com/pgadmin-org/pgadmin4/assets/90046525/afa0b566-a9cc-4810-9f77-ae6113180082

**Comment by yogeshmahajan-1903** [comment]
@B2-krunalrana ,
Not able to open the video. Could please attach new one & steps to reproduce the issue, platform information etc.

**Comment by khushboovashi** [comment]
Hi @B2-krunalrana, this issue has been fixed with the latest pgAdmin version. Please test and if you still reproduce it, reopen the issue.
