### ISSUE TITLE
User Password Change does not change password

### ISSUE THREAD

**Issue by markhv-code** [pgadmin-org/pgadmin4#6730]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

A user changes their password but on the subsequent login must login in using the old password because the new password does not work.

**To Reproduce**

1. Login as a normal user
2. Click on the Change Password
3. Fill out the Change Password Fields
4. Click the Change button
5. Logout
6. Attempt to login using the new password

**Expected behavior**

After a user changes their password they are able to login using the new password

**Error message**

n/a

**Screenshots**
<img width="1880" alt="Screenshot 2023-08-30 at 4 01 14 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/71941492/0076525b-6e9a-4421-9961-816db6aacc6a">
<img width="1880" alt="Screenshot 2023-08-30 at 3 24 52 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/71941492/3cb09703-4297-4bb1-96ed-9929910dbb51">
<img width="1880" alt="Screenshot 2023-08-30 at 3 30 06 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/71941492/d53058a4-c3c2-44c5-903c-daac75e02094">

First screen shot is right after a user changes their password.
Second screen shot of of the logs when a user changes their password.
Third screen shot is of the logs when an admin is able to successfully change a user's password.

**Desktop (please complete the following information):**
 - OS: OSX monterey
 - Version: 7.5
 - Mode: Server
 - Browser (if running in server mode): firefox
 - Package type: Container

**Additional context**
pgAdmin is deployed as a container in a Kubernetes cluster. The /var/lib/pgadmin directory is mounted to a persistent volume utilizing AWS EFS.

**Comment by niklasweimann** [comment]
I can confirm this bug. We are running pgAdmin as a docker container and we have the exact same Problem.

**Comment by nikhil-mohite** [comment]
The issue is still producible on the latest snapshot (https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-09-14/)
Change password API returns the 200 status code but if the user logout and tries to login with a new password it throws an error incorrect user or password. (If we use an older password then it is allowed to login)

OS: macOS
package: pip whl.

**Comment by nikhil-mohite** [comment]
Resolved, Verified on candidate build: https://developer.pgadmin.org/builds/2023-09-18-1/
OS: Windows 10
Package: Pip whl
Mode: Server Mode
