### ISSUE TITLE
Login Form Doesn't Appear If "internal" authentication source is removed from environment variables

### ISSUE THREAD

**Issue by icsinfo** [pgadmin-org/pgadmin4#6738]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
The login form doesn't appear on the PgAdmin page if *internal* is not listed as an authentication source.

**To Reproduce**

1. Remove 'internal' from the list of authenication sources in the PGADMIN_CONFIG_AUTHENTICATION_SOURCES environment variable:
2. Restart Container
3. Attempt to login

**Expected behavior**

A login form appears, allowing us to input our Email Address / Username and Password.

**Error message**

No error message is displayed.

**Screenshots**

If we use:
```
PGADMIN_CONFIG_AUTHENTICATION_SOURCES=["ldap"]
```
The login screen looks like this:
![image](https://github.com/pgadmin-org/pgadmin4/assets/119430841/0dadcfe6-248b-4a41-b811-ec4a2416e5d6)

If we use:
```
PGADMIN_CONFIG_AUTHENTICATION_SOURCES=["ldap","internal"]
```
The login screen has the form:
![image](https://github.com/pgadmin-org/pgadmin4/assets/119430841/2c7e4101-1323-491a-bfc8-3df0c6e7a751)

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Version: Issue has existed since version 7.4. We are currently attempting to run version 7.6
 - Mode: Server
 - Browser (if running in server mode): Issue exists on all browsers.
 - Package type: Docker Container

**Comment by adityatoshniwal** [comment]
Works fine. Tested on docker dpage/pgadmin4:snapshot.
