### ISSUE TITLE
Terminate sessions on a table

### ISSUE THREAD

**Issue by PoojaSMath22** [pgadmin-org/pgadmin4#6742]
Hi Team, 

Since morning we are facing issue in querying the table in pgadmin and there are lot of sessions getting created by 'dms_user' very frequently in dev DB. 

Please reach out to me for more DB details.

Please terminate the sessions as this is blocking our testing and delaying our production deployment.

Regards,
Pooja

**Comment by adityatoshniwal** [comment]
Hi @PoojaSMath22,
Probably incorrect place to raise the issue.
