### ISSUE TITLE
GENERATE IDENTITY ignores START and MINVALUE

### ISSUE THREAD

**Issue by WindGlyder** [pgadmin-org/pgadmin4#6745]
Using PGAdmin 4 V7 when I enter GENERATE IDENTITY values for start and minvalue they are ignored in the SQL generated from the ERD diagram leaving empty brackets. Strangely MAXVALUE works fine tho.

**Comment by pravesh-sharma** [comment]
Hi @WindGlyder 

I have tried on latest version and is working for me. Can you please share .pgerd file and also which version of pgAdmin you are using?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
