### ISSUE TITLE
Maintenance - Error: "(!) str expected, not bytes"

### ISSUE THREAD

**Issue by StefanPeterWolf** [pgadmin-org/pgadmin4#6748]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
It's not possible to start any maintenance-task.

**To Reproduce**
1) Right-click on a database.
2) Choose "Maintenance"
3) Choose [VACUUM] and [OK]
4) Error: "(!) str expected, not bytes"

**Expected behavior**
The maintenance-task should start.

**Error message**
"(!) str expected, not bytes

**Screenshots**
![image](https://github.com/pgadmin-org/pgadmin4/assets/27217208/c3a2bd21-f3d3-4bab-8e18-e2b9742277f3)
![image](https://github.com/pgadmin-org/pgadmin4/assets/27217208/ba8440c4-8e8b-4657-8190-87363ba0673c)

**Desktop (please complete the following information):**
- Windows 10
 - Mode: Desktop

**Additional context**
PostgreSQL 14.7 (Ubuntu 14.7-1.pgdg20.04+1) on x86_64-pc-linux-gnu

**Comment by adityatoshniwal** [comment]
HI @StefanPeterWolf,
This is fixed in v7.6, can you please try?

**Comment by StefanPeterWolf** [comment]
Yes - in 7.6 it works.
THX -Stefan-

**Comment by StefanPeterWolf** [comment]
Sorry, wrong "action"...
