### ISSUE TITLE
AWS connection through bastion on MacOS - v7.6

### ISSUE THREAD

**Issue by ozgursc** [pgadmin-org/pgadmin4#6749]
**Describe the bug**
I updated to v7.6 considering it may be stable now but while v6.21 has no connection problems, v7.6 cannot connect to AWS server through bastion connection using aws ssm from iTerm. Other connections does not have a problem, including SSH connection. The problem is specific to bastion connection regardless of region.

Bastion info:
Os kernel: 4.14.314-238.539.amzn2.x86_64
Instance type: t2.micro

Example command
aws ssm start-session --document-name AWS-StartPortForwardingSessionToRemoteHost --region <TARGET REGION> --target <TARGET INSTANCE> --parameters host=<TARGET DB HOST>,portNumber="5432",localPortNumber="5432"

**To Reproduce**
1. Download v7.6 from https://www.postgresql.org/ftp/pgadmin/pgadmin4/v7.6/macos/ as dmg file
2. Open dmg file and move pgAdmin to Application folder
3. Confirm replace
4. MAKE SURE you don't have any local servers running on port 5432
5. connect to bastion using aws ssm 
6. Open pgAdmin and create a server with hotname=localhost, port=5432, and your username and password for targeted aws db
8. see connection will fail and keep asking you the password eventhough it is correct
9. ADDITIONAL STEP: If spammed, connection succeeds at some point but then cannot connect to databases and starts giving connection errors again

**Expected behavior**
v7.6 should connect to database server and display dbs propertly when using bastion to connect AWS database

**Error message**
connection to server at "localhost" (::1), port 5432 failed. Connection refused

**Desktop (please complete the following information):**
 - OS: macOS Venture
 - Version: 13.2
 - Mode: Desktop
 - Browser (if running in server mode): N/A
 - Package type: DMG

**Comment by adityatoshniwal** [comment]
No response from the user. Closing.
