### ISSUE TITLE
 does not restore database, defective backup, files without .tar

### ISSUE THREAD

**Issue by ubuangel** [pgadmin-org/pgadmin4#6754]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
When I make a backup copy of my data it seems to do it well but when I restore the pgadmin4 file explorer it doesn't see it, so it doesn't work

**To Reproduce**
Unexpected behavior, while testing when restoring and backing up my database, I see that .tar was not present when doing a backup

1.right click database
2. select restore 
3. set name file
4. set format to Custon or tar
5. click  restore button 
6. See the error

**Expected behavior**

view file with tar extension naturally

**Error message**

no error message

**Screenshots**
![image](https://github.com/pgadmin-org/pgadmin4/assets/49200646/a6132954-be26-4978-8231-8859c0adc19d)

![Captura de pantalla de 2023-09-13 02-48-38](https://github.com/pgadmin-org/pgadmin4/assets/49200646/4535774b-fbe9-492a-bf6d-ebd1d63ee6f4)

![Captura de pantalla de 2023-09-13 02-48-51](https://github.com/pgadmin-org/pgadmin4/assets/49200646/b2fd2621-e9fc-45ae-a34f-430834044704)

**Desktop (please complete the following information):**
Debian 11 (Bullseye)
 - OS: Gnu Linux
 - Version: Bullseye
 pgadmin 
 - Mode:  Desktop
 - version :7.6
 - 
![image](https://github.com/pgadmin-org/pgadmin4/assets/49200646/a9151365-0183-4594-ab94-1fb86dd9a331)

 - Package type:DEB (apt)

**Additional context**
Through a trial and error solution, I had to add the extensions manually,

**Comment by adityatoshniwal** [comment]
Duplicates #5610
