### ISSUE TITLE
image does not start

### ISSUE THREAD

**Issue by kale1d0code** [pgadmin-org/pgadmin4#6756]
I tried setting this up with docker compose.

and received the following message.
`
You need to define the PGADMIN_DEFAULT_EMAIL and PGADMIN_DEFAULT_PASSWORD or PGADMIN_DEFAULT_PASSWORD_FILE environment variables.
`

the readme on dockerhub does not mention these environment variables

**Comment by adityatoshniwal** [comment]
Hi @kale1d0code,
Please check the docs here - https://www.pgadmin.org/docs/pgadmin4/7.6/container_deployment.html#examples
Thanks.
