### ISSUE TITLE
pgadmin looses connection & unbale to connect again when vpn gets disconnected & reconnected again

### ISSUE THREAD

**Issue by kc63789** [pgadmin-org/pgadmin4#6759]
pgadmin looses connection & unbale to connect again when vpn gets disconnected & reconnected again.. 
the db connects over vpn.. pgadmin needs to be quit & launch again, & only after sometime it connects suddenly again over vpn

**Comment by yogeshmahajan-1903** [comment]
@kc63789 
I am not able to reproduce the above issue . Can you please share pgAdmin logs , OS, pgadmin version etc?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
