### ISSUE TITLE
pdadmin not install on linux mint 

### ISSUE THREAD

**Issue by ashiii-k** [pgadmin-org/pgadmin4#6760]
Hi folks,
I am new to Linux, and when I try to install pgadmin4 I get errors like this. I am referring official pgadmin doc to download the application 

sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'                   
  The following signatures were invalid: EXPKEYSIG 8C718D3B5072E1F5 MySQL Release Engineering <mysql-build@oss.oracle.com>

Ign:13 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/victoria pgadmin4 InRelease
Err:14 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/victoria pgadmin4 Release
  404  Not Found [IP: 217.196.149.55 443]
Reading package lists... Done
W: http://repo.mysql.com/apt/debian/dists/stretch/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: http://repo.mysql.com/apt/debian stretch InRelease: The following signatures were invalid: EXPKEYSIG 8C718D3B5072E1F5 MySQL Release Engineering <mysql-build@oss.oracle.com>
E: The repository 'http://repo.mysql.com/apt/debian stretch InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease' doesn't support architecture 'i386'
E: The repository 'https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/victoria pgadmin4 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by khushboovashi** [comment]
Hi,

On Sat, Sep 16, 2023 at 4:59 PM ashiii-k ***@***.***> wrote:

> Hi folks,
> I am new to Linux, and when I try to install pgadmin4 I get errors like
> this. I am referring official pgadmin doc to download the application
>
> udo sh -c 'echo "deb
> [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg]
> https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs)
> pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
> The following signatures were invalid: EXPKEYSIG 8C718D3B5072E1F5 MySQL
> Release Engineering ***@***.***
>
> Ign:13 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/victoria
> pgadmin4 InRelease
> Err:14 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/victoria
> pgadmin4 Release
>
We do not support Linux Mint.

**Comment by kzsa** [comment]
It is supported.

Linux Mint is either Debian or Ubuntu based. Here is an example of an installation on Mint 21.2 Cinnamon (/ Ubuntu - jammy).

![image](https://github.com/pgadmin-org/pgadmin4/assets/59151228/09d04a58-f293-433d-bc08-a444dc25e5d8)


https://www.pgadmin.org/download/pgadmin-4-apt/

OS: Linux Mint 21.2 x86_64

1.
```
curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg
```
2.
```
sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/jammy pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
```
3.
```
sudo apt update
```
4.
```
# Desktop and Web modes:
sudo apt install pgadmin4

# Desktop mode only:
sudo apt install pgadmin4-desktop

# Web mode only: 
sudo apt install pgadmin4-web 

# Configure the webserver, if you installed pgadmin4-web:
sudo /usr/pgadmin4/bin/setup-web.sh
```
Br: Zsolt

**Comment by kzsa** [comment]
Here you can find which Mint version is based on which Debian/Ubuntu version:
```
https://linuxmint.com/download_all.php
```
Br.
