### ISSUE TITLE
Download Image button in the ERD tool crops the image

### ISSUE THREAD

**Issue by petr-larin** [pgadmin-org/pgadmin4#6761]
I use pgAdmin to create an ERP diagram with some secondary keys. One secondary key is showing on the diagram (see the screen shot - the rightmost line - from loans to readers) but is missing from the .png file produced by the Download Image button.

![Screenshot 2023-09-16 225534](https://github.com/pgadmin-org/pgadmin4/assets/113700952/08aab935-db77-4e3c-b1f9-8997a5f11fa1)

![library pgerd](https://github.com/pgadmin-org/pgadmin4/assets/113700952/f36f2ac6-1010-43d3-bd53-7d9fa4f100f2)

![about](https://github.com/pgadmin-org/pgadmin4/assets/113700952/7b32f251-2f31-4045-af23-390a354e36ec)

[library.zip](https://github.com/pgadmin-org/pgadmin4/files/12641502/library.zip)

**Comment by pravesh-sharma** [comment]
duplicates #4995
