### ISSUE TITLE
Support Backup/Restore PostgreSQL 16

### ISSUE THREAD

**Issue by pomazanbohdan** [pgadmin-org/pgadmin4#6768]
Pls add support support Backup/Restore PostgreSQL 16

**Comment by akshay-joshi** [comment]
We have already added support from pgAdmin v7.6, the only thing is PostgreSQL 16 has not released yet, so you will have to provide the Binary Path in the Preferences dialog for PG 16.

<img width="1046" alt="Screenshot 2023-09-21 at 11 30 52 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/8728144e-a7c6-4237-8e27-6c50c7223db6">
