### ISSUE TITLE
All the about info details should not be visible to non-admin users

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#6769]
**Describe the bug**
Currently, any user of pgAdmin server mode can see the pgAdmin DB path or other paths set by admin. Such details should be visible to admin only.

**Expected behavior**
Details like entire server config, db & log location, OS name should not be visible to non-admin user.

**Screenshots**
<img width="751" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/1bed9cb1-71fd-4270-bfca-4ce927d33560">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: 7.7
 - Mode: Server
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Comment by yogeshmahajan-1903** [comment]
Working fine.
