### ISSUE TITLE
SSL mode `verify-full` does not work with SSH tunnel

### ISSUE THREAD

**Issue by miskr-instructure** [pgadmin-org/pgadmin4#6770]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When SSL mode is set to `verify-full` and an SSH tunnel is also configured, the SSL verification fails, seemingly because it tries to validate against the SSH tunnel ingress as hostname (127.0.0.1) instead of the true database hostname.

Notes:
- SSH tunnel with SSL mode=`verify-ca` works
- SSL mode=`verify-full` without SSH tunnel also works

**To Reproduce**

1. Find a DB which is reachable behind an SSH tunnel and also has proper SSL configuration (set `sslrootcert` if needed)
1. Set up the configuration to have an SSH tunnel **and** also SSL mode=`verify-full`
1. Observe that connecting to it will fail, see attached picture

**Expected behavior**

SSL mode=`verify-full` should work the same *with or without* SSH tunnel.
The SSL layer's hostname validation should happen against the actual DB hostname, even if the "real" connection happens towards the SSH tunnel's ingress (127.0.0.1).

**Error message**

`connection failed: connection to server at "127.0.0.1", port 55850 failed: server certificate for "[redacted].rds.amazonaws.com" (and 3 other names) does not match host name "127.0.0.1"`

See screenshot.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/122885102/f5780fc3-a1e7-4c02-8ea0-f3661dc12a7e)
![image](https://github.com/pgadmin-org/pgadmin4/assets/122885102/bfd73b70-75f1-4d3a-8cae-67f336ffd08e)
![image](https://github.com/pgadmin-org/pgadmin4/assets/122885102/5fa32362-955e-44e8-9a89-09ebb2c007a9)

**Desktop (please complete the following information):**
 - macOS
 - Version: 13.5
 - Mode: Desktop
 - Browser (if running in server mode): -
 - Package type: dmg

**Additional context**

-

**Comment by akshay-joshi** [comment]
@miskr-instructure 

Can you please verify it once on the latest version v7.8? We have made some minor changes in that release.

**Comment by miskr-instructure** [comment]
Thank you, it seems to work as expected now (both verify-ca and verify-full works with SSH tunnel on).

**Comment by miskr-instructure** [comment]
I guess [this](https://github.com/pgadmin-org/pgadmin4/commit/81dcc917476c638ba32807ae9ae7f884b8b9182d) was the related change.

**Comment by akshay-joshi** [comment]
@miskr-instructure 

Thanks a lot for testing. Yes, that was the related change.

Closing the issue as it has been fixed.
