### ISSUE TITLE
Backup dialog object's tab both scroll bars flickering  and checkbox not clickable

### ISSUE THREAD

**Issue by anilsahoo20** [pgadmin-org/pgadmin4#6771]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

On selection of Backup dialog for Schema->Objects tab the both the scroll bars are flickering and due to that the checkbox for selection of objects are not working. On resizing the dialog the issue does not arises.

**To Reproduce**

1. Right click on any Database Schema
2. Select Backup
3. Enter file name
4. Go to Objects tab
5. Both the scroll bars are flickering
6. Checkbox are not clickable

**Expected behavior**

The scroll bars should not flicker and checkbox must be clickable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX Ventura 13.4.1
 - Version: 7.7
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: OSX Arm-64

**Comment by akshay-joshi** [comment]
Duplicate of #6799
