### ISSUE TITLE
No icon shows in Object Explorer

### ISSUE THREAD

**Issue by xudatecanada** [pgadmin-org/pgadmin4#6773]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
I used to have pgadmin4 4.3 showing up correctly with all kinds of colorful icons.
Now I cannot see any icons ( I do mean any!)

I just managed to install pgadmin4 V7.6, and it still cannot see all icons
other interface and dialog box are good.

**To Reproduce**
Don't know how to reproduce it.

Installed it on 
Edition	Windows Server 2022 Datacenter
Version	21H2
Installed on	‎9/‎15/‎2022
OS build	20348.1906

 and icons are there.

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**
![image](https://github.com/pgadmin-org/pgadmin4/assets/103840322/bbafa15f-129e-40fd-8a94-074963473b6c)

**Desktop (please complete the following information):**

Edition	Windows 10 Enterprise N
Version	22H2
Installed on	‎8/‎24/‎2023
OS build	19045.3324

**Additional context**

I am thinking maybe Windows 10 Enterprise N cannot show those icons?
That desktop is our VDI so it get OS upgraded often.

**Comment by xudatecanada** [comment]
Tried the following version the icon is ok
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎3/‎5/‎2022
OS build	19045.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0

**Comment by pravesh-sharma** [comment]
Closing as per user confirmation.

**Comment by xudatecanada** [comment]
Hi Pravesh
Just for your information, the following OS build still has icon missing issue.
Edition Windows 10 Enterprise N
Version 22H2
Installed on ‎8/‎24/‎2023
OS build 19045.3324

My second test is on a similar edition with minor difference (sorry if that caused confusion)
Edition Windows 10 Enterprise
Version 22H2
Installed on ‎3/‎5/‎2022
OS build 19045.3448
Experience Windows Feature Experience Pack 1000.19044.1000.0

And it has no issue.

I am not sure if the root cause is because of this minor different of OS edition or something else.
Thanks

**Comment by zhc009** [comment]
how do you deal with this issuse? My pgAdmin has the same problem.

**Comment by SnowDream39** [comment]
My pgAdmin 4 v9.8 has the same problem.

I have checked the developer tools, to find that the response from web server is empty.

<img width="1188" height="890" alt="Image" src="https://github.com/user-attachments/assets/273cbb49-9c3b-4e0b-973d-803cb23f6e3a" />
