### ISSUE TITLE
pgAdmin4 not starting at all

### ISSUE THREAD

**Issue by AksharaKrishnan** [pgadmin-org/pgadmin4#6774]
Hi,
I got this from the edb and running a Postgres 15 pgAdmin. I am running it on a MacOS Ventura 13.5.2. This is a desktop app and does not start up at all. I have re-downloaded it multiple times, but the server does not run at all. 
When I try to open it, the loading screen pops up, saying it's waiting for pgAdmin to start and then immediately disappears. 

<img width="750" alt="Screenshot 2023-09-19 at 1 01 48 pm" src="https://github.com/pgadmin-org/pgadmin4/assets/89782555/eaa6cfce-9231-4ae4-92ab-bc2882d3a809">

**Comment by yogeshmahajan-1903** [comment]
@AksharaKrishnan ,

Can you please try download from pgadmin.org & try? This is know issue with pgAdmin installed using PosthreSQL installer.

**Comment by pravesh-sharma** [comment]
Duplicates #6580
