### ISSUE TITLE
Wrong redirect after trying to log in with incorrect password

### ISSUE THREAD

**Issue by oliverbienert** [pgadmin-org/pgadmin4#6777]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

I am running the apt Version of pgAdmin4 on a virtual Debian 10 (Hyper-V Host) in an Enterprise network. When a user tries to log in with an incorrect password, he gets redirected to the welcome screen of the installed Apache web server.

**To Reproduce**

1. Type in a wrong password
2. Click on 'Login'
3. See the welcome page (In my case, Apache2 Debian Default Page)

**Expected behavior**

The user should see the Login page of pgAdmin at:

my-server/pgadmin4/login?next=%2Fpgadmin4%2Fbrowser%2F

**Screenshots**

When I log then in, using the correct password, I see the Error message pop-up that should have been displayed on the login page, but without the colored background:

![image](https://github.com/pgadmin-org/pgadmin4/assets/6669621/4829e758-56de-4edf-9c51-2d8dac8c94a7)

**Desktop (please complete the following information):**

This is my local machine

 - OS: Ubuntu
 - Version: 22.04
 - Mode: Server
 - Browser: Firefox
 - Package type: DEB

**Additional context**
This is the server where pgAdmin4 is running

Server: Debian 10
Package type: DEB
pgAdmin4 Version: 7.6
Web server: Apache2

**Comment by pravesh-sharma** [comment]
Duplicates #6704, The Issue is already fixed on the latest version of pgAdmin4.
