### ISSUE TITLE
pgAdmin backup: illegal option -- large-objects PostgreSQL V16

### ISSUE THREAD

**Issue by Adventurer2021** [pgadmin-org/pgadmin4#6778]
BUG: -large-objects” option has now (since installing V16 of postgres) been added to the automated backup process and is now part of the command line with pgAdmin 7.6 
After launching the pgAdmin backup process on a table (about 8 million records), I receive an illegal option error.
**C:\Program Files\pgAdmin 4\v7\runtime\pg_dump.exe: illegal option -- large-objects
pg_dump: hint: Try "pg_dump --help" for more information.**

This can be reproduced by after installing PostgreSQL V16 and restoring my DB tables, I launched the backup process in pgAdmin by highlighting and right clicking on the table and then choose "Backup". I do not change or configure any options and accept all defaults (as I did with previous V15 of PostgreSQL). I then specify the file_name.backup and then click "backup". The process starts but immediately fails with the above mentioned error: 

**C:\Program Files\pgAdmin 4\v7\runtime\pg_dump.exe: illegal option -- large-objects**

**Expected behavior**
Doing this process prior to PostgreSQL V16 install, the backup file would be created without issue.

**Error message**

**C:\Program Files\pgAdmin 4\v7\runtime\pg_dump.exe: illegal option -- large-objects**

**Screenshots**

Not necessary for this issue

**Desktop (please complete the following information):**

- OS Name	Microsoft Windows 11 Pro
- Version	10.0.22621 Build 22621
- Mode: Desktop
- Browser: **About pgAdmin 4**
                 Version: 7.6
                 Application Mode: Desktop
                 Current User pgadmin4@pgadmin.org
                 NW.js Version: 0.77.0
                 Browser: Chromium 114.0.5735.91
                 Operating System: Windows-10-10.0.22621-SP0
                 pgAdmin Database File: C:\Users\user\AppData\Roaming\pgadmin\pgadmin4.db
                 Log File: C:\Users\user\AppData\Roaming\pgadmin\pgadmin4.log

**Comment by akshay-joshi** [comment]
Hi @Adventurer2021 

"--blobs" are [deprecated](https://www.postgresql.org/docs/16/app-pgdump.html) from PostgreSQL 16 and the "--large-objects" option is newly introduced. You will have to specify the Binary Path in the Preferences dialog for PG 16. 

<img width="1046" alt="Screenshot 2023-09-21 at 11 30 52 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/68ce1d48-cd81-4fe8-843a-cd8dd83e0211">
