### ISSUE TITLE
"Schema Diff" function does not work when user language is set to Japanese in Preferences.

### ISSUE THREAD

**Issue by penguinlab** [pgadmin-org/pgadmin4#6784]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

"Schema Diff" function does not work when user language is set to Japanese in Preferences.  
Note that i have confirmed that it works as expected when the user language is set to English.

**To Reproduce**

1. Change user language to Japanese in Preferences.
2. Perform a schema comparison between two databases using the "Scheme Diff" function.
3. The two databases should have a difference in schema, but the result is shown as no difference.

**Expected behavior**

**Error message**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Version: 7.6
 - Mode: Desktop
 - Browser (if running in server mode): 
 - Package type: Windows Installer (.exe)

**Additional context**

**Comment by pravesh-sharma** [comment]
Tested with French language and issue is reproducible.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-10-27/
Environment: macOsx Ventura 13.4.1
Package: arm64
