### ISSUE TITLE
Connection Warning after Idle 

### ISSUE THREAD

**Issue by tmgarcia70** [pgadmin-org/pgadmin4#6791]
If I am idle for more than a few minutes I receive the attached error message. 

Currently using version 7.1. 

1. Pull up a query page and leave idle (time is not consistent) say 30 minutes
2. Click on refresh button
3. See the error

**Expected behavior*

There are currently 10 other users on the same network. I am the only one using version 7.1 and I am the only user receiving this error. Other users can stay logged in for hours (up to 7) and not receive this error (attached). Once I click on the Continue button it does reconnect me. 

**Desktop (please complete the following information):**
 - OS: Windows 10, PRO
 - Version: 7.1
 - Mode: Desktop
 - Browser: Edge

[Connection Warning.docx](https://github.com/pgadmin-org/pgadmin4/files/12717715/Connection.Warning.docx)

**Comment by anilsahoo20** [comment]
Hi @tmgarcia70,
Can you please test on the latest version v7.7. If it is still reproducible, kindly report.

**Comment by adityatoshniwal** [comment]
No response from the user. Closing.

**Comment by tmgarcia70** [comment]
Apologies, I was on vacation. I have upgraded to version 7.7 and no change.

**Comment by nikhil-mohite** [comment]
Hi @tmgarcia70,

Can you please check whether autocomplete is enabled or not in preferences, `File-> Preferences->Query Tool -> Auto-completion -> Auto complete on key press?`

**Comment by pravesh-sharma** [comment]
No response from the author, closing.
