### ISSUE TITLE
Pass host and user as environment variables to passwordexec subshell

### ISSUE THREAD

**Issue by pccowboy** [pgadmin-org/pgadmin4#6794]
**Describe the solution you'd like**

Pass the current value of `host name` and `user name` as environment variables to the `PasswordExec.get` command.

This would allow easy use of tokens generated by commandline utilities (such as the AWS CLI)  to incorporate the database hostname, i.e.:

for the password exec command, instead of hard coding the host and user name
```
aws rds generate-db-auth-token --hostname some.cluster.us-east-2.rds.amazonaws.com --port 5432 --region us-east-2 --username my_iam_user
```

we could use
```
aws rds generate-db-auth-token --hostname $PGADMIN_HOSTNAME --port 5432 --region us-east-2 --username $PGADMIN_USERNAME
```
or something similar.

**Describe alternatives you've considered**
We could perform variable substitution on the password exec command itself, but I think that would be open to attack, where passing the specific values to the subprocess call's environment keeps things internal to pgadmin.

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
Working fine.
