### ISSUE TITLE
Can not select Objects during backup  

### ISSUE THREAD

**Issue by hbatalhaStch** [pgadmin-org/pgadmin4#6799]
**Describe the bug**

When I am creating a backup of a schema I can not select the objects under the Objects tab when Filename under General Tab isn't empty and the horizontal and vertical scrolls keep flickering and I can't scroll to the bottom neither.

**To Reproduce**

1. Choose a schema and right click
2. Click Backup
3. Go to the Objects tab

**Expected behavior**
Should be able to select all the the all objects and scroll to the bottom

**Error message**

**Screenshots**

![Animation](https://github.com/pgadmin-org/pgadmin4/assets/114578587/bae699a1-c76b-45f0-8ffb-869d911a03c8)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 19045.3448
 - Version: 7.7
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: Windows

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
This is working fine. Verified on Windows, Linux and Mac.
