### ISSUE TITLE
Connectionstring parameter "load_balance_hosts" not supported

### ISSUE THREAD

**Issue by chaosben** [pgadmin-org/pgadmin4#6802]
**Describe the bug**

It seems, there is no way to supply the load_balance_hosts-option in the connection parameters.

**To Reproduce**

1. Open the properties of a registered server
2. Click on "Parameters"
3. Add a new parameter and search for "load_balance_hosts"

**Expected behavior**

The load_balance_hosts-paramter should be supported

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/1180488/0e1b0010-6457-4b75-a349-655cc3b13d14)

**Desktop:**
 - OS: Windows 11 22H2
 - Version: 7.7
 - Mode: Desktop

**Comment by anilsahoo20** [comment]
Tested and verified on Snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-10-06/
Environment: macOSX Ventura 13.4.1
