### ISSUE TITLE
Certain files in process_logs are empty when DATA_DIR is moved to a networked drive (windows)

### ISSUE THREAD

**Issue by rhewy** [pgadmin-org/pgadmin4#6803]
## Description of the bug 

If you set DATA_DIR in config.py to a network drive a lot of things work **except** the files named err and out are empty  for a process in the process_logs folder (could be a flush issue for io on the file). This effects retrieving the errors from the copy command when you use the import/export tool then there is a problem with the import and you want to see the error message.

## Redirect in config.py
``` python
if IS_WIN:
    # Use the short path on windows
    DATA_DIR = os.path.realpath(os.path.join('Z:', 'pgAdmin'))
else:
    if SERVER_MODE:
        DATA_DIR = '/var/lib/pgadmin'
    else:
        DATA_DIR = os.path.realpath(os.path.expanduser('~/.pgadmin/'))
``` 

## Steps to reproduce the behavior:
1. Map a network share as Z:
2. Edit the config.py in the software tree web folder as shown above 
3. Fire up PG admin
4. Create a table
5. Import **bad data or good data** into the table using the PGAdmin GUI
6. Go to sessions click on the view details ... no logs available messages

## Expectations
I was expecting to see the text for the error message

##Screenshots below

![image](https://github.com/pgadmin-org/pgadmin4/assets/4993063/dbc7a83a-dfb2-45f7-8e87-e8f45df1804b)

![image](https://github.com/pgadmin-org/pgadmin4/assets/4993063/d0ffbb51-c474-4924-bea1-418effad92ba)

## More info
If I install PgAdmin locally on my laptop then I do not have this issue.

The version/release I am running is below:
 
```
ALLOW_SAVE_PASSWORD = True
ALLOW_SAVE_TUNNEL_PASSWORD = False
APP_COPYRIGHT = "Copyright (C) 2013 - 2023, The pgAdmin Development Team"
APP_ICON = "pg-icon"
APP_NAME = "pgAdmin 4"
APP_RELEASE = 7
APP_REVISION = 7
APP_SUFFIX = ""
APP_VERSION = "7.7"
```
## Future tests
I will try to isolate the issue to the redirect vs the network drive

**Comment by rhewy** [comment]
Same problem when I redirect to another folder of the c-drive

**Comment by nikhil-mohite** [comment]
Resolved.
Tested on latest snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-05/
OS: Windows 10
Package: Pip whl
