### ISSUE TITLE
pgAdmin imports servers to the wrong accounts in the server version with webserver auth enabled

### ISSUE THREAD

**Issue by amarel123** [pgadmin-org/pgadmin4#6815]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

After importing the .json file with the server, sometimes (not always) it is imported to another user's account, and the list of servers in my account is still empty. The problem never appears when creating a server manually.

**To Reproduce**

The main thing that I think may be related to the problem is that I am using the following configuration:
AUTHENTICATION_SOURCES = ['webserver']

Users are authorized using basic auth, and the accounts are retrieved by a PHP script. **Such accounts in the pgAdmin sqlite database do not have an email, only a username.**

**Expected behavior**

Servers are always imported under the account of the user who imports them.

**Error message**

No error message - after import, a message appears stating that the operation was successful.

**Screenshots**

Select from pgAdmin sqlite "server" table:

![Captura desde 2023-10-04 11-12-10](https://github.com/pgadmin-org/pgadmin4/assets/12075502/f415c3a6-8701-4dd5-93ad-6724e228bf60)

The last server was imported on user 12 and as you can see it was added on user 2. User 2 confirmed to me that he sees the server imported on my account in his account.

**Desktop (please complete the following information):**
 - OS: Rocky Linux 9
 - Version: 7.6 (docker latest)
 - Mode: Server
 - Browser (if running in server mode): Firefox
 - Package type: Docker

**Additional context**

**Comment by amarel123** [comment]
I think I found where the problem is:
https://github.com/pgadmin-org/pgadmin4/blob/0b3c79865e61eff5862b737b472f0676d847d5fb/web/pgadmin/utils/__init__.py#L810

There are no email addresses in webserver auth method, only usernames. For this reason, it searches for users with an empty email address and provides any one.

**Comment by amarel123** [comment]
Bugfix proposed #6818

**Comment by adityatoshniwal** [comment]
Hi @amarel123,
Can you confirm if this is working?

**Comment by yogeshmahajan-1903** [comment]
An error while importing server.
![Screenshot 2024-01-03 at 3 35 08 PM](https://github.com/pgadmin-org/pgadmin4/assets/16016019/5f5bf857-1ca6-4659-894b-b82d21b4bee1)

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
