### ISSUE TITLE
setup.py issue with flask

### ISSUE THREAD

**Issue by koureasstavros** [pgadmin-org/pgadmin4#6830]
I have build and run the image using the Dockerfile, all went good.
Now, I am trying to find a way to reload the Servers from servers.json file either from url (not using the UI with Import/Export) either from inside the container using terminal. The servers.json and the pgpassfile is refreshed inside the container via an external tool.

So far I haven't found any refresh trigger via url and I am trying first to do that from terminal. My intention is to reload servers.json without restarting the application.

I read that this can be done by this command using setup.py
`python setup.py --load-servers`

But the above code produced problems:

```
/pgadmin4 $ python setup.py --load-server
Traceback (most recent call last):
  File "/pgadmin4/setup.py", line 24, in <module>
    import config
  File "/pgadmin4/config.py", line 32, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/pgadmin4/pgadmin/__init__.py", line 24, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'
/pgadmin4 $ python2 setup.py --load-server
/bin/sh: python2: not found
/pgadmin4 $ python3 setup.py --load-server
Traceback (most recent call last):
  File "/pgadmin4/setup.py", line 24, in <module>
    import config
  File "/pgadmin4/config.py", line 32, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/pgadmin4/pgadmin/__init__.py", line 24, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'
/pgadmin4 $
```

**Comment by akshay-joshi** [comment]
@koureasstavros 

You can try with the following command:

```
docker exec -it <container-name> /venv/bin/python /pgadmin4/setup.py --load-servers servers.json
```

**Comment by koureasstavros** [comment]
> @koureasstavros
> 
> You can try with the following command:
> 
> ```
> docker exec -it <container-name> /venv/bin/python /pgadmin4/setup.py --load-servers servers.json
> ```

Thanks!, so this is because there is another environment I suppose.
If I execute the following inside the container, it asks of User
`/venv/bin/python /pgadmin4/setup.py --load-servers servers.json`

Any idea what user i should specify into switch --User ?

**Comment by koureasstavros** [comment]
Ah just find out that, the user should be the user email configured when provisioning the pod or container as this creates a folder inside the container and uses that user. Many thanks!
