### ISSUE TITLE
Debugger hangs on a function with an "if statement"

### ISSUE THREAD

**Issue by ProgrammingPete** [pgadmin-org/pgadmin4#6832]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When trying to debug a function that has an if statement (declared variable), it is noted that the debugger freezes and does not want to progress forward when using the step over function. 

**To Reproduce**

1. Got the Function on a database and right click
2. Click on Debugging -> Debug
![image](https://github.com/pgadmin-org/pgadmin4/assets/10091505/eba22dc0-8468-4b7e-b683-fdb6131fb636)

4. Keep clicking step over until you reach an if statement in your function that is similar to this one:

![image](https://github.com/pgadmin-org/pgadmin4/assets/10091505/f36599fa-de16-45fe-90e8-2c97e746fadf)

6. Observe that the debugger will freeze  and you will not be able to progress past the if statement, not matter how long you wait

**Expected behavior**

I expect to keep debugging

**Error message**

None

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mode: Desktop
 - Package type: EXE for windows

**Comment by pravesh-sharma** [comment]
Hi @ProgrammingPete,

We are not able to reproduce the issue. Can you please share the SQL of the function or error logs? Also which version of pgAdmin 4 you are using?

**Comment by ProgrammingPete** [comment]
Here is the sql function below: 

```
declare
	v_created_date timestamp := now();
	v_type_id integer;
	v_notification_id integer;
	output record;
begin
	-- retrieve type
	select notification_type_id into v_type_id from notification_type where notification_type = upper(p_notification_type);
	if(v_type_id is null) then
		select notification_type_id into v_type_id from notification_type where notification_type = 'USER';
	end if;

	-- update existing notification
	if (p_notification_id is not null) then
		update notification
		set user_id = p_user_id, dealer_id = p_dealer_id, franchise_id = p_franchise_id, notification_group = p_notification_group, 
			notification_type = v_type_id, image_mime_type = p_image_mime_type, image_data = p_image_data, priority = p_priority, 
			created_date = v_created_date, expire_date = p_expire_date, delivery_date = p_delivery_date, 
			created_by_user_id = p_created_by_user_id, created_by_account_id = created_by_account_id, from_user = p_from_user   
		where notification_id = p_notification_id;

		v_notification_id := p_notification_id;

	-- insert new notification
	else
		insert into notification (user_id, dealer_id, franchise_id, notification_group, notification_type, image_mime_type, 
			image_data, priority, created_date, expire_date, delivery_date, created_by_user_id, created_by_account_id, from_user)
		values (p_user_id, p_dealer_id, p_franchise_id, p_notification_group, v_type_id, p_image_mime_type, 
			p_image_data, p_priority, v_created_date, p_expire_date, p_delivery_date, p_created_by_user_id, p_created_by_account_id, p_from_user);

		v_notification_id := currval('notification_notification_id_seq');
	end if;

	select *	
		into output
		from mt_notification_v where notification_id = v_notification_id;
	return output;

	exception when others then raise;

end;
```

There are basic input that could be passed into the debugger. Here are the values:

![image](https://github.com/pgadmin-org/pgadmin4/assets/10091505/072f75a3-4033-48d2-b2c8-ea7045a8fcc3)


One thing to note is that you NEED to press Step Over on an if statement to create this issue. I am not sure where to find the error logs.

**Comment by pravesh-sharma** [comment]
Hi @ProgrammingPete,

I have tried with the function and input provided and I am not able to reproduce the issue. Can you please share logs? To access logs go to `File -> Runtime -> View log` I have highlighted the log file path in attached screenshot. Also, it will be helpful if you can share the pgAdmin 4 version used.

<img width="791" alt="Screenshot 2023-11-03 at 1 13 08 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/1bf7f539-4b06-4a6f-89b8-26e3e2fc756f">

**Comment by pravesh-sharma** [comment]
No response from the author, closing.
