### ISSUE TITLE
Unable to terminate own connections as a non super user

### ISSUE THREAD

**Issue by wibrt** [pgadmin-org/pgadmin4#6836]
**Describe the bug**

The Dasboard allows for terminating other connections,
(aka psql pg_terminate_backend)

![image](https://github.com/pgadmin-org/pgadmin4/assets/17875724/85a51fbb-b1f1-4b4c-bec9-547e7c46762c)

When terminating a own connection with the red square:

![image](https://github.com/pgadmin-org/pgadmin4/assets/17875724/de57d9e3-2e52-4d16-99e7-c329220dec9a)

This doesn't work.

(if you the same with pg_terminate_backend this does work)

**To Reproduce**

1. Open multiple connections, eg multiple query tools to the same database
2. Go to the dashboard
3. Click on a red square on one of your own connections
4. Are you able to terminate the connection?

**Expected behavior**

I would expect the same behaviour as pg_terminate_backend
(consistentency)

**Version**
![image](https://github.com/pgadmin-org/pgadmin4/assets/17875724/0fc9d61e-8b9c-4975-ad3b-82005c5ccec6)

**Confirmation**

Can anyone confirm this?

hth

**Comment by yogeshmahajan-1903** [comment]
If non-super user tires to terminate super-user connection, error shown on UI is 500.

<img width="1757" alt="Screenshot 2023-10-12 at 2 18 37 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/5f92d34b-c75d-454e-8b0e-3119ef8baed7">

Error should be explanatory not 500.

**Comment by yogeshmahajan-1903** [comment]
Working fine/
