### ISSUE TITLE
Cloud instance deployment not working

### ISSUE THREAD

**Issue by pravesh-sharma** [pgadmin-org/pgadmin4#6840]
**Describe the bug**
When Trying to deploy a cloud instance from pgAdmin4 it is failing.

**To Reproduce**

1. Go to Object -> Register -> Deploy Cloud Instance
2. Select Amazon RDS and fill in all the details
3. Try deploying, error appears

**Expected behavior**

The user should be able to deploy the cloud instance successfully.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.6
 - Version: 7.7
 - Mode: Desktop

Attached log for reference
[error.log](https://github.com/pgadmin-org/pgadmin4/files/12845340/error.log)

**Comment by khushboovashi** [comment]
It's working fine on today's (7/11/2023) snapshot build.
