### ISSUE TITLE
why difficult to login the web page  no  default username and password

### ISSUE THREAD

**Issue by itildesk** [pgadmin-org/pgadmin4#6848]
my  pagadmin4  installed centos7  
run  ./setup...py
and  http://ip/pgadmin4  can see the login input
but who can tel me the default username and password

**Comment by adityatoshniwal** [comment]
@itildesk pgAdmin asks for Email and Password when you setup for the first time. If you don't remember, then you can remove the pgadmin4.db file from the `/var/lib/pgadmin` directory and run setup again. It is recommended to follow steps here - https://www.pgadmin.org/download/pgadmin-4-rpm/
Furthermore, pgAdmin do not support centos7. Closing.
