### ISSUE TITLE
Upgrade Flask, Werkzeug and other modules depends on the latest version of Flask

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#6850]

**Comment by adityatoshniwal** [comment]
It turns out, Flask-Login is not compatible with latest Flask/Werkzeug. They have done the changes but not released yet. Need to wait for Flask-Login to release.

**Comment by yogeshmahajan-1903** [comment]
All package updates has been tested across all supported platform.
