### ISSUE TITLE
erd numeric 0 floating point

### ISSUE THREAD

**Issue by mortifia** [pgadmin-org/pgadmin4#6851]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
in erd
create table like this (valid sql)
```sql
CREATE TABLE IF NOT EXISTS public.advertisements
(
    id serial NOT NULL,
    wages numeric(1000, 0),
    PRIMARY KEY (id)
);
```
i cannot set 0 on scale

ps : if you set manualy in json erd file it work 

**Expected behavior**

 set 0

**Error message**

between 1 to 1000

**Comment by adityatoshniwal** [comment]
this is happening for normal tables as well.
