### ISSUE TITLE
Define a function with return type of table(x type, y type, ...)

### ISSUE THREAD

**Issue by robertsosinski** [pgadmin-org/pgadmin4#6854]
**Describe the solution you'd like**
Define a function with return type `table(x type, y type, ...)` for a set returning function.

When you create a new function in PGAdmin, you're given a `Select an item...` dropdown that only has existing types. However, if I try to define a return type of `table(...)` the interface fails; when I click out of the Return type box, my anything there just disappears.

**Describe alternatives you've considered**
Just defining the function outside of PGAdmin in the console, and updating it from there.

**Additional context**

<img width="479" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/6429/ff57a18f-39ee-487e-a1ed-899e56f76f95">

**Comment by akshay-joshi** [comment]
Tested with snapshot build [2023-12-01](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-01/).
Working fine
