### ISSUE TITLE
Not possible to directly edit query when using "view/edit data" on a table

### ISSUE THREAD

**Issue by juan-diego89** [pgadmin-org/pgadmin4#6856]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
Today when clicking on "view/edit data" -> "All rows" its not possible to edit the generated query. This is ussaly my starting point for creating a query. Now I have to copy the query to a new tab. This result in that I get many tabs, should be better if query was possible to edit directly. 

**To Reproduce**

1. Go to Schemas in the left side
2. Click on "public" 
3. Click on "Tables" 
4. Right click on any table.
5. Click on "View/Edit Data"
6. Click on "All Rows"
7. Click on the query created.
8. Not possible to edit it

**Expected behavior**

I expect to be able to edit the query in same window

**Error message**
No error message

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: pgadmin 7.7
 - Mode: Desktop
 - Package type: exe

**Comment by yogeshmahajan-1903** [comment]
Duplicate of #5908
