### ISSUE TITLE
pgAdmin setup.py --load_servers issue

### ISSUE THREAD

**Issue by koureasstavros** [pgadmin-org/pgadmin4#6857]
I am using a custom web app tool written in C# for communication with a pod into a Kubernetes Cluster having the pgAdmin.
Though the custom web app I am sending auto-constructed Kubernetes Pod Exec commands to update the servers and the password files into pgAdmin container space whenever a new server is provisioned or un-provisioned though the tool.

The command is the following:

```
string[] command_load = { "/venv/bin/python", "/pgadmin4/setup.py", "--load-servers", $"/var/lib/pgadmin/storage/{main_unit_isobox}/servers/servers.json", "--user", $"{main_unit_account}", "--replace" };
ExecInPod(client, podname, space, command_load, container).Wait();
```
*In this example the servers.json and pgpassfile default locations have been changed due to mount, permissions, and overwrite issues. You can ignore it as it works.

I have noticed that when there is always one server in the list, the update works perfectly while adding or removing servers from servers.json. On the other side when all servers are un-provisioned and therefore there is no server in the list the servers.json is empty and the pgAdmin is triggered for loading then after that even adding a server into the list the "Servers" group into UI of pgAdmin seems to load forever. Then the only solution is to restart the pgAdmin, reloading the web page is not enough,

For now I am having a dummy server always in the list to avoid this issue but I have to see always this dummy server into the UI.

**Comment by adityatoshniwal** [comment]
Duplicates #6602.
