### ISSUE TITLE
Clicking "Sort" graphic in "Explain Alayze" output breaks program (white screen)

### ISSUE THREAD

**Issue by Bilge** [pgadmin-org/pgadmin4#6858]
1. Run a simple query with an `ORDER BY` clause.
2. Click _Explain Analyze_ button.
3. Click the _Sort_ graphic.

Screen goes completely white. Tab cannot be closed. Program is now useless.

![pgAdmin4_jFpNEJ0CuX](https://github.com/pgadmin-org/pgadmin4/assets/470626/3597b418-d686-443b-84ca-32c9f1fe3f69)

**Comment by adityatoshniwal** [comment]
To reproduce this, checkout the test case mentioned here - https://www.postgresql.org/message-id/CAGPqQf09oPX-cQRpBKS0Gq49Z+m6KBxgxd_p9gX8CKk_d75HoQ@mail.gmail.com

**Comment by anilsahoo20** [comment]
Tested and verified on candidate build:https://developer.pgadmin.org/builds/2023-10-16-1/
Environment: macOSX Ventura 13.4.1

**Comment by Bilge** [comment]
Just making a notice this was closed in 47e734dbf2ca4c2ee5864300f883ceb630735bf9.
