### ISSUE TITLE
Cannot see my schema in PGAdmin

### ISSUE THREAD

**Issue by peterfutaro** [pgadmin-org/pgadmin4#6862]
Hi there,

I am using pgAdmin4 version 6.7

I started to learn connecting postgREST with my postgreSQL database.
After doing some tutorial, I wanted to see the table via pgAdmin, but I couldn't find the created "api" schema.

Here are some screenshot of the information:
![image](https://github.com/pgadmin-org/pgadmin4/assets/76289958/e5682651-5f33-4a56-b47c-3bd6f6b980b6)

![image](https://github.com/pgadmin-org/pgadmin4/assets/76289958/ec633eff-ef88-4afe-995b-2b0b367de8f3)
I am connected as "postgres" user

Thank you.

**Comment by yogeshmahajan-1903** [comment]
@peterfutaro 
Can you please confirm that server connected in the pgAdmin is same as psql one. Also please use latest pAdmin 4 version 7.7

Run below command if your server is on linux system
```
select pg_read_file('/etc/hostname') as hostname, setting as port from pg_settings where name='port';
```

**Comment by peterfutaro** [comment]
@yogeshmahajan-1903 
Can you please confirm that server connected in the pgAdmin is same as psql one ?
>> Should be. To do the tutorial, I run it on the putty, on the same IP address with the pgAdmin one.

 Also please use latest pAdmin 4 version 7.7
 >> Ok, already updated.

Run below command if your server is on linux system
![image](https://github.com/pgadmin-org/pgadmin4/assets/76289958/b1f64f7f-1ab5-4f73-a3f8-a8b50fe4608b)

**Comment by yogeshmahajan-1903** [comment]
@peterfutaro 
Can you please launch psql tool(Doc [link](https://www.pgadmin.org/docs/pgadmin4/development/psql_tool.html)) for the same server from pgAdmin 4 and check schema list over there.

One more thing to check - 
Have you added schema restriction? Please check advanced tab for the database properties containing new schema.
E.g. if only public is specified over here, you will see only public schema listed under schemas node.

<img width="717" alt="Screenshot 2023-10-17 at 1 39 57 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/c18f92a3-37b2-4987-9f92-c231cb98c527">

**Comment by nikhil-mohite** [comment]
No response from the author, closing it.
