### ISSUE TITLE
Hi @cmarrerodb,

### ISSUE THREAD

**Issue by cmarrerodb** [pgadmin-org/pgadmin4#6867]
Hi @cmarrerodb,
 
By can't find query history, do you mean you are not able to find the table? or the history itself is not visible in the table?

_Originally posted by @pravesh-sharma in https://github.com/pgadmin-org/pgadmin4/issues/6666#issuecomment-1765898807_

In my new databases, I disable query history, which is a shame because it's a very useful tool; but in the old ones, it stays loading and the pgadmin crashes, not allowing me to work with them; I need to be able to delete the history of those databases outside of the program to be able to work with those databases

**Comment by adityatoshniwal** [comment]
As per Pravesh, this is created by mistake. Closing.
