### ISSUE TITLE
ERD: Support table inheritance

### ISSUE THREAD

**Issue by wayland** [pgadmin-org/pgadmin4#6868]
**Describe the solution you'd like**

I think the appropriate diagram is https://martinfowler.com/eaaCatalog/classTableInheritance.html .  

It'd be nice if the ERD diagram allowed this structure, which maps pretty well to table inheritance in Postgres.  

**Describe alternatives you've considered**

https://martinfowler.com/eaaCatalog/singleTableInheritance.html which isn't right

**Additional context**

**Comment by adityatoshniwal** [comment]
Duplicates #4998
