### ISSUE TITLE
Support hypertables from TimescaleDb

### ISSUE THREAD

**Issue by ecerichter** [pgadmin-org/pgadmin4#6871]
**Describe the solution you'd like**

I would like that pgAdmin show TimescaleDb hypertables with specific icon, similar to what we have when using partitioned tables.
Sometimes pgAdmin changes the icon like if the hypertable is a partitioned table - but this behavior is erratic and undeterministic.

**Describe alternatives you've considered**

Currently we have to query timescaledb_information.hypertables to check if the table is a hypertable or not.

**Additional context**

![image](https://github.com/pgadmin-org/pgadmin4/assets/2746089/2844e63d-bef1-4270-971c-832aa2e5ce6d)

**Comment by adityatoshniwal** [comment]
pgAdmin do not support TimescaleDB, few things may work as it is based on PostgreSQL.
