### ISSUE TITLE
Correctly show TimescaleDb materialized views as materialized views, not as plain ones

### ISSUE THREAD

**Issue by ecerichter** [pgadmin-org/pgadmin4#6872]
**Describe the solution you'd like**

I would like that pgAdmin show the "continuous" materialized views from TimescaleDb in the group of Materialized Views.
Currently, the views are being shown in the plain Views group.

**Describe alternatives you've considered**

None - currently, the views are shown in the Views group, which is kind of counterintutive.

**Additional context**

![image](https://github.com/pgadmin-org/pgadmin4/assets/2746089/27c1935f-f8b7-4c03-8296-50abd2dd801f)

**Comment by adityatoshniwal** [comment]
pgAdmin do not support TimescaleDB, few things may work as it is based on PostgreSQL.
