### ISSUE TITLE
When using TimescaleDb, statistics are zeroed, but can be filled with data from timescale functions

### ISSUE THREAD

**Issue by ecerichter** [pgadmin-org/pgadmin4#6873]
**Describe the solution you'd like**

Currently, in the statistics tab, almost all fields are zeroed for TimescaleDb hypertables.
Would be nice to get at least basic statistics from function [hypertable_detailed_size()](https://docs.timescale.com/api/latest/hypertable/hypertable_detailed_size/#hypertable_detailed_size)

**Describe alternatives you've considered**

We can run the query over the function hypertable_detailed_size() manually.

**Additional context**

Current information in statistics tab for a hypertable:
![image](https://github.com/pgadmin-org/pgadmin4/assets/2746089/b4212070-e716-4b9a-874d-15eda791f3de)

Real information from hypertable_detailed_size():

![image](https://github.com/pgadmin-org/pgadmin4/assets/2746089/de43af10-ca80-4bfc-96e6-67ef63cfcc1b)

**Comment by adityatoshniwal** [comment]
pgAdmin do not support TimescaleDB, few things may work as it is based on PostgreSQL.
