### ISSUE TITLE
Stuck on spinning with a Oauth user without email

### ISSUE THREAD

**Issue by kzhou57** [pgadmin-org/pgadmin4#6874]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When a user from oauth login, it might not have an email field, if in this case, after login, the page will stuck and keep spinning. 

In the error log, we see
```
   File "/usr/pgadmin4/web/pgadmin/tools/user_management/__init__.py", line 106, in current_user_info
    email=current_user.email.replace("'","\\\\'"),
AttributeError: 'NoneType' object has no attribute 'replace'
``` 
It seems it's a regression of latest release 7.8, it's not reproducible at 7.7. 

And I believe this long is the problem , 

https://github.com/pgadmin-org/pgadmin4/blob/3416184236c75131cd9e2d67cd1414a70d841502/web/pgadmin/tools/user_management/__init__.py#L106

**To Reproduce**

1. Setup an oauth authentication without email, for example : github and set OAUTH2_USERNAME_CLAIM : login
2. Click on Login with github button
3. After been redirected /borrow/ page, the page is stuck. 

**Expected behavior**

Login successfully.

**Error message**

Spinning.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: 7.8
 - Mode: Server / Web
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by olivluca** [comment]
After commenting out the incriminated line (actually just setting email=""), in my case it fails later on, here

```
           config.ALLOW_SAVE_PASSWORD and session['allow_save_password']
            else 'false',
            allow_save_tunnel_password='true' if

```
because the session has no 'allow_save_password' key.
Commenting out the "and session ['allow_save_password']" I can access pgadmin.

**Comment by yogeshmahajan-1903** [comment]
Working fine.

**Comment by olivluca** [comment]
I don't see a fix in trunk for what I reported in my comment
