### ISSUE TITLE
Cannot use Import / Export for shared servers

### ISSUE THREAD

**Issue by MarcelPa** [pgadmin-org/pgadmin4#6875]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When using a shared server not created by the user itself, I am not able to use the Import / Export tool. I receive an "Utility not found" error with the message "Could not find the specified server." when I click to open the Import / Export tool.
I made sure that the paths of the binaries are set correctly. I did not notice any other functions that do not work. If I register the exact same server with the exact same login information (i.e. I do not use the shared server), Import and Export works as expected without issues.

**To Reproduce**

1. Create two users
2. With user A, create a shared server
3. With user B, connect to the shared server
4. Choose any table (or create a new one)
5. Open the Import / Export data tool

**Expected behavior**

The Import / Export data tool opens.

**Error message**

Utility not found
Could not find the specified server.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/25476540/841bf785-129f-4948-be5c-3c37af057dc8)

**Desktop (please complete the following information):**
I run pgAdmin in a Platform-as-a-Service fashion as a Docker Container.
 - OS: Ubuntu (presumably, cannot verify)
 - Version: 22.04 LTS (presumably, cannot verify)
 - Mode:Server
 - Browser (if running in server mode): Firefox, Chromium (tested both)
 - Package type: Docker Container (Tag: 7.8, Container-Digest: eb35f6f)

**Additional context**

This error was present in both pgAdmin4 7.7 and pgAdmin4 7.8.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-11-14/
Environment: macOs Ventura 13.5.1
Package: pip wheel
