### ISSUE TITLE
The "password exec command" max length of 255 is too small

### ISSUE THREAD

**Issue by mconigliaro** [pgadmin-org/pgadmin4#6877]
255 should be big enough for anyone, right? Here's what I need to run to get the password from secrets manager for an RDS instance:

    athm aws exec corp-prod-developer-admin -- aws secretsmanager get-secret-value --secret-id 'arn:aws:secretsmanager:us-east-1:1234567890:secret:rds!cluster-REDACTED' --output json | jq -r '.SecretString | fromjson | .password'

How about no max length?

**Desktop (please complete the following information):**
 - OS: OSX 
 - Version: 7.8
 - Mode: Desktop
 - Package type: Homebrew

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on today's snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-11-09/

OS -  Fedora 38
Mode - Desktop
