### ISSUE TITLE
Binary Paths are incorrectly set on new install

### ISSUE THREAD

**Issue by HarryEClarke** [pgadmin-org/pgadmin4#6880]
Binary Paths are incorrectly set on new install, after uninstalling and deleting previous versions.

As preparation for a new clean install of postgresql, the following steps were carried out on a Windows computer
1) postgresql was uninstalled
2) postgis was uninstalled
3) The directory C:\Program Files\PostgreSQL was deleted to delete all old data files. After the completion of this step, there was no binary or data associated with postgresql.
4) postgresql version 16.0 was installed via the EDB installer
5) postgis was installed via StackBuilder
6) pgAdmin was started, and the Master password set.
7) version 14 server removed as it was not present on the computer
7) a new database was created under the version 16 server
8) When attempting to execute "Restore", an error message reported the binary paths needed to be changed.
9) The option "Preferences/Paths/Binary Paths
The "EDB Advanced Server Binary Path"
and "PostgreSQL Binary Path"
Were both set to the PostgreSQL 14 database server. (this was the version that had been deleted)

The Binary Paths needed to be changed to the PostgreSQL 16 database server, copying and editing the entry.

The binary paths should have been correctly set to the version 16 binaries, as these were the only binaries present on the computer.
The old database servers should not require manually removing when they weren't present on the computer during the install.

It would seem that pgAdmin is using some old information, such as in registry entries, that is not removed on an uninstall, and deletion of data. I would expect on an install, pgAdmin to use what data and binaries are actually present on the computer. I would also expect that an installation of postgresql version 16, then the default path used by pgAdmin should be version 16 regardless of what else is installed on the computer.

The error is repeatable, and occurs on both Windows 10 and Windows 11 computers.

**Comment by khushboovashi** [comment]
Hi,

Have you removed the pgAdmin database file (%APPDATA%/Roaming/pgadmin4/pgadmin4.db), too? Upon installation, the binary paths are stored in this DB file, and while uninstalling the app, this DB file will not be deleted.

Note: If you remove this db file, all the old pgAdmin data will be removed too.

**Comment by HarryEClarke** [comment]
Hi,
No I didn't delete the pgAdmin database file, as I wasn't aware of it. Whereas in an uninstall, I am reminded that the PostgreSQL data was not deleted, there is no reminder for pgAdmin data.

I think as a principle, I would expect pgAdmin to work without having to manually change the binary paths in the circumstances described above.

**Comment by nikhil-mohite** [comment]
Hi @HarryEClarke,

pgAdmin 4 can detect PostgreSQL installation but can’t get the exact location of the binary path. 
We are Closing this.
