### ISSUE TITLE
SQL editor not underlining location of syntax error

### ISSUE THREAD

**Issue by shadysudo** [pgadmin-org/pgadmin4#6887]
I no longer see the location of syntax errors underlined in red in the SQL editor when the messages panel returns a syntax error.

pgadmin versions: 7.7 and 7.8

I have the same experience using the standard windows install of pgadmin4 on Windows 10 and using the docker container from dpage/pgadmin4.

The PostgeSQL database is version 12.

I am expecting customers to be underlined in red like in the documentation linked below https://www.pgadmin.org/docs/pgadmin4/7.8/query_tool.html#messages-panel

**Comment by shadysudo** [comment]
![image](https://github.com/pgadmin-org/pgadmin4/assets/66808114/c604adc4-7260-4832-a239-516b356344cf)

**Comment by anilsahoo20** [comment]
Tested and verified on candidate build: https://developer.pgadmin.org/builds/2023-12-11-1/
Environment: macOs Ventura 13.5.1
Package: arm64 Installer
