### ISSUE TITLE
Inconsistent behavior when docking/undocking windows

### ISSUE THREAD

**Issue by bmercernccer** [pgadmin-org/pgadmin4#6890]
**Describe the bug**
Title bar behavior is inconsistent when attempting to dock an undocked panel/tab/tile/window/whatever-its-called.
 
When the panel is docked, clicking anywhere on the title bar will allow it to be moved to a different docked location. 
When the panel is undocked, you must instead click on the much smaller text label to be able to drag and dock. Clicking on the title bar allows moving, but docking does not function. 

This requirement is not intuitive, and is inconsistent with the behavior when the window is docked. 
 
**To Reproduce**

1. In PGAdmin, click on the title of one of the tabs/panels, such as Processes
2. Drag it up, down, left and right. Observe that it shows docking previews and behaves as a dockable object
3. Drag it down, and dock with the bottom of the application window
4. Now click **anywhere** on the title bar other than the actual title text and drag again
5. Notice that the docking behavior is present, and you can move the window to a new docked location. It is **not** necessary to click directly on the title.
6. Repeat this process, but this time drag the panel to an undocked location
7. Click anywhere on the title bar other than the title. and drag. Notice that it does not display any docking behavior and will not dock
8. Click on the actual title text and drag, and you will see that it does display docking behavior

**Expected behavior**
Clicking and dragging the title bar should behave consistently in all cases. It should not be necessary to memorize a different approach for undocked versus docked panels
Clicking anywhere on the title bar of an undocked panel should allow it to be docked, just as is the case for a docked panel
An inferior alternative would be to have the behavior of docked panels also require clicking directly on the text to drag them. This would be less intuitive, but would at least be consistent.

**Error message**
No error messages

**Screenshots**
Screenshot showing dragging title bar of docked panel with docking behavior working
![image](https://github.com/pgadmin-org/pgadmin4/assets/21127097/b28e02f0-0536-4600-ac38-c3f38a895c28)
Screenshot showing dragging title bar of undocked panel, with docking behavior not functioning
![image](https://github.com/pgadmin-org/pgadmin4/assets/21127097/8b08dca5-b540-4f29-b3ad-909e24d0bf27)

**Desktop (please complete the following information):**
 - OS: Windows 10,11
 - Version: 22H2
 - Mode: Desktop
 - Package type: Windows executable

**Additional context**

Docking behavior in general is weird and confusing compared to other applications, The fact that you have to basically reload everything to reset the layout makes it frustrating when can't figure out the right way to drag things to get the layout you want. Being able to lock the layout helps somewhat, but more intuitive behavior would be helpful. 

Online and local documentation don't address these details. Improving the documentation to specifically explain this behavior would be a good first step.

**Comment by khushboovashi** [comment]
Hi,

We have fixed all these issues with #6479, and they will be available in the next release. Closing it.
