### ISSUE TITLE
Add custom keyboard binding for query execute

### ISSUE THREAD

**Issue by tlam** [pgadmin-org/pgadmin4#6891]
**Describe the solution you'd like**

With other SQL tool, I usually use Shift+Enter or Shift+e to execute a query. This makes writing and executing queries faster.

Is it possible to do a custom keyboard binding to execute a query besides F5?

**Describe alternatives you've considered**

I have been using Table Plus with Shift+e to execute queries.

**Additional context**

**Comment by khushboovashi** [comment]
It is already supported. Use File > Preferences > Query Tool > Keyboard Shortcuts.
Please refer https://www.pgadmin.org/docs/pgadmin4/7.8/preferences.html

Closing the issue.
