### ISSUE TITLE
Support multi-line cursor in query tool

### ISSUE THREAD

**Issue by awhalbert** [pgadmin-org/pgadmin4#6894]
**Describe the solution you'd like**

Similar to VSCode, PyCharm, Notepad++, SSMS, and many other text editors/IDEs, it would be fantastic for pgAdmin 4 to support multiple discontinuous selection areas, AKA "multi-line cursors." In Windows, this is usually accomplished with Alt+Click+Drag or Alt+Shift+Up/Down.

![image](https://github.com/pgadmin-org/pgadmin4/assets/7232559/3bafe810-6e79-4e5f-9fc3-26393e057052)

Some text editors get _really_ fancy and even allow cursors to be placed in different places on each line via consecutive Alt+Clicks:
![image](https://github.com/pgadmin-org/pgadmin4/assets/7232559/d9137739-c9fd-49b2-86ac-2e0c1a4b0d05)

**Describe alternatives you've considered**

I copy/paste my query to an external text editor or try to use find/replace functionality.

**Comment by intellectualDarknet** [comment]
smth that resembles this behavior is ctrl + click in many places where you need it

**Comment by pravesh-sharma** [comment]
@awhalbert you can use  [alt][click & drag] to have multi line cursor.
