### ISSUE TITLE
Repository for Ubuntu 23.10 (Mantic Minotaur) does not exist

### ISSUE THREAD

**Issue by cammarb** [pgadmin-org/pgadmin4#6901]
**Describe the bug**

The repository for Ubuntu 23.10 (Mantic Minotaur) does not exist. 
Even though in the [pgdmin download page](https://www.pgadmin.org/download/pgadmin-4-apt/) it says that version 7.9 is available for the latest release of Ubuntu, when going to [https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/](https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/) you might see that 'mantic' does not exist yet making it impossible to install pgadmin for that specific version of Ubuntu.

**To Reproduce**

1. You should be on Ubuntu 23.10 (Mantic Minotaur)
2. Follow the installation instructions on https://www.pgadmin.org/download/pgadmin-4-apt/:
```
# Setup the repository

# Install the public key for the repository (if not done previously):
curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg

# Create the repository configuration file:
sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'

```

**Expected behavior**

The release pgAdmin file should be added to the repository.

**Error message**

`The repository 'https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/mantic pgadmin4 Release' does not have a Release file.`

**Screenshots**

![error](https://github.com/pgadmin-org/pgadmin4/assets/44549364/5cce83d3-e429-4709-a98f-a768c6c4ef2d)
![pgadmin for mantic not found](https://github.com/pgadmin-org/pgadmin4/assets/44549364/e5ad7581-2ca0-4393-93e6-f89baad28c91)
![pgadmin release page](https://github.com/pgadmin-org/pgadmin4/assets/44549364/0f1c7a38-ffc9-4546-9d1c-1eabaa58dd03)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 23.10
 - Mode: Desktop
 - Package type: deb

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
Ubuntu 23.10 will be supposed from 7.9 onwards.

**Comment by kevinhikaruevans** [comment]
In the meantime, I'm using the lunar release, i.e. `sudo sed -i -e 's/mantic/lunar/g' /etc/apt/sources.list.d/pgadmin4.list`.

It seems to work just fine for the 7.8 release.

**Comment by yisusDev76** [comment]
I was able to successfully install and run pgAdmin4 on Ubuntu 23.10 (Mantic Minotaur) by using the package for Ubuntu 23.04 (Lunar Lobster). Everything seems to be working fine without any issues. Below are the modified commands I used for the installation:


Setup the repository
`curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg`

`sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/lunar pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'`

Install pgAdmin
sudo apt install pgadmin4

**Comment by FelipeHSMartins** [comment]
> I was able to successfully install and run pgAdmin4 on Ubuntu 23.10 (Mantic Minotaur) by using the package for Ubuntu 23.04 (Lunar Lobster). Everything seems to be working fine without any issues. Below are the modified commands I used for the installation:
> 
> Setup the repository `curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg`
> 
> `sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/lunar pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'`
> 
> Install pgAdmin sudo apt install pgadmin4

I can confirm that this solution is working.
This helped me so much, you have no idea. Thank you so much!

**Comment by nikhil-mohite** [comment]
Ubuntu 23.10 will be supported from 7.9 onwards. (23rd Nov 2023)

**Comment by a99divx** [comment]
> I was able to successfully install and run pgAdmin4 on Ubuntu 23.10 (Mantic Minotaur) by using the package for Ubuntu 23.04 (Lunar Lobster). Everything seems to be working fine without any issues. Below are the modified commands I used for the installation:
> 
> Setup the repository `curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg`
> 
> `sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/lunar pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'`
> 
> Install pgAdmin sudo apt install pgadmin4

Working, Thanks bro

**Comment by khosokha** [comment]
> I was able to successfully install and run pgAdmin4 on Ubuntu 23.10 (Mantic Minotaur) by using the package for Ubuntu 23.04 (Lunar Lobster). Everything seems to be working fine without any issues. Below are the modified commands I used for the installation:
> 
> Setup the repository `curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg`
> 
> `sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/lunar pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'`
> 
> Install pgAdmin sudo apt install pgadmin4

it works fine thank you, man.

**Comment by faid-terence** [comment]
> In the meantime, I'm using the lunar release, i.e. `sudo sed -i -e 's/mantic/lunar/g' /etc/apt/sources.list.d/pgadmin4.list`
> 
> It seems to work just fine for the 7.8 release.

Thanks Bruv , This helped !

**Comment by npsang** [comment]
> > I was able to successfully install and run pgAdmin4 on Ubuntu 23.10 (Mantic Minotaur) by using the package for Ubuntu 23.04 (Lunar Lobster). Everything seems to be working fine without any issues. Below are the modified commands I used for the installation:
> > Setup the repository `curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg`
> > `sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/lunar pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'`
> > Install pgAdmin sudo apt install pgadmin4
> 
> I can confirm that this solution is working. This helped me so much, you have no idea. Thank you so much!

Thank you very much it work for me (Ubuntu 23.10)

**Comment by subhroneel** [comment]
Snapshot can be downloaded for mantic. It is available
https://ftp.postgresql.org/pub/pgadmin/pgadmin4/snapshots/2023-11-16/apt/mantic/dists/pgadmin4/main

curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg

sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/snapshots/2023-11-16/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'

sudo apt install pgadmin4
