### ISSUE TITLE
Connection Warning - Application has lost database connection

### ISSUE THREAD

**Issue by tmgarcia70** [pgadmin-org/pgadmin4#6914]
If I am idle for more than a few minutes I receive the attached error message. In last issue report I was asked to upgrade from 7.1 to 7.7 to see if the issue resolved. I just upgraded Monday and no change. 

Pull up a query page and leave idle (time is not consistent) say 30 minutes
Click on refresh button
See the error
*Expected behavior

There are currently 10 other users on the same network. I am the only one using version 7.1 and I am the only user receiving this error. Other users can stay logged in for hours (up to 7) and not receive this error (attached). Once I click on the Continue button it does reconnect me.

Desktop (please complete the following information):

OS: Windows 10, PRO
Version: 7.7
Mode: Desktop
Browser: Edge

[Connection Warning.docx](https://github.com/pgadmin-org/pgadmin4/files/13217827/Connection.Warning.docx)
ge

**Comment by adityatoshniwal** [comment]
Duplicates #6791
