### ISSUE TITLE
PSQL Tool not showing in pgAdmin

### ISSUE THREAD

**Issue by captechno-kbanks** [pgadmin-org/pgadmin4#6915]
Hello,

I have installed "postgresql-15.1-1-windows-x64.exe" onto a Windows Server 2016 box, I downloaded it from the "enterprisedb.com" website.

Attached are the pgAdmin specs from "About pgAdmin 4", a pic' of my PC info' and a pic of the db drop down options when I right click my db.

The PSQL Tool is not there in pgAdmin 4 when I right click on my db, please advise.

Thanks,
Keith

![About My PC](https://github.com/pgadmin-org/pgadmin4/assets/56559298/920037f9-591d-46d2-b70e-8809e487785c)
[About pgAdmin 4.txt](https://github.com/pgadmin-org/pgadmin4/files/13218217/About.pgAdmin.4.txt)
![No PSQL Tool in pgAdmin 4](https://github.com/pgadmin-org/pgadmin4/assets/56559298/d8bfdb09-6d36-48ba-97ab-63f971ad0bce)

**Comment by khushboovashi** [comment]
On Tue, Oct 31, 2023 at 8:55 PM Keith Banks ***@***.***>
wrote:

> Hello,
>
> I have installed "postgresql-15.1-1-windows-x64.exe" onto a Windows Server
> 2016 box, I downloaded it from the "enterprisedb.com" website.
>
> Attached are the pgAdmin specs from "About pgAdmin 4", a pic' of my PC
> info' and a pic of the db drop down options when I right click my db.
>
Your pgAdmin version is 6.15 and it's too old. With PG 15, the latest
pgAdmin should be installed. Have you installed pgAdmin for the first time?
Looks like you have multiple pgAdmin installations on the machine.

**Comment by nikhil-mohite** [comment]
Hi @captechno-kbanks,

On the Windows platform, the PSQL Tool feature is available on Windows 10 (1809 version), and Windows Server 2019 and onwards. so It will be not available on Windows Server 2016
