### ISSUE TITLE
eventlet not working with Python 3.12

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#6926]
We should use eventlet's subprocess once this is fixed [795](https://github.com/eventlet/eventlet/issues/795)

**Comment by malix0** [comment]
[795](https://github.com/eventlet/eventlet/issues/795) now is fixed

**Comment by nikhil-mohite** [comment]
Resolved, Verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-08/
OS: macOS (Sonoma 14.1)
Mode: Server Mode
Package: Pip whl
