### ISSUE TITLE
ERD Tool `Table Relationship Options` giving `Something went wrong` error

### ISSUE THREAD

**Issue by anilsahoo20** [pgadmin-org/pgadmin4#6942]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

ERD Tool gives `Something went wrong` error for Table Relationship Options.

**To Reproduce**

1. Go to ERD Tool
2. Create multiple tables
3. Select a table
4. On click of 1M or MM the dialog shows error `Something went wrong`

**Expected behavior**

The dialog for Table relationship should load and work.

**Screenshots**

<img width="1134" alt="Screenshot 2023-11-07 at 1 29 49 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/122535205/2f2a7b0b-b349-482c-8905-3fb1d8b1329c">

**Desktop (please complete the following information):**
 - OS: OSX Ventura
 - Version: 7.8 (Snapshot build)
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: arm64

**Comment by adityatoshniwal** [comment]
This looks related to the ongoing changes of wcDocker removal.
