### ISSUE TITLE
pgadmin4 fails to install with Fedora 39

### ISSUE THREAD

**Issue by skedee** [pgadmin-org/pgadmin4#6947]
**Describe the bug**

Unable to install admin4 on the newly released Fedora 39. 

The **pgadmin4.repo** has the write information, but the file (below) for Fedora 39 is missing.

https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/fedora/fedora-39-x86_64/repodata/repomd.xml/repodata/repomd.xml

**To Reproduce**

1. sudo rpm -i https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/pgadmin4-fedora-repo-2-2.noarch.rpm
# Install for both desktop and web modes.
sudo yum install pgadmin4

**Expected behavior**

pgadmin4 installed

**Error message**

**Comment by yogeshmahajan-1903** [comment]
pgAdmin does not support Fedore 39 yet.

**Comment by timnis** [comment]
hopefully packages are available soon :) 

pgAdmin4 RPM page says that Fedora 39 is supported...
https://www.pgadmin.org/download/pgadmin-4-rpm/

**Comment by yogeshmahajan-1903** [comment]
It will available from version 7.9 which will be released on 23 Nov.

**Comment by razzeee** [comment]
Having updated fedora from the previous version to 39 has presumably left me with a non-working pgadmin. It tries to start for a long time then accepts defeat.

![image](https://github.com/pgadmin-org/pgadmin4/assets/5943908/7b2ed0f8-c844-4529-967c-323e4db88f7f)

```
Total spawn time to start the pgAdmin4 server: 0.008 Sec
Failed to launch pgAdmin4. Error:
Error: spawn /usr/pgadmin4/venv/bin/python3 ENOENT

```
I suspect, that this might be due to the system python being updated etc - a flatpak would work wonders for this.

**Comment by yogeshmahajan-1903** [comment]
pgAdmin v8.0 is released which is supported on Fedora 39

**Comment by VGerris** [comment]
if I install pgadmin4 in Fedora 39 at the moment, a whole bunch of things gets installed but no command or executable seems to be added?
 pgadmin4-7.8-3.fc39.x86_64.rpm  

Seems like a packaging bug? Why include this if not working ?
