### ISSUE TITLE
Version notation remains unchanged from 7.6

### ISSUE THREAD

**Issue by pea-sys** [pgadmin-org/pgadmin4#6948]
I have a Windows11 22H2 environment with PgAdmin7.6 installed
I installed 7.8 to resolve this issue(#6946)

The installer is downloaded from the following site.
https://www.postgresql.org/ftp/pgadmin/pgadmin4/v7.8/windows/
The name of the downloaded file is pgadmin4-7.8-x64.exe
A dialog message indicates that the installation was successful.
However, when I check the version with PgAdmin4, there is no change.
![1](https://github.com/pgadmin-org/pgadmin4/assets/49807271/f7f3547c-7daa-445e-bf55-540ce45a8383)

When I look at the app list, it shows 7.8.  
![3](https://github.com/pgadmin-org/pgadmin4/assets/49807271/76983a90-2259-4e2d-b173-4e4819e95244)

I uninstalled it and then installed it again, same result.
I tried downgrading to 6.21, but it remains 7.6.

**Comment by yogeshmahajan-1903** [comment]
@pea-sys 
Can you please check in control panel > uninstall programs list what is pgadmin version is installed?

**Comment by adityatoshniwal** [comment]
Also, it is possible you've install 7.6 with PostreSQL installer. In that case, it will not show in uninstall programs list. You'll have to use PostgreSQL uninstaller to selectively uninstall pgAdmin.

**Comment by pea-sys** [comment]
@adityatoshniwal 
After uninstalling postgres, PgAdmin7.6 was uninstalled and now starts with 7.8.
It seems that pgAdmin7.6 was not actually uninstalled.
The installer below must also install PgAdmin, but the version is 7.6.
https://www.enterprisedb.com/downloads/postgres-postgresql-downloads
![1](https://github.com/pgadmin-org/pgadmin4/assets/49807271/b1c02df2-abab-4855-969f-3d225bd2a02b)

So for Windows, you can't replace the PgAdmin included in the postgres installer, and if you want to use the latest version of PgAdmin, you have to install two PgAdmins, right?
![1](https://github.com/pgadmin-org/pgadmin4/assets/49807271/605bee0a-28a7-435b-9abf-f52103c64e44)

Selecting PgAdmin 4 will launch 7.6.
Selecting PgAdmin 4 v7 will launch 7.8.

**Comment by adityatoshniwal** [comment]
@pea-sys you can choose not to install pgAdmin using PostgreSQL installer and use pgAdmin downloaded separately. There is no need/not recommended to install two pgAdmins.

**Comment by pea-sys** [comment]
@adityatoshniwal 
It seems like it's grayed out and I can't remove the checkbox.

**Comment by adityatoshniwal** [comment]
> @adityatoshniwal It seems like it's grayed out and I can't remove the checkbox.

You should be able to. Did you try uncheck?

**Comment by pea-sys** [comment]
@adityatoshniwal 
After uninstalling the individual PgAdmin that I installed and restarting the OS, I was able to uncheck it.
thank you.
