### ISSUE TITLE
pgadmin 4 ver 7.8，When a database table contains triggers, checking its DDL statement will result in an error。

### ISSUE THREAD

**Issue by llw168** [pgadmin-org/pgadmin4#6951]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**
pgadmin 4 ver 7.8，When a database table contains triggers, checking its DDL statement will result in an error。
**Describe the bug**
For a table to create its trigger, and then view its table creation statement in the SQL panel in pgAdmin, this error prompt will appear:syntax error at or near ":tgnargs" LINE 6: ...ray(encode(tgargs, 'escape'), E'\000')::text[])[1:tgnargs] ... ^
![新建位图图像 (2)](https://github.com/pgadmin-org/pgadmin4/assets/18276382/db31178e-2986-4d2b-b834-b28cc878696f)

**To Reproduce**

1. Go to  a  table with a trigger
2. Click on 'SQL' panel
3. See the error

**Screenshots**

![新建位图图像 (2)](https://github.com/pgadmin-org/pgadmin4/assets/18276382/87710d27-aa8a-4086-b283-98b54b8f8151)

**Desktop (please complete the following information):**   pgAdmain v7.8
 - OS: windows10
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode):  chrome
 - Package type: 

**Additional context**

**Comment by adityatoshniwal** [comment]
Duplicates #6940
