### ISSUE TITLE
Ubuntu 23.10

### ISSUE THREAD

**Issue by ibrahimkelly** [pgadmin-org/pgadmin4#6953]
The latest version of Ubuntu is not supported by pgAdmin4

# This process is not working

#
## Setup the repository
#

## Install the public key for the repository (if not done previously):
curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg

## Create the repository configuration file:
sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'

#
## Install pgAdmin
#

## Install for both desktop and web modes:
sudo apt install pgadmin4

## Install for desktop mode only:
sudo apt install pgadmin4-desktop

## Install for web mode only: 
sudo apt install pgadmin4-web 

## Configure the webserver, if you installed pgadmin4-web:
sudo /usr/pgadmin4/bin/setup-web.sh

**Comment by adityatoshniwal** [comment]
Duplicates #6901.
