### ISSUE TITLE
when using ERD tool table that generated with auto increment integer, displayed as integer instead of serial

### ISSUE THREAD

**Issue by DavidHerschler** [pgadmin-org/pgadmin4#6958]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
when using ERD tool table that generated with auto increment integer, displayed as integer instead of serial.

CREATE TABLE IF NOT EXISTS public.chip_positions
(
    chip_position_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    pos_number integer NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    chip_id integer,
    chip_x numeric,
    chip_y numeric,
    excluded boolean,
    CONSTRAINT chip_positions_pkey PRIMARY KEY (chip_position_id),
    CONSTRAINT chip_position_chip_id_fk FOREIGN KEY (chip_id)
        REFERENCES public.chips (chip_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.chip_positions
    OWNER to postgres;
-- Index: IX_chip_positions_chip_id

-- DROP INDEX IF EXISTS public."IX_chip_positions_chip_id";

CREATE INDEX IF NOT EXISTS "IX_chip_positions_chip_id"
    ON public.chip_positions USING btree
    (chip_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: chip_position_pos_number_chip_id_unq

-- DROP INDEX IF EXISTS public.chip_position_pos_number_chip_id_unq;

CREATE UNIQUE INDEX IF NOT EXISTS chip_position_pos_number_chip_id_unq
    ON public.chip_positions USING btree
    (pos_number ASC NULLS LAST, chip_id ASC NULLS LAST)
    TABLESPACE pg_default;

1. create the table
2. Right click on the DB name and choose "ERD for database"
3. See the error the field chip_position_id would be of type integer instead of serial.

**Expected behavior**

It should displays Serial.

If possible, include the full, unedited text of any error messages displayed.

![image](https://github.com/pgadmin-org/pgadmin4/assets/142316748/e5b6eea9-fe35-4e19-9749-2424349e5bf9)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10,]
 - Version: [7.8]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by adityatoshniwal** [comment]
@DavidHerschler This is not a bug. You're using identity column and not a serial column. Best we can do is instead of just `integer`, we can show it as `integer(identity)`.
