### ISSUE TITLE
How to fix Postgres error - "connection timeout expired"

### ISSUE THREAD

**Issue by Suspect128482** [pgadmin-org/pgadmin4#6959]
![Screenshot from 2023-11-11 10-02-57](https://github.com/pgadmin-org/pgadmin4/assets/150483916/bae1c8b4-bcdd-4391-8154-383629b84205)
If you are getting said "connection timeout expired" error when trying to connect to your PostGreSQL server
Simply;
-Go to Windows Run  (windows + R)
-Type in "services.msc"
-Go to the Postgresql service and manually start it 
![Screenshot from 2023-11-11 10-03-40](https://github.com/pgadmin-org/pgadmin4/assets/150483916/8a6bc7cd-e691-46f3-8690-692c67d8118b)
Voila problem solved, unsure why even though the Startup Type is automatic I had to manually turn it on
Had this problem for ages and solved it myself couldn't find anything helpful online, so hopefully this will help :)

**Comment by Suspect128482** [comment]
Also restarting the service might help if it is going already :)

**Comment by Suspect128482** [comment]
Also within C:\program files\postgresql\16\data\postgresql.conf make sure the listening address it set to "*" not a loopback address for ipv4 or 6 (127.0.0.1::1), this should enable you to start the service manually

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Pabl0l** [comment]
THANK U SO MUCH <3

**Comment by Vini0100** [comment]
THANK

**Comment by Bang28** [comment]
Not work for me sir, please help

**Comment by Mognatti** [comment]
Thanks, you are a life saver!

**Comment by Arthurpeixoto25** [comment]
> Not work for me sir, please help

look into your postgresql logs in /var/log/postgresql/postgresql-{version}-main.log

**Comment by MthetheleliMbuyisa** [comment]
Thank you champ

**Comment by deepsalternate** [comment]
Thanks man I was  searching for solution for hours finally found it . Thanks

**Comment by muhammadshahms** [comment]
Thank you

**Comment by myatsoekaung** [comment]
It works for me, thank u for your solution. I appreciate it.

**Comment by osipov-slava** [comment]
Check contex menu - Properties/Connection/Port
try 5432 or 5433 or which you use. I had 5433 in this field. May be from previous installation
Additionally your brandmayer/antivirus app can block access
![image](https://github.com/pgadmin-org/pgadmin4/assets/55810653/e78008d6-0371-4234-a39e-f863fde3311b)

**Comment by chrajeshdagur** [comment]
Thanks!

**Comment by akhilpraghav407** [comment]
thanks!!!

**Comment by emrucar** [comment]
> Not work for me sir, please help

Delete all PostgreSQL files, then download 15.6 Version https://www.enterprisedb.com/downloads/postgres-postgresql-downloads

**Comment by techiemithlesh** [comment]
> Also within C:\program files\postgresql\16\data\postgresql.conf make sure the listening address it set to "*" not a loopback address for ipv4 or 6 (127.0.0.1::1), this should enable you to start the service manually

Already applied this but still the same issue facing

**Comment by G3ntleM4n** [comment]
You can try open "Reload configuration" as Administrator. It helped me

**Comment by omar-medhat2** [comment]
worked

**Comment by Endeathia** [comment]
Thank you this helps

**Comment by Jasoshin** [comment]
Thanks, dude. It works ^^

**Comment by amjed-elhami** [comment]
Restaring the service was not enough to resolve the issue. 
I solved it by deleting the folder C:\Users\<username>\AppData\Roaming\pgadmin, then changing the port in postgresql.conf and restarting the service and pgAdmin.

**Comment by CLANOM2255** [comment]
Thank you bro!!!

**Comment by sreyaz01** [comment]
Well I Upgraded my Postgres from 15 to 16 after smoothly Transfaring my database to Postgres V16 I uninstalled V15 and changed My V16 port to 5432, before it Was 5433 (coz I needed both versions of server to transfer Databases and 5432 was taken by V15). and after Manually Installing PgAdmin4 v8.11 I found out that the server properties has port no 5433 which is no longer belong to v16 that why I was facing this issue. so I changed it manually and Voilla PgAdmin is now connected. 
But I still dont know Why PgAdmin configured the port 5433 by itself may be some left overs by old PgAdmin version.

**Comment by yogeshmahajan-1903** [comment]
@sreyaz01 
If server is configured by user, then pgadmin does not change any setting for it on its own. As you port is changed for the server, you need to update that server manually.

**Comment by kenewang** [comment]
Thank You!

**Comment by sreyaz01** [comment]
@yogeshmahajan-1903 
Thanks For the Info 
 Issue was that I installed PGadmin after manually changing the Port to 5432, by default PGadmin should consider port as 5432 but it had 5433 as auto configured. 
%appdata% had some old PgAdmin related Files whic can be reason for this weird auto config.

**Comment by watagalawgbn** [comment]
> Check contex menu - Properties/Connection/Port try 5432 or 5433 or which you use. I had 5433 in this field. May be from previous installation Additionally your brandmayer/antivirus app can block access ![image](https://private-user-images.githubusercontent.com/55810653/310008722-e78008d6-0371-4234-a39e-f863fde3311b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTY1MzksIm5iZiI6MTcyNTcxNjIzOSwicGF0aCI6Ii81NTgxMDY1My8zMTAwMDg3MjItZTc4MDA4ZDYtMDM3MS00MjM0LWEzOWUtZjg2M2ZkZTMzMTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDEzMzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZjIyNmMzMjFiNDU3YmQyY2RiZDRkNzdkZWExYTcyODc1ZWJhM2FhNzNkMzc2MGU3ODIzZmQwNGVmNjcyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BzJbMwey3YLTdpcBD3DBxWmpTPk8EFUohiso-m02LVw)

Thank you so much, this helped me

**Comment by abelshanoj** [comment]
Thanks bro..

**Comment by 1259xcdh** [comment]
Thank U so much (^-^)

**Comment by shreyareddyedulakanti** [comment]
> osipov-slava

Thank you for the solution. I installed my postgres on wrong port and changed it after reinstalling it but it was not working. Then, I made this change and it worked.

**Comment by kxitosxmx** [comment]
Thank you so much

**Comment by Nicolini7** [comment]
I searched a lot for a solution but my Windows was stopping the service right after starting it, so I found the solution in the error logs.
If anyone is having this problem (cannot start the service) just delete the "postmaster.pid" file in the "\Program Files\PostgreSQL\17\data" folder.
Then just start the service and it will work.

**Comment by arunragavan115** [comment]
TQ Bro

**Comment by NathanBC21** [comment]
Thanks, you're a life savior man

**Comment by NathanBC21** [comment]
> Check contex menu - Properties/Connection/Port try 5432 or 5433 or which you use. I had 5433 in this field. May be from previous installation Additionally your brandmayer/antivirus app can block access ![image](https://github.com/pgadmin-org/pgadmin4/assets/55810653/e78008d6-0371-4234-a39e-f863fde3311b)

Thanks man, you're a life savior.

**Comment by dian2051isna** [comment]
Thanks a lot bro :)

**Comment by 21Ovi** [comment]
It worked!!! Thank you soo much @Suspect128482

**Comment by harschr** [comment]
> Check contex menu - Properties/Connection/Port try 5432 or 5433 or which you use. I had 5433 in this field. May be from previous installation Additionally your brandmayer/antivirus app can block access ![image](https://github.com/pgadmin-org/pgadmin4/assets/55810653/e78008d6-0371-4234-a39e-f863fde3311b)

THANK YOU!!!

**Comment by paulperezzurita** [comment]
If I want to load libpq.dll in my delphi code using LoadLibrary before connecting to the database. How should I do?

**Comment by alisazjy** [comment]
Thank you！！
