### ISSUE TITLE
Not confirm character[] data type from Foreign Table Dialog.

### ISSUE THREAD

**Issue by kato-sho** [pgadmin-org/pgadmin4#6962]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Not confirm character[] data type from Foreign Table Dialog.

**To Reproduce**

1. Create foreign table which contains character[] type column. 
2. Click Properties on foreign table which is created step 1.
3. See Data type columns of Columns tab in Foreign Table Dialog and not confirm character[] from this view.

**Expected behavior**

We could confirm character[] data type from Foreign Table Dialog.

**Error message**

no error messages happen.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/9005031/155d6ea2-9236-431f-bcab-763b7f052959)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Version: 7.8
 - Mode: Desktop
 - Package type: Windows installer

**Additional context**

I could confirm character[] data type from Foreign Table Dialog in v7.7.

**Comment by adityatoshniwal** [comment]
I can confirm this bug. Reproducible.

**Comment by yogeshmahajan-1903** [comment]
Working fine.
