### ISSUE TITLE
Schema Not Visible in Dropdown of table properties or while creating a new table.

### ISSUE THREAD

**Issue by raprocks** [pgadmin-org/pgadmin4#6964]
The Selection where we can select the schema the table should be part of doesn't show any other schema than "public".

1. Create a new Schema
2. Try Creating a Table by right clicking on the tables item under the new schema.
3. The Schema selection is empty and doesn't show any other schema apart from public.

**Expected behavior**

All Schemas to be listed.

**Error message**

NA

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/52972480/224163e8-9387-4130-98de-850d3a32c2d8)
![image](https://github.com/pgadmin-org/pgadmin4/assets/52972480/88b08321-48a8-4d2e-9651-e532a18a4f6b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 7.8
 - Mode: Dont Know
 - Browser (if running in server mode): Check attached image
 - Package type: Windows Installation.

**Comment by raprocks** [comment]
Cannot Change Schema for a existing table as well. Wanted to move around tables to better categorize them. but cannot due to this. Obviously Querying is a way but just a bug report.

**Comment by adityatoshniwal** [comment]
I can confirm this bug. Workaround is to Right Click and refresh the server node once.

**Comment by raprocks** [comment]
Tried, even restarted the whole app. doesn't seem to work for me.

**Comment by adityatoshniwal** [comment]
> Tried, even restarted the whole app. doesn't seem to work for me.

Can you share a screen recording please? Because with server node refresh it works fine - in your case "Anchor".

**Comment by raprocks** [comment]
alright let me try once again and record this time. hopefully it works

**Comment by raprocks** [comment]
Okay Tried, and it works the way you said it would. Workaround fix works. but the main issue still persists. would be good if someone took a look at it.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-05/
Package: amr64
Environment: macOs ventura 13.5.1
