### ISSUE TITLE
pgagent doesn't work for Windows 10 and windows 2019 server

### ISSUE THREAD

**Issue by binliucam** [pgadmin-org/pgadmin4#6965]
The pgagent windows version for postgresql 12 and 16 don't work for windows 10 and windows server 2019. I downloaded them via EDB installer, both version pgagent stuck at starting stage, didn't do anything further.  Windows 10 is a laptop, Windows 2019 is a virtual machine. 

Probably this is why there is no downloadable pgagent windows version from the official web site.

**Comment by akshay-joshi** [comment]
Please log this issue [here](https://github.com/pgadmin-org/pgagent/issues)
