### ISSUE TITLE
GSSAPI authentication on Redhat8 and PostgreSQL15/16

### ISSUE THREAD

**Issue by YeeY23** [pgadmin-org/pgadmin4#6966]
Good day to all of you. I am attempting to configure Windows authentication on the Red Hat Linux server to connect to Windows AD. I chose the GSSAPI authentication method, but unfortunately, it is not working. May I ask a few questions:

1) What is the recommended authentication method from PostgreSQL if we want to use Windows authentication from Linux?
2) Do I need to generate a keytab file for every user or do I need to modify the /etc/krb5.keytab file?
3) Do I need to set up the Linux server domain name the same as the username domain name, e.g., [serverName@domainname.com] and domainname/username?
4) According to PostgreSQL 15 (hostgssenc - This record matches connection attempts made using TCP/IP but only when the connection is made with GSSAPI encryption. To make use of this option, the server must be built with GSSAPI support. Otherwise, the hostgssenc record is ignored, except for logging a warning that it cannot match any connections.) - which kind of components should Linux OS install to use GSSAPI authentication?". Recently my Linux OS only can find cyrus-sasl-gssapi.x86_64 rsyslog-gssapi.x86_64.

Thank you. Regards

**Comment by pravesh-sharma** [comment]
Hi @YeeY23,

This seems to be more related to PostgreSQL configuration. You will find better help at pgsql-admin@postgresql.org

**Comment by YeeY23** [comment]
Hi Pravesh-sharma, noted and thank you.
