### ISSUE TITLE
ERD Tool does not generate SQL correctly

### ISSUE THREAD

**Issue by FabBarWork** [pgadmin-org/pgadmin4#6973]
After creating an ERD model, the SQL generated based on this model is missing ALL the columns definitions for ALL the tables.
The code generated for each table is something like this:
CREATE TABLE IF NOT EXISTS public.auth_user
(

    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);
![test-pgerd](https://github.com/pgadmin-org/pgadmin4/assets/148258892/8be5b29f-64b7-47ba-9cb2-d7e47a4ccfb5)

**Comment by pravesh-sharma** [comment]
Duplicates #6920.
