### ISSUE TITLE
drop-down menus are almost unreadable in MATE

### ISSUE THREAD

**Issue by ccurvey** [pgadmin-org/pgadmin4#6974]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

The grey-on-grey text when using pgAdmin4 in MATE is nearly unreadable.  See attached screenshot

**To Reproduce**

Start pgAdmin on MATE with the default color scheme.   Try to find the menu.

**Expected behavior**

I should be able to easily see that there is a drop-down menu available

**Error message**

N/A/

**Screenshots**

![pgadmin-color](https://github.com/pgadmin-org/pgadmin4/assets/385577/1a2bab5b-332c-4b77-b758-c643c2d05709)

**Desktop (please complete the following information):**
 - OS: Ubuntu using the MATE desktop environment
 - Version: 7.8
 - Mode: Desktop
 - Browser: n/a
 - Package type: APT

**Additional context**

N/A

**Comment by adityatoshniwal** [comment]
Hi @ccurvey,
Can you please try latest version of pgAdmin?

**Comment by ccurvey** [comment]
It  works!  And the whole interface looks so much nicer in 8.14!  Thank you!
