### ISSUE TITLE
How do I define users with read-only role in k8s secrets?

### ISSUE THREAD

**Issue by khteh** [pgadmin-org/pgadmin4#6981]
**Describe the solution you'd like**
I am running pgadmin4 in my k8s cluster which has a secret file for `PGADMIN_DEFAULT_EMAIL` and `PGADMIN_DEFAULT_PASSWORD`. How do I define users in k8s manifests so that I don't have to manually create them every time when the app restarts?

**Describe alternatives you've considered**

**Additional context**

**Comment by adityatoshniwal** [comment]
Hi @khteh,
You can map the pgAdmin data directory to an outside external location which will persist. Please check - https://www.pgadmin.org/docs/pgadmin4/7.8/container_deployment.html#mapped-files-and-directories.
