### ISSUE TITLE
User Management does not show custom created role in the "Role column

### ISSUE THREAD

**Issue by khteh** [pgadmin-org/pgadmin4#6982]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**
![image](https://github.com/pgadmin-org/pgadmin4/assets/3871483/7109afc8-0bf6-4e15-b352-8ade15969a97)

How do I create and assign new user to custom role?
**Describe the bug**

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey] Ubuntu
 - Version: [e.g. 6.15] latest
 - Mode: [e.g Desktop or Server] Server
 - Browser (if running in server mode): [e.g. chrome, safari] Chrome
 - Package type: [e.g. RPM, DEB, Python, Container, etc.] Container

**Additional context**

**Comment by adityatoshniwal** [comment]
pgAdmin do not support custom roles.
