### ISSUE TITLE
User Management add user to `pg_read_all_data`

### ISSUE THREAD

**Issue by khteh** [pgadmin-org/pgadmin4#6983]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**
I want to create pgadmin4 user which only has read access. How to do that? The User Management does not allow me to assign to the builtin role `pg_read_all_data`

![Screenshot from 2023-11-20 14-05-57](https://github.com/pgadmin-org/pgadmin4/assets/3871483/7d6e0d8a-421f-406b-8178-e8be407a82da)

**Describe the bug**

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
@khteh 
pgAdmin user is different from database user. At the moment, pgAdmin user can not be created with Read-Only access.
Can you please elaborate the requirement?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
