### ISSUE TITLE
(Dismissable) alerts have a transparent background

### ISSUE THREAD

**Issue by Sophist-UK** [pgadmin-org/pgadmin4#6997]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

(Dismissable) alerts have a transparent background (and a 1px black **but transparent** border). In my case it was a dismissable alert about today's new release.

**Expected behavior**

So that alerts are more obvious and less confusing they should have a non-transparent background.

Ideally by using a pastel background colour or bold border colour this would indicate the severity of the alert.

This should be a simple CSS change.

**Screenshots**

Without background colour:
![image](https://github.com/pgadmin-org/pgadmin4/assets/3001893/614ed740-a18e-4746-845f-2e03504704dc)

With manually added white background colour and border made non-transparent:
![image](https://github.com/pgadmin-org/pgadmin4/assets/3001893/e6147d2e-517d-48c1-8a62-d5b8c5469051)

Using .alert-Warning class to set border and background colour:
![image](https://github.com/pgadmin-org/pgadmin4/assets/3001893/6aad8490-fb07-491d-bb70-ca846344c051)

**Comment by yogeshmahajan-1903** [comment]
This issue is fixed in v8.0
