### ISSUE TITLE
Error in SQL tab when using extended index

### ISSUE THREAD

**Issue by osapon** [pgadmin-org/pgadmin4#7002]
**Describe the bug**

I am using the full-text search index extension called [pgroonga](https://pgroonga.github.io/).
Up to pgAdmin4 v6, I was able to display the SQL tab for this index, but after v7 an error occurs.

**To Reproduce**

``` SQL

CREATE TABLE IF NOT EXISTS public.tt_note
(
    id character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    other jsonb NOT NULL,
    CONSTRAINT tt_note_pkey PRIMARY KEY (id)
        USING INDEX TABLESPACE nvme_index
)
TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_note_other_notag
    ON public.tt_note USING pgroonga
    ((other ->> 'notag'::text) COLLATE pg_catalog."default")
    TABLESPACE pg_default;
```

**Expected behavior**

I want it to be displayed the same way as it was in v6.

**Error message**

Error
'pgroonga'

**Screenshots**

v6 https://gyazo.com/8cdbeab96327cb0272c8b2a08713ffeb
v7 https://gyazo.com/44d932deb95cbc6e44c8a0b79588e1ec
v8 https://gyazo.com/b55b34e0b2bdf3ae2380d16d5d1b2782

 - OS: Windows 10
 - Version: 7.8, 8.0
 - Mode: Desktop
 - Package type: Installer

**Comment by akshay-joshi** [comment]
How to test on OSX:

1. brew install pgroonga
2. sudo cp /usr/local/Cellar/pgroonga/3.1.5/share/postgresql@14/extension/pgroonga* /Library/PostgreSQL/14/share/postgresql/extension/
3. sudo cp /usr/local/Cellar/pgroonga/3.1.5/lib/postgresql@14/pgroonga*.* /Library/PostgreSQL/14/lib/postgresql/
4. Connect to the database and run "CREATE EXTENSION pgroonga"

**Comment by nikhil-mohite** [comment]
Resolved, Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-26/
OS: macOS
Mode: Desktop
