### ISSUE TITLE
Copying query editor output with JSON produces invalid tsv

### ISSUE THREAD

**Issue by StefanBrand** [pgadmin-org/pgadmin4#7004]
**Describe the bug**

When I copy output from the query editor that contains a JSON column, the output is unusable because it is quoted incorrectly.

**To Reproduce**

1. Execute `SELECT json_build_object('foo', 'bar', 'baz', 'qux')`
2. Copy output
4. Get `"{""foo"" : ""bar"", ""baz"" : ""qux""}"`

**Expected behavior**

Quotes in output should be escaped or the JSON string should be surrounded by single quotes.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/8948865/4ed5be67-69bf-45cd-90d7-887ee21ad4fd)

**Desktop (please complete the following information):**
- Version: 6.15
- Application Mode: Server
- Browser: Firefox 120.0
- Operating System: Linux-5.10.179-166.674.amzn2.x86_64-x86_64-with

**Comment by StefanBrand** [comment]
Ah, thank you, this is very helpful!

**Comment by yogeshmahajan-1903** [comment]
Result grid provides CSV escape output, which will be above format.([Ref](https://jsonformatter.org/csv-escape)).
To copy data in json format, double click cell and copy from json editor. Hence rejecting the issue.
