### ISSUE TITLE
Can't find any projects after authentication

### ISSUE THREAD

**Issue by TimChinye** [pgadmin-org/pgadmin4#7008]
Upon registering/deploying a cloud instance, select Google Cloud SQL and authenticate, it now endlessly loads for projects (I only have one) on my account.

![image](https://github.com/pgadmin-org/pgadmin4/assets/150863066/542e48c5-e86b-41fb-a635-5ee464b09bde)

... I don't know what other information I can add.

**Comment by yogeshmahajan-1903** [comment]
@TimChinye 
Can you please check networks tab in development console of browser and share screenshot by keeping headers  and repose tab focused? If there is an access issue then, dropdown will be empty. 3 dots indicates request to google cloud is still in progress.

**Comment by TimChinye** [comment]
False Alarm: I didn't allow my IP as one of the "Authorized networks"
