### ISSUE TITLE
The "All Rows" and "Filter Rows" buttons are deactivated for Views

### ISSUE THREAD

**Issue by beno1705** [pgadmin-org/pgadmin4#7011]
Since version 8.0, Views can no longer be displayed using the "All Rows" and "Filter Rows" buttons. The buttons are deactivated for Views. This was still possible in version 7.8.

**Describe the bug**

If a view is selected in the Object Explorer, the two buttons have no function. They are then deactivated.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**
![image](https://github.com/pgadmin-org/pgadmin4/assets/76453076/24210da9-bfe2-409d-b3a2-7f2d1346bad0)

**Desktop**
 - OS: Windows 10
 - Version: 
 - Mode: 
 - Browser  chrome, firefox, edge, ...
 - Package type: Container (dpage/pgadmin4:8.0)

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-05/
Package: arm64
Environment: macOs Ventura 13.5.1
