### ISSUE TITLE
Docker Container Duplicate DBs Imported

### ISSUE THREAD

**Issue by espey** [pgadmin-org/pgadmin4#7012]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Hello! I am running pgadmin in a docker container within ECS. We utilize the entrypoint.sh when pgadmin is getting booted as a container in ECS (which is located at /entrypoint.sh). This mostly works fine. The part where we are running into issues is in regards to loading the servers via the json file we supply. Once a new container is booted to replace our old container we have running (which we do for various recycles and updates) the server json file is read again and the command `/venv/bin/python3 /pgadmin4/setup.py --load-servers "${PGADMIN_SERVER_JSON_FILE}" --user "${PGADMIN_DEFAULT_EMAIL}"` is executed. This works fine but it duplicates the server which already exists within pgadmin and then we end up having 2 servers when subsequently logging into the UI. This can happen over and over and over and the list will accumulate accordingly. I've found a workaround to this by appending the `--replace` flag to the above command in the entrypoint.sh but I feel like there should be an easier way in order to get this to work.

**To Reproduce**

1. launch a docker container with a server.json
2. launch another docker container with the same server.json
3. replace the old container with the new one and view the UI for pgadmin and observe duplicates of the same server imported

**Expected behavior**

I would expect the next time a container is booted, the same DB in servers.json is the one that is loading in the UI (not a duplicate or many duplicates of the server).

**Desktop (please complete the following information):**
 - Version: 7.6
 - Mode: Server
 - Browser: Chrome
 - Package type: Container

**Comment by anilsahoo20** [comment]
Hi @espey 
If you are using an external mounted data directory, then the server information will persist across docker restart.
--replace will essentially remove all the existing servers and add again from the servers.json.

You can use servers.json for the first load, and then avoid for later restarts.

**Comment by adityatoshniwal** [comment]
No response from the user, closing.
