### ISSUE TITLE
add keep-alive support on ssh session when connecting to postgresql server over ssh-tunnel 

### ISSUE THREAD

**Issue by exedx7** [pgadmin-org/pgadmin4#7016]
Possibility of configuring ssh tunnel with keep-alive feature.

Connection->properties windows -> tab: 'SSH Tunnel'
Add row in the input form and apply non zero value to the ssh session settings.
Keep-Alive interval (sec)      0 (means no-keep-alive enabled), >0 keep-alive enabled

No alternatives

-

Without K-A when we have connection over ssh-tunnel we can face with the situation that connection is dropped in case timeout of inactivity is configured on ssh-server site (ClientAliveInterval>0).

-

**Comment by nikhil-mohite** [comment]
Resolved, Verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-25/
OS: macOS (Sonoma)
Mode: Desktop
