### ISSUE TITLE
Schema Diff saved Preferences not activated on starting Schema Diff (PG Admin version 8.0)

### ISSUE THREAD

**Issue by ddjuric1** [pgadmin-org/pgadmin4#7017]
Hi.

1. In File->Preferences - Schema Diff section checking some or all 4 setting options.
2. Start Schema Diff - Compare button (down popup menu) non of previously checked options is checked.

Regards

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-07/
Package: arm64
Environment: macOs Ventura 13.5.1
