### ISSUE TITLE
Unable to open new Query tab when multiple tab panes are open

### ISSUE THREAD

**Issue by MaxEtMoritz** [pgadmin-org/pgadmin4#7018]
**Describe the bug**

When having multiple tab panes side by side in PGAdmin, it is not possible to open another query tab.

**To Reproduce**

1. Connect to some server
2. Open a query tab
3. drag the query tab to one side of the screen to get two tab panes side by side
4. focus the other tab pane
5. click to open another query tab
6. see the error

**Expected behavior**

Another query tab opens in the tab pane that has the focus

**Error message**

To gather the error message, i opened the pgadmin 4 log of the desktop app and opened the application server URL present there in a browser.
The error is taken from the browser console of my browser:

```
17:42:59.968 Uncaught TypeError: document.querySelector(...) is null
    n app.bundle.js:151768
    _set_dynamic_tab app.bundle.js:151770
    value app.bundle.js:132087
    value app.bundle.js:132157
    s app.bundle.js:151871
    showQueryTool app.bundle.js:151817
    value app.bundle.js:132053
    initializeToolbar app.bundle.js:45607
    __trigger vendor.main.js:2
    __init vendor.main.js:2
    dispatch vendor.main.js:2
    handle vendor.main.js:2
app.bundle.js:151768:145
    n app.bundle.js:151768
    forEach self-hosted:203
    _set_dynamic_tab app.bundle.js:151770
    value app.bundle.js:132087
    value app.bundle.js:132157
    s app.bundle.js:151871
    showQueryTool app.bundle.js:151817
    value app.bundle.js:132053
    initializeToolbar app.bundle.js:45607
    __trigger vendor.main.js:2
    __init vendor.main.js:2
    dispatch vendor.main.js:2
    handle vendor.main.js:2
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows-10-10.0.19045-SP0
 - Version: 7.6
 - Mode: Desktop (Opened in Browser to get the error message)
 - Browser (if running in server mode): Desktop App: Chromium 114.0.5735.91. For gathering the error message: Firefox
 - Package type: exe

**Additional context**

**Comment by adityatoshniwal** [comment]
Hi @MaxEtMoritz,
Please upgrade to v8.0, the layout UI is revamped and the issue is not reproducible on 8.0.

**Comment by MaxEtMoritz** [comment]
@adityatoshniwal yes you're right. No longer reproducible on v8.0.
Thank you for the hint.
Will close this issue since it's already fixed.
