### ISSUE TITLE
PGadmin4:6.9 dont see certificates when  user authenticate by OAUTH2 in  Keycloack

### ISSUE THREAD

**Issue by ArslanShaydulla** [pgadmin-org/pgadmin4#7019]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
I configured protocol  OAUTH2 authorization according to instructions https://www.pgadmin.org/docs/pgadmin4/development/oauth2.html  from PGAdmin to  Keycloack.
The administrator copied the self-signed certificate of the authorization server into the container with the pidge and executed the certification update command (update-ca-certificates). Curl - command for checking requests works with this site without problems.  For Example: /pgadmin4 # curl https://blk-astra-v01/
<!doctype html><html lang=""><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>belka-digital-interface</title><script defer="defer" src="/js/chunk-vendors.bd941e30.js"></script><script defer="defer" src="/js/app.8fa4a3ac.js"></script><link href="/css/chunk-vendors.362d8d9c.css" rel="stylesheet"><link href="/css/app.133ce26a.css" rel="stylesheet"></head><body><noscript><strong>We're sorry but belka-digital-interface doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div></body></html>
When  user  sign in Keycloak a message is displayed in the web interface: {"success":0,"errormsg":"HTTPSConnectionPool(host='blk-astra-v01', port=443): Max retries exceeded with url: /auth/realms/belka/protocol/openid-connect/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","info":"","result":null,"data":null}
![curl](https://github.com/pgadmin-org/pgadmin4/assets/29603499/d8c31fda-bab9-444f-b271-8b10122a03dc)
![pgadmin_kc1](https://github.com/pgadmin-org/pgadmin4/assets/29603499/48d2d95e-2ac3-49d9-b42c-d6c8e4cdd1ed)
![pgadmin_kc2](https://github.com/pgadmin-org/pgadmin4/assets/29603499/ad904154-f720-4636-9057-25000578bc23)
![pgadmin_kc3](https://github.com/pgadmin-org/pgadmin4/assets/29603499/3815527d-5bed-4e62-8539-9ce0e176b095)

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
@ArslanShaydulla 
Can you please share your docker-compose.yaml?  Are you accessing pgadmin over SSL protocol?
Possible duplicate of #6095
