### ISSUE TITLE
Reset Layout does not work after double-click on ">" (expand Servers)

### ISSUE THREAD

**Issue by casparsch** [pgadmin-org/pgadmin4#7025]
After double clicking on the ">" symbol preceding the "Servers" the screen/page turns completely white. Only the menubar remains. So the obvious way to go would be to reset the layout (File > Reset Layout)
However this did not work.

The only way to overcome this is closing pgAdmin, which in turn closes the other windows (e.g. query-windows) started from that pgAdmin instance, and restart pgAdmin

**Expected behavior**
One of following (in order of _my_ preference)
1. Double-click expands the node
2. Do not allow double click to expand "Servers"
3. Menu-item does a reset of the layout

**Screenshots**

Double-click:
![pgAdmin-start](https://github.com/pgadmin-org/pgadmin4/assets/121792923/79e6ff74-ee1b-4307-8553-a5ad6eb837d8)

... leads to:
![pgAdmin-blanc](https://github.com/pgadmin-org/pgadmin4/assets/121792923/3efc3258-2a72-4996-88a3-1a6bddb77e40)

**Desktop**
 - OS: Rocky
 - Version:9.3
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: RPM

**Comment by casparsch** [comment]
@adityatoshniwal 



pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/logon/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - SHELL: /bin/bash
  - SESSION_MANAGER: local/unix:@/tmp/.ICE-unix/2482,unix/unix:/tmp/.ICE-unix/2482
  - HISTCONTROL: ignoredups
  - XDG_MENU_PREFIX: gnome-
  - HOSTNAME: 192.168.2.9
  - HISTSIZE: 1000
  - GNOME_SHELL_SESSION_MODE: classic
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - XMODIFIERS: @im=ibus
  - DESKTOP_SESSION: gnome-classic
  - PWD: /home/logon
  - XDG_SESSION_DESKTOP: gnome-classic
  - LOGNAME: logon
  - XDG_SESSION_TYPE: wayland
  - MODULESHOME: /usr/share/Modules
  - MANPATH: /usr/share/man:
  - SYSTEMD_EXEC_PID: 2502
  - XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.5MI3E2
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - GDM_LANG: en_US.UTF-8
  - __MODULES_SHARE_MANPATH: :1
  - HOME: /home/logon
  - USERNAME: logon
  - LANG: en_US.UTF-8
  - XDG_CURRENT_DESKTOP: GNOME-Classic:GNOME
  - WAYLAND_DISPLAY: wayland-0
  - INVOCATION_ID: cf39b13fb53f43b189a317d826291992
  - MANAGERPID: 2344
  - GJS_DEBUG_OUTPUT: stderr
  - GNOME_SETUP_DISPLAY: :1
  - XDG_SESSION_CLASS: user
  - LESSOPEN: ||/usr/bin/lesspipe.sh %s
  - USER: logon
  - MODULES_RUN_QUARANTINE: LD_LIBRARY_PATH LD_PRELOAD
  - LOADEDMODULES: 
  - DISPLAY: :0
  - SHLVL: 0
  - QT_IM_MODULE: ibus
  - XDG_RUNTIME_DIR: /run/user/1000
  - __MODULES_LMINIT: module use --append /usr/share/Modules/modulefiles:module use --append /etc/modulefiles:module use --append /usr/share/modulefiles
  - DEBUGINFOD_URLS: https://debuginfod.centos.org/ 
  - which_declare: declare -f
  - JOURNAL_STREAM: 8:30659
  - XDG_DATA_DIRS: /home/logon/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
  - PATH: /usr/pgsql-15/bin/:/home/logon/.local/bin:/home/logon/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
  - MODULEPATH: /etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
  - GDMSESSION: gnome-classic
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - MAIL: /var/spool/mail/logon
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 17432
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - MODULES_CMD: /usr/share/Modules/libexec/modulecmd.tcl
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 33553
  - PGADMIN_INT_KEY: 34bb3f6c-7818-447d-9e10-d6891d059536
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.226 Sec
2023-12-01 11:52:59,247: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 13.035 Sec
------------------------------------------
Total launch time of pgAdmin4: 13.4 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:33553/?key=34bb3f6c-7818-447d-9e10-d6891d059536
--------------[UI error]---------------
TypeError: Cannot read properties of undefined (reading 'constructor')
    at f.getItemAtIndex (http://127.0.0.1:33553/static/js/generated/vendor.others.js?ver=80000:109:1456149)
    at getItemKey (http://127.0.0.1:33553/static/js/generated/vendor.others.js?ver=80000:109:1456600)
    at b.render (http://127.0.0.1:33553/static/js/generated/vendor.react.js?ver=80000:2:302800)
    at Ul (http://127.0.0.1:33553/static/js/generated/vendor.react.js?ver=80000:2:139147)
    at Vl (http://127.0.0.1:33553/static/js/generated/vendor.react.js?ver=80000:2:138946)
    at Ka (http://127.0.0.1:33553/static/js/generated/vendor.react.js?ver=80000:2:179777)
    at Ps (http://127.0.0.1:33553/static/js/generated/vendor.react.js?ver=80000:2:165999)
    at _s (http://127.0.0.1:33553/static/js/generated/vendor.react.js?ver=80000:2:165927)
    at Is (http://127.0.0.1:33553/static/js/generated/vendor.react.js?ver=80000:2:165790)
    at ws (http://127.0.0.1:33553/static/js/generated/vendor.react.js?ver=80000:2:162777)
------------[UI End]----------------

**Comment by casparsch** [comment]
Accidentally closed

**Comment by akshay-joshi** [comment]
Hi @casparsch 

We are not able to reproduce the issue. Can you please share the screen recording?

**Comment by casparsch** [comment]
I do not have any screen recording on my Rocky Linux.

However I noticed once the pgAdmin has been opened displaying the server-nodes and then double-click on the ">" it closes or opens that tree-node.. the default (expected) behaviour.
So start up pgAdmin and then double-click that ">" node to open servers.
Furthermore I was also told (colleague experienced the same) if you have grouped servers, the behavior happens when you double-click on the opening of the **group** opening the servers underneath and not on the top-node. This colleague has one level of groups and all beneath are servers.
Hope this might help.

**Comment by akshay-joshi** [comment]
Duplicate #5771

**Comment by casparsch** [comment]
@akshay-joshi 
It is still applicable for version 8.5.
So just closing this issue without reason would not be my way to go.
> That feels not being respectful to me. I can think of reasons, but that is only me guessing, based on assumptions. So now I'm into the dark.

Like in #7338  the reason for closing was the author was not responding.
As #5771 is still open having the same effect, but from other starting point (reproduction-path), it could be the same reason. So whenever that one is resolved I'm still willing to test this issue.

**Comment by adityatoshniwal** [comment]
> Duplicate #5771

@casparsch If you read again the comment why it was closed, you'll notice it says `Duplicate 5771`. Clearly, it is going to be fixed in 5771.
