### ISSUE TITLE
Dependent of a "type" does not show underlying "type"

### ISSUE THREAD

**Issue by casparsch** [pgadmin-org/pgadmin4#7027]
When a user-defined-type is used as an attribute in _another_ user-defined-type this is not reflected in the dependencies-tabs ("Dependencies" or "Dependents")

**Request**
Add the dependencies of user-defined-type in those tabs
_My assumption is pg_type with `typtype = 'b'` are postgres-native types (i.e. **not** user-defined)._

**Alternatives used**
Wrote my own query which did the job for _me_. However it might not be sufficient/correct enough.
```
select  chd.oid::regtype
,       par.oid::regtype
,       *
from    pg_type     chd
join    pg_depend   dep on (dep.refobjid = chd.oid)
join    pg_class    pcl on (dep.objid = pcl.oid)
join    pg_type     par on (pcl.reltype = par.oid)
where   dep.deptype = 'n'             -- A potential flaw?
and     chd.typname = 'SOME INPUT REQUIRED'
```
The column `dep.objsubid` shows the position within the "parent-type", which in turn can be used to get the attribute-**name**

**NOTE** it is also applicable for defined domain(s) used in types. However domains are also registered in pg_type (`typtype = 'd'`)

**Comment by casparsch** [comment]
Query mentioned by @pravesh-sharma is not the issue I described.
I did not mention extensions it is just using type/domain in an-other type
```
create type test1 as
  (  attr_int integer
  );
create type test2 as
  (  attr_int   integer
  ,  attr_test1 test1  -- Overhere we use a previously defined type named: "test1" --> dependency to show
  );
```
You can extract that dependency (in one way) via the query in my original request. So better use that one as reference-query

**Comment by pravesh-sharma** [comment]
Hi @casparsch,

The query mentioned by be was meant for another issue I have mistakenly put it here. Thanks for bringing it to notice.

**Comment by anilsahoo20** [comment]
Tested and verified on candidate build: https://developer.pgadmin.org/builds/2024-03-04-1/
Environment: Debian 12

**Comment by casparsch** [comment]
Thanks a lot for resolving this issue :+1:
