### ISSUE TITLE
The pgAdmin 4 server could not be contacted

### ISSUE THREAD

**Issue by Hai-TN** [pgadmin-org/pgadmin4#7036]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**
The pgAdmin 4 server could not be contacted
**Describe the bug**
The pgAdmin 4 server could not be contacted

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

please help, i can't start pgadmin on linux system (debian 11.8)
![Screenshot_2023-12-04_23-46-05](https://github.com/pgadmin-org/pgadmin4/assets/106439850/c24fa91c-5993-4d98-ab61-153b56f9dff8)
![Screenshot_2023-12-04_23-45-51](https://github.com/pgadmin-org/pgadmin4/assets/106439850/e931cffc-fe7e-4387-a07b-609c652d960c)

**Comment by adityatoshniwal** [comment]
Hi @Hai-TN,
Please share the complete log from the dialog in the screenshot.

**Comment by Hai-TN** [comment]
> Hi @Hai-TN, Please share the complete log from the dialog in the screenshot.

![Screenshot_2023-12-05_10-29-46](https://github.com/pgadmin-org/pgadmin4/assets/106439850/8d550bae-57fd-4b2e-833d-67f5e1a97a0c)
![Screenshot_2023-12-05_14-05-23](https://github.com/pgadmin-org/pgadmin4/assets/106439850/b7693d10-9274-4df3-b49f-445ee903ea51)
![Screenshot_2023-12-05_14-05-42](https://github.com/pgadmin-org/pgadmin4/assets/106439850/856df815-d1ba-4dc5-97a0-b936fc0dedce)
![Screenshot_2023-12-05_14-05-55](https://github.com/pgadmin-org/pgadmin4/assets/106439850/74bcf08e-c3b6-4fb6-b6a2-9b149d0ee8ea)

**Comment by Hai-TN** [comment]
> @Hai-TN Share the OS details please. It is advised to add it when originally creating the issue.



![Screenshot_2023-12-05_17-26-08](https://github.com/pgadmin-org/pgadmin4/assets/106439850/0b8b7f1c-c534-4712-a5cf-9c9c3010252f)

**Comment by adityatoshniwal** [comment]
OK, so it seems there is some issue with the venv of pgAdmin.
Can you share the output of?
```
ls -l /usr/pgadmin4/venv/bin/python3
ls -l /usr/bin/python3*
ls -l /usr/local/bin/python3*
```
Alternatively, you can also try completely uninstall pgAdmin and re-install fresh. You server config information will not be removed.

**Comment by Hai-TN** [comment]
i uninstalled pgadmin4 completely then reinstall fresh OS and pgadmin4 but the issue still doesn't improve


![Screenshot_2023-12-05_17-26-08](https://github.com/pgadmin-org/pgadmin4/assets/106439850/bc86c937-57d3-4cdb-add9-9391694b8f24)

**Comment by adityatoshniwal** [comment]
OK @Hai-TN,
try running the below command
```
sudo ln -sf /usr/bin/python3.11 /usr/pgadmin4/venv/bin/python3
```

**Comment by Hai-TN** [comment]
> OK @Hai-TN, try running the below command
> 
> ```
> sudo ln -sf /usr/bin/python3.11 /usr/pgadmin4/venv/bin/python3
> ```

another issue 

![Screenshot_2023-12-05_19-09-30](https://github.com/pgadmin-org/pgadmin4/assets/106439850/eb7523aa-37b9-4942-bcda-ad6785471469)

**Comment by yogeshmahajan-1903** [comment]
@Hai-TN 
Have you upgraded from Debian 10 to 11? If yes, please run below command - 
```
sudo rm /etc/apt/sources.list.d/pgadmin4.list
```
Ans recreate pgAdmin 4 repo configuration. Refer this [link](https://www.pgadmin.org/download/pgadmin-4-apt/).

**Comment by Hai-TN** [comment]
i install debian 11.8 directly not upgrade from any other version

> @Hai-TN Have you upgraded from Debian 10 to 11? If yes, please run below command -
> 
> ```
> sudo rm /etc/apt/sources.list.d/pgadmin4.list
> ```
> 
> Ans recreate pgAdmin 4 repo configuration. Refer this [link](https://www.pgadmin.org/download/pgadmin-4-apt/). And try reinstalling.

i install debian 11.8 directly not upgrade from any other version, i reinstalled OS and pgadmin4 step by step in the [link](https://www.pgadmin.org/download/pgadmin-4-apt/)

**Comment by yogeshmahajan-1903** [comment]
@Hai-TN 
Can you please try below command?

```
sudo apt install --reinstall pgadmin4-serve
```

**Comment by PAAPII10** [comment]
The one who is facing this issue on windows

Follow below steps

1. Close your pgAdmin(very imp)
2. Go to This PC
3. Go to Local Disk C
4.  Go to Users
5. Go to name of your PC ... FOLDERS:(Default/Public/This will be probably your folder with your username)
6. Go to AppData
7. Go to Roaming
8. Delete your pgAdmin Folder
9. Now last step.. In search bar seach pgAdmin and **run it as administrator**

hope this steps works for you

Thank you

**Comment by yogeshmahajan-1903** [comment]
> Ubuntu 22.04 pgAdmin4 latest - the same error.
Please try this solution.
https://github.com/pgadmin-org/pgadmin4/issues/7036#issuecomment-1941394704

**Comment by gabrieltemtsen** [comment]
> > Ubuntu 22.04 pgAdmin4 latest - the same error.
> > Please try this solution.
> > [#7036 (comment)](https://github.com/pgadmin-org/pgadmin4/issues/7036#issuecomment-1941394704)

Tried the commands from the solution and installed freshly again using the instructions here: https://www.pgadmin.org/download/pgadmin-4-apt/
And it is working fine now.
Thanks @yogeshmahajan-1903

**Comment by yogeshmahajan-1903** [comment]
As per user, this is working fine. Hence closing the issue.

**Comment by kiruiaaron** [comment]
I have the same issue in Kali linux 2024.1, any solution?

**Comment by homailali** [comment]
I have fixed this issue by downgrading to version 14 from 16 and also make sure to add "path\pgAdmin 4\runtime" to your enviromental variables if you are using windows

**Comment by AmanVerma1998** [comment]
> The one who is facing this issue on windows
> 
> Follow below steps
> 
> 1. Close your pgAdmin(very imp)
> 2. Go to This PC
> 3. Go to Local Disk C
> 4. Go to Users
> 5. Go to name of your PC ... FOLDERS:(Default/Public/This will be probably your folder with your username)
> 6. Go to AppData
> 7. Go to Roaming
> 8. Delete your pgAdmin Folder
> 9. Now last step.. In search bar seach pgAdmin and **run it as administrator**
> 
> hope this steps works for you
> 
> Thank you

thanks bro this helped me

**Comment by opadonou** [comment]
> > The one who is facing this issue on windows
> > Follow below steps
> > 
> > 1. Close your pgAdmin(very imp)
> > 2. Go to This PC
> > 3. Go to Local Disk C
> > 4. Go to Users
> > 5. Go to name of your PC ... FOLDERS:(Default/Public/This will be probably your folder with your username)
> > 6. Go to AppData
> > 7. Go to Roaming
> > 8. Delete your pgAdmin Folder
> > 9. Now last step.. In search bar seach pgAdmin and **run it as administrator**
> > 
> > hope this steps works for you
> > Thank you
> 
> thanks this helped me

**Comment by James0512** [comment]
create bat file:

@echo off

set "no_proxy=127.0.0.1,localhost"

set "NO_PROXY=127.0.0.1,localhost"

start "" "C:\Program Files\pgAdmin 4\pgAdmin4.exe"
