### ISSUE TITLE
Error during yarn install, dependencies not satisfied

### ISSUE THREAD

**Issue by shawn-olson-veeva** [pgadmin-org/pgadmin4#7048]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When trying to build a Docker image from the latest source code package, several errors come up related to unresolved dependencies during the app-builder phase when running 'yarn install'

**To Reproduce**

1. Navigate to un-tarred directory
2. Run: docker build .

**Expected behavior**

Docker image created successfully

**Error message**

[+] Building 92.3s (42/66)
 => [internal] load build definition from Dockerfile                                                                                                                                        0.0s
 => => transferring dockerfile: 7.81kB                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                           0.0s
 => => transferring context: 35B                                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/postgres:13-alpine                                                                                                                       0.7s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                                                                            0.7s
 => [internal] load metadata for docker.io/library/postgres:16-alpine                                                                                                                       0.7s
 => [internal] load metadata for docker.io/library/postgres:12-alpine                                                                                                                       0.7s
 => [internal] load metadata for docker.io/library/postgres:15-alpine                                                                                                                       0.7s
 => [internal] load metadata for docker.io/library/postgres:14-alpine                                                                                                                       0.7s
 => [internal] load build context                                                                                                                                                           0.4s
 => => transferring context: 347.97kB                                                                                                                                                       0.4s
 => CACHED [app-builder 1/6] FROM docker.io/library/alpine:latest@sha256:51b67269f354137895d43f3b3d810bfacd3945438e94dc5ac55fdac340352f48                                                   0.0s
 => => resolve docker.io/library/alpine:latest@sha256:51b67269f354137895d43f3b3d810bfacd3945438e94dc5ac55fdac340352f48                                                                      0.0s
 => CACHED [pg16-builder 1/1] FROM docker.io/library/postgres:16-alpine@sha256:a1efa4ac090c9065ecce437f78af3e4f6034311e04ab0055d5f8032e1fd03b60                                             0.0s
 => [pg15-builder 1/1] FROM docker.io/library/postgres:15-alpine@sha256:6d66512f38f92cf2cb75584bbd280de1b3f8a6f73e1f684a361ea6af7360256b                                                    0.0s
 => [pg14-builder 1/1] FROM docker.io/library/postgres:14-alpine@sha256:6a0e35296341e676fe6bd8d236c72afffe2dfe3d7eb9c2405c0f3fc04500cd07                                                    0.0s
 => [pg13-builder 1/1] FROM docker.io/library/postgres:13-alpine@sha256:eb4068de4c3771b1bdf0a339170a3b88c24edf9c3540091cdfdda6319ed004f6                                                    0.0s
 => [pg12-builder 1/1] FROM docker.io/library/postgres:12-alpine@sha256:52b412657170b7038d560f330f6465bdd521f3d1781ece28a021a6bbb6dc4eff                                                    0.0s
 => CACHED [tool-builder  2/21] COPY --from=pg12-builder /usr/local/bin/pg_dump /usr/local/pgsql/pgsql-12/                                                                                  0.0s
 => CACHED [tool-builder  3/21] COPY --from=pg12-builder /usr/local/bin/pg_dumpall /usr/local/pgsql/pgsql-12/                                                                               0.0s
 => CACHED [tool-builder  4/21] COPY --from=pg12-builder /usr/local/bin/pg_restore /usr/local/pgsql/pgsql-12/                                                                               0.0s
 => CACHED [tool-builder  5/21] COPY --from=pg12-builder /usr/local/bin/psql /usr/local/pgsql/pgsql-12/                                                                                     0.0s
 => CACHED [tool-builder  6/21] COPY --from=pg13-builder /usr/local/bin/pg_dump /usr/local/pgsql/pgsql-13/                                                                                  0.0s
 => CACHED [tool-builder  7/21] COPY --from=pg13-builder /usr/local/bin/pg_dumpall /usr/local/pgsql/pgsql-13/                                                                               0.0s
 => CACHED [tool-builder  8/21] COPY --from=pg13-builder /usr/local/bin/pg_restore /usr/local/pgsql/pgsql-13/                                                                               0.0s
 => CACHED [tool-builder  9/21] COPY --from=pg13-builder /usr/local/bin/psql /usr/local/pgsql/pgsql-13/                                                                                     0.0s
 => CACHED [tool-builder 10/21] COPY --from=pg14-builder /usr/local/bin/pg_dump /usr/local/pgsql/pgsql-14/                                                                                  0.0s
 => CACHED [tool-builder 11/21] COPY --from=pg14-builder /usr/local/bin/pg_dumpall /usr/local/pgsql/pgsql-14/                                                                               0.0s
 => CACHED [tool-builder 12/21] COPY --from=pg14-builder /usr/local/bin/pg_restore /usr/local/pgsql/pgsql-14/                                                                               0.0s
 => CACHED [tool-builder 13/21] COPY --from=pg14-builder /usr/local/bin/psql /usr/local/pgsql/pgsql-14/                                                                                     0.0s
 => CACHED [tool-builder 14/21] COPY --from=pg15-builder /usr/local/bin/pg_dump /usr/local/pgsql/pgsql-15/                                                                                  0.0s
 => CACHED [tool-builder 15/21] COPY --from=pg15-builder /usr/local/bin/pg_dumpall /usr/local/pgsql/pgsql-15/                                                                               0.0s
 => CACHED [tool-builder 16/21] COPY --from=pg15-builder /usr/local/bin/pg_restore /usr/local/pgsql/pgsql-15/                                                                               0.0s
 => CACHED [tool-builder 17/21] COPY --from=pg15-builder /usr/local/bin/psql /usr/local/pgsql/pgsql-15/                                                                                     0.0s
 => CACHED [tool-builder 18/21] COPY --from=pg16-builder /usr/local/bin/pg_dump /usr/local/pgsql/pgsql-16/                                                                                  0.0s
 => CACHED [tool-builder 19/21] COPY --from=pg16-builder /usr/local/bin/pg_dumpall /usr/local/pgsql/pgsql-16/                                                                               0.0s
 => CACHED [tool-builder 20/21] COPY --from=pg16-builder /usr/local/bin/pg_restore /usr/local/pgsql/pgsql-16/                                                                               0.0s
 => CACHED [tool-builder 21/21] COPY --from=pg16-builder /usr/local/bin/psql /usr/local/pgsql/pgsql-16/                                                                                     0.0s
 => CACHED [app-builder 2/6] RUN apk add --no-cache     autoconf     automake     bash     g++     git     libc6-compat     libjpeg-turbo-dev     libpng-dev     libtool     make     nasm  0.0s
 => CACHED [app-builder 3/6] COPY web /pgadmin4/web                                                                                                                                         0.0s
 => CACHED [app-builder 4/6] RUN rm -rf /pgadmin4/web/*.log            /pgadmin4/web/config_*.py            /pgadmin4/web/node_modules            /pgadmin4/web/regression            `fin  0.0s
 => CACHED [app-builder 5/6] WORKDIR /pgadmin4/web                                                                                                                                          0.0s
 => CACHED [env-builder 2/3] COPY requirements.txt /                                                                                                                                        0.0s
 => ERROR [app-builder 6/6] RUN export CPPFLAGS="-DPNG_ARM_NEON_OPT=0" &&     yarn set version berry &&     yarn set version 3 &&     yarn install &&     yarn run bundle &&     rm -rf n  90.6s
 => CANCELED [env-builder 3/3] RUN     apk add --no-cache         make         python3         py3-pip &&     apk add --no-cache --virtual build-deps         build-base         openssl-  91.1s
------
 > [app-builder 6/6] RUN export CPPFLAGS="-DPNG_ARM_NEON_OPT=0" &&     yarn set version berry &&     yarn set version 3 &&     yarn install &&     yarn run bundle &&     rm -rf node_modules
        yarn.lock            package.json            .[^.]*            babel.cfg            webpack.*            jest.config.js            babel.*            ./pgadmin/static/js/generated/.cach
e:
#49 3.190 ➤ YN0000: Retrieving https://repo.yarnpkg.com/4.0.2/packages/yarnpkg-cli/bin/yarn.js
#49 3.803 ➤ YN0000: Saving the new release in .yarn/releases/yarn-4.0.2.cjs
#49 3.813 ➤ YN0000: Done in 0s 624ms
#49 4.878 ➤ YN0000: Downloading https://repo.yarnpkg.com/3.7.0/packages/yarnpkg-cli/bin/yarn.js
#49 5.096 ➤ YN0000: Saving the new release in .yarn/releases/yarn-3.7.0.cjs
#49 5.114 ➤ YN0000: Done in 0s 237ms
#49 5.808 ➤ YN0000: ┌ Resolution step
#49 6.155 ➤ YN0002: │ @projectstorm/react-diagrams-defaults@npm:6.7.4 [c980e] doesn't provide resize-observer-polyfill (p654e6), requested by @projectstorm/react-diagrams-core
#49 6.155 ➤ YN0002: │ @projectstorm/react-diagrams-routing@npm:6.7.4 [c980e] doesn't provide @emotion/react (pa5377), requested by @projectstorm/react-diagrams-defaults
#49 6.155 ➤ YN0002: │ @projectstorm/react-diagrams-routing@npm:6.7.4 [c980e] doesn't provide @emotion/styled (paf795), requested by @projectstorm/react-diagrams-defaults
#49 6.155 ➤ YN0002: │ @projectstorm/react-diagrams-routing@npm:6.7.4 [c980e] doesn't provide resize-observer-polyfill (p70306), requested by @projectstorm/react-diagrams-core
#49 6.155 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide @emotion/react (p15192), requested by @projectstorm/react-diagrams-defaults
#49 6.155 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide @emotion/styled (p77d06), requested by @projectstorm/react-diagrams-defaults
#49 6.155 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide dagre (p4f195), requested by @projectstorm/react-diagrams-routing
#49 6.155 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide lodash (p9304f), requested by @projectstorm/react-diagrams-core
#49 6.155 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide lodash (pa7e7b), requested by @projectstorm/react-diagrams-defaults
#49 6.156 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide lodash (pd1305), requested by @projectstorm/react-diagrams-routing
#49 6.156 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide pathfinding (p116b1), requested by @projectstorm/react-diagrams-routing
#49 6.156 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide paths-js (pc959f), requested by @projectstorm/react-diagrams-routing
#49 6.156 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide react (pf13b2), requested by @projectstorm/react-diagrams-core
#49 6.156 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide react (p8f259), requested by @projectstorm/react-diagrams-defaults
#49 6.156 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide react (p5cdc5), requested by @projectstorm/react-diagrams-routing
#49 6.157 ➤ YN0002: │ @projectstorm/react-diagrams@npm:6.7.4 doesn't provide resize-observer-polyfill (p62060), requested by @projectstorm/react-diagrams-core
#49 6.157 ➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide @testing-library/dom (pa2b9f), requested by @testing-library/user-event
#49 6.157 ➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide aspen-core (p39d1e), requested by aspen-decorations
#49 6.157 ➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eve (p422b3), requested by snapsvg-cjs
#49 6.157 ➤ YN0060: │ root-workspace-0b6124@workspace:. provides react (pbe399) with version 17.0.2, which doesn't satisfy what react-aspen requests
#49 6.157 ➤ YN0060: │ root-workspace-0b6124@workspace:. provides react (p55e25) with version 17.0.2, which doesn't satisfy what react-new-window requests
#49 6.158 ➤ YN0060: │ root-workspace-0b6124@workspace:. provides react-dom (p8731a) with version 17.0.2, which doesn't satisfy what react-aspen requests
#49 6.158 ➤ YN0060: │ root-workspace-0b6124@workspace:. provides react-dom (p83c5d) with version 17.0.2, which doesn't satisfy what react-new-window requests
#49 6.158 ➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide react-is (pc48dd), requested by styled-components
#49 6.158 ➤ YN0060: │ root-workspace-0b6124@workspace:. provides svgo (p4997b) with version 2.8.0, which doesn't satisfy what svgo-loader requests
#49 6.158 ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
#49 6.160 ➤ YN0000: └ Completed in 0s 352ms
#49 6.161 ➤ YN0000: ┌ Fetch step
#49 46.53 ➤ YN0000: └ Completed in 40s 373ms
#49 46.64 ➤ YN0000: ┌ Link step
#49 70.94 ➤ YN0007: │ @fortawesome/fontawesome-free@npm:6.4.2 must be built because it never has been before or the last one failed
#49 70.95 ➤ YN0007: │ core-js@npm:3.31.0 must be built because it never has been before or the last one failed
#49 70.95 ➤ YN0007: │ mozjpeg@npm:8.0.0 must be built because it never has been before or the last one failed
#49 70.95 ➤ YN0007: │ optipng-bin@npm:7.0.1 must be built because it never has been before or the last one failed
#49 70.95 ➤ YN0007: │ ttf2woff2@npm:4.0.5 must be built because it never has been before or the last one failed
#49 71.34 ➤ YN0009: │ mozjpeg@npm:8.0.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-467e7d9a/build.log)
#49 71.82 ➤ YN0000: └ Completed in 25s 184ms
#49 72.04 ➤ YN0000: Failed with errors in 1m 7s
------
executor failed running [/bin/sh -c export CPPFLAGS="-DPNG_ARM_NEON_OPT=0" &&     yarn set version berry &&     yarn set version 3 &&     yarn install &&     yarn run bundle &&     rm -rf node_
modules            yarn.lock            package.json            .[^.]*            babel.cfg            webpack.*            jest.config.js            babel.*            ./pgadmin/static/js/gene
rated/.cache]: exit code: 1

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.0
 - Mode: Server
 - Browser (if running in server mode): N/A
 - Package type: Container from source tar.gz

**Additional context**

On 2023-12-07 I was able to have the docker image build successfully several times until late afternoon US Mountain time when errors started to occur when building, so I suspect some dependencies were updated and broke the build process, but I can't figure out which ones need to be fixed. Any help is appreciated!

**Comment by akshay-joshi** [comment]
@shawn-olson-veeva 

Can you please try the "**docker build . --no-cache**" command? Please update

**Comment by shawn-olson-veeva** [comment]
Thanks @akshay-joshi that seems to have fixed it, the docker image built successfully!
