### ISSUE TITLE
pgadmin schema diff generates nonsense SQL for a certain schema migration

### ISSUE THREAD

**Issue by bamo** [pgadmin-org/pgadmin4#7049]
pgadmin version: 8.0 (and 6.8)

Note: I've changed table & column names because our actual DB schema contains company confidential architectural details.

We rely upon pgadmin schema diff to generate SQL scripts to migrate our DB forward when we make schema changes.  Generally, it works well, and we have had few issues.  However, in this particular case, schema diff generated some SQL that doesn't make any sense.  Before I explain the generated SQL, let me give some background on our use-case.

We express our DB schema as a single SQL file.  The typical use-case for schema diff is that we have a running DB with data in it, but the schema has changed, and we want to upgrade the DB in place.  What we usually do before applying anything to the running DB is as follows:
 - Obtain the schema for the running DB using [pg_dump](https://www.postgresql.org/docs/current/app-pgdump.html)
 - Spin up two local "dummy" postgres instances.
 - Execute the dumped schema on one of the dummy instances (target instance)
 - Execute the schema from our git repo (latest schema) on the second dummy instance (source instance)
 - Connect pgadmin to the source & target instances
 - Run schema diff and obtain the migration script
 - Do a dry run where we run the migration script on the target instance, and then do a re-diff to ensure the schemas are identical
 - Then, and only then, upgrade the actual live DB using the same migration script that worked properly in the dry run.

In this case, our dry run was failing because schema diff generated the following SQL:
```sql
ALTER TABLE IF EXISTS public.object
    ADD CONSTRAINT object_other_id_fkey FOREIGN KEY (other_id)
    REFERENCES public.unrelated_id_key (other_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
```

The problem is that `unrelated_id_key` is a UNIQUE CONSTRAINT from another table (neither the `object` nor `other` table).  What should be there is `public.other` (the table being referenced by the foreign key).

When I dug into this, I found that, in the source schema, schema diff sees the foreign key constraint correctly.
To be clear, the following is taken from the DDL comparison view within pgadmin schema diff:
```sql
CREATE TABLE public.object
(
    object_id objectid COLLATE pg_catalog."default" NOT NULL,
    other_id otherid COLLATE pg_catalog."default",
    ... columns omitted ...
    CONSTRAINT object_pkey PRIMARY KEY (object_id),
    CONSTRAINT object_other_id_fkey FOREIGN KEY (other_id)
        REFERENCES public.other (other_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
```

Note that there were only two changes to this particular table in this diff.  First was the addition of the foreign key constraint object_other_id_fkey, and second was removal of a different column in the `object` table.  The `other` table was not changed in any way as a part of this schema change.

All this made it seem highly likely to me that this is an issue with pgadmin/schema diff itself, since schema diff sees the correct constraint declaration in the source schema, but for some reason replaces `public.other` with `public.unrelated_id_key`.

A few notes about the issue:
1. Given the same schemas to diff, the outcome seems deterministic; schema diff always generates the same nonsense diff.
2. I tried to create a minimal reproduction of this issue by removing tables one-by-one, but we have a rather large schema.  Sometimes, removing tables, indexes, etc., led to a nonsense diff, and other times, the correct diff.  I could not make sense of why removing certain tables "fixed" the issue and others did not.  What is perhaps more interesting is that, as I removed tables, *what* ended up in the `public.other` spot changed.  Sometimes it was a unique constraint; other times a primary key constraint or foreign key constraint from another table.  I gave up on making a minimal reproduction, because I think it would take me a long time to do so.
3. We originally observed this behavior in pgadmin 6.8, the version we normally use, but I thought it might be an issue that was already discovered and fixed upstream.  So, I downloaded pgadmin 8.0 and tried diffing the schemas, and it gave the same nonsensical diff as 6.8

I'm happy to provide additional context where it would be helpful, but I do not think I can provide our exact schemas as they are company proprietary.  If I can help by running any additional tests against these schemas, please let me know, as I'm happy to do so.

**Comment by bamo** [comment]
Also in case it helps:
```
-- Dumped from database version 14.9
-- Dumped by pg_dump version 14.5 (Ubuntu 14.5-1.pgdg20.04+1)
```

**Comment by adityatoshniwal** [comment]
Hi @bamo,
I tried to reproduce with the steps you mentioned and I found schema diff working fine. Can you share the correct DDL for object table on both schemas. Or may a dump of SQL to help us reproduce this.
<img width="1589" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/76ddc330-71ee-4d7b-93f2-082b5317b895">

**Comment by nikhil-mohite** [comment]
No response from the user, closing it.
