### ISSUE TITLE
APT Victoria pgadmin4 Release 404  Not Found [IP: 72.32.157.246 443]

### ISSUE THREAD

**Issue by ilentt** [pgadmin-org/pgadmin4#7052]
**Describe the bug**
Error when create the repository configuration file during install pgadmin-4 follow instructions [pgadmin-4-apt](https://www.pgadmin.org/download/pgadmin-4-apt/).

**To Reproduce**

1. Install the public key for the repository (if not done previously):
``curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg``
**Result: OK**

2. Create the repository configuration file:
``sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'``
**Result: Error**

3. See the error
```
https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/victoria pgadmin4 Release
  404  Not Found [IP: 72.32.157.246 443]
```

5. Error message
```
The repository 'https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/victoria pgadmin4 Release' does not have a Release file.
```

6. Screenshots

![InstallpgAdminError](https://github.com/pgadmin-org/pgadmin4/assets/11204504/448639e2-23fd-4ddf-bc3d-03e96954e217)

**Desktop (please complete the following information):**

```
System:
  Kernel: 5.15.0-91-generic x86_64 bits: 64 compiler: gcc v: 11.4.0
    Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33 wm: muffin dm: LightDM 1.30.0
    Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

Repos:
  Packages: apt: 2728
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http://packages.linuxmint.com victoria main upstream import backport
    2: deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/pgadmin4.list
    1: deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/victoria pgadmin4 main
```

**Additional context**
n/a

**Comment by yogeshmahajan-1903** [comment]
pgAdmin4 does not support Linux Mint.
