### ISSUE TITLE
Object list in object tab of backup popup it's truncated

### ISSUE THREAD

**Issue by folstuff** [pgadmin-org/pgadmin4#7053]
when i choose the backup menu item, with right click on database name, the popu up show me a tab (objects) with the list of schema to backup but the list is incomplete as you can see from the image enclosed.
I'm usign pgadmin4 ver 8.0 with docker image on ubuntu 22.04 desktop
![Schermata del 2023-12-12 11-45-39](https://github.com/pgadmin-org/pgadmin4/assets/4680520/394a13f3-faa7-4e82-b9bc-24afd1edd60a)

**Comment by nikhil-mohite** [comment]
Hi @folstuff,

The objects tab of the backup dialog shows only those schemas that have at least a single node of Tables, Views, Materialized Views, Sequences, or Foreign Tables present in the schema. Can you please check if the missing schemas have any of these nodes present?

**Comment by folstuff** [comment]
No they dont' have, but they have hundreds of  functions that I want backup

**Comment by folstuff** [comment]
however, it may also happen that a backup of only the schema is needed even if it is empty.
As you can see I use a lot of schemas and remembering them all to do the restore manually is inconvenient as well as not automatic unless you resort to scripts which certainly complicate everything

**Comment by folstuff** [comment]
What about add an option to hide schema empty ?

**Comment by folstuff** [comment]
another thing: it is not intuitive, by clicking on the check box that allows you to select all the schemes, you make a partial selection.
the first time I used this option I thought
that I had made a backup of all the schemes (except the public one which I deselected) then in the subsequent restore I noticed the error.
in the meantime, however, I lost some work done.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-22/

Env 
OS - macOS sonoma (14.2.1)
Mode -Desktop
