### ISSUE TITLE
UI Issue: Column border of "Type" column is missing for "Dependencies" and "Dependents" tabs.

### ISSUE THREAD

**Issue by nikhil-mohite** [pgadmin-org/pgadmin4#7055]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

The "Type" column border is missing for Dependencies & Dependents tabs.

**To Reproduce**
1. Select any node from the tree with dependencies or dependents.
2. Check the "Type" column, bottom border is missing.

![image](https://github.com/pgadmin-org/pgadmin4/assets/69510038/5fb573de-44b6-46a8-a9cf-d53c36de9c60)
<img width="1438" alt="dependents" src="https://github.com/pgadmin-org/pgadmin4/assets/69510038/bbd80e16-8ee7-4667-9360-d55cd8b1b213">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-22/

Env 
OS - macOS sonoma (14.2.1)
Mode -Desktop
