### ISSUE TITLE
Stupid question about logging filter in container environment

### ISSUE THREAD

**Issue by Gruummy** [pgadmin-org/pgadmin4#7056]
Hi loved community,

i would have a stupid question about how logging works in case that pgadmin is running as container ... and the logs are send to standard-out.

How can i influence how the logging should be done / how i can filter requests which should NOT be send to stdout ?

For example .. in kubernetes periodically requests are send to the kubernetes healt endpoint i configured for it.
As a consequence i receive such log line on stdout.

```
::ffff:192.168.9.96 - - [13/Dec/2023:13:35:06 +0100] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.24+"
```

I am no developer ... and can currently not really understand what exactly writes this log
- gunicorn ?
- werkzeug ?

How i can influence / apply a filter, that for example requests to /misc/ping are simply not logged ?

I started to try it this way with gunicorn config ... but ... seams to be useless:

```
import gunicorn
gunicorn.SERVER_SOFTWARE = 'Python'

# Patch of gunicorn_config to exclude special things from logging
# This is only a tryout. More details you can see at "../00_patch_gunicorn_config.sh"
#
# silence the request path "/misc/ping" to not write it to log output
def pre_request(worker, req):
  if req.path == '/misc/ping':
    return
```

Help / really helpfull hints / comments really would be very helpfull for me.

**Comment by yogeshmahajan-1903** [comment]
@Gruummy 
Can you please share health check command? If you are using wget, then simply adding -q will stop logging.

**Comment by khushboovashi** [comment]
No response from the author, hence closing it.

**Comment by tlk** [comment]
@Gruummy It is possible to control the access log output location with the [`GUNICORN_ACCESS_LOGFILE`](https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#environment-variables) environment variable. This is not exactly a filter as you asked for, but I have found it helpful to be able to simply turn it off.

How to disable access log entirely:
```
GUNICORN_ACCESS_LOGFILE=/dev/null
```
