### ISSUE TITLE
Empty field "DB restriction"

### ISSUE THREAD

**Issue by vd0v1n** [pgadmin-org/pgadmin4#7059]
The field "DB restriction" section "Advanced" in the settings of all connections  reset after the updating to version 8.0

**Desktop (please complete the following information):**
 - OS: AlmaLinux
 - Version: 9.1
 - Mode: Server
 - Browser (if running in server mode): Chrome
 - Package type: RPM

**Comment by pravesh-sharma** [comment]
Issue resolved. Tested on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-02/

Env - 
OS - macOS 14.1.2
Mode - Desktop
