### ISSUE TITLE
Dbo schema is being shown as system catalog schema

### ISSUE THREAD

**Issue by DouglasOrtiz1972** [pgadmin-org/pgadmin4#7061]
Hi PgAdmin Team!

I'm facing an issue that `Dbo` schema is being shown under Catalog and not as regular schema.

Dbo is not a system catalog schema at all, but rather a regular schema. 

I activated the 'flag' `Show System Objects` and refreshed the tree.

Dbo schema appears as a Catalog schema. Please, fix it.

**To Reproduce**

At PgAdmin 4 tool, click in File, then Preferences.

You can see a new window. On left column, click in display. On the right side, below Lock Layout, you can see the option Show System Objects.

Please, enable it and click in Save.

The screen will close and you're back to PgAdmin main screen.

Please, refresh the Databases and click on Catalogs to expand that tree.

Thank you.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-02/
Package: arm64
Environment: macOs Ventura 13.5.1
