### ISSUE TITLE
Error dialog - all it says is 'amname'

### ISSUE THREAD

**Issue by JasonGloverNZ** [pgadmin-org/pgadmin4#7064]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Occasionally, when using the latest pgadmin (on Mac) I am getting an error dialog that just says `'amname'`.

<img width="603" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/2729838/4fa3d0fe-5094-4ebd-b9ba-03b57579cea7">

It appears sporadically.
Even after restarting the app it happens.
It happens across multiple different databases on different servers, which makes me think it is related to pgadmin and not the database or postgres itself.

**To Reproduce**

I don't know how to reproduce it.  It seems to happen randomly.
I click 'Ok' and the dialog goes away.
🤷‍♂️

**Expected behavior**

- Either there is a really problem, which I would like to understand and fix.
- Or just not have a useless error dialog.

**Desktop (please complete the following information):**

Version
8.1
Application Mode
Desktop
Current User
pgadmin4@pgadmin.org
NW.js Version
0.77.0
Browser
Chromium 114.0.5735.91
Operating System
macOS-14.1.1-x86_64-i386-64bit
pgAdmin Database File
/Users/jason/.pgadmin/pgadmin4.db
Log File
/Users/jason/.pgadmin/pgadmin4.log

**Comment by yogeshmahajan-1903** [comment]
@JasonGloverNZ 
Can you please share log file? Also you can specifically check if selecting particular table/index/view/constraints gives above error?

**Comment by adityatoshniwal** [comment]
@JasonGloverNZ  Please also share the PostgreSQL server version.

**Comment by JasonGloverNZ** [comment]
@adityatoshniwal , @yogeshmahajan-1903 

I found a way to reproduce the issue. If I select the DB and click "ERD for database" it will produce that error message.

`PostgreSQL 11.17 (Debian 11.17-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`

Log file:

[pgadmin4.log](https://github.com/pgadmin-org/pgadmin4/files/13706271/pgadmin4.log)

**Comment by pravesh-sharma** [comment]
Issue resolved. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-30/

Env-
OS - macOS 14.1.2
Mode - Desktop
