### ISSUE TITLE
Can't build files such as static/js/generated/vendor.sqleditor.js

### ISSUE THREAD

**Issue by kb3ien** [pgadmin-org/pgadmin4#7065]
# pulled pgAdmin v 8.1 from git
git clone https://github.com/pgadmin-org/pgadmin4.git

#followed directions in the README.md file:

cd pgadmin4
cd runtime
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

So what obvious step is being missed ?

**Comment by yogeshmahajan-1903** [comment]
@kb3ien 
For building web-assets commands  are below - 
```
cd $PGADMIN4_SRC\web
$PGADMIN4_SRC\web> yarn install
$PGADMIN4_SRC\web> yarn run bundle
```

**Comment by kb3ien** [comment]
I have no file 'install' there either. are you using a different yarn than in the deb repo ? I'm using 

yarnpkg                                          1.22.19+~cs24.27.18-2

and it seems to expect a file that matches the last ARG.  The README.md file suggests that this is the first step to installing. 

git clone https://github.com/pgadmin-org/pgadmin4.git
cd pgadmin4 
PGADMIN4_SRC=$(pwd)
cd web
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by kb3ien** [comment]
I have no file 'install' there either. are you using a different yarn than in the deb repo ? I'm using 

yarnpkg                                          1.22.19+~cs24.27.18-2

and it seems to expect a file that matches the last ARG.  The README.md file suggests that this is the first step to installing. 

git clone https://github.com/pgadmin-org/pgadmin4.git
cd pgadmin4 
PGADMIN4_SRC=$(pwd)
cd web
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by adityatoshniwal** [comment]
@kb3ien `install` is not a file, but a yarn command. Check if you're able to use yarn with `yarn --version` in the web directory.

**Comment by kb3ien** [comment]
I gather that, but I'm not familiar with yarn. 

which yarn
/usr/bin/yarn
yarn --version
0.32+git

**Comment by adityatoshniwal** [comment]
@kb3ien Your yarn version looks quite old. You need to update your global yarn to 1.x or 3.x

**Comment by kb3ien** [comment]
setting path to prefer the one from 

https://github.com/yarnpkg/berry

PATH=/usr/local/src/berry/scripts/bin/:$PATH 

did it.

**Comment by adityatoshniwal** [comment]
Great! Closing this.
