### ISSUE TITLE
UI issue: Pgagent schedule modification window doesn't open

### ISSUE THREAD

**Issue by dlasak** [pgadmin-org/pgadmin4#7070]
The pgagent job schedule modification window does not open.

**To Reproduce**

1) right click on pgagent schedule -> properties -> nothing happen

**Expected behavior**

Window with modification should open and allow to change the job schedule.

**Error message**

No error message, nothing happened.

**Desktop (please complete the following information):**
 - Os Windows 10 Enterprise, 21H2
 - Version: 8.1
 - Mode: Desktop
 - pgadmin: 8.1
 - pgagent 4.2.1

**Comment by dlasak** [comment]
I would be grateful if someone could take a look at https://github.com/pgadmin-org/pgagent/issues/33

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on today's snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-25/)

Env -
OS - macOS Sonoma (14.1.2)
Mode - Desktop

**Comment by dlasak** [comment]
Thank you for fixing it.
