### ISSUE TITLE
`/pgadmin4/servers.json` content does not show up in web interface 8.1

### ISSUE THREAD

**Issue by khteh** [pgadmin-org/pgadmin4#7074]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**
Why was https://github.com/pgadmin-org/pgadmin4/issues/6998 closed!?! It is still an issue! I have `servers.json` mounted in k8s statefulset and `pgadmin4` is NOT deployed with the mounted server configuration!

**Describe the bug**

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey] Ubuntu 23.10
 - Version: [e.g. 6.15] 8.1
 - Mode: [e.g Desktop or Server] Server
 - Browser (if running in server mode): [e.g. chrome, safari] Chrome
 - Package type: [e.g. RPM, DEB, Python, Container, etc.] Container

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
@khteh ,
Can you please share the docker-config? As mentioned in #6998 I am not able to reproduce the issue.

**Comment by paulmilbank** [comment]
@khteh Are you using a custom entrypoint for the docker container? Or possibly loading an old one somehow? 

I can see in my logs: `No such option: --load-servers` on a PGAdmin4 8.2 container using an older entrypoint. Looking at the current `master` branch, I can see the `--` has been removed from the options. I think this is a consequence of switching from argparse to typer. 
https://github.com/pgadmin-org/pgadmin4/commit/0d287df6ddc3021d692ae741fb8c8d78a059f213

Updating my entrypoint to sync with the current master branch entrypoint has fixed the loading for me.

**Comment by adityatoshniwal** [comment]
Yes, @paulmilbank is right. Please refer https://www.pgadmin.org/docs/pgadmin4/8.2/import_export_servers.html#importing-servers

**Comment by khteh** [comment]
Not custom entrypoint. There is no `load-servers` in my k8s manifest!

**Comment by adityatoshniwal** [comment]
@khteh did you follow the simple example here to verify - https://www.pgadmin.org/docs/pgadmin4/8.2/container_deployment.html#examples?

**Comment by sanhardik** [comment]
Doesnt seem to work for me
This is in my docker compose
```
db-rl:
    image: dpage/pgadmin4:latest
    entrypoint: >
      /bin/sh -c "
      echo '*:5432:postgres:postgres:pass' >> /var/lib/pgadmin/pgpass;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@rapidlink.com
      - PGADMIN_DEFAULT_PASSWORD=5W2dO3AKP9hM
    networks:
      rdcnet: {}
    secrets:
      - source: pgadmin_config_20240223_3
        target: /pgadmin4/config_local.py
      - source: pgadmin_servers_20240223_1
        target: /pgadmin4/servers.json
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 1
      update_config:
        parallelism: 1
        order: start-first
        delay: 10s
        failure_action: rollback
```

My config.py looks like this
```
AUTHENTICATION_SOURCES = ['oauth2']
OAUTH2_CONFIG = [
    {
        'OAUTH2_NAME': 'Google',
        'OAUTH2_DISPLAY_NAME': 'Google',
        'OAUTH2_CLIENT_ID': 'clientId',
        'OAUTH2_CLIENT_SECRET': 'clientSecret',
        'OAUTH2_TOKEN_URL': 'https://oauth2.googleapis.com/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/v2/auth',
        'OAUTH2_SERVER_METADATA_URL': 'https://accounts.google.com/.well-known/openid-configuration',
        'OAUTH2_API_BASE_URL': 'https://openidconnect.googleapis.com/v1/',
        'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
        'OAUTH2_SCOPE': 'openid email profile',
        'OAUTH2_ICON': 'fa-google',
        'OAUTH2_BUTTON_COLOR': '#3253a8',
    }
]
PGADMIN_CONFIG_CONSOLE_LOG_LEVEL = 10
MASTER_PASSWORD_REQUIRED= False
```


I can see the servers loading in the logs 
`| Added 0 Server Group(s) and 3 Server(s).`

But I dont see the servers in the UI

**Comment by sanhardik** [comment]
I have logged in using OAuth2. 
I would like all the users logged in through OAuth2 to see all servers. 

The "Shared" option worked.  
I had to provide the "SharedUsername" option as well. 

However now, its asking for password for the user "postgres". 
I am passing the `"PassFile": "/var/lib/pgadmin/pgpass"` in the servers.json. 
I have added the pgpass config in the `entrypoint` script in docker.

**Comment by yogeshmahajan-1903** [comment]
While connecting to the server in the server mode, pgpass file is looked up in 'var/lib/storage/<user>/', hence you are getting password not supplied error.
If you want to share pgpass file, then you can use shared storage feature. Please refer this [link](https://mktgsite.enterprisedb.com/blog/configuring-and-using-shared-storage-in-pgadmin-4) / [or this link](https://www.pgadmin.org/docs/pgadmin4/development/storage_manager.html#shared-storage).

**Comment by sanhardik** [comment]
I will try out the shared storage. 
I also tried 
```    
entrypoint: >
  /bin/sh -c "
  mkdir -p /var/lib/pgadmin/storage/admin_abc.com/;
  echo '*:*:*:postgres:pass' >> /var/lib/pgadmin/storage/admin_abc.com/.pgpass;
  echo '' >> /var/lib/pgadmin/storage/admin_abc.com/.pgpass;
  chown pgadmin:root /var/lib/pgadmin/storage/admin_abc.com/.pgpass;
  chmod 600 /var/lib/pgadmin/storage/admin_abc.com/.pgpass;
  /entrypoint.sh
      "
      ```
But that didnt work. 

For the shared storage, what should be the passfile

```SHARED_STORAGE = [{
    'name': Shared-Storage',
     'path': '/var/pgadmin4/shared',
     'restricted_access': True
}]
```

**Comment by yogeshmahajan-1903** [comment]
@sanhardik 
entrypoint stuff should work. What is error? Did you check hidden files in storage manager?
You can copy pgpass file in shared directory and then set password_file parameter in server dialogue/(via server.json) to the pgpass  file path.

**Comment by sanhardik** [comment]
With the entrypoint, I see `Error: connection failed: fe_sendauth: no password supplied` error

My servers.json file has 
```
      "PassFile": ".pgpass",
      "ConnectionParameters": {
         "passfile": ".pgpass"
      }
```

**Comment by adityatoshniwal** [comment]
I'm closing this issue as the original issues seem to be fixed.
@sanhardik You have configuration problems, you can send email to pgadmin-support@postgresql.org

**Comment by samratdgreat** [comment]
> With the entrypoint, I see `Error: connection failed: fe_sendauth: no password supplied` error
> 
> My servers.json file has
> 
> ```
>       "PassFile": ".pgpass",
>       "ConnectionParameters": {
>          "passfile": ".pgpass"
>       }
> ```

Were you able to resolve the issue?
