### ISSUE TITLE
OAuth integration should respect `preferred_username`

### ISSUE THREAD

**Issue by james-callahan** [pgadmin-org/pgadmin4#7075]
**Describe the solution you'd like**

When using oauth, if `preferred_username` is present in the JWT, use that for the username rather than defaulting to `email`

**Additional context**

From https://www.iana.org/assignments/jwt/jwt.xhtml

`preferred_username`: Shorthand name by which the End-User wishes to be referred to 	[[OpenID_Foundation_Artifact_Binding_Working_Group](https://www.iana.org/assignments/jwt/jwt.xhtml#OpenID_Foundation_Artifact_Binding_Working_Group)] 	[[OpenID Connect Core 1.0, Section 5.1](http://openid.net/specs/openid-connect-core-1_0.html)]

**Comment by yogeshmahajan-1903** [comment]
@james-callahan 

Can you please try using 'OAUTH2_USERNAME_CLAIM' parameter in oauth2 configuration.
Add the configuration below - 
```
'OAUTH2_USERNAME_CLAIM': 'preferred_username',
```

**Comment by james-callahan** [comment]
@yogeshmahajan-1903 yes it's entirely possible to set it manually; I was suggesting a change in the default.

**Comment by adityatoshniwal** [comment]
HI @james-callahan,

There are no standard rules for JWT which says `preferred_username` has more priority over `email`. Every JWT token provider can have its own keys. For that reason, we've provided a way to customise it as per your need.

**Comment by yogeshmahajan-1903** [comment]
As per above comment, closing the issue as this is already implemented.
