### ISSUE TITLE
Unable to cancel or terminate active queries from Dashboard

### ISSUE THREAD

**Issue by shadysudo** [pgadmin-org/pgadmin4#7078]
**Describe the bug**

When I click on the cancel button next to connection with an actively running query in the sessions section of the dashboard, I get the message "You are not allowed to cancel the main active session".  I get a similar message when clicking the terminate button for a connection with an active query.  If I am logged in as a super user, I get that same message when trying to cancel active queries from run by other users as well as my own.  Non super users get the message when trying to cancel their own active queries.

Clicking the terminate button on connections without active queries will close the connection as expected.

**To Reproduce**

1) Open a new query tool window in pgAdmin4
2) Execute "select pg_sleep(1000);"
3) Click on Dashboard
4) Check "Sessions" tab under "Server activity" section then look for the connection with the active query from the query tool.
5) Click on cancel button and cancel the active session
6) The message "You are not allowed to cancel the main active session" will pop up at the bottom of the screen
7) Click on the terminate button to terminate the connection
8) The message "You are not allowed to terminate the main active session" will pop up at the bottom of the screen

**Expected behavior**

The active query should be canceled and in the query tool you will see "ERROR:  canceling statement due to user request"

**Error message**

"You are not allowed to cancel the main active session"
"You are not allowed to terminate the main active session"

**Screenshots**
![image](https://github.com/pgadmin-org/pgadmin4/assets/66808114/29ba0065-136f-4072-92c4-23933de9550b)

**Desktop (please complete the following information):**
 - OS: Windows 10 Desktop and Linux (dpage/pgadmin4 docker container)
 - Version: pgAdmin version 8.1
 - Mode: Desktop and Server
 - Browser Chrome
 - Package type: windows installer and docker container

**Additional context**

The database that I am connecting to is PostgreSQL version 12.17
I have seen this behavior in pgAdmin4 for several versions.  I believe it used to work correctly in pgAdmin4 version 6.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-02/
Package: pip wheel, arm64
Environment: macOs ventura 13.5.1
