### ISSUE TITLE
Broken email/username autocomplete in browser (pgadmin4 8.0)

### ISSUE THREAD

**Issue by alex-pobeditel-2004** [pgadmin-org/pgadmin4#7082]
Recently I upgraded from 7.1 to 8.0 and email/username autocomplete on login screen stopped working in browser (Firefox). Browser offers autocomplete only for password now. Chrome proposes to enter email/username not in a standard way, but it does not fill password for it (separate click on password needed to trigger saved password proposal).

Here is the new input for email:
```
<input autocomplete="new-password" name="email" placeholder="Email Address / Username" rows="4" type="text" maxlength="255" data-testid="input-text" class="MuiInputBase-input MuiOutlinedInput-input" value="">

<!-- New password input: -->
<input autocomplete="new-password" name="password" placeholder="Password" rows="4" type="password" maxlength="255" data-testid="input-text" class="MuiInputBase-input MuiOutlinedInput-input" value="">
```
And here is the old username/email input (pre-8.0, I guess):
```
<input class="form-control" placeholder="Email Address / Username" name="email" type="text" autofocus="">
```

**To Reproduce**

1. Have remembered password for the site with pgadmin (for example, saved for pre-8.0 version)
2. Enter login screen
3. Click on Email / Username input
4. No saved password proposal (Firefox), or only username proposal without password autocomplete for it

**Expected behavior**

Browser proposes autocomplete for login pair

**Screenshots**
Username autocomplete (Chrome):  
![изображение](https://github.com/pgadmin-org/pgadmin4/assets/14791483/0481e753-3a0a-435c-85c8-78817df342b5)

Separate password autocomplete (Chrome)
![изображение](https://github.com/pgadmin-org/pgadmin4/assets/14791483/3dcffbeb-4ccb-4f8d-81d0-06d870ed7014)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: 8.0
 - Mode: Server
 - Browser (if running in server mode): Firefox
 - Package type: Docker container running via Compose

**Additional information**
Autocomplete type `new-password` seems suspicious for both email / password fields. Maybe I'm slightly nuts, but I think I forced autocomplete to work once when changed email input autocomplete type to `username` - but I failed to reproduce this one more time.

**Comment by pravesh-sharma** [comment]
Issue resolved. Tested on snapshot image for docker on firefox browser.

**Comment by alex-pobeditel-2004** [comment]
@pravesh-sharma thank you!
