### ISSUE TITLE
membership displayed incorrectly

### ISSUE THREAD

**Issue by joaocc** [pgadmin-org/pgadmin4#7085]
**Describe the bug**
Membership information of group is shown incorrectly (in global properties pane) showing `[WITH ADMIN]` on all members, even if only one member has that attribute

<img width="776" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/2837860/d33e1dfe-340c-4f3e-9ffd-d80a94413d46">

In the screenshot above, a group `kg__dba___wr` with two members where only one has `WITH ADMIN` shows both with that attribute (`kg__dba___adm [WITH ADMIN], ku__dba___wr [WITH ADMIN]`)

**Expected behavior**
Only the correct attribute should be shown (`kg__dba___adm [WITH ADMIN], ku__dba___wr` in the example above)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.6.3
 - Version: 8.1
 - Mode: Desktop

**Comment by nikhil-mohite** [comment]
Resolved, Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-17/
OS: macOS (Sonoma 14.1)
Mode: Desktop
