### ISSUE TITLE
Pgadmin throwing 308 permanent redirect when accessed through azure app gateway

### ISSUE THREAD

**Issue by jpnaidu07** [pgadmin-org/pgadmin4#7095]
I have a containerized PgAdmin server running inside azure app service, It has the custom domain **internal.host.com** and is running under server path **/dataAdmin**  which is configured to the azure app gateway as the backend pool.

The Azure app gateway host url is **app.host.com**.

When I hit **app.host.com/dataAdmin** it does the permanent redirect to the internal URL which is **internal.host.com/dataAdmin** which is not expected

Expected behavior it should be accessed via **app.host.com/dataAdmin**

Below is my docker file

```
FROM dpage/pgadmin4

COPY servers.json /pgadmin4/servers.json

ENV PGADMIN_DEFAULT_EMAIL=*********
ENV PGADMIN_DEFAULT_PASSWORD=********
ENV PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
ENV SCRIPT_NAME=/dataAdmin

EXPOSE 80

CMD ["/entrypoint.sh"]
```

**Comment by jpnaidu07** [comment]
Hi Team, Kindly provide any update on this

**Comment by yogeshmahajan-1903** [comment]
@jpnaidu07 
Have you enabled setting below in Azure app gateway? Then you will be redirected to application host. You need to adjust setting with Azure. pgAdmin does not have any role over here.

<img width="1520" alt="Screenshot 2024-01-23 at 5 33 43 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/5e74f7af-4e95-4ce8-904e-6e08e6040717">

**Comment by yogeshmahajan-1903** [comment]
@jpnaidu07 
I guess you have set 'Host name override' to yes.  you have mentioned about backend path not the host.
Can you please share screenshot for backend settings in Azure app gateway?

**Comment by jpnaidu07** [comment]
@yogeshmahajan-1903 

Below are the config Backend settings

![image](https://github.com/pgadmin-org/pgadmin4/assets/44135328/2bfb692b-90bc-4abe-b36d-a95f21b42e5c)

I have already mentioned bout the host in my query, i will reiterate again

App Gateway -> Host -> **app.host.com**

PgAdmin container Running inside the app service -> Host -> **internal.host.com**

We have configured the PgAdmin App service with the host name in the backend pools of the app gateway.

**Comment by jpnaidu07** [comment]
@yogeshmahajan-1903 Waiting for an update

**Comment by yogeshmahajan-1903** [comment]
@jpnaidu07 
What is backend protocol is used for backend setting/http setting? If it is http, then can you please check setting for HTTPS only in PgAdmin container App service > Configuration > HTTPS Only. Please turn of it if you are using http as backend protocol.
Also can you please share your backend setting?

**Comment by jpnaidu07** [comment]
@yogeshmahajan-1903 I dont see ur latest comment here but i can see via gmail notification, here is the full backend setting
![image](https://github.com/pgadmin-org/pgadmin4/assets/44135328/2d073420-418f-45db-940f-ccccfc1c9816)

And in app service it is set to HTTPS only to on

**Comment by yogeshmahajan-1903** [comment]
@jpnaidu07 
This is Azure App Gateway issue. You can find issue and solution [here](https://www.patrickob.com/2022/04/06/azure-front-door-afd-app-gateway-app-service-unexpected-issues/). Azure app gateway adds trailing slash causing this issue.

**Comment by yogeshmahajan-1903** [comment]
@jpnaidu07 
Here is the solution working for me. I am using front_end ip directly to access app gateway.
<img width="702" alt="Screenshot 2024-02-21 at 8 15 32 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/c921c1c5-7690-4e54-9fce-1a46553e7cc0">
<img width="638" alt="Screenshot 2024-02-21 at 8 15 43 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/5190136d-b621-4cb7-9da9-ab434dbad830">

**Comment by yogeshmahajan-1903** [comment]
@jpnaidu07 
Can you please try in private window and check? If still did not work, can we connect over the call? I am working in IST timezone. We can connect between  3-5 PM IST.

**Comment by adityatoshniwal** [comment]
No response from the author. Closing.
