### ISSUE TITLE
Schema Diff not generating difference for missing columns

### ISSUE THREAD

**Issue by Customerology** [pgadmin-org/pgadmin4#7104]
No SQL is generated in the DDL Comparision for instances where the difference between the Source and Target is a missing column in the Target.

Note: The opposite works correctly - If there is a column in the Target that is not present in the Source then a statement is correctly generated to remove the 'extra' column from the Target.

I am running pgAdmin 8.1 on Windows 11 desktop.

To simply testing I have done the following ...

On Source DB (postgres 14.1) I created the following table:

```
CREATE TABLE public.atable
(
    col1 integer,
    col2 integer
);
```

On Target DB (postgres 14.7), running on a different server, I created the following table:

```
CREATE TABLE public.atable
(
    col1 integer
);
```

When I run Schema Diff in pgAdmin 8.1 it appears to detect there is a difference but the difference box in the DDL comparison is blank. 

<img width="842" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/98335228/533003b8-f2a4-4255-b00d-9a4a9f9bf40a">

The owner is different but I am currently running the Compare with all 4 'ignore' options turned on. If I don't ignore owner, I correctly get the statement to alter the owner but still no statement to add the missing column. Most other kinds of differences are correctly generated but so far it seems that no SQL is generated for missing columns. I use this feature a lot and I believe it worked correctly in the past.

**Comment by anilsahoo20** [comment]
Tested and verified on candidate build: https://developer.pgadmin.org/builds/2024-01-08-1/
Package: pip wheel
Environment:macOs Ventura 13.5.1
