### ISSUE TITLE
Schema diff tool shows every object as existing in target only when source is Docker alpine image

### ISSUE THREAD

**Issue by Bilge** [pgadmin-org/pgadmin4#7108]
When source database is `postgres:13-alpine`, containing the exact same tables as a local target Windows installation, every object is shown as uniquely belonging to the target, as if the Docker source database were empty. The same happens when the target is AWS. Docker Alpine image seems to just not work with the schema diff tool for some reason.

pgAdmin 4 version 8.1

**Comment by yogeshmahajan-1903** [comment]
@Bilge 
Can you please share screenshot and couple of DDLs? PostgreSQL installation should not be issue. As database object definitions are same irrespective of PostgreSQL installation.

**Comment by Bilge** [comment]
Indeed, this is nothing to do with Docker. This is an issue where the Schema Diff tool goes completely haywire after first use. I'll create a new issue.
