### ISSUE TITLE
Getting error collation not supported while changing data type.

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#7113]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Getting error collation not supported while changing data type.

**To Reproduce**

1. Create a table with column having data type 'character varying'
2. Now try to edit data type to "Char" data type.
3. Click on save. Error is shown.
4. Issue is for both foreign tables and normal tables.

**Expected behavior**

Create correct the sql so that data type can be changed.
It should be alter column <column_name> type "char".
Also when issue is fixed add a test case in API tests for the same.

**Screenshots**

<img width="899" alt="Screenshot 2024-01-09 at 9 49 12 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/b276db40-5d51-4194-b398-1c86953ed14d">

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-31/
Environment: macOs ventura 13.5.1
Package: arm64
