### ISSUE TITLE
Backup and restore from postgres v11 to v13 fails: pg_restore: `pg_restore: error: unsupported version (1.15) in file header`

### ISSUE THREAD

**Issue by viceice** [pgadmin-org/pgadmin4#7114]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

I tried to backup a database on a postgre v11 server and restore it on a v13 server which failed on restore.
The backup was made with pg_dump v16 and then the restore was tried with pg_restore v13.

**To Reproduce**

1. backup a db froom postgres v11
2. restore the backup to a v13 postgre server
3. See the error

**Expected behavior**

the restore should work.

**Error message**

```
pg_restore: error: unsupported version (1.15) in file header
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey] Kubernetes (k3s)
 - Version: [e.g. 6.15] 8.1
 - Mode: [e.g Desktop or Server] Server
 - Browser (if running in server mode): [e.g. chrome, safari] chrome
 - Package type: [e.g. RPM, DEB, Python, Container, etc.] Container

**Additional context**

no

**Comment by viceice** [comment]
yes, it's from restore. I've migrated a different DB from PostgreSQL v15 to v13 with pgadmin successful. so it seems the pg_dump from v16 is no longer compatible with v13. 

I would like to have an option to choose the pg_dump version, so it's easier to restore on different versions.

**Comment by yogeshmahajan-1903** [comment]
@viceice 
You can configure desired binaries to be used for the particular postgres version in preferences as below - 
 
<img width="964" alt="Screenshot 2024-02-02 at 5 18 04 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/3325908d-7a87-471d-90e7-6c1d3f72f770">

**Comment by viceice** [comment]
ok, will try to remember next time 🙂

**Comment by GHkrishna** [comment]
Hello I had the same issue.

How did you resolve this @viceice 

I did add the path to binaries,
![Screenshot from 2024-08-20 13-59-01](https://github.com/user-attachments/assets/07e9eeb8-b426-4fd0-b3ba-b0b7872818aa)

However, I am still facing the same issue.

Here, I was trying to backup from v15 to v16

**Comment by viceice** [comment]
I used the console cli to do the export

**Comment by adityatoshniwal** [comment]
> Hello I had the same issue.
> 
> How did you resolve this @viceice
> 
> I did add the path to binaries, ![Screenshot from 2024-08-20 13-59-01](https://private-user-images.githubusercontent.com/74084119/359399567-07e9eeb8-b426-4fd0-b3ba-b0b7872818aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTQ0MTQsIm5iZiI6MTcyNDIxNDExNCwicGF0aCI6Ii83NDA4NDExOS8zNTkzOTk1NjctMDdlOWVlYjgtYjQyNi00ZmQwLWIzYmEtYjBiNzg3MjgxOGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA0MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ODY4Y2QyOTMyZDAwNTY5MDI5MjUwNTZiZDk2YTMxYTE1N2VmYmVhZWU3OGRkMjhkNTY1ZDZmMzM0ZjhmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t3cmTo_vGgyLtdcVxGbKG6IJFjrNIqLbIXSLoAsWgEg)
> 
> However, I am still facing the same issue.
> 
> Here, I was trying to backup from v15 to v16

It depends on what binary did you use to export and binary used to import along with what database supports.

**Comment by GHkrishna** [comment]
> It depends on what binary did you use to export and binary used to import along with what database supports.

I tried with pg_dump 14 as well as 16 and similarly with pg_restore 14 and 16

I also noticed that in ubuntu 22, I was unable to see the files while restoring using pgadmin 4. I tried with multiple formats directory, custom, tar, plain text. (Exported version was 15.1). I faced the above mentioned issue only while restoring using cli

Tried imports with multiple version 16, 15, 14

**Comment by adityatoshniwal** [comment]
> > It depends on what binary did you use to export and binary used to import along with what database supports.
> 
> I tried with pg_dump 14 as well as 16 and similarly with pg_restore 14 and 16
> 
> I also noticed that in ubuntu 22, I was unable to see the files while restoring using pgadmin 4. I tried with multiple formats directory, custom, tar, plain text. (Exported version was 15.1). I faced the above mentioned issue of unsupported verion only while restoring using cli
> 
> Tried imports with multiple version 16, 15, 14

What is the version of PG and pg_backup binary when taking the backup?

**Comment by GHkrishna** [comment]
The version for PG and pg_backup is 15.1 when taking the backup.

Actually I am taking a backup from server and trying to restore it on my local machine(using pgadmin)

From the server that I am taking backup from, PG version is 15.1

**Comment by adityatoshniwal** [comment]
> The version for PG and pg_backup is 15.1 when taking the backup.
> 
> Actually I am taking a backup from server and trying to restore it on my local machine(using pgadmin)
> 
> From the server that I am taking backup from, PG version is 15.1

You need to restore it to PG version 15.1 or above. You can use pg_restore version 15.1 or above.
