### ISSUE TITLE
Query Format

### ISSUE THREAD

**Issue by JuanLuisNL** [pgadmin-org/pgadmin4#7115]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

---- If we write a statement like this:

SELECT pais, apr_idioma FROM estadisticas WHERE COALESCE(apr_idioma,'') = '' ORDER BY pais

---- When pressing Ctrl+Shift+k

SELECT PAIS,
	APR_IDIOMA
FROM ESTADISTICAS
WHERE COALESCE(APR_IDIOMA,

							'') = ''
ORDER BY PAIS 

**To Reproduce**

Press Ctrl+Shift+k

**Expected behavior**

SELECT PAIS,
	APR_IDIOMA
FROM ESTADISTICAS
WHERE COALESCE(APR_IDIOMA,'') = ''
ORDER BY PAIS

**Desktop (please complete the following information):**
 -  WIdonws
 - Version: all

**Comment by nikhil-mohite** [comment]
Duplicate of #5083
