### ISSUE TITLE
pgAdmin CLI pending bugs

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#7116]
Couple of issues:

1. If I run the command `python setup.py set-prefs aditya.toshniwal14@gmail.com "browser:processes:process_retain_days=true"` then it is success. Here, process retain days is a number.

2. Login with an internal user for some email and run the below cmd. Then go to UI and open the preferences dialog. App crashes. I think we should logout the user if it is inactive.
`python setup.py update-user [aditya.toshniwal14@gmail.com](mailto:aditya.toshniwal14@gmail.com) --nonadmin --inactive --json --no-console`

**Comment by yogeshmahajan-1903** [comment]
Some more issues - 
1.Tool tip for query tool shows query tool:logical_operator_new_line. Expected is - sqleditor:editor:logical_operator_new_line  in preferences dialogue.
2.Tools tips are missing for drop downs in preferences dialogue.
3.If user provides boolean value 'false',  preference setting is NOT updated.(Fixed with #6058)

**Comment by pravesh-sharma** [comment]
1. I tried adding a user using CLI on Rocky 9, but it gives the below error. However, it works with the pip wheel package (macOS).

<img width="1216" alt="Screenshot 2024-02-28 at 2 37 19 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/badd5551-10f7-4740-b3db-665881c3ed98">


2. When trying `pgadmin4-cli ` on the pip wheel package it is not working.

<img width="1128" alt="Screenshot 2024-02-28 at 3 01 44 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/d12e5639-d8c6-49fd-8bb1-2887f989dc5e">

**Comment by adityatoshniwal** [comment]
> Some more issues - 1.Tool tip for query tool shows query tool:logical_operator_new_line. Expected is - sqleditor:editor:logical_operator_new_line in preferences dialogue. 2.Tools tips are missing for drop downs in preferences dialogue. 3.If user provides boolean value 'false', preference setting is NOT updated.(Fixed with #6058) 4.CLI tool does not work in Desktop as default SQLITE_PATH taken is /var/lib/pgadmin/pgadmin4.db. Also no option to provide sqlite path value.

I suggest we should have tooltips on labels and not input controls. Having a tooltip on input is not a good UX.

**Comment by pravesh-sharma** [comment]
Reopening for testing

**Comment by khushboovashi** [comment]
Closing the issue.

I have created new issue for #7346 for the pending Preference validation issue.
