### ISSUE TITLE
pgAdmin 8.1 - DB restriction - doesn't remember the database list

### ISSUE THREAD

**Issue by przemyslaw-szustak** [pgadmin-org/pgadmin4#7118]
DB restriction in Advanced tab in server properties doesn't remember last typed and doesn't preview actual typed database. 
When I like to edit DB restriction list for server it always is empty field.

1. Go to Object tree.
2. Find server and right click on it.
3. Click "Properties...".
4. Open "Advanced" tab.
5. Type DB_NAME in "DB restriction" field and click on dropdown list "Create DB_NAME".
6. Field is empty (in pgAdmin this DB_NAME was added into field styled like button).

**Expected behavior**
Field "DB restriction" should contain actual db names that was typed.

**Screenshots**
![image](https://github.com/pgadmin-org/pgadmin4/assets/17796828/820d48b0-0fbb-4590-855b-a0f3f7fbfa9b)

**Desktop (please complete the following information):**
 - OS: Windows 10, Ubuntu 22.04.3 LTS
 - Mode: Desktop

**Comment by adityatoshniwal** [comment]
Hi @przemyslaw-szustak,
The issue is fixed and will be available in v8.2 planned to release tomorrow.
Thanks.

**Comment by adityatoshniwal** [comment]
You can also try the candidate build here - https://developer.pgadmin.org/builds/2024-01-08-1/
