### ISSUE TITLE
Can't install pgadmin4 on Ubuntu jammy

### ISSUE THREAD

**Issue by vmvelev** [pgadmin-org/pgadmin4#7123]
**Describe the bug**

Following the installation guide here - https://www.pgadmin.org/download/pgadmin-4-apt/, I am not able to install pgadmin4.

**To Reproduce**

1. Execute `curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg`
2. Execute `sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'`

**Expected behavior**

pgAdmin should be installed

**Error message**

```E: Failed to fetch https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/jammy/dists/pgadmin4/main/binary-all/Packages.gz  File has unexpected size (5384 != 5010). Mirror sync in progress? [IP: 147.75.85.69 443]
   Hashes of expected file:
    - Filesize:5010 [weak]
    - SHA512:babb1cb3fdafd21a7b08918f5f1f3be30c31b546ba84cf0693e774f69df44b5ba5ed4f45e49fc3e606936a98b95ba611c1ab2da9faeb8c2fecdf5f1666e8589d
    - SHA256:e866012e2398715251392d5125feb20860a1db61bd198649fa383b92c8416d89
    - SHA1:cd2ec66ab92eda14bc6f6e5f6232a49a5f52db6a [weak]
    - MD5Sum:5548e8405807cd862b73247e03affb81 [weak]
   Release file created at: Thu, 14 Dec 2023 11:42:24 +0000
E: Failed to fetch https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/jammy/dists/pgadmin4/main/binary-amd64/Packages.gz  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04.3 LTS
 - Mode: Desktop
 - Package type: DEB

**Additional context**

It looks like the file Packages.gz was updated today, and the size is 5384 while the installation expects 5010.

**Comment by nikhil-mohite** [comment]
Hi @vmvelev,

Can you please re-try once? There was some network issue which seems to be resolved now.

**Comment by vmvelev** [comment]
Hey @nikhil-mohite, everything is good! Thanks for fixing it :+1:
