### ISSUE TITLE
[desktop] Doesn't launch in windows 11

### ISSUE THREAD

**Issue by slushpuppy** [pgadmin-org/pgadmin4#7125]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Hi, I am unable to start pgadmin unless i delete C:\Users\<username>\AppData\Roaming\pgadmin folder

**To Reproduce**

1. install pgadmin
2. start pgadmin/fill in server details
3. reboot the comp
4. pgadmin fails to start. no loading splash screen or anything. nwjs is running in task manager tho

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version: [e.g. 6.15]
 - Mode: desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: Python 3.12.1

**Additional context**

**Comment by adityatoshniwal** [comment]
Hi @slushpuppy,
Can you please share the screenshot of error and logs please?

**Comment by slushpuppy** [comment]
Hi @adityatoshniwal i checked C:\Users<username>\AppData\Roaming\pgadmin folder but logs are not being logged there, is there a way I can run it in verbose mode in cli?

**Comment by nikhil-mohite** [comment]
Hi @slushpuppy ,

Can you please try killing the process from the task manager and please share the screen recording if possible?

**Comment by MrBns** [comment]
Hi, this issue is closed. But still  I am facing this problem..
