### ISSUE TITLE
Token Expired with Oauth to Gitlab-CE

### ISSUE THREAD

**Issue by silversky54** [pgadmin-org/pgadmin4#7126]
Hi, I've been using pgadmin4 docker container and Gitlab as Oauth authenticator for a while and recently migrated from Pgadmin:6.15 to 8.1 after migrating I can no longer authenticate with OAuth, the process fails with the error The Token is expired. 

**Describe the bug**
When trying to log in with Oauth through Gitlab-ce it fails with the following message.
{"success":0,"errormsg":"expired_token: The token is expired","info":"","result":null,"data":null}

The issue happens after the Gitlab instance replies to the authentication request and redirects to Pgadmin.

If I revert back to 6.15 the issue disappears. I've tried multiple versions and it starts failing with version 6.18 onwards. 

**To Reproduce**
During Log-in I provide user/password and click on log-in with Gitlab. 
The system redirects to the private Gitlab instance for authentication. I submit the user/password in Gtilab again. IT authenticates in Gtilab without error but when doing the callback to pgadmin it fails with the above error. 

**Expected behavior**
After login with Gtilab it should go to the home page as per usual. 

**pgadmin configuration**
I am using the official pgadmin docker image dpage/pgadmin4:8.1 with the following container config in a compose file. The service is running behind Traefik as reverse proxy, I've had no issues with this in the past and works well if I login locally (not Oauth) with the admin password.

 environment:
      PGADMIN_DEFAULT_EMAIL:  support@email
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/secret_pwd
      SCRIPT_NAME: "/pgadmin"
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 0  #temp for debugging
      PGADMIN_CONFIG_AUTHENTICATION_SOURCES: "['oauth2','internal']"
      PGADMIN_AUTO_CREATE_USER: "True"
      PGADMIN_CONFIG_OAUTH2_CONFIG: "[{
          'OAUTH2_NAME': 'gitlab',
          'OAUTH2_DISPLAY_NAME': 'Gitlab',
          'OAUTH2_CLIENT_ID': 'client_id_from_gitlab',
          'OAUTH2_CLIENT_SECRET': 'secret_from_gitlab',
          'OAUTH2_TOKEN_URL': 'https://gitlab_domain/oauth/token',
          'OAUTH2_AUTHORIZATION_URL': 'https://gitlab_domain/oauth/authorize',
          'OAUTH2_SERVER_METADATA_URL': 'https://gitlab_domain/.well-known/openid-configuration',
          'OAUTH2_API_BASE_URL': 'https://gitlab_domain/oauth/',
          'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
          'OAUTH2_SCOPE': 'openid email profile',
          'OAUTH2_ICON': 'fa-gitlab',
          'OAUTH2_BUTTON_COLOR': '#E24329'
        }]"

I've also tried upgrading Gitlab, all versions seems to give the same result. Current Gitlab version is v16.7.0

**Comment by pravesh-sharma** [comment]
Hi @silversky54,

I am not able to reproduce the issue. Can you please share the GitLab oAuth application setting for reference?

**Comment by adityatoshniwal** [comment]
No response from the author. Closing.

**Comment by silversky54** [comment]
Hi, I was away for personal reasons and was unable to respond on time. How an I re-open this case?

**Comment by silversky54** [comment]
> Hi @silversky54,
> 
> I am not able to reproduce the issue. Can you please share the GitLab oAuth application setting for reference?

This is the current config which is still giving the same error. 
      PGADMIN_CONFIG_AUTHENTICATION_SOURCES: "['oauth2','internal']"
      PGADMIN_AUTO_CREATE_USER: "True"
      PGADMIN_CONFIG_OAUTH2_CONFIG: "[{
          'OAUTH2_NAME': 'gitlab',
          'OAUTH2_DISPLAY_NAME': 'Gitlab',
          'OAUTH2_CLIENT_ID': [Removed for privacy]
          'OAUTH2_CLIENT_SECRET': [Removed for privacy],
          'OAUTH2_TOKEN_URL': 'https://privategitlab.com/oauth/token',
          'OAUTH2_AUTHORIZATION_URL': 'https://privategitlab.com/oauth/authorize',
          'OAUTH2_SERVER_METADATA_URL': 'https://privategitlab.com/.well-known/openid-configuration',
          'OAUTH2_API_BASE_URL': 'https://privategitlab.com/oauth/',
          'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
          'OAUTH2_SCOPE': 'openid email profile',
          'OAUTH2_ICON': 'fa-gitlab',
          'OAUTH2_BUTTON_COLOR': '#E24329'
        }]"

**Comment by akshay-joshi** [comment]
@silversky54 

Can you please share the GitLab OAuth application setting from the OAuth2 provider?

**Comment by silversky54** [comment]
@akshay-joshi 
I'm not 100% sure what you are asking for so I'll take a shot. In my previous message I shared the OAuth2 settings I added to the PGAdmin Docker container as environment variables. These were working fine until the change of PGadmin version. 
As for Gitlab, the settings are done by adding a global application OAuth instance (https://privateGitlab.com/admin/applications) with the following settings 
name: Pgadmin
redirect URL: https://privatePGadmin.com/oauth2/authorize
Trusted: Checked / True
Confidential: Checked /True
Scopes: read_api, read_user, openid, profile, email. 

One additional note, I've now upgraded to gitlab version 16.11.1-ce.0 and PGAdmin4 version 8.5

**Comment by adityatoshniwal** [comment]
@pravesh-sharma Can you please test once?

**Comment by pravesh-sharma** [comment]
Hi @silversky54,

I tried with the same config details you provided on a self-hosted GitLab and could not reproduce the issue. Below are my config details:

GitLab version - 16.11.2
pgAdmin version - 8.5

OAuth config:
``` 'OAUTH2_NAME': 'gitlab',
    'OAUTH2_DISPLAY_NAME': 'Gitlab',
    'OAUTH2_CLIENT_ID': '<client_id>',
    'OAUTH2_CLIENT_SECRET': '<client_secret>',
    'OAUTH2_TOKEN_URL': 'https://gitlab.example.com/oauth/token',
    'OAUTH2_AUTHORIZATION_URL': 'https://gitlab.example.com/oauth/authorize',
    'OAUTH2_SERVER_METADATA_URL': 'https://gitlab.example.com/.well-known/openid-configuration',
    'OAUTH2_API_BASE_URL': 'https://gitlab.example.com/oauth/',
    'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
    'OAUTH2_SCOPE': 'openid email profile',
    'OAUTH2_ICON': 'fa-gitlab',
    'OAUTH2_BUTTON_COLOR': '#E24329',` ``

GitLab app config:
```Confidential: True
   Scopes: read_api, read_user, openid, profile, email.```

I could not find one parameter `Trusted: Checked / True` on GitLab can you please let me know where I can find it?

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing issue.
