### ISSUE TITLE
Why cannot front-end resources be accessed in the browser after startup?

### ISSUE THREAD

**Issue by yyhack110** [pgadmin-org/pgadmin4#7128]
![image](https://github.com/pgadmin-org/pgadmin4/assets/36223779/c93bf4d8-a4e0-4c2c-8cf8-b96fcc9ce343)
![image](https://github.com/pgadmin-org/pgadmin4/assets/36223779/394af6e2-4cc5-4b6e-b342-0d2b51132f4e)

**Comment by adityatoshniwal** [comment]
Hi @yyhack110,
Did you follow the steps mentioned in the README.md for setting up the dev env?

**Comment by adityatoshniwal** [comment]
You can also checkout the article here - https://www.enterprisedb.com/blog/setup-pgadmin-dev-env.

**Comment by yyhack110** [comment]
@adityatoshniwal  
Thank you, my friend. According to your instructions, I successfully ran it, but if I want to develop and debug locally, should I use server mode or desktop mode? I see the DATA in the steps_ Where should the DIR be established? It keeps reminding me that I can't find the directory

**Comment by yyhack110** [comment]
![image](https://github.com/pgadmin-org/pgadmin4/assets/36223779/3dd7e3b2-3ef2-4f7f-b4e0-41dfb824d873)
![image](https://github.com/pgadmin-org/pgadmin4/assets/36223779/e60c1e31-2a6b-48c5-b10d-4fde8b05b15a)

**Comment by yyhack110** [comment]
I have another question, why do I need to use email login after default startup? Where should I get this email account password? And when I check the configuration, I also need to configure emails. Is it necessary for me to only develop and test locally?

**Comment by yyhack110** [comment]
I have successfully started according to README.md, but now I want to debug the method of generating scripts. How should I proceed?
This is the method I want to debug:
![image](https://github.com/pgadmin-org/pgadmin4/assets/36223779/63397694-35df-43ed-9c11-07a4cedd83f9)
I only found one file like this, is that it?
![image](https://github.com/pgadmin-org/pgadmin4/assets/36223779/36960c2a-b8c1-4d2f-91a1-cec06c1376bf)

**Comment by adityatoshniwal** [comment]
@yyhack110 the URL says table so definitely in the table module. What you're seeing is a "TestCase", looking at the name.
You need to first understand the how code works and then debug.
This is not a bug. You can send mail mail to pgadmin-hackers@postgresql.org for any such queries.
