### ISSUE TITLE
Json log format

### ISSUE THREAD

**Issue by tingeltangelthomas** [pgadmin-org/pgadmin4#7138]
**Describe the solution you'd like**

We are running pgadmin on a cloud environment and our security department forces us to log every query executed via pgadmin.
All our container logs are written to stdout/stderr and fluentbit streams it to Elasticsearch.
At the moment the SQL log output of pgadmin is plain text and contains line breaks. This means in Elasticsearch every line of the log message will be a new entry. 
To solve this issue it would be great implement a setting to log every log message in json format.

This could be achieved by an additional logformatter, e.g. https://github.com/Colin-b/logging_json or https://github.com/MyColorfulDays/jsonformatter

**Additional context**

Example of a current log message:
```
2024-01-18 12:49:44,494: SQL	pgadmin:	Execute (scalar) by me@company.de on databasename@postgresql/postgres #73 - DB:postgres (Query-id: 3845816):

SELECT
    has_table_privilege(
      'pgagent.pga_job', 'INSERT, SELECT, UPDATE'
    ) has_priviledge
WHERE EXISTS(
    SELECT has_schema_privilege('pgagent', 'USAGE')
    WHERE EXISTS(
        SELECT cl.oid FROM pg_catalog.pg_class cl
        LEFT JOIN pg_catalog.pg_namespace ns ON ns.oid=relnamespace
        WHERE relname='pga_job' AND nspname='pgagent'
    )
)
```

As json it would be in one line and look like:
```
{"time": "2024-01-18 14:32:42,517", "message": "Execute (scalar) by me@company.de on databasename@postgresql/postgres #73 - DB:postgres (Query-id: 3845816):\n\nSELECT\n    has_table_privilege(\n      'pgagent.pga_job', 'INSERT, SELECT, UPDATE'\n    ) has_priviledge\nWHERE EXISTS(\n    SELECT has_schema_privilege('pgagent', 'USAGE')\n    WHERE EXISTS(\n        SELECT cl.oid FROM pg_catalog.pg_class cl\n        LEFT JOIN pg_catalog.pg_namespace ns ON ns.oid=relnamespace\n        WHERE relname='pga_job' AND nspname='pgagent'\n    )\n)"}
```

Regards
Thomas

**Comment by florian-sabonchi** [comment]
can i work on it?

**Comment by tingeltangelthomas** [comment]
thank you @florian-sabonchi for implementing it!!! Greetings to franconia!

**Comment by florian-sabonchi** [comment]
> thank you @florian-sabonchi for implementing it!!! Greetings to franconia!

No Problem! I am also from franconia

**Comment by adityatoshniwal** [comment]
reopening for testing.

**Comment by pravesh-sharma** [comment]
Verified on snapshot image of docker as well as on server mode in Rocky 9 for both console logs and file logs.
