### ISSUE TITLE
Enabling tunneling passwords to be saved stopped working

### ISSUE THREAD

**Issue by tom-giesberg** [pgadmin-org/pgadmin4#7139]
Sometime between v6.2 and v8.0, enabling SSH tunneling passwords to be saved on a Mac stopped working

**To Reproduce:**
1. Create /Library/Preferences/pgadmin/config_system.py with the following contents:
   ALLOW_SAVE_TUNNEL_PASSWORD = True
2. Launch pgAdmin 4
3. Create a server connection that uses SSH Tunnel with password authentication
4. Choose server connection and right click > Connect Server
5. The Connect to Server dialog box pops open but note that the Save Password check box is disabled

**Expected behavior:**
I expect the the Save Password check box to be enabled

**Desktop:**
 - OS: macOS 
 - Processor: Intel x86 64-bit
 - Version: 14.2.1 Sonoma
 - Mode: Desktop

**Additional context**
1. The behavior described above for the Connect to Server dialog box is consistent in other dialog boxes and context menus
2. Works in v6.2 does not work in v8.0 or v8.2
3. Tried setting the ALLOW_SAVE_TUNNEL_PASSWORD = True in config.py and config_local.py
4. Confirmed that the config_system.py was being read by intentionally misspelling True which caused an error at startup time

**Comment by adityatoshniwal** [comment]
I am able to reproduce this.

**Comment by akamch** [comment]
The bug is absent in v7.8.

**Comment by pravesh-sharma** [comment]
Found below issue:

Not able to clear the saved SSH tunnel password. Option is not enabled in object menu.

<img width="668" alt="Screenshot 2024-04-01 at 11 15 11 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/e0e05368-28d0-470b-8aed-a9f4e5cdb857">

**Comment by pravesh-sharma** [comment]
Issue resolved. Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-04-01/).

**Comment by nabe1653** [comment]
Hi there.

I feel this is not fixed completly yet on pgadmin v4.8.6 docker image at least.
I updated image and tried to put empty pass but server requests the pass when connect again.
I just wished ignorering asking for no-pass ssh key...


version and config: 
![image](https://github.com/pgadmin-org/pgadmin4/assets/48498820/da6f14da-a06a-4fc8-9cf6-cf44d4aada2f)
