### ISSUE TITLE
Enabling Outh2 on Pgadmin giving me error  

### ISSUE THREAD

**Issue by farakh-shahid** [pgadmin-org/pgadmin4#7144]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Enable outh2 on Pgadmin latest version 8.2 getting error. 
{"success":0,"errormsg":"Missing \"jwks_uri\" in metadata","info":"","result":null,"data":null}

Below is my Setting.
```
OAUTH2_CONFIG = [
    {
        'OAUTH2_NAME': 'Google',
        'OAUTH2_DISPLAY_NAME': 'Google',
        'OAUTH2_CLIENT_ID': 'my-client-id',
        'OAUTH2_CLIENT_SECRET': 'client-secret',
        'OAUTH2_TOKEN_URL': 'https://accounts.google.com/o/oauth2/token',
        'OAUTH2_API_BASE_URL': 'https://openidconnect.googleapis.com/v1/',
        'OAUTH2_AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/auth',
        'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
        'OAUTH2_SCOPE': 'openid email profile',
        'OAUTH2_USERNAME_CLAIM': None,
        'OAUTH2_ICON': 'fa-google',
        'OAUTH2_BUTTON_COLOR': '#3253a8',
        # 'OAUTH2_ADDITIONAL_CLAIMS': {
        #     'https://gitlab.org/claims/groups/maintainer': [
        #           'kuberheads/applications',
        #           'kuberheads/dba',
        #           'kuberheads/support'
        #      ],
        #     'https://gitlab.org/claims/groups/developer': [
        #           'kuberheads/applications/team01'
        #      ],
        # }
        # Example for AzureAD:
        # 'OAUTH2_ADDITIONAL_CLAIMS': {
        #     'groups': ["0760b6cf-170e-4a14-91b3-4b78e0739963"],
        #     'wids': ["cf1c38e5-3621-4004-a7cb-879624dced7c"],
        # }
        # 'OAUTH2_ADDITIONAL_CLAIMS': None,
        # Set this variable to False to disable SSL certificate verification
        # for OAuth2 provider.
        # This may need to set False, in case of self-signed certificates.
        # Ref: https://github.com/psf/requests/issues/6071
        # 'OAUTH2_SSL_CERT_VERIFICATION': True
    }
]
```

**To Reproduce**

Got to Config.py add Outh2 credentials.
Run application and Click on Login with Google button.
It will show this error message:

{"success":0,"errormsg":"Missing \"jwks_uri\" in metadata","info":"","result":null,"data":null}

**Expected behavior**

It should redirect Us to Pgadmin dasboard after login from google.

**Error message**

{"success":0,"errormsg":"Missing \"jwks_uri\" in metadata","info":"","result":null,"data":null}

**Screenshots**

<img width="1680" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/45315010/fd44188a-8288-41a0-b2e0-a434978fbf35">

**Desktop (please complete the following information):**
 - OS: [ macOSX  Son0ma]
 - Version: [14.1.2]
 - Mode: [Server]
 - Browser (chrome)
 

**Additional context**

**Comment by farakh-shahid** [comment]
Anyone who can help me in this?

**Comment by khushboovashi** [comment]
Hi @farakh-shahid, set OAUTH2_SERVER_METADATA_URL and try.

**Comment by farakh-shahid** [comment]
@khushboovashi Sorry to be specific here what will be metadata URL for Google?

**Comment by farakh-shahid** [comment]
I have set
     `  'OAUTH2_SERVER_METADATA_URL': 'https://accounts.google.com/.well-known/openid-configuration',`
     
     but still getting same error
     
     {"success":0,"errormsg":"invalid_claim: Invalid claim \"iss\"","info":"","result":null,"data":null}

**Comment by khushboovashi** [comment]
Refer https://stackoverflow.com/questions/71878134/runtimeerror-missing-jwks-uri-in-metadata-for-flask-and-google-authlib

**Comment by pravesh-sharma** [comment]
No response from the author hence closing.
