### ISSUE TITLE
Fatal Error: "The pgAdmin 4 server could not be contacted"

### ISSUE THREAD

**Issue by DaniiC00kie** [pgadmin-org/pgadmin4#7153]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Used pgadmin v8.0 for about 2 months, now it seems to have problems at starting up. (The Interface won't open, it stopps with an exception)

**To Reproduce**

// not quite sure where this bugs comes from
1. Open pgadmin (version 8.0 and up) 

**Expected behavior**

The User Interface should open (please see screenshots where it's stuck=

**Error message**

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\Danii\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\config.py"
Webapp Path: "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\python\python.exe -s C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\Danii\AppData\Roaming
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_10044_UOQMGEZCHGPJVKTJ
  - CHROME_RESTART: NW.js|NW.js ist abgestürzt. Jetzt neu starten?|LEFT_TO_RIGHT
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: DESKTOP-M7CJU4S
  - ComSpec: C:\Windows\system32\cmd.exe
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - EFC_2784: 0
  - FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
  - FPS_BROWSER_USER_PROFILE_STRING: Default
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\Danii
  - JAVA_HOME: C:\Program Files\Eclipse Adoptium\jdk-8.0.392.8-hotspot\
  - LOCALAPPDATA: C:\Users\Danii\AppData\Local
  - LOGONSERVER: \\DESKTOP-M7CJU4S
  - NUMBER_OF_PROCESSORS: 16
  - OneDrive: C:\Users\Danii\OneDrive
  - OneDriveConsumer: C:\Users\Danii\OneDrive
  - OS: Windows_NT
  - path: C:\Program Files\Eclipse Adoptium\jdk-8.0.392.8-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.9.9-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\Danii\AppData\Local\Microsoft\WindowsApps;C:\Windows\AtlasModules;C:\Windows\AtlasModules\Apps;C:\Windows\AtlasModules\Other;C:\Windows\AtlasModules\Tools;C:\Windows\AtlasModules\Scripts;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\Windows\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Kubernetes\Minikube;C:\Users\Danii\AppData\Local\Microsoft\WindowsApps;;C:\Users\Danii\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Danii\.dotnet\tools
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PGADMIN_INT_KEY: 370e28b0-7849-41bc-893c-e50603ac4359
  - PGADMIN_INT_PORT: 59342
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
  - PROCESSOR_LEVEL: 23
  - PROCESSOR_REVISION: 0802
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Windows\AtlasModules\Scripts\Modules
  - PUBLIC: C:\Users\Public
  - SESSIONNAME: Console
  - SystemDrive: C:
  - SystemRoot: C:\Windows
  - TEMP: C:\Users\Danii\AppData\Local\Temp
  - TMP: C:\Users\Danii\AppData\Local\Temp
  - USERDOMAIN: DESKTOP-M7CJU4S
  - USERDOMAIN_ROAMINGPROFILE: DESKTOP-M7CJU4S
  - USERNAME: Danii
  - USERPROFILE: C:\Users\Danii
  - VBOX_MSI_INSTALL_PATH: C:\Program Files\Oracle\VirtualBox\
  - windir: C:\Windows
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.018 Sec
Traceback (most recent call last):
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgAdmin4.py", line 104, in <module>

    app = create_app()
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgadmin\__init__.py", line 534, in create_app

    driver.init_app(app)
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgadmin\utils\driver\__init__.py", line 27, in init_app

    DriverRegistry.load_modules(app)
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgadmin\utils\driver\registry.py", line 20, in load_modules

    from . import psycopg3 as module
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgadmin\utils\driver\psycopg3\__init__.py", line 21, in <module>

    import psycopg
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\python\lib\site-packages\psycopg\__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\python\lib\site-packages\psycopg\pq\__init__.py", line 114, in <module>

    import_from_libpq()
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\python\lib\site-packages\psycopg\pq\__init__.py", line 106, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: DLL load failed while importing pq: Das angegebene Modul wurde nicht gefunden.
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: Could not find module 'libpq.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/109168862/1105444c-a211-4361-902d-38c812dfa403)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 23H2 Build 22631.2428
 - Mode: Desktop
 - Browser: none
 - Package type: EXE, to be precise: pgadmin4-8.2-x64.exe

**Additional context**
 tried the following steps:
- Installed newer version of pgAdmin (v8.0, v8.1, v8.2)
- I wiped the whole data directories of pgadmin for a clean install
- I tried installing both ways: "Only of me", and "For all users"
- I tried: Running in user mode, and "run as administrator" as well 

Now im not quite sure what the Problem could be.

**Comment by DaniiC00kie** [comment]
Another issue with the same Problem, but no error logs: https://github.com/pgadmin-org/pgadmin4/issues/7125

(seen it to late, sorry)

**Comment by khushboovashi** [comment]
Hi @DaniiC00kie, Please check if the libpq.dll is in any sub-folder of C:\Users\Danii\AppData\Roaming\pgadmin.
If yes, could you provide the exact location?

**Comment by DaniiC00kie** [comment]
Hi @khushboovashi thanks for the reply.

As it seems, this dll does not exist.

![image](https://github.com/pgadmin-org/pgadmin4/assets/109168862/831d3c74-52d4-4c24-b2f5-cd02d4bcce5b)
![image](https://github.com/pgadmin-org/pgadmin4/assets/109168862/caf06acf-9026-4052-aa7c-f9e477ffbfe7)

**Comment by DaniiC00kie** [comment]
However, in this path : C:\Users\Danii\AppData\Local\Programs\pgAdmin 4 the dll exists.

The exact location is: C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\runtime\libpq.dll

It seems theres a misshap between local and roaming paths ?

**Comment by khushboovashi** [comment]
C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\runtime\libpq.dll is correct, so it should be linked, and pgAdmin should work fine.
As a workaround, add the path of the libpq.dll folder to the System Variable **Path**  with a ";" separator.

**Comment by DaniiC00kie** [comment]
So, still does not work, i added the dll to path:

![image](https://github.com/pgadmin-org/pgadmin4/assets/109168862/71ff7e10-5383-40c3-b69e-beb11e9f3fbe)

This is the error (still not sure if it is the same as before)
```
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\Danii\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\config.py"
Webapp Path: "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\python\python.exe -s C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\Danii\AppData\Roaming
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_4756_LJXPHBMJMALCIAMK
  - CHROME_RESTART: NW.js|NW.js ist abgestürzt. Jetzt neu starten?|LEFT_TO_RIGHT
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: DESKTOP-M7CJU4S
  - ComSpec: C:\Windows\system32\cmd.exe
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - EFC_2784: 0
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\Danii
  - JAVA_HOME: C:\Program Files\Eclipse Adoptium\jdk-8.0.392.8-hotspot\
  - LOCALAPPDATA: C:\Users\Danii\AppData\Local
  - LOGONSERVER: \\DESKTOP-M7CJU4S
  - NUMBER_OF_PROCESSORS: 16
  - OneDrive: C:\Users\Danii\OneDrive
  - OneDriveConsumer: C:\Users\Danii\OneDrive
  - OS: Windows_NT
  - path: C:\Program Files\Eclipse Adoptium\jdk-8.0.392.8-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.9.9-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\Danii\AppData\Local\Microsoft\WindowsApps;C:\Windows\AtlasModules;C:\Windows\AtlasModules\Apps;C:\Windows\AtlasModules\Other;C:\Windows\AtlasModules\Tools;C:\Windows\AtlasModules\Scripts;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\Windows\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Kubernetes\Minikube;C:\Users\Danii\AppData\Local\Microsoft\WindowsApps;C:\Users\Danii\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Danii\.dotnet\tools;C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\runtime\libpq.dll;
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PGADMIN_INT_KEY: 5f6ce294-bf55-4f35-8318-eaf6b8b0f586
  - PGADMIN_INT_PORT: 60366
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
  - PROCESSOR_LEVEL: 23
  - PROCESSOR_REVISION: 0802
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Windows\AtlasModules\Scripts\Modules
  - PUBLIC: C:\Users\Public
  - SESSIONNAME: Console
  - SystemDrive: C:
  - SystemRoot: C:\Windows
  - TEMP: C:\Users\Danii\AppData\Local\Temp
  - TMP: C:\Users\Danii\AppData\Local\Temp
  - USERDOMAIN: DESKTOP-M7CJU4S
  - USERDOMAIN_ROAMINGPROFILE: DESKTOP-M7CJU4S
  - USERNAME: Danii
  - USERPROFILE: C:\Users\Danii
  - VBOX_MSI_INSTALL_PATH: C:\Program Files\Oracle\VirtualBox\
  - windir: C:\Windows
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.007 Sec
Traceback (most recent call last):
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgAdmin4.py", line 104, in <module>

    app = create_app()
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgadmin\__init__.py", line 534, in create_app

    driver.init_app(app)
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgadmin\utils\driver\__init__.py", line 27, in init_app

    DriverRegistry.load_modules(app)
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgadmin\utils\driver\registry.py", line 20, in load_modules

    from . import psycopg3 as module
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\web\pgadmin\utils\driver\psycopg3\__init__.py", line 21, in <module>
    import psycopg
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\python\lib\site-packages\psycopg\__init__.py", line 9, in <module>

    from . import pq  # noqa: F401 import early to stabilize side effects
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\python\lib\site-packages\psycopg\pq\__init__.py", line 114, in <module>

    import_from_libpq()
  File "C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\python\lib\site-packages\psycopg\pq\__init__.py", line 106, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: DLL load failed while importing pq: Das angegebene Modul wurde nicht gefunden.
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: Could not find module 'libpq.dll' (or one of its dependencies). Try using the full path with constructor syntax.


```

**Comment by khushboovashi** [comment]
Add only the folder path,  C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\runtime

**Comment by DaniiC00kie** [comment]
worked, yea. thanks - will this be fixed in the next version?

**Comment by khushboovashi** [comment]
I am not sure why the libpq path was not set for you as we have already added the libpq path to the current process in the code base. So, we couldn't fix this until we can reproduce this issue at our end.

**Comment by DaniiC00kie** [comment]
mhm okay - maybe windows 11 behaves differently than windows 10 ? weird problem ... but okay yea, thank you very much anyways - close this issue if you want, I still let it open in case you want to keep track of it.

**Comment by M3rcena** [comment]
> I am not sure why the libpq path was not set for you as we have already added the libpq path to the current process in the code base. So, we couldn't fix this until we can reproduce this issue at our end.

Hi, I also have the same issue with Linux Ubuntu, do you know how may I fix it?

**Comment by solarsamuel** [comment]
I had the same issue yesterday, but was able to fix it by editing the Path system variable and adding: C:\Program Files\PostgreSQL\16\bin

This worked for Postgres 16.4-2. I was running with the Windows 10 Pro OS. 

After editing the Path, open the windows command line (cmd) and type: psql -V 

It should show the postgres version. Then you should be able to connect to postgres through the command line with this command: psql -U postgres -h localhost -p 5432

See attached. 
![postgres16 change](https://github.com/user-attachments/assets/4c63fcaf-9f6d-4543-8325-af910859c238)

**Comment by johnesc1984** [comment]
borre C:\Users\John\AppData\Roaming\pgadmin y funciono por si a alguien le pasa
