### ISSUE TITLE
Incorrect display of table check constraint definition.

### ISSUE THREAD

**Issue by Satek7** [pgadmin-org/pgadmin4#7160]
**Describe the bug**

pgAdmin display incorrect table check contraint definition in SQL window and table properties

**To Reproduce**

CREATE TABLE test.t1 (
    c1 integer NOT NULL,
    c2 text,
    c3 text,
    CONSTRAINT t1_chk CHECK (c1 IS NULL OR (c1 IS NOT NULL AND c2 IS NOT NULL))
);

check condition is

c1 IS NULL OR (c1 IS NOT NULL AND c2 IS NOT NULL)

pgAdmin display incorrect check definition and miss brackets  

CREATE TABLE IF NOT EXISTS test.t1
(
    c1 integer NOT NULL,
    c2 text COLLATE pg_catalog."default",
    c3 text COLLATE pg_catalog."default",
    CONSTRAINT t1_chk CHECK (c1 IS NULL OR c1 IS NOT NULL AND c2 IS NOT NULL)
)

pg_dump generates definition correctly as 

CREATE TABLE test.t1 (
    c1 integer NOT NULL,
    c2 text,
    c3 text,
    CONSTRAINT t1_chk CHECK (((c1 IS NULL) OR ((c1 IS NOT NULL) AND (c2 IS NOT NULL))))
);

**Comment by Satek7** [comment]
I think the source of problem is inside function 

pg_get_constraintdef ( constraint oid [, pretty boolean ] ) → text

where pretty incorecly removes brackets

**Comment by adityatoshniwal** [comment]
@Satek7 This is not a bug. PostgreSQL simplifies your expression and stores it. pgAdmin will retrieve and show it from PostgreSQL server. If you think its not correct then you can raise it to PG team on pgsql-admin@postgresql.org. Below is the output by psql terminal:

<img width="972" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/cbff9200-46e4-4240-9bab-027c6378998d">
