### ISSUE TITLE
Edition of CHECK condition is not applied

### ISSUE THREAD

**Issue by IAkumaI** [pgadmin-org/pgadmin4#7164]
Edition of CHECK condition is not applied.

**To Reproduce**

1. Create table (manually or via pdAdmin) like this:
```sql
-- pdAdmin SQL tab
CREATE TABLE public.examle
(
    id integer,
    CONSTRAINT examle_ck CHECK (id > 0) NOT VALID
);
```
2. Go to the table Properties > Constraints > Check. Our constraint has "id > 0" check. Lets say, I want to change it to "id >= 0". Do it.
3. Go to SQL tab of the window: It's none. No SQL generated. So saving will have no effect at all.

**Expected behavior**
Either not possible to edit the check or generate some ALTER sql for it.
I'm not sure if we can alter check clause in postgres (suppose we can't), so better just make the field readonly.

First time I didn't open SQL tab and just clicked Save. It seemed like worked, but then I realized it didn't. No errors, not warning, nothing.

**Screenshots**

<img width="809" alt="Screenshot 2024-01-29 at 23 07 35" src="https://github.com/pgadmin-org/pgadmin4/assets/907560/525a594c-2af9-4fc8-b09f-b2f20c7e3402">
<img width="764" alt="Screenshot 2024-01-29 at 23 08 32" src="https://github.com/pgadmin-org/pgadmin4/assets/907560/734a17a6-dcb9-428c-9a6c-815257e5ba14">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2.1
 - Version: pgAdmin4 8.2
 - Mode: Desktop
 - Browser: Chromium 114.0.5735.91
 - Package type: downloaded dmg

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-02-23/

Env:
OS - macOS 14.2.1 (Sonoma)
Mode - Desktop
