### ISSUE TITLE
Wrong Diff query generation for a table with sequence

### ISSUE THREAD

**Issue by IAkumaI** [pgadmin-org/pgadmin4#7165]
**Describe the bug**

Diff query for a table with sequence field does not work.

**To Reproduce**

1. Create simple table:
```sql
CREATE TABLE public.example
(
    id bigserial,
    PRIMARY KEY (id)
);
```
2. Make diff with the Diff toll of pgAdmin. Compare. Select both of the sequence and the table. Generate query script.
```sql
 BEGIN; 
 CREATE TABLE IF NOT EXISTS public.example
(
    id bigint NOT NULL DEFAULT nextval('example_id_seq'::regclass),
    CONSTRAINT example_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.example
    OWNER to postgres;

CREATE SEQUENCE IF NOT EXISTS public.example_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1
    OWNED BY example.id;

ALTER SEQUENCE public.example_id_seq
    OWNER TO postgres;

 END;
```

**Expected behavior**

It works.

**Error message**

`ERROR:  relation "example_id_seq" does not exist`
It's obvious you cant create table withou the sequence and, either, you can create sequence without the table, so the possible solution I see it to move `OWNER BY` from sequence `ALTER` after table creation.

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2.1
 - Version: pgAdmin4 
 - Mode: Desktop
 - Browser: Chromium 114.0.5735.91
 - Package type: Downloaded dmg

**Comment by pravesh-sharma** [comment]
Hi @anilsahoo20,

While testing, I found that if we compare two different databases and then try to run the script, we get an error. Screenshot for ref.

![Image](https://github.com/pgadmin-org/pgadmin4/assets/111979571/fa4ee708-1ad4-4e7d-b2a7-ee954dd41410)


![Image](https://github.com/pgadmin-org/pgadmin4/assets/111979571/8892d5d3-60e6-4fed-92f0-551881f3ec4d)

**Comment by anilsahoo20** [comment]
Please keep in mind, the below points while using the schema diff tool,

1. Due to circular dependancies, the order in which Schema Diff writes the objects is not very sophisticated and may require manual changes to the script to ensure changes are applied in the correct order.
2. When you are comparing two different schemas, the default value for a sequence is schema qualified, so it holds the source schema's name, change it to target schema name, if you want to assign it to target schema's sequence.

**Comment by JyotiEdb** [comment]
Tested and verified on snapshot build: 
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-26/
