### ISSUE TITLE
Windows: Error when trying to create a named restore point. Error: local variable 'status' referenced before assignment.

### ISSUE THREAD

**Issue by keshavkaul** [pgadmin-org/pgadmin4#7166]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
On Windows, An error is displayed when trying to create a named restore point. 
**Error:** `local variable 'status' referenced before assignment`

<img width="1352" alt="Screenshot 2024-01-30 at 8 21 07 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/3319809/2bc271a6-25d9-4a55-9c75-0f1377698816">

**To Reproduce**

1. On Windows, Install Postgres 15 or 16 (issue with both), install latest PgAdmin v8.2
2. Right click the postgres server.
3. Click "Add Named Restore Point..."
4. Enter any name in the dialog that opens.
5. Click OK. 

**Expected behavior**

Successful restore point created

**Error message**

`local variable 'status' referenced before assignment`

**Screenshots**

Attached above

**Desktop (please complete the following information):**
 - OS: Windows server 2022
 - Version: 21H2
 - Mode: server desktop

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on candidate build.

Env -

OS - macOS Sonoma
Mode - Desktop

**Comment by keshavkaul** [comment]
Thank you all. Appreciate it!
@anilsahoo20 @pravesh-sharma @akshay-joshi @adityatoshniwal
