### ISSUE TITLE
pgAdmin not opening after successful installation on mac

### ISSUE THREAD

**Issue by skflwright** [pgadmin-org/pgadmin4#7177]
Hi, I'm not a mac user but I have students I help who are and they have had issues using the latest pgAdmin installation when installing postgreSQL onto their macbooks.  Is there a trouble shooting guide for mac users to which I can refer them? Please advise. Thanks

K

**Comment by adityatoshniwal** [comment]
Hi @skflwright,
Which installer did you use to install? Please share the Mac details as well.

**Comment by skflwright** [comment]
HiYou’ll want to use pgadmin4 version 6.2It’s also easier if you install postgreSQL15 instead of 16I’ll be meeting with students tomorrow morning. Kimberly Sent from my iPhoneOn Feb 1, 2024, at 11:57 PM, Aditya Toshniwal ***@***.***> wrote:﻿
Hi @skflwright,
Which installer did you use to install? Please share the Mac details as well.

**Comment by adityatoshniwal** [comment]
Hi @skflwright,
I recommend uninstall current pgAdmin and download the latest from https://www.pgadmin.org/download/pgadmin-4-macos/ based on Mac Silicon or Intel.

**Comment by skflwright** [comment]
Thanks sorry thought you were one of the students. What has worked for
those with macs is to upload lower versions. Too many glitches with latest
pgAdmin. But thank you. I'll suggest this link as well.
