### ISSUE TITLE
Backup fails because pg_dump command does not include certificate authentication parameters supplied to server

### ISSUE THREAD

**Issue by Ianvdl** [pgadmin-org/pgadmin4#7182]
**Describe the bug**

We use MTLS authentication, so we specify a client certificate, a client certificate key, and a root certificate in the server parameters. This works for a normal connection. When we choose the "Backup" option, the generated pg_dump command line parameters do not include these parameters, so the command fails with the message "no valid certificate presented". 

**To Reproduce**

1. Create a new server, and specify a client certificate, a client certificate key, and a root certificate for authentication, and specify SSL mode to verify-ca
2. Connect to the server
3. Right-click on the server and choose "Backup"
4. Complete the form, and click on "Backup"
5. See error message from pg_dump that a certificate was not supplied

**Expected behavior**

pgAdmin should add the certificate parameters supplied to the server to the pg_dump parameters: sslcert=<cert> sslkey=<key> sslrootcert=<ca_crt> sslmode=verify-ca"

**Error message**

The complete error message is:

```
pg_dump: error: connection to server at "<host>", port <port> failed: ERROR: CERT authentication failed
```

**Screenshots**

![pg_dump_screenshot](https://github.com/pgadmin-org/pgadmin4/assets/1923157/3e80b750-349f-4f09-bed0-ddec68834894)

**Desktop (please complete the following information):**
 - OS: Linux-4.18.0-372.64.1.el8_6.x86_64-x86_64-with
 - Version: 7.1
 - Mode: Server
 - Browser Firefox 122.0
 - Package type: Should be RPM but I'm not sure.

I do not run the server that pgAdmin runs on, so the OS above is from the About dialog. 

**Additional context**

**Comment by Ianvdl** [comment]
@akshay-joshi I see this issue was flagged as Not Refined - did I omit something that is needed to report the issue appropriately?

Thank you for your time.

**Comment by akshay-joshi** [comment]
@Ianvdl 

"Not Refined" indicates that the team will review the issue during the refinement meeting and determine whether it should be moved to the sprint or if additional information is required from your end.

**Comment by Ianvdl** [comment]
Understood, thank you.

**Comment by pravesh-sharma** [comment]
Hi @Ianvdl,

I am not able to reproduce the issue. Attaching pgAdmin server parameters and PostgreSQL SSL config.



![Image](https://github.com/pgadmin-org/pgadmin4/assets/111979571/d921de66-6573-4393-a121-f5c629ad51b5)

**Comment by adityatoshniwal** [comment]
@Ianvdl Just to add, the ssl params are not passed as pg_dump params but are set as env vars.
```python
                self.env['PGSSLMODE'] = server.connection_params['sslmode'] \
                    if hasattr(server, 'connection_params') and \
                    'sslmode' in server.connection_params else 'prefer'
                self.env['PGSSLCERT'] = '' if sslcert is None else sslcert
                self.env['PGSSLKEY'] = '' if sslkey is None else sslkey
                self.env['PGSSLROOTCERT'] = \
                    '' if sslrootcert is None else sslrootcert
```

**Comment by Ianvdl** [comment]
@pravesh-sharma and @adityatoshniwal Thank you for the feedback and the details on the environment variables (it's good to know that they should be populated even though we don't see them in the command line), I'll revert back to the user who experienced this issue to try and find the cause.
