### ISSUE TITLE
Incorrect password and username

### ISSUE THREAD

**Issue by MuindiStephen** [pgadmin-org/pgadmin4#7184]
When logging I encounter this error, even during password recovery, the same happens

**Comment by pravesh-sharma** [comment]
Hi @MuindiStephen,

Can you please share more details on the issue?

**Comment by niallnsec** [comment]
I'm having the same issue on 8.3

After upgrading from 8.2 to 8.3 logging in is not possible.

I have pgadmin running under the path /pgadmin4
After clicking the login button on /pgadmin4/login , a POST request is made which gives a 302 to /pgadmin4
That results in a 308 to /pgadmin4/ and finally that gives a 302 to /pgadmin4/login

I checked and the cookies appear to be being set for the session. There are no errors reported in the logs as far as I can see.

**Comment by khushboovashi** [comment]
Hi @niallnsec, please give the OS details and your webserver configuration details.

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
