### ISSUE TITLE
pgAdmin 8.2 does not display large jsonb value

### ISSUE THREAD

**Issue by jbeynar** [pgadmin-org/pgadmin4#7185]
Hi,
On both versions that we have tested (pgAdmin 7.8 and 8.2) we have reproduce issue related to jsonb.

Large jsonb value is not displayed in query editor even though that length function confirms that the contents of the field is not empty.

It has been reproduced on:
- Windows 10 Home with pgAdmin 7.8 and 8.2
- macOS Ventura 13.6.3 reproduced on 7.8, but it works on 8.2

Size of the json we have tested:
- Does not works when json value length is 2122144 or greater
- Does work when json value length is 2006914 or less

Steps to reproduce:
Insert JSON with size 2122144 bytes or greater into jsonb column
When query that column then the value is blank in pgadmin while in another pg client you can see the json value.
You can also run length function on this column to verify that it is not empty.

Cheers

**Comment by adityatoshniwal** [comment]
Duplicates #6510.
