### ISSUE TITLE
Download to CSV not working.

### ISSUE THREAD

**Issue by DavidHoltCVN** [pgadmin-org/pgadmin4#7186]
Using PGAdmin 4.8.2 CSV will not download data to CSV is the returned results is greater than 100,000

**To Reproduce**
1. Open PGAdmin, select server, database, and perform a new query
2. enter the query 
select id, other_id, status,completed_at
from table
where status='complete' and completed_at >='06/01/2023' and completed_at <='02/01/2024'
3. Execute query
4. Click on save results to file
5. Spinner will show Downloading Results until process terminated.

6. Repeat steps 2-5 but instead use a query such as this
select id, other_id, status,completed_at
from table
where status='complete' and completed_at >='01/01/2024' and completed_at <='02/01/2024'

7. If you narrow the results down below a number of returned rows than 100,000 then the download results button will work and prompt for a file name to save it to.

Data formats (id=UUID, other_ID=UUID, status=text, complete_at=timestamp without time zone)

**Expected behavior**

Results should be allowed to be exported to CSV for large datasets, (this had been working on 4.8 on Windows 10.

**Error message**

No error message presented in UI or in log file.  

**Desktop (please complete the following information):**
 - OS: Windows 11 professional 64 bit 23H2
 - Version: 23H2
 - Mode: Desktop
 - Package type: x64 Exe installer

**Additional context**

This query had been working in PGAdmin previously and with larger data sets.  Also works and runs in PSQL within seconds.

**Comment by pravesh-sharma** [comment]
Duplicates #3369
