### ISSUE TITLE
Ubuntu 22.04.3 apt pgadmin4 ssl problem

### ISSUE THREAD

**Issue by Lumanet2012** [pgadmin-org/pgadmin4#7191]
Hello everyone,

we got Ubuntu 22.04.3 TLS running on on a VM. 
We installed as documented from pgadmin.org the via apt the packages and have now installed pgadmin4 as such : 

/usr/pgadmin4# cat config_local.py

LOG_FILE = '/var/log/pgadmin/pgadmin4.log'
SQLITE_PATH = '/var/lib/pgadmin/pgadmin4.db'
SESSION_DB_PATH = '/var/lib/pgadmin/sessions'
STORAGE_DIR = '/var/lib/pgadmin/storage'
SERVER_MODE = True

We do also have Apache 2 configured as such  : 

cat /etc/apache2/conf-enabled/pgadmin4.conf

WSGIDaemonProcess pgadmin processes=1 threads=10 python-home=:/usr/pgadmin4:/usr/lib/python3 python-path=$PYTHONPATH:/usr/pgadmin4/venv:/usr/lib/python3
WSGIScriptAlias /pgadmin /usr/pgadmin4/web/pgAdmin4.wsgi

<Directory /usr/pgadmin4/>
    WSGIProcessGroup pgadmin
    WSGIApplicationGroup %{GLOBAL}
    WSGIScriptReloading On
    Require all granted
    Order deny,allow
    Allow from all
    Allow from 10.0.0.0/8

</Directory>

on top we got PIP3 : 

pip3 list
Package                Version
---------------------- ----------------
attrs                  21.2.0
Automat                20.2.0
Babel                  2.8.0
bcrypt                 3.2.0
bidict                 0.21.3
blinker                1.7.0
certifi                2020.6.20
chardet                4.0.0
click                  8.1.7
cloud-init             23.3.3
colorama               0.4.4
command-not-found      0.3
configobj              5.0.6
constantly             15.1.0
cryptography           3.4.8
dbus-python            1.2.18
distlib                0.3.4
distro                 1.7.0
distro-info            1.1+ubuntu0.2
filelock               3.6.0
Flask                  3.0.2
Flask-SocketIO         5.0.1
gpg                    1.16.0
gunicorn               20.1.0
httplib2               0.20.2
hyperlink              21.0.0
idna                   3.3
importlib-metadata     4.6.4
incremental            21.3.0
itsdangerous           2.1.2
jeepney                0.7.1
Jinja2                 3.1.3
jsonpatch              1.32
jsonpointer            2.0
jsonschema             3.2.0
keyring                23.5.0
launchpadlib           1.10.16
lazr.restfulclient     0.14.4
lazr.uri               1.0.6
MarkupSafe             2.1.5
more-itertools         8.10.0
netifaces              0.11.0
oauthlib               3.2.0
openssl-python         0.1.1
paramiko               2.9.3
pexpect                4.8.0
pip                    24.0
platformdirs           2.5.1
ptyprocess             0.7.0
pyasn1                 0.4.8
pyasn1-modules         0.2.1
PyGObject              3.42.1
PyHamcrest             2.0.2
pyinotify              0.9.6
PyJWT                  2.3.0
PyNaCl                 1.5.0
pyOpenSSL              21.0.0
pyparsing              2.4.7
pyrsistent             0.18.1
pyserial               3.5
python-apt             2.4.0+ubuntu2
python-debian          0.1.43+ubuntu1.1
python-engineio        4.0.0
python-magic           0.4.24
python-socketio        5.0.3
pytz                   2022.1
PyYAML                 5.4.1
requests               2.25.1
SecretStorage          3.3.1
service-identity       18.1.0
setuptools             59.6.0
simplejson             3.17.6
six                    1.16.0
sos                    4.5.6
ssh-import-id          5.11
sshtunnel              0.1.4
systemd-python         234
Twisted                22.1.0
ubuntu-advantage-tools 8001
ubuntu-drivers-common  0.0.0
ufw                    0.36.1
unattended-upgrades    0.1
urllib3                1.26.5
uWSGI                  2.0.23
virtualenv             20.13.0+ds
wadllib                1.3.6
Werkzeug               3.0.1
wheel                  0.37.1
xkit                   0.0.0
zipp                   1.0.0
zope.interface         5.4.0

all this is proper installed and running. But when we try to access or start via python the wsgi file we get this :in the apache2 error log: 

mod_wsgi (pid=1151): Failed to exec Python script file '/usr/pgadmin4/web/pgAdmin4.wsgi'.
 mod_wsgi (pid=1151): Exception occurred processing WSGI script '/usr/pgadmin4/web/pgAdmin4.wsgi'.
 Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgAdmin4.wsgi", line 25, in <module>
     import config
  File "/usr/pgadmin4/web/config.py", line 32, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
 File "/usr/pgadmin4/web/pgadmin/__init__.py", line 25, in <module>
     from flask_socketio import SocketIO
   File "/lib/python3/dist-packages/flask_socketio/__init__.py", line 21, in <module>
     import socketio
   File "/lib/python3/dist-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/lib/python3/dist-packages/socketio/client.py", line 7, in <module>
    import engineio
 File "/lib/python3/dist-packages/engineio/__init__.py", line 3, in <module>
    from .client import Client
   File "/lib/python3/dist-packages/engineio/client.py", line 9, in <module>
    import ssl
  File "/lib/python3.10/ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
 ModuleNotFoundError: No module named '_ssl'

Looking at the error message I am guessing this is a _ssl module which is missing even PGAdmin4 wasn't complaining about anything. 
Apache is restarted just fine and other things like phpmyadmin and even a perl system are running on this same server as well just fine. 

and we receive a standard error 500 upfront : 

"GET /pgadmin HTTP/1.1" 500 796 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@mynaturesdelight.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache Server at <URL> Port 80

So if anyone would be so kind and helpful to figure out why when clearly document the apt procedure that it doesn't work as straight forward as it should. 

We looked a a dozen websites and options, got a bunch of packages installed by hand like pyhon3-socketio and python3-flask and such because all those dependencies where not set when pgadmin4 was installed it didn't wanted to install them. 

apt install python3-werkzeug python3-sshtunnel python3-flask python3-itsdangerous python3-pyinotify python3-simplejson python3-virtualenv libssl-dev 

those listed we had to install by hand to get rid of all the other issues. 

So hopefully someone can take a stab at this and charm in on what is wrong and why things ain't better documented. 

NGINX and APACHE2 config's are no longer really around so we had to look at a dozen websites to find the working setup which is shared above .

Apache 2.4.52-1ubuntu4.7 amd64  which is a standard package of Ubuntu 22.04.3 LTS is installed.

**Comment by AxiomPraxis** [comment]
This looks like more of a python issue than a pgadmin issue.

You mentioned you installed libssl-dev, which is good, because Python looks like it's missing the ssl .so (shared object file, like a Windows .dll) Make you also install openssl itself also.

```bash
sudo apt-get install openssl libssl-dev
```

If you initially built/compiled python manually, rebuild it so it has the proper ssl libraries included (make sure to update the ./configuration with whichever flags you used during your configuration).

```bash
sudo make clean
./configure
sudo make test
sudo make && sudo make install
```

If you installed a pre-built python, try to upgrade to beyond Python 3.11.5, that's when they made the latest SSL changes.

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing the issue.
