### ISSUE TITLE
ability to set accesskey, or rebind save/open

### ISSUE THREAD

**Issue by ellisonch** [pgadmin-org/pgadmin4#7192]
I'm trying to use the query tool.  I'm on windows, and I expect shortcuts to use `ctrl`, e.g., "save" should be `ctrl-s` and "open" should be `ctrl-o`.  However, my "accesskey" seems to be set to `alt` and I cannot figure out how to change it.  The "keyboard shortcuts" tab under the "query tool" settings in file/preferences doesn't allow changing meta keys or the accesskey, as far as I can tell.

Even more confusing is that copy/paste/find all work with `ctrl` and don't work with `alt`.

I'm on Windows 10 using the standalone pgadmin4 version 8.2.

How can I rebind "save" to `ctrl-s`, or change my "accesskey" to `ctrl`?

**Comment by pravesh-sharma** [comment]
Hi @ellisonch,

The access key is something which can not be changed as defined by OS+browser. We will re-evaluate and check if we can remove the access key completely.
