### ISSUE TITLE
pgAdmin4 - Refresh Table inoperative on ERD

### ISSUE THREAD

**Issue by dalmaupatrick** [pgadmin-org/pgadmin4#7194]
Description:
When modifying a Table via the Object Explorer/Object/Properties (adding Constraint, Column or else,
the ERD doesn't take the changes.

to reproduce:
1 - On a  table Object Explorer/Tables/Properties 
2 - add 1 constraint or 1 column
3 - Save
4 - Object Explorer/Table/Refresh 
     Table display is ok for the changes
5 - When I drag & move the table on ERD
      The changes doesn't appear.

**Expected behavior**

To not have to refresh the object explorer hierarchy when i save a change.
The ERD has to take the changes when they are saved in properties window.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Mode: [Desktop]

Thanks a lot

Patrick

**Comment by adityatoshniwal** [comment]
HI @dalmaupatrick,
I tried all the changes. Drag and drop works fine without refreshing anything. Check the below screenshot.
Just to mention, on dropping a table on ERD canvas the data is fetched from backend and not taken from the UI.
<img width="1095" alt="Screenshot 2024-02-08 at 11 46 17" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/ea902045-7ad6-4fb0-bb20-36be4bdfe9dc">

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
