### ISSUE TITLE
Dashboard/General/Sessions section, the Sql content is short

### ISSUE THREAD

**Issue by abdullahyapici** [pgadmin-org/pgadmin4#7196]
Hello,

In the Dashboard/General/Sessions section, the Sql content is short in the row detail that appears on the screen, how can I make it appear more.

**Comment by adityatoshniwal** [comment]
Hi @abdullahyapici,
It shows the complete SQL. Did you try scrolling? Can you share screenshot of the issue?
<img width="1298" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/dd6b77c9-c3c7-4fc8-9231-2f1d748c24f2">

**Comment by abdullahyapici** [comment]
Bilmeden bitti olarak işaretledim, yardımlarınızı rica ediyorum.

**Comment by abdullahyapici** [comment]
I unknowingly marked it as finished, I ask for your help.

**Comment by pravesh-sharma** [comment]
Hi @abdullahyapici ,

It looks like you have a very large query. PostgreSQL has some limits on the size of the query stored. Please check https://www.postgresql.org/docs/current/runtime-config-statistics.html#GUC-TRACK-ACTIVITY-QUERY-SIZE

**Comment by abdullahyapici** [comment]
Thank you very much for your interest.

> Hi @abdullahyapici ,
> 
> It looks like you have a very large query. PostgreSQL has some limits on the size of the query stored. Please check https://www.postgresql.org/docs/current/runtime-config-statistics.html#GUC-TRACK-ACTIVITY-QUERY-SIZE

Thank you very much for your interest.
