### ISSUE TITLE
Saved passwords are discarded when network times out

### ISSUE THREAD

**Issue by baldurg** [pgadmin-org/pgadmin4#7199]
Forgetting a saved password is not the right way to deal with a network error. Please fix this.
![image](https://github.com/pgadmin-org/pgadmin4/assets/225764/a91bddbc-13a8-43ca-aae7-f8dc6f2e19e8)

**Comment by pravesh-sharma** [comment]
Hi @baldurg,

The saved password is not removed. This dialog is intended to show the error while connecting. You enter the password or close the dialog and connect again.

**Comment by baldurg** [comment]
I see, that is a relief. It is still very confusing to display a password entry dialog in any scenario that does not involve a rejected password.

**Comment by adityatoshniwal** [comment]
> I see, that is a relief. It is still very confusing to display a password entry dialog in any scenario that does not involve a rejected password.

It is not possible to detect whether it got failed because of invalid password or not. The error comes from PostgreSQL server. So its better to show the password dialog along with the error so that user has a choice to enter to a new one.
