### ISSUE TITLE
Gentoo: locally crafted ebuild install fails beyond splash here...

### ISSUE THREAD

**Issue by CaptainBloodz** [pgadmin-org/pgadmin4#7202]
Since dev-db/pgadmin4-4.30 removal from gentoo portage tree, I attempted to locally maintain a ebuild install script for pgadmin4.
So installed package ran fine here until dev-db/pgadmin4-7.0, a milestone from which installed app failed to start properly.

Current ebuild crafted here.
[pgadmin4-8.3.ebuild.gz](https://github.com/pgadmin-org/pgadmin4/files/14224229/pgadmin4-8.3.ebuild.gz)

This package install script contains some package constrains herited from the last official dev-db/pgadmin4-4.30 script.
Those worked with  until dev-db/pgadmin4-7.0
It also has been updated to match 'requirements.txt' from source tar file.

The situation is that splash start and closes, then a window opens with an endless 'whirling' circle.
[pgadmin4.log](https://github.com/pgadmin-org/pgadmin4/files/14224334/pgadmin4.log)

[pgadmin4-8.3-package-dependencies-tree.txt](https://github.com/pgadmin-org/pgadmin4/files/14226954/pgadmin4-8.3-package-dependencies-tree.txt)

The app is running in python-11.

Plz note the script installs [config_local.py.gz](https://github.com/pgadmin-org/pgadmin4/files/14224413/config_local.py.gz)  in /usr/share/pgadmin4/web.

Side notes:
Upgrading dev-python/flask-security-5.1.0 to dev-python/flask-security-5.2.0 breaks at splash level.
Initiating eventlet upgrade to python-3.10 [https://github.com/eventlet/eventlet/issues/780#issuecomment-1862973804](url)
has not lead me to pgadmin4 working again.

When working in 6.xx, app was running in desktop mode IIUC, which is the mode I wish to see running properly.

Hoping someone will be courageous enough to help me out of such a mess.

**Comment by CaptainBloodz** [comment]
Using default config.py throws the same pgadmin4.log
Activating DEBUG= True doesn't change log content.

Maybe cause of failure is too early for such an activation to take place...

**Comment by yogeshmahajan-1903** [comment]
@CaptainBloodz 

Working python venv pip freeze - 
```
alembic==1.13.1
anyio==4.2.0
attrs==23.2.0
Authlib==1.2.1
azure-common==1.1.28
azure-core==1.29.6
azure-identity==1.15.0
azure-mgmt-core==1.4.0
azure-mgmt-rdbms==10.1.0
azure-mgmt-resource==23.0.1
azure-mgmt-subscription==3.1.1
Babel==2.14.0
bcrypt==4.0.1
bidict==0.22.1
blinker==1.7.0
boto3==1.33.13
botocore==1.33.13
Brotli==1.1.0
cachetools==5.3.2
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
cryptography==41.0.7
decorator==5.1.1
dnspython==2.3.0
email-validator==2.1.0.post1
eventlet==0.34.2
extras==1.0.0
fixtures==4.1.0
Flask==2.3.3
flask-babel==4.0.0
Flask-Compress==1.14
Flask-Gravatar==0.5.0
Flask-Login==0.6.3
Flask-Mail==0.9.1
Flask-Migrate==4.0.5
Flask-Paranoid==0.3.0
Flask-Principal==0.4.0
Flask-Security-Too==5.2.0
Flask-SocketIO==5.3.6
Flask-SQLAlchemy==3.1.1
Flask-WTF==1.2.1
google-api-core==2.15.0
google-api-python-client==2.113.0
google-auth==2.26.2
google-auth-httplib2==0.2.0
google-auth-oauthlib==1.1.0
googleapis-common-protos==1.62.0
greenlet==3.0.3
gssapi==1.8.3
h11==0.14.0
httpagentparser==1.9.5
httplib2==0.22.0
idna==3.6
importlib-resources==6.1.1
isodate==0.6.1
itsdangerous==2.1.2
jaraco.classes==3.3.0
Jinja2==3.1.3
jmespath==1.0.1
keyring==24.3.0
ldap3==2.9.1
linecache2==1.0.0
Mako==1.3.0
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
more-itertools==10.2.0
msal==1.26.0
msal-extensions==1.1.0
msrest==0.7.1
oauthlib==3.2.2
outcome==1.3.0.post0
packaging==23.2
paramiko==3.4.0
passlib==1.7.4
pbr==5.11.1
portalocker==2.8.2
protobuf==4.25.2
psutil==5.9.7
psycopg==3.1.12
psycopg-c==3.1.12
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycodestyle==2.11.1
pycparser==2.21
Pygments==2.17.2
PyJWT==2.8.0
PyNaCl==1.5.0
pyotp==2.9.0
pyparsing==3.1.1
pypng==0.20220715.0
PySocks==1.7.1
python-dateutil==2.8.2
python-engineio==4.8.2
python-mimeparse==1.6.0
python-socketio==5.11.0
pytz==2023.3.post1
qrcode==7.4.2
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.7.0
rsa==4.9
s3transfer==0.8.2
selenium==4.10.0
setuptools==69.0.3
shellingham==1.5.4
simple-websocket==1.0.0
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
speaklater3==1.4
SQLAlchemy==2.0.25
sqlparse==0.4.4
sshtunnel==0.4.0
testscenarios==0.5.0
testtools==2.7.1
traceback2==1.4.0
trio==0.24.0
trio-websocket==0.11.1
typer==0.9.0
typing_extensions==4.9.0
ua-parser==0.18.0
uritemplate==4.1.1
urllib3==1.26.18
user-agents==2.2.0
Werkzeug==2.3.8
wsproto==1.2.0
WTForms==3.1.2
```

**Comment by CaptainBloodz** [comment]
Thks 4 ur reply.
At least I feel less lonely.

> Working python venv pip freeze -
Is this your diagnose what seems to happen (wrongly on my side ?
-------------------------------------------------------------------------------------------------
I'm confronting your list with what is installed here:
> ```
> alembic==1.13.1
> anyio==4.2.0
> attrs==23.2.0
> Authlib==1.2.1 <= 1.2.0 here
> azure-common==1.1.28 <= 1.1.27 here
> azure-core==1.29.6 <= 1.26.3 here
> azure-identity==1.15.0
> azure-mgmt-core==1.4.0 <= 1.3.0 here
> azure-mgmt-rdbms==10.1.0
> azure-mgmt-resource==23.0.1
> azure-mgmt-subscription==3.1.1
> Babel==2.14.0
> bcrypt==4.0.1
> bidict==0.22.1
> blinker==1.7.0
> boto3==1.33.13 <= 1.33.11
> botocore==1.33.13 <= 1.33.11
> Brotli==1.1.0
> cachetools==5.3.2
> certifi==2023.11.17 <=  3021.3.16-r4
> cffi==1.16.0
> charset-normalizer==3.3.2
> click==8.1.7
> colorama==0.4.6
> cryptography==41.0.7
> decorator==5.1.1 <= 5.1.1-r1 
> dnspython==2.3.0 <= 2.5.0
> email-validator==2.1.0.post1 
> eventlet==0.34.2
> extras==1.0.0 <= not  installed but available
> fixtures==4.1.0 <= not  installed but available
> Flask==2.3.3
> flask-babel==4.0.0
> Flask-Compress==1.14
> Flask-Gravatar==0.5.0
> Flask-Login==0.6.3
> Flask-Mail==0.9.1
> Flask-Migrate==4.0.5
> Flask-Paranoid==0.3.0
> Flask-Principal==0.4.0
> Flask-Security-Too==5.2.0
> Flask-SocketIO==5.3.6
> Flask-SQLAlchemy==3.1.1
> Flask-WTF==1.2.1
> google-api-core==2.15.0
> google-api-python-client==2.113.0
> google-auth==2.26.2
> google-auth-httplib2==0.2.0
> google-auth-oauthlib==1.1.0
> googleapis-common-protos==1.62.0
> greenlet==3.0.3
> gssapi==1.8.3
> h11==0.14.0
> httpagentparser==1.9.5
> httplib2==0.22.0
> idna==3.6
> importlib-resources==6.1.1
> isodate==0.6.1
> itsdangerous==2.1.2
> jaraco.classes==3.3.0
> Jinja2==3.1.3
> jmespath==1.0.1
> keyring==24.3.0
> ldap3==2.9.1
> linecache2==1.0.0
> Mako==1.3.0
> markdown-it-py==3.0.0
> MarkupSafe==2.1.3
> mdurl==0.1.2
> more-itertools==10.2.0
> msal==1.26.0
> msal-extensions==1.1.0
> msrest==0.7.1
> oauthlib==3.2.2
> outcome==1.3.0.post0
> packaging==23.2
> paramiko==3.4.0
> passlib==1.7.4
> pbr==5.11.1
> portalocker==2.8.2
> protobuf==4.25.2
> psutil==5.9.7
> psycopg==3.1.12
> psycopg-c==3.1.12
> pyasn1==0.5.1
> pyasn1-modules==0.3.0
> pycodestyle==2.11.1
> pycparser==2.21
> Pygments==2.17.2
> PyJWT==2.8.0
> PyNaCl==1.5.0
> pyotp==2.9.0
> pyparsing==3.1.1
> pypng==0.20220715.0
> PySocks==1.7.1
> python-dateutil==2.8.2
> python-engineio==4.8.2
> python-mimeparse==1.6.0
> python-socketio==5.11.0
> pytz==2023.3.post1
> qrcode==7.4.2
> requests==2.31.0
> requests-oauthlib==1.3.1
> rich==13.7.0
> rsa==4.9
> s3transfer==0.8.2
> selenium==4.10.0
> setuptools==69.0.3
> shellingham==1.5.4
> simple-websocket==1.0.0
> six==1.16.0
> sniffio==1.3.0
> sortedcontainers==2.4.0
> speaklater3==1.4
> SQLAlchemy==2.0.25
> sqlparse==0.4.4
> sshtunnel==0.4.0
> testscenarios==0.5.0
> testtools==2.7.1
> traceback2==1.4.0
> trio==0.24.0
> trio-websocket==0.11.1
> typer==0.9.0
> typing_extensions==4.9.0
> ua-parser==0.18.0
> uritemplate==4.1.1
> urllib3==1.26.18
> user-agents==2.2.0
> Werkzeug==2.3.8
> wsproto==1.2.0
> WTForms==3.1.2
> ```
This list update is in progress, not entirely updated yet.

**Comment by akshay-joshi** [comment]
@CaptainBloodz 

This doesn't look like a pgAdmin issue, hence closing it.
