### ISSUE TITLE
Bump libexpat 2.5.0 to 2.6.0

### ISSUE THREAD

**Issue by arthuRHD** [pgadmin-org/pgadmin4#7205]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe**

Currently, the Docker image contains 2 critical CVE from this library. Updating the version inside the dockerfile should solve it.

**Comment by yogeshmahajan-1903** [comment]
8.4 candidate build does not have any Vulnerabilities.
<img width="801" alt="Screenshot 2024-03-05 at 11 51 21 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/f7e1bbf8-49dc-4713-8744-43e1656e42ea">
