### ISSUE TITLE
'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by rbrooklyn** [pgadmin-org/pgadmin4#7210]
**Describe the bug**

When doing anything to a table or a view (and possibly other objects) using the "properties" right click menu, such as adding a column, there is a high chance of an error message of "'NoneType' object has no attribute 'strip'"

**To Reproduce**

1. Go to any table
2. Right click on table name, go to "Properties..."
3. Add a column, or make any other change
4. See the error

**Expected behavior**

Error should not show. Window should close and the work be completed.

**Error message**

'NoneType' object has no attribute 'strip'
This appears in a red box at the bottom of the window.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 8.3, however this has been an issue for years.
 - Mode: Desktop
 - Package type: MSI installer

**Additional context**

This is extremely difficult to track down what triggers this bug. Sometimes it works. Sometimes it does not work. I have no reason for when it works and when it doesn't work. If I go to the SQL tab in the properties window, it produces perfect SQL every time, so I can just copy and paste that and it works fine, but clicking "Save" just doesn't work sometimes.

**Comment by adityatoshniwal** [comment]
Hi @rbrooklyn,
Can you please share the pgAdmin logs from File->Runtime->View logs?

**Comment by rbrooklyn** [comment]
I think this is the bit that you need. I've managed to trigger the bug just now and this is the latest entry. Lines before that are errors that I triggered by not formatting my query correctly.

> --------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:51321/static/js/generated/vendor.others.js?ver=80300:109:2210814
    at XMLHttpRequest.d (http://127.0.0.1:51321/static/js/generated/vendor.others.js?ver=80300:109:2210959)
    at ke.request (http://127.0.0.1:51321/static/js/generated/vendor.others.js?ver=80300:109:2216487)
------------[UI End]----------------

Also a screenshot I should have attached yesterday, in this case I was trying to grant a user update and insert access to a table:
![image](https://github.com/pgadmin-org/pgadmin4/assets/11929484/8c1ea9af-123a-46a7-a370-995a06dba006)

**Comment by rbrooklyn** [comment]
Full log below from this morning. I started pgadmin this morning and tried to give a group access to a table and it failed. This is literally the only operation done with pgadmin and I'm happy to share the full log in this case:

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Program Files\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\RBrooklyn\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Program Files\pgAdmin 4\web\config.py"
Webapp Path: "C:\Program Files\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\pgAdmin 4\python\python.exe -s C:\Program Files\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\RBrooklyn\AppData\Roaming
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_12520_GOYQGZKPRFKOGSBK
  - CHROME_RESTART: NW.js|Whoa! NW.js has crashed. Relaunch now?|LEFT_TO_RIGHT
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: L219555
  - ComSpec: C:\Windows\system32\cmd.exe
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
  - FPS_BROWSER_USER_PROFILE_STRING: Default
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\RBrooklyn
  - JAVA_HOME: C:\Program Files\Microsoft\jdk-17.0.5.8-hotspot\
  - LOCALAPPDATA: C:\Users\RBrooklyn\AppData\Local
  - LOGONSERVER: \\L219555
  - NUMBER_OF_PROCESSORS: 8
  - OneDrive: C:\Users\RBrooklyn\OneDrive - Holland & Barrett
  - OneDriveCommercial: C:\Users\RBrooklyn\OneDrive - Holland & Barrett
  - OS: Windows_NT
  - Path: C:\Program Files\pgAdmin 4\runtime;C:\Program Files\Python311\Scripts\;C:\Program Files\Python311\;C:\Program Files\Microsoft\jdk-17.0.5.8-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\nodejs\;C:\Users\RBrooklyn\AppData\Local\Microsoft\WindowsApps;C:\Users\RBrooklyn\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\PostgreSQL\15\bin;C:\Users\RBrooklyn\AppData\Roaming\npm
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
  - PGADMIN_INT_KEY: cebc4e2e-04b1-49e2-9e8c-756ac0c13aea
  - PGADMIN_INT_PORT: 50596
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
  - PROCESSOR_LEVEL: 6
  - PROCESSOR_REVISION: 8c01
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
  - PUBLIC: C:\Users\Public
  - SESSIONNAME: Console
  - SNOW_AGENT: C:\Program Files\Snow Software\Inventory\Agent\
  - SystemDrive: C:
  - SystemRoot: C:\Windows
  - TEMP: C:\Users\RBROOK~1\AppData\Local\Temp
  - TMP: C:\Users\RBROOK~1\AppData\Local\Temp
  - USERDNSDOMAIN: corp.hollandandbarrett.net
  - USERDOMAIN: CORP
  - USERDOMAIN_ROAMINGPROFILE: CORP
  - USERNAME: RBrooklyn
  - USERPROFILE: C:\Users\RBrooklyn
  - windir: C:\Windows
  - ZES_ENABLE_SYSMAN: 1
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.018 Sec
2024-02-16 09:20:57,196: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 21.527 Sec
------------------------------------------
Total launch time of pgAdmin4: 22.006 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:50596/?key=cebc4e2e-04b1-49e2-9e8c-756ac0c13aea
--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:50596/static/js/generated/vendor.others.js?ver=80300:109:2210814
    at XMLHttpRequest.d (http://127.0.0.1:50596/static/js/generated/vendor.others.js?ver=80300:109:2210959)
    at ke.request (http://127.0.0.1:50596/static/js/generated/vendor.others.js?ver=80300:109:2216487)
------------[UI End]----------------

**Comment by adityatoshniwal** [comment]
@rbrooklyn Still not reproducible. Can you share exact permissions screenshot? We can try same. Or even you can try.

**Comment by rbrooklyn** [comment]
It's not just permissions... It's _anything_ using those windows. On these occasions it was permissions, but sometimes it's adding a column, or a constraint, or anything else.

For example, when writing this comment, I added a column called "farts" to this table and got the error:
![image](https://github.com/pgadmin-org/pgadmin4/assets/11929484/c61d81d1-18c9-4a95-8ce4-74394cc51fe7)
Yet as you can see, valid SQL is produced:
![image](https://github.com/pgadmin-org/pgadmin4/assets/11929484/3b4062e4-a035-4488-8eb1-32d4d35771e0)

I can try 10 times and it works 10 times. I can try 10 times and it fails 10 times (although if it fails I do have to close and reopen to window to have any chance of success). Sometimes I can close the window, do the exact same changes and press "Save" and it will work again. Which is exactly what happened here when I closed the window, did the exact same action, but this time it worked:
![image](https://github.com/pgadmin-org/pgadmin4/assets/11929484/a4ead329-b817-4ebc-91a4-9a0c7aa6f68b)

It's incredibly difficult to reproduce and this bug is years old but I've never reported it as I've never found what triggers it. This has, however, happened over multiple machines.

SELECT VERSION() returns:
PostgreSQL 13.13 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit

**Comment by adityatoshniwal** [comment]
Hi @rbrooklyn,
Does it occur only on this table? If yes, then you can share the DDL of this table.

**Comment by rtrad89** [comment]
I am facing the same issue on Ubuntu with pgAdmin desktop 8.4.

**Comment by rbrooklyn** [comment]
> Hi @rbrooklyn, Does it occur only on this table? If yes, then you can share the DDL of this table.

No, it occurs everywhere.

Is there a way of turning on extra debugging? The logs I've sent don't look very helpful.

**Comment by jonathan-knight** [comment]
This has been a problem since around 7.2 or 7.3.  Prior versions work fine.

The only extra info I can give is that if I make the change to the columns and then hit the "SQL" tab I can see the SQL that's about to be done.

If I hit save first and cause an error, the SQL tab only ever reports "Definition incomplete"

I haven't spotted the pattern of when it happens and when it doesn't.  It's most of the time, but not all of the time and never on new small tables, just the big awkward ones.

**Comment by rbrooklyn** [comment]
Hello,

I've been unable to trigger this bug for the past week. I have loaded in the python code given and once I trigger it I will update this issue with the log.

Just reassuring that I haven't forgotten about this. I'm keen to fix this.

**Comment by rbrooklyn** [comment]
I've managed to trigger the issue this morning when changing permissions for a table.

I have upgraded to 8.4 this morning before this was triggered, so please keep this in mind. In hindsight, that may have been a mistake, but I don't think the python file has been rewritten (or maybe it was still loaded somehow, I don't know) as there is more information this time.

Log is below:

> 2024-03-08 09:37:39,318: ERROR	pgadmin:	'NoneType' object has no attribute 'strip'
> Traceback (most recent call last):
>   File "C:\Program Files\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\__init__.py", line 1074, in update
>     lock_on_table = self.get_table_locks(did, res['rows'][0])
>   File "C:\Program Files\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\utils.py", line 2058, in get_table_locks
>     if row['relation'].strip('\"') == data['name']:
> AttributeError: 'NoneType' object has no attribute 'strip'
> 
> --------------[UI error]---------------
> AxiosError: Request failed with status code 500
>     at http://127.0.0.1:51378/static/js/generated/vendor.others.js?ver=80400:109:2196728
>     at XMLHttpRequest.f (http://127.0.0.1:51378/static/js/generated/vendor.others.js?ver=80400:109:2196873)
>     at ke.request (http://127.0.0.1:51378/static/js/generated/vendor.others.js?ver=80400:109:2202401)
> ------------[UI End]----------------

**Comment by adityatoshniwal** [comment]
@rbrooklyn Thank you for the log. Now we have more info to fix this.

**Comment by gmolop** [comment]
+1 here.. same bug using gui (on v8.4 win)  
as workarround, I run the query manually...  
Ex. `GRANT SELECT ON TABLE public.table_name TO user;` and works

> I've managed to trigger the issue this morning when changing permissions for a table.
> 
> I have upgraded to 8.4 this morning before this was triggered, so please keep this in mind. In hindsight, that may have been a mistake, but I don't think the python file has been rewritten (or maybe it was still loaded somehow, I don't know) as there is more information this time.
> 
> Log is below:
> 
> > 2024-03-08 09:37:39,318: ERROR	pgadmin:	'NoneType' object has no attribute 'strip'
> > Traceback (most recent call last):
> > File "C:\Program Files\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables__init__.py", line 1074, in update
> > lock_on_table = self.get_table_locks(did, res['rows'][0])
> > File "C:\Program Files\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\utils.py", line 2058, in get_table_locks
> > if row['relation'].strip('"') == data['name']:
> > AttributeError: 'NoneType' object has no attribute 'strip'
> > --------------[UI error]---------------
> > AxiosError: Request failed with status code 500
> > at http://127.0.0.1:51378/static/js/generated/vendor.others.js?ver=80400:109:2196728
> > at XMLHttpRequest.f (http://127.0.0.1:51378/static/js/generated/vendor.others.js?ver=80400:109:2196873)
> > at ke.request (http://127.0.0.1:51378/static/js/generated/vendor.others.js?ver=80400:109:2202401)
> > ------------[UI End]----------------

**Comment by anilsahoo20** [comment]
As per the errors in log, we have fixed this.
