### ISSUE TITLE
Upgrade Material UI from v4 to v5

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#7213]
As part of this, we should also get rid of SCSS. The usage has already reduced a lot with MUI4, cleaning up remaining will be good. It will allow real-time themes.

**Comment by adityatoshniwal** [comment]
Implemented with https://github.com/pgadmin-org/pgadmin4/commit/102e0a983956be57fdb63abb356b5b8fcb8b74ba

**Comment by akshay-joshi** [comment]
Tested on Snapshot build 2024-04-24. Basic sanity is done. Check the impacted controls like DateTimePicker and Notistack.
