### ISSUE TITLE
pg_signal_backend check is too restrictive

### ISSUE THREAD

**Issue by pmpetit** [pgadmin-org/pgadmin4#7217]
Hi,

**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

If you want to kill a session using 
<img width="618" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/4059185/71d5f41e-fc9b-4e75-8afb-96bffc25c1ee">

then i have this error  message

<img width="520" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/4059185/9b3f4c75-541c-4843-81eb-7e80427b2ca7">

but using a query i can 

 ```sql
select pg_terminate_backend(149682)
``` 

i think it is because you check that https://github.com/pgadmin-org/pgadmin4/blob/389896411a595a6897b53456fa69e7c017bb9d4a/web/pgadmin/utils/driver/psycopg3/connection.py#L627
the user has been granted with pg_signal_backend.

but in some case, you can kill a session if the user is granted with the connected user using 'with admin option' 

for example i can kill if 

```sql
grant the_user_to_kill to the_user_who_kill with admin option:
```

**To Reproduce**

1. create 2 users

```sql
create user user1 with password user1;
create user user2 with password user2;
grant user2 to user1 with admin option;
```
create 2 psql sessions one with user 1 an other with  user2

2. go to pgadmin console connected as user1 and try to kill session using the red cross => you can't
3. execute the code 
```sql
select pg_terminate_backend(the pid of user2);
```

check that you can kill the session.

version is 
![image](https://github.com/pgadmin-org/pgadmin4/assets/4059185/623c3cbd-a7fb-4c6a-bf86-3706086a62d5)

thanks

**Comment by yogeshmahajan-1903** [comment]
@pmpetit 
Can you please try on latest version 8.3?

**Comment by pmpetit** [comment]
can't test on 8.3, app does not run as 7.8 did.

Is there any breaking change between 7.8 & 8.3 ?

**Comment by pmpetit** [comment]
7.8 i use to load my server connection using 
```bash
/venv/bin/python3 setup.py --load-servers 
```

**Comment by pmpetit** [comment]
arf : 
```log
│ No such option: --load-servers       
``` 
why ??????

**Comment by pmpetit** [comment]
i can not import user anymore

The specified user ID (pierremarie.petit.partxxxxxxyyyzzzz) could not be found.

**Comment by yogeshmahajan-1903** [comment]
@pmpetit 
Just remove '--' from load-servers. Now load-servers is command instead of switch.(In 8.3)

```
(Venv3121) % python3 setup.py load-servers ./server.json --user admin@admin.com
----------
Loading servers with:
User: admin@admin.com
SQLite pgAdmin config: <DB Path>pgadmin4.db
----------
Added 0 Server Group(s) and 1 Server(s)
```

**Comment by pmpetit** [comment]
ok thanks, now i can test in 8.3

i have the same problem.

**Comment by pmpetit** [comment]
but i can
![image](https://github.com/pgadmin-org/pgadmin4/assets/4059185/c7562508-f51c-495e-9f92-7b5929e5b062)

**Comment by yogeshmahajan-1903** [comment]
This is working fine. Verified in 8.4 candidate build.
