### ISSUE TITLE
pgadmin4 8.3 desktop query tool panel maximise icon missing on both win11 and linux 

### ISSUE THREAD

**Issue by grahamj157** [pgadmin-org/pgadmin4#7218]
this icon allowed me to maximise the panel i was most interested in at the time and augments user experience.
Desktop versions at 8.3 are both missing this icon.
![2024-02-16 12_37_55-pgAdmin 4](https://github.com/pgadmin-org/pgadmin4/assets/44218080/ba59bf21-b891-4de6-aab6-9bc2fbfef0ce)

the icon i am talking about shows up in the 8.3 documentation
![2024-02-16 12_42_46-Query Tool — pgAdmin 4 8 3 documentation — Mozilla Firefox](https://github.com/pgadmin-org/pgadmin4/assets/44218080/db040e48-4297-4375-b66d-64ac9331b07c)

I could not find any control mechanism in preferences to activate this or mention of my experience in community.

**Comment by adityatoshniwal** [comment]
You're right. The maximise button is missing.

**Comment by pravesh-sharma** [comment]
Issue fixed, verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-29/)

Env
OS - macOS Sonoma
Mode - Desktop

**Comment by grahamj157** [comment]
great - thank you guys
