### ISSUE TITLE
Notification "Process started" and "Process completed" do not disappear automatically

### ISSUE THREAD

**Issue by JP95Git** [pgadmin-org/pgadmin4#7219]
**Describe the bug**

Related: https://github.com/pgadmin-org/pgadmin4/issues/6571

The notification "Process started" and "Process completed" do not disappear automatically. Those notifications should disappear automatically after a given time.

**To Reproduce**

1. Start pgAdmin
2. Connect to a server.
3. Create a backup of a schema (schema only) using plain.
4. Notification appears.
5. Repeat steps 3 and 4 several times.

**Expected behaviour**

See description.

**Error message**

None.

**Screenshots**

![pgadmin](https://github.com/pgadmin-org/pgadmin4/assets/78929417/3437c36b-7146-40e9-9202-62ce44d70dcf)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Version: 8.3 (also reproducible in 8.2)
 - Mode: ?
 - Browser (if running in server mode): None
 - Package type: exe Installer

**Additional context**

None

**Comment by akshay-joshi** [comment]
Will be covered as part of #6571, hence closing it.

**Comment by JP95Git** [comment]
The issue still exists in pgAdmin 8.9, see screenshot.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-07-18/)

Env:
OS - macOS Sonoma 14.5
Mode - Desktop
