### ISSUE TITLE
Creating a function with arguments creates arguments with double quotes

### ISSUE THREAD

**Issue by JanSladky65** [pgadmin-org/pgadmin4#7222]
When creating a function with the pgadmin function creation dialogue, arguments are created with double quotes in the function definition.
This happens when arguments are input without double quotes and in uppercase.

![definition](https://github.com/pgadmin-org/pgadmin4/assets/46869990/fc7ee31a-b39d-474b-af97-76fcaba34ab3)

The effect of this is, that when you insert the code for the function and make use of arguments without double quotes the execution will fail saying "ERROR: column »status« doesn't exist"
Please note: the column is output in lowercase, even if it is written in uppercase.

This happens on Windows 10 pro and
pgadmin 4, 6.18 and pgadmin 8.x

**To Reproduce**

1. Select a schema in pgadmin
2. in the Functions menu select "Create" -> "Function"
3. Fill in an argument in uppercase letter (e.g. STATUS)
Right click on the  created function and select 'Scripts' -> "CREATE script"
The shown script contains the input argument in double quotes: "STATUS"

**Expected behavior**
While creating a function and inputting an argument in uppercase pgadmin should not create arguments in double quotes.

**Error message**

FEHLER:  Spalte »status« existiert nicht
LINE 1: SELECT STATUS+4
               ^
QUERY:  SELECT STATUS+4
CONTEXT:  PL/pgSQL-Funktion decode(integer) Zeile 2 bei RETURN

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows-10-10.0.19045-SP0
 - Version: 6.18
 - Mode: Desktop
 - Browser Chromium 108.0.5359.95
 - Package type: standalone installer

**Comment by khushboovashi** [comment]
Hello @JanSladky65, Please provide the Function DDL and the error screenshot.

**Comment by JanSladky65** [comment]
DDL: 
![script](https://github.com/pgadmin-org/pgadmin4/assets/46869990/0ee6591c-ec55-406f-9f7e-3a6193179cf1)

ERROR: 
![error](https://github.com/pgadmin-org/pgadmin4/assets/46869990/ceb37e68-0b74-4108-8ad0-0e09ef1ad341)

**Comment by yogeshmahajan-1903** [comment]
Working fine.

**Comment by pravesh-sharma** [comment]
This has been the by-design behaviour of pgAdmin. Using GUI intentionally handles quoting for the user.
