### ISSUE TITLE
Support multiple nodes (in DB clusters) and allow using all connectionstring parameters ((RM#6961) #4728)

### ISSUE THREAD

**Issue by krisavi** [pgadmin-org/pgadmin4#7223]
**Describe the solution you'd like**

pgAdmin to have ability to declare "clusters" that are like database objects, but actually contain different DB nodes and have selectable target_session_attrs. Upon connection it should try to connect to DB node in cluster specified by target_session_attrs parameter. Reconnection to different node when switchover should happen on DB cluster level.

Loosely connected to RM#6961(https://redmine.postgresql.org/issues/6961) that was migrated over to #4728 and then kind of hijacked by some other issue before making it fixed. Initial issue is still not really fixed.

**Describe alternatives you've considered**

Tried to enter multiple hostnames in database hostname field and add target_session_attrs to connection parameters. But it seemed to give error that , is not allowed in hostname field.

**Comment by yogeshmahajan-1903** [comment]
@krisavi 
I am able to provide multiple hostname and able to connect. PFA SS.
<img width="1409" alt="Screenshot 2024-02-23 at 5 05 22 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/7251bcb0-aea1-4bc2-a3e8-1e263defba45">

**Comment by adityatoshniwal** [comment]
No response from the author. Closing.
