### ISSUE TITLE
different ID PRIMARY in diagramm and SQL Editor

### ISSUE THREAD

**Issue by rlsoft80** [pgadmin-org/pgadmin4#7229]
Hello,
There are a diffèrent KEY PRIMARY
In the diagramm : this is "id"
In the exportation SQL : this id "id_corps_metier"
I think, the export SQL take the first integer column after id
![sql](https://github.com/pgadmin-org/pgadmin4/assets/160749611/e1d35536-ce27-4667-b5cd-9679d637d5b8)
![schema](https://github.com/pgadmin-org/pgadmin4/assets/160749611/45f21ddd-4b78-43fb-bc35-a5a64f41d9ee)

**Comment by adityatoshniwal** [comment]
Hi @rlsoft80,
I tried all possible ways to reproduce this, and it works fine for me. Can you share some reproducible steps and pgerd file as well?
<img width="259" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/ec49b9bc-789a-4358-a909-bd737788822e">
```
BEGIN;


CREATE TABLE IF NOT EXISTS other.test
(
    id integer,
    id_corps integer,
    PRIMARY KEY (id)
);
END;

```

**Comment by rlsoft80** [comment]
Hello
I join the file pgerd
When I execute the script SQL, I have a bad primary key
Thank's for help

Romain LECOMTE

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-11/
Environment: macOs ventura 13.5.1
package: arm64
