### ISSUE TITLE
No password request for pgAdmin4

### ISSUE THREAD

**Issue by bgqn** [pgadmin-org/pgadmin4#7230]
when I downloaded pgAdmin per instructions, and restarted my computer, there is no option for me to input a password, and therefore no way for me to use pgAdmin. I also tried reinstalling the application. Is there another way to create a password?

**Comment by anilsahoo20** [comment]
Hi @bgqn 

Please provide us with some additional information like System configuration, pgAdmin 4 package type and version.

Please download the latest version of pgAdmin 4 from https://www.pgadmin.org/download/. And let us know if you are unable to use the pgAdmin 4.

**Comment by adityatoshniwal** [comment]
No response from the author. Closing.
