### ISSUE TITLE
Missing setup-web.sh on ubuntu jammy installation steps

### ISSUE THREAD

**Issue by alegaon** [pgadmin-org/pgadmin4#7240]
When running the steps detailed here: https://www.pgadmin.org/download/pgadmin-4-apt/ last step fails returning a not found message.

Error: sudo: /usr/pgadmin4/bin/setup-web.sh: command not found

Step i'm trying to run locally:

_# Configure the webserver, if you installed pgadmin4-web:
sudo /usr/pgadmin4/bin/setup-web.sh_

Linux installation details:
Linux user-pc 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yogeshmahajan-1903** [comment]
@alegaon 
Can you please check output of commands below - 
```
sudo apt list pgadmin4*
sudo ls -la /usr/pgadmin4/*
sudo ls -la /usr/pgadmin4/bin/*
```

**Comment by alegaon** [comment]
my output is:
[cid:f815639a-6dee-4037-a62c-04b60788f5dd]
[cid:b1cdd44c-46f0-42b8-872a-a1dfa3c7a538]
[cid:edc8b9d0-2dea-4b82-a25c-f2865e0e219c]
[cid:3f68fe97-0396-4cfe-af05-ae7f0252ef12]
[cid:b3e71415-af17-4165-a5fd-b26c83f7c10f]

________________________________
De: Yogesh Mahajan ***@***.***>
Enviado: lunes, 26 de febrero de 2024 01:57
Para: pgadmin-org/pgadmin4 ***@***.***>
Cc: ale ***@***.***>; Assign ***@***.***>
Asunto: Re: [pgadmin-org/pgadmin4] Missing setup-web.sh on ubuntu jammy installation steps (Issue #7240)


Assigned #7240<https://github.com/pgadmin-org/pgadmin4/issues/7240> to @alegaon<https://github.com/alegaon>.

**Comment by yogeshmahajan-1903** [comment]
@alegaon 
Is above output of commands that I given?

**Comment by alegaon** [comment]
hello,
yes,
I have executed the commands you provided, and those are the screenshots I sent in the previous email.

________________________________
De: Yogesh Mahajan ***@***.***>
Enviado: martes, 27 de febrero de 2024 00:57
Para: pgadmin-org/pgadmin4 ***@***.***>
Cc: ale ***@***.***>; Mention ***@***.***>
Asunto: Re: [pgadmin-org/pgadmin4] Missing setup-web.sh on ubuntu jammy installation steps (Issue #7240)


@alegaon<https://github.com/alegaon>
Is above output of commands that I given?

**Comment by akshay-joshi** [comment]
@alegaon 

The attached screenshots are not visible. Can you please attach it again?

**Comment by khushboovashi** [comment]
Closing the issue as no response from the author.
