### ISSUE TITLE
Unable to resize

### ISSUE THREAD

**Issue by centfox** [pgadmin-org/pgadmin4#7241]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When we resize the data editor window in query editor using the handle at the right bottom, it is possible to drag behind the windows task bar causing the save button or cancel button or the resize handle itself becoming inaccessible. As the window it self is not moveable only pressing esc key is the only option causing all the edits, if done, to be lost.

**To Reproduce**

As mentioned in the problem.

**Expected behavior**

Options:
1. Make the editor window moveable.
2. Provide scroll bars in the main window. 
3. Prevent resizing not to go behind windows taskbar.
4. Any other feasible option. 

**Screenshots**
![Screenshot (329)](https://github.com/pgadmin-org/pgadmin4/assets/43844631/00cfdadd-6512-4f1b-9009-5efd962ed105)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 8.3
 - Mode: Desktop

**Comment by RohitBhati8269** [comment]
Tested and verified on candidate build: [candidate-build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-18/)
Environment: MacOs
