### ISSUE TITLE
Custom backup still PgAdmin 4-8.3 still includes Owner statements when Do Not Include Owner & Privileges is enabled

### ISSUE THREAD

**Issue by JensVerlinden-UCLL** [pgadmin-org/pgadmin4#7245]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by akshay-joshi** [comment]
@JensVerlinden-UCLL 

We are unable to reproduce the bug when we take the backup command clearly shows "--no-owner" and "--no-privileges" options.

<img width="774" alt="Screenshot 2024-03-01 at 4 44 06 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/65b1c2be-3dec-44f8-8d8b-d5a7c1ef19c3">

**Comment by khushboovashi** [comment]
No response from the author so closing the issue
