### ISSUE TITLE
Rollback and commit button gets activated for sometime on getting any error for SQL query or cancelling the query.

### ISSUE THREAD

**Issue by anilsahoo20** [pgadmin-org/pgadmin4#7248]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

If we run some query and the some error occurs or if we cancel the query in between, the rollback and commit button gets activated for some seconds.

**To Reproduce**

1. Open query tool
2. Run any wrong query
4. See the rollback and commit button gets activated for some seconds

**Expected behavior**

These buttons should not get activated.

<img width="1249" alt="Screenshot 2024-02-28 at 9 22 41 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/122535205/bd73e1f7-3e94-43b7-8fbc-f60da18e79de">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by JyotiEdb** [comment]
@anilsahoo20 
All working fine,
But when we run wrong query and auto-commit is off, we get error, and after clicking commit button its shows massage of rollback, is it expected behaviour?

**Comment by anilsahoo20** [comment]
@JyotiEdb,
yes it is correct behaviour. Because there is nothing to commit as the error comes in. so the commit and rollback button will rollback always.

**Comment by JyotiEdb** [comment]
Tested and verified on snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-28/
