### ISSUE TITLE
Backup uses original username for shared server

### ISSUE THREAD

**Issue by mrtumnus** [pgadmin-org/pgadmin4#7255]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Changing the connection user for a shared server does not change the connection string.  A Backup operation uses the original user name of the user that shared the server.

**To Reproduce**

1. Login as user1
2. Register a shared server, with Connection Username set to user1
3. Logout
4. Login as user2
5. Open Properties of shared server
6. On Connection tab, change Username to user2
7. Connect to server (entering password for user2)
9. Right click on a database and select `Backup...`
10. Enter backup details and press `Backup`

**Expected behavior**

The username passed to `pg_dump` is the same as the connection's Username (user2)

**Error message**

```
pg_dump: error: connection to server at "db" (x.x.x.x), port 5432 failed: FATAL: password authentication failed for user "root"
```

**Screenshots**

Note the difference between the Username value `test` (user2) and the Connection String's `user=root` (user1).
![image](https://github.com/pgadmin-org/pgadmin4/assets/1738198/8b7b12f8-b4d6-4ad2-a71a-82a9b643f41e)

The process failure details:
![image](https://github.com/pgadmin-org/pgadmin4/assets/1738198/a827cea0-6fe3-4fe1-8213-29b5663f4dcb)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04.06
 - Mode: Server 
 - Browser: Brave v1.63.165 (Chromium 122.0.6261.94)
 - Package type: Docker dpage/pgadmin4:8.3

**Additional context**

Backend is PostgreSQL 15.6

**Comment by mrtumnus** [comment]
Looks like this might have the same root cause as 6084.  Does the shared server feature support unique user names?  I assumed it would because of the configurable Username field in the server properties, but maybe I'm misunderstanding the feature.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-27/
Environment: macOs ventura 13.5.1
package: pip wheel
