### ISSUE TITLE
Parameters , add client certificate hangs from PG admin UI 

### ISSUE THREAD

**Issue by roshvin** [pgadmin-org/pgadmin4#7257]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

when we try to upload client certificate , it hangs 

![image](https://github.com/pgadmin-org/pgadmin4/assets/11057966/b677cf27-a566-4f66-be02-2689244deed0)

![image](https://github.com/pgadmin-org/pgadmin4/assets/11057966/69cd3fc4-75d1-46d6-8221-a756a24737dd)

Error from container side

```

2024-03-04 05:50:42,794: ERROR  pgadmin:        400 Bad Request: The CSRF tokens do not match.
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 115, in validate_csrf
    raise ValidationError("The CSRF tokens do not match.")
wtforms.validators.ValidationError: The CSRF tokens do not match.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF tokens do not match.
192.168.0.118 - - [04/Mar/2024:05:50:42 +0000] "POST /file_manager/init HTTP/1.1" 400 120 "https://80--dev--docker--test.com/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

```

**To Reproduce**

1. run below command 

```
# docker run -p 80:80     -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com'     -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret'     -d dpage/pgadmin4

```

2. login to pgadmin , got to add server , click on parameters ,  add , client certificate 
3. 
![image](https://github.com/pgadmin-org/pgadmin4/assets/11057966/52880743-7d76-4a11-b94f-029da55a7883)
 

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by adityatoshniwal** [comment]
Hi @roshvin,
We're not able to reproduce the issue. Can you please share browser console logs?
If possible, please share the screen recording as well.

**Comment by anilsahoo20** [comment]
No reply from author, hence closing the issue.
