### ISSUE TITLE
Replace option in query tool edit menu is not working on windows/rpm package

### ISSUE THREAD

**Issue by pravesh-sharma** [pgadmin-org/pgadmin4#7262]
**Describe the bug**
When clicking on replace option in edit menu in query tool it is not opening.

**To Reproduce**

1. Open Query tool
2. Click on edit then click on replace

**Expected behavior**

Replace box should open.

 - OS: Rocky 8
 - Mode: Desktop
 - Package type:RPM

**Comment by EFrankel-ITEP** [comment]
Additional Info: The keyboard shortcut for Replace (Ctrl-Shift-F) has been assigned to Browser->Quick Search. Reassigning it does not allow it to bring up Replace.

**Comment by EFrankel-ITEP** [comment]
Also, I'm seeing a new possibly-related behavior in the Query Tool that I don't see in any of the release notes. If I highlight something in the query, all instances of that thing are also highlighted. It looks like the beginning of one of those features where you can highlight something and then operate on all instances of it, but doesn't seem to have any actual effect at this time. Maybe the initial foray into something meant to add another way to search/replace that is interfering with the existing method?

**Comment by brsa** [comment]
Stopped working in v8.4 on Ubuntu as well. Neither the keyboard shortcut, nor the menu item bring up the "Replace" dialog. (While the "Find" dialog still works.) I assume that's all in connection with https://github.com/pgadmin-org/pgadmin4/issues/7268 and https://github.com/pgadmin-org/pgadmin4/issues/5083 . The query tool is largely broken ATM.

**Comment by adityatoshniwal** [comment]
It turns there is some mismatch in the actual shortcut and what is mapped in UI. I tried Ctrl+Alt+F and replace opens.

**Comment by adityatoshniwal** [comment]
> Also, I'm seeing a new possibly-related behavior in the Query Tool that I don't see in any of the release notes. If I highlight something in the query, all instances of that thing are also highlighted. It looks like the beginning of one of those features where you can highlight something and then operate on all instances of it, but doesn't seem to have any actual effect at this time. Maybe the initial foray into something meant to add another way to search/replace that is interfering with the existing method?

@EFrankel-ITEP  I am removing the "highlight all matches on selection" for now. You can create a feature request for "Change all occurrences of selection".

**Comment by brsa** [comment]
> @EFrankel-ITEP I am removing the "highlight all matches on selection" for now. You can create a feature request for "Change all occurrences of selection".

@adityatoshniwal I wouldn't mind to have the feature of highlighting matches of the current selection. It just needs to be documented, and the release notes should mention something.
Ideally, there is an option to turn it off/on.Should I create a feature request for this?

**Comment by EFrankel-ITEP** [comment]
I don't require or object to the feature. I just noticed it appeared at the same time as the Replace shortcut broke and wondered if it might be a related symptom.

**Comment by adityatoshniwal** [comment]
There was an upgrade of lib used for the editor part (Upgrade CodeMirror from version 5 to 6.). The issues occurring are mostly because of this change.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-25/
Environment: Debian 11
package: Python package

**Comment by KeterSCP** [comment]
Shouldn't the documentation be updated accordingly? https://www.pgadmin.org/docs/pgadmin4/8.12/keyboard_shortcuts.html
