### ISSUE TITLE
pgadmin is very cumbersome to use for testing and development

### ISSUE THREAD

**Issue by mrbesen** [pgadmin-org/pgadmin4#7267]
**Describe the bug**
I use pgadmin regularly in a docker-compose setup with something like this:

-  an application container
-  postgres container
- pgadmin4 container to check the db and debug the app

I have a pgadmin-server.json config that i load to configure the server.

Now i would like to just open my browser on the specified url and view my tables. But pgadmin4 has other plans:
first i need to log in with an dummy account. Why can that not just be disabled, when in docker or with an env variable? Its just very annoying to enter this login that serves no purpose (at least in this use case). Now i am logged in. But the first time i start the container i need to enter the server pw again. Why can i not set that with the server.json? There is the `PasswordExecCommand` option, but it is not evaluated, when used in a container. At least it does not work and does not allow me to set it in the ui (greyed out). So this adds another frustration to just starting and using pgadmin4. I think if i choose to not use the pgadmin4 account and have an unsecured webinterface and have my server automatically setup with my password, pgadmin4 should let me. If i have enough knowledge to setup a docker-compose setup and that stuff i should be trusted with that decision.

**Error message**
n/a

**Screenshots**

![grafik](https://github.com/pgadmin-org/pgadmin4/assets/8640309/ab661b17-8e30-4634-b656-4fa84243e322)

My `server.json`:
```json
{
	"Servers": {
		"1": {
			"Name": "db",
			"Group": "Servers",
			"Port": 5432,
			"Username": "user",
			"Host": "db",
			"SSLMode": "prefer",
			"MaintenanceDB": "postgres",
			"PasswordExecCommand": "echo -n 'DTBoN1pEY9qK'"
		}
	}
}
```

**Desktop (please complete the following information):**
 - OS: linuxmint
 - Version: 8.4
 - Mode: Server
 - Browser: Firefox 123
 - Package type: docker container image

**Additional context**
n/a

**Comment by adityatoshniwal** [comment]
Hi @mrbesen,
Docker/Container deployment is intended for server mode. A server mode is something where multiple users can access pgAdmin using pgAdmin username/password.
Although we don't recommend/test, if you still want to run docker as desktop then try below:
```sh
docker run -p 80:80 \
    -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' \
    -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
    -e 'PGADMIN_CONFIG_SERVER_MODE=False' \
    -e 'PGADMIN_CONFIG_DESKTOP_USER="user@domain.com"' \
    -d dpage/pgadmin4
```
Regarding `PasswordExecCommand`, it is disabled by default in server mode True for security reasons. You can enable using config - `ENABLE_SERVER_PASS_EXEC_CMD` (https://www.pgadmin.org/docs/pgadmin4/8.4/config_py.html). But if you're using desktop mode (server mode False) then it will be enabled.

**Comment by mrbesen** [comment]
To disable the Master password i also needed `PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED="False"` but with that it seems to work.
