### ISSUE TITLE
Release 8.4 has broken multiple features of the Query Tool for me

### ISSUE THREAD

**Issue by brsa** [pgadmin-org/pgadmin4#7268]
Since I installed pgAdmin4 v8.4 from https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal yesterday, multiple editing / formatting features of the Query Tool stopped working for me.

The keyboard shortcut [strg][shift][k] used to trigger code formatting (of selected text). Now it **deletes** selected text, and formats the rest (in new and mysterious ways).
Notably, selecting text now highlights all matches in the whole text in green. No idea what that does (or is supposed to do) but it suggests more underlying changes. Nothing in the release notes about that.

The very useful feature of multi-line edit after marking a multi-line selection with [alt][click & drag] has stopped working. In fact, pressing [alt] does nothing to the mouse cursor now; used to transform it into cross-hairs. Nothing in the release notes about that.

Code formatting has been broken for me since the previous release 8.3, when it started adding line breaks that I do not want, without an obvious way to stop that. Again, nothing obvious in the release notes. Limited investigation suggests it might all be connected to this?

https://github.com/pgadmin-org/pgadmin4/issues/5083

I tried to downgrade to pgAdmin4 v8.2, but failed. So I am hoping the mist will clear ..

System info:

Version 8.4
Application Mode Desktop
Current User pgadmin4@pgadmin.org
NW.js Version 0.77.0
Browser Chromium 114.0.5735.91
Operating System Linux-5.15.0-100-generic-x86_64-with-glibc2.29
pgAdmin Database File /home/erwin/.pgadmin/pgadmin4.db
Log File /home/erwin/.pgadmin/pgadmin4.log

Regards
Erwin

**Comment by udit47** [comment]
> The very useful feature of multi-line edit after marking a multi-line selection with [alt][click & drag] has stopped working. In fact, pressing [alt] does nothing to the mouse cursor now; used to transform it into cross-hairs. Nothing in the release notes about that.

Facing the same issue for Windows Desktop Application as well.
OS : Windows 11

**Comment by adityatoshniwal** [comment]
Please try the shortcut Alt+Ctrl+F for replace. There is a mismatch in UI mapping.

**Comment by adityatoshniwal** [comment]
> Code formatting has been broken for me since the previous release 8.3, when it started adding line breaks that I do not want, without an obvious way to stop that. Again, nothing obvious in the release notes. Limited investigation suggests it might all be connected to this?
> 

@brsa  Please report this as a separate issue. It doesn't seem related.

**Comment by robpoyntz** [comment]
One of my most-used keyboard shortcuts, ctrl+enter to execute selected SQL, no longer works for me. It now adds an empty line, and executes all of the text in the query window, ignoring the text selection

**Comment by adityatoshniwal** [comment]
> One of my most-used keyboard shortcuts, ctrl+enter to execute selected SQL, no longer works for me. It now adds an empty line, and executes all of the text in the query window, ignoring the text selection

@robpoyntz Ctrl+Enter was never mapped to execute SQL. F5 is to execute SQL.

**Comment by robpoyntz** [comment]
> > One of my most-used keyboard shortcuts, ctrl+enter to execute selected SQL, no longer works for me. It now adds an empty line, and executes all of the text in the query window, ignoring the text selection
> 
> @robpoyntz Ctrl+Enter was never mapped to execute SQL. F5 is to execute SQL.

By default it may be F5, but I've set a custom mapping in Preferences | Query Tool | Keyboard shortcuts to use Ctrl+Enter. This no longer works, when it did in 8.3

**Comment by pravesh-sharma** [comment]
Find below issues while testing:

1. The toggle comment shortcut is not working. However, I can click on the menu option and it works.
2. No shortcut is working on the debugger tool and also on the tooltip shortcut is not visible which was there on 7.8.

**Comment by adityatoshniwal** [comment]
> _I also miss the KEYBOARD - functions for controlling the pgAdmin4 integrated pgplsql debugger: In some of the latest earlier versions I could use [ALT]+i to step into a function, and [ALT]+o to step over for example. Both of them were indicated by tooltip when doing mouse-over in the corresponding toolbar buttons._
> 
> Who ever is working on this nice, 'new' python piece of 'pgAdmin4':
> 
> * Please be so good as to consider that the majority of users who were born before 1995 and grew up without a mouse are about 5 times faster at using the computer with a keyboard than if you force us to use a mouse for regularly required operations.
> * pgAdmin4 is a ongoing textbook failure in this regard. This applies not only to the shortcuts mentioned but also (and still) to the keyboard usability of the navigation trees.
> * As a switcher from Oracle, I came to the best version of pgAdmin3 and gradually became enthusiastic about PostgreSQL. pgAdmin4 now has put a huge damper on this (even though I still think PostgreSQL itself is great).
> 
> _Sorry for showing up the 'badasses' here, but the pot is more then full in this context, and steam is still not out! It doesn't mean that I disregard the work you put in here - I appreciate it in spite of everything. It's just that sometimes it's hard to bear when such important little things as the user interface look more like the first work of an intern than the expertise of an experienced developer._

Shortcuts in debugger is broken since v8.0. This went unnoticed. We'll fix this in upcoming release.

**Comment by pravesh-sharma** [comment]
Issue resolved, verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-27/).

**Comment by FJo69** [comment]
thanks a lot for solving Debugger Shortcut Toolbar issue. It works fine again now!

**Comment by mkfrohme** [comment]
I just upgraded from 9.6 to 9.15 and the keyboard shortcut no longer works, nor has the documentation caught up ( it still has Ctrl + Shift + f for **both** quick search **and** replace in the SQL Editors section.

What is the recommended solution?

Yes, I know this is closed - I'll open another ticket if needed.
