### ISSUE TITLE
Schema Diff: View Triggers missing

### ISSUE THREAD

**Issue by fjf2002** [pgadmin-org/pgadmin4#7271]
View triggers don't seem to get compared properly.

**To Reproduce**

* On two servers, execute
```sql
create view myview as select 42;

create function my_trigger_func() returns trigger language plpgsql as $$
begin
	return null;
end
$$
```

* On just the first server, execute
```sql
CREATE TRIGGER mytrigger INSTEAD OF DELETE ON myview FOR EACH ROW EXECUTE FUNCTION my_trigger_func();
```

* Run Schema diff.

**Expected behavior**

Schema Diff should tell me that the Trigger is missing from the second server, but fails and reports "no difference found".

**Desktop (please complete the following information):**
 - OS: pgadmin docker hub container dpage/pgadmin4:8.4
 - Mode: Server
 - Browser Chrome

**Comment by anilsahoo20** [comment]
These below issues I noticed randomly, 

1. Schema diff source schema or target schema shows the default database's schema list not the selected database's schema list.
2. If target has same object name and all the details except a small change as the source object, the target, does not shows the SQL, only source sql is being shown.
3. If a object is not present in target but present in source, the diff SQL must show target schema qualified SQL, but it shows source schema qualified SQL.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-28/
Environment: macOs ventura 13.5.1
package: arm64
