### ISSUE TITLE
[BUG]Too many redirects

### ISSUE THREAD

**Issue by yijiangchengming** [pgadmin-org/pgadmin4#7274]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
After being deployed in CDN, the browser responded with too many redirects. I deployed the application on k8s, ingress-nginx processed the traffic entrance, and used http to access the backend service. The application did not enable TLS. When I use hosts to specify that k8s traffic does not go through the CDN it works fine. It cannot be accessed after connecting to the CDN. The following is the log of the Pod.
I don't know how multiple reverse proxies should set up these pgAdmin X-Forwarded-* Configuration in my CDN traffic path, including ingress-nginx if additional configuration is required.
Browser(https)--cdn(https)--ingress-nginx(http)--service
**Error message**
ip.ip.ip.ip - - [12/Mar/2024:13:05:42 +0000] "GET /login?next=%2Fbrowser%2F HTTP/1.1" 302 205 "https://pgadmin.example.com/login?next=%2Fbrowser%2F" 
ip.ip.ip.ip - - [12/Mar/2024:13:05:42 +0000] "GET /browser/ HTTP/1.1" 302 237 "https://pgadmin.example.com/login?next=%2Fbrowser%2F"
ip.ip.ip.ip - - [12/Mar/2024:13:05:42 +0000] "GET /login?next=%2Fbrowser%2F HTTP/1.1" 302 205 "https://pgadmin.example.com/login?next=%2Fbrowser%2F"
ip.ip.ip.ip - - [12/Mar/2024:13:05:43 +0000] "GET /browser/ HTTP/1.1" 302 237 "https://pgadmin.example.com/login?next=%2Fbrowser%2F"
ip.ip.ip.ip - - [12/Mar/2024:13:05:43 +0000] "GET /login?next=%2Fbrowser%2F HTTP/1.1" 302 205 "https://pgadmin.example.com/login?next=%2Fbrowser%2F"

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/30022966/6bdb30db-8763-4a25-b4fe-fe818ebb76be)
![image](https://github.com/pgadmin-org/pgadmin4/assets/30022966/3e6303ac-ea13-4c4b-b419-c30384ddf0a4)
![image](https://github.com/pgadmin-org/pgadmin4/assets/30022966/4a2eea33-8966-4384-b84b-3417cac9c6c2)

**Additional context**

**Comment by khushboovashi** [comment]
Hi @yijiangchengming, try to set PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION = False in your k8s config file and try again
