### ISSUE TITLE
Debug of a function not working properly

### ISSUE THREAD

**Issue by josesalge** [pgadmin-org/pgadmin4#7275]
I believe as of version 8.4 when I debug a function, the screen editor does not follow the position the function is currently in (it does not go down as i follow the function) 

I tested in another computer with 8.3 and it worked fine

Version: 8.4
Desktop mode
Ubuntu 22.04

**Comment by khushboovashi** [comment]
Hi @josesalge, can you please provide the screen recording?

**Comment by adityatoshniwal** [comment]
@josesalge We didn't receive any email. Please share the recording here.

**Comment by josesalge** [comment]
@adityatoshniwal Please find attached the recording. It happens with every function, not one in particular
[Screencast from 03-22-2024 08:42:27 AM.webm](https://github.com/pgadmin-org/pgadmin4/assets/114332179/ee22875a-5c2d-4ac9-a6d1-d44bb96a144c)

**Comment by akshay-joshi** [comment]
Tested on the snapshot build 2024-04-24
