### ISSUE TITLE
XSS vulnerability in /settings/store endpoint

### ISSUE THREAD

**Issue by felixtoe** [pgadmin-org/pgadmin4#7282]
**Describe the bug**

XSS vulnerability in /settings/store endpoint

**To Reproduce**

1. Use a man-in-the-middle proxy like `mitmproxy`
2. Intercept POST request to /settings/store (is e. g. being called when resizing left menu bar)
3. Modify the request body like in the attached screenshot (`... \"children\": [{\"id\":\"+3'-alert('XSS')-'\", ...`) and resume request
4. Reload pgAdmin homepage. Alert box is popping up.

Tested with pgAdmin4 8.0 and 8.3.

**Screenshots**

Are attached :)
![XSS1](https://github.com/pgadmin-org/pgadmin4/assets/26927719/c9dcdd10-e7fa-4a9e-a300-f9f934636bbf)
![XSS2](https://github.com/pgadmin-org/pgadmin4/assets/26927719/0cd05831-805e-46a7-908b-7d5aabc71727)

**Comment by khushboovashi** [comment]
Issue has been fixed.
