### ISSUE TITLE
SQL formatting eats line under the cursor

### ISSUE THREAD

**Issue by limpus64** [pgadmin-org/pgadmin4#7283]
* pgAdmin 8.4 [docker]

Hitting [Ctrl][Shift][k] on my platform starts SQL formatting. If I hit that shortcut, SQL formatting apparently works — with a caveat: the line under the cursor is removed. In effect, it works only correctly if I place the cursor in a blank line outside my query. Please see my examples below.

Is it possible that shortcut settings (for SQL formatting and remove line) have gotten mixed up here? I can't find any place where the shortcut [Ctrl][Shift][k] has been set.

Original1 – the ⁞ marks the point of the caret
``` sql
SELECT id, col1, col2, col3
⁞     , min(amount) FILTER (WHERE amount IS NULL) AS a_null
     , min(brand) FILTER (WHERE brand  IS NULL) AS b_null
  FROM   tbl
 GROUP BY id;
```
Result1 – the ⁞ marks the point of the caret
``` sql
⁞SELECT
    id,
    col1,
    col2,
    col3,
    min(brand) FILTER (
        WHERE
            brand IS NULL
    ) AS b_null
FROM
    tbl
GROUP BY
    id;
```
Original2 – the ⁞ marks the point of the caret
``` sql
⁞SELECT 'today'::date - '1964-08-01'


```
Result2 – the ⁞ marks the point of the caret
``` sql
⁞
```
This might be a duplicate of #7268

**Comment by pravesh-sharma** [comment]
Issue resolved. Verified on latest snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-25/)

Note - After the code mirror version update default shortcut for format SQL is now `ctrl/cmd+k`

Env:
OS - macOS Sonoma and Rocky 9
Mode - Desktop and server
