### ISSUE TITLE
servers.json password error

### ISSUE THREAD

**Issue by samratdgreat** [pgadmin-org/pgadmin4#7284]
I am deploying the pgadmin in my kubernetes cluster. 

deployment.yaml file

   containers:
      - image: postgres:8.4
        env:
         -  name: PFADMIN_SERVER_JSON_FILE
            value: /pgadmin4/servers.json
        volumeMounts:
        -   name: server-config
            mountPath: /pgadmin4/servers.json
            subPath: servers.json
        -   name: password-config
            mountPath: /var/lib/storage/pgpass
            subPath: pgpass
   volumes:
     -  name: password-config
        configMap:
           name: pgad-password-config
    -  name: pgad-server-config
        configMap:
           name: server-config

configmap for servers.json
  kind: ConfigMap
  apiVersion: v1
  metadata:
     name:  pgad-server-config
  data:
     servers.json:  |
  {
  "Servers": {
    "1": {
      "Name": "My Postgres Server",
      "Group": "Servers",
      "Host": "host.docker.internal",
      "Port": 5432,
      "MaintenanceDB": "postgres",
      "Username": "postgres",
      "PassFile": "/var/lib/storage/pgpass",
      "SSLMode": "prefer",
      "ConnectionTimeout":10,
      "SavePassword": true,
    }
  }
}

configmap for pgpass
 kind: ConfigMap
  apiVersion: v1
  metadata:
     name:  password-config
  data:
     pgpass:  |
     hostname:port:database:username:password

The issue is when i log in to the postgres, i can see the server but it is prompting me to enter the password so it is not able to read the one i supplied.

i get this error in the UI: connection failed: fe_sendauth: no password supplied

**Comment by akshay-joshi** [comment]
Hi @samratdgreat 

We have made changes to the structure of the JSON file after changing the Server dialog. Could you kindly adjust your JSON file to match the following format?"

{
"Servers": {
"1": {
"Name": "My Postgres Server",
"Group": "Servers",
"Host": "host.docker.internal",
"Port": 5432,
"MaintenanceDB": "postgres",
"Username": "postgres",
"SavePassword": true,
"ConnectionParameters": {
    "passfile": "/var/lib/storage/pgpass",
    "sslmode": "prefer",
    "connection_timeout":10
}
}
}
}

**Comment by samratdgreat** [comment]
Finally, I am able to connect to the server with this docker-compose.yml
version: "3.8"

services:
  pgadmin:
    container_name: dev-pgadmin4
    restart: always
    image: dpage/pgadmin4:8.3
    ports:
      - "9000:80/tcp"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@edb.com
      PGADMIN_DEFAULT_PASSWORD: adminedb
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json
    entrypoint: >
        /bin/sh -c "
        mkdir -p /var/lib/pgadmin/storage/user_edb.com/;
        echo '44.201.206.164:5431:postgres:postgres:<pass>' >> /var/lib/pgadmin/storage/user_edb.com/.pgpass;
        echo '' >> /var/lib/pgadmin/storage/user_edb.com/.pgpass;
        chown pgadmin:root /var/lib/pgadmin/storage/user_edb.com/.pgpass;
        chmod 600 /var/lib/pgadmin/storage/user_edb.com/.pgpass;
        /entrypoint.sh
        "
        
        
        
However, I am only able to access the db with name postgres inside that server. When I provided the password manually through UI, i had an option to save password and I was able to access any dbs within that server. Now, I can only access one db (postgres)

**Comment by samratdgreat** [comment]
Okay we can close this issue.

What's happening is that if you have several dbs inside a server then you might face issue to not able to access other db beside the db named 'postgres'.

so i went ahead and changed the /pgpass fille as 
localhost:5432:*:postgres:your_password

Previously i had the db name and replaced it with *

**Comment by mecampbellsoup** [comment]
FTR I don't think `"SavePassword": true` is a valid option for the DB JSON config: https://github.com/pgadmin-org/pgadmin4/blob/35d585251a0922f3c66f0ee33fbee4c1cd6105a6/web/pgadmin/utils/__init__.py#L494-L539
