### ISSUE TITLE
400 From trying to edit volumes

### ISSUE THREAD

**Issue by JustRedTTG** [pgadmin-org/pgadmin4#7288]
**Describe the bug**

Duplicate/Edit a container, only editing the volumes fails

**To Reproduce**

1. Go to container of choice
2. Click on duplicate/edit
3. Edit bind volume
4. Update container (400 error shows shortly)

**Expected behavior**

Should Edit the volumes

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/46073266/8c3f052b-26ad-4854-a768-9e27483d2d1b)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version: latest
 - Mode: server
 - Browser (if running in server mode): opera gx
 - Package type: container

**Comment by adityatoshniwal** [comment]
Hi @JustRedTTG,
This doesn't look like a pgAdmin issue to me.

**Comment by JustRedTTG** [comment]
It appears the entire advance section doesn't work simply cause the main section on the top is unchanged, it means I have to create a new container by changing the name of it or by changing anything else like the image version and so on for the there to be no error updating the container, cause I only noticed this issue when trying to make changes to the advance section without making changes to the main section

**Comment by adityatoshniwal** [comment]
Not a pgAdmin issue. Closing.

**Comment by JustRedTTG** [comment]
Wrong repo my bad, will forward it to the correct repo
