### ISSUE TITLE
Azure Oauth2 cannot integrate - the claim 'email' is required to login

### ISSUE THREAD

**Issue by lyubomirk** [pgadmin-org/pgadmin4#7292]
I am trying to integrate pgAdmin with Azure Oauth2. I am deploying pgAdmin in Azure Kubernetes Service as a deployment. I have config_local.py as a configmap, which is mounted in the correct location: /pgadmin4/config_local.py

Here is the configmap I am using: 
```

  AUTHENTICATION_SOURCES = ['oauth2','internal']

  OAUTH2_CONFIG = [
      {
          # The name of the of the oauth provider
          'OAUTH2_NAME': 'azure',
          # The display name
          'OAUTH2_DISPLAY_NAME': 'azure',
          # Oauth client id
          'OAUTH2_CLIENT_ID': 'app_registration_client_id',
          # Oauth secret
          'OAUTH2_CLIENT_SECRET': 'app_registration_secret',
          # URL to generate a token,
          'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/token',
          # URL for authentication,
          'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/authorize',
          # server metadata url
          'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/<TENANT_ID>/v2.0/.well-known/openid-configuration',
          # Oauth base url
          'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
          # Name of the Endpoint, ex: user
          'OAUTH2_USERINFO_ENDPOINT': 'me',
          # Oauth scope. Note that an 'email' claim is required in the resulting profile
          'OAUTH2_SCOPE': 'User.Read openid email profile',
          # The claim which is used for the username.
          # I had to specify this, because if I left it blank, I was receiving an error message that this value is empty and it is required. 
          'OAUTH2_USERNAME_CLAIM': 'email ',
          # UI button colour, ex: #0000ff
          'OAUTH2_BUTTON_COLOR': '#0000ff',
      }
  ]
```

In Azure I have created an app registration with redirect URIs for localhost:8080 (for now, pgAdmin will be used by port-forwarding). I have enabled the app registration to issue Access tokens and ID tokens and added "email" as a valid claim. I also added "email", "openid", "profile" and "User.Read" as permitted API endpoints for Microsoft Graph. 

When I deploy pgAdmin to the cluster, I can see the "Login with azure" button, but when I click it, it says 

> The claim 'email' is required to login into pgAdmin. Please update your OAuth2 profile.

I have tried following different online guides and articles, but none of the resources I could find were able to solve my issue.

**Comment by yogeshmahajan-1903** [comment]
@lyubomirk 
You can override username_claim by specifying value for key 'OAUTH2_USERNAME_CLAIM' in config_local.py. By default it takes email.
Depending on your Azure configuration , you can set the value for OAUTH2_USERNAME_CLAIM. Please refer [this](https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference) link or [this](https://learn.microsoft.com/en-us/entra/identity-platform/optional-claims).
Also what is your pgadmin version?

**Comment by lyubomirk** [comment]
I have an optional claim called "email" in my Azure token configuration (as described in the second link). I also tried it with preferred_username, but I get the same error message. 
I am using the docker image dpage/pgadmin4:8.4, so the pgadmin version is 8.4

**Comment by yogeshmahajan-1903** [comment]
@lyubomirk 
You are getting above error because profile received by OAuth2 client does not have 'preferred_username' key. Can you please share complete pgadmin logs?

**Comment by lyubomirk** [comment]
@yogeshmahajan-1903 
![image](https://github.com/pgadmin-org/pgadmin4/assets/140058557/1a29ca44-0843-4dc5-8ab0-b9bbddeded27)
The obfuscated token seems to be incomplete, because I cannot manage to decode it. I am not sure what claims it has inside. 

I did put the custom claims email and preferred_username in my configurations though:
![image](https://github.com/pgadmin-org/pgadmin4/assets/140058557/ec104a33-5469-451f-92a9-deeb00ac409f)
(Please ignore that it says "The claim 'user' is required... "I have tried with both 'email' and 'preferred_username', but it doesn't work with them either) 

Also, I am sure that pgAdmin is using the correct app registration, because I can see the login attempts in the Enterprise Application, which weirdly enough are logged as successful.

**Comment by yogeshmahajan-1903** [comment]
@lyubomirk 
I checked Azure token. It contains key 'mail' not 'email', hence you are not able to login. Please try with
 ```
'OAUTH2_USERNAME_CLAIM': 'mail'
```
It should work.

**Comment by lyubomirk** [comment]
@yogeshmahajan-1903 
Yes, it works now... I couldn't find the key 'mail' anywhere in the Azure documentation. I don't know where you found it, but thank you very much for this! 

Also, if anyone else has a similar issue - the DEBUG logs of pgAdmin do not output the token key-value pairs until you hit a valid key. So if it doesn't work with 'mail', enable the DEBUG logs and see which keys are configured in your case. For me it worked with this: 
`'OAUTH2_USERNAME_CLAIM': 'userPrincipalName'`
