### ISSUE TITLE
Enhancement - Query Tool - Run SQL Code From non-contiguous highlighted code blocks

### ISSUE THREAD

**Issue by ChristopherMaurer** [pgadmin-org/pgadmin4#7293]
In the SQL window of the Query Tool, if I highlight a block of SQL, PGADMIN4 will try to run just the SQL within the highlighted block.  This is a very useful debugging tool to isolate and debug subqueries of a larger query,

In the Windows operating system I can highlight a second block of code  by holding down the CTRL key while I click and drag the mouse over that second block.  However, PGAdmin4 will only try to run the last block you highlighted, not all blocks together.  Here is an  (considerably simplified) example that illustrates the issue:

Here is a simple, somewhat nonsensical Union query that utilizes a Common Table Expression.  It runs without error in my Query Tool window of PGAdmin4 ver. 8.4 executing PostgreSQL ver. 16.
![image](https://github.com/pgadmin-org/pgadmin4/assets/142697362/a069b4c5-aecd-4784-ba9b-92b04f617c05)

If I highlight the last line and try to run I, of course, get an error  because the CTE definition is not included:

![image](https://github.com/pgadmin-org/pgadmin4/assets/142697362/db16f527-f698-4f02-a18f-38c1f93afca7)

Now if I hold down the CTRL key and click-drag the mouse over the CTE code, I get a second highlighted area.  Taken together, these two blocks are valid SQL code and should run without error, but it does not - I get the same error:

![image](https://github.com/pgadmin-org/pgadmin4/assets/142697362/cb907248-d21c-4b4f-aa62-d960110f1bed)

Notice that the error says it occurred on line 1 - the topmost block of text was not included for the execution.

If I copy this to the clipboard and paste it into a new blank Query Tool window, both blocks come over correctly and the code executes correctly.

![image](https://github.com/pgadmin-org/pgadmin4/assets/142697362/44c020f8-62ea-4875-aafa-4c2e1d6493af)

**Comment by pravesh-sharma** [comment]
Feature implemented. Tested on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-09-02/).

Env:
OS - macOS Sonoma (14.6.1)
Mode - Desktop
