### ISSUE TITLE
Quoting with double $-sign ($$) turns the rest of sql-code visual as text, till corresponding close $$

### ISSUE THREAD

**Issue by casparsch** [pgadmin-org/pgadmin4#7294]
**Describe the bug**
Since release 8.4 I experience following:
The text for writing a function, procedure or anonymous block is visualized as text when it comes across a "$$"-token
This textual visualization remains till the corresponding $$ at the end. This obstructs e.g. the highlighting of keywords and texts.
If there is anything in between the two $-characters (opening and closing) the keywords and texts are again highlighted 
I would like to revert to the $$ ... $$ to have a similar visualization as $anything$ ... $anything$ as it was before release 8,4

**To Reproduce**

1. Open a "Query Tool"
2. Type: 
```
DO $$
DECLARE
    _txt text := 'some text';
BEGIN
END;
$$;
```
3. See the visualization of the code
4. Put for example a: "x" between the adjacent $-characters. Both at the start and at the end.
5. Look at the visual difference.

**Expected behavior**
I would like to have the visualization of $x$ ... $x$ when using $$ ... $$

**Error message**
No technical error but visual "error"

**Screenshots**
![Screenshot from 2024-03-18 17-01-48](https://github.com/pgadmin-org/pgadmin4/assets/121792923/767a5219-ab84-4b6f-8c81-2ed80221f1f1)

**Desktop (please complete the following information):**
It is on a: "rocky-linux 9" operating system.

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/splendid/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin
(https://github.com/pgadmin-org/pgadmin4/assets/121792923/50f52290-0509-4dcd-b018-f8d2b04ccf62)
4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - SHELL: /bin/bash
  - SESSION_MANAGER: local/unix:@/tmp/.ICE-unix/11696,unix/unix:/tmp/.ICE-unix/11696
  - HISTCONTROL: ignoredups
  - XDG_MENU_PREFIX: gnome-
  - GTK_IM_MODULE: ibus
  - HOSTNAME: localhost
  - HISTSIZE: 1000
  - GNOME_SHELL_SESSION_MODE: classic
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - XMODIFIERS: @im=ibus
  - DESKTOP_SESSION: gnome-classic
  - PWD: /home/splendid
  - XDG_SESSION_DESKTOP: gnome-classic
  - LOGNAME: splendid
  - XDG_SESSION_TYPE: wayland
  - MODULESHOME: /usr/share/Modules
  - MANPATH: /usr/share/man:
  - SYSTEMD_EXEC_PID: 11712
  - XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.GET0K2
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - GDM_LANG: en_US.UTF-8
  - __MODULES_SHARE_MANPATH: :1
  - HOME: /home/splendid
  - USERNAME: splendid
  - LANG: en_US.UTF-8
  - XDG_CURRENT_DESKTOP: GNOME-Classic:GNOME
  - WAYLAND_DISPLAY: wayland-0
  - INVOCATION_ID: b82749762f1242048070bd2902ece73a
  - MANAGERPID: 11585
  - GJS_DEBUG_OUTPUT: stderr
  - GNOME_SETUP_DISPLAY: :1
  - XDG_SESSION_CLASS: user
  - LESSOPEN: ||/usr/bin/lesspipe.sh %s
  - USER: splendid
  - MODULES_RUN_QUARANTINE: LD_LIBRARY_PATH LD_PRELOAD
  - LOADEDMODULES: 
  - DISPLAY: :0
  - SHLVL: 0
  - QT_IM_MODULE: ibus
  - XDG_RUNTIME_DIR: /run/user/1000
  - __MODULES_LMINIT: module use --append /usr/share/Modules/modulefiles:module use --append /etc/modulefiles:module use --append /usr/share/modulefiles
  - DEBUGINFOD_URLS: https://debuginfod.centos.org/ 
  - which_declare: declare -f
  - JOURNAL_STREAM: 8:41178
  - XDG_DATA_DIRS: /home/splendid/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
  - PATH: /usr/pgsql-15/bin/:/home/splendid/.local/bin:/home/splendid/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
  - MODULEPATH: /etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
  - GDMSESSION: gnome-classic
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - MAIL: /var/spool/mail/splendid
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 15863
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - MODULES_CMD: /usr/share/Modules/libexec/modulecmd.tcl
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 36651
  - PGADMIN_INT_KEY: c030d167-616e-4308-b728-7beaf3b7f79c
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

**Additional context**
-- None yet

**Comment by brsa** [comment]
Plain dollar-quoting now treats the content as string constant. Dollar-quotes with nested token are transparent so that code highlighting works for function bodies et al. I consider this helpful.

**Comment by adityatoshniwal** [comment]
I have raised this to upstream - https://discuss.codemirror.net/t/code-inside-do-block-treated-as-string-postgresql-dialect/8005

**Comment by adityatoshniwal** [comment]
@casparsch As per the docs - https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING, it is in fact a string. And so it is treated as string only.
The fact that it used to work differently in previous pgAdmin version doesn't means it was correct.

**Comment by casparsch** [comment]
I just read the documentation and that is perfectly alright. It states that the tag in between the $-tokens is optional.
However I was looking at pgAdmin's visualization of that. The issue raised was not on the correctness of the implementation within postgres. 
So _why_ is **$$** treated different to **Stag$**?

Furthermore if there is a single quote within the _nested_ dollar-quoted-text (like in the documentation: "`$SomeTag$Dianne's horse$SomeTag$`") the text up-to the single quote is visual non-text and after the single quote becomes visual as text.
![Screenshot from 2024-03-21 09-39-21](https://github.com/pgadmin-org/pgadmin4/assets/121792923/54d29102-fa68-4a9a-b32b-9ab61c5e6f40)
To me this is inconsistent visualization of strings.

I would suggest following:

- Revert to the previous (before pgAdmin4 release 8.4-1) syntax-highlighting of dollar-quoting
- For **nested** dollar-quoting treat the string between the open and corresponding close nested-dollar-quote, visually as text.

**Comment by adityatoshniwal** [comment]
@casparsch I will raise the bug to upstream CodeMirror repo. But I'm afraid it won't change the fact how $ quotes will be treated(as strings). You can follow the discussion with CodeMirror team here - https://discuss.codemirror.net/t/code-inside-do-block-treated-as-string-postgresql-dialect/8005

**Comment by adityatoshniwal** [comment]
I'm raising this to CM team again if we have option to disable this somehow.

**Comment by adityatoshniwal** [comment]
CM allows to disable $$ string but it was not working because of some bug in upstream. It is fixed and pgAdmin is changed accordingly.

**Comment by khushboovashi** [comment]
Fixed with the latest code.

**Comment by casparsch** [comment]
> Fixed with the latest code.

@khushboovashi and others as well of course.
Thanks for the development effort on this issue. I am looking forward for release 8.6. _As I understand it will be released on 2nd of may 2024._ Once this version is publicly available and I have it installed I will let you know if it is resolved as soon as possible.
But so far: :+1:

**Comment by brsa** [comment]
I am not sure how this was "fixed" exactly. Have to see in v8.6. But treating dollar-quoted strings as plain strings (while technically correct) is unhelpful. In the absolute majority of cases, dollar-quoting (with a token) is used for function bodies and other code blocks, which benefit from syntax-highlighting. The best practice would be to treat simple strings (```'string'```) and maybe also plain dollar-quoting without token (```$$string$$```) as strings, but keep up the syntax-highlighting for dollar-quoting with token ```$func$BEGIN ...$func$```.

Related post making the same point: https://github.com/pgadmin-org/pgadmin4/issues/7276#issuecomment-2039264572

**Comment by casparsch** [comment]
My verification on version 8.6 gets my approval  :heavy_check_mark:  
Thank you all for resolving this issue. :top:
