### ISSUE TITLE
Auto completion is dramatically worse since PGAdmin 8.4

### ISSUE THREAD

**Issue by rbrooklyn** [pgadmin-org/pgadmin4#7299]
**Describe the bug**

Auto complete in PGAdmin is much worse in the latest 8.4 release.

The font has also changed for some reason and now it's borderline useless most of the time.

Unfortunately experience tells me that I cannot downgrade pgadmin when I encounter these issues.

**To Reproduce**

Open SQL Query window. Try to use autocomplete.

For example:
SELECT * FROM schema. WHERE primary_key = 1
Move cursor to the end of schema. and then press Control + Space.

**Expected behavior**

Tables in the schema to be automatically completed for easy selection.

**Error message**

Odd entries like "ABORT" show up instead. Or nothing shows up at all. No error is ever displayed.

**Screenshots**

I see this:
![image](https://github.com/pgadmin-org/pgadmin4/assets/11929484/71f2952e-b290-4b7d-b07b-c21bb546de0b)

I should be seeing entries like this:
![image](https://github.com/pgadmin-org/pgadmin4/assets/11929484/aa25d665-f3bd-485d-af69-0e5b61f40823)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.4
 - Mode: Desktop
 - Package type: MSI Installer

**Comment by pravesh-sharma** [comment]
Issue fixed, verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-27/).
