### ISSUE TITLE
Mot de passe principal oublié

### ISSUE THREAD

**Issue by IsraelOmba** [pgadmin-org/pgadmin4#7300]
Faute d'une bonne connexion, j'ai eu du mal à saisir le mot de passe principal... j'ai entré un mot de passe que j'ignore complètement et maintenant j'ai du mal à me connecter et à créer mes serveurs. J'ai testé toutes les options pour résoudre ce problème mais de solution toujours

**Comment by yogeshmahajan-1903** [comment]
@IsraelOmba 
pgadmin does not store Master password.
You have a button to reset the master password on same pop up. 
**Note** - Your existing server passwords will be deleted. You will have to enter server password while connecting again.

**Comment by pravesh-sharma** [comment]
No response from the author. Closing.
