### ISSUE TITLE
pgAdmin4 v8 FATAL ERROR: the server could not be contracted

### ISSUE THREAD

**Issue by shivangivatsalpatel** [pgadmin-org/pgadmin4#7301]
![fatalError](https://github.com/pgadmin-org/pgadmin4/assets/147914621/addb5e18-80c6-46ef-8bc3-3d1ff4c6e969)

Hello!

please somebody help me with this issue,
whenever i launch PgAdmin it shows me this error and when i click on configure and follow all the required steps it still show me the same error constantly,
i have tried everything from google and youtube but nothing helps,
nothing on the internet that i have not tried but still the error happens everytime I lunch pgAdmin,
please HELP!!!!!!

**Comment by yogeshmahajan-1903** [comment]
@shivangivatsalpatel 
Can you please provide OS details? From where did you download pgadmin installer? 
Can you please share complete logs from above splash screen?

**Comment by Mahendrareddybuthukuri** [comment]
Stop Running  MQTT server in Your PC, If your Using Mosquito or some other.

**Comment by shivangivatsalpatel** [comment]
@yogeshmahajan-1903 OS - Windows_NT
Downloaded pgAdmin from - https://www.pgadmin.org/download/pgadmin-4-windows/
and here are other screenshots
![Screenshot (1)](https://github.com/pgadmin-org/pgadmin4/assets/147914621/6bace64e-2492-4a0b-b0e0-21cef4347dac)
![Screenshot (2)](https://github.com/pgadmin-org/pgadmin4/assets/147914621/c4680d84-8875-42f8-a24c-41ded86c413a)
![Screenshot (3)](https://github.com/pgadmin-org/pgadmin4/assets/147914621/a83b1f7b-db78-4e96-892e-3b723d7e02a5)
![Screenshot (4)](https://github.com/pgadmin-org/pgadmin4/assets/147914621/0417d0d8-644c-4cc5-8cb7-4f49ca848a40)
![Screenshot (5)](https://github.com/pgadmin-org/pgadmin4/assets/147914621/90dba585-5642-42f3-80bb-f4866c075dad)

**Comment by yogeshmahajan-1903** [comment]
@shivangivatsalpatel ,

I guess Windows_NT is 32 bit OS. pgadmin does not support 32 bit OS.

**Comment by shivangivatsalpatel** [comment]
@yogeshmahajan-1903 

No, it's actually 64-bit operating system, x64-based processor.

**Comment by shivangivatsalpatel** [comment]
@Mahendrareddybuthukuri 

No sir, i am not using any MQTT server in my PC.

**Comment by anilsahoo20** [comment]
Hi @shivangivatsalpatel 
Can you please uninstall pgAdmin 4 and try to search for pgAdmin 4, in that way we can find any other pgAdmin 4 installed or not.

**Comment by adityatoshniwal** [comment]
> @yogeshmahajan-1903 No sir , there are no duplicates. For me also it's works only for 2 days after Stopped MQTT Server. Again it's showing same error. I had restarted my PC so many times. Still it's not Working.
> 
> @shivangivatsalpatel it's better to use MySQL workbench.

No idea what MQTT does. You can simply share the logs by Ctrl+A, Copy and Paste. Partial screenshot of logs doesn't help. Also provide complete OS details(possibly screenshot).

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.

**Comment by shivangivatsalpatel** [comment]
> No response from the author, hence closing it.

@akshay-joshi 
Apologies, but the issue has not been solved yet,
i've already given all the required details for the issue.

**Comment by adityatoshniwal** [comment]
> > No response from the author, hence closing it.
> 
> @akshay-joshi Apologies, but the issue has not been solved yet, i've already given all the required details for the issue.

You are yet to reply to my comment here - https://github.com/pgadmin-org/pgadmin4/issues/7301#issuecomment-2027158708

**Comment by shivangivatsalpatel** [comment]
@adityatoshniwal  
Hello, my bad i missed that
so here are the details,

**Device Specifications**
Processor	AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G      2.60 GHz
Installed RAM	4.00 GB (3.11 GB usable)
System type	64-bit operating system, x64-based processor



**Windows Specifications**
Edition	Windows 10 Home
Version	22H2
Installed on	‎22-‎11-‎2023




The pgAdmin 4 server could not be contacted: 
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Program Files\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\shiva\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Program Files\pgAdmin 4\web\config.py"
Webapp Path: "C:\Program Files\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\pgAdmin 4\python\python.exe -s C:\Program Files\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\shiva\AppData\Roaming
  - ChocolateyInstall: C:\ProgramData\chocolatey
  - ChocolateyLastPathUpdate: 133560155175652659
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_5848_OODRZFMUCTUGSLOU
  - CHROME_RESTART: NW.js|Whoa! NW.js has crashed. Relaunch now?|LEFT_TO_RIGHT
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: 
  - ComSpec: C:\WINDOWS\system32\cmd.exe
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
  - FPS_BROWSER_USER_PROFILE_STRING: Default
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\shiva
  - LOCALAPPDATA: C:\Users\shiva\AppData\Local
  - LOGONSERVER: 
  - NUMBER_OF_PROCESSORS: 2
  - OneDrive: C:\Users\shiva\OneDrive
  - OneDriveConsumer: C:\Users\shiva\OneDrive
  - OS: Windows_NT
  - Path: C:\Program Files\pgAdmin 4\runtime;C:\Python312\Scripts\;C:\Python312\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\shiva\AppData\Local\Microsoft\WindowsApps;;C:\Users\shiva\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\shiva\AppData\Roaming\npm
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
  - PGADMIN_INT_KEY: 
  - PGADMIN_INT_PORT: 49736
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
  - PROCESSOR_LEVEL: 21
  - PROCESSOR_REVISION: 7000
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
  - PUBLIC: C:\Users\Public
  - SESSIONNAME: Console
  - SystemDrive: C:
  - SystemRoot: C:\WINDOWS
  - TEMP: C:\Users\shiva\AppData\Local\Temp
  - TMP: C:\Users\shiva\AppData\Local\Temp
  - USERDOMAIN:
  - USERDOMAIN_ROAMINGPROFILE:
  - USERNAME: shiva
  - USERPROFILE: C:\Users\shiva
  - windir: C:\WINDOWS
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.158 Sec

**Comment by shivangivatsalpatel** [comment]
@adityatoshniwal 
sorry, i didn't quite catch that, what workaround? mentioned where?

**Comment by adityatoshniwal** [comment]
> @adityatoshniwal it shows it's not very safe workaround to apply.

Unfortunately, pgAdmin team cannot help. The issue is with upstream and until that is fixed we can't do anything.
