### ISSUE TITLE
Color scheme disappears in DO Block with $$ as block end

### ISSUE THREAD

**Issue by udit47** [pgadmin-org/pgadmin4#7302]
When DO block is written with $$ as block end, color scheme of SQL text inside DO block disappears and all text turns Yellow.
However, when tried with $ BODY $ or $ HAHA $ it works. This has only appeared in 8.4

**To Reproduce**

Write following DO block in Query Editor

```
DO
$$
BEGIN
	RAISE NOTICE 'Hello!';
END;
$$;
```

**Expected behavior**

Color scheme should persist.

**Screenshots**

With $$

![image](https://github.com/pgadmin-org/pgadmin4/assets/8330999/ecdf014c-db41-44a7-b672-8f8b030b9b13)

With others

![image](https://github.com/pgadmin-org/pgadmin4/assets/8330999/dcb84d95-6de3-4bfd-b0db-4f9ba8ff05b0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 8.4
 - Mode: Desktop
 - Package type: .msi

**Comment by adityatoshniwal** [comment]
Duplicates #7294.
