### ISSUE TITLE
setup.py update-user doesn't change password

### ISSUE THREAD

**Issue by jmckulk** [pgadmin-org/pgadmin4#7304]
***Please note that security bugs or issues should be reported to [[security@pgadmin.org](mailto:security@pgadmin.org)](mailto:security@pgadmin.org).***

**Describe the bug**

The `setup.py update-user` command does not update my password. After running the command with a new password, the UI does not recognize the new password for user login, but it still accepts the old password. This issue prevents me from successfully changing my passwords via command line.

**To Reproduce**

1. Create a user with the `setup.py add-user` command:

```
bash-4.4$ setup.py add-user user@example.com pass123
User Details            
+---------------------------------+
| Field       | Value             |
|-------------+-------------------|
| Email       | user@example.com |
| auth_source | internal          |
| role        | Non-admin         |
| active      | True              |
+---------------------------------+
```

2. Verify the user can log into the pgAdmin GUI using the password `pass123`.
3. Attempt to update the user's password with the `setup.py update-user` command:

```
bash-4.4$ setup update-user user@example.com --password newpass123
+---------------------------------+
| Field       | Value             |
|-------------+-------------------|
| Username    | user@example.com |
| Email       | user@example.com |
| auth_source | internal          |
| role        | Non-admin         |
| active      | True              |
+---------------------------------+
```

4. Try to log into the pgAdmin GUI using the new password `newpass123` and observe the failure.
5. Confirm that logging in with the old password `pass123` still works.
6. Update the password through the GUI to `thirdpass123` and verify that you can log in using `thirdpass123`.

**Expected behavior**

After using the `setup.py update-user` command to update a user's password, the new password should be recognized by the system, allowing me to log in with the new credential. The old password should no longer be valid.

**Error message**

No explicit error message is displayed in the terminal. However, the pgAdmin GUI login process fails with an incorrect password error when attempting to use the new password set via the `setup.py update-user` command.

**Screenshots**

![pgadmin-version](https://github.com/pgadmin-org/pgadmin4/assets/16840147/f7da1351-7e04-4705-9514-009d8e37d19a)

**Desktop (please complete the following information):**

- OS: [Linux Container]
- Version: [8.4]
- Mode: [Server]
- Browser (if running in server mode): [brave/chrome]
- Package type: [python/container]

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
