### ISSUE TITLE
Execute queries with Ctrl+Enter

### ISSUE THREAD

**Issue by AtmoFX** [pgadmin-org/pgadmin4#7305]
Linked to [7268](https://github.com/pgadmin-org/pgadmin4/issues/7268)

**Describe the bug**

As commented by @robpoyntz [here](https://github.com/pgadmin-org/pgadmin4/issues/7268#issuecomment-1990545384), <kbd>Ctrl+Enter</kbd> can no longer be used to execute queries the same way it was until pgAdmin 8.2 or 8.3.<br/>This issue looks unrelated to query formatting hence this separate report.

There are 3 arguments to be made in favor of restoring:
 1. It used to work fine.
 1. Some of us out there work on other DBs too, with other clients where <kbd>Ctrl+Enter</kbd> was the default shortcut to execute queries (e.g. SSMS) and it is very uncomfortable to switch between applications when such an important shortcut cannot be the same.<br/>I understand you may not want to be tied to choices made in other software but it is a choice your users have already made.
 1. Finally and perhaps more importantly, the problem exists in the first place because pgAdmin does provide an option where the key binding can be set to <kbd>Ctrl+Enter</kbd> (`Preferences > Query Tool > Keyboard shortcuts > Execute script`).<br/>BTW, this is the setting you will need to alter to reproduce the bug.

**Expected behavior**

The expected behavior is what it used to be: execute the selection portion of text from the editor.<br/>The behavior now is: Insert a line break + execute the entire text of the editor.

**Desktop:**
 - OS: Windows 10
 - Version: 8.4
 - Mode: Desktop

**Additional context**

Query [7167](https://github.com/pgadmin-org/pgadmin4/issues/7167) may come in conflict with this one.<br/>
I am not completely sure shortcuts for the Sort/Filter option dialog would collide with shortcuts for the query tool window, precisely because they are separate windows, but the shortcut to display it (<kbd>Alt+F</kbd> by default) is shown in the same portion of the preferences as above: `Preferences > Query Tool > Keyboard shortcuts > Accesskey (Filter dialog)`.

**Comment by pravesh-sharma** [comment]
Issue resolved. Verified on latest snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-25/)

Env
OS - macOS Sonoma and Rocky 9
Mode - Desktop and server
