### ISSUE TITLE
Email authentication dialog showing unexpected error after sending the verification code to the email address.

### ISSUE THREAD

**Issue by anilsahoo20** [pgadmin-org/pgadmin4#7308]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

In server mode, while setting up email authentication of 2FA, after the verification code is sent on click of continue button, getting error `{"success":0,"errormsg":"'int' object is not callable","info":"","result":null,"data":null}`

**To Reproduce**

1. Click on 2FA
2. Click on continue after entering the correct email id
3. See the error

**Expected behavior**

it should show the screen to enter verification code.

**Error message**

{"success":0,"errormsg":"'int' object is not callable","info":"","result":null,"data":null}

**Screenshots**

<img width="1002" alt="Screenshot 2024-03-22 at 11 01 55 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/122535205/5011af61-02df-4e26-b7b2-7aef2f7d67a7">

**Desktop (please complete the following information):**
 - OS: macOs ventura
 - Version: 8.4
 - Mode: Server
 - Browser (if running in server mode): chrome
 - Package type: Python

**Comment by pravesh-sharma** [comment]
Issue resolved. Verified on latest snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-27/)

Env
Mode -Server
Package - Python
OS - macOS Sonoma
