### ISSUE TITLE
Wrong ER-Diagram gerated for a one to one relationship

### ISSUE THREAD

**Issue by natnael-bedru** [pgadmin-org/pgadmin4#7311]
i was working on a spring-boot project and running dockerized version of postgress and pgadmin and i run in into this issue when i generated the er diagram for a one to one relation-ship. here is the sql

``` sql
create sequence student_id_card_sequence start with 1 increment by 1;
create sequence student_sequence start with 1 increment by 1;
 create table student (
        age integer not null,
        id bigint not null,
        email TEXT not null,
        first_name TEXT not null,
        last_name TEXT not null,
        primary key (id),
        constraint student_email_unique unique (email)
    );
 create table student_id_card (
        id bigint not null,
        student_id bigint unique,
        card_number varchar(15),
        primary key (id),
        constraint student_id_card_unique unique (card_number)
    );
alter table if exists student_id_card 
       add constraint Student_Id_Card_Student_Id_Fk 
       foreign key (student_id) 
       references student;
```
here is the docker commands that i used to recreate the issue
> Postgress version: psql (PostgreSQL) 16.2 (Debian 16.2-1.pgdg120+2)
> ```
> docker run -itd -e POSTGRES_USER=amigoscode -e POSTGRES_PASSWORD=amigoscode -p 5432:5432 --name postgresql postgres
> ```

> PgAdmin version: 8.4
> ```
> docker run --name pgadmin -p 5051:80 -e PGADMIN_DEFAULT_EMAIL="admin@pgadmin.com" -e PGADMIN_DEFAULT_PASSWORD="admin" -d dpage/pgadmin4
> ```

[pgAdmin about section server config text file](https://github.com/pgadmin-org/pgadmin4/files/14730696/my.pgadmin.dockerized.server.configuration.txt)

Wrong ER-Diagram
--
![pgadminissueonetomany](https://github.com/pgadmin-org/pgadmin4/assets/116979329/a2570d75-a9bc-488a-98c2-adb234c9dd17)

**Comment by adityatoshniwal** [comment]
one to one relationship is not supported yet. Duplicates #5128.
