### ISSUE TITLE
Use spaces? not working properly

### ISSUE THREAD

**Issue by pravesh-sharma** [pgadmin-org/pgadmin4#7317]
**Describe the bug**
If we enable `Use spaces?` and then indent any SQL it uses spaces. However, when we press backspace it should remove the spaces and not the entire tab width.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Version: 8.4
 - Mode: Desktop

**Comment by adityatoshniwal** [comment]
I have asked the CodeMirror team about this - https://discuss.codemirror.net/t/indentation-using-spaces-should-remove-single-space-on-backspace/8072

**Comment by adityatoshniwal** [comment]
As per the CM team, the current behaviour is correct and is followed by most of the standard editors.
I tested on VS Code and PyCharm, both behave the same. Closing this.

**Comment by adityatoshniwal** [comment]
I'm reopening this issue to make this behaviour customisable based on preference. Based on the reply from CM team, we'll need to add custom backspace behaviour.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-04-23/
Environment: macOs Ventura 13.5.1
Package: arm64
