### ISSUE TITLE
Error generating script for calling a SQL-function

### ISSUE THREAD

**Issue by Aesth** [pgadmin-org/pgadmin4#7334]
There is a SQL function with this header:

"CREATE OR REPLACE FUNCTION public.person_add(
	_creator_id integer,
	_email character varying,
	_surname character varying,
	_name character varying,
	_patronymic character varying,
	_women boolean,
	_born date,
	_born_ymd "char" DEFAULT NULL::"char",
	_location_id smallint DEFAULT NULL::smallint,
	_first_name character varying DEFAULT NULL::character varying,
	_last_name character varying DEFAULT NULL::character varying,
	_middle_name character varying DEFAULT NULL::character varying)
    RETURNS integer
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE"

In “Object explorer”, right-click on the function name, select the context menu item “Script|Select script” and get this option for calling the function
"
SELECT public.person_add(
	<_creator_id integer>, 
	<_email character varying>, 
	<_surname character varying>, 
	<_name character varying>, 
	<_patronymic character varying>, 
	<_women boolean>, 
	<_born date>, 
	<_born_ymd "char">, 
	<_location_id smallint>, 
	<_first
	<_name character varying>>, 
	<_last
	<_name character varying>>, _middle
	<_name character varying>
)"
The call code is incorrect because parameter names with two underscores are displayed incorrectly.
Instead of "<_first_name character varying>" we get:
 "
<_first
<_name character varying>>
"
We observe exactly the same behavior in the case of other similar parameters: "_last_name" and "_middle_name".

It seems that the error concerns only the script generation itself and does not depend in any way on the software.

**Comment by pravesh-sharma** [comment]
Hi @Aesth,

Can you please share the DDL of the function?

**Comment by Aesth** [comment]
No DDL needed. The simplest example of the selected procedure in the left tree window. The following code is displayed on the SQL tab:

```
-- FUNCTION: public.test(character varying, character varying, integer, integer)

-- DROP FUNCTION IF EXISTS public.test(character varying, character varying, integer, integer);

CREATE OR REPLACE FUNCTION public.test(
	_name character varying,
	_eng_name character varying,
	_first integer,
	_1_first integer)
    RETURNS integer
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
SELECT 1
$BODY$;

ALTER FUNCTION public.test(character varying, character varying, integer, integer)
    OWNER TO postgres;
```

It completely coincides with what is shown by right-clicking on this procedure when selecting "Scripts|CREATE Script".

Then select the “Scripts|SELECT Script” item and see the following script in the window:

```
SELECT public.test(
	<_name character varying>, 
	<_eng
	<_name character varying>>, 
	<_first integer>, _1
	<_first integer>
)

```

Thus, we see that a script generation error occurs when generating a function call with parameters that contain identical parts of the name that begin with the “_” character. For the first 2 parameters it is:
  "_name" and "_eng_name"
and for the last 2:
  "_first" and "_1_first"

Just in case:

Version: 8.4
Application Mode: Desktop
Current User: pgadmin4@pgadmin.org
NW.js Version: 0.77.0
Browser: Chromium 114.0.5735.91
Operating System: Windows-10-10.0.19045-SP0

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-04-26/
Environment: macOs Ventura 13.5.1
Package: arm64

**Comment by Aesth** [comment]
thanks!
