### ISSUE TITLE
Save layout

### ISSUE THREAD

**Issue by DavidBuch1** [pgadmin-org/pgadmin4#7336]
I often have numerous tabs open from different schemas or databases, and I drag them around to have them side by side or in other layouts. However the moment I close pgadmin, the layout is never saved.

It would be very helpful to be able to save the layout as I have set it.

thanks

**Comment by pravesh-sharma** [comment]
Hi @DavidBuch1,

Can you please share the screenshot of your layout? Please note query tool tab will not be saved on close.

**Comment by DavidBuch1** [comment]
Hi

Attached is the screenshot.

It would be really helpful to be able to save the query tool tab layout - I use pretty much the same kind of layout all the time.

￼
Kind regards

David Buch

CEO & Founder Appzoola

+61 451 753 960
+1 218-203-5343

Meeting request: https://calendly.com/appzoola
￼

On 5 Apr 2024, at 21:37, Pravesh Sharma ***@***.***> wrote:


Hi @DavidBuch1 <https://github.com/DavidBuch1>,

Can you please share the screenshot of your layout? Please note query tool tab will not be saved on close.

**Comment by khushboovashi** [comment]
@DavidBuch1, I'm not able to see the screenshot; please send it again.

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
