### ISSUE TITLE
Randomly crashes

### ISSUE THREAD

**Issue by DavidBuch1** [pgadmin-org/pgadmin4#7337]
I will be working in pgAdmin and without warning, it shuts down, losing all my work.
I cannot reproduce this at will, but it seems to happen after I have been working for a long time and have numerous tabs open from different databases/schemas

**Desktop (please complete the following information):**
 - OS: Mac Sonoma 
 - Version: 14.4.1  - Desktop
 - RAM: 128GB

**Comment by pravesh-sharma** [comment]
Hi @DavidBuch1,

Can you please share the logs? What is the version of pgAdmin?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
