### ISSUE TITLE
When attempting to open pgAdmin, it keeps crashing. Despite uninstalling and reinstalling postgresql-15.4-1-osx, the issue persists.

### ISSUE THREAD

**Issue by daLogewajackie888** [pgadmin-org/pgadmin4#7341]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacBook Air 
 - Version: macOS Monterey 12.7.4
 - Mode: Desktop
 - Browser: chrome
 

**Additional context**

![image](https://github.com/pgadmin-org/pgadmin4/assets/140554234/2fb5b292-6c69-4fe5-a5bc-683bae057fd5)

**Comment by yogeshmahajan-1903** [comment]
@daLogewajackie888 
Can you please try downloading latest version of PostgreSQl 15 i.e. 15.6 and try? Ot you can download latest pgadmin from [here](https://www.pgadmin.org/download/).

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
