### ISSUE TITLE
incomplete data output of a json column 

### ISSUE THREAD

**Issue by sandeshShahapur** [pgadmin-org/pgadmin4#7342]
**Describe the bug**

After reproducing the steps as described below, the output for the json column only shows a single opening curly parenthesis '{' instead of the whole output (refer screenshot).

**To Reproduce**

1. create a table containing a `jsonb` column. example:
```sql
CREATE TABLE IF NOT EXISTS public.plugin_config_templates
(
    plugin_name text COLLATE pg_catalog."default" NOT NULL,
    config_template jsonb NOT NULL,
    CONSTRAINT plugin_config_templates_pkey PRIMARY KEY (plugin_name),
    CONSTRAINT plugin_config_templates_plugin_name_fkey FOREIGN KEY (plugin_name)
        REFERENCES public.plugins (name) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
```
2. insert a row. example:
```sql
INSERT INTO plugin_config_templates (plugin_name, config_template)
VALUES ('bumper', 
    '{
        "server_id": null,
        "reminder": {
            "enabled": false,
            "channel_id": null,
            "bump_message": "Thank you {user_mention} for bumping our server! We will remind you in two hours to bump again.\n",
            "to_ping": null,
            "reminder_message": "{to_ping_mention} It is time to bump the server again!, Bump our server by typing /bump!"
        },
        "miss_reminder": {
            "enabled": false,
            "channel_id": null,
            "interval": 600,
            "to_ping": null,
            "message": "{to_ping_mention} Woops! It seems like you missed bumping our server! Please bump again to support us!"
        },
        "counter": {
            "enabled": false,
            "bump_message": "We have been bumped **{count}** times and your contribution is **{contribution_pct}%**! Thank you for your support!"
        }
    }'::jsonb
);
```
3. change the `jsonb` datatype to `json` by right clicking table in explorer and going to properties,
4. open a query tool and query to output all rows. example:
`select * from plugin_config_templates;`
at this point, the output works fine
5. delete the rows from data output tab and insert it again from query tool.
6. repeat step four. the output is now bugged (refer screenshot). to me it only shows an opening curly parenthesis. if i use psql from pg admin or from windows command prompt, it shows the whole output just fine.

**Expected behavior**

The complete data output should be seen instead of a single open parenthesis.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/110241292/ca351905-abef-4182-93c9-c2fb6777df28)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.3
 - Mode: Desktop
 - Package type: i don't know?

**Comment by sandeshShahapur** [comment]
> @sandeshShahapur Have you tried double clicking the json data cell? It may be formatted, hence you see first line as '{'.

yeah double clicking data cell shows the json. what is the problem with it being formatted?

**Comment by yogeshmahajan-1903** [comment]
> > @sandeshShahapur Have you tried double clicking the json data cell? It may be formatted, hence you see first line as '{'.
> 
> yeah double clicking data cell shows the json. what is the problem with it being formatted?

This is because json data type saves data as it is.(refer [this](https://www.postgresql.org/docs/current/datatype-json.html) link). Hence pgadmin also shows , how it was retrieved from backend. Hence this is not an issue.
<img width="1595" alt="Screenshot 2024-04-03 at 9 43 06 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/cdc73977-2c16-4bb3-8575-bf6d4b1d9994">

You can save by changing it to compact format.

<img width="657" alt="Screenshot 2024-04-03 at 9 41 25 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/19ad30bd-c125-45ad-9c5d-13c075d5f5ed">
<img width="707" alt="Screenshot 2024-04-03 at 9 41 38 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/af703105-aa41-4870-aa3c-75e627ea076b">

**Comment by sandeshShahapur** [comment]
understood, thank you!
