### ISSUE TITLE
Certificate verification failed: The certificate is NOT trusted

### ISSUE THREAD

**Issue by douglashg** [pgadmin-org/pgadmin4#7344]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When try install pgadmin on ubuntu follow the script pruposed on page.

https://www.pgadmin.org/download/pgadmin-4-apt/

Err:7 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/jammy pgadmin4 InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. 

1. Go to https://www.pgadmin.org/download/pgadmin-4-apt/
2. Copy script to install on ubuntu *apt
3. And run script on terminal

**Expected behavior**

Installed pgadmin with succes.

**Error message**

Err:7 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/jammy pgadmin4 InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. 

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: [e.g. UTM Virtual Ubuntu Server 22.04, Jammy]
 - Version: [e.g. 22.04]
 - Mode: [Macbook M2 Pro]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [script apt-get pruposed]

**Additional context**

**Comment by pravesh-sharma** [comment]
Hi @douglashg,

Can you please try running `sudo apt install ca-certificates`. Ref: https://askubuntu.com/questions/1095266/apt-get-update-failed-because-certificate-verification-failed-because-handshake

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.

**Comment by MaWoe** [comment]
I have the same problem. `ca-certificates` is already installed. Running on ubuntu-22.04

**Comment by damdaepark** [comment]
Have the same problem here.

**Comment by khushboovashi** [comment]
> Have the same problem here.

https://askubuntu.com/questions/1095266/apt-get-update-failed-because-certificate-verification-failed-because-handshake
