### ISSUE TITLE
Query Editor Find Replace Function not working

### ISSUE THREAD

**Issue by maazr** [pgadmin-org/pgadmin4#7345]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
New version 8.4 
Find replace option is not working 
Whenever I press "Ctrl + Shift + F" I am getting "Quick Search" box opens up

**To Reproduce**

Open query panel with some text 

3. Click on '....'
Select edit option from tool bar
Use Replace option it is disabled

4. See the error
Now go to editor box Press "Ctrl-Shift-F" a quick find box open up which is an error

**Expected behavior**
In earlier versions "Find replace dialog box use to open"

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11,
 - Version: 22H2 (OS Build 22621.3155)
 - Mode: [Desktop]

 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

This feature was very useful when bring queries from Oracle and replace bunch of extra character in one shot. Now I have do it one by one or bring code to VSCode to fix it.

**Comment by pravesh-sharma** [comment]
Duplicates #7262.

**Comment by pravesh-sharma** [comment]
Hi @maazr 

There was an upgrade in lib used for the editor. Please try `Ctrl+Alt+F`.

**Comment by maazr** [comment]
That is a big help thank you very much


Sent from my iPhone

On Apr 4, 2024, at 1:10 AM, Pravesh Sharma ***@***.***> wrote:

﻿

Closed #7345<https://github.com/pgadmin-org/pgadmin4/issues/7345> as not planned.

**Comment by maazr** [comment]
Thanks it works
Unfortunately I open another issue with for 8.5
Please check my new issue on GitHub


Sent from my iPhone

On Apr 4, 2024, at 1:13 AM, Pravesh Sharma ***@***.***> wrote:

﻿

Hi @maazr<https://github.com/maazr>

There was an upgrade in lib used for the editor. Please try Ctrl+Alt+F.
