### ISSUE TITLE
Find and Replace does not show

### ISSUE THREAD

**Issue by ksiazekm** [pgadmin-org/pgadmin4#7347]
When trying to use 'Replace' from 'Edit' button nothing happens. Same when trying to use keyboard shortcut of 'Ctrl + Shift + F'.

1. Open Query Tool
2. Click on 'Replace' from 'Edit' button
3. Nothing happens.

Find/Replace pop-up window should be shown.

 - OS: Windows 10
 - Version: 8.4
 - Mode: Desktop

**Comment by pravesh-sharma** [comment]
Duplicates #7262
