### ISSUE TITLE
Query Tool have issue

### ISSUE THREAD

**Issue by maazr** [pgadmin-org/pgadmin4#7348]
Script is turning into comment after $ sign.
screen shot attached.
First screen shot show no $ sign after $BODY
Second screen shot show with $BODY$ every line turn to pink
<img width="343" alt="First_04-04 112816" src="https://github.com/pgadmin-org/pgadmin4/assets/18107864/5a8cc6a6-ccb8-45f8-94dc-0dec8432d145">
<img width="362" alt="Second_04-04 112631" src="https://github.com/pgadmin-org/pgadmin4/assets/18107864/fba93508-3f71-4daf-a205-f5998be54ab4">

I thought there is some invisible character but all my previous scripts also showing same behavior.

Thanks

**Comment by maazr** [comment]
Let me add one more point issue #7348 is query tool has stop compiling script.

**Comment by adityatoshniwal** [comment]
Duplicates #7294.

**Comment by maazr** [comment]
Sir,
I just installed 8.5 again and see the issue persist.
Example in screen shot do not contain any single quote.
The screen shots I attached are from 8.5. Everything was good till 8.4.
If I put same sample code back in 8.4 version everything works fine.
What am I missing ?
Code highlighting is very crucial for my livelihood
Please help.


Sent from my iPhone

On Apr 5, 2024, at 2:16 AM, Aditya Toshniwal ***@***.***> wrote:

﻿

Closed #7348<https://github.com/pgadmin-org/pgadmin4/issues/7348> as not planned.
