### ISSUE TITLE
Documentation needs to be updated for Replace shortcut.

### ISSUE THREAD

**Issue by rdhedgepath2** [pgadmin-org/pgadmin4#7349]
Find and Replace shortcut has been changed, but documentation has not been updated. 

Documentation says to use CTRL-Shift-F to bring up dialog, starting with 8.4 this shortuct brings up Quick Search. 

The Edit Menu indicates that Alt+Ctrl+F will bring up Replace dialog box. 

Either Replace dialog box should come up with Ctrl+Shift+F as in the documentation. Or the Documentation needs to be updated to reflect that Alt+Ctrl+F is the shortcut for the Replace dialog. 

**Screenshots**
<img width="837" alt="Documentation with old shortcut" src="https://github.com/pgadmin-org/pgadmin4/assets/17178962/df7841a6-70e0-4ee8-b3f9-c210e18bfceb">

<img width="206" alt="Edit Menu with new shortcut" src="https://github.com/pgadmin-org/pgadmin4/assets/17178962/fb1b1681-0e81-450d-b426-187ce8489dfd">

**Desktop (please complete the following information):**
 - OS: Window 11
 - Version: pgAdmin4 8.5
 - Mode: pgAdmin4
 - Browser (if running in server mode): Chrome and Edge
 - Package type: Container

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-21/
Package: arm64
Environment: macOs Ventura 13.5.1
