### ISSUE TITLE
PGAdmin 4 - Query tool - provide shortcut to execute query at cursor

### ISSUE THREAD

**Issue by RosscoPecoTrain** [pgadmin-org/pgadmin4#7350]
Currently there does not appear to be a shortcut for executing the currently selected query block in the query editor.  Currently the only option for doing this is to manually select the query block, then hit execute/F5. 
This feature is commonly available in many other SQL IDEs and would be really helpful.

**Comment by adityatoshniwal** [comment]
Duplicates #6841.
