### ISSUE TITLE
Syntax Highlighting not working properly

### ISSUE THREAD

**Issue by tejasvih** [pgadmin-org/pgadmin4#7352]
**Describe the bug**

Syntax highlighting is not working for stored procedures!

**To Reproduce**

Open any stored procedures in editor. it shows all code in yellow color between (including) `$BODY$`

**Expected behavior**

Proper syntax highlighting

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/8927903/d883dd75-c510-4a29-9cb9-1a757d59b1f2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 8.5
 - Mode: Desktop

**Comment by adityatoshniwal** [comment]
Duplicates #7294

**Comment by adityatoshniwal** [comment]
And yes, it is same as 7294. Read this - https://github.com/pgadmin-org/pgadmin4/issues/7294#issuecomment-2006706654

**Comment by tejasvih** [comment]
Then how come earlier versions were showing syntax highlighting properly for same ?

**Comment by adityatoshniwal** [comment]
> Then how come earlier versions were showing syntax highlighting properly for same ?

To keep app up to date, we need to update outdated libs. As part of that, we moved from CodeMirror v5 to v6.

**Comment by tejasvih** [comment]
But still I feel, it has broken the feature. Issue might be something else, not because of `$$` syntax . Because syntax highlight is showing properly in Azure Data Studio and Dbeaver and earlier version of PgAdmin

**Comment by adityatoshniwal** [comment]
> But still I feel, it has broken the feature. Issue might be something else, not because of `$$` syntax . Because syntax highlight is showing properly in Azure Data Studio and Dbeaver and earlier version of PgAdmin

I think you should my above comments again until you understand the actual issue.

**Comment by tejasvih** [comment]
I see that the issue is fixed now. Thanks to Development Team.
