### ISSUE TITLE
Syntax highlighting has stopped working in functions, procedures & DO blocks for v8.5

### ISSUE THREAD

**Issue by udit47** [pgadmin-org/pgadmin4#7355]
**Describe the bug**

Syntax highlighting has stopped working in functions, procedures & DO blocks for v8.5 even with $ BODY $ as token.

**To Reproduce**

Create a function, procedure or DO block that uses $ BODY $ as token

**Expected behavior**

Syntax highlighting should persist.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/8330999/8e8316e7-21e2-43ab-a66f-3b39feb4a935)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 8.5
 - Mode: Desktop

**Comment by adityatoshniwal** [comment]
Duplicates #7294.

**Comment by tejasvih** [comment]
@udit47, Even I had raised this issue in my issue https://github.com/pgadmin-org/pgadmin4/issues/7352
But it was marked as duplicate and closed by @adityatoshniwal . I feel this is different issue than https://github.com/pgadmin-org/pgadmin4/issues/7294 even though both are effecting syntax highlighting.

**Comment by udit47** [comment]
Yes @tejasvih correct. Earlier in last version (8.4) $$ token started working as string literal but $ BODY $ or $ x $ was working fine but in this version even that is also not working. In #7352, there is reference to another issue reported to upstream (https://discuss.codemirror.net/t/code-inside-do-block-treated-as-string-postgresql-dialect/8005) in which @adityatoshniwal has highlighted the same problem as both of us did in bugs. I hope this means this is known for them.

**Comment by tejasvih** [comment]
Agree with @udit47.
But also, I feel closing the issue without analyzing properly is not correct.
PgAdmin introduces new issues or broken (existing) features in every release. That needs to be addressed.

**Comment by adityatoshniwal** [comment]
> Agree with @udit47. But also, I feel closing the issue without analyzing properly is not correct.

Did you try to read the analysis I have already mentioned in the comment?
>PgAdmin introduces new issues or broken (existing) features in every release. That needs to be addressed.

We would like your suggestions and resources on how to address it.

**Comment by tejasvih** [comment]
> > Agree with @udit47. But also, I feel closing the issue without analyzing properly is not correct.
> 
> Did you try to read the analysis I have already mentioned in the comment?
> > > Yes I went through, but there was no need of complicated analysis et all. Its as simple as the feature was working it's stopped working. Also, same feature is working in other software. That's all. Some things don't need much complex analysis.
> > PgAdmin introduces new issues or broken (existing) features in every release. That needs to be addressed.
> 
> We would like your suggestions and resources on how to address it.
>> one example was, version 8.5 did not have search-replace working. It used to just open a search window centered on the parent code window. 

I am not trying to blame anyone, please take these are as constructive criticism. Because PgAdmin is really my favorite tool for PostgreSQL. I really like using it.
