### ISSUE TITLE
Ctrl-C no longer working in Firefox after pgAdmin 8.3

### ISSUE THREAD

**Issue by dbkeon** [pgadmin-org/pgadmin4#7356]
pgAdmin 8.3, Firefox 122, Windows 11:  One or more cells in the Data Output results pane can be selected, then copied via Ctrl-C, and pasted in the Query pane via Ctrl-V.

pgAdmin 8.4 and 8.5, Firefox 122, Windows 11:  When one or more cells in the Data Output results pane are selected, then Ctrl-C is pressed, a small red "Does not have clipboard access" dialog comes up in the lower right, and Ctrl-V pastes nothing, presumably because nothing was copied to the Clipboard.

This only applies to Firefox.  The issue does not occur in Chrome or Edge on Windows, both Ctrl-C and Ctrl-V work fine in those cases.

**Comment by anilsahoo20** [comment]
Hi @dbkeon 
Please provide the clipboard access to pgAdmin in Firefox. Does not look like a pgAdmin issue.
