### ISSUE TITLE
Body of script is not colour coded

### ISSUE THREAD

**Issue by DavidBuch1** [pgadmin-org/pgadmin4#7357]
upgraded to 8.5 and then everything between
$BODY$

end 
$BODY$

displays as yellow with no code [highlighting](url
![Uploading Screenshot 2024-04-06 at 07.36.18.png…]()
)

To reproduce, right click a function and select scripts| CREATE Script

Expected:
Code highlighting as per previous versions.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.4.1
 - Version: 8.5
 - Mode: Desktop

**Comment by tejasvih** [comment]
@DavidBuch1 , I had raised this bug in https://github.com/pgadmin-org/pgadmin4/issues/7352 and @udit47 in https://github.com/pgadmin-org/pgadmin4/issues/7355 but unfortunately, they are not ready to accept that this is a bug with broken feature.

**Comment by adityatoshniwal** [comment]
Duplicates https://github.com/pgadmin-org/pgadmin4/issues/7294. Please check my last comment.
