### ISSUE TITLE
Please me shortcut as per standard

### ISSUE THREAD

**Issue by tejasvih** [pgadmin-org/pgadmin4#7358]
**Please make the commonly used shortcuts as per the standard practice, i.e. Ctl+S, Ctl+H etc.**

![image](https://github.com/pgadmin-org/pgadmin4/assets/8927903/db8c4f32-1ff3-4de2-964d-6bb2db0d01b0)
![image](https://github.com/pgadmin-org/pgadmin4/assets/8927903/1385923b-19ed-4099-ba0f-39b898746666)

As most users are used to standard shortcuts. Some shortcuts in PgAdmin are non standard i.e. Alt+S, Ctl+Alt+F 
Following the standard shortcuts will be easier for users.

**Comment by adityatoshniwal** [comment]
Duplicates #7192
