### ISSUE TITLE
pgadmin 8.5 forms invalid commands for backup when using Postgres 15

### ISSUE THREAD

**Issue by jrjake** [pgadmin-org/pgadmin4#7370]
**Describe the bug**

pgadmin4 v8.5 does not appear to be checking the installed Postgres version correctly, and is creating invalid commands.
`--large-objects` is only present in pg v16+, not in pg v15. Fedora 39 has Postgres 15.6:

```
$ cat /etc/fedora-release 
Fedora release 39 (Thirty Nine)
$ pg_dump --version
pg_dump (PostgreSQL) 15.6
$ pg_dump --large-objects
pg_dump: unrecognized option '--large-objects'
```

**To Reproduce**

#. Install pgadmin 4 8.5 on Fedora 39
#. Connect to a server
#. Attempt to Backup a database or schema
#. You will receive an error for "unrecognized option '--large-objects'"

**Expected behavior**

When trying to Backup a database or schema, pgadmin should not use invalid options for the installed Postgres. Postgres 15 does not support `--large-objects`, so pgadmin should not formulate commands with it.

**Error message**

Command:
```
/usr/bin/pg_dump --file "/home/user/file.pgdump" --host "127.0.0.1" --port "40679" --username "user" --no-password --format=c --large-objects --verbose "my_database"
```

Result:
```
/usr/bin/pg_dump: unrecognized option '--large-objects'
pg_dump: hint: Try "pg_dump --help" for more information.
```

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Fedora 39 (Linux-6.8.4-200.fc39.x86_64-x86_64-with-glibc2.38)
 - Version: 8.5
 - Mode: Desktop
 - Browser (if running in server mode): N/A
 - Package type: RPM

**Additional context**

N/A

**Comment by anilsahoo20** [comment]
Hi @jrjake 
pgAdmin does not create the command on the basis of pg_dump version. It creates on the basis of selected server version.
You can configure the pg_dump file path from Preferences->Paths->Binary Paths.
