### ISSUE TITLE
Connection to database is not automatically reestablished after connectivity drop

### ISSUE THREAD

**Issue by lzambarda** [pgadmin-org/pgadmin4#7372]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Whenever my connection to a database drops and is then reopened, any query ran from the editor immediately returns blank results.
The only way to get results again is to close the editor tab, create a new one from th same database and then to run the query from the new one.

**To Reproduce**

1. Set up a connection to a database using a tunnel
2. Open a query editor and run a query, note that the results come back normally
3. Terminate the tunnel and reopen it
4. Running the same query from step 2 should now return immediately and result in blank results.
5. Copy the query, close the editor and then reopen a query editor to the same database
6. Paste the query and run it. It should now work like step 2

**Expected behavior**

PgAdmin should be able to reconnect the query editor.

**Error message**

N/A

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  OSX Sonoma 14.4.1
 - Version: 8.5
 - Mode: Desktop

**Additional context**

This used to work fine in older versions of PgAdmin (Unfortunately I can't recall which version it was)

**Comment by jrm-fayolle** [comment]
Hello, 
Thanks PGADMIN team for your job.
This bug is also confirmed in PGADMIN4 8.5 (WIN11)
Needed to downgrade to 8.4 to have it works properly. 
We have a 1mn firewall timeout connection with all our DBs and PGADMIN 8.5 is not possible to use without automatic reconnection (and blank result is really strange).
Regards,

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-04-25/
Environment: macOs Ventura 13.5.1
Package: arm64

**Comment by jflambert** [comment]
Thanks for this fix!!!!
