### ISSUE TITLE
ERD Tools SQL generator doesn't include the sequence object creation

### ISSUE THREAD

**Issue by arguto1993** [pgadmin-org/pgadmin4#7391]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

I tried to generate sql from a .pgerd file, the generated sql doesn't have the sequences objects creation so when I run it on empty database I got an error saying that the sequence for the default value in column 1 (id) doesn't exists.

**To Reproduce**

1. Go to ERD Tool
2. Open a .pgerd file
3. Click on "Generate SQL"
4. Run the generated SQL on empty database
5. ERROR:  relation "[sequence_object_name]" does not exist

**Expected behavior**
The generated SQL should be able to run and created all of the tables, sequences, and relationshiop from the ERD

**Error message**
ERROR:  relation "[sequence_object_name]" does not exist
LINE 8:     id integer NOT NULL DEFAULT nextval('[sequence_object_name]...
                                                ^ 

SQL state: 42P01
Character: 313

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version: [10.10]
 - Mode: [Desktop]

**Comment by adityatoshniwal** [comment]
@arguto1993 What is your pgAdmin version? We had added a logic to reverse engineer serial columns in ERD so that there is no question of sequences.

**Comment by arguto1993** [comment]
I got the pgAdmin4 from postgres 15.6 installation, 
Version 8.2

**Comment by adityatoshniwal** [comment]
> I got the pgAdmin4 from postgres 15.6 installation, Version 8.2

Hi @arguto1993,
Are you using an older .pgerd file? If you generate now with 8.2+ then it will convert sequences to serial if they were originally serial. If it still doesn't work then please share then it means its a manual sequence, which is currently not supported by ERD.

**Comment by adityatoshniwal** [comment]
> I don't think so, my peers gave me the .pgerd, she told me her postgres version is 15 so I assume the pgAdmin4 version is the same as me since I also got postgres 15

Please share the pgerd file.

**Comment by arguto1993** [comment]
I can't share the pgerd files, but nevermind, I don't need it anymore for the moment. Thanks
