### ISSUE TITLE
Reconnect doesn't work in PGAdmin 8.5 Query window

### ISSUE THREAD

**Issue by durumdara** [pgadmin-org/pgadmin4#7392]
After I instelled the newer  (8.5) version, the reconnect function doesn't work.

Formerly it asked me about reconnection.
Now there is no dialog.
The Query window is seems to be work, but the result is empty.
None of data, none of update, etc.

1. Open a Query window to nonlocal PGSQL through WIFI, write "select 1" and open the result
2. Restart the WIFI connection
3. Then try to reopen the query
4. The result is empty. No dialog, no result.

Version
8.5
Application Mode
Desktop
Current User
pgadmin4@pgadmin.org
NW.js Version
0.77.0
Browser
Chromium 114.0.5735.91
Operating System
Windows-10-10.0.22631-SP0

**Comment by anilsahoo20** [comment]
Related to #7372
