### ISSUE TITLE
Ignore tablespace in Schema Difference doesn't work for indexes

### ISSUE THREAD

**Issue by pkExec** [pgadmin-org/pgadmin4#7405]
**Describe the bug**

When using schema diff, even though I have "Ignore Tablespace" ignored, I get differences because of different tablespaces in index creation. 

**To Reproduce**

1. Create a table in two databases eg "tableA" with a "colA" int column.
2. Create an additional tablespace in both databases, e.g. "tbs_2"
3. Create an index on the first database.
4. Create the same index on the second databasem but specify the tablespace "tbs_2".
5. Run Schema Diff in pgAdmin, select "Ignore Tablespace". See that the tables are reported as different.

**Expected behavior**

The tables shouldn't be considered different, and no change script should be generated for the index tablespace.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.5
 - Mode: Desktop

**Additional context**
Postgres Version 12.16

**Comment by anilsahoo20** [comment]
Hi @pkExec 
I tried with PostgreSQL 12 and 16, with the above steps you had given. It is not reproducible.
Attaching the screenshot for both the versions.

![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/5f9ae4d9-6308-40a3-9f5f-72dd1259f914)

![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/b39f1b5a-31df-4ed4-8529-dd86699a1e7b)

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
