### ISSUE TITLE
Enable JWT based Authentication in Pgadmin

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [pgadmin-org/pgadmin4#7418]
Hi, 
I am using pgadmin4 in to view data in the postgresql data within my application. pgadmin4 comes with its own authentication layer. But I wanted to know is there any way around that I can enable jwt based authentication for pgadmin.

My application is built on top of kubernetes 1.26. And pgadmin is also deployed as part of kubernetes cluster. I have setup an reverse proxy for the entire application, which first validates the JWT & later route back to the required application. Hence is it there in built feature that I can enable same within the pgadmin Authentication layer or any workaround that can help me to achieve same.

**Comment by adityatoshniwal** [comment]
oauth2 is based on JWT. You can create your own oauth2 authentication and configure pgAdmin.
