### ISSUE TITLE
Update react-table to the latest version.

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#7419]

**Comment by akshay-joshi** [comment]
Labels are truncated for most of the headers like in the Dashboard, and User Management dialog.
<img width="919" alt="Screenshot 2024-05-09 at 3 14 05 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/89cf5964-1ac2-4cf8-9e7d-887a0b0214d9">

**Comment by yogeshmahajan-1903** [comment]
System stats dashboard had missing Row borders, Disk table is empty.

<img width="1419" alt="Screenshot 2024-05-09 at 5 27 24 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/70ce619e-3796-4b2f-986c-bf0139b5ddf3">
<img width="1432" alt="Screenshot 2024-05-09 at 5 27 34 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/aba94f9d-edbd-43a4-ae25-d0d24cd7f794">
<img width="1424" alt="Screenshot 2024-05-09 at 5 28 14 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/5872acec-876a-485b-9167-fc0e621fb0bc">

**Comment by pravesh-sharma** [comment]
When creating a new table, I cannot create a Unique or Exclude constraint. However, I can create other constraints.


https://github.com/pgadmin-org/pgadmin4/assets/111979571/d628f3c8-492b-4aa3-bde7-ab80d6bb6532

**Comment by yogeshmahajan-1903** [comment]
Statistic tab table is mis aligned.
<img width="1443" alt="Screenshot 2024-05-16 at 11 06 13 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/0b6b9f45-0f0d-40a8-9740-b04e97a0fb36">

**Comment by anilsahoo20** [comment]
@adityatoshniwal 

1. Dashboard>General>Database/server activity panel>Locks table header cutting in next line
2. Dashboard>system stats>cpu>process cpu usage table heading border not showing
3. Dashboard>system stats>memory>process memory usage table heading border not showing
4. Dashboard>system stats>storage graphs are mis aligned by coming up
5. Dashboard>system stats>storage>Disk info table data is not showing up
6. User management dialog table header is cutting in next line

**Comment by yogeshmahajan-1903** [comment]
Icon for psql tool in the browser tool bar is changed.
<img width="686" alt="Screenshot 2024-05-20 at 10 21 26 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/79b3e309-3ddb-4937-b428-e97e2e3fb57f">

**Comment by adityatoshniwal** [comment]
> Icon for psql tool in the browser tool bar is changed. 

Please check https://github.com/pgadmin-org/pgadmin4/commit/0e786c519e1bcac78df4799f79d60cf4f1215e72

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-21/
Package: arm64, pip wheel
Environment: macOs Ventura 13.5.1
