### ISSUE TITLE
Weird Syntax Error at line#3

### ISSUE THREAD

**Issue by varad43** [pgadmin-org/pgadmin4#7423]
Running the "GeneratedScript.sql" is showing syntax error as mentioned in the title

**Comment by yogeshmahajan-1903** [comment]
@varad43 
Can you please provide more details about issue and error screenshot?

**Comment by adityatoshniwal** [comment]
@varad43 The information is not enough. It is a obvious thing to share relevant information when raising a bug and save everyones time.

**Comment by varad43** [comment]
> @varad43 Can you please provide more details about issue and error screenshot?

I was doing an project from a IBM/Coursera on pgAdmin and I had to do 10 tasks to do pass the test. I'll write the steps (from where I started till the problem):
1) Create 2 ERD Tables,
2) Normalize both the tables,
3) Define primary keys in each table and relationships as mentioned in the instructions section,
4) Generate an SQL script,
5) Download a file given in the instructions panel, i.e, [Generatedscript.sql](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DB0110EN-SkillsNetwork/datasets/CoffeeData/GeneratedScript.sql)
6) Opened the file in Query tool and run the sql script. 

That's where the problem began. Everytime I had refreshed the page and run the script, a new error would pop-up. I even tried changing the browser.

**Comment by adityatoshniwal** [comment]
@varad43 I ran your script and it works fine with no error:
<img width="1342" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/8782729d-c1e5-41ca-82d0-ca77e09020fd">

**Comment by varad43** [comment]
It's supposed to add 7 tables. Do you have the tables (check it under postgres --> Catalogs --> PostgreSQL Catalog (pg_catalog) --> Tables.

**Comment by adityatoshniwal** [comment]
> It's supposed to add 7 tables. Do you have the tables (check it under postgres --> Catalogs --> PostgreSQL Catalog (pg_catalog) --> Tables.

<img width="417" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/4a8e92f6-e2f0-4292-aa4e-4eef19edd515">

**Comment by varad43** [comment]
Hmm. Let me see again what I've been doing wrong.

**Comment by adityatoshniwal** [comment]
I will close this issue as the script works fine. Feel free to ask questions though.
