### ISSUE TITLE
Server starts but I can't get into login page

### ISSUE THREAD

**Issue by Xefreh** [pgadmin-org/pgadmin4#7424]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

I installed postgresql and then followed all the instructions to start pgadmin server but when I visit the home page it throws a big error that the page is not found or idk what that means.

**To Reproduce**

1. Install postgresql
2. Follow instructions to use pgadmin4.
3. start server
3. See the error

**Expected behavior**

A working login page.

**Error message**

https://pastebin.com/PhRp2AsC

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Version: 2024.04.01
 - Mode: Desktop
 - Browser Chrome
 - Package type: Python

**Comment by yogeshmahajan-1903** [comment]
@Xefreh 
Can you please share the screenshot for error? Also what is the pgadmin mode (server or desktop)?

**Comment by khushboovashi** [comment]
@Xefreh, From where did you install the pgAdmin? Also, we do not support Arch linux.

**Comment by Xefreh** [comment]
Via the instructions in the readme that tells us how to get source and make it run

**Comment by Xefreh** [comment]
I downloaded the source code of the latest release from pgadmin website and I made everything just like it is said in readme

**Comment by Xefreh** [comment]
> @Xefreh 
> Can you please share the screenshot for error? Also what is the pgadmin mode (server or desktop)? Also what is the PostgreSQL installer version?

I installed postgre with my package manager but it is up to date and I got no errors doing all the steps before, its just the flask server having an issue

**Comment by Xefreh** [comment]
Somehow I fixed the issue by following the instructions written on the website here https://www.pgadmin.org/download/pgadmin-4-python/. I don't know if the instructions written on the readme are no longer valid.
