### ISSUE TITLE
Unavailable modifier request

### ISSUE THREAD

**Issue by mark260486** [pgadmin-org/pgadmin4#7427]
**Describe the bug**

Fresh installation from Python Wheel v8.5. Standalone uWSGI Configuration used to run. With any cURL request I've got this in journald:
```
-- unavailable modifier requested: 0 --
```

For installation I've followed procedures from docs: 
- https://www.pgadmin.org/download/pgadmin-4-python/
- https://www.pgadmin.org/docs/pgadmin4/8.5/server_deployment.html

**To Reproduce**

1. Install PGAdmin4 v8.5 from Python Wheel;
2. Run application as a service with standalone uWSGI config;
3. See the error

**Expected behavior**

I'm not sure, but login page maybe?

**Error message**

```
-- unavailable modifier requested: 0 --
```

**Desktop (please complete the following information):**
 - OS: AlmaLinux 9.3
 - Version: 8.5
 - Mode: Server
 - Browser: none, cURL requests from another host;
 - Package type: Python.

Systemd service config:
```
[Unit]
Description = PgAdmin4 uwsgi Service
After = network.target network-online.target
Wants = network-online.target

[Service]
User=root
StateDirectory=pgadmin
RuntimeDirectory=pgadmin4
LogsDirectory=pgadmin
ExecStart=uwsgi \
      --http-socket 0.0.0.0:80 \
      --processes 1 \
      --threads 25 \
      --chdir /usr/local/lib/python3.9/site-packages/pgadmin4/ \
      --mount /=pgAdmin4:app
      --plugin python3
ExecReload=/bin/kill -HUP $MAINPID
ExecStop=/bin/kill -INT $MAINPID
Restart=always
Type=notify
StandardError=syslog
NotifyAccess=all
KillSignal=SIGQUIT

[Install]
WantedBy = multi-user.target
```
```

**Comment by khushboovashi** [comment]
Hi @mark260486, have you installed uWSGI properly?

**Comment by mark260486** [comment]
> Hi @mark260486, have you installed uWSGI properly?

Hi! Let me check. Any advices?

**Comment by adityatoshniwal** [comment]
I found this on SO - https://stackoverflow.com/questions/10748108/nginx-uwsgi-unavailable-modifier-requested-0

**Comment by mark260486** [comment]
@adityatoshniwal Your goggle-foo is much better than mine, duckduckgo didn't find this :(

I will check this and return with report asap, thanks!

**Comment by mark260486** [comment]
Adding ```plugins = python3``` to service file didn't help.

**Comment by mark260486** [comment]
Oh, I've miss backslash for new line in systemd file. It works now, sorry for bothering you, and thanks a lot for quick response. Have a nice day :)
