### ISSUE TITLE
Unable to start under Windows

### ISSUE THREAD

**Issue by Whippet0** [pgadmin-org/pgadmin4#7429]
Unable to start under Windows

pgadmin4-5.7-x64.exe
windows10
python 3.12

https://www.postgresql.org/ftp/pgadmin/pgadmin4/v5.7/windows/
![a4cf8f4fdb87af43d474410de0a2a24](https://github.com/pgadmin-org/pgadmin4/assets/46486374/b2cc47b9-0aca-47d6-8293-aed50e5ba897)

![9be06218cc8e135dcc5e01571189676](https://github.com/pgadmin-org/pgadmin4/assets/46486374/e6ab789a-b475-4b30-832e-5b40820d7e85)

**Comment by yogeshmahajan-1903** [comment]
@Whippet0 
From logs it seems you have V6 install not 5.7
Can you please uninstall all other versions? and install latest one 8.5?

**Comment by adityatoshniwal** [comment]
Hi @Whippet0,
This duplicates #7153 and workaround is mentioned in the ticket. To summarise, you need to add `C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\runtime` to windows PATH.
