### ISSUE TITLE
pgAgent Job: Issue with windows batch (exe  application+ arguments): command arguements not supported

### ISSUE THREAD

**Issue by rdczhzq** [pgadmin-org/pgadmin4#7430]
i,pgadmin-hackers.

I am using pgagent(edb_pgagent_pg16.exe) to config job for custom application （.exe) with arguments.

The problem I encountered if I add command parameters as showed below, I got result with "r" 

![image](https://github.com/pgadmin-org/pgadmin4/assets/168157852/d2376fa1-d54d-4286-8be7-b7141381affe)

but if I run the test.exxe without the parameters, the result is "s".

![image](https://github.com/pgadmin-org/pgadmin4/assets/168157852/ff06b581-4aab-4f8c-b71d-bfface417891)

I am wondering if the pgagent batch scripts doesn't support run exe with parameters? How shall I workaroud this problem. 

Looking foward to your reply.

**Comment by adityatoshniwal** [comment]
Can you check the pgAgent logs why it is failing? BTW, r is for running.

**Comment by rdczhzq** [comment]
Hi,Aditya

Thanks for your mail.

Please let me know where I can find pgAgent logs, thanks.

Yes, I know r stands for running. But actully it didn't.


Best regards,
Joe



***@***.***
 
From: Aditya Toshniwal
Date: 2024-04-26 13:03
To: pgadmin-org/pgadmin4
CC: rdczhzq; Author
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
Can you check the pgAgent logs why it is failing? BTW, r is for running.

**Comment by akshay-joshi** [comment]
@rdczhzq 

I've tested pgAgent in DEBUG mode on Windows but could not replicate the reported issue. To validate its functionality, I executed the following test scenario:

**Scenario 1:** Open a file using Notepad as a job step of pgAgent. 

https://github.com/pgadmin-org/pgadmin4/assets/1632882/903b54be-b300-495f-8939-8bdf5f30996a


**Scenario 2:**  Run a Python program to add two numbers and save the output in the file. 

https://github.com/pgadmin-org/pgadmin4/assets/1632882/3955c938-b061-479f-ae37-73cce976f390


Can you please try the notepad example?

**Comment by rdczhzq** [comment]
Hi Akshay

I have tested scenario 1: Failed with following log, and  i have checked the old log,it's the same observation I got when I reported the titled issue. 

For scenario 2: I don't have python installed, I think for time being, we need to sort out why i got null for jslresult and jslduration and jsistatus=r. 

Best regards,
Joe




The command line is as following:



Best regards,
Joe


***@***.*** 


 
From: Akshay Joshi
Date: 2024-05-15 15:19
To: pgadmin-org/pgadmin4
CC: rdczhzq; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
@rdczhzq
I've tested pgAgent in DEBUG mode on Windows but could not replicate the reported issue. To validate its functionality, I executed the following test scenario:
Scenario 1: Open a file using Notepad as a job step of pgAgent.
https://github.com/pgadmin-org/pgadmin4/assets/1632882/903b54be-b300-495f-8939-8bdf5f30996a
Scenario 2: Run a Python program to add two numbers and save the output in the file.
https://github.com/pgadmin-org/pgadmin4/assets/1632882/3955c938-b061-479f-ae37-73cce976f390
Can you please try the notepad example?

**Comment by rdczhzq** [comment]
More information.



***@***.***
 
From: 周志勤
Date: 2024-05-15 15:50
To: pgadmin-org/pgadmin4; pgadmin-org/pgadmin4
CC: Mention
Subject: Re: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
Hi Akshay

I have tested scenario 1: Failed with following log, and  i have checked the old log,it's the same observation I got when I reported the titled issue. 

For scenario 2: I don't have python installed, I think for time being, we need to sort out why i got null for jslresult and jslduration and jsistatus=r. 

Best regards,
Joe




The command line is as following:



Best regards,
Joe


***@***.*** 


 
From: Akshay Joshi
Date: 2024-05-15 15:19
To: pgadmin-org/pgadmin4
CC: rdczhzq; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
@rdczhzq
I've tested pgAgent in DEBUG mode on Windows but could not replicate the reported issue. To validate its functionality, I executed the following test scenario:
Scenario 1: Open a file using Notepad as a job step of pgAgent.
https://github.com/pgadmin-org/pgadmin4/assets/1632882/903b54be-b300-495f-8939-8bdf5f30996a
Scenario 2: Run a Python program to add two numbers and save the output in the file.
https://github.com/pgadmin-org/pgadmin4/assets/1632882/3955c938-b061-479f-ae37-73cce976f390
Can you please try the notepad example?

**Comment by rdczhzq** [comment]
As the issue can reproduce here (with more steplog information(null result)), I suggest this issue still needs to be investigated. 

if you need more logs, i can do a data collection. If needed, a Lync  session can be arranged to show you how the issue reproduce here.

**Comment by akshay-joshi** [comment]
@rdczhzq 

Do one thing stop the pgAgent service, get the path of the binary file and run from command line using "DEBUG -l 2  <connection-string>" parameters? OR

Setup a zoom session any time between **10am to 6pm IST**(GMT + 5:30) tomorrow.

**Comment by akshay-joshi** [comment]
@rdczhzq 

Could you please verify one more scenario? Run the command '**c:\release\test.exe measurement 4 20**' from the command prompt and confirm if the execution has been completed

**Comment by rdczhzq** [comment]
Hi Akshay

I have test the debug mode: please see the error log below, I will set up a zoom session for you to join.

Pleas note the password is valid for postgres.

Best regards,
Joe

C:\Users\Administrator>C:\PGSql\program\bin\pgagent.exe DEBUG -l 2  host=localhost port=5432 user=postgres password=123456 dbname=postgres
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #1]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #2]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #3]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #4]
DEBUG: Clearing all connections
DEBUG: No connections found!







***@***.***
 
From: Akshay Joshi
Date: 2024-05-16 18:38
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
@rdczhzq
Do one thing stop the pgAgent service, get the path of the binary file and run from command line using "DEBUG -l 2 " parameters? OR
Setup a zoom session any time between 10am to 6pm IST(GMT + 5:30) tomorrow.

**Comment by rdczhzq** [comment]
Hi Akshay

Due to specific reasons, I  am not able to use Zoom from here.

Do you have some alternative for me to use?

Best regards,
Joe



***@***.***
 
From: 周志勤
Date: 2024-05-17 09:12
To: pgadmin-org/pgadmin4; pgadmin-org/pgadmin4
CC: Mention
Subject: Re: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
Hi Akshay

I have test the debug mode: please see the error log below, I will set up a zoom session for you to join.

Pleas note the password is valid for postgres.

Best regards,
Joe

C:\Users\Administrator>C:\PGSql\program\bin\pgagent.exe DEBUG -l 2  host=localhost port=5432 user=postgres password=123456 dbname=postgres
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #1]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #2]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #3]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #4]
DEBUG: Clearing all connections
DEBUG: No connections found!







***@***.***
 
From: Akshay Joshi
Date: 2024-05-16 18:38
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
@rdczhzq
Do one thing stop the pgAgent service, get the path of the binary file and run from command line using "DEBUG -l 2 " parameters? OR
Setup a zoom session any time between 10am to 6pm IST(GMT + 5:30) tomorrow.

**Comment by rdczhzq** [comment]
Hi Akshay

I am not able to use Zoom here. Do you have alternatives?

Best regards,
Joe



***@***.***
 
From: 周志勤
Date: 2024-05-17 09:12
To: pgadmin-org/pgadmin4; pgadmin-org/pgadmin4
CC: Mention
Subject: Re: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
Hi Akshay

I have test the debug mode: please see the error log below, I will set up a zoom session for you to join.

Pleas note the password is valid for postgres.

Best regards,
Joe

C:\Users\Administrator>C:\PGSql\program\bin\pgagent.exe DEBUG -l 2  host=localhost port=5432 user=postgres password=123456 dbname=postgres
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #1]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #2]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #3]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #4]
DEBUG: Clearing all connections
DEBUG: No connections found!







***@***.***
 
From: Akshay Joshi
Date: 2024-05-16 18:38
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
@rdczhzq
Do one thing stop the pgAgent service, get the path of the binary file and run from command line using "DEBUG -l 2 " parameters? OR
Setup a zoom session any time between 10am to 6pm IST(GMT + 5:30) tomorrow.

**Comment by rdczhzq** [comment]
Hi Akshay

Some background below:

The following conf works with the job with another databse.

However two things I need to point out:

1.  The service was configured running under user admin. When I followed your instruction "run from command line using "DEBUG -l 2 " parameter",it was under user: Administrator,but as you see I supplied with correct username and password there. Will this cause the issue?

2. Anotherthing  I recalled that  when I installed the pgagent 2wks ago,  I was not able to create the pagent account: postgres as  it seems tha tthe password:123456 violates the windows password security policy, that's why I created a user called admin. Wil this cause the issue?

Best regards,
Joe 






***@***.***
 
From: 周志勤
Date: 2024-05-17 09:12
To: pgadmin-org/pgadmin4; pgadmin-org/pgadmin4
CC: Mention
Subject: Re: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
Hi Akshay

I have test the debug mode: please see the error log below, I will set up a zoom session for you to join.

Pleas note the password is valid for postgres.

Best regards,
Joe

C:\Users\Administrator>C:\PGSql\program\bin\pgagent.exe DEBUG -l 2  host=localhost port=5432 user=postgres password=123456 dbname=postgres
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #1]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #2]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #3]
DEBUG: Clearing all connections
DEBUG: No connections found!
DEBUG: Creating primary connection
DEBUG: Parsing connection information...
DEBUG: Creating DB connection: user=postgres password=***** dbname=postgres host=localhost port=5432 dbname=postgres
WARNING: Failed to create primary connection: connection to server at "localhost" (::1), port 5432 failed:    "postgres" Password ??
WARNING: Couldn't create the primary connection [Attempt #4]
DEBUG: Clearing all connections
DEBUG: No connections found!







***@***.***
 
From: Akshay Joshi
Date: 2024-05-16 18:38
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
@rdczhzq
Do one thing stop the pgAgent service, get the path of the binary file and run from command line using "DEBUG -l 2 " parameters? OR
Setup a zoom session any time between 10am to 6pm IST(GMT + 5:30) tomorrow.

**Comment by akshay-joshi** [comment]
@rdczhzq 

Another option could be Google Meet.

**Comment by rdczhzq** [comment]
Google is not accessible either here. :-(



***@***.***
 
From: Akshay Joshi
Date: 2024-05-17 14:23
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
@rdczhzq
Another option could be Google Meet.

**Comment by akshay-joshi** [comment]
@rdczhzq 

You can set up a meeting where I can join using browser, there is no restriction at our end

**Comment by rdczhzq** [comment]
***@***.***
 
From: Akshay Joshi
Date: 2024-05-16 21:09
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job: Issue with windows batch (exe application+ arguments): command arguements not supported (Issue #7430)
@rdczhzq
Could you please verify one more scenario? Run the command 'c:\release\test.exe measurement 4 20' from the command prompt and confirm if the execution has been completed

**Comment by rdczhzq** [comment]
Put this on hold until the following happens:
1. A join troubleshooting between Akshay and me is arranged as we google, zoom are not feasible.
2. A  fresh new installation of postgresql is ready for a new test.

**Comment by rdczhzq** [comment]
Close the issue. When I rewrote the program without reading Console input as following. This feature works. 

Console.CancelKeyPress += new ConsoleCancelEventHandler(CancelKeyPressHandler);
ConsoleKeyInfo keyInfo = Console.ReadKey(true);
if (keyInfo.Key.HasFlag(ConsoleKey.Escape))
{ }

![image](https://github.com/pgadmin-org/pgadmin4/assets/168157852/01238a20-67c6-4566-8611-0b4f384278a9)
![image](https://github.com/pgadmin-org/pgadmin4/assets/168157852/dd46fedc-23f8-4459-ad48-cae95e94a0de)
![image](https://github.com/pgadmin-org/pgadmin4/assets/168157852/617151f1-3f0f-4904-9088-0aae31800c7f)


There's one outstanding issue,however I would like to take it seperately.
1. notepad.exe is not schedulded in the pgagnet job.  Is there any configuration to be done so that the windows service can interact with the desktop, I assume the service is not able to interact with desktop by default?
