### ISSUE TITLE
Pgagent edb  installation failed due to  No postgreSQL 16(x64) installation found

### ISSUE THREAD

**Issue by rdczhzq** [pgadmin-org/pgadmin4#7431]
When I tried to install edb_pgagent_pg16.exe on a lenovo laptop without postgreSQL datbase (i.e. developer's laptop). installation failed with the following  error message;
![image](https://github.com/pgadmin-org/pgadmin4/assets/168157852/dbd040d4-68f8-4eb0-9b2b-76918b1e95bb)

The windows system I am using is as following:

Version	Windows 11 Home Chinese 
Version 23H2
OS version 22631.3447
Windows Feature Experience Pack 1000.22688.1000.0

The hardware is as following:

CPU: 12th Gen Intel(R) Core(TM) i5-12500H   2.50 GHz
RAM	16.0 GB (15.7 GB 可用)

**Comment by akshay-joshi** [comment]
This is not a pgAdmin issue. This seems to be a valid error as **pgAgent** requires a PostgreSQL database on the same machine.

**Comment by rdczhzq** [comment]
Hi,Akshay

thaks for  your feedback.

According to the documentation below, the pgagent can run remotely on a client without postgreSQL database co-located beside the scenario pgagent installed on a postgreSQL database server.

Creating a pgAgent Job — pgAdmin 4 8.5 documentation


"Use the Connection type switch to indicate if the step is performed on a local server (Local) or on a remote host (Remote). ", 

Best regards,
Joe



***@***.***
 
From: Akshay Joshi
Date: 2024-04-26 18:43
To: pgadmin-org/pgadmin4
CC: rdczhzq; Author
Subject: Re: [pgadmin-org/pgadmin4] Pgagent edb installation failed due to No postgreSQL 16(x64) installation found (Issue #7431)
This is not a pgAdmin issue. This seems to be a valid error as pgAgent requires a PostgreSQL database on the same machine.
