### ISSUE TITLE
Error "Cannot read properties of undefined (reading 'status')" display if the user creates a table via the ERD tool.

### ISSUE THREAD

**Issue by VBPrakash252** [pgadmin-org/pgadmin4#7438]
Trying to create a table through running scripts or manually in database, table is not created and getting Error "Cannot read properties of undefined (reading 'status')"

**Comment by anilsahoo20** [comment]
Hi @VBPrakash252 
Can you please share the System details, pgAdmin 4 package details and version of pgAdmin 4 you are using?

**Comment by adityatoshniwal** [comment]
@VBPrakash252  I'm wondering how should pgAdmin fix issues with such one liner descriptions with no useful information, wasting time for both the team and you.

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
