### ISSUE TITLE
pgAdmin fails to start when Ubuntu OS is upgraded to a major version

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#7439]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

pgAdmin fails to start when Ubuntu OS is upgraded to a major version, even to a supported version.

**To Reproduce**

1. Install pgAdmin to some ubuntu version.
2. Upgrade to a supported version.

**Expected behavior**

pgAdmin should work without issues.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: Any
 - Mode: Any
 - Package type: DEB

**Comment by yogeshmahajan-1903** [comment]
This is working fine. Now python version is painted while upgrading major version upgrade. This is working with desktop mode.
However, in server mode, mod_wsgi is compiled according system python and there is no way restrict mod_wsgi to use other python version for it.Refer this [link](https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html).
