### ISSUE TITLE
Windows cannot start 8.4

### ISSUE THREAD

**Issue by Whippet0** [pgadmin-org/pgadmin4#7440]
![image](https://github.com/pgadmin-org/pgadmin4/assets/46486374/99b1e474-b54a-4265-88a8-938858621abf)

**Comment by adityatoshniwal** [comment]
Hi @Whippet0,
This duplicates #7153 and workaround is mentioned in the ticket. To summarise, you need to add `C:\Users\Danii\AppData\Local\Programs\pgAdmin 4\runtime` to windows PATH.
