### ISSUE TITLE
Syntax Highlighting of Functions got lost in the SQL editor in version 8.5

### ISSUE THREAD

**Issue by Arnd-B** [pgadmin-org/pgadmin4#7441]
In version 8.5 the content of functions surronded by the $Body$ tag does not show any syntax highlighting anymore. All content between the tags in the Query Tool SQL editor is listed as "String" now. This made 8.5 unusable for me and I went back to version 8.4 as I am developing the functions in the SQL editor of PGAdmin.

**Comment by pravesh-sharma** [comment]
Duplicates #7294
