### ISSUE TITLE
PgAdmin QueryTool "loses connection" to the database after some time (since 8.5)

### ISSUE THREAD

**Issue by tvocetka** [pgadmin-org/pgadmin4#7443]
After upgrading to 8.5 on Mac (ARM), I observed that the Query Tool loses connection after some time. Query Tool cannot reconnect and I need to open a new Qery Tool window and retype/copy the query.

**To Reproduce**

1. Launch PGAdmin
2. Open and use Query Tool
3. Leave PGAdmin running in the background for some time (hours)
4. The Query Tool icon indicates the connection is lost
5. No action can be done in this Query Tool  window - the result stays blank

**Expected behavior**

Never happened in previous versions, I could use the Query Window for days without the need re-create it.

**Error message**

No message - just the result table stays empty

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma, 14.4.1
 - Version: 8.5
 - Mode: Desktop

**Additional context**

**Comment by adityatoshniwal** [comment]
This is fixed in #7372 and released with v8.6.
