### ISSUE TITLE
Backup database excluding multiple tables missing foreign data wrappers on pgadmin 8.6, please option for export Foreign Data Wrappers

### ISSUE THREAD

**Issue by lugowski1** [pgadmin-org/pgadmin4#7444]
**Describe the solution you'd like**

1. Secondary click on the database name
2. Backup option
3. Objects tab, option for create Foreign Data Wrappers

**Describe alternatives you've considered**

**Additional context**

**Comment by adityatoshniwal** [comment]
Hi @lugowski1,
As per the docs - https://www.postgresql.org/docs/15/app-pgdump.html, it doesn't provide any flag to pass specific foreign data wrappers in the command. However, there is one flag `--include-foreign-data` which can be used to pass a pattern. We can implement this if this is your requirement.

Thanks.

**Comment by khushboovashi** [comment]
No response from the author, closing the issue.
