### ISSUE TITLE
View columns made by EXTRACT cannot be used in Query Tool.

### ISSUE THREAD

**Issue by DaniWe** [pgadmin-org/pgadmin4#7446]
Have a view with Year, Month and/or Day as numeric view columns defined as:
    EXTRACT(year FROM f.recorddate::timestamp without time zone) AS "Year",
    EXTRACT(month FROM f.recorddate::timestamp without time zone) AS "Month",
    EXTRACT(day FROM f.recorddate::timestamp without time zone) AS "Day",

Execute a simple query:
SELECT * FROM service.yxney_fuelrecord WHERE Year>2022

Result:
-----
ERROR:  column "year" does not exist
LINE 7: SELECT * FROM service.yxney_fuelrecord WHERE Year>2022
                                                     ^
HINT:  Perhaps you meant to reference the column "yxney_fuelrecord.Year". 

SQL state: 42703
Character: 407
------

No other alternatives work either, like:
SELECT * FROM service.yxney_fuelrecord WHERE yxney_fuelrecord .Year>2022
SELECT * FROM service.yxney_fuelrecord WHERE service.yxney_fuelrecord.Month=6
SELECT * FROM service.yxney_fuelrecord ORDER BY Day;

The Query Tool colors Year, Month and Day as if they are reserved keywords and refuse to acknowledge them as columns no matter what. Cannot be used anywhere in a query, even if prefixed.

![Year-Month-Day-fails](https://github.com/pgadmin-org/pgadmin4/assets/10460980/fae0e3e7-537c-422a-b840-23971ea71372)

pgAdmin 7.8 on Windows 11.

**Comment by adityatoshniwal** [comment]
Hi @DaniWe,
What is the behaviour when you run it from psql tool?

**Comment by adityatoshniwal** [comment]
Hi @DaniWe,
If its the same behaviour with PSQL then Query tool is working fine. You'll probably need to fix the SQL you're using.
You can take help from pgsql-admin@postgresql.org
I'm closing this issue.
Thanks.
