### ISSUE TITLE
Error installing version 8.6

### ISSUE THREAD

**Issue by ac1953** [pgadmin-org/pgadmin4#7453]
**Desktop (please complete the following information):**
 - OS: [Debian]
 - Version: [11]
 - Mode: [Server]
 - Browser (Chrome / Mozilla)
 - Package type: [Python]

Good morning.
Today I did update my pgadmin4 (8.5) with the new version. The installation procedure didn't show any flows, but, when I started it with the following command:

gunicorn --bind 0.0.0.0:5000 --workers=1 --threads=25 --chdir /usr/local/bin/pgadmin4/lib/python3.9/site-packages/pgadmin4 pgAdmin4:app &

I got the following error in log:

importerror: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/bin/pgadmin4/lib/python3.9/site-packages/werkzeug/urls.py)

Installed werkzeug is 3.0.3 (After pgadmin install. Before it was 2.3.8)

Python version is 3.9

Greetings

**Comment by akshay-joshi** [comment]
Duplicate #7459.

Please check the workaround given on #7459
