### ISSUE TITLE
Error running version 8.6

### ISSUE THREAD

**Issue by nikita-fuchs** [pgadmin-org/pgadmin4#7454]
**Describe the bug**

Can't run v8.6 after installation on Mac, receiving the "pgAdmin is damaged and can’t be opened. You should move it to the Trash." message.

**To Reproduce**

1. Download and install 8.6 arm edition for mac
2. Run it
3. See the error

**Expected behavior**

pgAdmin would start normally.

**Error message**

 "pgAdmin is damaged and can’t be opened. You should move it to the Trash." message.

**Desktop (please complete the following information):**
 - OS: Monterey 14.4.1 on an M3 Max
 - Version: 8.6
 - Mode: Desktop

**Comment by anilsahoo20** [comment]
Hi @nikita-fuchs 
Have you downloaded the pgAdmin 4 from [here](https://www.pgadmin.org/download/)? 
Please uninstall the pgAdmin 4, and try installing from the above site.

**Comment by nikita-fuchs** [comment]
Hey, yes, this is where I've dowloaded it from. I've downgraded to version 8.5 for now which works fine.

**Comment by akshay-joshi** [comment]
@nikita-fuchs 

I have downloaded it from [here](https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.6/macos/), unable to reproduce the issue.

<img width="400" alt="Installer" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/e9c5760c-cc1c-41cf-b4b9-8bfb37214d66">

**Comment by nikita-fuchs** [comment]
Alright, redownloading and installing again did work indeed for me this time 🤷‍♂️ thanks.
