### ISSUE TITLE
Improve the Upgrade Experience

### ISSUE THREAD

**Issue by anthonydb** [pgadmin-org/pgadmin4#7455]
**Describe the solution you'd like**

Upgrading pgAdmin requires a bit more work than I'd like and is more involved than most applications I run. On Windows, particularly, if a user installs pgAdmin via the EDB PostgreSQL installer, upgrading requires uninstalling that version before downloading and installing the new version -- that is, if a user doesn't want to end up with two versions of pgAdmin on their system.

Instead, I would like to be prompted that a new pgAdmin version is available, and then if I want to upgrade simply click a button to download and install the new version. I'd like this to be available on Windows and macOS at least. Not sure if Linux is feasible.

Many, many applications operate this way, and it would be very nice if pgAdmin did as well.

**Describe alternatives you've considered**

Continue the current paradigm, which isn't horrible but is more involved.

**Comment by RohitBhati8269** [comment]
Duplicate :- https://github.com/pgadmin-org/pgadmin4/issues/5766
