### ISSUE TITLE
Selecting blocks of code doesnt work

### ISSUE THREAD

**Issue by nprgin** [pgadmin-org/pgadmin4#7456]
Lets say I have a cte, with cte_1, cte_2, cte_3, cte_3 uses cte_1, i want to be able to select cte_1 and everything inside the cte_3 so i dont have to comment my code always, you killed this with 8.4 update i think, also it doesnt work in 8.5 or 8.5, this is a game breaking bug i dont know why its not fixed yet. Also, why would the color of everything inside some delimtier $$ be same as comment!???!?!?!?!

**Comment by adityatoshniwal** [comment]
Duplicates #7293.
Please update to 8.6 for $$ related issue.
