### ISSUE TITLE
Query info notifier timeout field missing in from Query Tool node in Preferences Dialog

### ISSUE THREAD

**Issue by oscarmacdonald** [pgadmin-org/pgadmin4#7458]
**Describe the bug**

According to [the documentation](https://www.pgadmin.org/docs/pgadmin4/8.4/preferences.html#the-query-tool-node):

> Use the Query info notifier timeout field to control the behaviour of the notifier that is displayed when query execution completes.

However in pgAdmin 4 v8.6 this field isn't available

**To Reproduce**

1. Go to File
2. Click on Preferences
3. Go to Query Tool
4. Go to Display
5. Query info notifier timeout field is not present, only "Show query success notification?"

**Expected behavior**

Either "Query info notifier timeout field" should be present, or documentation updated with correct information.

**Screenshots**

Expected (from documentation) ![expected](https://www.pgadmin.org/static/docs/pgadmin4-8.4-docs/_images/preferences_sql_display.png)

Actual:
![actual](https://github.com/pgadmin-org/pgadmin4/assets/107375184/eb3d5316-7892-4981-8cf4-bedf17ab4301)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2 (OS Build 22631.3447)
 - Mode: Desktop
 - Package type: exe

**Comment by adityatoshniwal** [comment]
Docs need to be updated. The setting is removed.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-21/
Package: arm64
Environment: macOs Ventura 13.5.1
