### ISSUE TITLE
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' -> upgrade Flash-Login to 0.6.3+

### ISSUE THREAD

**Issue by bwakkie** [pgadmin-org/pgadmin4#7459]
After a pip upgrade I am getting (and have been getting in previous upgrades) the following error:

`ImportError: cannot import name 'url_decode' from 'werkzeug.urls'
`
The reason this is not working is that Flask-Login 0.6.2 is not compattible with Werkzeug 3.x

Previously I would downgrade Werkzeug belog 3.0.0 but now upgrading Flask-Login to 0.6.3 or above works too.

To fix this Flask-Login needs to be upgraded to 0.6.3 as from then Werkzeug 3.x if supported

`pip install git+https://github.com/maxcountryman/flask-login.git 
`helped me but it is version 0.7-dev so maybe you can try first 
`pip install Flask-Login==0.6.3
`

source: https://stackoverflow.com/questions/77215107/importerror-cannot-import-name-url-decode-from-werkzeug-urls

**Comment by bwakkie** [comment]
ok i'll do this the next update see how that works. Thx!

**Comment by khushboovashi** [comment]
Hi, please reopen it if you still reproduce the issue with the new release.
