### ISSUE TITLE
Debugger shows error if we stop the debugging after continue/stop

### ISSUE THREAD

**Issue by pravesh-sharma** [pgadmin-org/pgadmin4#7460]
**To Reproduce**

1. Select any function and start debugging.
2. Click on the continue/start button.
3. Again click on the continue/start button.
4. Click on the stop button.
5. Error will be displayed.

**Expected behavior**
The debugger should stop and close like in normal cases.

**Screenshots**
Attaching recording

https://github.com/pgadmin-org/pgadmin4/assets/111979571/88de0479-238f-4397-9f88-5d5ecc21f422

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Version: 8.6
 - Mode: Desktop

**Comment by khushboovashi** [comment]
Once the debugging session is completed, it's not possible to restart. It will always give the null output. We have tested with debugger behaviour the psql sessions. So, closing the issue.
