### ISSUE TITLE
pgadmin4 web gui "This site can't be reached"

### ISSUE THREAD

**Issue by blueguy23** [pgadmin-org/pgadmin4#7463]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Following the installation guide here - https://www.pgadmin.org/download/pgadmin-4-apt/, I am not able to log into the pgadmin web interface. 

**To Reproduce**

1. Use the command to install pgadmin4: 
sudo apt install pgadmin4

2. After running the command sudo /usr/pgadmin4/bin/setup-web.sh I am unable to access the web interface they provide which is http://127.0.0.1/pgadmin4 

**Expected behavior**
The link should load and take me to the Web GUI and load successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version: [22.04]
 - Mode: [Server]
 - Browser: [Chrome]
 - Package type: [DEB]

**Additional context**

I have also tried including the port number http://127.0.0.1/pgadmin4:5432
and haven't had any luck.

**Comment by adityatoshniwal** [comment]
@blueguy23  please share the screenshot and pgadmin logs.

**Comment by blueguy23** [comment]
~$ cd /usr/pgadmin4/bin
/usr/pgadmin4/bin$ ./pgadmin4
./pgadmin4: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory

![PGadmin4 webgui](https://github.com/pgadmin-org/pgadmin4/assets/63981435/bdc066c4-54a8-4182-9db6-d2336db3712f)

**Comment by adityatoshniwal** [comment]
Try this `sudo apt-get install libasound2` and start pgAdmin.

**Comment by blueguy23** [comment]
Hmm, after installing I've run into this error. I'm confused as to why it is trying to display when I want to access the Web GUI. 

./pgadmin4 --server
[2136:2136:0509/055318.816016:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[2136:2136:0509/055318.816386:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.

**Comment by qasimtahir91** [comment]
If you are unable to access pgadmin using web url http://127.0.0.1/pgadmin4, below are the steps to find the root cause 

1. Try to access url in browser. if it fails
2. share the logs at below location. 
/var/log/apache2/error.log
These are apache2 logs. It might track error message when http request hits.

Probably when some library or .so file is missing, an error gets recorded at this log file (/var/log/apache2/error.log) showing the cause of error

**Comment by khushboovashi** [comment]
> Hmm, after installing libasound2 successfully, I've run into this error. I'm confused as to why it is trying to display when I want to access the Web GUI. I'm running pgadmin4 on a separate machine and trying to access the web gui from my laptop
> 
> ./pgadmin4 --server [2136:2136:0509/055318.816016:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY [2136:2136:0509/055318.816386:ERROR:env.cc(255)] The platform failed to initialize. Exiting.

You don't need to run ./pgadmin4 server separately, it is already running behind Apache. Just try to access the url from browser directly.

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing issue.
