### ISSUE TITLE
Be able to log in using oauth without an email address

### ISSUE THREAD

**Issue by bergethon** [pgadmin-org/pgadmin4#7465]
**Describe the solution you'd like**

We're currently deploying pgAdmin in our OpenShift cluster, and we're planning to integrate pgAdmin with OpenShift OAuth.
The problem we are facing is that the user objects within OpenShift does not hold an email address.

So naturally, when someone tries to log in using OAuth, they get the error message saying:

"Invalid email address". 

I've read the documentation and interpret it such that creating a pgAdmin account without a valid email is not possible. 

--

Would it be possible to implement a feature for not requiring email address for users? 

I'd imagine the issue is quite similar to this one for Grafana, where Grafana required email address, but OpenShift user objects does not contain it: https://github.com/grafana/grafana/issues/9585

Is there any specific reason why email is a must for registering an account?

**Comment by yogeshmahajan-1903** [comment]
@bergethon 
If there are other parameters provided by openshift OAuth, then you use that by specifying it with config - OAUTH2_USERNAME_CLAIM. e.g login, mail etc.

**Comment by bergethon** [comment]
@yogeshmahajan-1903 
Thanks for the reply.

I've looked into the OAUTH2_USERNAME_CLAIM setting, and that would indeed solve the issue where a valid email is availible at a certain claim, such as "mail".

In OpenShift this is not the case, which begs the question - why are email addresses required for registering an account?

I'm guessing there is a reason behind this?

**Comment by yogeshmahajan-1903** [comment]
@bergethon 
Valid email is required only at the container startup. Then subsequent logins with OAuth2 will not require email.
If you do not have email in the profile returned by OAuth2 provider but if you specify some other parameter which is returned in profile returned by provider as OAUTH2_USERNAME_CLAIM, then that will be used as username.

**Comment by bergethon** [comment]
Thanks for clarifying!

My mistake was including email in the scope. Instead of not returning an email at all, OpenShift returns your username in the email field, and of course trying to validate it as such.

Removing email from the claim leaves the email field blank. 

Setting the scope "profile", and the OAUTH2_USERNAME_CLAIM "preferred_username" worked. 
(I had previously tried with scope "profile email", which would not leave the email field empty, which was what I not realized) 

Thank you for your time! :)

**Comment by SOLDIERz** [comment]
@bergethon What do you used now for the "scope" and "username_claim" to get it working with OpenShift OAuth?
