### ISSUE TITLE
License incompatibility - proprietary licence in pgadmin4

### ISSUE THREAD

**Issue by laktibarada** [pgadmin-org/pgadmin4#7472]
PGAdmin4 should run whole under open-source licenses.
But after running license scan, following file was found, where the licence is proprietary and therefore we can not use the PGadmin4 in our company (according to EU & German law).

Is it possible to release this file also under an OSS license?

- web/pgadmin/static/img/terminal.svg:  [terminal.svg](ttps://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/static/img/terminal.svg?short_path=c7a4380)
https://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/static/img/terminal.svg?short_path=c7a4380

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
<!--! Font Awesome Pro 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
<path d="M9.4 86.6C-3.1 74.1-3.1 53.9 9.4 41.4s32.8-12.5 45.3 0l192 192c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L178.7 256 9.4 86.6zM256 416H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H256c-17.7 0-32-14.3-32-32s14.3-32 32-32z"/></svg>
```

**Comment by adityatoshniwal** [comment]
The changes are committed. Please re-scan.

**Comment by laktibarada** [comment]
Looks great, thanks a lot!
