### ISSUE TITLE
ERD Tool - Primary key constraints is not updated after the checkbox for primary key is unchecked

### ISSUE THREAD

**Issue by petkorutesic** [pgadmin-org/pgadmin4#7476]
**Changing a primary key constraints or even deleting attributes does not change the constraints in the "Constraints" tab**

Removing an attribute does not change the constraints defined on that attribute. 

**To Reproduce**

1. Define the primary key constraint on a table and save the whole project in the ERD Tool.

3. Double-click on the table in the diagram, and the form for editing table properties will open. The checkbox for the primary key can now be unchecked. However, saving your changes does not exclude the primary key constraints. The primary key constraint can still be found if you open the "Constraints" tab. Moreover, even if we completely remove the attribute on which the primary constraint is defined, the constraint still remains in the "Constraints" tab.

4. This can cause problems and is annoying if you click on the "Generate SQL" option which generates SQL DDL statements with unwanting constraints or constraints on unexisting attributes.

**Expected behavior**

It would be natural that the ERD Tools shows a dialogue form to confirm an automatic delete of the primary key constraint if this constraint is removed in the tab "Columns" that contains the list of attributes.

**Screenshots**

<img width="902" alt="Screenshot 2024-05-15 at 12 52 23" src="https://github.com/pgadmin-org/pgadmin4/assets/4040507/5207bcb3-4c0f-4c93-94f6-08456dff8773">

After we remove the attribute with the primary key:
<img width="896" alt="Screenshot 2024-05-15 at 13 48 23" src="https://github.com/pgadmin-org/pgadmin4/assets/4040507/76f5b778-ef0e-4126-9608-4d41be6d29ea">

However, the constraint is still there:
<img width="894" alt="Screenshot 2024-05-15 at 13 33 12" src="https://github.com/pgadmin-org/pgadmin4/assets/4040507/f908b833-cb33-4bd5-8bf4-90f695dae982">

**Error message if the generated DDL SQL is run**

<img width="1032" alt="Screenshot 2024-05-15 at 13 53 17" src="https://github.com/pgadmin-org/pgadmin4/assets/4040507/f5f9aa87-1711-4941-9513-c007105149a9">

**Software**
 - MacOS: [OSX Sonoma 14.5 - macOS-14.5-x86_64-i386-64bit]
 - pgAdmin4 Version:  8.6 
                 NW.js Version: 0.77.0
 - Mode: Desktop 
 - Browser: Chromium 114.0.5735.91

**Comment by adityatoshniwal** [comment]
I can confirm its a bug.

**Comment by anilsahoo20** [comment]
I found same issues with Foreign key, Unique and Exclude constraint in Table dialog as well as in ERD tool table dialog. So fixed all the issues for all the constraints except Check constraint. 

While testing this please consider looking into the other constraints also.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-19/).

Env:
OS - macOS Sonoma 14.5
Mode - Desktop
