### ISSUE TITLE
Schema Diff does not find differences on 'GRANT USAGE ON SCHEMA'

### ISSUE THREAD

**Issue by fjf2002** [pgadmin-org/pgadmin4#7477]
**Describe the bug**

Schema Diff does not find differences on 'GRANT USAGE ON SCHEMA'.

**To Reproduce**
Given a user `myuser`,

1. On the first database, execute:
```sql
CREATE SCHEMA foo;
GRANT USAGE ON SCHEMA foo TO myuser;
```
2. On the second database, execute:
```sql
CREATE SCHEMA foo;
```
3. Perform a schema diff.

**Expected behavior**
The obvious difference should be listed:
```sql
GRANT USAGE ON SCHEMA foo TO myuser;
```

But it won't. No differences are shown.

**Error message**
None.

**Desktop (please complete the following information):**
 - Postgres Docker Container 16.3
 - pgadmin Docker Container 8.6

**Comment by khushboovashi** [comment]
Duplicates #4968.
