### ISSUE TITLE
pgAgent Job issue: Couldn't get a connection to the database when  local SQL mode specified in another database other than postgres

### ISSUE THREAD

**Issue by rdczhzq** [pgadmin-org/pgadmin4#7478]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

pgAgent Job issue: Couldn't get a connection to the database when  local SQL mode specified in another database other than postgres
**To Reproduce**

Step to reproduce:
1. Create a job (local/SQL)
2. Select  another database other than default postgres
3. Create SQL scripts & scheduler task
4. Run the job

**Expected behavior**
The jobstep log should show corresponding result, e.g. s.

**Error message**
The jobstep have a information with status:r and error message: Couldn't get a connection to the database 

**Screenshots**
![image](https://github.com/pgadmin-org/pgadmin4/assets/168157852/1a76c546-9b85-46a2-ac66-db196925885b)
![image](https://github.com/pgadmin-org/pgadmin4/assets/168157852/ff0a462b-1044-42ea-82a6-ba746e216b44)

**Desktop (please complete the following information):**
 - OS:Windows Server 2019
 - Version:Windows Server 2019
 - Mode: Server
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

When I switch the database back to default postgres, the job runs succesfully without any problem.

**Comment by akshay-joshi** [comment]
@rdczhzq 

Find your %AppData%\Roaming\postgresql\pgpass.conf file under the user whose credentials you have provided for the pgAgent installer. For my computer, it's C:\Users\enterprisedb\AppData\Roaming\postgresql\pgpass.conf

Change the line localhost:5444:edb:enterprisedb:edb to localhost:5444:*:enterprisedb:edb (Format: HOST:PORT:DATABASE:USER:PASSWORD)

<img width="549" alt="Solution" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/e59f42b8-e9ff-4306-98c3-5e595a70f514">

**Comment by rdczhzq** [comment]
Hi Akshay

It works after replace with *.

Will you include this into the end of May release?

Best regards,
Joe



***@***.***
 
From: Akshay Joshi
Date: 2024-05-16 21:17
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job issue: Couldn't get a connection to the database when local SQL mode specified in another database other than postgres (Issue #7478)
@rdczhzq
Find your %AppData%\Roaming\postgresql\pgpass.conf file under the user whose credentials you have provided for the pgAgent installer. For my computer, it's C:\Users\enterprisedb\AppData\Roaming\postgresql\pgpass.conf
Change the line localhost:5444:edb:enterprisedb:edb to localhost:5444:*:enterprisedb:edb (Format: HOST:PORT:DATABASE:USER:PASSWORD)
Solution.png (view on web)

**Comment by akshay-joshi** [comment]
@rdczhzq 

This is not an issue with pgAgent; it is related to PostgreSQL's behavior in providing the correct entry in the pgpass.conf file

Hence closing this issue.

**Comment by rdczhzq** [comment]
Will you transfer the ticket to PostgreSQL or shall I open one on PostSQL ? how to proceed?

Best regards
Joe



***@***.***
 
From: Akshay Joshi
Date: 2024-05-17 13:58
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job issue: Couldn't get a connection to the database when local SQL mode specified in another database other than postgres (Issue #7478)
@rdczhzq
This is not an issue with pgAgent; it is related to PostgreSQL's behavior in providing the correct entry in the pgpass.conf file
Hence closing this issue.

**Comment by akshay-joshi** [comment]
This is not a bug in PostgreSQL either. [Check](https://www.postgresql.org/docs/current/libpq-pgpass.html)

**Comment by rdczhzq** [comment]
So who should be blamed in this case? Who is responsible for populating this file correctly during installation?

Best regards,
Joe



***@***.***
 
From: Akshay Joshi
Date: 2024-05-17 14:11
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job issue: Couldn't get a connection to the database when local SQL mode specified in another database other than postgres (Issue #7478)
This is not a bug in PostgreSQL either. Check

**Comment by akshay-joshi** [comment]
@rdczhzq 

Why you would like to blame anyone? This is a process defined by PostgreSQL. The pgpass.conf file should be modified by the administrator who has installed the database server or owns that machine.

It is similar to "pg_hba.conf" where it's the user's responsibility to change as per his/her requirement.

**Comment by rdczhzq** [comment]
Hi Akshay

In our culture, blame=be responsible for . Now I got it. The DBA for postgres should be responsible for populating this data correct.

Best regards,
Joe



***@***.***
 
From: Akshay Joshi
Date: 2024-05-17 14:34
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAgent Job issue: Couldn't get a connection to the database when local SQL mode specified in another database other than postgres (Issue #7478)
@rdczhzq
Why you would like to blame anyone? This is a process defined by PostgreSQL. The pgpass.conf file should be modified by the administrator who has installed the database server or owns that machine.
It is similar to "pg_hba.conf" where it's the user's responsibility to change as per his/her requirement.
