### ISSUE TITLE
Dark Theme starts with a big white screen

### ISSUE THREAD

**Issue by bengosu** [pgadmin-org/pgadmin4#7481]
Dark Theme starts with a big white screen, effectively flash-banging me until I select something from a table or so.

![image](https://github.com/pgadmin-org/pgadmin4/assets/4634482/c97c7ea2-14b3-4df0-8a5c-2456ea8f02c4)

**Comment by HubKing** [comment]
It happens with "High Contrast", which I think is supposed to be "dark high contrast", too. Not just start, if you close all the tabs, the background is white. It should be black. 

Also, high contrast's selected item is white on light blue, which makes it difficult to see. It should be dark blue

![image](https://github.com/pgadmin-org/pgadmin4/assets/10900489/5e2af15a-1892-48a3-98d6-0c9557fec9a5)

The same for the menu bar's background. It also should be dark blue.

![image](https://github.com/pgadmin-org/pgadmin4/assets/10900489/0eb46dad-1ae5-4235-bab8-2fcdacda506d)

**Comment by RohitBhati8269** [comment]
Tested and verified on candidate build: [candidate-build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-18/)
Environment: MacOs
