### ISSUE TITLE
Pgadmin install error in Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by abhay-scaletech** [pgadmin-org/pgadmin4#7482]
- On your website mentioned pagadmin4 was supported in Ubuntu 24.04 but it's not working
- I have attached an error screenshot. so please find the attachment

![image](https://github.com/pgadmin-org/pgadmin4/assets/92075255/69da0ad0-97d7-40e4-874a-796972711b08)
![image](https://github.com/pgadmin-org/pgadmin4/assets/92075255/7b219d1c-c07b-4873-a2f5-6f8f86fe6dc6)

**Comment by adityatoshniwal** [comment]
It also mentions the start version - v8.7 which is not released yet. Duplicates #7437
