### ISSUE TITLE
Linter does not handle C-Style escape string constants (postgresql.org 4.1.2.2)

### ISSUE THREAD

**Issue by sammy-hughes** [pgadmin-org/pgadmin4#7485]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

The PG Admin 8.5 release does not properly lint C-Style string constants as described in section [4.1.2.2 of the PostgreSQL documentation](https://www.postgresql.org/docs/16/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE]). This has previously been properly handled, but is not currently.

**To Reproduce**

The following is colored as if it is a normal string, as if there was a string-literal, an identifier `bar`, and an unterminated string-literal:

```sql
SELECT E'foo\'bar';
```

**Expected behavior**

I expect the linter to provide syntax highlighting for this feature, and for the above to be recognized as a string-literal of `foo'bar` instead of as a string-literal `foo\` followed by invalid sequences.

Previously, this was properly handled. I know this was handled properly in the 5.x and 6.x series, but I do not know what version this regressed on. In addition to handling escaped  quotes, the initial [Ee] was colored as a keyword.

**Error message**

N/A

**Screenshots**

N/A -- can provide if the above steps to reproduce are not sufficiently clear.

**Desktop (please complete the following information):**
 - OS: macOS-14.4.1-arm64-arm-64bit
 - Version: 8.5
 - Mode: Desktop
 - Browser (if running in server mode): N/A, help info reports Chromium 114.0.5735.91
 - Package type: installed via homebrew

**Additional context**

Can I haz my e-strings back?

**Comment by pravesh-sharma** [comment]
Issue fixed, verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-22/).

Env:
OS - macOS Sonoma
Mode - Desktop

**Comment by adityatoshniwal** [comment]
I'm reopening this as the fix was incorrect and has been reverted. I've raised this to the CodeMirror team https://discuss.codemirror.net/t/postgresql-c-style-escape-using-e/8346.

**Comment by anilsahoo20** [comment]
Issue fixed and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-18/
Environment:
OS: OSX ventura 13.5.1
Package: arm64

**Comment by sammy-hughes** [comment]
Thanks for the fix, guys! Looking forward to it making the release.
