### ISSUE TITLE
Display user friendly message if user hits 'Recover Password' button with empty password field

### ISSUE THREAD

**Issue by automationSele** [pgadmin-org/pgadmin4#7487]
**Describe the bug**
When user hits 'Recover Password' button on reset_password page without providing email in Email Address field, insetad of showing user friendly message, it displays JSON output.

**To Reproduce**

1. Go to Login Page
2. Click on 'Forgot your password?' link to navigate to Password reset page.
3. Hit Recover Password button without entering email address. Here, it instead of prompting user for email address, the application crashes/shows JSON output.

**Expected behavior**
When user hits Recover Password button with empty email address field, user must be prompted to enter password.

**Error message**

**Screenshots**

<img width="960" alt="password_reset" src="https://github.com/pgadmin-org/pgadmin4/assets/19538363/68730c9a-dbd7-4bfc-8105-d1f4e7dd5815">

**Desktop (please complete the following information):**
 - OS: [Rockey]
 - Version: [8.9]
 - Mode: [ Server]
 - Browser (if running in server mode): [Firefox, Chrome]
 - Package type: [Source code] - I am on master branch with latest commit id : ad5bb0b190a2fb7f22e5c99ce1c8581a35525862.
 -

**Comment by usmanmuzaffar15** [comment]
Verified. Now a user friendly message displays.
Thanks
