### ISSUE TITLE
Print support

### ISSUE THREAD

**Issue by rdczhzq** [pgadmin-org/pgadmin4#7488]
**Describe the solution you'd like**

Add print function for SQL/other defintiion

**Describe alternatives you've considered**

As the GUI layout is not consistent, e.g. properties of store procedures doesn't even have a menu called File, let alone:Print.

But we can add print function on the context menu if user clicks SQL table and right click the mouse, the user is able to print the SQL. 

This will be less work than a full support of the  print functionality.

**Additional context**

**Comment by pravesh-sharma** [comment]
Hi @rdczhzq,

You can use the create script feature by right-clicking on object.

**Comment by rdczhzq** [comment]
Hi Pravesh

I need to print instead of creating scripts for the object. Could you please clarify what's your purpose by creating scripts.

Thanks and best regards,
Joe



***@***.***
 
From: Pravesh Sharma
Date: 2024-05-24 18:41
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] Print support (Issue #7488)
Hi @rdczhzq,
You can use the create script feature by right-clicking on object.
