### ISSUE TITLE
pgAdmin:Commented SQL statement executes when toggle back/forth for the  SQL statement and above line.

### ISSUE THREAD

**Issue by rdczhzq** [pgadmin-org/pgadmin4#7489]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
Commented SQL statement executes when toggle back/forth for the  SQL statement and above line.

**To Reproduce**

1. Prepare the database using the sample database below
https://www.postgresqltutorial.com/postgresql-getting-started/load-postgresql-sample-database/

2. Open a Query tool for the dvdrental database and execute the sql, the result is successful.
set search_path to public;
select * from actor limit 10;

3. Add 2 empty commented  line bewteen the first and second SQL statement and execute the SQL, the result is succesful.
set search_path to public;
--
--
select * from actor limit 10;

4. Comment the select SQL and execute the SQL, successful.

5. Uncomment the select SQL and execute the SQL, successful

6. Comment the select SQL again and execute, the commented SQL can still execute.

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by pravesh-sharma** [comment]
Hi @rdczhzq,

Can you please share a screen recording of the issue?

**Comment by rdczhzq** [comment]
Hi Pravesh

I have reproduce procedure included in the ticket. Do you have difficulty in reproducing the issue? Please let me know.

Best regards,
Joe



***@***.***
 
From: Pravesh Sharma
Date: 2024-05-24 18:38
To: pgadmin-org/pgadmin4
CC: Joe; Assign
Subject: Re: [pgadmin-org/pgadmin4] pgAdmin:Commented SQL statement executes when toggle back/forth for the SQL statement and above line. (Issue #7489)
Hi @rdczhzq,
Can you please share a screen recording of the issue?

**Comment by pravesh-sharma** [comment]
Hi @rdczhzq,

I am not able to reproduce the issue with the provided steps that's why I asked if you could share a screen recording of the issue.

**Comment by rdczhzq** [comment]
[pgAdmin 4 2024-05-27 13-04-05.zip](https://github.com/pgadmin-org/pgadmin4/files/15451133/pgAdmin.4.2024-05-27.13-04-05.zip)

Please note when I comment the sql, I am using control + / instead of adding -- at the beginning of the line.

**Comment by rdczhzq** [comment]
Hi Pravesh

I have uploaded the screen recording pof the issue in the ticket.

Please note: when I comment the sql, I am using keyboard control + / instead of putting -- at the beginning of line. I guess you are not capturing the control + / for the comment so you keep executing the previous sql.

Best regards,
Joe



***@***.***
 
From: Pravesh Sharma
Date: 2024-05-27 12:14
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAdmin:Commented SQL statement executes when toggle back/forth for the SQL statement and above line. (Issue #7489)
Hi @rdczhzq,
I am not able to reproduce the issue with the provided steps that's why I asked if you could share a screen recording of the issue.

**Comment by adityatoshniwal** [comment]
From the screen recording it clear that you've selected the query. When you're selecting any part of SQL, only selected part goes to the server irrespective if it is commented outside the selection.
Not an issue.

**Comment by rdczhzq** [comment]
No.  

The issue here is control + / or -- at the beginning of the SQL. 

If you put -- at the beginning of the SQL , it will never execute.

Please re-open the case.

Best  regards,
Joe



***@***.***
 
From: Aditya Toshniwal
Date: 2024-05-27 13:21
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAdmin:Commented SQL statement executes when toggle back/forth for the SQL statement and above line. (Issue #7489)
From the screen recording it clear that you've selected the query. When you're selecting any part of SQL, only selected part goes to the server irrespective if it is commented outside the selection.
Not an issue.

**Comment by rdczhzq** [comment]
Ok, I retest this. Yes the behavior is according to what you described.

But this is misleading for us as we comment out something, but it executes.



***@***.***
 
From: 周志勤
Date: 2024-05-27 13:25
To: pgadmin-org/pgadmin4; pgadmin-org/pgadmin4
CC: Mention
Subject: Re: Re: [pgadmin-org/pgadmin4] pgAdmin:Commented SQL statement executes when toggle back/forth for the SQL statement and above line. (Issue #7489)
No.  

The issue here is control + / or -- at the beginning of the SQL. 

If you put -- at the beginning of the SQL , it will never execute.

Please re-open the case.

Best  regards,
Joe



***@***.***
 
From: Aditya Toshniwal
Date: 2024-05-27 13:21
To: pgadmin-org/pgadmin4
CC: Joe; Mention
Subject: Re: [pgadmin-org/pgadmin4] pgAdmin:Commented SQL statement executes when toggle back/forth for the SQL statement and above line. (Issue #7489)
From the screen recording it clear that you've selected the query. When you're selecting any part of SQL, only selected part goes to the server irrespective if it is commented outside the selection.
Not an issue.

**Comment by adityatoshniwal** [comment]
Like I said, it doesn't matter if there is a comment before the line if you've selected only part of the query. Only selected part is considered.

**Comment by adityatoshniwal** [comment]
You can comment a line without selection as well.
