### ISSUE TITLE
pgAgent installation:  Wrong/Misleading error message/failed installation  when the default postgres db user's password doesn't meet window security policy.

### ISSUE THREAD

**Issue by rdczhzq** [pgadmin-org/pgadmin4#7490]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

During pgAgent installation, when the GUI prompts for a default user: postgres to be created , if the user's windows password is not fulfilling windows security policy, the GUI prompts an error message, saying something like  " The password length  doesn't meet the requirement".(e.g. if the postgres db user's password is set to 123456).

**To Reproduce**

1. DB user postgres, password: 123456
2. Install the pgagent under adminstrator rights.
3. When the GUI prompts enter password for the default user: postgres, input:123456, you will never pass with an error message saying something "The posssword length doesn't meet  the reqirement".

4. Then you create another windows user with password fulfilling windows securty policy and during pgagent installation, use admin as the user and also the windows approved password, installation succeeded without any problem.

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by dpage** [comment]
The pgAdmin team doesn't maintain any packages for pgAgent. Please report this issue to whoever you obtained your package from. Thanks.

**Comment by rdczhzq** [comment]
OK. report on edb project istead.



***@***.***
 
From: Dave Page
Date: 2024-05-21 23:54
To: pgadmin-org/pgadmin4
CC: Joe; Author
Subject: Re: [pgadmin-org/pgadmin4] pgAgent installation: Wrong/Misleading error message/failed installation when the default postgres db user's password doesn't meet window security policy. (Issue #7490)
The pgAdmin team doesn't maintain any packages for pgAgent. Please report this issue to whoever you obtained your package from. Thanks.
