### ISSUE TITLE
On refreshing schema diff tool opened in new tab gives error 'Transaction not found' error

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#7499]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

On refreshing schema diff tool opened in new tab gives error 'Transaction not found' error

**To Reproduce**

1. Open schema diff tool in new tab.
2. Refresh the tab.
3. Try to compare 2 databases now.
4. Error will be shown

**Expected behavior**

Error should not be shown.

**Comment by RohitBhati8269** [comment]
Issue fixed and Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-08-12/).

Env:-
OS - macOS arm
Mode - Server
