### ISSUE TITLE
Update notistack library to version 3.x

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#7501]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by pravesh-sharma** [comment]
Please include testing #6571 alongside this issue.

**Comment by RohitBhati8269** [comment]
Completed and verified on MacOs with [snapshot](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-07-10/)
