### ISSUE TITLE
Query Tool Screenshot Displays Incorrect Function Key

### ISSUE THREAD

**Issue by anthonydb** [pgadmin-org/pgadmin4#7507]
**Describe the bug**

In the following file:
https://github.com/pgadmin-org/pgadmin4/blob/master/docs/en_US/query_tool.rst

The screenshot that shows the Execute Script menu icon and its hover properties shows the associated function key as being F6:
https://github.com/pgadmin-org/pgadmin4/blob/master/docs/en_US/images/query_execute_script.png

The key should be F5, as in the app.

**Comment by pravesh-sharma** [comment]
Issue fixed, verified on candidate [build](https://developer.pgadmin.org/builds/2024-05-28-1/).

Env:
OS - macOS Sonoma 14.4.1
Mode - Desktop
