### ISSUE TITLE
pgAdmin is not installed on Ubuntu Desktop 24.04 LTS

### ISSUE THREAD

**Issue by SalavatH** [pgadmin-org/pgadmin4#7509]
/**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
When installed using the algorithm from https://www.pgadmin.org/download/pgadmin-4-apt/ - it is not installed!

(I use the Russian interface.
It worked on Ubuntu 22.04!)

Ubuntu Desktop 24.04 LTS - downloaded from https://ubuntu.com/download/desktop/thank-you?version=24.04&architecture=amd64&lts=true

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**
[url=https://postimages.org/][img]https://i.postimg.cc/HLPKrJdw/2024-05-29-09-45-55.png[/img][/url]

https://radikal.cloud/i/XjUV1

**Desktop (please complete the following information):**
- **Название ОС:**                                Ubuntu 24.04 LTS
- **Сборка ОС:**                                   (null)
- **Тип ОС:**                                         64-бит
- **Версия GNOME:**                           46
- **Оконный интерфейс:**                  Wayland
- **Версия ядра:**                                Linux 6.8.0-31-generic

**Additional context**

**Comment by SalavatH** [comment]
I couldn’t post a screenshot of the error in the original post, so I’ve included it here.
![Снимок экрана от 2024-05-29 09-45-55](https://github.com/pgadmin-org/pgadmin4/assets/171186739/64c1b1f8-3fe1-40b4-88cf-f1aa4a18466a)

**Comment by pravesh-sharma** [comment]
Duplicates #7437.

pgAdmin 4 will be supported on Ubuntu 24.04 from version 8.7 onwards which is due to release today.

**Comment by SalavatH** [comment]
> Duplicates #7437.
> 
> pgAdmin 4 will be supported on Ubuntu 24.04 from version 8.7 onwards which is due to release today.

Thank you.
I hope and look forward to it - very much!!
Tell me right away how to find out exactly when the update will happen so that I can try again.
Which version will be downloaded from the site and/or can I choose a downloadable version?

**Comment by pravesh-sharma** [comment]
Hi @SalavatH,

You can visit the news section at https://www.pgadmin.org/ for release-related information and https://www.pgadmin.org/download/ for download-related information.

**Comment by SalavatH** [comment]
> You can visit the news section at https://www.pgadmin.org/ for release-related information

Thank you very much!!
Now it is established, yes.
