### ISSUE TITLE
Query Editor Code Underlining

### ISSUE THREAD

**Issue by Arnd-B** [pgadmin-org/pgadmin4#7510]
Hello,

as much as I like PGADMIN and your efforts on enhancing it please provide an option where to turn off the new "active line" underlining. I find it very disturbing as the line reduces the readability and distracts from focusing on the content as it pulls the focus of the eye and it wants a semicolon to end.

Regards

Arnd

**Comment by adityatoshniwal** [comment]
Its there. Please check the preferences -> query tool -> options.

**Comment by Arnd-B** [comment]
Top and thanks! Got it. I was looking into preferences -> query tool but not at options.

**Comment by dangelsaurus** [comment]
Did I miss this in the release notes?

**Comment by Arnd-B** [comment]
I do not know as I did not read them. I was checking the sections „Editior Display“ and everything in this area I did not look into „Options“. Now I know and I will search more thorough next time.
