### ISSUE TITLE
Cannot insert a character where I want to. PgAdmin is adding it to the end of the line for some reason

### ISSUE THREAD

**Issue by rbrooklyn** [pgadmin-org/pgadmin4#7511]
**Describe the bug**

I cannot insert a "(" character where I want to in the query I'm trying to write.

**To Reproduce**

1. Consider this query:
![image](https://github.com/pgadmin-org/pgadmin4/assets/11929484/207336b7-2386-4779-bccd-f1d03e7d81cb)
3. Move cursor to the end of line 4. Press "Home" key on keyboard so the cursor is at the beginnig of the first SUM, type in a "("
4. "(" character is inserted at the end of the line, not where the cursor is:
![image](https://github.com/pgadmin-org/pgadmin4/assets/11929484/2e7579a4-9c19-4fa4-b1af-ddfd57097c5e)

**Expected behavior**

"(" character is inserted where the cursor is. Because that's what I typed and that's where the cursor is. Adding a second ")" might be okay based on what the user is doing, but overriding what they have typed in this manner is not acceptable.

Using cut and paste, I was able to get the code I actually wanted. It was not possible to actually modify the text on screen to be what I actually wanted by using the keyboard:
![image](https://github.com/pgadmin-org/pgadmin4/assets/11929484/758fd638-7268-405a-98a7-1b5178a2ee44)
Obviously that query is incomplete as it stands, but I wanted a "(" character at a specific place, and I was unable to place it there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.7
 - Mode: Desktop
 - Package type: MSI installer

**Comment by rbrooklyn** [comment]
It seems that it's not just the "(" character which is broken. Putting anything there seems to show this behaviour:
![image](https://github.com/pgadmin-org/pgadmin4/assets/11929484/3998b8ca-e0c7-40ce-8de8-e4ffaf4b382c)

**Comment by FJo69** [comment]
For me it looks like it has to do with the new keyboard- shortcut features. In my pgsql code editor I faced heavy problems putting in a simple 'O' character (trying to write 'OVER()' ... ). When typing 'over()' I had no problem, when typing 'OVER()' after the 'O' key the cursor placed to end_of_line. But it was depending on some chars which were already written in sta same line before the 'O', it was mysterious. Ti fix it I modified the keyboard shortcuts (which normally are completely untouched in my systems) and got rid of this 'O' - cursor bug. But now I faced a new bug when typing 's' within the same editor ('s' called up an unwanted dialog).

(...)
I turn back to Pgadmin4 8.6 and hope it gets better.

**Comment by adityatoshniwal** [comment]
As a workaround, please disable `Underline query at cursor?` from Preferences -> Query Tool -> Options.

**Comment by FJo69** [comment]
> As a workaround, please disable `Underline query at cursor?` from Preferences -> Query Tool -> Options.

Thanks for your fast feedback.

It helped for the 'O' issue, but maybe as a result of previous trying to inactivate keyboard shortcuts, I now faced a new problem: 
(using Windows Server2019, and still after doing a complete system restart).
Within the SQL editor, now each single 'd' keystroke was showing up the "do you really want to delete this object" - editor. Things are gonna getting worse.

I now set Preferences -> Query Tool -> Options | Underline query at cursor? = no (as you told me)
and additionally, I choose Preferences -> Browser -> keyboard shortcuts | ... activate for all items all 3 buttons [SHIFT]+[CTRL]+ALT]

I don't want to use them, I just want to get rid of unwanted effects, and I don't expect to accidentally press all 3 buttons together.

Now it seems to work and I can go on in typing my code like I was used to.

**Comment by adityatoshniwal** [comment]
> > As a workaround, please disable `Underline query at cursor?` from Preferences -> Query Tool -> Options.
> 
> Thanks for your fast feedback.
> 
> It helped for the 'O' issue, but maybe as a result of previous trying to inactivate keyboard shortcuts, I now faced a new problem: (using Windows Server2019, and still after doing a complete system restart). Within the SQL editor, now each single 'd' keystroke was showing up the "do you really want to delete this object" - editor. Things are gonna getting worse.
> 
> I now set Preferences -> Query Tool -> Options | Underline query at cursor? = no (as you told me) and additionally, I choose Preferences -> Browser -> keyboard shortcuts | ... activate for all items all 3 buttons [SHIFT]+[CTRL]+ALT]
> 
> I don't want to use them, I just want to get rid of unwanted effects, and I don't expect to accidentally press all 3 buttons together.
> 
> Now it seems to work and I can go on in typing my code like I was used to.

How are you using pgAdmin desktop or server? If server, try restarting the server once. The shortcuts have changed, we remove use of browser accesskey.

**Comment by kewang** [comment]
I have the same issue, very annoyed

**Comment by FJo69** [comment]
...
> 
> How are you using pgAdmin desktop or server? If server, try restarting the server once. The shortcuts have changed, we remove use of browser accesskey.

I don't really know 'how I use it, desktop or server', as for me this architecture- mix always was a little bit confusing. So I never took attention to this detail. What I am running when using pgAdmin4 on "Windows Server 2019", is a desktop .exe file; maybe this helps.

But what I already did, before reporting further details: I restarted the whole environment (database, and workplace windows engine). Because I definitely need to avoid jeopardizing my second working environment (which is UBUNTU MATE 22.04), I can't actually try this out there, sorry.

**Comment by FJo69** [comment]
> I have the same issue, very annoyed

for me it really worked to set:

_Preferences -> Browser -> keyboard shortcuts | ... activate for all items all 3 buttons [SHIFT]+[CTRL]+ALT]_

It's not nice but it's better then having a sick editor

**Comment by celm1990** [comment]
I have the same issue
Ubuntu 22.04
pg_admin 8.7

I update to latest 8.8 and now working fine

**Comment by masb3** [comment]
Same here with pgAdmin 8.7 on MacOS 14.5. 
Works with workaround https://github.com/pgadmin-org/pgadmin4/issues/7511#issuecomment-2146793258

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-07-02/
Package: arm64
Environment: macOs Ventura 13.5.1

**Comment by sgehrlein** [comment]
this effect seems to apear when there is a TAB before the code and the underlining is active.
-> if you put then any character after the TAB, starting the code text, the cursor jumps at the end of the line puting the new characters there.
cut and paste lets you input the new text where you want.
Also when you delete the TAB, input the new text at the beginning of the line and then put a TAB in front again.

But all that is a miserable side effect after the last update.
Hope this is fixed with the next update?
For me at least it helped disabling the underline text...

**Comment by adityatoshniwal** [comment]
@sgehrlein  disabling the underline was a workaround. Complete fix will be available in next release.
