### ISSUE TITLE
Open and run a query (file) from a terminal command?

### ISSUE THREAD

**Issue by birgersp** [pgadmin-org/pgadmin4#7514]
**Describe the solution you'd like**

I would like to trigger a query execution in pgAdmin, without having to navigate the UI of pgAdmin.

Ideally, I could do this if there was a CLI command like this:

```
/usr/pgadmin4/bin/pgadmin4 --exec-query-file ~/query.sql db/user@pgserver.com
```

This would:

* Open a new window of pgAdmin, **unless one is already open**
* Load the query in a query tool tab, unless a tab with the file loaded already exists
  * if a tab with the file loaded already exists, reload the file (if the file changed)
* execute the query (same as hitting f5)

**Describe alternatives you've considered**

Executing the query with `psql`, but then I don't get the results in a nice format like with pgadmin

**Comment by yogeshmahajan-1903** [comment]
pgAdmin4 is NOT intended to use in this way. Query Tool depends on existing connections and other parameters which makes difficult to achieve.Hence this closing the issue.
