### ISSUE TITLE
docker / podman container image outside of docker hub

### ISSUE THREAD

**Issue by vbelogrudov** [pgadmin-org/pgadmin4#7518]
Hello,

is it possible to put built container images also outside docker.io?  The latter became quite restrictive and unfriendly to many developers round the world (api restrictions, rate limiters, total ban in some geographic locations, ...).

**Comment by yogeshmahajan-1903** [comment]
@dpage 
Can you please share your inputs on this?

**Comment by akshay-joshi** [comment]
We are not supporting it and don't have a plan to do so shortly.
