### ISSUE TITLE
Tools -> Shema Diff not working correctly

### ISSUE THREAD

**Issue by ddjuric1** [pgadmin-org/pgadmin4#7523]
![0](https://github.com/pgadmin-org/pgadmin4/assets/87120049/b03d454a-1f33-4e23-b991-1a8e90b07cf0)

1. States differences in comments of the same tables when there is no differences
   This is from earlier versions.
![1](https://github.com/pgadmin-org/pgadmin4/assets/87120049/19e2070a-7a81-4a50-b69c-23c4989e712a)

2. States differences of the same tables when there is no any text in Difference screen.
   This is also from earlier versions.
![2](https://github.com/pgadmin-org/pgadmin4/assets/87120049/51ee8ae9-e43a-4aae-a4d7-3e035f7bfd61)

3. States differences of the same tables on triggers.
   It should recognize that the called trigger function is from the same shame as the calling trigger is
   and not treat it as difference.
![3](https://github.com/pgadmin-org/pgadmin4/assets/87120049/e35adeee-2d75-44ff-8293-5131ccd02e7e)

**Comment by akshay-joshi** [comment]
@ddjuric1 

Are you comparing two databases or 2 schemas?

**Comment by ddjuric1** [comment]
Hi 

 

I'm comparing two schemas on two different databases and different machines, but of the same DB version and parameters.

 

Regards

**Comment by pravesh-sharma** [comment]
Issue resolved, tested on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-24/).
