### ISSUE TITLE
Running materialized view blocks UI components while materialize view refresh is occurring

### ISSUE THREAD

**Issue by dangelsaurus** [pgadmin-org/pgadmin4#7525]
If you have a materialized view refreshing, initiated by right click **Refresh View -> With Data**, and then try **Scripts -> CREATE Script** on ANY materialized view, you will get a blank query window opened. 

If you run a **refresh materialized view ....** sql directly from the query window, this does not occur and you get the expected outcome. 

Bonus Bug: You also cannot view Help->About info when a materialized view refresh is occurring, seems as if something is blocking the UI
![image](https://github.com/pgadmin-org/pgadmin4/assets/12521900/a2be79d0-fa4b-4a8f-899c-b8147a098c92)

This is on 8.7 Desktop.
Windows 11 23H2 - 64GB 13900K

**Comment by adityatoshniwal** [comment]
Hi @dangelsaurus,
We're not able to reproduce this. pgAdmin forks a separate process to refresh the mview, so it should not hang the main process.
Can you share screen recording and logs please?

**Comment by dangelsaurus** [comment]
I went from 8.6 to 8.8, and currently am not having the issue. (not saying that it was "fixed" in 8.8, just that for whatever reason it is not occurring today.) If it comes back up I'll re-open.
