### ISSUE TITLE
pg_dump: error: invalid compression specification: this build does not support compression with gzip

### ISSUE THREAD

**Issue by dangelsaurus** [pgadmin-org/pgadmin4#7526]
v8.7 Desktop - Windows 11

pg_dump with compression

C:\Users\<user>\AppData\Local\Programs\pgAdmin 4\runtime\pg_dump.exe --file "E:\\cc_backup_temp\\test3" --host "<host>" --port "5432" --username "<username>" --no-password --format=d --compress "9" --verbose "postgres"

**pg_dump: error: invalid compression specification: this build does not support compression with gzip**

rolled back to v8.6 and works fine.

**Comment by akshay-joshi** [comment]
@dangelsaurus 

We are investigating the issue. The problem might be related to changes in the zlib library in this version of pgAdmin 4.
