### ISSUE TITLE
Backslash breaks syntax highlighting in version 8.7

### ISSUE THREAD

**Issue by rgelsi** [pgadmin-org/pgadmin4#7528]
A backslash escapes the single quotation mark and breaks the syntax highlighting.

![image](https://github.com/pgadmin-org/pgadmin4/assets/16667311/57357667-0aa4-4b4c-8f77-0bdd11c861fe)

PgAdmin should recognize the single backslash and not escape the single quotation mark.
It worked as expected in PgAdmin 8.6:
![image](https://github.com/pgadmin-org/pgadmin4/assets/16667311/ccdae971-08be-4f8a-b18e-38e89f9472fe)

**Desktop:**
 - OS: Windows 10
 - Version: 8.7
 - Mode: Desktop

**Comment by anilsahoo20** [comment]
Related to #7485.

**Comment by anilsahoo20** [comment]
Issue fixed and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-18/
Environment: 
OS: OSX ventura 13.5.1
Package: arm64
