### ISSUE TITLE
Smart Select option in pgAdmin 4

### ISSUE THREAD

**Issue by SheikhAziz** [pgadmin-org/pgadmin4#7530]
Smart Select option which was introduced in pgAdmin 4 v8.4 was removed in next released pgAdmin v8.5, I was thinking that it will be back in next release but it doesn't. I don't know why that useful feature is removed from the next release of pgAdmin.
Smart select feature which is provided in most of query editor like visual studio code etc. It is like when you select a text, it will highlights all the matches. For example in pgAdmin 4 v8.4 when you select a text, it highlights all matches in the whole text in green.
Just because of this feature I'm still using v8.4. I installed latest version but downgrade it because of this feature.
I'm sharing screenshots of query example from pgAdmin 4 v8.4.

![highlight](https://github.com/pgadmin-org/pgadmin4/assets/99309995/625fd67c-9df6-4b2a-be13-65b07d7d3b1e)

Is it possible to get back this feature again in future release ?

**Comment by anilsahoo20** [comment]
Note: We could add preference based Smart select.

**Comment by SheikhAziz** [comment]
I think this feature is only in pgAdmin 8.4 and its removed from future release versions, because I never seen this functionality in older version and newer version except v8.4.
Reverted to v8.4 but there are some bugs in v8.4 (like :- find and replace is not working etc.)
Expecting this feature in future release.

Thank you. :)

**Comment by anilsahoo20** [comment]
Feature implemented and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-07-19/
Environment: OSX ventura 13.5.1
Pacakge: arm64

**Comment by SheikhAziz** [comment]
Thank you very much. 🥇
