### ISSUE TITLE
Search Objects dialog focus

### ISSUE THREAD

**Issue by avispt** [pgadmin-org/pgadmin4#7536]
Version: 8.7
Source: brew
Application mode: Desktop
OS: macOS Sonoma 14.5

Please set focus to search box on "Search Objects" dialog when it opened.
Steps to reproduce :
Open Search Objects dialog from the menu bar or the toolbar.
On opening, you will need to set focus manually to start writing your search.

**Comment by anilsahoo20** [comment]
Issue fixed and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-18/
Environment:
OS: macOs Ventura 13.5.1
Package: arm64

**Comment by avispt** [comment]
Thank you for your work
