### ISSUE TITLE
Add support for PostgreSQL v17

### ISSUE THREAD

**Issue by IgorLytkin** [pgadmin-org/pgadmin4#7537]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
Databases - Properties on PostgreSQL 17 Beta 1 not work

**To Reproduce**

1. Go to 'Server with PostgreSQL 17beta1 - Databases '
2. Click on 'Properties' tab
3. See the error windows "Failed to retrieve data from the server" + "Request failed with status code 500" message.

**Expected behavior**
See all databases properties.

**Error message**
Request failed with status code 500

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 22.04.4 LTS
 - Mode: Server
 - Browser (if running in server mode): Yandex
 - Package type: Container

![2024-06-05_10-12-51](https://github.com/pgadmin-org/pgadmin4/assets/78451595/f39ae3f3-f549-4e53-b3b0-ab0f3685cf39)

**Comment by IgorLytkin** [comment]
[_postgresql-pgadmin-1_logs.txt](https://github.com/user-attachments/files/15572673/_postgresql-pgadmin-1_logs.txt)
pgAdmin Container Log.

**Comment by adityatoshniwal** [comment]
I am changing the label as pgAdmin is not tested on PG17 yet. We'll work on adding support.

**Comment by fly74** [comment]
Another issue is to open database properties with pgadmin 8.8 (Windows) on postgresql17b1:

![Screenshot 2024-06-15 081333](https://github.com/pgadmin-org/pgadmin4/assets/38754941/f435bc99-3c7b-4d87-80c8-d52087437212)

**Comment by yogeshmahajan-1903** [comment]
This is working fine.

**Comment by fly74** [comment]
Is there an action build to make a test?

**Comment by yogeshmahajan-1903** [comment]
> Is there an action build to make a test?

@fly74 You can download daily snapshot build from [here](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/).

**Comment by IgorLytkin** [comment]
No image in docker hub yet?

**Comment by fly74** [comment]
> Another issue is to open database properties with pgadmin 8.8 (Windows) on postgresql17b1:
> 
> ![Screenshot 2024-06-15 081333](https://private-user-images.githubusercontent.com/38754941/339960656-f435bc99-3c7b-4d87-80c8-d52087437212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTcwMDUsIm5iZiI6MTcyMDE1NjcwNSwicGF0aCI6Ii8zODc1NDk0MS8zMzk5NjA2NTYtZjQzNWJjOTktM2M3Yi00ZDg3LTgwYzgtZDUyMDg3NDM3MjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA1MTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNzA1ZTBmMTcyOWJkODhkODgwMDlkODQ5Y2FmYzk3OWZiZWEwYWYzYzdlM2UwZmM4ZTY5YjVjYWY3NjliNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dTQdVrGmGiwaSxWvxr7nt757fJf9bESL3IoI771HXZQ)

Great. work now with the daily snapshot 2024-7-5 and ""PostgreSQL 17beta2 on x86_64-pc-linux-gnu, compiled by gcc (SUSE Linux) 7.5.0, 64-bit""

**Comment by yogeshmahajan-1903** [comment]
> No image in docker hub yet?

You can use snapshot image which is updated daily basis.
```
docker pull dpage/pgadmin4:snapshot
```

**Comment by IgorLytkin** [comment]
Yes. It works on my VPS. Thank you.

**Comment by casparsch** [comment]
@yogeshmahajan-1903 
Just a question/remark, related to this issue: _Should the section ["Supported Database Servers"](https://www.pgadmin.org/docs/pgadmin4/development/release_notes_8_10.html#supported-database-servers) in the releasenotes contain "17" as well?_
So instead of:
```
12, 13, 14, 15, and 16
```
it should probably be:
```
12, 13, 14, 15, 16 and 17
```
