### ISSUE TITLE
Windows 11 issue: Server heartbeat logging error after deleting server

### ISSUE THREAD

**Issue by usmanmuzaffar15** [pgadmin-org/pgadmin4#7540]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
Encountered error 'Server heartbeat logging error : Request failed with status code 404' while deleting a server from tree control

Pre req:
     Postgresql 16 is added to the server group.
1. Go to 'tree control and delete existing server'.
2. Wait for almost 20 seconds, an error message from the right bottom corner appears saying:
**'Server heartbeat logging error : Request failed with status code 404'**
I have tried followings also:
1) Delete the server after disconnecting it from context menu ---> I tried it couple of times and did not encounter the error.
2) Delete the server without disconnecting it from context menu --->  It raised the above mentioned error. I tried three to four times and every time it was encountered.

I tried with both with pgadmin 8.7 and 8.8

**Expected behavior**
No error message should be raised if a server is deleted from the server group from tree area

**Error message**
**'Server heartbeat logging error : Request failed with status code 404'**

**Screenshots**
<img width="960" alt="heartbeat" src="https://github.com/pgadmin-org/pgadmin4/assets/149988380/895903d6-77b6-427e-930b-29a40ef30b4b">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version: [e.g. 11 Home 22H2]
 - Mode: [e.g Desktop ]
 - Browser (Nill]
 - Package type: [e.g. windows installer.]

**Additional context**

**Comment by akshay-joshi** [comment]
Tested on candidate build by Yogesh

**Comment by automationSele** [comment]
The issue is fixed. Verified on latest build(8.11) from live. 
Thanks
