### ISSUE TITLE
Statistics sorting by size does not work as expected on pgAdmin 8.8

### ISSUE THREAD

**Issue by robe2** [pgadmin-org/pgadmin4#7542]
**Describe the bug**
When you click on any statistics tab,  whether at server or tables level, and you click sort by size, the sorting does not go from highest to lowest or lowest to highest.

**To Reproduce**

1. Go to a Databases node on a server
2. Click the statistics tab
3. Click the Size header

**Expected behavior**

There should be some sort of meaningful sort going on.
In this case the gisdb (at very least) seems out of place.  I have other servers where the sorting issue is more obvious.

**Screenshots**

From Databases Node
![image](https://github.com/pgadmin-org/pgadmin4/assets/4734450/aaf69fbc-f7ca-4e81-9b66-e559f8e72aec)

Here is another example navigating to a Schema -> Tables

![image](https://github.com/pgadmin-org/pgadmin4/assets/4734450/a0493caa-ec74-4487-8592-ce9d1f25d59c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 8.8 (I just upgraded, it came out yesterday)
 - Mode: Desktop
 - Package type: Installer

**Comment by pravesh-sharma** [comment]
Issue fixed. Tested on snapshot build.

Env:
OS - macOS Sonma 14.5
Mode - Desktop
