### ISSUE TITLE
Sorting Database Activity by any column and then expanding activity shows activity at wrong position

### ISSUE THREAD

**Issue by 1Map** [pgadmin-org/pgadmin4#7554]
**Describe the bug**

Sorting Database Activity by any column and then expanding activity shows activity at wrong position

Example:

**1) Click on State column to sort**
<img width="398" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/1152458/d3ae674a-116e-464f-b9c4-61e0de941c6e">

**2) Expand Any activity**
<img width="242" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/1152458/a6d44312-3357-45ed-9652-b038e2e3846b">

**3) Scroll down to find blank space at the bottom and detail about activity not shown at correct position**
<img width="1117" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/1152458/024792be-f5a2-4b55-9eaa-5bcd0f7253e2">

**Comment by RohitBhati8269** [comment]
Issue resolved, tested on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-07-02/).
