### ISSUE TITLE
pgAdmin 4 v8.8 shortcuts issues

### ISSUE THREAD

**Issue by brian-ceccarelli** [pgadmin-org/pgadmin4#7555]
You just released this version.   
In the Query Tool, none of the "Find" Crtl-F functions work.   A pop-up never appears.
I reverted to v8.7.   8.7 works.

**Comment by robe2** [comment]
Same issue for me, we had this issue too I think maybe in 8.4 or so maybe something got reverted.

**Comment by adityatoshniwal** [comment]
@brian-ceccarelli I'm not able to reproduce. Can you check the shortcut here?
<img width="490" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/4a9ea6bd-ac92-4d66-be58-2c1f3ce7d92d">

**Comment by udit47** [comment]
Same happening with me for Win 11. Shortcut for find shows "Ctrl + F" for Find only but it opens the "Quick Search" pop-up which searches in PgAdmin functions.
Reverted to 8.6

**Comment by brian-ceccarelli** [comment]
The Unindent selection works.
The Indent selection works.

Ctrl-F does not.   Menu->Find does not work.
Go to Line/Columns does not work.

------------------
So, the upper three items in the drop-down menu do NOT work.
The middle items work.
The bottom item,  Format SQL, works.
--------------------
I get the same behavior on Windows 10 and Windows 11.

**Comment by HelloD939** [comment]
The Ctrl+F shortcut no longer works.
Menu -> Search no longer works.
Please fix this quickly, it's unworkable

**Comment by ajsmith-savills** [comment]
Also finding this issue on a windows deployment, both find and replace not working either using shortcuts or menus. Please fix ASAP

**Comment by akshay-joshi** [comment]
All,
We are currently working on this issue, and the fix will be available in the next release scheduled for June 25th

**Comment by pravesh-sharma** [comment]
Issue fixed. Tested on candidate [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-21/).

Env:
OS - Windows 11
Mode - Desktop
