### ISSUE TITLE
Dialog screens persistent size

### ISSUE THREAD

**Issue by Poolgray** [pgadmin-org/pgadmin4#7558]
I have some triggers with codes that make some lines a little long and every time I open the dialog to edit the trigger code I change the size of the dialog, dragging its edges with the mouse, to have a better view of the trigger code.

I would like to ask if it is possible to implement a solution so that the size of the dialog is kept the way it was when it was closed or some configuration to standardize the default size of pgAdmin dialogs.

Thank you very much in advance.

**Comment by adityatoshniwal** [comment]
Duplicates #3241
