### ISSUE TITLE
After selecting and deleting text in the editor pgAdmin gets stuck in a type of insert mode

### ISSUE THREAD

**Issue by Carl-Llewellyn** [pgadmin-org/pgadmin4#7572]
**Describe the bug**

Quite regularly after either selecting text in the SQL editor and deleting it, the editor switches to a sort of insert mode which I cannot escape from in any predictable way (pressing insert does nothing). Also I cannot move the typing cursor with the arrows, where it just bounces back to the same line.

The only way I can get out is either closing the text editor, or spamming buttons until it may or may not go back into normal type mode.

This used to only seem to happen after editing the generated queries after pressing "View/Edit Data", now it seems to happen in any SQL I'm editing.

**To Reproduce**

Select text, delete it. Seems like it could be more common after a select all (ctrl + A) or after editing the generated queries after pressing "View/Edit Data".

**Expected behavior**

Not to enter insert mode without pressing insert.

**Desktop (please complete the following information):**
 - OS: Ubuntu  22.04
 - Mode: Running on a laptop that is connected to a remote PSQL server.
 - NOT in browser. Using desktop application 8.9.
 - Package type: apt.

**Comment by adityatoshniwal** [comment]
Duplicates #7351
