### ISSUE TITLE
SSH Tunnel password

### ISSUE THREAD

**Issue by mikulicf** [pgadmin-org/pgadmin4#7585]
After initiating a new connection which uses SSH Tunneling it always asks for the identity file password even if the identity file password is blank, unable to save the password as blank or anything else.

![image](https://github.com/pgadmin-org/pgadmin4/assets/72322905/74c7b069-0153-4ff1-8a6b-e454547acded)

**Comment by pravesh-sharma** [comment]
Duplicates #6996
