### ISSUE TITLE
View Dependancies right click

### ISSUE THREAD

**Issue by RTSMikeM** [pgadmin-org/pgadmin4#7587]
To be able to right click on a table and "View Dependencies".
This would bring up a dialog showing all other database objects (functions, stored procs etc) that use the table.

This feature is very well supported in SQL Server Management Studio.

When maintaining a PG database with many objects, this feature is sorely lacking.

**Comment by khushboovashi** [comment]
You can achieve this by selecting any object from the browser tree and selecting the Dependencies and Dependents tabs.

**Comment by RTSMikeM** [comment]
I have no such tab visible.  A right click would be better IMHO.

**Comment by khushboovashi** [comment]
See the screenshot. 

<img width="1297" alt="Screenshot 2024-06-19 at 10 12 20 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/14345545/873716d5-f6c1-4d45-9e3f-0a57b308d64a">


If you have closed any panel, you can reopen as shown in the screenshot.

<img width="1428" alt="Screenshot 2024-06-19 at 10 13 47 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/14345545/1d530b83-fb52-4c60-bb7b-5bcf17accdb6">
