### ISSUE TITLE
Filter shortcut is not working in 8.8 version

### ISSUE THREAD

**Issue by rishikautkar** [pgadmin-org/pgadmin4#7589]
while i had check the shortcuts CTRL + F is not working to fing anyword in query tool box.
![pgadmin](https://github.com/pgadmin-org/pgadmin4/assets/48465681/337af320-db5d-4fbd-a548-cc92ee5f3fda)

**Comment by adityatoshniwal** [comment]
Duplicates [#7555](https://github.com/pgadmin-org/pgadmin4/issues/7555)

**Comment by rishikautkar** [comment]
sorry what duplicates?

**Comment by pravesh-sharma** [comment]
Hi @rishikautkar,

Duplicates mean this issue has been already raised and the team is working on it.
