### ISSUE TITLE
Autocomplete not working after update connection.

### ISSUE THREAD

**Issue by anilsahoo20** [pgadmin-org/pgadmin4#7593]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When we update the connection from one database to other database, the autocomplete is not working.

**To Reproduce**

1. Open query tool
2. Type something, autocomplete will work
3. Now update the connection
4. try typing something
5. autocomplete not working

**Expected behavior**

It should work.

**Error message**

```
data: null
errormsg: "Transaction ID not found in the session."
info: "DATAGRID_TRANSACTION_REQUIRED"
result: null
success: 0
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX Ventura
 - Version: 8.8
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by pravesh-sharma** [comment]
Found below issue:

If autocomplete is off and ctrl+space is used to trigger autocomplete it can not be done after updating the connection.
If autocomplete is enabled in that case everything works fine.

**Comment by adityatoshniwal** [comment]
Hi @pravesh-sharma,
I checked again and API is being called with correct txn id, which was fixed.

**Comment by pravesh-sharma** [comment]
> Hi @pravesh-sharma, I checked again and API is being called with correct txn id, which was fixed.

Okay. What I mentioned seems to be another issue will create a separate one for it.

**Comment by pravesh-sharma** [comment]
Issue fixed. Tested on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-06-20/).

Env:
OS - macOS Sonoma 14.5
Mode - Desktop
