### ISSUE TITLE
Add shortcut for closing PgAdmin tab

### ISSUE THREAD

**Issue by AlessandroMartinelli** [pgadmin-org/pgadmin4#7594]
**Describe the solution you'd like**
It would be nice to have the possibility to close a tab of PgAdmin by means of clicking the mouse wheel and/or the keyboard shortcut Ctrl + W, as it is standard for browsers. As of now you need to either 
- place the mouse cursor on the X of each tab and then click or
- place the mouse cursor on a given tab, press the mouse right button, then click close
so currently, if you have several tabs open, it takes some time to close all of them, while it would require almost no time if the above suggestion was to be implemented

**Additional context**
The features I've described are common on all major browsers, so users are accustomed to them.

**Comment by marekchovanec** [comment]
Another similar issues: 

https://github.com/pgadmin-org/pgadmin4/issues/6572
https://github.com/pgadmin-org/pgadmin4/issues/6814

**Comment by adityatoshniwal** [comment]
Duplicates #6572. We will prioritise #6572
