### ISSUE TITLE
Option to save SSH key passphrase is greyed out

### ISSUE THREAD

**Issue by ahmgithubahm** [pgadmin-org/pgadmin4#7602]
**Describe the bug**

I am unable to save the SSH key passphrase for a server's SSH tunnel config.

**To Reproduce**

1. Create a new server connection, adding SSH tunnel config.
2. The radio button to 'Save password?' (SSH key passphrase) is greyed out.
3. Save the server anyway.
4. Open the server, receive prompt to enter 'SSH Tunnel password for the identity file' (SSH key passphrase), but tick box to 'Save Password' is greyed out.

**Expected behavior**

I expect to be able to save the SSH key passphrase, as I used to.

**Error message**

None, just the options are greyed out.

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/701588/5f2bc24f-324d-4de6-ada6-afb809097b3e)

![image](https://github.com/pgadmin-org/pgadmin4/assets/701588/8eee431f-90e5-42fb-9dfb-ea2a8fd78d29)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: pgAdmin 4 8.8
 - Mode: Desktop
 - Browser (if running in server mode): n/a
 - Package type: Windows installer

**Additional context**

n/a

**Comment by pravesh-sharma** [comment]
Hi @ahmgithubahm,

You need to set `ALLOW_SAVE_TUNNEL_PASSWORD = True` on your `config_local.py` file. You can get information about config files from [here](https://www.pgadmin.org/docs/pgadmin4/8.8/config_py.html).
