### ISSUE TITLE
ERD Tool - Can't move tables

### ISSUE THREAD

**Issue by dmondra2** [pgadmin-org/pgadmin4#7604]
I drag a couple of tables (individually) into the ERD Tool, it doesn't place/drop them where I release the mouse hold, it just stacks them atop of each other, and then doesn't let me move them.

Version
8.2
Application Mode
Desktop
Current User
pgadmin4@pgadmin.org
NW.js Version
0.77.0
Browser
Chromium 114.0.5735.91
Operating System
Windows-10-10.0.19045-SP0

**Comment by adityatoshniwal** [comment]
I cannot reproduce this. It works fine. Can you try once with latest version?

**Comment by dmondra2** [comment]
This was the latest version. I downloaded and it installed clean yesterday
to be sure.

**Comment by akshay-joshi** [comment]
Hi @dmondra2 

Can you please share the screen recording and logs (pgAdmin4 > Runtime > View Logs menu)?

**Comment by dmondra2** [comment]
Hmmm....

Looks like a restart is all that's needed? I powered on my computer this morning and now it's no longer doing it...

I could try to reproduce this, the steps I took yesterday were: uninstalled pgadmin, installed latest version of pgadmin from the website, started exploring a remote pg database that I had just stood up for a client, was attempting to create an ERD to share with him and I had the problems mentioned.

I'm not sure it's worth going through all the effort to reproduce, I think it's common that sometimes after installing something you may need to restart your computer.

If you want me to go through the full gambit though I can, just not today because I'm just absolutely slammed.

Thanks!

**Comment by adityatoshniwal** [comment]
@dmondra2 Sure you can reply back to us with some reproducible steps that will help us to fix. Also share a screen recording. On mac sometimes it gets stuck because of a Mac shortcut, possible in your case as well.

**Comment by adityatoshniwal** [comment]
I will close the issue for now. If you get any reproducible steps then please let us know, we can re-open this.

**Comment by torchsmith** [comment]
FWIW, my first attempt at creating an ERD also lacked functionality like dragging. I just restarted PGAdmin and it fixed itself.

I'm on version 4.8.11

**Comment by craigreyenga** [comment]
This just happened to me as well. Much like the previous comment, exiting the app and reopening it solves the problem.

This issue should be reopened.

```
Version
9.4
Application Mode
Desktop
Commit
7c74b7cdb764d54ba7f42e0644b3f1d3ee7c786f 2025-05-27
Python Version
3.13.2
Current User
pgadmin4@pgadmin.org
Electron Version
35.4.0
Browser
Chrome 134.0.6998.205
Operating System
macOS-15.5-arm64-arm-64bit-Mach-O
```

**Comment by craigreyenga** [comment]
Just as an FYI to the maintainers: there isn't much to see in a screen recording. Basically, open the ERD tool, add a table, and then attempt to move it. It will not move. The screen recording would simply show stuff sitting in whatever position it started in.

The steps to reproduce, at least in my case are:

1. Install the app.
1. Launch it.
1. Connect to a DB
1. Open the ERD tool
1. Add a table.
1. Attempt to move the table; it will be stuck there.

After exiting and restarting the app, the issue is gone forever.

**Comment by adityatoshniwal** [comment]
@craigreyenga  Are you taking any screenshot of ERD? In past, taking a screenshot(using Mac shortcut have created problems.

**Comment by craigreyenga** [comment]
> [@craigreyenga](https://github.com/craigreyenga) Are you taking any screenshot of ERD? In past, taking a screenshot(using Mac shortcut have created problems.

I take screenshots really often. I have a dedicated button for it on my on-screen keyboard. It is the equivalent of cmd-shift-4.

But I don't think I did any screenshots around that time.

**Comment by torchsmith** [comment]
I definitely did not do screenshots when mine broke.
