### ISSUE TITLE
Use virtualisation of DataGridView in SchemaView for better performance

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#7607]

**Comment by pravesh-sharma** [comment]
1. Adding/removing users from user management and clicking the save button crashes the application.
2. Opening the user management dialog and closing crashes the application.


https://github.com/pgadmin-org/pgadmin4/assets/111979571/b9f0b488-5cb7-4bf9-8e91-b744a80991d2

**Comment by adityatoshniwal** [comment]
Side effect of React 18. Working on it.

**Comment by pravesh-sharma** [comment]
Verified on latest docker snapshot image and is working fine.
