### ISSUE TITLE
Find in sql editor not working (CTRL + f)

### ISSUE THREAD

**Issue by DLRSKINS001** [pgadmin-org/pgadmin4#7610]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Press CTRL + f and nothing happens

Open Query Tool
Open SQL script
Press CTRL + f

**Expected behavior**

Find window should open

**Desktop (please complete the following information):**
Version  8.8
Application Mode  Desktop
Current User  pgadmin4@pgadmin.org
NW.js Version  0.77.0
Browser  Chromium 114.0.5735.91
Operating System  Windows-10-10.0.19045-SP0

**Comment by adityatoshniwal** [comment]
Duplicates https://github.com/pgadmin-org/pgadmin4/issues/7555

**Comment by poojapatelgithub** [comment]
Facing same issue 
Press CTRL + f and nothing happens

About pgAdmin 4
Version
8.8
Application Mode
Desktop
Current User
pgadmin4@pgadmin.org
NW.js Version
0.77.0
Browser
Chromium 114.0.5735.91
Operating System
Linux-6.5.0-41-generic-x86_64-with-glibc2.35

**Comment by adityatoshniwal** [comment]
> Facing same issue Press CTRL + f and nothing happens
> 
> About pgAdmin 4 Version 8.8 Application Mode Desktop Current User [pgadmin4@pgadmin.org](mailto:pgadmin4@pgadmin.org) NW.js Version 0.77.0 Browser Chromium 114.0.5735.91 Operating System Linux-6.5.0-41-generic-x86_64-with-glibc2.35

Upgrade to 8.9
