### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by DavidBuch1** [pgadmin-org/pgadmin4#7611]
I will be working in pgadmin quite happily, when it just suddenly closes and loses everything I have been working on.

It is completely random, but generally happens at the most critical time for me. I have lost so much work already from these random crashes!

I am working in the version 8.8 on Mac running Sonoma 14.5 and 128GB ram, so ram is NOT an issue here.

**Comment by khushboovashi** [comment]
Please share logs, you can find them @ pgAdmin4 > Runtime > View Logs menu.

**Comment by DavidBuch1** [comment]
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3"
Runtime Config File: "/Users/david/Library/Preferences/pgadmin/runtime_config.json"
pgAdmin Config File: "/Applications/pgAdmin 4.app/Contents/Resources/web/config.py"
Webapp Path: "/Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
pgAdmin Command: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3 -s /Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
Environment: 
  - MallocNanoZone: 0
  - USER: david
  - COMMAND_MODE: unix2003
  - __CFBundleIdentifier: org.pgadmin.pgadmin4
  - PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
  - LOGNAME: david
  - SYSTEM_VERSION_COMPAT: 0
  - SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.zeCAD4KBjj/Listeners
  - HOME: /Users/david
  - SHELL: /bin/zsh
  - TMPDIR: /var/folders/nv/mnvn7dj514lfzhrmqyz4m2jw0000gp/T/
  - __CF_USER_TEXT_ENCODING: 0x1F6:0x0:0xF
  - XPC_SERVICE_NAME: application.org.pgadmin.pgadmin4.155423074.155438048
  - XPC_FLAGS: 0x0
  - PGADMIN_INT_PORT: 63872
  - PGADMIN_INT_KEY: 2e76670f-9d24-4386-bfca-16e53baccd62
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.01 Sec
2024-06-21 09:52:55,380: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 2.518 Sec
------------------------------------------
Total launch time of pgAdmin4: 2.755 Sec
------------------------------------------

**Comment by akshay-joshi** [comment]
Hi

The logs you sent are the latest logs from when you relaunched pgAdmin 4. Could you please check the log files in the /Users/david/Library/Application Support/pgadmin folder and share any log files that might contain crash information or useful error logs?

**Comment by DavidBuch1** [comment]
Hi

Here is the log from before that.

￼
Cheers


Kind regards

David Buch

CEO & Founder Appzoola

+61 451 753 960
+1 218-203-5343

Meeting request: https://calendly.com/appzoola
￼

On 21 Jun 2024, at 18:06, Akshay Joshi ***@***.***> wrote:


Hi

The logs you sent are the latest logs from when you relaunched pgAdmin 4. Could you please check the log files in the /Users/david/Library/Application Support/pgadmin folder and share any log files that might contain crash information or useful error logs?

**Comment by adityatoshniwal** [comment]
@DavidBuch1 Attachment is missing.

**Comment by DavidBuch1** [comment]
Hi Sorry about that


It has just happened again. I am attaching the two latest logs


Kind regards
￼￼
David Buch

CEO & Founder Appzoola

+61 451 753 960
+1 218-203-5343

Meeting request: https://calendly.com/appzoola
￼

On 24 Jun 2024, at 15:31, Aditya Toshniwal ***@***.***> wrote:


@DavidBuch1 <https://github.com/DavidBuch1> Attachment is missing.

**Comment by DavidBuch1** [comment]
I have now just had the white screen

Attaching the logs and screen shot.

I have tried resetting layout etc, nothing works. I just get a completely white screen

￼￼
Kind regards

David Buch

CEO & Founder Appzoola

+61 451 753 960
+1 218-203-5343

Meeting request: https://calendly.com/appzoola
￼

On 24 Jun 2024, at 15:31, Aditya Toshniwal ***@***.***> wrote:


@DavidBuch1 <https://github.com/DavidBuch1> Attachment is missing.

**Comment by adityatoshniwal** [comment]
Hi @DavidBuch1,
Still not able to see the attachments. Please open the ticket on github and upload. Not via mail.

**Comment by DavidBuch1** [comment]
[pgadmin4.1719271069043.log](https://github.com/user-attachments/files/15966669/pgadmin4.1719271069043.log)
[pgadmin4.1719183728013.log](https://github.com/user-attachments/files/15966670/pgadmin4.1719183728013.log)
Here you go

**Comment by adityatoshniwal** [comment]
@DavidBuch1 We didn't find anything suspicious in the logs. Can you please share the screenshot as well?

**Comment by DavidBuch1** [comment]
I'm afraid there. is not much to see on the screenshot. When it goes white, thats it.. and when it crashes, it just shuts down
![Screenshot 2024-06-25 at 09 16 00](https://github.com/pgadmin-org/pgadmin4/assets/67270211/9fe024a2-0b63-45dd-9af9-583aab166af7)

**Comment by DavidBuch1** [comment]
Still with this same issue.
I was saving large function I was writing to disk for safekeeping. pgAdmin indicated it had saved, and then decided to to its sudden shutdown.
The query I was writing was NOT saved, and there is nothing in the log. Lost about an hour of work.

**Comment by khushboovashi** [comment]
Hi @DavidBuch1, we have shifted from NWjs to Electron and that will be available in the next release. By that time you can test the snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/.

**Comment by pravesh-sharma** [comment]
No response from the author, hence closing the issue.
