### ISSUE TITLE
Add git commit details in the about dialog

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#7623]
It is helpful to show git commit hash details along with date.

**Comment by RohitBhati8269** [comment]
Commit key shows on the About page but doesn't contain value:-

![Image](https://github.com/pgadmin-org/pgadmin4/assets/167757499/f6433fc4-9d77-4076-b300-715021740af5)

**Comment by RohitBhati8269** [comment]
It was working fine with the Mac installer(dmg package) but with the wheel package, it still gave a blank commit value.

**Comment by RohitBhati8269** [comment]
On the wheel package installer, it's still not showing the commit value.
