### ISSUE TITLE
"Connect to server" dialog password field autocomplete property is set to "new-password", preventing password managers from working

### ISSUE THREAD

**Issue by ianbamforth** [pgadmin-org/pgadmin4#7627]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When connecting to a new server, you are prompted for a password by a popup headed "Connect to server". I use a password manager, which should be offering me stored passwords for this site. It does not, and instead offers to create me a new password. This is likely because the password field is incorrectly labelled as `autocomplete="new-password"` rather than `autocomplete="password"`.

**To Reproduce**

1. With a password manager installed...
2. Select a server to connect to, where the password is _not _ stored
4. Observe that the password manager offers to create a new password for you, rather than offering you a saved password

**Expected behavior**

Password managers should offer you a saved password when encountering a password field. 

**Error message**

n/a

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/7094207/9b0057e0-d85a-4433-9a0a-92206c37f4ac)

![image](https://github.com/pgadmin-org/pgadmin4/assets/7094207/7c355091-7326-497a-8e65-f3aa9bc04dde)

**Desktop (please complete the following information):**
 - OS: Windows 11 local / Ubuntu 22 server
 - Version: pgAdmin 4 version 8.8
 - Mode: Server
 - Browser (if running in server mode): Edge 125
 - Package type: Unknown

**Additional context**

n/a

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-07-02/
Package: pip wheel
Environment: macOs Ventura 13.5.1
