### ISSUE TITLE
Schema Diff: Generate script button remains enabled even if not object is selected.

### ISSUE THREAD

**Issue by pravesh-sharma** [pgadmin-org/pgadmin4#7638]
**To Reproduce**

1. Open schema diff and compare two DBs or schemas
2. Click on the check box to select any object, generate script button gets enabled.
3. Change schema or click on the compare button again, generate script is still enabled however no object is selected

**Expected behavior**
The generate script button should be disabled.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Version: 8.9
 - Mode: Desktop

**Comment by yogeshmahajan-1903** [comment]
Working fine.
