### ISSUE TITLE
ERD tool: Open and save button shortcut not working

### ISSUE THREAD

**Issue by pravesh-sharma** [pgadmin-org/pgadmin4#7639]
**To Reproduce**

Open the ERD Tool and press the shortcut key to open save or open dialog, no action is performed. On server mode pressing shortcut opens the browser's(native) dialog.

**Expected behavior**

Save and open dialog should open on pressing the shortcut key.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: 8.9
 - Mode: Desktop and Server
 - Browser (if running in server mode): Chrome
 - Package type: DEB

**Comment by RohitBhati8269** [comment]
It is fixed with the latest Electron changes.
Tested on:- [snapshot build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-07-17/)
OS:- Ubuntu

**Comment by RohitBhati8269** [comment]
Fixed  and Tested on:- [build](https://developer.pgadmin.org/builds/2024-07-29-1/) 
OS:- Ubuntu/Mac
