### ISSUE TITLE
Title: Missing Foreign Key Constraint in Automatically Generated SQL for Self-Referencing One-to-Many Relationship

### ISSUE THREAD

**Issue by Habtamu-Dires** [pgadmin-org/pgadmin4#7642]
**Describe the bug**
When creating a table with a self-referencing one-to-many relationship in pgAdmin, the automatically generated SQL does not include the foreign key constraint between the attributes. Specifically, when defining a table with a foreign key that references the primary key within the same table, the generated SQL omits the foreign key constraint.

**To Reproduce**
    1. Go to pgAdmin.
    2. Create a new table with a primary key and a self-referencing foreign key (e.g., employee table with employee_id as primary key 
    and manager_id referencing employee_id).
   3. Save the table.
   4.Check the automatically generated SQL in the SQL tab.

**Expected behavior**
The automatically generated SQL should include the foreign key constraint for the self-referencing one-to-many relationship.
**Error message**
No error message is displayed, but the generated SQL is missing the foreign key constraint.

**Desktop (please complete the following information):**
 - OS:Linux MInt 21.3 cinnamon
 - Version: cinnamon version 6.0.4
 - Mode: Destktop
 - Browser: FireFox
 - Package type: Container

**Additional context**
This issue affects the creation of hierarchical data structures within a single table, as the missing foreign key constraint prevents proper enforcement of data integrity. The expected SQL should look like: 
CREATE TABLE employee (
    employee_id INT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    manager_id INT,
    FOREIGN KEY (manager_id) REFERENCES employee(employee_id)
);
Currently, the generated SQL omits the FOREIGN KEY line.

**Comment by khushboovashi** [comment]
Hi @Habtamu-Dires, this is not reproducible at our end, can you please give the screen recording?
