### ISSUE TITLE
hope UPLOAD function can store .sql files in PostgreSQL database

### ISSUE THREAD

**Issue by ghr111** [pgadmin-org/pgadmin4#7651]
**Describe the solution you'd like**
Dear Developer,

I use multiple nodes to run pgadmin4 in server mode, PostgreSQL as database.
Using UPLOAD function to save .sql files in server's "DATA_DIR/storage".
When the next time accessing other node, the .sql files can't synchronize to other nodes automatic.
So I hope to store .sql files in PostgreSQL database.

Thanks for your reply.

**Additional context**

<img width="733" alt="图片" src="https://github.com/pgadmin-org/pgadmin4/assets/46097311/b6e7d8ea-fc78-4db9-8f57-585a8ee14da8">

**Comment by adityatoshniwal** [comment]
Hi @ghr111,
It is not clear what you're trying to achieve. SQL files are not uploaded to PostgreSQL database. They're stored on pgAdmin server. If you have 2 separate pgAdmin servers then they won't be shared of course.

**Comment by ghr111** [comment]
@adityatoshniwal Thank you for your reply,
I want to use PostgreSQL database to store SQL files, so that separate pgAdmin servers can shared SQL files. Can this function be implemented?

**Comment by khushboovashi** [comment]
Hi @ghr111, have you used the shared storage option? 
Please refer https://www.pgadmin.org/docs/pgadmin4/8.9/storage_manager.html. 
Your requirement should be fulfilled by Shared storage.

**Comment by ghr111** [comment]
> Hi @ghr111, have you used the shared storage option? Please refer https://www.pgadmin.org/docs/pgadmin4/8.9/storage_manager.html. Your requirement should be fulfilled by Shared storage.

Thank you for your reply, using "shared storage option" users can have common storages to share files, but that is not my scene.
For example, I have 2 machines install pgAadmin4 separately and with nginx in the front, when I use machine A to store files the next time login to machine B this causing can not use stored files.

**Comment by ghr111** [comment]
> Hi @ghr111, have you used the shared storage option? Please refer https://www.pgadmin.org/docs/pgadmin4/8.9/storage_manager.html. Your requirement should be fulfilled by Shared storage.

@khushboovashi Thank you for your reply, using "shared storage option" users can have common storages to share files, but that is not my scene.
For example, I have 2 machines install pgAadmin4 separately and with nginx in the front, when I use machine A to store files the next time login to machine B this causing can not use stored files.

**Comment by adityatoshniwal** [comment]
> > Hi @ghr111, have you used the shared storage option? Please refer https://www.pgadmin.org/docs/pgadmin4/8.9/storage_manager.html. Your requirement should be fulfilled by Shared storage.
> 
> @khushboovashi Thank you for your reply, using "shared storage option" users can have common storages to share files, but that is not my scene. For example, I have 2 machines install pgAadmin4 separately and with nginx in the front, when I use machine A to store files the next time login to machine B this causing can not use stored files.

Hi,

Share storages can be network storages as well. You can map a network drive and set it as shared storage.

**Comment by ghr111** [comment]
> > > Hi @ghr111, have you used the shared storage option? Please refer https://www.pgadmin.org/docs/pgadmin4/8.9/storage_manager.html. Your requirement should be fulfilled by Shared storage.
> > 
> > 
> > @khushboovashi Thank you for your reply, using "shared storage option" users can have common storages to share files, but that is not my scene. For example, I have 2 machines install pgAadmin4 separately and with nginx in the front, when I use machine A to store files the next time login to machine B this causing can not use stored files.
> 
> Hi,
> 
> Share storages can be network storages as well. You can map a network drive and set it as shared storage.

@adityatoshniwal Thank you for your reply, map a network drive such as NFS can solve the problem, but I will manage NFS by myself which increasing maintenance complexity

**Comment by adityatoshniwal** [comment]
We're closing this issue. A user may decide to use SQLite or PostgreSQL for config DB. Also, there are alternative solutions available. This doesn't come under pgAdmin scope.

**Comment by ant31** [comment]
Hi, 
I have exact same usecase. 
We've deployed pgadmin using Postgres as storage which works great but 
but few elements are still stored on the local storage such saved SQL queries. 

Storing "configuration" file locally makes deployements much more complex.
The end goal is to:
- Schedule pgadmin on any node of a cluster easily (noneead to attach any storage)
- Scale pgadmin beyond one instance 

Storing the SQL queries inside the storagemanager (sqlite/postgres...) instead of of local drive would be awesome and solve this !
