### ISSUE TITLE
PgAdmin error 'NoneType' object has no attribute '_query'

### ISSUE THREAD

**Issue by kmarimuthu90** [pgadmin-org/pgadmin4#7660]
**PgAdmin Setup Details:**

- We have deployed pgadmin on the AKS cluster. Helm chart 1.26.0 and app version 8.8. 
- DNS record is proxied in CloudFlare and it allows only HTTPS traffic. 
- And the DNS record is mapped with nginx ingress IP which is running in AKS. 
- We have an ingress controller to forward the traffic from 443 to backend pgadmin 8080

```
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    meta.helm.sh/release-name: pgadmin
    meta.helm.sh/release-namespace: pgadmin4
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  creationTimestamp: "2024-07-03T12:28:00Z"
  generation: 3
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pgadmin4
    app.kubernetes.io/version: "8.8"
    helm.sh/chart: pgadmin4-1.26.0
  name: pgadmin-pgadmin4
  namespace: pgadmin4
  resourceVersion: "699311774"
  uid: 5801c0f3-42c7-4663-922f-e3b83dfc7e2b
spec:
  rules:
  - host: pgadmin-nonprod.com
    http:
      paths:
      - backend:
          service:
            name: pgadmin-pgadmin4
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - pgadmin-nonprod.com
    secretName: tls-secret-pgadmin
```

pgadmin service running on AKS:
```
PS D:\2024-Q3\pgadmin-upgrade\pgadmin4> kubectl get svc -npgadmin4
NAME               TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)          AGE
pgadmin-pgadmin4   LoadBalancer   10.X.X.X   13.X.X.X  8080:31735/TCP   2d
```

**Issue:** 

When we run the below query it returns **'NoneType' object has no attribute '_query'**

```
select * from tenant where a.tenant_id not in 
(select tenant_id from tenant_app_tier_mapping where application_id=6 and status='A') a 
order by tenant_id desc;
```

**Logs from the PgAdmin pod:** 
```
2024-07-01 13:50:51,056: ERROR  pgadmin:        'NoneType' object has no attribute '_query'
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 304, in inner
    return mfa_enabled(
           ^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 169, in mfa_enabled
    return execute_if_enabled()
           ^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 301, in if_else_func_inner
    return _func(first, second)
           ^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 242, in mfa_session_authenticated
    return authenticated() if session.get('mfa_authenticated', False) is True \
           ^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 297, in execute_func
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/user_login_check.py", line 22, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/tools/sqleditor/__init__.py", line 992, in poll
    conn._Connection__async_cursor._query)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_query'
```

**Here are the values.yaml for the pgadmin deployment:**

```
VolumePermissions:
  enabled: false
affinity: {}
annotations: {}
autoscaling:
  enabled: true
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
commonLabels: {}
containerPorts:
  http: 8080
containerSecurityContext:
  allowPrivilegeEscalation: false
  enabled: false
env:
  email: *************
  enhanced_cookie_protection: "False"
  password: **********
  variables:
  - name: PGADMIN_LISTEN_PORT
    value: "8080"
  - name: PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT
    value: "False"
  - name: PGADMIN_CONFIG_WTF_CSRF_ENABLED
    value: "False"
  - name: PGADMIN_CONFIG_CONSOLE_LOG_LEVEL
    value: "10"
envVarsExtra: []
envVarsFromConfigMaps: []
envVarsFromSecrets: []
existingSecret: ""
extraConfigmapMounts: []
extraContainers: ""
extraDeploy: []
extraInitContainers: ""
extraSecretMounts: []
extraVolumeMounts: []
extraVolumes: []
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: dpage/pgadmin4
  tag: ""
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
  - host: pgadmin-nonprod.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - pgadmin-nonprod.com
    secretName: tls-secret-pgadmin
init:
  resources: {}
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 60
  successThreshold: 1
  timeoutSeconds: 15
namespace: null
networkPolicy:
  enabled: true
nodeSelector:
  agentpool: appnodepool
persistentVolume:
  accessModes:
  - ReadWriteOnce
  annotations: {}
  enabled: true
  size: 6Gi
podAnnotations: {}
podLabels: {}
priorityClassName: ""
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 60
  successThreshold: 1
  timeoutSeconds: 15
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
secretKeys:
  pgadminPasswordKey: password
securityContext:
  fsGroup: 5050
  runAsGroup: 5050
  runAsUser: 5050
serverDefinitions:
  enabled: false
  existingConfigmap: ""
  existingSecret: ""
  resourceType: ConfigMap
  servers: null
service:
  annotations: {}
  clusterIP: ""
  loadBalancerIP: ""
  port: 8080
  portName: http
  targetPort: 8080
  type: LoadBalancer
serviceAccount:
  annotations: {}
  automountServiceAccountToken: false
  create: false
  name: ""
strategy: {}
templatedPodAnnotations: ""
test:
  image:
    registry: docker.io
    repository: busybox
    tag: latest
  resources: {}
  securityContext:
    fsGroup: 5051
    runAsGroup: 5051
    runAsUser: 5051
tolerations:
- effect: NoSchedule
  key: pool
  operator: Equal
  value: app00
```

Kindly help on this pls

**Comment by kmarimuthu90** [comment]
![image](https://github.com/pgadmin-org/pgadmin4/assets/67636927/5f3e7530-0301-4228-947c-9532bab5471e)

**Comment by khushboovashi** [comment]
Hi @kmarimuthu90, I couldn't reproduce this issue.
Did you face this issue with all the queries or a particular one?
Have you tried using any other Postgres server?

**Comment by kmarimuthu90** [comment]
It's happening randomly in Postgresql queries. We are facing this issue on all env from dev to prod PostgreSQL flexible server db

**Comment by kmarimuthu90** [comment]
I am using this helm chart, 
helm repo add runix https://helm.runix.net
helm pull runix/pgadmin4 --untar --version 1.26.0

**Comment by khushboovashi** [comment]
@kmarimuthu90, whenever you encounter this error, please check the connection status through Dashboard.
This error will occur only if the query tool loses its connection cursor; in that case, pgAdmin should show the connection lost popup.

**Comment by kmarimuthu90** [comment]
I don't see any connection loss here 
![image](https://github.com/pgadmin-org/pgadmin4/assets/67636927/2a5e8059-9960-434a-bc82-12625042b603)

![image](https://github.com/pgadmin-org/pgadmin4/assets/67636927/0b29add4-c53a-4ba2-b883-9a54813b74bb)

**Comment by kmarimuthu90** [comment]
Is there any doc available to install pgadmin with nginx ingress by using helm?

**Comment by Ctrl-Elite** [comment]
Is there any update? I'm having the same issue (Not using K8S, just in Docker).

`2024-07-19 08:35:38,078: ERROR  pgadmin:        'NoneType' object has no attribute '_query'
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 304, in inner
    return mfa_enabled(
           ^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 169, in mfa_enabled
    return execute_if_enabled()
           ^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 301, in if_else_func_inner
    return _func(first, second)
           ^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 242, in mfa_session_authenticated
    return authenticated() if session.get('mfa_authenticated', False) is True \
           ^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 297, in execute_func
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/user_login_check.py", line 22, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/tools/sqleditor/__init__.py", line 992, in poll
    conn._Connection__async_cursor._query)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_query'`

**Comment by khushboovashi** [comment]
@Ctrl-Elite,

We have fixed the issue; you can test it on the snapshot.
docker pull dpage/pgadmin4:snapshot

**Comment by RohitBhati8269** [comment]
Issue fixed and verified with [snapshot-build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-07-22/)
OS - macOS/Ubuntu

**Comment by RohitBhati8269** [comment]
Issue fixed and verified with [snapshot-build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-07-22/)
OS - macOS/Ubuntu

**Comment by kmarimuthu90** [comment]
Hi team,

Is this fix included in any of the helm chart app version? I am using helm
chart pgadmin4-1.26.0 and app version 8.8.


Thanks,
Krishnakumar.M

**Comment by khushboovashi** [comment]
@kmarimuthu90, we do not support the helm chart. We have fixed this issue and will be available in the next release.
You need to keep an eye on the helm chart updated version which will include this fix.
