### ISSUE TITLE
docker: config_local.py not read

### ISSUE THREAD

**Issue by saper-2** [pgadmin-org/pgadmin4#7668]
**Describe the bug**

Like in topic. I created `config_local.py` beside `pgadmin4.db` and it's not being read. 

Basically I want to disable this ret... stupid email_validator because I DO NOT WANT TO USE EMAIL (it's stupid to use email for MY LOCAL LAB SERVER **IN HOME**). So I found a half-solution in https://github.com/pgadmin-org/pgadmin4/issues/6222 , looking in doc https://www.pgadmin.org/docs/pgadmin4/development/config_py.html#the-config-py-file , I created file (where I think it should be - there is NOTHING where this file SHOULD BE).

*Sorry, I'm not that good with docker*

**To Reproduce**

1. Create composer file,
2. let run pgadmin for once, close it.
3. Create `config_local.py` in (mounted) `data` directory, chown+chmod to `5050:5050` & `0660` (I even tried 0777).
4. Nothing happens, ( `email_validator` continues to being annoying)

**Expected behavior**

Local config file `config_local.py` being read. Or documentation updated where it should be placed.

**Screenshots**

Here is a bit of console, that should explain everything. (I have crated group in linux `5050=pgadmin` (and added myself to it)), also aIso I added a line with 'print' to config file to see if it'll be read (I think I should see this in console).
```
saper@lanserv:~/composers/pgadmin4 $ ll data
total 184K
drwxr-xr-x 2 5050 pgadmin 4.0K Jul  7 18:46 azurecredentialcache
-rwxrwx--x 1 5050 pgadmin  124 Jul  7 19:36 config_local.py
-rw------- 1 5050 pgadmin 164K Jul  7 18:49 pgadmin4.db
drwx------ 2 5050 pgadmin 4.0K Jul  7 19:40 sessions
drwxr-xr-x 2 5050 pgadmin 4.0K Jul  7 18:46 storage
saper@lanserv:~/composers/pgadmin4 $ sudo cat data/config_local.py
import email_validator
email_validator.SPECIAL_USE_DOMAIN_NAMES.remove("local")
print("email_validator settings updated.")
saper@lanserv:~/composers/pgadmin4 $ cat docker-compose.yaml
version: '3.8'
services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: saper@lanserv.local
      PGADMIN_DEFAULT_PASSWORD: test1234
    ports:
      - "5050:80"
    volumes:
     - ./data:/var/lib/pgadmin

saper@lanserv:~/composers/pgadmin4 $ docker-compose up
Starting pgadmin4_container ... done
Attaching to pgadmin4_container
pgadmin4_container | postfix/postlog: starting the Postfix mail system
pgadmin4_container | [2024-07-07 18:12:59 +0000] [1] [INFO] Starting gunicorn 22.0.0
pgadmin4_container | [2024-07-07 18:12:59 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
pgadmin4_container | [2024-07-07 18:12:59 +0000] [1] [INFO] Using worker: gthread
pgadmin4_container | [2024-07-07 18:12:59 +0000] [83] [INFO] Booting worker with pid: 83
pgadmin4_container | ::ffff:192.168.2.21 - - [07/Jul/2024:18:13:46 +0000] "GET / HTTP/1.1" 302 213 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
pgadmin4_container | ::ffff:192.168.2.21 - - [07/Jul/2024:18:15:30 +0000] "GET /login HTTP/1.1" 200 2559 "http://192.168.2.120:5050/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
pgadmin4_container | ::ffff:192.168.2.21 - - [07/Jul/2024:18:15:44 +0000] "GET /login HTTP/1.1" 200 2493 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
pgadmin4_container | ::ffff:192.168.2.21 - - [07/Jul/2024:18:18:33 +0000] "GET /tools/translations.js?ver=80900 HTTP/1.1" 200 321 "http://192.168.2.120:5050/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
pgadmin4_container | ::ffff:192.168.2.21 - - [07/Jul/2024:18:18:33 +0000] "GET /browser/js/endpoints.js?ver=80900 HTTP/1.1" 200 15250 "http://192.168.2.120:5050/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
pgadmin4_container | The part after the @-sign is a special-use or reserved name that cannot be used with email.
```

**Desktop (please complete the following information):**
 - OS: Debian 12.5, docker, docker-compose
 - Version: latest from docker
 - Mode: server
 - Browser (if running in server mode): FF
 - Package type: docker
 
```
saper@lanserv:~/composers/pgadmin4 $ docker pull dpage/pgadmin4:latest
latest: Pulling from dpage/pgadmin4
Digest: sha256:9d75116cc9cfbf33a0927a9928c99a46356b658bb7bfc2345ff921e5f7725e3f
Status: Image is up to date for dpage/pgadmin4:latest
docker.io/dpage/pgadmin4:latest
```

**Comment by adityatoshniwal** [comment]
Hi @saper-2,
You're putting the file in an incorrect location. You need to map the config_loca.py - https://www.pgadmin.org/docs/pgadmin4/8.9/container_deployment.html#mapped-files-and-directories

**Comment by saper-2** [comment]
@adityatoshniwal - duh, it's completely in different place this information that I'd search ever.... 😑 

Ok, got it working... I forgot that I can bind a file too (most time I bind folders so I totally forgot about this too...)

Here is my docker-compose file, you can use it as example if you want 😄 

**docker-compose.yaml**
```
version: '3.8'
services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@server.local
      PGADMIN_DEFAULT_PASSWORD: ThePassword
    ports:
      - "5050:80"
    volumes:
      - ./data:/var/lib/pgadmin
      - type: bind
        source: ./config_local.py
        target: /pgadmin4/config_local.py
```

Create directory data with this docker-compose file, chown it to 5050:5050  (this is docs too), create beside composer file a `config_local.py` (`chwon` to `5050:5050`  and `chmod u+rw` or `ug+rw`). 
**config_local.py**:
```
import email_validator
email_validator.SPECIAL_USE_DOMAIN_NAMES.remove("local")
```

Leaving this for someone that would look for it....
