### ISSUE TITLE
Fail to work with Find and Replace options on pgadmin

### ISSUE THREAD

**Issue by Michellehdr** [pgadmin-org/pgadmin4#7670]
1. Deploy OS, and install all updates
2. Enable roles & features.
3. Download the application from vendor [link](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads).
4. Install the application and Restart the machine.
5. Launch pgadmin from the start menu.
6. Connect to the database.
7. Go to Tool menu ->click on query tool option.
8. Write the sql query.
9. Click edit option ->Try to work with find and replace options.
10. Observe.

Actual Results: Fail to work with Find and Replace options within the application with latest version of app

**Comment by pravesh-sharma** [comment]
Hi @Michellehdr,

Could you please let me know which version of pgAdmin you are using? You can find this info from `Help -> About pgAdmin 4`

**Comment by Michellehdr** [comment]
Hi @pravesh-sharma the version of pgAdmin is 8.7. Please refer to the screenshot.
![Screenshot 2024-07-11 095614](https://github.com/pgadmin-org/pgadmin4/assets/75816577/5e2f4d93-8cb3-407b-a58d-08bfdfb27ed5)

**Comment by pravesh-sharma** [comment]
Hi @Michellehdr

Could you please try out the latest version of pgAdmin from the link I provided in the previous comment and check?

**Comment by Michellehdr** [comment]
Hi @pravesh-sharma our tester verified with the pgAdmin version downloaded from (https://www.pgadmin.org/download/), and found the issue no longer repro. Thanks a lot for your great support.

**Comment by pravesh-sharma** [comment]
Closing as per author's confirmation.
