### ISSUE TITLE
Not able to download results to file

### ISSUE THREAD

**Issue by seanwbarry** [pgadmin-org/pgadmin4#7671]
reopening bug:
#6336

Describe the bug
pgAdmin 8.9 cannot download results (using f8 hotkey, or the "download" button above the query results pane) for large numbers of records. After clicking save result to file button (F8), it goes on the loading screen with the message "Downloading results" appears.
Issue1# Even after waiting for many hours (8-9 hours for 523,970 records) no downloaded file is created.
Issue2# There is no button to stop this, to cancel this process, pgAdmin needs to be closed.

Version
8.9
Application Mode
Desktop
Current User
[pgadmin4@pgadmin.org](mailto:pgadmin4@pgadmin.org)
NW.js Version
0.77.0
Browser
Chromium 114.0.5735.91
Operating System
Windows-11-10.0.22631-SP0

**Comment by khushboovashi** [comment]
Duplicates #3369. So, closing the issue.
