### ISSUE TITLE
Column Visibility Discrepancy and Query Tool Malfunction in pgAdmin

### ISSUE THREAD

**Issue by ReubenJFraser** [pgadmin-org/pgadmin4#7673]
Bug Description

**1. Column Visibility Discrepancy:**

Initially, I reported an issue where I could not see any columns listed under the Columns node in the Restaurants table.
Support staff member Yogesh presumed this was due to user error and instructed me to ensure I was selecting the correct node.
After providing multiple screenshots showing that I was indeed selecting the correct node, Yogesh finally provided a screenshot from his side, indicating he could see 29 columns in the same table.
This confirmed that the issue was not user error but a deeper problem, as I could not see any columns while Yogesh could see all 29.

**2. Query Tool Malfunction:**

Following the confirmation of the column visibility issue, I encountered a new problem with the Query Tool.
When attempting to open the Query Tool as Yogesh had directed me to do so, the following sequence occurred:

A revolving circle icon briefly appears.
This is followed by a flash.
The screen then closes, displaying the message: "! No data output. Execute a query to get output."

Despite following guidance from ChatGPT to enable Query Tool Logging and executing the correct steps, the issue persists.

Steps to Reproduce

Attempt to open the Query Tool.
Observe the revolving circle icon, followed by a flash and the error message.
Check the Columns node in the Restaurants table and note the absence of columns.
Expected Behavior
The Query Tool should open without errors, allowing queries to be executed.
Columns in the Restaurants table should be visible and accessible.
Troubleshooting Steps Taken
Attempted to enable Query Tool Logging as per ChatGPT's instructions but could not locate the Logging option.
Ensured that I was selecting the Restaurants table correctly, but the columns remain invisible.
Screenshot of Query Tool error is attached.

Additional Context
The support staff initially presumed user error for the column visibility issue.
After confirming that I was selecting the correct node, it was verified by Yogesh through a screenshot that he could see 29 columns while I could see none.
Following this, the Query Tool malfunction became apparent, further complicating the issue.
Yogesh has since shifted focus back to user error, disregarding the earlier confirmed problem.
Conclusion
Given these issues and the unproductive nature of current support interactions, I seek detailed guidance from a higher level of support. There appears to be a connection between the column visibility problem and the Query Tool malfunction. Reinstalling pgAdmin is a consideration, but given that my initial setup was correct, I am uncertain and very doubtful that this will resolve the issues.

Your assistance in resolving this matter would be greatly appreciated.

Best regards,

Reuben

The image screenshot files below don't seem to be working, which is yet another example of things not working as they should.

![2024-7-05-Screenshot](https://github.com/pgadmin-org/pgadmin4/assets/141807448/da834398-574c-4a4e-a525-90ca1ad96726)

![2024-7-06-Screenshot-3](https://github.com/pgadmin-org/pgadmin4/assets/141807448/d0343c94-f5dc-4569-91fd-dbc95d2c8b46)

**Comment by khushboovashi** [comment]
@ReubenJFraser, please link your old reported issue here so we can track those conversations.

**Comment by adityatoshniwal** [comment]
@ReubenJFraser  Please mention OS, pgAdmin version, PostgreSQL version.

**Comment by pravesh-sharma** [comment]
No response from the author, hence closing the issue.
