### ISSUE TITLE
iFrame embedding breaks after login

### ISSUE THREAD

**Issue by githuberj** [pgadmin-org/pgadmin4#7681]
[pgAdmin-investigation-issue.zip](https://github.com/user-attachments/files/16163039/pgAdmin-investigation-issue.zip)
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Iframe embedding fails after the login screen with a javascript error
![image](https://github.com/pgadmin-org/pgadmin4/assets/83455398/ebfe4613-c7fc-421f-88ac-4b2cf76cef32)
Using a reverse proxy and no iframe works, but we would need the iFrame too.
While it looked similar to issue https://redmine.postgresql.org/issues/6105, I was unable to resolve this issue. 

**To Reproduce**

I put the a few files to reproduce into the attachments:

- Dockerfile
- docker-compose.yaml
- nginx.conf
- index.html

docker-compose up should build and start the containers 

Go to localhost:8082 and then you should be able to login to the application (credentials are in the docker-compose)
In the developer console you should see two errors

**Expected behavior**

IFrame embedding works and no errors happen after login

**Error message**
Copied from console: 
TypeError: Cannot read properties of undefined (reading 'pgAdmin')
    at app.bundle.js?ver=80900:1:1309985
    at Au (vendor.react.js?ver=80900:2:145457)
    at t.unstable_runWithPriority (vendor.others.js?ver=80900:312:1438185)
    at qo (vendor.react.js?ver=80900:2:86276)
    at Tu (vendor.react.js?ver=80900:2:144925)
    at bu (vendor.react.js?ver=80900:2:136513)
    at vendor.react.js?ver=80900:2:86499
    at t.unstable_runWithPriority (vendor.others.js?ver=80900:312:1438185)
    at qo (vendor.react.js?ver=80900:2:86276)
    at Qo (vendor.react.js?ver=80900:2:86444)
ca @ vendor.react.js?ver=80900:2
n.callback @ vendor.react.js?ver=80900:2
hi @ vendor.react.js?ver=80900:2
va @ vendor.react.js?ver=80900:2
Fu @ vendor.react.js?ver=80900:2
t.unstable_runWithPriority @ vendor.others.js?ver=80900:312
qo @ vendor.react.js?ver=80900:2
Mu @ vendor.react.js?ver=80900:2
bu @ vendor.react.js?ver=80900:2
(anonym) @ vendor.react.js?ver=80900:2
t.unstable_runWithPriority @ vendor.others.js?ver=80900:312
qo @ vendor.react.js?ver=80900:2
Qo @ vendor.react.js?ver=80900:2
Go @ vendor.react.js?ver=80900:2
hu @ vendor.react.js?ver=80900:2
Ol @ vendor.react.js?ver=80900:2
(anonym) @ vendor.others.js?ver=80900:312
(anonym) @ vendor.others.js?ver=80900:312
r @ vendor.others.js?ver=80900:312
(anonym) @ app.bundle.js?ver=80900:1
p @ vendor.others.js?ver=80900:312
(anonym) @ vendor.others.js?ver=80900:312
(anonym) @ vendor.others.js?ver=80900:312
t @ vendor.others.js?ver=80900:312
a @ vendor.others.js?ver=80900:312
Promise.then (asynchron)
t @ vendor.others.js?ver=80900:312
a @ vendor.others.js?ver=80900:312
(anonym) @ vendor.others.js?ver=80900:312
(anonym) @ vendor.others.js?ver=80900:312
(anonym) @ app.bundle.js?ver=80900:1
init @ app.bundle.js?ver=80900:1
(anonym) @ app.bundle.js?ver=80900:1
21607 @ app.bundle.js?ver=80900:1
c @ app.bundle.js?ver=80900:1
87612 @ app.bundle.js?ver=80900:1
c @ app.bundle.js?ver=80900:1
(anonym) @ app.bundle.js?ver=80900:1
c.O @ app.bundle.js?ver=80900:1
(anonym) @ app.bundle.js?ver=80900:1
(anonym) @ app.bundle.js?ver=80900:1
execCb @ require.min.js?ver=80900:9
check @ require.min.js?ver=80900:9
(anonym) @ require.min.js?ver=80900:9
(anonym) @ require.min.js?ver=80900:9
(anonym) @ require.min.js?ver=80900:9
each @ require.min.js?ver=80900:9
emit @ require.min.js?ver=80900:9
check @ require.min.js?ver=80900:9
enable @ require.min.js?ver=80900:9
init @ require.min.js?ver=80900:9
O @ require.min.js?ver=80900:9
completeLoad @ require.min.js?ver=80900:9
onScriptLoad @ require.min.js?ver=80900:9
load (asynchron)
req.load @ require.min.js?ver=80900:9
load @ require.min.js?ver=80900:9
load @ require.min.js?ver=80900:9
fetch @ require.min.js?ver=80900:9
check @ require.min.js?ver=80900:9
enable @ require.min.js?ver=80900:9
enable @ require.min.js?ver=80900:9
(anonym) @ require.min.js?ver=80900:9
(anonym) @ require.min.js?ver=80900:9
each @ require.min.js?ver=80900:9
enable @ require.min.js?ver=80900:9
init @ require.min.js?ver=80900:9
O @ require.min.js?ver=80900:9
completeLoad @ require.min.js?ver=80900:9
onScriptLoad @ require.min.js?ver=80900:9
load (asynchron)
req.load @ require.min.js?ver=80900:9
load @ require.min.js?ver=80900:9
load @ require.min.js?ver=80900:9
fetch @ require.min.js?ver=80900:9
check @ require.min.js?ver=80900:9
enable @ require.min.js?ver=80900:9
enable @ require.min.js?ver=80900:9
(anonym) @ require.min.js?ver=80900:9
(anonym) @ require.min.js?ver=80900:9
each @ require.min.js?ver=80900:9
enable @ require.min.js?ver=80900:9
init @ require.min.js?ver=80900:9
(anonym) @ require.min.js?ver=80900:9
setTimeout (asynchron)
req.nextTick @ require.min.js?ver=80900:9
o @ require.min.js?ver=80900:9
requirejs @ require.min.js?ver=80900:9
(anonym) @ browser/:121
app.bundle.js?ver=80900:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pgRespErrorNotify')
    at app.bundle.js?ver=80900:1:892512
    at p (vendor.others.js?ver=80900:312:1936492)
    at Generator.<anonymous> (vendor.others.js?ver=80900:312:1937834)
    at Generator.next (vendor.others.js?ver=80900:312:1936921)
    at t (vendor.others.js?ver=80900:312:1930485)
    at a (vendor.others.js?ver=80900:312:1930696)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows with WSL
 - Version: 8.9:latest (as in docker-compose)
 - Mode: Server
 - Browser (if running in server mode): edge
 - Package type: container

**Additional context**

**Comment by pravesh-sharma** [comment]
The issue remains reproducible in the latest snapshot build.

**Comment by pravesh-sharma** [comment]
Issue fixed. verified with today's docker snapshot image.

OS - macOS Sonoma 14.5
Mode - Server

**Comment by githuberj** [comment]
Thank you very much :) It also works for me with the snapshot tag
