### ISSUE TITLE
Schema Diff: Generate script Ignores Filter Conditions When Using "Select All"

### ISSUE THREAD

**Issue by WeiJie-JL** [pgadmin-org/pgadmin4#7682]
**Describe the bug**

After generating the schema diff results in pgAdmin4, the "Select All" button ignores any filter conditions that have been applied, leading to a potentially dangerous situation where objects could be unintentionally modified or dropped. 

**To Reproduce**

1.After the diff results are displayed, uncheck the "target only" option in the top-right corner.
2.Select all items in the displayed results list. At this point, the list does not show items that are "target only."
3.Generate the change script. You will find that the script includes "DROP TABLE xxx CASCADE" statements.

**Expected behavior**

Only the visible selected content is included in the script.

**Desktop (please complete the following information):**
 - OS: both Windows 10 and OSX monterey
 - Version: 8.9
 - Mode: Desktop

**Additional context**

This behavior is completely counterintuitive and can easily lead to irreversible consequences. It is hoped that this issue can be addressed and resolved.

**Comment by rtrad89** [comment]
This also happens when I select all tables, or all functions, etc. so not only on the high-level select all checkbox but also on the subgroups.

**Comment by RohitBhati8269** [comment]
Issue fixed and Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-08-12/).

Env:-
OS - macOS arm
Mode - Server

**Comment by WeiJie-JL** [comment]
<img width="733" alt="image" src="https://github.com/user-attachments/assets/8b159942-445e-47bf-a23f-683607b9a070">
the issue can still be reproduced on the latest version 8.10.

**Comment by akshay-joshi** [comment]
@WeiJie-JL 

The fix has not been released yet, if you can check the milestone it is for v8.11.

**Comment by WeiJie-JL** [comment]
> @WeiJie-JL
> 
> The fix has not been released yet, if you can check the milestone it is for v8.11.

Alright, thank you very much.
