### ISSUE TITLE
During text edit, delete key tries to both delete selected text and any selected item in Object Explorer

### ISSUE THREAD

**Issue by paultobey** [pgadmin-org/pgadmin4#7683]
**Describe the bug**

In Windows (I have not tested on other OSes), when I'm editing query text, pressing the Del key to delete the currently selected text or to delete the next character in the text editor also attempts to delete the selected object in Object Explorer, generating an are-you-sure dialog (and a lot of frustration ;-)

**To Reproduce**

Open a database, select a table. Open query editor. Select some text in the query or place the cursor where the Del key makes sense for text editing. Press Del. The text editor operation occurs, but you also get an are-your-sure error about deleting the selected table.

**Expected behavior**

When the text editor uses a key, it should not pass it up the chain to other potential consumers like Object Explorer. It should just do the text editing operation.

**Screenshots**

State before pressing Del key. Note that I most-recently selected the text in the query editor, NOT the table in the Object Explorer so this isn't an issue of what is focused.

![pgAdmin 1](https://github.com/user-attachments/assets/72100ef8-e0dc-498b-b609-24b6db3beb80)

State after pressing Del key.

![pgAdmin 2](https://github.com/user-attachments/assets/e4d3efbf-4755-496a-b97c-ad8a4be45430)

State after dismissing are-your-sure with No. Note that the Del operation did the right thing in the query editor.

![pgAdmin 3](https://github.com/user-attachments/assets/59a8f1ed-e100-43e6-a355-f830e4db6085)

**Desktop (please complete the following information):**
 - OS: Windows 10, but I've also seen it in Windows Server 2022
 - Version: 8.9, 8.8, 8.7...
 - Mode: Desktop

**Comment by paultobey** [comment]
I'll also note that using the Find or Replace dialog in the query editor also has the same problem: entering some search or replacement text then Del also asks if you want to delete the table.

**Comment by adityatoshniwal** [comment]
Hi @paultobey,

Check your shortcuts in preferences. Possibly overlapping.
<img width="919" alt="image" src="https://github.com/user-attachments/assets/afade001-e271-4a8a-aec1-3e525c0381b6">

**Comment by paultobey** [comment]
> Hi @paultobey,
> 
> Check your shortcuts in preferences. Possibly overlapping. <img alt="image" width="919" src="https://private-user-images.githubusercontent.com/31855755/348660147-afade001-e271-4a8a-aec1-3e525c0381b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjAwNTUsIm5iZiI6MTcyMTA1OTc1NSwicGF0aCI6Ii8zMTg1NTc1NS8zNDg2NjAxNDctYWZhZGUwMDEtZTI3MS00YThhLWFlYzEtM2U1MjVjMDM4MWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE2MDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NmRjOWY1MWNjZmVjOWQ3NmI3Y2IzYzdiYjllNDYwZDVmMDY2MGNhNTVjODBjYzJiZTAwMDA0NTQxOTI5ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2pi7wf3jUY8qqFe-g7qluYzZXDWIBSPy_l1c5GV5KU">

@adityatoshniwal Agreed. If I wanted to alter keyboard shortcuts I could work-around it. However, it seems reasonable to delete from Object Explorer when that control is focused and from the text editor when that is focused. For example, if we have two query editors open, we don't apply the Del key to both of them. I guess it feels like this should be the same case.

**Comment by adityatoshniwal** [comment]
> @adityatoshniwal Agreed. If I wanted to alter keyboard shortcuts I could work-around it. However, it seems reasonable to delete from Object Explorer when that control is focused and from the text editor when that is focused. For example, if we have two query editors open, we don't apply the Del key to both of them. I guess it feels like this should be the same case.

I agree. Consider it as a workaround while we fix the issue.

**Comment by paultobey** [comment]
Much better in 8.10! Thanks!

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-08-07/) .

Env:
OS - macOS 14.5 (Sonoma)
Mode - Desktop
