### ISSUE TITLE
Problem with Results Grid

### ISSUE THREAD

**Issue by MARKPARE70** [pgadmin-org/pgadmin4#7699]
Hi, I just upgraded from v5.0 to v8.9 and here are some things that used to work, but no longer do:

Results Grid
CTRL-A does not work to highlight all data
CTRL-END does not work to get to the end of the list
CTRL-HOME does not work to get to the beginning of the list
Using arrow keys to navigate is slow and sometimes doesn't work, very flimsy

Query Windows
If you have many query windows open, there used to be a horizontal scroll bar at the top to manage switching between windows. Now you have to click on a tab and use the arrows to switch

I had previously entered these same problems and after the issue was vetted, kept getting pushed to the next release. I gave up, but now I am forced to use v8.9 because my company uses PostgreSQL 15.x and 16.x which v5.0 does not support.

Please help with these basic items. Thanks

**Comment by adityatoshniwal** [comment]
> Hi, I just upgraded from v5.0 to v8.9 and here are some things that used to work, but no longer do:
> 
> Results Grid CTRL-A does not work to highlight all data CTRL-END does not work to get to the end of the list CTRL-HOME does not work to get to the beginning of the list Using arrow keys to navigate is slow and sometimes doesn't work, very flimsy
> 

Shortcuts issue is reported here - #5099.

> Query Windows If you have many query windows open, there used to be a horizontal scroll bar at the top to manage switching between windows. Now you have to click on a tab and use the arrows to switch
> 

The current version supports scrolling and drop down arrow if tabs goes beyond the window.  There are no arrows to switch in 8.9.

> I had previously entered these same problems and after the issue was vetted, kept getting pushed to the next release. I gave up, but now I am forced to use v8.9 because my company uses PostgreSQL 15.x and 16.x which v5.0 does not support.
> 
> Please help with these basic items. Thanks

Closing as it is a duplicate.
