### ISSUE TITLE
Python psycopg2-binary having issue when using GSSAPI authentication to connect to postgres server

### ISSUE THREAD

**Issue by YeeY23** [pgadmin-org/pgadmin4#7702]
Hi hi, 
We have 3 different realms: the application is in one realm, and the PostgreSQL server is in another. The Python psycopg2-binary module encounters an issue when using GSSAPI authentication to connect to the PostgreSQL server from a Linux OS. 

The error message is: INFO:root:connection to server at "example.realm.com" (2.2.2.2), port 5432 failed: GSSAPI continuation error: Unspecified GSS failure. Minor code may provide more information: Invalid boolean value.

The connection string used is: conn_string = psycopg2.connect(f'host={host} port=5432 dbname={dbname}')
conn = psycopg.connect(conn_string)

We have installed krb5-workstation and libkrb5-dev on the application server.

For your information, the connection works successfully without error when using the same Python code from a Windows OS.

Thank you.

**Comment by yogeshmahajan-1903** [comment]
What is the  pgadmin version are you using? pgadmin is moved to psycopg-3.

**Comment by anilsahoo20** [comment]
No response from author, hence closing it.
