### ISSUE TITLE
Problem with Grid Results -> #5099 #7699

### ISSUE THREAD

**Issue by MARKPARE70** [pgadmin-org/pgadmin4#7716]
Hi I see that you closed 7699 as a duplicate. I originally opened a defect 2 years ago and the issues have not been fixed.

I see that there was a question about OS since you couldn't reproduce it in macOS. The OS I'm using in Windows.

Please either update the original (which i think is 5099) or re-open the new one with these details and get this fixed.

The previous release I mentioned was v6.9 so it's been broken for a long time and I now have no choice but to use this release since I need it to access PostgreSQL 15.x and 16.x

Thanks

**Comment by pravesh-sharma** [comment]
Hi @MARKPARE70,

The original issue #5099 is still open; therefore, we closed #7699. I am also closing this issue and recommend that you provide your feedback and suggestions on the original issue instead.
