### ISSUE TITLE
Alternative dockerfile that doesn't use setcap

### ISSUE THREAD

**Issue by jpholtmeyer** [pgadmin-org/pgadmin4#7721]
**Issue**
I'm creating this feature request because there is an issue deploying the pgadmin4 container on Kubernetes/OpenShift infrastructure.
The [setcap CAP_NET_BIND_SERVICE](https://github.com/pgadmin-org/pgadmin4/blob/master/Dockerfile#L214) command prevents Python executables from running and gives an 'Operation not permitted' error.

**Solution**
There is currently only a single Docker image being built.
My proposal is to build 2 docker images:
- The default docker image (already exists)
- A nocap docker image (simply removes the setcap command at the link above)

The issue is presented well here:
[Pgadmin python executable requires extended capabilities](https://www.postgresql.org/message-id/CA%2BOCxoxR2xrGx8%3DXXcwW6rOVQbrbBMpy9EapUw%3DSaA7qKfGR-w%40mail.gmail.com)

Depending on the build process, the default image could be used as a base for the new image:
```
FROM dpage/pgadmin4:8.9
USER root
RUN setcap -r /usr/bin/python3.12
USER pgadmin
```

Alternatively, an independent dockerfile could be created that simply leaves out the setcap command.

**Alternatives**
The alternative is to build the image on my own.
This works but requires more effort.
It seems trivial to add one more docker build to the pipeline and publish that alternative to Dockerhub.

**Additional Context**
The process to build the new image is trivial, but I think that it would be a big help to the community if an image were made 'officially' available.

**Comment by pravesh-sharma** [comment]
Since it is already discussed [here](https://www.postgresql.org/message-id/CA%2BOCxoxR2xrGx8%3DXXcwW6rOVQbrbBMpy9EapUw%3DSaA7qKfGR-w%40mail.gmail.com) that we will not create another image, we are closing this issue.
