### ISSUE TITLE
Webserver REMOTE_USER authentication broken

### ISSUE THREAD

**Issue by skreienk** [pgadmin-org/pgadmin4#7728]
I’m trying to setup two versions of PGAdmin, 6.12 and latest, using dockerhub images running on RH9 with podman.  I’m fronting this with HTTPD as a reverse proxy and authentication layer.  Here's my command for running the dockerhub image:

```
 /usr/bin/podman run \
         -e PGADMIN_DEFAULT_EMAIL=$MYEMAIL \
         -e "PGADMIN_DEFAULT_PASSWORD=$PASSWORD" \
         -e "PGADMIN_CONFIG_AUTHENTICATION_SOURCES=['webserver']" \
         -e PGADMIN_CONFIG_WEBSERVER_AUTO_CREATE_USER=True \
         -e PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False \
         -e "PGADMIN_CONFIG_CONFIG_DATABASE_URI='postgresql://$PGUSER:$PGPASS@$PGHOST:5432/$PGDB" \
         -e 'PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10' \
         --privileged  \
         -p 127.0.0.1:8081:80 \
         -v /var/lib/pgadmin/pgadmin:/var/lib/pgadmin \
         docker.io/dpage/pgadmin4:$VERSION
```

And here's my webserver config:

 ```
<VirtualHost *:8081>
         SSLEngine on
         SSLCertificateFile /etc/ssl/wildcard.crt
         SSLCertificateKeyFile /etc/ssl/wildcard.key
         ProxyPass / http://127.0.0.1:8081/ retry=0
         ProxyPassReverse / http://127.0.0.1:8081/ retry=0
         <LocationMatch "^(?!/dologin.html|/4C-Vertical.jpg)" >
                 AuthType form
                 AuthName "Login Required"
                 AuthFormLoginRequiredLocation "https://%{SERVER_NAME}/dologin.html"
                 AuthFormLoginSuccessLocation "https://%{SERVER_NAME}:8081/"
                 AuthFormProvider ldap-vip ldap-na
                 Require valid-user
                 AuthFormLogoutLocation "https://%{SERVER_NAME}/login.html"
                 #Redirect to login.html for anything unauthorized
                 ErrorDocument 401 "/dologin.html"
                 Session On
                 SessionCookieName session path=/
                 RewriteEngine on
                 RewriteCond %{REMOTE_USER} (.*)
                 RewriteRule .* - [E=X_REMOTE_USER:%1]
                 RequestHeader set REMOTE_USER %{X_REMOTE_USER}e
         </LocationMatch>
         <Location /dologin>
                 SetHandler form-login-handler
                 Header unset ETag
                 Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
                 Header set Pragma "no-cache"
                 Header set Expires "Wed, 11 Jan 1984 05:00:00 GMT"
         </Location>
 </VirtualHost>
```
 

The 6.12 version is working perfectly with these settings.  The webserver is authenticating me and when I connect to PGAdmin the user menu in the top right corner shows my user name.  If I use the latest version the webserver is authenticating me, but when I connect to PGAdmin I'm presented with the login screen and the message "Webserver authenticate failed".  I would expect the current version to show me as logged in just as the older version does.  Log messages confirm that both versions are running in server mode.

2024-07-22 13:26:39,833: DEBUG      pgadmin:        Config server mode: True
2024-07-22 13:26:39,836: DEBUG      pgadmin:        Not running under the desktop runtime, port: 5050
2024-07-22 13:26:48,493: DEBUG      pgadmin:        Authentication initiated via source: webserver
2024-07-22 13:26:48,495: DEBUG      pgadmin:        Authentication initiated via source: webserver is failed.

I posted on the user support list and searched both Google and the list archives but I was unable to find anything other than the original feature implementation.

**Comment by yogeshmahajan-1903** [comment]
@skreienk 
I am not able to reproduce the issue with latest image however I tried without SSL certs.

**Comment by yogeshmahajan-1903** [comment]
@skreienk 
Can you please try replacing '**REMOTE_USER**' in RequestHeader with REMOTE-USER or Remote-user? and try once?(without underscore)
pgadmin had updated Werkzeug library which might be causing the issue.

**Comment by skreienk** [comment]
That works!  With it setting REMOTE-USER instead of REMOTE_USER for the latest version it works as it should.

**Comment by pravesh-sharma** [comment]
Need to update documentation.
