### ISSUE TITLE
Create script invalid when role contain some character like "-"

### ISSUE THREAD

**Issue by tomamplius** [pgadmin-org/pgadmin4#7737]
**Describe the bug**

![image](https://github.com/user-attachments/assets/06496cee-e558-4b5e-b105-1b1a1752cdc0)
WORK
``` 
GRANT SELECT ON TABLE public.archive_payables TO "interface-ro";
```
NOT WORK
```
REVOKE ALL ON TABLE public.archive_payables FROM interface-ro;
```

On the revoke part role name need " like in the grant part
 
**To Reproduce**

1 Create role with "-" in the name 
2 Create table with grant to this user
3 ask the create script

**Expected behavior**

add "" arround the role name on revoke part like in GRANT part
```
REVOKE ALL ON TABLE public.archive_payables FROM interface-ro;
```
become 
```
REVOKE ALL ON TABLE public.archive_payables FROM "interface-ro";
```
**Error message**
```
ERROR:  syntax error at or near "-"
LINE 1: ...VOKE ALL ON TABLE public.archive_payables FROM interface-ro;
                                                                   ^ 

État SQL : 42601
Caractère : 59
```

 - Version: 8.9
 - Mode: Server
 - Browser : firefox
 - Package type: DEB

**Comment by RohitBhati8269** [comment]
Fixed and Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-08-08/).

Env:
OS - macOS arm
Mode - Desktop
