### ISSUE TITLE
setup-web.sh --yes asks for input

### ISSUE THREAD

**Issue by antedebaas** [pgadmin-org/pgadmin4#7745]
When i run `/usr/pgadmin4/bin/setup-web.sh --yes` i expect the setup to run in non-interactive mode (as the code suggests)
however this results in a prompt that asks for an initial user and password.
this is caused by `/usr/pgadmin4/web/setup.py` which does not seem to honor the non-interactive mode

**To Reproduce**

- install pgadmin4 on a clean machine
- run /usr/pgadmin4/bin/setup-web.sh --yes

**Expected behavior**
a non-interactive setup is performed (without user i guess)

**Screenshots**
![image](https://github.com/user-attachments/assets/d76720a7-acb5-42d4-9419-c8d905a76445)

**Comment by yogeshmahajan-1903** [comment]
@antedebaas 
Have you set env variable PGADMIN_SETUP_EMAIL and PGADMIN_SETUP_PASSWORD? If yes, can you please try running script with command below - 
```
sudo -E /usr/pgadmin4/bin/setup-web.sh --yes

```

**Comment by antedebaas** [comment]
running `PGADMIN_SETUP_EMAIL="email" PGADMIN_SETUP_PASSWORD="password" /usr/pgadmin4/bin/setup-web.sh --yes`
works.

**Comment by antedebaas** [comment]
I’ll leave it up you you if you want to make changes to the process to make it more robust or close the ticket

**Comment by anilsahoo20** [comment]
This is as per design, hence closing the issue.
