### ISSUE TITLE
pgAdmin v8.9 some parts of syntax highlighting stopped working

### ISSUE THREAD

**Issue by Pizanias-S** [pgadmin-org/pgadmin4#7748]
There is no syntax highlighting in the table names and columns 

1. Any query

In the previous version (pgAdmin v7.8) there was syntax highlighting in the table names and columns 

![Screenshot 2024-07-29 113419](https://github.com/user-attachments/assets/25ea866c-a247-4bae-b78b-88a057834d40)

**Desktop (please complete the following information):**

 - OS: Windows 11, Home
 - Version: 23H2
 - Mode: Desktop

**Comment by pravesh-sharma** [comment]
Issue fixed. Tested on candidate [build](https://developer.pgadmin.org/builds/2024-08-20-2/).

Env:
OS - Rocky Linux 9
Mode - Desktop
