### ISSUE TITLE
Wheel package of pgAdmin 4 not getting installed in arm64 based macOs version below 14

### ISSUE THREAD

**Issue by anilsahoo20** [pgadmin-org/pgadmin4#7754]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

While installing python package of pgAdmin 4 on arm64 based macOs version below 14, getting this error `ERROR: Could not find a version that satisfies the requirement psycopg-binary==3.2.1; implementation_name != "pypy" and extra == "binary" (from psycopg[binary]) (from versions: 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19)
ERROR: No matching distribution found for psycopg-binary==3.2.1; implementation_name != "pypy" and extra == "binary`

<img width="743" alt="Screenshot 2024-07-30 at 9 36 21 AM" src="https://github.com/user-attachments/assets/42437733-4b74-49ae-9521-61cd3b9c7baf">

This code takes the psycopg-binary=3.2.1 in the requirements.txt as this gets executed in the build machine(it may have macOs v14 or above) and in the installed machine that i have of macOs v13.5.1 it tries to install v3.2.1. 

Version: 8.10,
Package: Python
Environment: macOS Ventura 13.5.1

**Comment by RohitBhati8269** [comment]
Fixed and Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-08-08/).
OS - macOS (arm)
