### ISSUE TITLE
Search Object Dialog - Column Resizing not Working

### ISSUE THREAD

**Issue by 3ddark** [pgadmin-org/pgadmin4#7772]
Column resizing not working.  Below is the screenshot.

**Screenshots**
![bug](https://github.com/user-attachments/assets/15e53182-77a3-4e27-a7b0-17d9dcc27d28)

**Comment by adityatoshniwal** [comment]
Looks to be fixed in #7705.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-08-07/).

Env:
OS - macOS 14.5 (Sonoma)
Mode - Desktop
