### ISSUE TITLE
Editor find box doesn't get new search if already opened

### ISSUE THREAD

**Issue by avispt** [pgadmin-org/pgadmin4#7775]
When editor find box is already open, doing a new search on selected text does not replace searched text.

The text in the find box should be replaced with the new selected one if I choose "Find" by the menu or use cmd-f.

1. Do a search at the editor, doesn't matter if you choose a text or not. Use the "Find" menu or cmd-f for that.
2. Choose some other text and do the find again (By "Find" menu or cmd-f).
3. The problem - the new selected text is not on the find box and the app doesn't search for that.

I expect the new selected text to be searched.

 - OS: OSX Sonoma 14.5 (23F79) macOS-14.5-arm64-arm-64bit
 - Version: 8.10
 - Mode: Desktop
 - Package type: brew
 
 ![Screenshot 2024-08-01 at 13 38 50](https://github.com/user-attachments/assets/78289963-7443-4799-88ef-6ec21781411b)

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-08-07/
Package: arm64
Environment: macOs Ventura 13.5.1
