### ISSUE TITLE
Simplify the BaseSchemUI state management

### ISSUE THREAD

**Issue by asheshv** [pgadmin-org/pgadmin4#7776]
Use a separate custom hook for the Schema state management for:
* Simplify the SchemaView code
* Split the state management code in mode manageable & testable
* Make the state management reusable.
* Simplify the dependency management

**Comment by anilsahoo20** [comment]
In the latest snapshot, import export server dialog showing the loading icon and no error is in logs.
But locally getting this error.
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at SchemaDialogView (webpack:///./pgadmin/static/js/SchemaView/SchemaDialogView.jsx?:48:7)
    at ErrorBoundary (webpack:///./pgadmin/static/js/helpers/ErrorBoundary.jsx?:23:5)
    at SchemaView (webpack:///./pgadmin/static/js/SchemaView/SchemaView.jsx?:24:7)
```

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-08-13/
Package: arm64
Environment: macOs Ventura 13.5.1

**Comment by anilsahoo20** [comment]
Hi @asheshv 
Facing some issues with the below dialogs

1. Filtered rows: When we open the dialog for any table and write the condition and click `Ok`, it does not open View/Edit Data tool.
2. New Connection Dialog: In query tool, if we open new connection dialog, and it should by default load the server, database, role, also when selecting the server from the dropdown not able to show the selected server.
3. Macro dialog: In query tool, If we open Manage macros and add a new macro or update any existing macro, the `Save` button is not enabled.
4. User management dialog: In server mode, on adding a new user or updating a user does not enable the `Save` button.

**Comment by anilsahoo20** [comment]
Hi @asheshv 
Here are some more issues I found.

1. create subscription dialog: after entering password, click on save, password is not going empty in API call.
2. create publication dialog: after entering tables, the dialog says Something went wrong .
3. table dialog: constraints sections not working properly.

**Comment by anilsahoo20** [comment]
Tested and verified on candidate build: https://developer.pgadmin.org/builds/2024-08-19-1/
Package: arm64, pip wheel
Environment: macOs Ventura 13.5.1
