### ISSUE TITLE
Can't Install pgadmin4 in ubuntu 24.04 or linux mint 22

### ISSUE THREAD

**Issue by Krupal08** [pgadmin-org/pgadmin4#7778]
# i followed the method from here https://www.pgadmin.org/download/pgadmin-4-apt/

# so here i get this error
sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'

Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease   
Hit:2 https://packages.microsoft.com/repos/code stable InRelease   
Hit:3 http://archive.ubuntu.com/ubuntu noble InRelease             
Ign:4 http://packages.linuxmint.com wilma InRelease                
Hit:5 http://archive.ubuntu.com/ubuntu noble-updates InRelease     
Hit:6 http://packages.linuxmint.com wilma Release                  
Ign:7 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/wilma pgadmin4 InRelease
Hit:8 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Err:10 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/wilma pgadmin4 Release
  404  Not Found [IP: 64:ff9b::4820:9df6 443]
Reading package lists... Done
E: The repository 'https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/wilma pgadmin4 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by dpage** [comment]
Your OS seems to be identifying itself as "wilma", which given the other URLs in the output you posted, I would assume is a version of Linux Mint, which is not directly supported.

You could try editing `/etc/apt/sources.list.d/pgadmin4.list` and setting the codename to "noble" which I assume is the Ubuntu release on which Wilma is based. We do support that, so there's a good change that would work.
