### ISSUE TITLE
Italian translation messages.po

### ISSUE THREAD

**Issue by falcesimo** [pgadmin-org/pgadmin4#7780]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

File messages.po for italian language have large numbers of errors of translation.

Can we help improve the Italian translation by correcting and rectifying the text strings?

**Comment by akshay-joshi** [comment]
Hi @falcesimo 

You can raise a pull request for the appropriate translation files and contribute before each release of pgAdmin 4. We have monthly releases; before that, we send an email to the pgadmin-hackers list before each release to update the translations.
