### ISSUE TITLE
GUI Invisible on Startup Due to Out-of-Range Bounds in config.json

### ISSUE THREAD

**Issue by rodgermoore** [pgadmin-org/pgadmin4#7781]
**Describe the bug**

When starting pgAdmin 4 on Windows 11, the application starts but the GUI is invisible. This occurs when the previous application state was saved with a different display setup. The bounds in %APPDATA%/pgadmin4/config.json were out of range for the current display configuration.

**To Reproduce**

1. Set bounds in config.json to an out-of-range situation for your current display setup.
2. Start pgAdmin 4.
3. Observe that no user interface appears when starting pgAdmin 4.

**Expected behavior**

pgAdmin 4 should check if the set bounds exist with the current display setup. If they do, use them; otherwise, reset the bounds to [0,0] to ensure the GUI is visible.

**Error message**

There is no error message displayed.

**Screenshots**

No screenshots are available.

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Mode: Desktop
 - Package type: Windows executable

**Additional context**

- OS Version: 23H2
- OS Build: 22631.3880
- Windows Feature Experience Pack: 1000.22700.1020.0
- Installation Date: July 26, 2023

The problem can be solved by resetting bounds to x=0, y=0. pgAdmin should implement a check to verify if the set bounds exist within the current display setup. If true, use the existing bounds; otherwise, reset the bounds to [0,0].

Relevant config details:
APP_NAME = "pgAdmin 4"
APP_RELEASE = 8
APP_REVISION = 10
APP_VERSION = "8.10"
COMMIT_HASH = "ab25238f17bd52aa361db487a94435e97beb62c6 2024-07-29"
DATA_DIR = "C:\Users\REDACTED\AppData\Roaming\pgadmin"
IS_WIN = True
SERVER_MODE = False

Note: All paths containing personal information have been redacted.

**Comment by adityatoshniwal** [comment]
Hi @rodgermoore,

Did you check the latest version? Electron seems to have fixed the issue. I'm not able to reproduce with v8.11 on Mac/Win 11.

**Comment by pravesh-sharma** [comment]
No response from the author. We are closing the issue.

**Comment by rodgermoore** [comment]
> Hi @rodgermoore,
> 
> Did you check the latest version? Electron seems to have fixed the issue. I'm not able to reproduce with v8.11 on Mac/Win 11.

Sorry for the late reply. The issue seemed to be fixed, thanks a lot!

**Comment by IhorMarkivBetssongroup** [comment]
I have version 4.8.12 and still have the same problem. I had multiple displays, and the next day when I started work from home without the additional displays, I encountered the same issue. When I collapse/expand a window from the taskbar, I clearly see a slip animation towards where the additional display used to be.

**Comment by yogeshmahajan-1903** [comment]
@IhorMarkivBetssongroup 
Can you please share you OS details and logs from View > Toggle Developer tool > Console tab output

<img width="1108" alt="Screenshot 2024-10-23 at 10 58 15 AM" src="https://github.com/user-attachments/assets/b00a8ae6-797e-46c8-bd2b-bd6957bdbff0">

**Comment by Hummel-Hub** [comment]
I ran into the same problem using pgadmin4 first on my home, then on my work setup. My logs in the console are empty (i.e. look like yours @yogeshmahajan-1903 ). My OS details are:
Edition: Windows 10 Pro
OS Version: 22H2
OS Build: 19045.5011
Windows Feature Experience Pack: 1000.19060.1000.0
Installation Date: ‎09.‎03.‎2021
Resetting the bounds in %APPDATA%/pgadmin4/config.json to (0,0) as described by @rodgermoore fixed it for me, I guess the corresponding diagnose is correct.

**Comment by fkellner** [comment]
Can confirm, problem persists with 
```
Version
8.14
Application Mode
Desktop
Commit:
9e58717321a434519875773707df78c020bcde40 2024-12-09
Current User
pgadmin4@pgadmin.org
Electron Version
33.2.1
Browser
Chrome 130.0.6723.137
Operating System
Windows-11-10.0.22621-SP0
```
Resetting the bounds fixed it, but I also noticed that the `width` and `height` were bigger than the resolution of the built-in monitor, so I reduced them, too - maybe that was part of the problem?

**Comment by desincarnage** [comment]
I just experienced this issue with version 8.14 on Windows 11 Pro. Setting `x` and `y` to 0 in `%APPDATA%/pgadmin4/config.json` fixed it.

```Version
8.14
Application Mode
Desktop
Commit:
9e58717321a434519875773707df78c020bcde40 2024-12-09
Current User
pgadmin4@pgadmin.org
Electron Version
33.2.1
Browser
Chrome 130.0.6723.137
Operating System
Windows-11-10.0.26200-SP0
