### ISSUE TITLE
Support PSS Restricted

### ISSUE THREAD

**Issue by freudl** [pgadmin-org/pgadmin4#7792]
**Describe the solution you'd like**

I'd like to run pgAdmin's docker image in a k8s cluster with [Pod Secrutiy Standard _Restricted_](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) enabled.

While this is fair for small clusters it introduces obstacles for regulated / multi tenant environments.

**Describe alternatives you've considered**

The image [sets a capability](https://github.com/pgadmin-org/pgadmin4/blob/master/Dockerfile#L214) which is, afaik. not required.

The workaround is to rebuild the image dropping the capability (or a PSS profile with less restrictions).

**Additional context**

I'm not sure which other usecases judge the existence of the capability.

**Comment by akshay-joshi** [comment]
Can you please read this [email thread](https://www.postgresql.org/message-id/CA%2BOCxoxR2xrGx8%3DXXcwW6rOVQbrbBMpy9EapUw%3DSaA7qKfGR-w%40mail.gmail.com).

We are not going to do this shortly.
