### ISSUE TITLE
Refactoring broke flatpak paths

### ISSUE THREAD

**Issue by razzeee** [pgadmin-org/pgadmin4#7793]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

The flatpak paths used in misc.js get prefixed with the base path https://github.com/pgadmin-org/pgadmin4/commit/91eb60a363c71608569bc646773a26105c3c11bf#diff-e9a2f2b06526683ff74be06bd684cb8e68985cb279698e2881506bae6337bdadR60

But they are intended as absolute paths.

This leads to an exception on start of the flatpak and it crashing https://github.com/razzeee/org.pgadmin.pgadmin4/pull/4#issuecomment-2273673481

**To Reproduce**

1. Start flatpak 
2. Crash

**Expected behavior**

It should get the correct paths and  start fine.

**Error message**

```
Total spawn time to start the pgAdmin4 server: 0.013 Sec
Failed to launch pgAdmin4. Error:
Error: spawn /app/pgadmin4/bin/resources/app/src/js/usr/bin/python ENOENT
```

**Desktop (please complete the following information):**
 - OS:  Linux
 - Package type: Flatpak

**Comment by adityatoshniwal** [comment]
Hi @razzeee,

what is the python path for flatpak?

**Comment by adityatoshniwal** [comment]
Hi @razzeee,
I've fixed the code. Can you please verify?

**Comment by razzeee** [comment]
Should work like that, thank you.
