### ISSUE TITLE
The newest release of PgAdmin v8.10 is not compatible with Windows 11

### ISSUE THREAD

**Issue by dijanapavleska** [pgadmin-org/pgadmin4#7797]
![Capture](https://github.com/user-attachments/assets/f394a926-1239-4e82-b226-27825ff0b251)

![Capture2](https://github.com/user-attachments/assets/1f564733-9a48-4fc6-aaa1-05b74e2ee155)

**Comment by akshay-joshi** [comment]
@dijanapavleska 

We are unable to reproduce this. From where you have downloaded the pgAdmin installers?

**Comment by RohitBhati8269** [comment]
No response from the author, hence closing.
