### ISSUE TITLE
Add Create script in trigger function in context menu

### ISSUE THREAD

**Issue by zpaks** [pgadmin-org/pgadmin4#7802]
**Describe the solution you'd like**

I would like to right click on trigger function and to have possibility to "CREATE Script" like it is possible for functions.
Now "No menu available for this object" is displayed.

![image](https://github.com/user-attachments/assets/3d14e13b-5965-4921-a444-fc70a8217769)

The only possibility is to create trigger definition, but not trigger function.

**Additional context**

version: 4.8.10

**Comment by akshay-joshi** [comment]
Hi @zpaks 

This is by design, as we already have a "Trigger Functions" collection node. You can select the same function and "CREATE Script" from there.
