### ISSUE TITLE
Servers are re-imported at every container startup

### ISSUE THREAD

**Issue by vlaborie** [pgadmin-org/pgadmin4#7811]
**Describe the bug**

Hello,

I use pgadmin from Docker image `dpage/pgadmin4:8.10` in server mode and mount the following file to `/pgadmin4/servers.json` :

~~~
    {
        "Servers": {
            "1": {
                "Name": "Local",
                "Group": "Servers",
                "Shared": true,
                "SharedUsername": "admin",
                "Username": "admin",
                "Comment": "Local Postgresql server",
                "Host": "postgresql-rw.postgresql.svc.cluster.local",
                "Port": 5432,
                "MaintenanceDB": "postgres",
                "ConnectionParameters": {
                    "sslmode": "verify-full",
                    "sslcert": "tls:/tls.crt",
                    "sslkey": "tls:/tls.key",
                    "sslrootcert": "tls:/ca.crt"
                }
            }
        }
    }
~~~

The server is imported at container startup but it is imported at **every** startup :

~~~
Added 0 Server Group(s) and 1 Server(s).
~~~

You can see in the following screenshot which i have 8 times this same server (because of 8 containers restart).

**Expected behavior**

I expect the server config to be updated on new import or at least to not be imported multiple time.

**Screenshots**

![pgadmin-multi-servers-import](https://github.com/user-attachments/assets/3beaf7fa-f438-495e-b0c3-d9bcd1569024)

**Additional context**

I use **oauth2** for authentification (AUTHENTICATION_SOURCES) and **postgresql** for config database (CONFIG_DATABASE_URI).

**Comment by yogeshmahajan-1903** [comment]
Working fine.
