### ISSUE TITLE
MAIL_SERVER variable not being formatted as a string

### ISSUE THREAD

**Issue by IS-Vivek** [pgadmin-org/pgadmin4#7816]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

I have my PgAdmin application running in an ecs container using a task definition which pulls the docker image.

I have tried to deploy a new task definition with the variable "PGADMIN_CONFIG_MAIL_SERVER". the documentation says that this should be automated formatted as a string.

Instead it gives an error and does not boot up.

**To Reproduce**

1. Deploy PGAdmin in a docker container through an ecs task definition with the variable PGADMIN_CONFIG_MAIL_SERVER.
2. Start a new deployment using this task definition.

**Expected behavior**

The application runs and uses the MAIL_SERVER provided in the variable.

**Error message**

If possible, include the full, unedited text of any error messages displayed.
See screenshot below.

**Screenshots**

![image](https://github.com/user-attachments/assets/aa920b84-ae05-44f0-ae23-b1cd88743fc8)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey] Amazon Linux
 - Version: [e.g. 6.15] 8.4
 - Mode: [e.g Desktop or Server] Server
 - Browser (if running in server mode): [e.g. chrome, safari] N/A - issue on startup
 - Package type: [e.g. RPM, DEB, Python, Container, etc.] Docker Container

**Additional context**

Trying to add 2FA and using amazon ses as our mail server.

**Comment by akshay-joshi** [comment]
The value for PGADMIN_CONFIG_MAIL_SERVER should be in quotes as per the .yml syntax
