### ISSUE TITLE
pgAdmin can't cancel query when role field is filled in connection settings

### ISSUE THREAD

**Issue by Splarv** [pgadmin-org/pgadmin4#7821]
I reopen the bugreport #7442 because it was closed for bad reason. The long description can be red there. 
I have the same on PgAdmin 4  v. 8.10. Look what did happen, I use role A to login and B to set role after login. To cancel query you must send pg_cancel_query from the other connection by the same user, but the user must be not B for this purpose, but A. The error raised because you use user B for this purpose. This is a bug. The workaround to add all developers to role pg_signal_backend is bad, because they will be able to cancel query or terminate backend of any user, not only own.
Btw, Dbeaver worked fine. Can be used as workaround.

**Comment by adityatoshniwal** [comment]
@Splarv Can you please share PostgreSQL docs link to `pg_cancel_query`? I failed to find it - https://www.postgresql.org/search/?q=pg_cancel_query

**Comment by Splarv** [comment]
> @Splarv Can you please share PostgreSQL docs link to `pg_cancel_query`? I failed to find it - https://www.postgresql.org/search/?q=pg_cancel_query
Yep, my mistype.
https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-SIGNAL

pg_cancel_backend ( pid integer ) → boolean
Cancels the current query of the session

Btw, you can cancel query from the same connection, just like psql do it.
https://www.postgresql.org/docs/current/libpq-cancel.html
PQcancel 
Requests that the server abandon processing of the current command.

**Comment by adityatoshniwal** [comment]
> > @Splarv Can you please share PostgreSQL docs link to `pg_cancel_query`? I failed to find it - https://www.postgresql.org/search/?q=pg_cancel_query
> 
> Yep, my mistype. https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-SIGNAL
> 
> pg_cancel_backend ( pid integer ) → boolean Cancels the current query of the session
> 
> Btw, you can cancel query from the same connection, just like psql do it. https://www.postgresql.org/docs/current/libpq-cancel.html PQcancel Requests that the server abandon processing of the current command.

Hi @Splarv,

pgAdmin is already using pg_cancel_backend - https://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/dashboard/__init__.py#L657

**Comment by Splarv** [comment]
Sure, thats why the bug is. Look what did happen, I use role A to login and B to set role after login. To cancel query you send pg_cancel_backend from the other connection by the same user, but the effective user to execute pg_cancel_backend must be not B for this purpose, but A. The error raised because you use user B for this purpose and query doesn't canceled. This is a bug.

**Comment by adityatoshniwal** [comment]
Hi @Splarv,
The connection made using the details from server dialog is used everywhere. pgAdmin cannot create a connection separately without the role specified and execute `pg_cancel_backend`.
This is not a bug. 
This behaviour is same as psql.

Thanks.
