### ISSUE TITLE
"set role" must be different for each database

### ISSUE THREAD

**Issue by Splarv** [pgadmin-org/pgadmin4#7822]
Pgadmin has a username to login and username to issue "set role" after login. The reason for second can be different. Someone can use "set role postgres" to do administrative tasks or, for instance database owner is dbo, issue "set role dbo" to work and create objects in such database. So role for "set role" must be different for different databases: for the database postgres it can be "postgres", while for each database in development its own dbo. This is perfectly done in Dbeaver. While in pgadmin option to "set role" defined in server block of options, but not a database block of options, and must be the same for all databases in the server. So it force a developer to create separate "server" object for each database.

**Comment by akshay-joshi** [comment]
@Splarv

Can you please share a screen recording of how it's done in DBeaver?

**Comment by Splarv** [comment]
![image](https://github.com/user-attachments/assets/fb9fce09-2b80-4a62-9c7e-2f9726f46fa7)

**Comment by Splarv** [comment]
This is not true. DBeaver can set different roles for difference databases inside the same server. For instance I can set role postgres when connect to db postgres and set role to the database owner (dbo) when connect to development database. While PdAdmin has 'set role' for server object, not for the database. So in PgAdmin must be the same role for all databases in server.

**Comment by adityatoshniwal** [comment]
> This is not true. DBeaver can set different roles for difference databases inside the same server. For instance I can set role postgres when connect to db postgres and set role to the database owner (dbo) when connect to development database. While PdAdmin has 'set role' for server object, not for the database. So in PgAdmin must be the same role for all databases in server.

But as per your screenshot it is setting at the server object and not for each database separately. Share the screenshot where you have set the role for each database for the same server.

**Comment by dpage** [comment]
Perhaps in DBeaver you create a separate connection for each database, whereas in pgAdmin we use a single maintenance database and browse/connect elsewhere from that?

**Comment by Splarv** [comment]
Nope, you create separate connection for each database, just like DBeaver.
postgres=# select datname,application_name from pg_stat_activity where client_hostname='od.samoylov';
```

   datname   |      application_name
-------------+----------------------------
 postspark   | pgAdmin 4 - DB:postspark
 postgres    | pgAdmin 4 - DB:postgres
 spark       | pgAdmin 4 - DB:spark
 od.samoylov | pgAdmin 4 - DB:od.samoylov
(4 rows)

```

**Comment by adityatoshniwal** [comment]
> Nope, you create separate connection for each database, just like DBeaver. postgres=# select datname,application_name from pg_stat_activity where client_hostname='od.samoylov';

What Dave meant was creating separate connections from the UI.

**Comment by RohitBhati8269** [comment]
The behavior in DBeaver is the same in pgAdmin4. We are closing the issue.
