### ISSUE TITLE
Unable to Install pgAdmin on Debian 12

### ISSUE THREAD

**Issue by paulbam237** [pgadmin-org/pgadmin4#7823]
I have made repeated attempts over the past week to install pgAdmin on a computer running Debian 12.

Each time the installation has failed. the attached screenshots show the results of my last two attempts.
<img width="629" alt="Screen Shot 2024-08-16 at 2 44 00 pm" src="https://github.com/user-attachments/assets/7a3f2374-43dc-42b7-8179-1c97dd52564b">
<img width="648" alt="Screen Shot 2024-08-16 at 2 44 41 pm" src="https://github.com/user-attachments/assets/ba6de3c7-527e-46d6-9050-135252ac80bb">

**Comment by pravesh-sharma** [comment]
Hi @paulbam237,

Have you followed the steps mentioned [here](https://www.pgadmin.org/download/pgadmin-4-apt/)?

**Comment by paulbam237** [comment]
Yes.

Every time.

**Comment by pravesh-sharma** [comment]
@paulbam237,

Can you please share your system details? Are you using an ARM-based machine?

**Comment by paulbam237** [comment]
I'm using a Raspberry Pi 5, with the M2+ hat, Corsair MP600 memory
(although right now until I get my desired set-up sorted everything is
sitting on an SD card).

According to this page, it is ARM based:
https://www.raspberrypi.com/news/introducing-raspberry-pi-5/

Are there further details that you need?

Paul

**Comment by pravesh-sharma** [comment]
Hi @paulbam237,

Unfortunately, pgAdmin 4 installers are not supported on Linux ARM machines. Alternatively, you can use docker [container](https://www.pgadmin.org/download/pgadmin-4-container/) or [pip](https://www.pgadmin.org/download/pgadmin-4-python/) for installation.
