### ISSUE TITLE
SSPI continuation error: The specified target is unknown or unreachable (80090303)

### ISSUE THREAD

**Issue by dmckay-thig** [pgadmin-org/pgadmin4#7828]
I have a postgres cluster running in AWS Aurora. We are trying to connect using Kerberos with pgadmin from a Windows client. When trying to connect we get "SSPI continuation error: The specified target is unknown or unreachable (80090303)". We have the host name right and logs reflect the failed login on the cluster. We are using AWS managed AD with a one way trust for authentication. This setup works with dbeaver using a krb5.ini file with all the realms in the file. Just not able to get pgadmin to work.

**Comment by RohitBhati8269** [comment]
What steps did you follow to set up Kerberos with the pgAdmin4 desktop application on Windows?
Your setup works with DBeaver, So are you creating a  Kerberos ticket manually or is it using Windows default behavior for the Kerberos ticket?

**Comment by dmckay-thig** [comment]
For DBeaver we needed to create a KRB5.ini file that has all the realms in it. We have not come across anything showing that we need to create anything like that for pgAdmin.

**Comment by yogeshmahajan-1903** [comment]
@dmckay-thig 
Can you please provide screenshot for your server properties > connection tab and output of command below  using ktutil
```
ktutil:  rkt <keytab location>/<key tab name for postgres>.keytab 
ktutil:  list
```

**Comment by yogeshmahajan-1903** [comment]
No response from author , hence closing the issue. We are not able to reproduce the issue at our end. Host name , user name should match to details shown using  rkt command above.

**Comment by tbwcap** [comment]
> For DBeaver we needed to create a KRB5.ini file that has all the realms in it. We have not come across anything showing that we need to create anything like that for pgAdmin.

hi there, can you share how you di your kerberos settings for dbeaver? I am trying to setup kerberos for dbeaver.  thanks
