### ISSUE TITLE
Target Session Attribute Primary or Target Session Attribute Read-Write Fail to Connect

### ISSUE THREAD

**Issue by prime-minister-of-fun** [pgadmin-org/pgadmin4#7832]
**Describe the bug**
Pgadmin4 is running in desktop mode, version 8.9.

Using a comma separated string of hosts and adding the "Target Session Attribute" parameter to either read-write or primary returns an error message.  Pgadmin4 is unable to connect to the primary.  
Error message: ```2024-08-20 11:56:34,972: ERROR	pgadmin:	Could not connect to server(#3) - 'my-staging-dev'.
Error: connection failed: connection to server at "10.3.10.71", port 5432 failed: server is in hot standby mode``` 

**To Reproduce**

1. Create a new connection.
2. Add a comma separated list of host names in the Host name/address field
3. Add "Target Session Attribute" to Connection Parameters.  
4. Use the drop-down menu to set the Value to either read-write or primary
5. Save connection.
6. Attempt to connect to the cluster.

**Expected behavior**

I expect to be connected to the primary node.

**Error message**

2024-08-20 11:56:34,972: ERROR	pgadmin:	Could not connect to server(#3) - 'my-staging-dev'.
Error: connection failed: connection to server at "10.3.10.71", port 5432 failed: server is in hot standby mode

**Desktop (please complete the following information):**
 - OS: Windows Server 2022 Standard
 - Version: 21H2
 - Mode: Desktop 
 - Browser N/A
 - Package type: Windows installer

**Additional context**
In case it matters, this is a multi-user remote desktop session.  The error appears if one or more users is on the VM, and using pgadmin.
It's an ordeal to get a new version approved for installation.  So, if there's a workaround, that would be great.

**Comment by adityatoshniwal** [comment]
@prime-minister-of-fun Are you able to connect using psql? The error is coming from PostgreSQL and may not be a pgAdmin issue.
Secondly, pgAdmin doesn't intercept PostgreSQL errors. Errors can be in any language or may change with time.

**Comment by yogeshmahajan-1903** [comment]
No response from author , hence closing the issue.
