### ISSUE TITLE
Selecting blocks of code doesnt work

### ISSUE THREAD

**Issue by nprgin** [pgadmin-org/pgadmin4#7838]
![image](https://github.com/user-attachments/assets/928454d4-48f1-479a-bdc4-e26f60363590)

Take a look at this query, if i execute the whole query it works fine, but the problem arises once i highlight cte_1 and last select, then I get the error "ERROR:  syntax error at end of input LINE 4: )", beacuse it treats it as 2 seperate selects instead of 1.

This bug has been here for the last 5-6 versions, fix it its a game breaking bug!!!!!!!!!
(Using Linux)

**Comment by adityatoshniwal** [comment]
Hi @nprgin,

What is your pgAdmin version?

**Comment by nprgin** [comment]
hi @adityatoshniwal,
Currently the version is 8.11

**Comment by adityatoshniwal** [comment]
Duplicates #7293.
