### ISSUE TITLE
regression loading password from pg_service.conf since v8.10

### ISSUE THREAD

**Issue by Marley0000** [pgadmin-org/pgadmin4#7840]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

We use the .pg_service.conf file to manage our multiple databases access.
Since v8.10, pgadmin don't load correctly the password in .pg_service.conf file.
Pgadmin ask password  even though it is correctly entered in the file. No error, but password is not loading from file
In v8.9 no problem. This is a regression since v8.10

**To Reproduce**

Create a .pg_service.conf with DB configuration in C:\Users\toto\AppData\Roaming\postgresql

[db01]
host=host1,host2
password=xxxxxx
port=port1,port2
target_session_attrs=read-write
user=user_db

In pgAdmin config:
connexion tab -> service: db01

**Expected behavior**

password is loading from .pg_service.conf file correctly

**Screenshots**

![image](https://github.com/user-attachments/assets/da956f61-b2a1-47f6-9562-a60f818fc434)

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - Version: [8.10]
 - Mode: [Desktop]
 - Browser none
 - Package type: [.exe]

**Comment by stephdl** [comment]
I can confirm this regression with pgadmin 8.10. I use a linux socket to connect to postgres, hence I use no password. Before 8.10, nothing was asked, with 8.10 and 8.11 I get this warning to save an empty password at least one time if the checkbox is checked, else each authentication will ask me to validate this form. Once the form is accepted with an empty password, I can use the databases without issue

I use [dpage/pgadmin4](https://hub.docker.com/r/dpage/pgadmin4/tags)
version dpage/pgadmin4:8.10 and dpage/pgadmin4:8.11
Mode server
browser chrome
container: podman
postgresql 16

**Comment by yogeshmahajan-1903** [comment]
> I can confirm this regression with pgadmin 8.10. I use a linux socket to connect to postgres, hence I use no password. Before 8.10, nothing was asked, with 8.10 and 8.11 I get this warning to save an empty password at least one time if the checkbox is checked, else each authentication will ask me to validate this form. Once the form is accepted with an empty password, I can use the databases without issue
> 
> I use [dpage/pgadmin4](https://hub.docker.com/r/dpage/pgadmin4/tags) version dpage/pgadmin4:8.10 and dpage/pgadmin4:8.11 Mode server browser chrome container: podman postgresql 16
> 
> my server.json configuration is
> 
> ```json
> {
>   "Servers": {
>     "1": {
>       "Name": "postgresql16",
>       "Group": "Servers",
>       "Host": "/var/run/postgresql/",
>       "Port": 5432,
>       "MaintenanceDB": "postgres",
>       "Username": "postgres",
>       "TunnelPort": "22",
>       "KerberosAuthentication": false,
>       "ConnectionParameters": {
>         "passfile": ""
>       }
>     }
>   }
> }
> ```

@stephdl 

I am not able to reproduce the issue. Can you please provide your pgapss file content format?
I have just added host entry in pgpass file and created a server with host maintenance db, username and pgpass file.
Connection to the server was successful without entering  password as server did not require password

**Comment by stephdl** [comment]
@yogeshmahajan-1903  could you show me your pgpass please, maybe this is the error I have because the passfile does not exist

however with the version 8.9 I have no issue with this configuration, something has changed

I suppose this is the [format](https://docs.postgresql.fr/16/libpq-pgpass.html) I need to have

**Comment by yogeshmahajan-1903** [comment]
> @yogeshmahajan-1903 could you show me your pgpass please, maybe this is the error I have because the passfile does not exist
> 

I have already mentioned that I have only host entry in my pgpass as below - 
```
 % cat ~/.pgpass 
localhost

```

> however with the version 8.9 I have no issue with this configuration, something has changed
> 

> I suppose this is the [format](https://docs.postgresql.fr/16/libpq-pgpass.html) I need to have

That's correct.

Note - I could reproduce when I explicit set value for pgpassfile = ''

**Comment by yogeshmahajan-1903** [comment]
This is fixed with #7076. It will be available in version 8.12

**Comment by stephdl** [comment]
thank a lot, I will test it

**Comment by stephdl** [comment]
thank @yogeshmahajan-1903 I fixed my configuration, I confirm it work now

https://github.com/stephdl/ns8-postgresql16/pull/7/files

**Comment by yogeshmahajan-1903** [comment]
Working fine.
