### ISSUE TITLE
Installation script doesn't restart Apache2 after re-installation of pgAdmin in Ubuntu 24.10

### ISSUE THREAD

**Issue by mxchist** [pgadmin-org/pgadmin4#7848]
**Apache2 service does not restart after pgAdmin was reinstalled.**
The default pgAdmin4 web configuration is based on a standard Ubuntu Apache2 reverse proxy. After pgAdmin4 was reinstalled, a re-installation script ~just reloaded~ [even not reloaded](https://github.com/pgadmin-org/pgadmin4/issues/7848#issuecomment-2308914250) the apache2 service. This caused the apache2 service to log an old error for an unclear (for me) reason:
```
[Sun Aug 25 18:49:40.123342 2024] [wsgi:error] [pid 782005] [remote 127.0.0.1:58036] mod_wsgi (pid=782005): Failed to exec Python script file '/usr/pgadmin4/web/pgAdmin4.wsgi'.
[Sun Aug 25 18:49:40.123466 2024] [wsgi:error] [pid 782005] [remote 127.0.0.1:58036] mod_wsgi (pid=782005): Exception occurred processing WSGI script '/usr/pgadmin4/web/pgAdmin4.wsgi'.
[Sun Aug 25 18:49:40.124199 2024] [wsgi:error] [pid 782005] [remote 127.0.0.1:58036] Traceback (most recent call last):
[Sun Aug 25 18:49:40.124842 2024] [wsgi:error] [pid 782005] [remote 127.0.0.1:58036]   File "/usr/pgadmin4/web/pgAdmin4.wsgi", line 25, in <module>
[Sun Aug 25 18:49:40.124882 2024] [wsgi:error] [pid 782005] [remote 127.0.0.1:58036]     import config
[Sun Aug 25 18:49:40.124921 2024] [wsgi:error] [pid 782005] [remote 127.0.0.1:58036]   File "/usr/pgadmin4/web/config.py", line 33, in <module>
[Sun Aug 25 18:49:40.124937 2024] [wsgi:error] [pid 782005] [remote 127.0.0.1:58036]     from pgadmin.utils import env, IS_WIN, fs_short_path
[Sun Aug 25 18:49:40.124965 2024] [wsgi:error] [pid 782005] [remote 127.0.0.1:58036]   File "/usr/pgadmin4/web/pgadmin/__init__.py", line 24, in <module>
[Sun Aug 25 18:49:40.124981 2024] [wsgi:error] [pid 782005] [remote 127.0.0.1:58036]     from flask import Flask, abort, request, current_app, session, url_for
[Sun Aug 25 18:49:40.125033 2024] [wsgi:error] [pid 782005] [remote 127.0.0.1:58036] ModuleNotFoundError: No module named 'flask'
```

This error was present in the logs before, following the Linux upgrade to 24.04 and prior to the re-installation. However,  after the apache2 service was manually restarted, this error wasn't raised anymore

**To Reproduce**

1. Install pgadmin4-server, pgadmin4-web on Ubuntu 23.10 mantic
2. Upgrade Linux to 24.04
3. Update pgadmin to 8.9
4. Change `https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/mantic pgadmin4 main` to `https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/noble pgadmin4 main` in a `/etc/apt/sources.list.d/`
5. Make `sudo apt update`
6. Re-install pgadmin: ` sudo apt reinstall pgadmin4 pgadmin4-server pgadmin4-web`

pgAdmin packages before re-installation:
```
$ sudo dpkg -l *pgadmin*
ii  pgadmin4-server 8.9           amd64 
ii  pgadmin4-web    8.9           all
ii  phppgadmin      7.14.7+dfsg-1 all
```

pgAdmin packages after re-installation:
```
$ sudo dpkg -l *pgadmin*
ii  pgadmin4         8.11          all 
ii  pgadmin4-desktop 8.11          amd64
ii  pgadmin4-server  8.11          amd64 
ii  pgadmin4-web     8.11          all 
ii  phppgadmin       7.14.7+dfsg-1 all 
```

**Expected behavior**
The web address `http://127.0.0.1/pgadmin4` opens a pgAdmin web interface

**Error message**

In my browser:
```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache/2.4.58 (Ubuntu) Server at 127.0.0.1 Port 80
```

In Apache logs: see messages above since Sun Aug 25 18:49:40

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version: 23.04
 - Mode: Server 
 - Browser (if running in server mode): Chromium
 - Package type: `ftp.postgresql.org/pub/pgadmin/` repository

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
To apply updates either you need to restart apache server or you can run script shipped with installer with command below - 
```
sudo /usr/pgadmin4/bin/setup-web.sh
```
You need NOT to run pgAdmin4.py
