### ISSUE TITLE
Allow 'Locks' Grid to be configurable and/or hidden

### ISSUE THREAD

**Issue by mldisibio** [pgadmin-org/pgadmin4#7861]
**Describe the solution you'd like**

A table with several hundred partitions and a few indexes can take out several thousand locks. The "Locks" grid hangs the browser, often running out of memory, but making the "State" tab, especially "Sessions" very difficult to view. Would be nice to either:
- Put "Locks" into their own tab
- Have option to toggle display of "Locks" on "State" tab
- Have option to filter or limit number of locks displayed in grid

**Describe alternatives you've considered**

Preferences -> Dashboards -> Display -> Show State
But this toggles the "Sessions" as well as locks. Sessions used to be on Activity tab which was much more helpful. 

**Additional context**

With the latest UI changes, options to dock tabs are gone, and Sessions are forced to be viewed with Locks. Please either optimize grid display for several thousand locks or put Sessions tab back at bottom of Activity tab.

**Comment by khushboovashi** [comment]
Hi @mldisibio,

We have fixed this issue in the last release. Can you please check with the latest version?

**Comment by mldisibio** [comment]
> Hi @mldisibio,
> 
> We have fixed this issue in the last release. Can you please check with the latest version?

I can verify the `State` tab is very responsive even with several thousand rows in the `Locks` grid and memory usage for the browser tab is much much lower.
Thank you!

Should I close this issue or do you?

**Comment by khushboovashi** [comment]
duplicates #7809.
