### ISSUE TITLE
Bug: Unable to Import Data

### ISSUE THREAD

**Issue by vcao** [pgadmin-org/pgadmin4#7862]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
On MacOS user can't import any files, specifically text files into tables, when you use the import tool. Files are greyed out regardless of type selected.

**To Reproduce**

1. Right click a table
2. Select Import/Export Data
3. Select filename under file selector ...
4. Attempt to select files, but greyed out

**Expected behavior**

All files should be available to select.

**Error message**

No error messages available.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Version: 14.6.1
 - Mode: Desktop
 - Browser: n/a
 - Package type: Intel/Apple Silicon

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
@vcao 
Can you please share screenshot? I am not able to reproduce the issue.

**Comment by vcao** [comment]
Here are the screenshots. It will import with a full pathname, but it will not with file browser.
<img width="1350" alt="Screenshot 2024-08-27 at 11 45 59 PM" src="https://github.com/user-attachments/assets/d1f2ba84-2ce6-4e76-af61-93ddc4de31d5">
<img width="1350" alt="Screenshot 2024-08-27 at 11 45 31 PM" src="https://github.com/user-attachments/assets/279f50f5-801e-48a2-9136-8e4b9370e158">

**Comment by yogeshmahajan-1903** [comment]
@vcao 
Can you please click on 'Show options' and check what file format is selected. I suspect, it is other than All files or .txt.

**Comment by vcao** [comment]
Both options also result in greyed out files in the file browser

**Comment by yogeshmahajan-1903** [comment]
@vcao 
It should look as below -
<img width="694" alt="Screenshot 2024-08-29 at 9 50 07 AM" src="https://github.com/user-attachments/assets/bad58b21-6155-4e2f-94ce-131a338c892a">

You need to select either.txt or all file. If selection for it greyed out then its issue with native file explorer not the pgadmin. pgadmin use os level file explorer.

**Comment by adityatoshniwal** [comment]
@vcao Click on show options to show the file format drop-down. There you can select appropriate extension.

**Comment by vcao** [comment]
> @vcao It should look as below - <img alt="Screenshot 2024-08-29 at 9 50 07 AM" width="694" src="https://private-user-images.githubusercontent.com/16016019/362530833-bad58b21-6155-4e2f-94ce-131a338c892a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTc5MTgsIm5iZiI6MTcyNDkxNzYxOCwicGF0aCI6Ii8xNjAxNjAxOS8zNjI1MzA4MzMtYmFkNThiMjEtNjE1NS00ZTJmLTk0Y2UtMTMxYTMzOGM4OTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3NDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ODYyMGY5ZDQ0NTFjNWRhYTBjYzE5NWI4NjcyMGUxZjhlNjE5NjMzZThiYjEzYjU1Mjk1OGE2MDIwMWZjZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4NONMmNmeXX6jrUoO8IDVHkuNy5hRVwgoBqio2zGoog">
> 
> You need to select either.txt or all file. If selection for it greyed out then its issue with native file explorer not the pgadmin. pgadmin use os level file explorer.

Thank you! The Show Options section threw me off. I usually have it on permanently. I'll close off the thread.
