### ISSUE TITLE
The row number in result grid is deceptive and easy to lead mistake in data operation

### ISSUE THREAD

**Issue by xzer** [pgadmin-org/pgadmin4#7863]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

The row number in result grid is very annoying, when the table has a number id (usually the PK) as the first column, it is very confusing to user which number is the row number and which number is the id from the table. Especially when the user is scrolling to right side to view the long columns, the row number column is stick at left side, it is very much easy to mislead user to treat the row number as the id of the table data.

I report this as a bug rather than feature request, because this defect has significant impact on data operation correctness.

**To Reproduce**

1. Go to 'query panel'
2. input SQL as "select * from some_table"
3. See result grid

**Expected behavior**

The row number should be optional, there should be toggle to allow hide the row number column, and also there should be a global setting to allow hide the row number column.

**Error message**

N/A

**Screenshots**

<img width="1120" alt="image" src="https://github.com/user-attachments/assets/de28dd03-e0fe-44f0-80cb-b832052df7f4">

<img width="1111" alt="image" src="https://github.com/user-attachments/assets/dc4ce906-b0e4-4a17-b1d5-cd0c1835a45f">

**Desktop (please complete the following information):**
 - OS: OSX Sonoma
 - Version: 8.9
 - Mode: Desktop or Server

**Additional context**

**Comment by xzer** [comment]
I report this as a bug rather than feature request, because this defect has significant impact on data operation correctness.

**Comment by adityatoshniwal** [comment]
@xzer You can check any sql editor, all have row numbers because it is very useful in most cases. Your request is first of a kind, no one had a problem with this before. So we're taking it as feature request to allow disabling the rownumbers.

**Comment by xzer** [comment]
check the dbeaver

https://dbeaver.io/wp-content/uploads/2018/03/data_edit-450x220.png

Yes, it also has row number in the result grid, but it is in clear different cell style and background color, it is very clearly indicate the number is not a part of the data. But look above picture I pasted, they are almost same.

I would say, it may be not necessary to really "hide" it, but it need to be clearly differentiated from the data cells.

**Comment by xzer** [comment]
> Right now we add slight shadow to the right edge of row number.

If you go back to check my pasted screenshot, I don't think the "slight shadow" can be easily differentiate from other cell border lines.

I was not using postgre and pgAdmin for several years, and I didn't remember I have any trouble on the UI previously, but this time it is really becoming a "bug" to me as I really picked wrong id numbers many times....

I think this is a recent (years?) UI change, and it is not a correct design decision, so I insist this should be treated as a bug rather than feature request.

**Comment by pravesh-sharma** [comment]
Feature implemented. Tested on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-14/).

Env:
OS - macOS 14.7 (Sonoma)
Mode - Desktop
