### ISSUE TITLE
Automatically strip postgres:// from url

### ISSUE THREAD

**Issue by SorkoPiko** [pgadmin-org/pgadmin4#7877]
**Describe the solution you'd like**

I'd been stuck on the server connection screen for 30 minutes, because I had `postgres://` at the front of my URL.
I think the URL should be stripped of `postgres://` if it's present

**Describe alternatives you've considered**

Maybe add some text to say `postgres://` isn't required.

**Additional context**

None

**Comment by adityatoshniwal** [comment]
@SorkoPiko  Which URL are you talking about?

**Comment by SorkoPiko** [comment]
My apologies, I should have been more specific.
![image](https://github.com/user-attachments/assets/2ad6dcdc-93ec-4bef-b0dd-93451fb15a5f)

**Comment by adityatoshniwal** [comment]
> My apologies, I should have been more specific. ![image](https://private-user-images.githubusercontent.com/36188446/363077183-2ad6dcdc-93ec-4bef-b0dd-93451fb15a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDcwMTgsIm5iZiI6MTcyNTAwNjcxOCwicGF0aCI6Ii8zNjE4ODQ0Ni8zNjMwNzcxODMtMmFkNmRjZGMtOTNlYy00YmVmLWIwZGQtOTM0NTFmYjE1YTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA4MzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZjJmNGQwZWZjNmFjMTBiMmZmMjQ3ZTNjNmMzN2ZhYjc1NWY1ZjQwN2JmZmE1YTI2YjIzNzY3NjQ4Y2YxOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2LytLjCuTFNXi3ozoZnfawlhrdFAtWG2Dz-EjSv3z90)

That clearly says Hostname/address. pgAdmin cannot/shouldn't edit a users hostname. You need to provide valid value.
Closing this issue.
Thanks.
