### ISSUE TITLE
cursor moves to end of line when editing input fields

### ISSUE THREAD

**Issue by dangelsaurus** [pgadmin-org/pgadmin4#7878]
When trying to edit an input box, say when creating a new table, or column, or editing something in the "properties" menu, the cursor jumps to the end of the line after pressing a key.  so if I'm trying to rename "table" to "mytable". I end up with "mtabley" since the cursor immediately jumps to the end, even though I'm trying to edit something at the beginning of the field.

Version: 8.11
Application Mode: Desktop
Windows 11

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-09-10/
Package: arm64
Environment: macOs Ventura 13.5.1
