### ISSUE TITLE
GUI anomaly v8.11.0 for pgAdmin4 (Grid view turned into full width columns / just rows / non-scrollable data)

### ISSUE THREAD

**Issue by clarisetlw** [pgadmin-org/pgadmin4#7879]
*Workspace Environment*
- Windows OS (includes WSL)
- Docker Desktop using pgAdmin (latest version) as extension

*Actions taken before creating this issue*
- Firstly, without the file menu that has been removed upon the update (confirmed to be consistent among team members), I am unable to access File > Reset Layout to stop the error
- Uninstalled pgAdmin4 as an extension
- Uninstalled Docker Desktop
- Restarted the work laptop
- Check through preferences, going through *Configure pgAdmin > Preferences > Query Tool > Results Grid* to change maximum column width from 0 to 500, resulted in no change after saving changes
- Altered other potential settings but to no change in the GUI
- Going to any table > View/Edit Data > All Rows > Reset Layout (icon at top right corner)
- No hotkeys (that I am aware of) had affected or caused the anomaly
- Searched the internet for anybody else who had this issue, nothing that currently matches problem

Looking at the images, it is clear to see that the GUI has somehow reformatted upon updating from 8.10 to 8.11. What is more worrying is that this has only affected me in a team where 2 other users of Docker Desktop (of the same version) do not face this issue, while the third team member has not updated due to what happened to my pgAdmin.

Also note that due to the way the data is displayed, I cannot scroll and can only access data further below is by selecting a cell and pressing the down key and after it reaches a certain limit to show (like in the example below) of columns found under 'Product' will then display the other searches as a singular path name with no icon indication besides reading the full path name

![Screenshot 2024-08-30 103136](https://github.com/user-attachments/assets/45c6123d-e008-4453-a102-dfdb2830e602)
![Screenshot 2024-08-30 103315](https://github.com/user-attachments/assets/3d0747a8-0545-4aa2-85db-ed6a248d2d99)

**Side Note: If this may have any contributing fact that I don't have .../AppData/Roaming/pgAdmin **
When restoring my database, I cannot open the file icon to access the pgAdmin folder and upload the file to be used from there, instead it is done manually through a series of steps (which had also affected two of the team members and provided me this solution)
- Docker settings > Extensions > Check Show Docker Extensions system containers
- Open Containers > open newly generated container > pgadmin4_embedded_dd_vm > View Files > tmp > Import File
- After adding the file > pgAdmin4 extension > Database > Restore > type in file path [/tmp/<Folder>/<File>.txt]

*dies*
Hope to get an idea of what might be the problem, reading the data now is impossible :'D

**Comment by yogeshmahajan-1903** [comment]
@clarisetlw 
Can you please get screenshot of About > Help in pgAdmin?

**Comment by clarisetlw** [comment]
I am using latest version and I am also running the pgAdmin on the browser with no problems with any problems mentioned above.
However the GUI anomaly is not present on the browser, and only occurs when the latest installed version of pgAdmin4 extension on Docker Desktop 

![Screenshot 2024-09-02 104728](https://github.com/user-attachments/assets/f3745ee3-4790-4567-bf69-129032ee47c2)

**Comment by adityatoshniwal** [comment]
> I am using latest version and I am also running the pgAdmin on the browser with no problems with any problems mentioned above. However the GUI anomaly is not present on the browser, and only occurs when the latest installed version of pgAdmin4 extension on Docker Desktop
> 
> ![Screenshot 2024-09-02 104728](https://private-user-images.githubusercontent.com/103199516/363543989-f3745ee3-4790-4567-bf69-129032ee47c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTQwMjcsIm5iZiI6MTcyNTI1MzcyNywicGF0aCI6Ii8xMDMxOTk1MTYvMzYzNTQzOTg5LWYzNzQ1ZWUzLTQ3OTAtNDU2Ny1iZjY5LTEyOTAzMmVlNDdjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwNTA4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODcyMTFkNmYyMTBjYjIwNmY2MmM2NjZhMGM4NTQ1MmVkZWFjNmI4MGZiZjU0NjI0Y2ZiYTYzYzEwZDUyMWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0IY4n4n8-FbdHsOYoELFZeLOZZTyozCc4GrG-0c9n7M)

Hi @clarisetlw,

Can you check the about dialog of pgAdmin?
pgAdmin is not officially supported on Docker desktop, but if its an easy fix then we can think. However, if the about dialog shows an older browser version then unfortunately, we can't fix it.

**Comment by claudep** [comment]
Hi, I'm getting the exact same behavior as the reporter after updating to 8.11 on my pgAdmin 4 server (running on Debian stable).
However, it happens on my Firefox 115 instance, but not on Chromium (so it's indeed a client issue). Even starting a Firefox private window doesn't help. Strange...

**Comment by khushboovashi** [comment]
@claudep, upgrade your Firefox ESR 115 to the latest version (128).

**Comment by claudep** [comment]
It's not an option for me, as I'm attached to the Firefox ESR from Debian stable. However, I guess the latest 128 ESR version should enter Debian in the next 2-3 months (https://tracker.debian.org/pkg/firefox-esr).

**Comment by KnSwee** [comment]
Same problem

**Comment by khushboovashi** [comment]
As a workaround, you can use Chrome and wait till the FF ESR 128 official support for Debian platforms.
Closing the issue.

**Comment by claudep** [comment]
I can understand your decision. However it would be appreciated if you don't rush in new CSS/JS features, as in some job contexts, you cannot always easily decide to upgrade to latest versions or to change your browser (which is not my case, honestly).

**Comment by StefanLobbenmeierObjego** [comment]
> As a workaround, you can use Chrome and wait till the FF ESR 128 official support for Debian platforms.
Closing the issue.

Rolling back to 8.10 should also work right?
