### ISSUE TITLE
Filter on database listing

### ISSUE THREAD

**Issue by udit47** [pgadmin-org/pgadmin4#7880]
**Describe the solution you'd like**

It would be great to have a "like" filter on the list of databases on the left panel. When you have 500+ databases on single server, lot of scrolling can be avoided using the filter.

**Describe alternatives you've considered**

No alternative available.

**Comment by pravesh-sharma** [comment]
This will be taken care of with https://github.com/pgadmin-org/pgadmin4/issues/4192
