### ISSUE TITLE
pgAdmin4 Debugger Window UI Controls

### ISSUE THREAD

**Issue by hanastopoulos** [pgadmin-org/pgadmin4#7883]
**Description**
When utilizing pgAdmin4 7.8 in Windows 11 and debugging functions the **Debugger**  dialog Window has some buggy and unexpected behavior when working with parameters.  

First, boolean parameters passed to a function might be true, false, null, or a default value.  A checkbox is presented to indicate a true value.  An unchecked box should therefore indicate a false value.  Having unchecked boolean checkboxes often results in the Debug submission button not being active and clickable.  Sometimes the user is forced to check and uncheck the boolean checkboxes to satisfy the submission requirements and finally have the Debug button made active and clickable.

Second, if the user manually types in a value in a parameter's **Value** input box, it seems like this should automatically deactivate the corresponding **Use Default?** checkbox for the parameter, unless the intent is to allow toggling between a specified parameter or a default value for the parameter.

Third, modified or edited functions require a manual Object Explorer refresh, before the function can be debugged again, otherwise a "Function Not Found" error dialog is displayed to the user when attempting to debug again.

**To Reproduce**

1. Debug a schema function with one or more boolean parameters by right clicking om the function name under Schemas.
2. Attempt to submit the values without toggling all boolean checkboxes.
3. The Debug submission button will not be active until all boolean checkboxes are toggled.

**Expected behavior**

An unchecked boolean checkbox should default to a false value and shouldn't require toggling.

**Error message**

**Debugger Error:** The specified function could not be found.

**Screenshots**

![image](https://github.com/user-attachments/assets/98f9b769-97d9-4526-83dd-f470e516bdfd)
![image](https://github.com/user-attachments/assets/46487522-e9f6-40b0-988a-7de886316126)

**Desktop (please complete the following information):**
About pgAdmin 4
Version: 7.8, behavior also seen in 8.11
Application Mode: Desktop
Current User: pgadmin4@pgadmin.org
NW.js Version: 0.77.0
Browser: Chromium 114.0.5735.91
Operating System: Windows-10-10.0.22631-SP0, Windows 11 Pro

**Comment by hanastopoulos** [comment]
The Debugger "function could not be found" error occurs when a function is dropped and re-created versus just a "create and replace" operation.  That technically might not be a bug.

**Comment by RohitBhati8269** [comment]
@hanastopoulos The **"function could not be found"** error in the debugger is not a bug. It occurs because our tree node is not auto-refreshed.
