### ISSUE TITLE
Suggestion: Allow disabling the confirmation on application exit

### ISSUE THREAD

**Issue by ThomasLandauer** [pgadmin-org/pgadmin4#7890]
**Describe the solution you'd like**

When closing pgAdmin4 8.11 (Desktop), there's a confirmation dialog:
> Are you sure you want to quit the application?

I'm suggesting to allow disabling this.

**Additional context**

In File > Preferences I found a seemingly related option:
> Confirm on close or refresh?

But even if I disable this, I still get the confirmation dialog.

**Comment by adityatoshniwal** [comment]
Its a bug. The confirmation should respect `Confirm on close or refresh?`

**Comment by pravesh-sharma** [comment]
Found one issue:

If `Confirm on close or refresh?` is enabled and I try to reload from `view -> Reload` or `Reset all preferences -> Save & Reload` it does not ask for confirmation and reloads the application.

**Comment by adityatoshniwal** [comment]
> Found one issue:
> 
> If `Confirm on close or refresh?` is enabled and I try to reload from `view -> Reload` or `Reset all preferences -> Save & Reload` it does not ask for confirmation and reloads the application.

Hi @pravesh-sharma,
It is intentionally done. When use a user decides to "Save and Reload", it is expected not to ask another confirmation.
View->Reload is for trouble shooting, should not require any pgAdmin code confirmation.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-09-19/).

Env:
OS - macOS 14.6.1 (Sonoma)
Mode - Desktop

**Comment by tobese** [comment]
Thx for reporting and fixing this! Now my Mac might be able to update OS during the night!
