### ISSUE TITLE
Auto refresh of Object Explorer on when updating objects

### ISSUE THREAD

**Issue by bjorngback** [pgadmin-org/pgadmin4#7892]
When I update something from the Object Explorer, e.g. if I open a table and change a column name, the Object Explorer still shows the old object. To get it updated I need to right click and select refresh.

Obviously it is pretty annoying to do this every time if I want to be sure that the Object Explorer is showing the correct information. I therefore suggest the improvement that when one clicks save after having updated an object, it does an automatic refresh of the Object Explorer (i.e. it automatically triggers the same refresh I get by doing right click -> refresh).

**Comment by adityatoshniwal** [comment]
pgAdmin should auto-refresh in that case. Its a bug if it is not.

**Comment by khushboovashi** [comment]
The child node is not getting updated if it is updated from the parent node in the object explorer.

**Comment by anthonydb** [comment]
I was just coming here to ask about this. It would also be good if the Object Explorer automatically refreshed every time a CREATE DATABASE or CREATE TABLE statement is executed.

**Comment by adityatoshniwal** [comment]
> I was just coming here to ask about this. It would also be good if the Object Explorer automatically refreshed every time a CREATE DATABASE or CREATE TABLE statement is executed.
The problem is how do we detect that a new database or table is created.

**Comment by khushboovashi** [comment]
> I was just coming here to ask about this. It would also be good if the Object Explorer automatically refreshed every time a CREATE DATABASE or CREATE TABLE statement is executed.

Did you mean, whenever the CREATE DATABASE or CREATE TABLE executes from the Query Tool?

**Comment by anthonydb** [comment]
@khushboovashi 
Yes, when I execute `CREATE DATABASE` or `CREATE TABLE` in the Query Tool.

I wouldn't expect pgAdmin to know about those commands run outside the tool, e.g. in psql.

**Comment by khushboovashi** [comment]
> @khushboovashi Yes, when I execute `CREATE DATABASE` or `CREATE TABLE` in the Query Tool.

In that case,  we need to manage `DELETE`,  `UPDATE` statements too.

> I wouldn't expect pgAdmin to know about those commands run outside the tool, e.g. in psql.

**Comment by anthonydb** [comment]
> In that case, we need to manage DELETE, UPDATE statements too.

Yes, that makes sense! I hope it is possible to implement that feature.

**Comment by pravesh-sharma** [comment]
Hi @anthonydb,

You can create a new feature request for it.

**Comment by pravesh-sharma** [comment]
Hi @anthonydb,

You can submit a new feature request for it.

**Comment by pravesh-sharma** [comment]
Tested the issue and is working fine.

**Comment by anthonydb** [comment]
@pravesh-sharma 
Feature request created at https://github.com/pgadmin-org/pgadmin4/issues/8250
