### ISSUE TITLE
pgadmin v8.11 the different client backend But all SQL are same

### ISSUE THREAD

**Issue by hellojw** [pgadmin-org/pgadmin4#7895]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
When I use the pgadmin version 8.11，
view the State，Active Sessions Only，
there are 12 sessions，when expanding the 12 sessions，the client backend SQL are same。
But should be there are different client backend and different SQL.

**To Reproduce**

1. Go to 'State'
2. Click on 'Active Sessions Only'
3. See the error: all client backend sessions expanding are the same SQL

**Expected behavior**

Different client backend should be different SQL, or the back-end database statements are the same as those shown

**Error message**

There's no error message, but each one is the same, so you can reproduce it

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version: [8.11]
 - Mode: [Server]
 - Browser (if running in server mode): [Microsoft Edge]
 - Package type: [Container]

**Additional context**
![image](https://github.com/user-attachments/assets/7a6bd32e-82f7-4914-9fb7-7a3a7f1a923b)

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-09-10/
Package: arm64
Environment: macOs Ventura 13.5.1
