### ISSUE TITLE
pgAdmin v8.11 freezes when State panel is opened

### ISSUE THREAD

**Issue by aledonati** [pgadmin-org/pgadmin4#7900]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

This happens under database cluster heavy load
When clicking on the State tab in the Dashboard page, the SW is able to display sessions but when it comes to display Locks, it hangs and suddenly the main page becomes white. I have to close pgAdmin.
It didn't happen with the previous version I had installed (v8.9), where the Sessions page was organized differently, there was a Locks subtab, so the queries vs pg_stat_activity/pg_locks where executed on demand. Now you probably try to collect too much information to display on the State page?

**To Reproduce**

1. Go to the Dashboard
2. Click on State
3. See above the description

**Expected behavior**
Locks are displayed and the SW does not hang

**Error message**

No error message is displayed.

**Screenshots**

N/A.

**Desktop (please complete the following information):**
 - Windows 10 22H2 (Windows-10-10.0.19045-SP0)
 - Version: v8.11
 - Browser: Chrome 128.0.6613.36
 - Mode: Desktop

**Additional context**
N/A

**Comment by anilsahoo20** [comment]
It will be fixed with #7861
