### ISSUE TITLE
Support system option for sslrootcert

### ISSUE THREAD

**Issue by dgilman-hrp** [pgadmin-org/pgadmin4#7907]
**Describe the solution you'd like**

postgres v16 and on supports using `system` for `sslrootcert` where the system root certificate storage will be used instead of setting the path to a file.

**Describe alternatives you've considered**

The workaround is to set the path manually, which is workable, but less secure and not the desired behavior.

**Additional context**

[Postgres docs here](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLROOTCERT)

**Comment by yogeshmahajan-1903** [comment]
@dgilman-hrp 
You can set the value for Root certificate by manually typing `system`. 
<img width="697" alt="Screenshot 2024-09-20 at 5 07 30 PM" src="https://github.com/user-attachments/assets/0cb59e4b-198d-4a8f-8335-6bc6acd4c79a">

**Comment by willluongo-vendia** [comment]
I am running pgadmin 8.12 and it does not seem to honor the "system" value, I get this error:
> Unable to connect to server: connection failed: connection to server at "<ip>", port 5432 failed: root certificate file "/Users/<user>/.postgresql/root.crt" does not exist Either provide the file, use the system's trusted roots with sslrootcert=system, or change sslmode to disable server certificate verification.

from these settings:
<img width="698" alt="image" src="https://github.com/user-attachments/assets/4421bcd3-52c7-4068-8764-6f6e5f2f9511">
 



However, I can provide the path from this line in pathAbout PgAdmin 4: `CA_FILE = "/Applications/pgAdmin 4.app/Contents/Resources/web/cacert.pem"`. The connection also works from psql using the `sslrootcert=system` option.

**Comment by yogeshmahajan-1903** [comment]
@willluongo-vendia 

Does file - /Users/<user_name>/.postgresql/root.crt exists on you system? If yes can you please list permission for the same?
Also does pgadmin is installed with the same user which is being used to create psql  connection?

When I rename root certificate, at ~/.postgresql directory  I get the error
$ .postgresql % sudo mv root.crt root123.crt                                                                                                            
$ .postgresql % psql "host=< ip_addr > port=<port_number> dbname=postgres user=postgres connect_timeout=10 sslmode=verify-full"
psql: error: connection to server at "<ip_addr>, port< port_number > failed: root certificate file "/Users/<user_name>/.postgresql/root.crt" does not exist
Either provide the file or change sslmode to disable server certificate verification.

**Comment by willluongo-vendia** [comment]
@yogeshmahajan-1903 No, that file does not exist on my machine. I am running pgadmin as the same user I installed it with.

**Comment by yogeshmahajan-1903** [comment]
@willluongo-vendia 
Have you set environmental variable SSL_CERT_FILE?

**Comment by kevin-kortum-trustedshops** [comment]
I everyone, i just wanted to confirm the issue for my mac (14.7) as well. I am currently trying to connect to and Postgres RDS instance on AWS using their certificate, but the documentation is quite unclear. So, i was hoping to add the certificate to the system truststore and be done but it seems to be ignored with the same error described above.

FYI: I have not set the env variable mentioned.

**Comment by adityatoshniwal** [comment]
Hi @dgilman-hrp @kevin-kortum-trustedshops,
We've made some changes in this regard, but not entirely sure if it will work. Can you guys test v8.13 once and let us know?

**Comment by kevin-kortum-trustedshops** [comment]
Hi,
i must admit that my assumption from two days ago might be incorrect as i was following the red herring. I learned today that my company IT was blocking TLS on the Postgres port. I never had a chance to test this properly. It now works fine for me but might be unrelated to the problem at all.

**Comment by yogeshmahajan-1903** [comment]
@dgilman-hrp 
Can you please try with pgadmin version 8.13, we have added fix for this? 
What is location of your ssl root certificates on Mac?

**Comment by khushboovashi** [comment]
No response from the author, closing the issue.
