### ISSUE TITLE
Unable to change user password in pgAdmin web

### ISSUE THREAD

**Issue by rajat9093** [pgadmin-org/pgadmin4#7912]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

Description:
Unable to change user password in pgAdmin web.
I am using pgAdmin4 8.11 version on an EC2 instance. It gets installed through the python package - https://www.pgadmin.org/download/pgadmin-4-python/

When I am trying to change the user password from the web after entering the current and new password, it just loads for around 1-2 mins and come back at the same stage. It is not giving any pop-up that the password has been changed.

I can login with the old password only. New password is not getting setup.

**To Reproduce**

1. Go to pgAdmin portal
2. Click on Change Password
3. Enter the currenet & new password.
4. Click on Change

**Expected behavior**

It should change the user password and give the pop-up that password has been changed successfully.

**Error message**

Not giving any error message. I can see 504 in developer tools.

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2023
 - Version: pgAdmin4 8.11
 - Mode: Server
 - Browser (if running in server mode): chrome
 - Package type: Python

**Comment by rajat9093** [comment]
@akshay-joshi 
Could you please help/suggest for the mentioned issue.

**Comment by yogeshmahajan-1903** [comment]
@rajat9093 
I am not able to reproduce the issue. It gives successful notification on right bottom corner. I might take a little long than other requests. Can you please try again and wait for 10-20 seconds?

**Comment by rajat9093** [comment]
Hey @yogeshmahajan-1903 
So, I found the issue. It was related to my configuration. I am using postfix in my EC2 server which is creating conflicts with the pgAdmin configuration.
I am able to fix this.

**Comment by Ballon10** [comment]
Hello, 
I got a same behavior, how could I resolve it ?

Thanks
