### ISSUE TITLE
Activity dashboard State details panels all show the same query

### ISSUE THREAD

**Issue by dcpowertothepeople** [pgadmin-org/pgadmin4#7922]
In the server Dashboard, under the State panel, is a listing of Sessions, with per session columns like: PID, State, Wait event and Blocking PIDs. Clicking the arrow to open the details is supposed to show the query running in that process.

The details are always showing the same query across the board, even though most of those processes are not running that query, as is proven by running the query:
select pid, state, query_start, query from pg_stat_activity where state in ('active', 'idle in transaction') and pid <> pg_backend_pid()

To Reproduce

1. Open a Query Tool
2. Execute: select pid, state, query_start, query from pg_stat_activity where state in ('active', 'idle in transaction') and pid <> pg_backend_pid()
3. Go to 'Dashboard'
4. Click on 'State'
5. Click on a few '>' arrows in the 'Sessions' listing to see the Details, and compare the contents of the SQL line with the contents of the query column from the results of step 2
6. Notice all the SQL lines in the above show the same SQL and that they don't always match the query result with the same PID
7. Notice that refreshing either view in any order does not alleviate the problem, so it's not a timing issue

**Expected behavior**

The SQL line is expected to show the actually running query, not a random one from some other session.

**Screenshots**
The first screenshot shows a SELECT query as the SQL, while the second screenshot shows that that process is running a TRUNCATE statement (waiting for a lock to release for a while already, so that PID is really really not running a SELECT statement!).

![query-output](https://github.com/user-attachments/assets/99069ea8-5dff-476e-a3aa-2dd352f95e9b)
![dashboard-output](https://github.com/user-attachments/assets/a5bd72cb-60ab-4d3a-b7e9-2267fe20868e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.11
 - Mode: Desktop
 - Package type: Downloaded from [pgadmin](https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.11/windows/) 
 - PostgreSQL server version: PostgreSQL 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit

**Comment by davidak09** [comment]
Exactly the same behavior on MacOs with PgAdmin version 8.11.

**Comment by pravesh-sharma** [comment]
Duplicates #7895
