### ISSUE TITLE
TIL: Using the `PGADMIN_DEFAULT_USER` in a docker image does not work

### ISSUE THREAD

**Issue by dayo777** [pgadmin-org/pgadmin4#7923]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
PgAdmin does not start on Docker when setting the PGADMIN_DEFAULT_USER value. I initially used the PGADMIN_DEFAULT_EMAIL, which works as expected, then decided to switch to using the PGADMIN_DEFAULT_USER which produced `Exited (1)` status on docker.

Is it possible that using the PGADMIN_DEFAULT_USER is deprecatated?

**To Reproduce**

ru
`docker run --name test-pgadmin -p 15432:80 -e "PGADMIN_DEFAULT_EMAIL=oruns@gmail.com" \
  -e "PGADMIN_DEFAULT_PASSWORD=postgres" -d dpage/pgadmin4:8.4`
1. You might want to have a Postgres instance already running on docker.
2. Start the PgAdmin docker instance using the command above. 
3. See the error

**Expected behavior**

I should be able to login with just setting the USER & PASS env variables, but I had to use the EMAIL var.

**Comment by khushboovashi** [comment]
Hi @dayo777, 

PGADMIN_DEFAULT_USER is not supported. Please check the documentation: https://www.pgadmin.org/docs/pgadmin4/8.11/container_deployment.html

**Comment by dayo777** [comment]
Hello, I think I was reading an older docs on setting up PgAdmin. But I have been able to resolve the issue.
Thank you.
