### ISSUE TITLE
need setup google authentication

### ISSUE THREAD

**Issue by SkazochnikZlodey** [pgadmin-org/pgadmin4#7925]
**Describe the bug**
review documentation and code and cannot setup google authentication for admin 8.11
**To Reproduce**
used docker image dpage/pgadmin4:8.11
/pgadmin4/config_local.py

`# CSRF token
WTF_CSRF_ENABLED = False
WTF_CSRF_CHECK_DEFAULT = False

# External Database Params
CONFIG_DATABASE_URI = 'postgresql://pgadmin:Passw0rd1@35.333.333.195:5432/pgadmin'
# ip changed to incorrect
#OAuth 2.0
AUTHENTICATION_SOURCES = ['oauth2', 'internal']

OAUTH2_CONFIG = [
    {
        # The name of the of the oauth provider, ex: github, google
        'OAUTH2_NAME': 'google',
        # The display name, ex: Google
        'OAUTH2_DISPLAY_NAME': 'Google Authorization',
        # Oauth client id fake 
        'OAUTH2_CLIENT_ID': '682431691212-11116lealir3e4p2222o0hnil8c64200.apps.googleusercontent.com',
        # Oauth secret fake
        'OAUTH2_CLIENT_SECRET': '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',
        # URL to generate a token,
        # Ex: https://github.com/login/oauth/access_token
        'OAUTH2_TOKEN_URL': 'https://oauth2.googleapis.com/token',
        # URL is used for authentication,
        # Ex: https://github.com/login/oauth/authorize
        'OAUTH2_AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/auth' ,
        # server metadata url might optional for your provider
        'OAUTH2_SERVER_METADATA_URL': 'https://accounts.google.com/.well-known/openid-configuration',
        # Oauth base url, ex: https://api.github.com/
        'OAUTH2_API_BASE_URL': 'https://www.googleapis.com/',
        # Name of the Endpoint, ex: user
        'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
        # Oauth scope, ex: 'openid email profile'
        # Note that an 'email' claim is required in the resulting profile
        'OAUTH2_SCOPE': 'openid email profile',
        # The claim which is used for the username. If the value is empty the
        # email is used as username, but if a value is provided,
        # the claim has to exist.
        #'OAUTH2_USERNAME_CLAIM': 'email',
        # Font-awesome icon, ex: fa-github
        'OAUTH2_ICON': 'fa-google',
        # UI button colour, ex: #0000ff
        'OAUTH2_BUTTON_COLOR': '#4285F4',
        # The additional claims to check on user ID Token or Userinfo response.
        # This is useful to provide additional authorization checks
        # before allowing access.
        # Example for GitLab: allowing all maintainers teams, and a specific
        # developers group to access pgadmin:
        # 'OAUTH2_ADDITIONAL_CLAIMS': {
        #     'https://gitlab.org/claims/groups/maintainer': [
        #           'kuberheads/applications',
        #           'kuberheads/dba',
        #           'kuberheads/support'
        #      ],
        #     'https://gitlab.org/claims/groups/developer': [
        #           'kuberheads/applications/team01'
        #      ],
        # }
        # Example for AzureAD:
        # 'OAUTH2_ADDITIONAL_CLAIMS': {
        #     'groups': ["0760b6cf-170e-4a14-91b3-4b78e0739963"],
        #     'wids': ["cf1c38e5-3621-4004-a7cb-879624dced7c"],
        # }
        'OAUTH2_ADDITIONAL_CLAIMS': True,
        # Set this variable to False to disable SSL certificate verification
        # for OAuth2 provider.
        # This may need to set False, in case of self-signed certificates.
        # Ref: https://github.com/psf/requests/issues/6071
        'OAUTH2_SSL_CERT_VERIFICATION': True,
        # set this variable to invalidate the session of the oauth2 provider
        # Example for keycloak:
        # 'OAUTH2_LOGOUT_URL':
        # 'https://example.com/realms/master/protocol/openid-connect/logout?post_logout_redirect_uri={redirect_uri}&id_token_hint={id_token}'
        'OAUTH2_LOGOUT_URL': None
    }
]

OAUTH2_AUTO_CREATE_USER = True

# Enable Debug mode
DEBUG = True

# Log SQL queries
CONSOLE_LOG_LEVEL = DEBUG
`

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

what have to be as if publick name is pga.testing.io:
Authorised redirect URIs
For use with requests from a web server
URIs 1 
http://pga.testing.io/oauth2/callback/google ?????

what wrong in OAUTH2_CONFIG ?
OAUTH2_TOKEN_URL???? OAUTH2_AUTHORIZATION_URL ??? OAUTH2_SERVER_METADATA_URL ??? OAUTH2_API_BASE_URL??? OAUTH2_USERINFO_ENDPOINT ??? OAUTH2_SCOPE ??? OAUTH2_USERNAME_CLAIM ???

in output 

64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
2024-09-15 13:28:32,589: DEBUG	pgadmin:	Authentication initiated via source: oauth2
2024-09-15 13:28:33,027: DEBUG	pgadmin:	Authentication initiated via source: oauth2 is failed.

from user web browser
Access blocked: This app’s request is invalid

vladimir.d@testing.io
You can’t sign in because this app sent an invalid request. You can try again later or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch

**Comment by yogeshmahajan-1903** [comment]
@SkazochnikZlodey 
Kindly remove client credentials. Redirect url should be same as the your pgadmin server url. Redirect url has to be specified while creating Oauth2 app in google.

**Comment by SkazochnikZlodey** [comment]
OAUTH2_CLIENT_ID and OAUTH2_CLIENT_SECRET is fake
Authorised redirect URIs
URIs 1
http://pga.testing.io/oauth2/callback/google 
changed to 
http://pga.testing.io

not help

**Comment by yogeshmahajan-1903** [comment]
@SkazochnikZlodey 
My bad. Redirect url should be 
```
http://<app url with port if any>/oauth2/authorize
```

**Comment by SkazochnikZlodey** [comment]
This fix passed. but 
{"success":0,"errormsg":"404 Client Error: Not Found for url: https://www.googleapis.com/userinfo","info":"","result":null,"data":null}

**Comment by SkazochnikZlodey** [comment]
OAUTH2_TOKEN_URL???? OAUTH2_AUTHORIZATION_URL ??? OAUTH2_SERVER_METADATA_URL ??? OAUTH2_API_BASE_URL??? OAUTH2_USERINFO_ENDPOINT ??? OAUTH2_SCOPE ??? OAUTH2_USERNAME_CLAIM ???

**Comment by SkazochnikZlodey** [comment]
@yogeshmahajan-1903 Thanks a lot. Last question: how to restrict access only for testing.io and testing.org ?

**Comment by yogeshmahajan-1903** [comment]
> @yogeshmahajan-1903 Thanks a lot. Last question: how to restrict access only for testing.io and testing.org ?

While creating OAuth2 web app, you need to specify application url, there you can mention desired url.
