### ISSUE TITLE
Typing in edit boxes goes to end of word

### ISSUE THREAD

**Issue by DavidBuch1** [pgadmin-org/pgadmin4#7938]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
Typing into an edit box to change the name of something moves the cursor to the end of the word after EACH letter typed. Leads to messed up fields if not paying attention.

Open any table properties, and go to a field. Place the cursor in the middle of the field name and start typing.. You will see the cursor jump to the end of after each letter. 
See video of issue in the shared google drive

https://drive.google.com/drive/folders/1QdtTz6Iwf4KJ9WVEakP8uoQX0vz4IeYA?usp=sharing

**Comment by pravesh-sharma** [comment]
Duplicates #7878.
