### ISSUE TITLE
pgAdmin password fails after reboot

### ISSUE THREAD

**Issue by dataclankgh** [pgadmin-org/pgadmin4#7939]
pgAdmin 4 v8.11
Desktop mode
macOS Sonoma 14.6.1
macOS Sequoia 15.0
MacBook Air M3 15

Installed Enterprise DB, postgresql-17.0-rc1-osx.dmg
	⁃	pgAdmin installed with PostgreSQL
Logged in using password manager to prevent password error at login
Restored Three databases
Next day, attempt to login failed (using macOS Sonoma 14.6.1).
- connection failed: connection to server at "127.0.0.1", port 5432 failed: could not receive data from server: Connection refused

macOS Sequoia 15.0 installed.
Found that I could reinstall Enterprise DB, postgresql-17.0-rc1-osx.dmg over current install
Password worked
Quit app.
Logged in again, saving password and quit.
Logged in multiple times using saved password.
Shut down computer.
Rebooted, attempted pgAdmin login, failed (using password manager)
- connection failed: connection to server at "127.0.0.1", port 5432 failed: could not receive data from server: Connection refused

**Comment by yogeshmahajan-1903** [comment]
@dataclankgh 
Can you please try connecting to the server using psql? Error is connection refused from Postgres server.

**Comment by dataclankgh** [comment]
Akshay,

I was previously asked to connect to the server using psql.

In psql:
Server [localhost]: localhost
Database [postgres]: postgres
Port [5432]: 5432
Username [postgres]: postgres
for username I also tried postgresql but got same results

psql: error: connection to server at "localhost" (::1), port 5432 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?

Press <return> to continue...

**Comment by yogeshmahajan-1903** [comment]
@dataclankgh 
As you are not able to connect using psql also, it means Postgres server is not up and running. You may status with the command - 
```
brew info postgres
```
or
```
pg_ctl -D /usr/local/var/postgres start
```

As this is not pgdmin issue , closing the issue.

**Comment by dataclankgh** [comment]
Please confirm that you saw initial PG admin log on successful, but password unsuccessful after computer shut down and rebooted.
