### ISSUE TITLE
OAuth2 issue in pgAdmin 4.

### ISSUE THREAD

**Issue by khushboovashi** [pgadmin-org/pgadmin4#7945]

**Comment by yogeshmahajan-1903** [comment]
This is verified.

**Comment by AugustIce** [comment]
@yogeshmahajan-1903 hi,I learned from the official website that oauth2 authentication is only supported after version 5.5. Are pgadmin versions earlier 5.5 affected by this vulnerability？

**Comment by GkaMei** [comment]
oumaga

**Comment by yogeshmahajan-1903** [comment]
@AugustIce 
No, version before 5.15 are not affected by this and with latest released version 8.12 issue is already fixed.
