### ISSUE TITLE
Broken interface display on android chrome.

### ISSUE THREAD

**Issue by Zapzatron** [pgadmin-org/pgadmin4#7953]
**Describe the bug**

Broken interface display on android chrome.

**To Reproduce**

1. Go to 'pgadmin4/browser'
3. See the broken interface display

**Expected behavior**

Full interface display

**Screenshots**

![image](https://github.com/user-attachments/assets/6f86c355-6847-4516-b52d-4167d7f16f45)

**Desktop**
 - OS: Android
 - Version: 8.11
 - Mode: Server
 - Browser: Chrome

**Additional context**
pgadmin4 is running on ubuntu server. Access is granted using ngrok. The broken interface is visible on android.
Commands to install on Ubuntu:
 ```
curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add
sudo sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
sudo apt install pgadmin4-web
sudo /usr/pgadmin4/bin/setup-web.sh
```

**Comment by adityatoshniwal** [comment]
pgAdmin is not tested/supported on mobile devices below a tablet size.
We will work on this only if it is easily fixable.
