### ISSUE TITLE
v8.11 PSQL - No longer be able to copy the contents.

### ISSUE THREAD

**Issue by EddySoeparmin235** [pgadmin-org/pgadmin4#7954]
Prior to v8.11, PSQL allows to copy the contents. For example \d+ mytable shows the table name, column and its data type, indexes, and so on. I was able to copy and paste it to VSCode, but v8.11 is longer be able to copy and it to VSCode.

**Comment by adityatoshniwal** [comment]
Did you deny the clipboard access when psql asked for it?

**Comment by pravesh-sharma** [comment]
Duplicates #7957

**Comment by EddySoeparmin235** [comment]
I just downloaded v8.12, and this issue is not part of this release. Any idea when?

**Comment by adityatoshniwal** [comment]
> I just downloaded v8.12, and this issue is not part of this release. Any idea when?

it will be taken care in #7957

**Comment by EddySoeparmin235** [comment]
Yes, I saw AshesAV indicated that this issue has been fixed in #7957. I don't know how does it translate to v8.xx. Will that be v8.13 or?? Thanks.

**Comment by EddySoeparmin235** [comment]
So will that be v8.13 or v8.xx? It will be nice to see it fixed in v8.13. :)
