### ISSUE TITLE
v8.11 Dashboard - "Something went wrong message

### ISSUE THREAD

**Issue by EddySoeparmin235** [pgadmin-org/pgadmin4#7955]
Click on Dashboard > State. Click on Active Sessions.

Click on Configuration and click on State again, the Dashboard shows "Something went wrong"
![pgAdmin v11 Dashboard](https://github.com/user-attachments/assets/7ffe1259-5b15-4c4f-ad0d-5bc19750dbed)

Since then, I'm no longer be able to switch to any of the SQL Editor

**Comment by pravesh-sharma** [comment]
Issue fixed, verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-07/).

Env:
OS - macOS 14.7 (Sonoma)
Mode - Desktop

**Comment by EddySoeparmin235** [comment]
I just downloaded and installed pgadmin4-8.12-arm64.dmg. It works. Thanks guys!!

**Comment by EddySoeparmin235** [comment]
But, the copy command (Ctrl-C) does not work. NOT GOOD in the SQL Editor.
