### ISSUE TITLE
react-data-grid improper function on Firefox 115.0

### ISSUE THREAD

**Issue by jackmcnulty** [pgadmin-org/pgadmin4#7956]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

react-data-grid does not work correctly on Firefox, resulting in the data output menu appearing as a single column rather than in tabular format.

**To Reproduce**

1. Using the query tool, execute any query on Firefox 115.0
2. Look at the data output
3. (optional) Compare those steps to using Chrome instead

**Expected behavior**

I expected to see a tabular data output as I do using other browsers

**Error message**

There is no direct error message

**Screenshots**

![Screenshot 2024-09-20 134818](https://github.com/user-attachments/assets/ccbc6b0c-7cb5-44b7-878c-7fe5f7b09ed4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.11
 - Mode: Server
 - Browser Firefox 115.0
 - Package type: Container

**Additional context**

**Comment by adityatoshniwal** [comment]
Duplicates #7846
