### ISSUE TITLE
v8.11 Experiencing issues with cursor selection in PSQL Tool in pgAdmin, os Ubuntu

### ISSUE THREAD

**Issue by AbhinaySinghDBA** [pgadmin-org/pgadmin4#7957]
Version : 8.11
Application Mode : Desktop
Browser : Chrome 128.0.6613.36
Operating System : Ubuntu 22.04.5 LTS, Linux-6.8.0-40-generic-x86_64-with-glibc2.35

I am experiencing issues with cursor selection in the pgAdmin. Specifically, I cannot use the cursor to select text or interact properly within the PSQL Tool. This problem significantly hampers my ability to use pgAdmin effectively for database management tasks.

**Comment by adityatoshniwal** [comment]
@AbhinaySinghDBA works fine for me. Can you share a screenrecording?

**Comment by pravesh-sharma** [comment]
Issue fixed, verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-14/).

Env:
OS - macOS 14.7 (Sonoma)
Mode - Desktop
