### ISSUE TITLE
User management dialog search is not working.

### ISSUE THREAD

**Issue by anilsahoo20** [pgadmin-org/pgadmin4#7958]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

1. The search box takes the full width, but it has taken half width.
2. The search box is not giving any result on searching the users that are still present.
3. Note is missing in Existing table>Edit dialog>Partitions tab.

**Screenshots**
<img width="899" alt="Screenshot 2024-09-19 at 5 25 55 PM" src="https://github.com/user-attachments/assets/6d544743-29fb-492e-9a70-e1484a98bdc1">

<img width="901" alt="Screenshot 2024-09-23 at 2 33 55 PM" src="https://github.com/user-attachments/assets/b2ae3fcf-5f2f-4661-8259-47fb18593184">

**Comment by anilsahoo20** [comment]
#7955, the issue will be fixed along with this issue.

**Comment by yogeshmahajan-1903** [comment]
1.Scroll is added in the parameters - [Sev-3]
<img width="720" alt="Screenshot 2024-09-20 at 9 53 48 AM" src="https://github.com/user-attachments/assets/72de1a99-6cbf-447e-8e62-ae26470846c8">

Expected - 
<img width="771" alt="Screenshot 2024-09-20 at 9 53 53 AM" src="https://github.com/user-attachments/assets/f3eaedb1-4edf-44d5-b739-9fbe1077858a">

**Comment by asheshv** [comment]
[> #7955, the issue will be fixed along with this issue.
](https://github.com/pgadmin-org/pgadmin4/pull/7959)
This has not taken care of the Dashboard issue as it is not really related to SchemaView changes.

**Comment by pravesh-sharma** [comment]
Issue fixed verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-03/).

Env:
OS - macOS 14.7 (Sonoma)
Mode - Desktop.
