### ISSUE TITLE
BYTEA data are corrupted while download using PSQL - PGAdmin 8

### ISSUE THREAD

**Issue by thiyagarajan-s-alight** [pgadmin-org/pgadmin4#7962]
BYTEA data are corrupted while download using PSQL in version PGAdmin 8.3. **Previously it was works in PGAdmin 7.6**
It's happen for all formats. ex.: jpg,png,zip and pdf.
1. Go to PSQL tool.
2. Execute below query

> \COPY (<<blob select query>>) to '<<file location>>' (FORMAT binary);

4. After that try to open the file, showing corrupted error.

 - OS: Windows 11
 - Version: 8
 - Mode: Desktop 
![image](https://github.com/user-attachments/assets/c53bd4f1-dd4c-42ac-a9b6-afd5462de0a0)

![image](https://github.com/user-attachments/assets/cc49798f-31e0-4fa1-903d-5109e77f1657)

**Comment by pravesh-sharma** [comment]
Hi @thiyagarajan-s-alight,

This is the behaviour of psql binary of PostgreSQL. Report this to PostgreSQL if you think it's a bug. Not a pgAdmin issue.

**Comment by thiyagarajan-s-alight** [comment]
Hi @pravesh-sharma 

But it was worked in PGAdmin 7.6's psql.

**Comment by pravesh-sharma** [comment]
@thiyagarajan-s-alight I tested with pgAdmin 4 7.6 and could not reproduce this issue there also the file is corrupted. I tested with PostgreSQL 14.7.
