### ISSUE TITLE
Data output pgadmin 4 outputs as a list and not a table

### ISSUE THREAD

**Issue by fsn79** [pgadmin-org/pgadmin4#7963]
Win10, Pgadmin4 v8.11 - the query result is no longer displayed as a table. Now it looks like a list for each entry in the table. The "Reset layout" button does not help. I also did not find anything in Preferences. Deleting and creating a server also does not give a result. Tell me, what could be the problem?
![photo](https://github.com/user-attachments/assets/a611c656-4990-4ced-a339-195961a36574)

**Comment by shekshuev** [comment]
Same issue when i used this image https://hub.docker.com/r/dpage/pgadmin4/. I returned to version 8.10 and it is ok for now. By the way, the v8.12 still have this bug. I used Google Chrome for Windows, latest version

**Comment by adityatoshniwal** [comment]
@fsn79 @shekshuev  Please share browser details.

**Comment by fsn79** [comment]
@adityatoshniwal I also use https://hub.docker.com/r/dpage/pgadmin4/
version 8.11
Tried on Yandex.Browser (Chromium) and Microsoft Edge under Win10, as well as Mozilla Firefox (ver 110) under Xubuntu. In all cases, the result is the same.
![screen](https://github.com/user-attachments/assets/79e97b3e-abb3-40f3-b916-376021358f0d)

**Comment by adityatoshniwal** [comment]
@fsn79 You're browser versions? Firefox 110 is more than a year old. pgAdmin doesn't support Yandex.Browser. What is the MS Edge version?
We recently updated our libraries and stop fixing issues for browsers with very old versions.

**Comment by shekshuev** [comment]
I have the same stuff, when columns are being rows with no data. Just now i checked this configuration

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:8.11
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "3141:80"
            
on linux mint chrome Version 128.0.6613.113 (Official Build) (64-bit) and all is fine

**Comment by fsn79** [comment]
@adityatoshniwal @shekshuev Chrome version 128 is a recent version, and if you experience the same issue, it's clear that the problem isn't with an outdated or unsupported browser.

**Comment by adityatoshniwal** [comment]
Hi @fsn79 pgAdmin works fine on Chrome v128. In fact, pgAdmin 8.12 desktop is shipped with Chrome 128
<img width="747" alt="image" src="https://github.com/user-attachments/assets/17442e53-c00b-4020-add4-8934973ef7d3"> and works fine.

**Comment by fsn79** [comment]
@adityatoshniwal ok i will try ver.8.10 on my browsers and let you know the result

**Comment by SinRoot** [comment]
Same problem after update from 8.10 to 8.11.
Same problem after update from 8.12 to 8.12.
Clean install (+remove site cookie and cache) have this problem too.

```
OS Name:        Microsoft Windows 11 Pro
OS Version:     10.0.22631 N/A Build 22631
Browser:        Firefox ESR 115.15.0esr (32-bit)
```

**Comment by fsn79** [comment]
@adityatoshniwal Rebuilt the project with version 8.10 and the problem disappeared. Thanks everyone!

**Comment by adityatoshniwal** [comment]
> @adityatoshniwal Rebuilt the project with version 8.10 and the problem disappeared. Thanks everyone!

I recommend to update the browser version instead. 
Anyway, this issue duplicates #7956

**Comment by allComputableThings** [comment]
> @adityatoshniwal Rebuilt the project with version 8.10 and the problem disappeared. Thanks everyone!

It is present in 8.12

**Comment by kosmonavtus** [comment]
Same problem repeats on windows google chrome  8.13

**Comment by adityatoshniwal** [comment]
> Same problem repeats on windows google chrome 8.13

what is your google chrome version?

**Comment by Mimikoo** [comment]
The problem described by the author of this topic is persistent with every newer version of pgadmin starting with v.8.11.
I have the latest versions of browsers for my windows 7. I can not afford upgrade to windows 10 or 11. This leave no chance of using pgadmin.

**Comment by adityatoshniwal** [comment]
> The problem described by the author of this topic is persistent with every newer version of pgadmin starting with v.8.11. I have the latest versions of browsers for my windows 7. I can not afford upgrade to windows 10 or 11. This leave no chance of using pgadmin.

Hi Mimikoo,

Can you share browser details with version?

**Comment by Mimikoo** [comment]
> > The problem described by the author of this topic is persistent with every newer version of pgadmin starting with v.8.11. I have the latest versions of browsers for my windows 7. I can not afford upgrade to windows 10 or 11. This leave no chance of using pgadmin.
> 
> Hi Mimikoo,
> 
> Can you share browser details with version?

Yes, this is version of Chrome: Version 109.0.5414.120 (Official Build) (64-bit)
Can not update to latest as Im on windows 7.
 Same in Mozilla Firefox 115.25.0esr (32-bit)

**Comment by adityatoshniwal** [comment]
> > > The problem described by the author of this topic is persistent with every newer version of pgadmin starting with v.8.11. I have the latest versions of browsers for my windows 7. I can not afford upgrade to windows 10 or 11. This leave no chance of using pgadmin.
> > 
> > 
> > Hi Mimikoo,
> > Can you share browser details with version?
> 
> Yes, this is version of Chrome: Version 109.0.5414.120 (Official Build) (64-bit) Can not update to latest as Im on windows 7. Same in Mozilla Firefox 115.25.0esr (32-bit)

Hi @Mimikoo,

Unfortunately, your browser versions are quite old. You'll need to upgrade to latest browser.
Also, pgAdmin stopped supporting windows 7 since last many major versions.

**Comment by Mimikoo** [comment]
> > > > The problem described by the author of this topic is persistent with every newer version of pgadmin starting with v.8.11. I have the latest versions of browsers for my windows 7. I can not afford upgrade to windows 10 or 11. This leave no chance of using pgadmin.
> > > 
> > > 
> > > Hi Mimikoo,
> > > Can you share browser details with version?
> > 
> > 
> > Yes, this is version of Chrome: Version 109.0.5414.120 (Official Build) (64-bit) Can not update to latest as Im on windows 7. Same in Mozilla Firefox 115.25.0esr (32-bit)
> 
> Hi [@Mimikoo](https://github.com/Mimikoo),
> 
> Unfortunately, your browser versions are quite old. You'll need to upgrade to latest browser. Also, pgAdmin stopped supporting windows 7 since last many major versions.

Ok, undestand that. This leads to searching other ways to access postgres, as I do not plan for now switching to any newer version of windows. There is no newer version of windows that is friendly to use without ads and other annoying staff.
