### ISSUE TITLE
Schema export from 17rc1 don't work

### ISSUE THREAD

**Issue by fly74** [pgadmin-org/pgadmin4#7969]
Hi Devs,

Schema backup don't work with 17rc1:

```
...\pg_dump.exe --file "...\1.tar" --host "XXX" --port "5432" --username "XXX" --no-password --format=t --large-objects --verbose --schema "xxx" "xxx"

 Start time: Tue Sep 24 2024 17:30:47 GMT+0200 (Mitteleuropäische Sommerzeit)

pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17rc1; pg_dump version: 16.4
```

![image](https://github.com/user-attachments/assets/c413fc92-f8b7-4aa5-b9c1-b5c6e79d31f5)

**Comment by anilsahoo20** [comment]
Hi @fly74,

Please setup the binary path for PostgeSQl v17rc1 in pgAdmin 4>Preferences/Settings...>Paths>Binary Paths>PostgreSQL Binary path.

**Comment by fly74** [comment]
Will it be shipped with the release of 17 with pgadmin?

**Comment by anilsahoo20** [comment]
While you installed the PostgreSQL v17rc1, the binary path is being set. You have to give bin folder path of Postgres v17rc1 by following above mentioned steps.

For example with macOs, this is how you have to enter.
<img width="901" alt="Screenshot 2024-09-25 at 10 44 39 AM" src="https://github.com/user-attachments/assets/cd34f46b-ee76-4241-977c-cdafecefa9c6">

**Comment by akshay-joshi** [comment]
> Will it be shipped with the release of 17 with pgadmin?

It will be shipped after the GA release of PG 17.

**Comment by fly74** [comment]
@akshay-joshi Hi again, PG17 is now released, when will be a version with the included new binaries?

**Comment by akshay-joshi** [comment]
@fly74 

We will check the feasibility and is possible ship with the next release which will be on 17th October.

**Comment by akshay-joshi** [comment]
> @akshay-joshi is the plan still 17th for the new v17 included binaries ?

Yes

**Comment by fly74** [comment]
@akshay-joshi are there problems left, because there is no new release?

**Comment by 6LWa6ZKx** [comment]
> @fly74
> 
> 我们将检查可行性，并可能在 10 月 17 日发布的下一版本中发布。

now not update ?

**Comment by CCdsm** [comment]
> We are planning to release today, but we are facing some issues. Will update you once release is done

Are you still working? I wait for 10 years.

**Comment by 6LWa6ZKx** [comment]
> > We are planning to release today, but we are facing some issues. Will update you once release is done
> 
> Are you still working? I wait for 10 years.

hahaha... metoo

**Comment by yogeshmahajan-1903** [comment]
We have 8.13 release for tomorrow.

**Comment by adityatoshniwal** [comment]
> Are you still working? I wait for 10 years.

_"Wait, have patience, everything will come right in time." - Swami Vivekanand_

**Comment by akshay-joshi** [comment]
> > We are planning to release today, but we are facing some issues. Will update you once release is done
> 
> Are you still working? I wait for 10 years.

Based on my earlier comments, it seems we’re on track to release within a month—hopefully not a 10-year wait! :)
