### ISSUE TITLE
Upgrade to 8.12 cannot access saved passwords

### ISSUE THREAD

**Issue by nooblyf** [pgadmin-org/pgadmin4#7975]
**Describe the bug**

pgadmin is unable to load my saved passwords after upgrading from 8.10 to 8.12, and wants me to enter some master password to migrate my passwords. i don't know what the master password is.

**To Reproduce**

1. install pgadmin 8.10 on arm mac with saved servers with passwords
2. upgrade to 8.12
3. get a 'Migrate Saved Passwords' banner on launch

**Expected behavior**

i shouldn't be seeing this error in the attached screenshot

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

![Screenshot 2024-09-26 at 02 28 25](https://github.com/user-attachments/assets/5c3a0edc-60e6-4b73-9a32-edc9f397880e)

**Desktop (please complete the following information):**
 - OS: macos sonoma 
 - Version: 14.6.1
 - Mode: laptop
 - Browser (if running in server mode): na
 - Package type: dmg

**Comment by yogeshmahajan-1903** [comment]
@nooblyf 
It is master password which you might have set while using earlier version of pgadmin.
If you are okay to loose some saved passwords then can you please click on reset master password? And restart the pgadmin.

**Comment by nooblyf** [comment]
@yogeshmahajan-1903 thanks, is there a way to avoid this in the future?

**Comment by yogeshmahajan-1903** [comment]
@nooblyf 
Hi, This was one time migration which we have done to avoid multiple type entering passwords to unlock saved password in Mac OS key ring. Not expecting this to happen in future.
