### ISSUE TITLE
Pin tabs containing sql queries

### ISSUE THREAD

**Issue by Zapzatron** [pgadmin-org/pgadmin4#7977]
**Describe the solution you'd like**

It would be great to be able to pin tabs containing sql queries, so that you don't have to reopen everything on restart.

**Additional context**

![image](https://github.com/user-attachments/assets/45957c90-fc30-4663-8302-4231854da1c6)
For example, I want the `sales_bot.sql` tab to be open on startup.

**Comment by pravesh-sharma** [comment]
Duplicates #3319
