### ISSUE TITLE
Broken view Data Output as rows

### ISSUE THREAD

**Issue by AJIeksandro** [pgadmin-org/pgadmin4#7978]
pgAdmin, version 8.12 set as docker container (see image)
And see next images for Chromium (right view Data Output as table) and Firefox (broken view Data Output as rows)
It was in 8.11 version too.

![Chromium right view Data Output as table](https://github.com/user-attachments/assets/d54db09a-95cd-4ba0-8731-e8a19617e937)
![Firefox  broken view Data Output as rows](https://github.com/user-attachments/assets/0dff0775-1e79-4a90-b5bc-c254ab1b8bc2)
![pgAdmin version](https://github.com/user-attachments/assets/21a09498-2211-45bc-9a9a-52c078e460b8)

**Comment by pravesh-sharma** [comment]
Duplicates #7846
