### ISSUE TITLE
Docker image missing psycopg2 module

### ISSUE THREAD

**Issue by Da-Teach** [pgadmin-org/pgadmin4#7981]
Version: 8.12.0 from hub.docker.com

When specifying a postgresql external database (using PGADMIN_CONFIG_CONFIG_DATABASE_URI) it will error due to the missing psycopg2 module.

**Comment by pravesh-sharma** [comment]
Hi @Da-Teach,

Duplicates #7973. Please check [comment](https://github.com/pgadmin-org/pgadmin4/issues/7973#issuecomment-2374136717).
