### ISSUE TITLE
Your account is locked

### ISSUE THREAD

**Issue by TechMaster** [pgadmin-org/pgadmin4#7987]
**Error Description:** 
I installed pgadmin4 version 8.12.0 in Docker container. Everything is fine until today, I got this error message

<img width="777" alt="PgAdmin_YourAccountIsLocked" src="https://github.com/user-attachments/assets/3422f6f5-f3a5-4905-b41a-aecc6677222e">

I tried to reset password, delete container, delete mapped volume and create new Docker container again. Error still happens again.

**Environment**
Docker container: dpage/pgadmin4:8.12.0
Host: Ubuntu 18.04 LTS

**Comment by khushboovashi** [comment]
Hi @TechMaster,

You must have entered wrong password 3 times.  You can change the MAX_LOGIN_ATTEMPTS setting into config.py (Ref: https://www.pgadmin.org/docs/pgadmin4/latest/config_py.html) and try.

**Comment by pravesh-sharma** [comment]
No response from the author. Closing the issue.
