### ISSUE TITLE
Desktop application is not visible when double click on title bar.

### ISSUE THREAD

**Issue by RohitBhati8269** [pgadmin-org/pgadmin4#7988]
**Describe the bug**

pgadmin4 desktop application is not visible when double-clicking on the title bar.

**To Reproduce**

1. Open the pgadmin4 desktop application
2. Double Click on the title bar
3. The application goes hide or resized

**Desktop (please complete the following information):**
 - OS: macOS sonoma 14.1 
 - Version: 8.12
 - Mode: Desktop

**Comment by pravesh-sharma** [comment]
Issue fixed, verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-14/).

Env:
OS - macOS 14.7 (Sonoma)
Mode - Desktop
