### ISSUE TITLE
Persistent detail view in Graphical Explain.

### ISSUE THREAD

**Issue by gh-tsc** [pgadmin-org/pgadmin4#7993]
**Describe the bug**

The detail view in [Explain] -> [Graphical] from previous "Explain" is shown after a new "Explain" is ran.

**To Reproduce**

1. Open query tool.
2. Write the query: 'SELECT 22;'
3. Run 'Explain' with the 'Explain' button.
4. Open pane: 'Explain -> Graphical'. Click on 'Result' to open detail of 'Result':
![image](https://github.com/user-attachments/assets/a859b5a5-f078-41ba-8c9d-f231bb3516c5)
5. Remove existing query and write: 'SELECT * FROM (SELECT * FROM UNNEST(ARRAY[22,23])) T;'
6. Run 'Explain' with the 'Explain' button.
7. Open pane: 'Explain -> Graphical'. The Detail view from the first Explain is still showing despite having nothing to do with the new Explain.

**Expected behavior**

The expected behavior is that no detail view is shown after running a new Explain. The problem is that if you ran similar queries, you can be looking a 'Detail view' you think are from the current query, but is actually from a previous query. 

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Version: 8.12
 - Mode: server
 - Browser (if running in server mode): edge
 - Package type: container

**Comment by RohitBhati8269** [comment]
Issue fixed, verified on latest snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-14/).

Env:
OS - macOS 14.1 (Sonoma)
Mode - Desktop
