### ISSUE TITLE
PGAdmin Service Stops Running

### ISSUE THREAD

**Issue by Siphosethu-Sidloyi** [pgadmin-org/pgadmin4#8009]
PGAdmin service stopped running, I was unable to log into my servers. There was no indication that this service had stopped running. I only got a connection timeout when entering my password. After some digging I figured that the service stopped running.

**Comment by pravesh-sharma** [comment]
Hi @Siphosethu-Sidloyi,

Can you please share more details like service name, screenshots and OS details?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
