### ISSUE TITLE
Grid Styling version 8.12 -- rows do not retain shading on scroll

### ISSUE THREAD

**Issue by anthonydb** [pgadmin-org/pgadmin4#8013]
**Describe the bug**

In the new implementation of alternate shading of rows in the Data Output grid, when I scroll through results the shading does not "stick" to a row. Instead, after scrolling a few rows the shading begins to switch rows. 

In other words, the 11th row will alternate between light or dark depending on the scroll position.

This makes it hard to focus on the results.

**To Reproduce**

1. Run a query.
2. Scroll through results.

**Expected behavior**

I would expect that a row shaded light or dark retains that shading when I scroll through results.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version: 8.12 from snapshot build 10/7/24
 - Mode: Desktop

**Comment by anthonydb** [comment]
This looks good in latest snapshot build. Thanks for fixing!

**Comment by pravesh-sharma** [comment]
Issue fixed, verified on latest snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-14/).

Env:
OS - macOS 14.7 (Sonoma)
Mode - Desktop
