### ISSUE TITLE
Issue when registering a new server in pgAdmin4

### ISSUE THREAD

**Issue by Marinades01** [pgadmin-org/pgadmin4#8018]
Hi, can you please help me? I'm trying to register a new server, so that it is possible to remotly access it. I've already made the changes making it reachable, but now a new error appears. 

<img width="721" alt="Screenshot 2024-10-09 alle 11 34 00" src="https://github.com/user-attachments/assets/8b6e5050-bdda-4078-8b56-3e380334ac93">

Do you know how to solve it?

**Comment by khushboovashi** [comment]
@Marinades01, It seems, your server is not reachable.

**Comment by pravesh-sharma** [comment]
No response from the author. Closing the issue.
