### ISSUE TITLE
Missing pgsql-17 tools in latest docker images.

### ISSUE THREAD

**Issue by emmanuelpare** [pgadmin-org/pgadmin4#8022]
Hi, in the latest version (docker image) the binary for pgsql-17 arent included. so pg_dump and pg_restore arent available.

Also at this time the snapshot build appear to be broken

![image](https://github.com/user-attachments/assets/3c4e29ac-7a83-4366-a76b-bbb19832edb6)

**Comment by pravesh-sharma** [comment]
The default binary is set to PG 17, verified on today's docker snapshot [image](https://hub.docker.com/r/dpage/pgadmin4/tags).

**Comment by emmanuelpare** [comment]
All good for me using snapshot. This can be flagged as closed
