### ISSUE TITLE
user mapping permissions not showing

### ISSUE THREAD

**Issue by DavidBuch1** [pgadmin-org/pgadmin4#8023]
A new bug - 

I create a foreign wrapper, and add the user mappings. for each user mapping I create the permissions.
When I create the permissions from the GUI, most of the time its fine. but sometimes, although it "saves" and shows no error, when I then return to the permissions, there is nothing there. If I then try and recreate the same permission I get an error saying it exists.

If I create it from code, I get the same issue.

see screen shot
![Screenshot 2024-10-10 at 13 33 48](https://github.com/user-attachments/assets/9209578d-d585-46f7-b874-b97a11d01216)

**Comment by pravesh-sharma** [comment]
Hi @DavidBuch1,

I am not able to reproduce the issue. Below is the screenshot.

<img width="1221" alt="image" src="https://github.com/user-attachments/assets/b1bbd02a-c2f8-47fc-811b-9e53cee4c6b7">

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
