### ISSUE TITLE
syntax error in edit tool

### ISSUE THREAD

**Issue by hfp-ak** [pgadmin-org/pgadmin4#8028]
pgAdmin 8.12 either Windows or Linux. On "Save Data Changes" a syntax error occurs.

**Steps to reproduce the behavior:**
1. Create table
`
CREATE TABLE IF NOT EXISTS public.x
(
    a character varying(4) COLLATE pg_catalog."default" NOT NULL,
    b integer,
    CONSTRAINT x_pkey PRIMARY KEY (a)
)
`
2. go to edit tools (Alt Shift V)
3. add 2 rows, as shown in screenshot
![edit](https://github.com/user-attachments/assets/2104fe1d-4686-49a8-8798-9e794e54f014)
4. click "Save Data Changes"
5. syntax error occurs

**Expected behavior**

If the edited input is not acceptable, the UI should clearly say that instead of an syntax error

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-11-29/
Package: arm64, pip wheel
Environment: macOs Sonoma 14.7.1
