### ISSUE TITLE
Pgadmin4 launches and you see the splash screen then disappears and nothing launches

### ISSUE THREAD

**Issue by SmittyNole** [pgadmin-org/pgadmin4#8040]
**Describe the bug**

Pgadmin4 launches and you see the splash screen then goes away and nothing launches on Mac OS 15 Sequoia. When i try to open the application pgadmin 4 the splash screen will pop up and say loading then will disappear and the app never actually loads the ui. It appears as if the app is running the icon is in the top right bar. If you try to uninstall it says its running.  You have force close out of it. There is no error that i can see. 

**To Reproduce**
Open Pgadmin4 App
1. Go to 'application/pgadmin4'
2. Click on 'pgadmin4'
3. See the error - no visible error

**Expected behavior**

The Ui should Load when opening the app.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac os 
 - Version: 15 sequoia
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

Ive done a fair bit of troubleshooting. Ive tried deleting the library/pgadmin4 files. Tried uninstalling and installing older versions. Ive tried to install via brew, uninstall via brew then install via pkg file. This does work on other macs running os15 so im not sure if this is an isolated issue.

**Comment by yogeshmahajan-1903** [comment]
pgadmin is best to be tested and supported Sequoia platform

**Comment by samuel-jones-insitro** [comment]
@SmittyNole - I ran into this as well - A workaround I found is to force the application to launch in fullscreen. In the menu bar, when PGAdmin is selected (which it will be after launch) you can go to "View -> Toggle Full screen" which should open the app in a full screen application.

**Comment by adityatoshniwal** [comment]
@yogeshmahajan-1903 What is the pgAdmin version you're using? And from where did you install?

**Comment by SmittyNole** [comment]
Workaround was to force the application to launch in fullscreen.

**Comment by japji25** [comment]
<img width="368" alt="Image" src="https://github.com/user-attachments/assets/8e9fd9a1-a225-4e2e-8be7-7631cdcbf4ae" />

What can we do to run the pgadmin4

**Comment by adityatoshniwal** [comment]
> <img alt="Image" width="368" src="https://private-user-images.githubusercontent.com/210659831/443062266-8e9fd9a1-a225-4e2e-8be7-7631cdcbf4ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDcxMTc0MjcsIm5iZiI6MTc0NzExNzEyNywicGF0aCI6Ii8yMTA2NTk4MzEvNDQzMDYyMjY2LThlOWZkOWExLWEyMjUtNGUyZS04YmU3LTc2MzFjZGNiZjRhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUxM1QwNjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjk0ZTFjNGJmNGM3NmJkNzBkMmQxNmM5OGEwNjc2ZjY3ZjI0MTU0MDcwYjc1ZmE5YzlkN2Q2YjdjYjFlY2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sW93BAD72fNuc4892kIzMNnG8O-LLE7msTAgS-7VTdo">
> What can we do to run the pgadmin4

You're using a very old pgAdmin. Please uninstall pgAdmin and install latest from pgadmin.org.

**Comment by japji25** [comment]
Thank u @adityatoshniwal

**Comment by federicoMoroni-git** [comment]
hover on the pg admin icon on the task bar, hover on the thumbnail , right click, maximize
worked for me
