### ISSUE TITLE
Error while restoring a backup

### ISSUE THREAD

**Issue by automationSele** [pgadmin-org/pgadmin4#8044]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

**To Reproduce**

1. Create a new database 'test1'
2. Create a new schema 'testscheme' in 'test1' and create a single table with a single column type integer.
3. Create a backup with default values through pgadmin4 context menu
4. Create another database 'test2'
5.Restore the backup created at step 3. above through the context menu of the tree with default values on the dialogue.

**Expected behavior**

No error should be shown.

**Error message**

Following is the output 
------------------------------------------------------------
pg_restore: connecting to database for restore
pg_restore: while INITIALIZING:
pg_restore: error: could not execute query: ERROR: unrecognized configuration parameter "transaction_timeout"
Command was: SET transaction_timeout = 0;
pg_restore: creating SCHEMA "testschema"
pg_restore: creating TABLE "testschema.testtable1"
pg_restore: processing data for table "testschema.testtable1"
pg_restore: warning: errors ignored on restore: 1
------------------------------------------------------------

**Screenshots**

![image](https://github.com/user-attachments/assets/f5e27dc1-8c33-45d8-981f-9ae30e184107)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11, Ubuntu 24.04]
 - Version: [8.13 candidate build]
 - Mode: [Desktop ]
 - Browser (N/A]
 - Package type: [Bitrock and APT]

**Additional context**

On both the platforms, PostgreSQL 16.4 was installed

**Comment by pravesh-sharma** [comment]
Hi @automationSele,

Can you please check your default binary path? You can check it here `File -> Preferences -> Binary paths`.
