### ISSUE TITLE
pg_dump is not 17.0 issue

### ISSUE THREAD

**Issue by dffdgdg** [pgadmin-org/pgadmin4#8046]
Backing up an object on the server 'PostgreSQL 17 (localhost:5432)' from database 'TestDB'
Running command:
C:\Program Files\PostgreSQL\17\pgAdmin 4\runtime\pg_dump.exe --file "C:\\Users\\dsasa\\OneDrive\\7496~1\\74AC~1.SQL" --host "localhost" --port "5432" --username "postgres" --no-password --format=c --large-objects --verbose "TestDB"
pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.0; pg_dump version: 16.4

**Comment by 6LWa6ZKx** [comment]
https://github.com/pgadmin-org/pgadmin4/issues/7969#issuecomment-2378481828

**Comment by adityatoshniwal** [comment]
Duplicates #7969
