### ISSUE TITLE
Can't install pgAdmin 4 on Linux Mint by apt - "vera" not exists in ftp

### ISSUE THREAD

**Issue by omer-priel** [pgadmin-org/pgadmin4#8049]
Can't install pgAdmin 4 on Linux Mint - by apt command

**Describe the bug**
`$(lsb_release -cs)` returns `vera`. And
`https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/vera` dos not exits

I followed according to the [downloads](https://www.pgadmin.org/download/pgadmin-4-apt/) page ...
```bash
#
# Setup the repository
#

# Install the public key for the repository (if not done previously):
curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg

# Create the repository configuration file:
sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'

#
# Install pgAdmin
#

# Install for both desktop and web modes:
sudo apt install pgadmin4

# Install for desktop mode only:
sudo apt install pgadmin4-desktop

# Install for web mode only: 
sudo apt install pgadmin4-web 

# Configure the webserver, if you installed pgadmin4-web:
sudo /usr/pgadmin4/bin/setup-web.sh
```

In the end I found the soultion using [https://forums.linuxmint.com/viewtopic.php?p=2308097#p2308097](https://forums.linuxmint.com/viewtopic.php?p=2308097#p2308097) that explain to install manualy.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 21.1
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: APT (Debian)

**Additional context**

[https://forums.linuxmint.com/viewtopic.php?p=2308097#p2308097](https://forums.linuxmint.com/viewtopic.php?p=2308097#p2308097)

**Comment by yogeshmahajan-1903** [comment]
pgadmin does not support  Linux Mint  version. You can view the list of supported platforms [here](https://www.pgadmin.org/download/pgadmin-4-apt/).

**Comment by omer-priel** [comment]
> pgadmin does not support  Linux Mint  version. You can view the list of supported platforms [here](https://www.pgadmin.org/download/pgadmin-4-apt/).

Why?
