### ISSUE TITLE
[Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by em00l** [pgadmin-org/pgadmin4#8066]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

cannot connect to the server with this error message, please help, tried multiple version of postgreSQL

**Error message**

[Errno 8] nodename nor servname provided, or not known

**Comment by yogeshmahajan-1903** [comment]
@em00l 
Can you please provide more descriptions about what error occurring in pgadmin? If possible please share screenshot.

**Comment by dBalag** [comment]
i've tried multiple times, though not having stablished any password as at any moment has been asked during the installation process, when connecting to server i type my desired password with no success.. how can i get the right password?, attached screenshot. 
![Screenshot 2024-10-28 102542](https://github.com/user-attachments/assets/aeeda96f-86d7-49fb-b9de-b90a2b9c4084)

cheers
D

**Comment by yogeshmahajan-1903** [comment]
@dBalag 
Here you need to enter password for postgres server with is you are trying to connect. You must have entered password for while postgres installation setup.

**Comment by akshay-joshi** [comment]
@em00l and @dBalag 

Can you please refer to the old issue and comments here #6959. Not seem to be a pgAdmin issue.
