### ISSUE TITLE
stored passwords cannot be decoded

### ISSUE THREAD

**Issue by ccurvey** [pgadmin-org/pgadmin4#8069]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

Saved password cannot be decoded after restarting PgAdmin

**To Reproduce**

1. Register a server.   Ensure that the password is saved.  Confirm that you can connect to the server
2. Quit PgAdmin
3. Start PgAdmin
4. Click on the server in the tree pane
5. Get error message saying "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 0: invalid start byte"

**Expected behavior**

You should be connected to the server

**Error message**

"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 0: invalid start byte"

(Note that it is always a UnicodeDecodeError, although the byte position may vary.)

**Screenshots**

![image](https://github.com/user-attachments/assets/767aa728-a44b-437f-9c30-9705479ca631)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04, fully patched, Using MATE
 - Version: 8.12
 - Mode: desktop
 - Browser (if running in server mode): n/a
 - Package type: deb

**Additional context**

I thought I had filed this bug report before, but I can't find it anywhere.

**Comment by yogeshmahajan-1903** [comment]
@ccurvey 
Can you please Clear save password from context menu of the server and try saving it again.

**Comment by ccurvey** [comment]
No joy.   I tried clearing and re-saving.  I tried deleting the server connection and re-adding.   Everything works until I restart the program, then I get the decode error.

This is an old machine, it has run many versions of PgAdmin in the past.   I even tried purging PgAdmin from the system and re-installing...but I was very surprised to see my servers available after I re-installed the software.

I can try removing and re-installing again.  Maybe there's some directory or file that I need to manually delete between the removal and installation.

**Comment by akshay-joshi** [comment]
@ccurvey 

Can you please register a new server and try to store the password?
Do you have any non-ASCII characters in the password? 

We need to reproduce this issue.

**Comment by ccurvey** [comment]
No joy

1. Create new server connection. Ensure we want to save the password.  Save the connection.  System connects successfully
2. Disconnect server
3. Reconnect server.  System connects successfully
4. Close PgAdmin4
5. Open PgAdmin4.  
6. Click on new server...get "Failed to decrypt the saved password. Error: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte"

This system is very old, and it has run many versions of PgAdmin...maybe somewhere along the line there's something about the encoding that's weird?

If you can tell me where to find the stored passwords, maybe I can open that up and see what's in there

**Comment by yogeshmahajan-1903** [comment]
@ccurvey 
Can you please list out me the entries in password store(or secret storage application in your machine)?

**Comment by adityatoshniwal** [comment]
> I'd be happy to! Where should I look?

Hi @ccurvey Can you please check the app `PasswordStore` on your system?
