### ISSUE TITLE
Schema Diff Tool: Cannot Produce Difference Script for Index Definition with Where Condition

### ISSUE THREAD

**Issue by canayozel** [pgadmin-org/pgadmin4#8072]
**Describe the bug**

Schema Diff Tool cannot produce difference script for index definition with "where" condition. The tool identifies the difference as "Different" but only cannot produce the difference script.

**To Reproduce**

1. Create 2 database instances and connect them via pgadmin.
2. Run the script below on both instances (create schema & create an example table):
```
   CREATE SCHEMA IF NOT EXISTS test;
   CREATE TABLE IF NOT EXISTS test.test_table (
      id bigint NOT NULL,
      del boolean NOT NULL DEFAULT false,
      ver integer NOT NULL DEFAULT 0,
      name character varying(10)[] NOT NULL,
      status character varying(10)[] NOT NULL,
      CONSTRAINT pk_test_table PRIMARY KEY (id)
);
```
3. Run the script on Instance 1 (create an index with no where condition): 
```
CREATE UNIQUE INDEX IF NOT EXISTS udx_test_table_01 ON test.test_table USING btree (name ASC, status ASC);
```
4. Run the script on Instance 2 (create an index with where condition): 
```
CREATE UNIQUE INDEX IF NOT EXISTS udx_test_table_01 ON test.test_table USING btree (name ASC, status ASC)
    WHERE del = false;
```
5. Open Schema Tool and compare test schemas on both DB instances. 
6. Click on 'test_table' in Objects view and see source, target & difference scripts.

**Expected behavior**

Difference section shall show how to equalize both schemas. (e.g. DROP index and create index from source)

**Screenshots**
![image](https://github.com/user-attachments/assets/2eeb8871-7b09-4063-8564-83cd08ff2dff)

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-12-21/
Package: arm64
Environment: macOs Sonoma 14.7.1
