### ISSUE TITLE
LSOpenURLsWithCompletion

### ISSUE THREAD

**Issue by SakethKanchi** [pgadmin-org/pgadmin4#8079]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
![CleanShot 2024-11-01 at 11 40 42@2x](https://github.com/user-attachments/assets/95edeae6-3648-42e6-a77d-b60b056f31cd)

**To Reproduce**

1. Open PgAdmin

**Error message**
![CleanShot 2024-11-01 at 11 40 42@2x](https://github.com/user-attachments/assets/a77f3ffe-faa2-4ccc-9a60-7fd1ce7a2fc6)

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sequoia
 - Version: [e.g. 6.15]
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by dpage** [comment]
You have not told us the pgAdmin version, or the package type. What are they please? Also, where did you download pgAdmin from?

**Comment by SakethKanchi** [comment]
PG Admin Version: v8.12
Package Type: dmg
I downloaded it from the official [website](https://www.pgadmin.org/download/)

**Comment by ramonmalcolm10** [comment]
Started experiencing this error as well when I updated my macOS to Sequoia 15.1

**Comment by mqignacio** [comment]
I downloaded and installed pgadmin separately with this: [https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.12/macos/](https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.12/macos/).

**Comment by ramonmalcolm10** [comment]
> Started experiencing this error as well when I updated my macOS to Sequoia 15.1

I reinstalled it and that resolved the issue for me.

**Comment by sergiocolombo** [comment]
I reinstalled it, but it didn’t work. Any advice?

**Comment by ramonmalcolm10** [comment]
> I reinstalled it, but it didn’t work. Any advice?

I also run brew update and brew upgrade, not sure if that made any difference.

**Comment by sergiocolombo** [comment]
I managed to solve the problem. I'm not entirely sure if it was the most efficient or correct approach, but now I can use pgAdmin. Here are the steps I followed:

1. I completely uninstalled pgAdmin and the PostgreSQL folder inside the /Library directory.
2. I reinstalled everything from this link: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads (I installed version 16.4, but I believe it should work with other versions as well).
3. After completing the installation (and encountering the same error that prevented me from using the pgAdmin app), I uninstalled the application again, but this time without deleting the previously mentioned folder.
4. I then installed only the pgAdmin application from this link: https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.12/macos/.<br>
<img width="1306" alt="image" src="https://github.com/user-attachments/assets/4498d8e0-1deb-4b0c-92db-b3b6b097c835">
<p>&emsp;&emsp;I downloaded the file pgadmin4-8.12-arm64.dmg</p>
5. Once installed, the application was able to recognize the files in the /Library folder, and I can now use the databases as I did before.
<br>
<img width="241" alt="image" src="https://github.com/user-attachments/assets/6036cfe8-3da3-4a82-b047-f4c1acb1400f"><br><br>

I hope this can be helpful. If I did anything incorrectly, please let me know. Thank you.

**Comment by sergiocolombo** [comment]
I managed to solve the problem. I'm not entirely sure if it was the most efficient or correct approach, but now I can use pgAdmin. Here are the steps I followed:

1. I completely uninstalled pgAdmin and the PostgreSQL folder inside the /Library directory.
2. I reinstalled everything from this link: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads (I installed version 16.4, but I believe it should work with other versions as well).
3. After completing the installation (and encountering the same error that prevented me from using the pgAdmin app), I uninstalled the application again, but this time without deleting the previously mentioned folder.
4. Then I installed only the pgAdmin application from this link: https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.12/macos/.<br>
<img width="1306" alt="image" src="https://github.com/user-attachments/assets/4498d8e0-1deb-4b0c-92db-b3b6b097c835">
<p>&emsp;&emsp;I downloaded the file pgadmin4-8.12-arm64.dmg</p>
5. Once installed, the application was able to recognize the files in the /Library folder, and I can now use the databases as I did before.
<br>
<img width="241" alt="image" src="https://github.com/user-attachments/assets/6036cfe8-3da3-4a82-b047-f4c1acb1400f"><br><br>

I hope this can be helpful. If I did anything incorrectly, please let me know. Thank you.

**Comment by SakethKanchi** [comment]
Doesn't work for me. I just gave up on PGAdmin, started using dbeaver community edition.

> I managed to solve the problem. I'm not entirely sure if it was the most efficient or correct approach, but now I can use pgAdmin. Here are the steps I followed:
> 
> 1. I completely uninstalled pgAdmin and the PostgreSQL folder inside the /Library directory.
> 2. I reinstalled everything from this link: [enterprisedb.com/downloads/postgres-postgresql-downloads](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads) (I installed version 16.4, but I believe it should work with other versions as well).
> 3. After completing the installation (and encountering the same error that prevented me from using the pgAdmin app), I uninstalled the application again, but this time without deleting the previously mentioned folder.
> 4. Then I installed only the pgAdmin application from this link: [postgresql.org/ftp/pgadmin/pgadmin4/v8.12/macos](https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.12/macos/).
> 
> <img alt="image" width="1306" src="https://private-user-images.githubusercontent.com/80453752/382938832-4498d8e0-1deb-4b0c-92db-b3b6b097c835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzQyMTEsIm5iZiI6MTczMDc3MzkxMSwicGF0aCI6Ii84MDQ1Mzc1Mi8zODI5Mzg4MzItNDQ5OGQ4ZTAtMWRlYi00YjBjLTkyZGItYjNiNmIwOTdjODM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDAyMzE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOWIyZmU3ZjMwODQ1YjUzZjdmNDBjYmE5NTczZDJiOTA2MDg5MDk2NjU0ZWU1ZGZlYWQxNzAwOWYwNDYxZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tZVIVz4x0-DCs7RFRicziai-U-OHWW9jvFjIc-btLYc">
>   I downloaded the file pgadmin4-8.12-arm64.dmg
> 
> 5. Once installed, the application was able to recognize the files in the /Library folder, and I can now use the databases as I did before.
> <img alt="image" width="241" src="https://private-user-images.githubusercontent.com/80453752/382940089-6036cfe8-3da3-4a82-b047-f4c1acb1400f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzQyMTEsIm5iZiI6MTczMDc3MzkxMSwicGF0aCI6Ii84MDQ1Mzc1Mi8zODI5NDAwODktNjAzNmNmZTgtM2RhMy00YTgyLWIwNDctZjRjMWFjYjE0MDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDAyMzE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OTgyMDc0ODI3MjM4NTdiZWUxMjljOWQ1OWY3MTQ3MGRjMTVmYTdjYzYxMTdhOTA3YjZjMWNjM2RkNzBhYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fZGnr-MLTBEtt0H_t0KozT0gS8JWqx269BzvgD8VEiE">
> 
> I hope this can be helpful. If I did anything incorrectly, please let me know. Thank you.

**Comment by Marco-0107** [comment]
> I managed to solve the problem. I'm not entirely sure if it was the most efficient or correct approach, but now I can use pgAdmin. Here are the steps I followed:
> 
> 1. I completely uninstalled pgAdmin and the PostgreSQL folder inside the /Library directory.
> 2. I reinstalled everything from this link: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads (I installed version 16.4, but I believe it should work with other versions as well).
> 3. After completing the installation (and encountering the same error that prevented me from using the pgAdmin app), I uninstalled the application again, but this time without deleting the previously mentioned folder.
> 4. Then I installed only the pgAdmin application from this link: https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.12/macos/.
> 
> <img alt="image" width="1306" src="https://private-user-images.githubusercontent.com/80453752/382938832-4498d8e0-1deb-4b0c-92db-b3b6b097c835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjAwMTksIm5iZiI6MTczMDgxOTcxOSwicGF0aCI6Ii84MDQ1Mzc1Mi8zODI5Mzg4MzItNDQ5OGQ4ZTAtMWRlYi00YjBjLTkyZGItYjNiNmIwOTdjODM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE1MTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxOTZjMDEyZmE0ZjVkNTcwMGEyY2ZlYjZkM2FkNTM0OTU3Nzc3OTY5YjVmYTgxYzY4MWY0N2EyNmZkMDEyZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LAmk4gbZ6vdM4Ji3abpO7vnbsf2pamFyyKOXSyo3PEU">
>   I downloaded the file pgadmin4-8.12-arm64.dmg
> 
> 5. Once installed, the application was able to recognize the files in the /Library folder, and I can now use the databases as I did before.
> <img alt="image" width="241" src="https://private-user-images.githubusercontent.com/80453752/382940089-6036cfe8-3da3-4a82-b047-f4c1acb1400f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjAwMTksIm5iZiI6MTczMDgxOTcxOSwicGF0aCI6Ii84MDQ1Mzc1Mi8zODI5NDAwODktNjAzNmNmZTgtM2RhMy00YTgyLWIwNDctZjRjMWFjYjE0MDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE1MTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZmJjNmM4M2EzMWZhZTM4ZWQ2MTU3YjU5Mzk3MjJmOTZmMjQ2OWVlNGI1ZjllMWE1YzA3ZDBjNDdkYzRhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VdKXMYxW7IYIrU8tSNjvif56gHf15r5ODe4XXA_Qrfg">
> 
> I hope this can be helpful. If I did anything incorrectly, please let me know. Thank you.

Thank you for your great contribution, dear friend, I followed your steps to the letter and resolved the error.

**Comment by adityatoshniwal** [comment]
It looks like the issue is with the pgAdmin shipped with PostgreSQL installers, possibly because it may be a old version of pgAdmin which doesn't support MacOS Sequoia. As @sergiocolombo mentioned, uninstall the old pgAdmin version and download/install from the pgAdmin website.
Closing this issue.

**Comment by AskSapa** [comment]
I recently installed pgAdmin 4 on my Mac (Apple Silicon, M4) as part of PostgreSQL 17. However, when I tried to open it, I encountered the following error:

_LSOpenURLsWithCompletionHandler() failed with error -10669.

After troubleshooting various permissions and execution issues, I found that pgAdmin 4 was built for Intel processors, and my Mac needed "Rosetta" to run it.

Solution:

1. Navigate to /Library/PostgreSQL 17/pgAdmin 4/ in Finder.

2. Try to open pgAdmin 4 manually.

3. macOS should prompt you to install "Rosetta" (if it's not already installed).

4. Install "Rosetta" and restart pgAdmin 4.

**Comment by adityatoshniwal** [comment]
> I recently installed pgAdmin 4 on my Mac (Apple Silicon, M4) as part of PostgreSQL 17. However, when I tried to open it, I encountered the following error:
> 
> _LSOpenURLsWithCompletionHandler() failed with error -10669.
> 
> After troubleshooting various permissions and execution issues, I found that pgAdmin 4 was built for Intel processors, and my Mac needed "Rosetta" to run it.
> 
> Solution:
> 
> 1. Navigate to /Library/PostgreSQL 17/pgAdmin 4/ in Finder.
> 2. Try to open pgAdmin 4 manually.
> 3. macOS should prompt you to install "Rosetta" (if it's not already installed).
> 4. Install "Rosetta" and restart pgAdmin 4.

You can uninstall the pgAdmin 4 shipped with PostgreSQL 17 and download Arm based from pgadmin.org.

**Comment by paridahimanshu0610** [comment]
> I managed to solve the problem. I'm not entirely sure if it was the most efficient or correct approach, but now I can use pgAdmin. Here are the steps I followed:
> 
> 1. I completely uninstalled pgAdmin and the PostgreSQL folder inside the /Library directory.
> 2. I reinstalled everything from this link: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads (I installed version 16.4, but I believe it should work with other versions as well).
> 3. After completing the installation (and encountering the same error that prevented me from using the pgAdmin app), I uninstalled the application again, but this time without deleting the previously mentioned folder.
> 4. Then I installed only the pgAdmin application from this link: https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.12/macos/.
> 
> <img alt="image" width="1306" src="https://private-user-images.githubusercontent.com/80453752/382938832-4498d8e0-1deb-4b0c-92db-b3b6b097c835.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjcxMzkzNzIsIm5iZiI6MTc2NzEzOTA3MiwicGF0aCI6Ii84MDQ1Mzc1Mi8zODI5Mzg4MzItNDQ5OGQ4ZTAtMWRlYi00YjBjLTkyZGItYjNiNmIwOTdjODM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjMwVDIzNTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNzAxMjRmYmZkNzNiMzczNjM1ZWJlZTNlZDNkZWU4NTFmOTliODc4ODNhYzVlMWMxMDg2Zjk1ODFmMzMwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WguyxJ7E-uIFZl48vyRmtuTmZE4HUEG0vOcwm_HCSqQ">
>   I downloaded the file pgadmin4-8.12-arm64.dmg
> 
> 5. Once installed, the application was able to recognize the files in the /Library folder, and I can now use the databases as I did before.
> <img alt="image" width="241" src="https://private-user-images.githubusercontent.com/80453752/382940089-6036cfe8-3da3-4a82-b047-f4c1acb1400f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjcxMzkzNzIsIm5iZiI6MTc2NzEzOTA3MiwicGF0aCI6Ii84MDQ1Mzc1Mi8zODI5NDAwODktNjAzNmNmZTgtM2RhMy00YTgyLWIwNDctZjRjMWFjYjE0MDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjMwVDIzNTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMTYwYmY2OWYwY2FkM2NiYjU1MzBjYjUzZmJlN2IxZDgwNWQ0OTgyYjBkYzg5N2UwZTlmYWZlNzFkN2M2MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y2Joo6vUQlSvSUFcaVpQVRbPsEELIxLgnr_UX53GuwM">
> 
> I hope this can be helpful. If I did anything incorrectly, please let me know. Thank you.

Worked for me. Thanks a lot!

**Comment by Santhosh-KS** [comment]
I have used EDB installer approach. Followed the instructions provided  in the official documentation 

https://www.enterprisedb.com/docs/supported-open-source/postgresql/uninstalling/#uninstalling-postgresql-on-mac

to unistall the PGAdmin alone. After that downloaded the dmg file from https://www.postgresql.org/ftp/pgadmin/pgadmin4/v9.11/macos/

And after the manual installation of the above version. PgAdmin is working fine.

**Comment by rahulMishra05** [comment]
> I recently installed pgAdmin 4 on my Mac (Apple Silicon, M4) as part of PostgreSQL 17. However, when I tried to open it, I encountered the following error:
> 
> _LSOpenURLsWithCompletionHandler() failed with error -10669.
> 
> After troubleshooting various permissions and execution issues, I found that pgAdmin 4 was built for Intel processors, and my Mac needed "Rosetta" to run it.
> 
> Solution:
> 
> 1. Navigate to /Library/PostgreSQL 17/pgAdmin 4/ in Finder.
> 2. Try to open pgAdmin 4 manually.
> 3. macOS should prompt you to install "Rosetta" (if it's not already installed).
> 4. Install "Rosetta" and restart pgAdmin 4.


This worked for , thank you!
