### ISSUE TITLE
Fedora 41 Repo

### ISSUE THREAD

**Issue by ChrisBoerner** [pgadmin-org/pgadmin4#8087]
Please add support for Fedora 41 repository.

**Comment by KBeDevel** [comment]
Just an opinion: until this issue is resolved, the [RPM Download page](https://www.pgadmin.org/download/pgadmin-4-rpm/) should remove "Fedora 41" from the supported platforms list.

**Comment by adityatoshniwal** [comment]
> Just an opinion: until this issue is resolved, the [RPM Download page](https://www.pgadmin.org/download/pgadmin-4-rpm/) should remove "Fedora 41" from the supported platforms list.

It says supported from v8.13, no harm in that I believe.

**Comment by KBeDevel** [comment]
> > Just an opinion: until this issue is resolved, the [RPM Download page](https://www.pgadmin.org/download/pgadmin-4-rpm/) should remove "Fedora 41" from the supported platforms list.
> 
> It says supported from v8.13, no harm in that I believe.

The problem appears when the repo is added on Fedora and you try to update packages, for example, on KDE Discover. Upgrade process is broken because the repo link is not being resolved as expected (and KDE will be an official Fedora workstation DE release variant).

**Comment by AlexKovynev** [comment]
it is broken in any distro. When it will created all will be fine. Please be patient :)

**Comment by pravesh-sharma** [comment]
Tested with candidate [build](https://developer.pgadmin.org/builds/2024-11-11-1/yum/). Working fine on Fedora 41
