### ISSUE TITLE
Do not generate foreign key in sql generation

### ISSUE THREAD

**Issue by oopschen** [pgadmin-org/pgadmin4#8089]
**Describe the solution you'd like**
It is better to have an option whether generating foreign key definition.
For some medium application, the best practice is to ignore foreign key for performance and do the constraint in framework level.

**Describe alternatives you've considered**
It is better to have an option whether generating foreign key definition.

**Additional context**

/

**Comment by akshay-joshi** [comment]
@oopschen 

Can you please elaborate more on this feature request by providing some examples?

**Comment by adityatoshniwal** [comment]
No response from the author. Closing.
