### ISSUE TITLE
Empty pgAdmin window MacOS

### ISSUE THREAD

**Issue by michalz-rely** [pgadmin-org/pgadmin4#8090]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
- Empty window on MacOS
- pgAdmin starts showing a welcome screen, then program window never pop out
- Requires force quit

**To Reproduce**
The issue started when moving pgAdmin window from external display to built in display

**Expected behavior**

**Error message**

- No error messages presented
- Uninstalled and reinstalled the package

**Screenshots**
The following is visible, when clicling on pgAdmin icon in doc, and brwosing to "Show All Windows"
![Screenshot 2024-11-05 at 12 26 26](https://github.com/user-attachments/assets/77aea2db-4a44-43fb-b113-afefffa7c52f)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version:  Sonoma 14.4.1
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: pgadmin4-8.12-arm64.dmg
**Additional context**

**Comment by jmealo** [comment]
@michalz-rely: Are you seeing this issue with any other apps? I have this issue with many apps when I dock/undock my M2 MacBook with three external displays. Going from home -> office or office -> home causes windows to stop drawing their contents. It's not limited to a single app, but, I can report that Electron and Java-based (Jetbrains) are most often impacted.

**Comment by michalz-rely** [comment]
@jmealo thank you for the insights.Here's what I have done so far, besides what I mentioned in initial issue

- Disconnected external display
- Reboot
- Force quit Finder and `killall -KILL Dock`
- Reconfigured the resolution of the display
- Updated MacOS to 14.7.1

**Comment by akshay-joshi** [comment]
@michalz-rely 

We have released v8.13 today, so can you please test this behavior once at the latest?

**Comment by michalz-rely** [comment]
@akshay-joshi just installed v8.13 and I confirm it works now!
