### ISSUE TITLE
Right click menus with icons

### ISSUE THREAD

**Issue by chreck** [pgadmin-org/pgadmin4#8096]
**Describe the solution you'd like**

The right click menus you can open in the object explorer do not have any icons. It would help to find the right menu entry if you would provide a pre icon. Below is an example of 2 menu entries with icons, one for copy and one for disconnect server.

![image](https://github.com/user-attachments/assets/156935c7-bf64-4e01-98b1-061a745b542f)

**Describe alternatives you've considered**

There is no other alternative really.

**Additional context**

No additional context.

**Comment by akshay-joshi** [comment]
It affects the performance. So we discourage adding icons.
