### ISSUE TITLE
Schema Diff Tool: Error message is not displayed correctly

### ISSUE THREAD

**Issue by tasaba** [pgadmin-org/pgadmin4#8098]
**Describe the bug**

Schema Diff tool does not display the correct error message when comparing database servers with different major versions.

**To Reproduce**

1. Create one instance each for PostgreSQL 16 and 17.
2. Register both in pgAdmin4.
3. Run Schema Diff tool for each public schema

**Expected behavior**

I get the error message "Source and Target database server must be of the same major version".

**Error message**

I get the error message "[object Object]".

**Screenshots**
![image](https://github.com/user-attachments/assets/60929398-4c4a-4aed-8226-577183e019fc)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.12
 - Mode: Desktop
 - Package type: Installer(https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.12/windows/)

**Comment by pravesh-sharma** [comment]
Issue tested and verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-11-29/) and is fixed.
