### ISSUE TITLE
Cannot see data table when I view/edit a table

### ISSUE THREAD

**Issue by MMeketon** [pgadmin-org/pgadmin4#8099]
First on pgAdmin 4 v8.12, after a few weeks of successfully using the desktop/Windows version, now when I right-click on the table name and do a view/edit (all rows, or first 100 rows; I tried them all), a message returns saying the query successfully ran, but the data table does not show.

I uninstalled v8.12, tried v6.21, and still did not work.  I tried the browser, it did not work.

I turned off the Auto Complete (File/preferences/query tool/auto complete/autocomplete on key press) but that did not help.

**Comment by yogeshmahajan-1903** [comment]
@MMeketon 
Can you please share the pgadmin logs located at %APPDATA%\pgAdmin\pgadmin4.log? Also is it happening for all tables and every time?

**Comment by MMeketon** [comment]
Happens to all the tables.

**Comment by MMeketon** [comment]
Here is a much smaller log file.

I opened up pgAdmin, clicked to get to my tables, did a view/edit of a table.  The contents did not show.  Close pgAdmin.  And this is the log file.

**Comment by yogeshmahajan-1903** [comment]
@MMeketon 
I do not see log file attached or logs.

**Comment by MMeketon** [comment]
I attached them to the reply to the email.

Is there a better way to send them?
________________________________

**Comment by akshay-joshi** [comment]
@MMeketon 

Attach the logs here in the issue itself. Can you please share the screenshot?

**Comment by adityatoshniwal** [comment]
No response from the author. Closing.

**Comment by jcyuan** [comment]
i have solved it, check this out: https://github.com/pgadmin-org/pgadmin4/issues/8993

**Comment by sudhanshu100** [comment]
Situation: you have created the table successfully but you are not able to view/edit the table. Additionally, right side of your window is completely empty which had some stuff initially. ( you have probably closed them all )

Solution: Go to File > Reset layout  , this would restore the default layout which contains the tab responsible for allowing you to view/edit table.
