### ISSUE TITLE
pgadmin 4.8.12 Save data button disabled

### ISSUE THREAD

**Issue by MathiasZaja** [pgadmin-org/pgadmin4#8104]
Right-click on table in the browser window and select View/Edit Data -> (any option)
Edit some data
Save button remains greyed out
Only way to save is to close the window and answer yes to warning dialog to save changed data

**Comment by pravesh-sharma** [comment]
Hi @MathiasZaja,

I think you’ve mistaken the query tool’s save button for the data change save button. Above the result output, there is a toolbar with a button that becomes active once there is a change in the data. You need to press that button to save your changes. Attached screenshot.

<img width="1531" alt="image" src="https://github.com/user-attachments/assets/a79221bf-a3fd-4179-9fad-1db507058390">

**Comment by MathiasZaja** [comment]
Hi Pravesh,
      
      Thanks for your answer and the screenshot.
      
      You are right, sorry for the confusion.
      
      Best regards.
    
    Le 07.11.2024 à 17:24, Pravesh Sharma a
      écrit :
    
    
      
      Hi @MathiasZaja,
      I think you’ve mistaken the query tool’s save button
        for the data change save button. Above the result output, there
        is a toolbar with a button that becomes active once there is a
        change in the data. You need to press that button to save your
        changes. Attached screenshot.
      image.png (view on web)
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
