### ISSUE TITLE
Cannot start pgAdmin 4 after update to Mac OS 15.1 (Sequoia)

### ISSUE THREAD

**Issue by omkarg0** [pgadmin-org/pgadmin4#8112]
Dear pgAdmin Community, 

Ever since I updated my MacBook Air from OS Sonoma to the OS 15.1 (Sequoia), I cannot start pgAdmin 4 from the dock or from the folder where the pgAdmin 4.app is stored via finder. The popup says respectively "The application "Dock"/"Finder" does not have permission to open (null)". Any help would be highly appreciated to get the application running again. I saw a suggestion to update to a new version supporting the OS, but the latest version on the pgAdmin 4 site is Mac OS 14. Is an updated version supporting OS 15.1 planned? If it is planned, by when will it be released?

Below I try to answer your questions: 
**The version of pgAdmin you are running, and where you obtained it from**: pgAdmin 4
**Whether you're running in server or desktop mode:** How can I find out?
**Steps required to reproduce the problem. Please include a simple schema with optional data if required. This may be sent privately upon request from a developer if you are concerned about posting sample code or data to a public mailing list:** trying to Strat from the dock shortcut or from the finder location where the app is saved. Please see the screenshots 1-pgAdmin.png and 2-pgAdmin.png
<img width="735" alt="2-pgAdmin" src="https://github.com/user-attachments/assets/c861b963-531d-4d1c-a051-7007a54c5e39">
<img width="258" alt="1-pgAdmin" src="https://github.com/user-attachments/assets/f3a8733d-da47-4a83-afd8-6cf6656858a6">

**The operating system and version details - e.g. Windows 10, or macOS 10.11.5:** M2 MacBook Air 2022 running Mac OS: 15.1 (24B83)

**Hardware Overview:**

  Model Name:	MacBook Air 2022
  Model Identifier:	Mac14,2
  Model Number:	G1603D/A
  Chip:	Apple M2
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	11881.41.5
  OS Loader Version:	11881.41.5

**Any logfile output you may have. See the FAQ for information on how to [enable logging](https://www.pgadmin.org/faq/#8):** Could not enable, as I could not get the application running.

Thank you very much for any help.

With kind regards, 

Omkar Gopalakrishnan

**Comment by zbxd002** [comment]
I have the same issue. Immediately after upgrading to Sequoia, pgAdmin will not launch. I've attached the error. 
![pgAdmin error](https://github.com/user-attachments/assets/fcee21e1-db52-4d6e-9b61-2a5d3c8876c6)

**Comment by duncand** [comment]
For my part, I'm running MacOS Sequoia 15.0.1 on both Apple Silicon M2 and Intel i7, and the current pgAdmin version launches successfully. I haven't yet tried Sequoia 15.1.

**Comment by duncand** [comment]
@omkarg0 Your picture suggests your pgAdmin 4.app isn't located in the standard /Applications folder. What happens if you try moving it there and then opening it? MacOS security mechanism may deal with apps differently if they have been moved to this location after unpacking rather than being located somewhere else. @zbxd002 What about you, is yours in the /Applications folder or somewhere else?

**Comment by omkarg0** [comment]
@duncand Thank you for your reply and suggestion. I tried moving it to the applications folder, but it still does not start.

**Comment by duncand** [comment]
@omkarg0 So another thing is I used Homebrew / brew to install pgAdmin 4, and that might have done it in a way more likely to work. How did you install it, and maybe try it as I did.

**Comment by adityatoshniwal** [comment]
Hi @omkarg0,
Please uninstall currently installed pgAdmin - I'm guessing it was shipped with PostgreSQL installer. Download the latest from pgAdmin website, it works on Sequoia.
You can also check - #8040.

**Comment by Sahil1722** [comment]
hi @zbxd002 
I am also facing the same issue. please let me know if you found any solution for this.

**Comment by adityatoshniwal** [comment]
> hi @zbxd002 I am also facing the same issue. please let me know if you found any solution for this.

https://github.com/pgadmin-org/pgadmin4/issues/8112#issuecomment-2467218885

**Comment by Sahil1722** [comment]
hi @adityatoshniwal,
After Updating my MacBook Air from OS Sonoma to the OS 15.1 (Sequoia), My pgAdmin is not working. My pgAdmin 4 is stored in folder named as "PostgreSQL 16" in Application folder as you can see in screenshot. As I am clicking on the pgAdmin 4 it does not open and throws an error that "_LSOpenURLsWithCompletionHandler() failed with error -54." as you can see in the screenshot. In previous version of my MacBook it was working fine. After seeing this issue I uninstalled PostgreSQL 16 and again installed the latest version of it called PostgreSQL 17 but issue remains the same then I again restored the PostgreSQL 16 from my bin. because my entire database is stored in PostgreSQL 16. Please resolve this issue as I am unable to work on my project since last 3 days. 

Hardware Overview:

Model Name: MacBook Air 2020
Chip: Apple M2
Total Number of Cores:  8 (4 performance and 4 efficiency)
 Memory: 8 GB


<img width="931" alt="Screenshot 2024-11-11 at 11 58 18 AM" src="https://github.com/user-attachments/assets/6f6503b1-cc51-4f09-873d-93bda2261e20">
<img width="934" alt="Screenshot 2024-11-11 at 11 59 08 AM" src="https://github.com/user-attachments/assets/ee7eabac-9563-49ef-acf1-1183f04acfdc">
<img width="920" alt="Screenshot 2024-11-11 at 11 59 35 AM" src="https://github.com/user-attachments/assets/7ad9db52-7561-435d-926f-967c90230a92">

**Comment by adityatoshniwal** [comment]
@Sahil1722 as I've mentioned in my comment - Download the latest from pgAdmin website.

**Comment by Sahil1722** [comment]
> @Sahil1722 as I've mentioned in my comment - Download the latest from pgAdmin website.

Thank you bro it worked

**Comment by Sahil1722** [comment]
@adityatoshniwal  thank you bro it worked

**Comment by omkarg0** [comment]
Thank you for the quick help, Aditya!

**Comment by nawazzzz** [comment]
![image](https://github.com/user-attachments/assets/a42763b6-b458-47b5-a15e-411e483f47b7)

Updated to macOS sequoia (15.1), redownloaded pgAdmin4 now this popup comes up, old password is not working here
Please guide

**Comment by adityatoshniwal** [comment]
> ![image](https://private-user-images.githubusercontent.com/103118074/384960393-a42763b6-b458-47b5-a15e-411e483f47b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODY4NTAsIm5iZiI6MTczMTM4NjU1MCwicGF0aCI6Ii8xMDMxMTgwNzQvMzg0OTYwMzkzLWE0Mjc2M2I2LWI0NTgtNDdiNS1hMTVlLTQxMWU0ODNmNDdiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwNDQyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjdlYTdhYWI4MzIyOWE2MTkyNDBhMjk3YWE0ZjdiNmIzNjJjZDZiMDY1NWY5YmY3MmNmYTUzMTFmYjQzOWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KRJqVAKY29HxsCVJUHmIaRWimvjECr0-HlCsb9Yj0bk)
> 
> Updated to macOS sequoia (15.1), redownloaded pgAdmin4 now this popup comes up, old password is not working here Please guide

Hi @nawazzzz,
It is asking for your systems password to access keychain. Basically, it is used for saving your server passwords.

**Comment by nawazzzz** [comment]
@adityatoshniwal I tried that but it isn't working, it is something wired

The thing is I reinstalled pgAdmin4 just and moved it to `Applications` folder, while Postgres has been installed at `Application/PostgreSQL 16`

**Comment by adityatoshniwal** [comment]
> @adityatoshniwal I tried that but it isn't working, it is something wired
> 
> The thing is I reinstalled pgAdmin4 just and moved it to `Applications` folder, while Postgres has been installed at `Application/PostgreSQL 16`

In that case, you might be using an older version of pgAdmin which had an issue where the password was asked once for every server. I recommend uninstall the current version and install latest from pgAdmin website.

**Comment by nawazzzz** [comment]
@adityatoshniwal tried that but what worked is adding new entry in keychain like this

![image](https://github.com/user-attachments/assets/052d726e-c8d1-4825-8179-acf455523576)

**Comment by japji25** [comment]
<img width="368" alt="Image" src="https://github.com/user-attachments/assets/1c3d1859-f791-4dfd-9392-48e7f43bed32" />
can somebody help with this.How to resolve this issue

**Comment by ilicaemirhan** [comment]
> Hi [@omkarg0](https://github.com/omkarg0), Please uninstall currently installed pgAdmin - I'm guessing it was shipped with PostgreSQL installer. Download the latest from pgAdmin website, it works on Sequoia. You can also check - [#8040](https://github.com/pgadmin-org/pgadmin4/issues/8040).

To anyone having an issue this works like a charm.

**Comment by abdulaleem01** [comment]
Navigate to this path: /Library/PostgreSQL/17 (replace 17 with your PostgreSQL version) and try starting pgAdmin from there — it worked for me.
