### ISSUE TITLE
Error while opening pgAdmin on macOS

### ISSUE THREAD

**Issue by Santoshchodipilli** [pgadmin-org/pgadmin4#8116]
"_LSOpenURLsWithCompletionHandler() failed with error -54. (1)"

I have attempted several troubleshooting steps, including:

Reinstalling pgAdmin multiple times.
Clearing relevant configuration files and caches.
Ensuring that macOS security settings allow the app to open.
Running the application from the Terminal.
Attempting to reset permissions and using disk utility checks.
Despite these efforts, the error persists and I am unable to launch the application.

Could you please assist me with resolving this issue? If additional logs or details are required from my end, please let me know, and I will be happy to provide them.

Thank you for your support, and I look forward to your response.

**Comment by adityatoshniwal** [comment]
Duplicates  #8079.
