### ISSUE TITLE
Preferences / Query tool / Display / Connection status setting seems to have no effect.

### ISSUE THREAD

**Issue by BjornMoren** [pgadmin-org/pgadmin4#8118]
When running a new query in the query window, two brief green messages show connection status and number of rows affected.

Number of rows affected message can be turned off in the preferences on the same page. Turning off Connection status has no effect, that green message still shows every time.

pgAdmin 8.12 for Windows.

**Comment by khushboovashi** [comment]
Please refer https://www.pgadmin.org/docs/pgadmin4/8.12/query_tool.html#connection-status to understand where the Connection Status preference setting reflects.

Closing the issue.

**Comment by BjornMoren** [comment]
> Please refer https://www.pgadmin.org/docs/pgadmin4/8.12/query_tool.html#connection-status to understand where the Connection Status preference setting reflects.
> 
> Closing the issue.

Thanks for the reply. What you refer to looks like a button you can click on and get information about the connection and transaction status. It doesn't seem very logical that the setting I refer to affects my ability to press that button. Is that really the case?

What I refer to are two green messages that show briefly at the bottom of the window when you run a query. One tells how many rows were affected, and it can be turned off in the settings. The other message can't be turned off, even though there seems to be a setting for it.
