### ISSUE TITLE
Error when I try to open pgAdmin4 on my Mac M1.

### ISSUE THREAD

**Issue by BegicHarun** [pgadmin-org/pgadmin4#8119]
After I updated my macOS to Sequoia 15.1 and I try to open pgAdmin4 it shows this error(image below):
![Screenshot 2024-11-13 at 17 16 59](https://github.com/user-attachments/assets/996c3180-325e-45d5-89fd-bd0dabcecd74)

**Comment by adityatoshniwal** [comment]
Duplicates #8079.
