### ISSUE TITLE
ERD tool constraints not updated

### ISSUE THREAD

**Issue by tdhock** [pgadmin-org/pgadmin4#8120]
Thanks for supporting pgadmin4, which I find useful in my teaching! (IFT187, first year undergrad database class, at Université de Sherbrooke)

Using the ERD tool, I expected the SQL export to always work, without errors, when executing the generated SQL in the Query Tool.

However today I observed using pgadmin4 v8 (cda7d7de90dc3ef6c0c0b482c529584dd891116d 2024-08-20) that some generated SQL resulted in an error.
![image](https://github.com/user-attachments/assets/4d36b23a-660a-4f3c-9ac8-79b68f40deb7)

The problem occurs when you create a primary key constraint (by clicking primary key button in ERD Tool Table window Columns tab), or a foreign key constraint, by clicking the 1M or MM buttons, and then changing the name of the column (in Table window, Columns tab) which is involved with the constraint. The generated SQL then results in an error (column name used to define table is not the same as the column name used in the constraint).

The work-around is to go into the table window, Constraints tab, remove constraints, then re-generate them. After that the generated SQL works (no error).

I expected that the user should not need to use the work around. It would be much more user-friendly if the automatically generated SQL for the constraints could be updated, after the user changes the column name.

**Comment by adityatoshniwal** [comment]
This duplicates #7903.
