### ISSUE TITLE
Unable to open pgadmin 4 after installing the latest version of macOS 15.1

### ISSUE THREAD

**Issue by jur-davidatkinson** [pgadmin-org/pgadmin4#8126]
After updating to the latest version of macOS for m3 mac i have been unable to open pgadmin it throws error code on startup. Had a look online can't really find any information about this issue. Any ideas welcome 

_LSOpenURLsWithCompletionHandler() failed with error -54.

**Comment by adityatoshniwal** [comment]
Duplicates #8079
