### ISSUE TITLE
Query tool prompts for unsaved changes even no changes have been made

### ISSUE THREAD

**Issue by natha1818** [pgadmin-org/pgadmin4#8127]
Same as #5756
Bug is back:

Reproduce issue:

    open Query Tool
    click 'open file' icon and open a file
    -> 'save file' icon in toolbar is highlighted by default even before any changes occurred.
    click 'open file' icon to open another file
    -> prompts for 'Unsaved changes - Are you sure you want to discard the current changes?'

Tested on following config:
PGAdmin version 8.13
OS: Windows 10 Pro version 22H2 (OS build 19045.5131)

**Comment by pravesh-sharma** [comment]
@RohitBhati8269  Found below issue:

If we change the EOL, the save button gets enabled. If any changes are made to the editor and it is reverted to its original state, the save button is disabled, which should not happen as the EOL has changed.

**Comment by natha1818** [comment]
Also, when you open the second file, the file name on the tab doesn't change. When you open a third file, the name of the second file appears on the tab. And so on, always one file name behind.

**Comment by pravesh-sharma** [comment]
@natha1818 I cannot reproduce the issue on the latest version of pgAdmin 4. Which version of pgAdmin 4 you are using?

**Comment by natha1818** [comment]
PGAdmin version 8.13

OS: Windows 10 Pro version 22H2 (OS build 19045.5131)

**Comment by anthonydb** [comment]
I am experiencing this issue on version 8.13 on macOS Sonoma 15.1.1

**Comment by pravesh-sharma** [comment]
Working fine.
