### ISSUE TITLE
PGAdmin won't start on Docker after update to 8.13

### ISSUE THREAD

**Issue by Starstrike** [pgadmin-org/pgadmin4#8133]
Using Docker on Ubuntu 24.04 LTS and just pulled an update from dpage/pgadmin:latest last night. This error is repeating in the logs when trying to start.

```
postfix/postlog: starting the Postfix mail system
[2024-11-14 13:08:06 +0000] [1] [INFO] Starting gunicorn 22.0.0
[2024-11-14 13:08:06 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
[2024-11-14 13:08:06 +0000] [1] [INFO] Using worker: gthread
[2024-11-14 13:08:06 +0000] [83] [INFO] Booting worker with pid: 83
[2024-11-14 13:08:12 +0000] [83] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 103, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/__init__.py", line 754, in create_app
    app.register_blueprint(module)
  File "/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 47, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 595, in register_blueprint
    blueprint.register(self, options)
  File "/pgadmin4/pgadmin/tools/__init__.py", line 52, in register
    from .psql import blueprint as module
  File "/pgadmin4/pgadmin/tools/psql/__init__.py", line 15, in <module>
    from eventlet.green import subprocess
ModuleNotFoundError: No module named 'eventlet'
[2024-11-14 13:08:12 +0000] [83] [INFO] Worker exiting (pid: 83)
[2024-11-14 13:08:13 +0000] [1] [ERROR] Worker (pid:83) exited with code 3
[2024-11-14 13:08:13 +0000] [1] [ERROR] Shutting down: Master
[2024-11-14 13:08:13 +0000] [1] [ERROR] Reason: Worker failed to boot.
```

Please let me know if you need anything else.

**Comment by farewarr** [comment]
I can recreate it too. I posted this as well but didnt realize there was a previous post about it.

**Comment by yogeshmahajan-1903** [comment]
@Starstrike , @farewarr 
We are not able to reproduce the issue. Can you please share your docker command/docker compose yaml ? Also what was previous version of pgadmin?

Error indicates, that code base is not updated to 8.13 code as we have removed eventlet module usage.

**Comment by angmac** [comment]
Same issue here. My docker-compose:
--
services:
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    hostname: pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
      - pgadmin4:/pgadmin4      
      - /usr/lib/locale:/usr/lib/locale:ro
    environment:
      - PGADMIN_DEFAULT_EMAIL=x.y@mail.address
      - PGADMIN_DEFAULT_PASSWORD=XXXXXXXXXX      
      - PGADMIN_DISABLE_POSTFIX=True
      - PGADMIN_LISTEN_PORT=5050
      - TZ=Europe/Budapest      
    ports:
      - 5050:5050
volumes:
  pgadmin:
  pgadmin4:  
--
The dpage/pgadmin4:2024-10-19-2 image works. The dpage/pgadmin4:latest or dpage/pgadmin4:8.13 not working.

**Comment by yogeshmahajan-1903** [comment]
@angmac 
Any reason you have code base mounted on separate volume? I guess updates are not copied to volume and it's causing the issue.

**Comment by angmac** [comment]
I don't remember from where the docker-compose file comes from. Without the pgadmin4:/pgadmin4 volume mapping it works.

**Comment by Starstrike** [comment]
I didn't use compose to build this but used [auto-compose](https://github.com/Red5d/docker-autocompose) to generate this. pgadmin_data is a persistent volume I created. I setup oauth in config.py so if I need to change volume mappings so 8.13 works, I'll need to make sure the oauth stuff will be kept or save it so I can redo it.

```
networks:
  docker-network:
    external: true
    name: "docker-network"
services:
  pgadmin:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "pgadmin"
    entrypoint:
      - "/entrypoint.sh"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=REDACTED"
      - "PGADMIN_DEFAULT_PASSWORD=REDACTED"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PYTHONPATH=/pgadmin4"
    hostname: "51d7a15fd277"
    image: "dpage/pgadmin4:8.12"
    ipc: "private"
    logging:
      driver: "json-file"
      options: {}
    networks:
      - "docker-network"
    ports:
      - "5050:80/tcp"
    restart: "always"
    user: "pgadmin"
    volumes:
      - "pgadmin_data:/pgadmin4"
      - "pgadmin_data:/var/lib/pgadmin"
    working_dir: "/pgadmin4"
volumes:
  pgadmin_data:
    external: true
```

**Comment by Serverfrog** [comment]
Im running this in K8s, only have /var/lib/pgadmin really mounted and also running into this problem.
I dont know if with code base the /pgadmin4 folder is meant or the /var/lib/pgadmin folder. I also just copied it from multiple other repositories which done it that way, so i was thinking it should be the correct one

```
spec:
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: pgadmin-config
    - name: kube-api-access-c5nr7
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  initContainers:
    - name: volume-permissions
      image: >-
        dpage/pgadmin4:8.13@sha256:561c1f8f99f2fe24bc63814db9e30292cf4360331de9182da21e3554ce61bdaa
      command:
        - /bin/chown
        - '-R'
        - '5050:5050'
        - /var/lib/pgadmin
      resources: {}
      volumeMounts:
        - name: config
          mountPath: /var/lib/pgadmin
        - name: kube-api-access-xxx
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
  containers:
    - name: main
      image: >-
        dpage/pgadmin4:8.13@sha256:561c1f8f99f2fe24bc63814db9e30292cf4360331de9182da21e3554ce61bdaa
      env:
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: 'False'
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_PASSWORD
      resources:
        limits:
          memory: 500Mi
        requests:
          cpu: 50m
          memory: 100Mi
      volumeMounts:
        - name: config
          mountPath: /var/lib/pgadmin
        - name: kube-api-access-xxxx
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      livenessProbe:
        tcpSocket:
          port: 80
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        tcpSocket:
          port: 80
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      startupProbe:
        tcpSocket:
          port: 80
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 30
      imagePullPolicy: IfNotPresent
```

**Comment by farewarr** [comment]
Here is also my compose file: 

version: '3.9'
services:  
  db:
    container_name: PostgreSQL
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    hostname: PostgreSQL
    networks:
      - databases_network
    mem_limit: 256m
    cpu_shares: 768
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgresdb", "-U", "root"]
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: postgresdb
      CLASSPATH: /volume1/docker/postgresdb/postgresql-42.7.3.jar:/var/lib/postgresql/data/postgresql-42.5.0.jar:.java MyApp
    volumes:
      - /volume1/docker/postgresql:/var/lib/postgresql/data:rw
    ports:
      - 5444:5432
    restart: on-failure:5
    labels:
      - com.centurylinklabs.watchtower.enable=true
  
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:8.12.0
    networks:
      - databases_network
    cpu_shares: 768
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: 
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    volumes:
      - /volume1/docker/postgresadmin:/var/lib/pgadmin:rw
      - /volume1/docker/pgadmin:/pgadmin4:rw
    restart: on-failure:5
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  databases_network:
    external: true

**Comment by adityatoshniwal** [comment]
One should not mount `/pgadmin4` as it contains the source code of pgAdmin. If you mount it, then the code shipped with docker will not be used.

**Comment by yogeshmahajan-1903** [comment]
> Im running this in K8s, only have /var/lib/pgadmin really mounted and also running into this problem. I dont know if with code base the /pgadmin4 folder is meant or the /var/lib/pgadmin folder. I also just copied it from multiple other repositories which done it that way, so i was thinking it should be the correct one
> 
> ```
> spec:
>   volumes:
>     - name: config
>       persistentVolumeClaim:
>         claimName: pgadmin-config
>     - name: kube-api-access-c5nr7
>       projected:
>         sources:
>           - serviceAccountToken:
>               expirationSeconds: 3607
>               path: token
>           - configMap:
>               name: kube-root-ca.crt
>               items:
>                 - key: ca.crt
>                   path: ca.crt
>           - downwardAPI:
>               items:
>                 - path: namespace
>                   fieldRef:
>                     apiVersion: v1
>                     fieldPath: metadata.namespace
>         defaultMode: 420
>   initContainers:
>     - name: volume-permissions
>       image: >-
>         dpage/pgadmin4:8.13@sha256:561c1f8f99f2fe24bc63814db9e30292cf4360331de9182da21e3554ce61bdaa
>       command:
>         - /bin/chown
>         - '-R'
>         - '5050:5050'
>         - /var/lib/pgadmin
>       resources: {}
>       volumeMounts:
>         - name: config
>           mountPath: /var/lib/pgadmin
>         - name: kube-api-access-xxx
>           readOnly: true
>           mountPath: /var/run/secrets/kubernetes.io/serviceaccount
>       terminationMessagePath: /dev/termination-log
>       terminationMessagePolicy: File
>       imagePullPolicy: IfNotPresent
>       securityContext:
>         runAsUser: 0
>   containers:
>     - name: main
>       image: >-
>         dpage/pgadmin4:8.13@sha256:561c1f8f99f2fe24bc63814db9e30292cf4360331de9182da21e3554ce61bdaa
>       env:
>         - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
>           value: 'False'
>         - name: PGADMIN_DEFAULT_EMAIL
>           valueFrom:
>             secretKeyRef:
>               name: pgadmin-secret
>               key: PGADMIN_DEFAULT_EMAIL
>         - name: PGADMIN_DEFAULT_PASSWORD
>           valueFrom:
>             secretKeyRef:
>               name: pgadmin-secret
>               key: PGADMIN_DEFAULT_PASSWORD
>       resources:
>         limits:
>           memory: 500Mi
>         requests:
>           cpu: 50m
>           memory: 100Mi
>       volumeMounts:
>         - name: config
>           mountPath: /var/lib/pgadmin
>         - name: kube-api-access-xxxx
>           readOnly: true
>           mountPath: /var/run/secrets/kubernetes.io/serviceaccount
>       livenessProbe:
>         tcpSocket:
>           port: 80
>         timeoutSeconds: 1
>         periodSeconds: 10
>         successThreshold: 1
>         failureThreshold: 3
>       readinessProbe:
>         tcpSocket:
>           port: 80
>         timeoutSeconds: 1
>         periodSeconds: 10
>         successThreshold: 1
>         failureThreshold: 3
>       startupProbe:
>         tcpSocket:
>           port: 80
>         timeoutSeconds: 1
>         periodSeconds: 5
>         successThreshold: 1
>         failureThreshold: 30
>       imagePullPolicy: IfNotPresent
> ```

Can you please share container logs? 
Also can you please try to upgrade from 8.11 to 8.12 and check after login check the pgadmin version?

**Comment by Serverfrog** [comment]
@yogeshmahajan-1903 sadly i cant share the logs anymore as already removed the entire deployment and storage and redeployed it, which worked.
But the error was 1:1 the same as above, thats why i even found this github issue.
Due to the fact that this is currently needed, i refrain to downgrade 2 version to test things.
I could look into a little k3d cluster to test this, but i think anybody could do this ;)

**Comment by Starstrike** [comment]
> One should not mount `/pgadmin4` as it contains the source code of pgAdmin. If you mount it, then the code shipped with docker will not be used.

If the config in that folder has been modified for settings like OAuth, that might be why folks, such as myself, would mount that folder. Perhaps I'll need to just need to bind the file itself because, as I thought, as soon as I removed that and pulled 8.13, I lost my OAuth config.

**Comment by yogeshmahajan-1903** [comment]
> @yogeshmahajan-1903 sadly i cant share the logs anymore as already removed the entire deployment and storage and redeployed it, which worked. But the error was 1:1 the same as above, thats why i even found this github issue. Due to the fact that this is currently needed, i refrain to downgrade 2 version to test things. I could look into a little k3d cluster to test this, but i think anybody could do this ;)

I do not expect error to be occurred with config file that you have shared. I have asked to downgrade and upgrade with your environment , because I want to check whether upgrade with older version were successful or not?

**Comment by adityatoshniwal** [comment]
> > One should not mount `/pgadmin4` as it contains the source code of pgAdmin. If you mount it, then the code shipped with docker will not be used.
> 
> If the config in that folder has been modified for settings like OAuth, that might be why folks, such as myself, would mount that folder. Perhaps I'll need to just need to bind the file itself because, as I thought, as soon as I removed that and pulled 8.13, I lost my OAuth config.
> 
> **Edit: I was able to successfully add the OAUTH2 environment variables for the container. v8.13 is working fine for me now after unmounting /pgadmin4.**

You're probably trying to change the config.py file and mount. But config.py should not be changed at all. It will be overridden on every release. Check more on config here - https://www.pgadmin.org/docs/pgadmin4/8.13/config_py.html
You could map a config_local.py to override default config - https://www.pgadmin.org/docs/pgadmin4/8.13/container_deployment.html#mapped-files-and-directories

**Comment by Starstrike** [comment]
> > > One should not mount `/pgadmin4` as it contains the source code of pgAdmin. If you mount it, then the code shipped with docker will not be used.
> > 
> > 
> > If the config in that folder has been modified for settings like OAuth, that might be why folks, such as myself, would mount that folder. Perhaps I'll need to just need to bind the file itself because, as I thought, as soon as I removed that and pulled 8.13, I lost my OAuth config.
> > **Edit: I was able to successfully add the OAUTH2 environment variables for the container. v8.13 is working fine for me now after unmounting /pgadmin4.**
> 
> You're probably trying to change the config.py file and mount. But config.py should not be changed at all. It will be overridden on every release. Check more on config here - https://www.pgadmin.org/docs/pgadmin4/8.13/config_py.html You could map a config_local.py to override default config - https://www.pgadmin.org/docs/pgadmin4/8.13/container_deployment.html#mapped-files-and-directories

That's exactly what I was doing lol. So now I'm using the environment variables instead and all is well.
