### ISSUE TITLE
Provide an option to disable the alternating row colors added in #2874

### ISSUE THREAD

**Issue by rahlquist** [pgadmin-org/pgadmin4#8134]
Would like to suggest an option in the preferences at

File/Preferences/Query Tool/Results grid

To let us disable the alternating row colors in the results grid. 

The new enhancement, while welcome to some, will not be welcomed by all. Visual changes like this really should include an option to opt out or disable it.                                                                                

The originating ticket for the change was https://github.com/pgadmin-org/pgadmin4/issues/2874

Thanks!

**Comment by jon777** [comment]
Original issue #2874 is clearly not tested on themes "Dark" and "High Contrast"

**Comment by andregracioso** [comment]
Yes, please. In dark mode it looks terrible. Very difficult to read and work. The way it used to be was just fine.
So, an option to opt-out this feature would be great. Ideally, the default status should come without alternating row colors. Thanks.

**Comment by develHector** [comment]
I am backing up this request. As a matter of fact, all new visual features should be optional by default. This one, with the dark theme, made me roll back to version 8.12 as it makes reading quite uncomfortable.

**Comment by kittonian** [comment]
After updating to 8.13 I saw this and immediately started looking for an option to turn it off, when I found this request. I too am in favor of all visualization features having an option to turn them off and/or customize them. In my case, I understand the different colors to help separate the data, but with the light color used in the Dark theme it is very difficult to read and I would rather revert back to non-alternating colors as it was just fine.

**Comment by anthonydb** [comment]
While I agree that having an option to turn alternating row colors off would be nice, at the same time I believe the dark mode implementation of the alternating colors could be refined as well. In light mode, the alternating colors are fairly subtle. In dark mode, the difference is pronounced. I wouldn't mind the alternating colors in dark mode if the highlight color was way more subtle.

Ultimately, ability to incorporate third-party themes would be the best solution as in DataGrip. But I realize that's a whole separate issue.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-11-28/
Package: arm64
Environment: macOs Ventura 14.7.1
