### ISSUE TITLE
ssh tunnel with identity file doesn't work on arm

### ISSUE THREAD

**Issue by Beth1708** [pgadmin-org/pgadmin4#8135]
I'm trying to set up pgAdmin to connect to a remote server with an identity file on a M1 Max macbook pro

I have the connection working on an intel mac.  I replicated the setup to the M1 mac, but when I hit save, I get an error message that says:
Unable to connect to server: connection failed: connection to server at "127.0.0.1", port 61435 failed: fe_sendauth: no password supplied.

On the intel mac, pgAdmin prompts me for the password, but it doesn't on the M1 mac.  

I tried it with a key pair that doesn't have a password & it still doesn't work.

The expected behavior is that it will set up the remote server in the server group & I'll be able to see & work with the databases in the remote server (as I can on the intel macbood).

Here's a pic of the error message:
<img width="697" alt="Screenshot 2024-11-15 at 8 47 23 AM" src="https://github.com/user-attachments/assets/eea93d41-138a-4de1-b30a-02bbbb3dcac7">

System:
MacBook Pro (2021), Apple M1 Max chip, Sequoia 15.1

**Comment by Beth1708** [comment]
I tried it with the latest pgAdmin (v 8.13) & one version back (v 8.12) -- neither worked.

**Comment by pravesh-sharma** [comment]
Hi @Beth1708,

I am not able to reproduce the issue (Attached screenshot of my conf). From the error, it seems you have not passed the PostgreSQL server password. Could you let me know if you are providing the server password while registering it? 

<img width="704" alt="image" src="https://github.com/user-attachments/assets/e1924c3a-5852-4cfb-a883-e922c47d1931">

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing the issue.
