### ISSUE TITLE
Error on MAC book Air M2 Chip

### ISSUE THREAD

**Issue by MahaswetaMukherjee** [pgadmin-org/pgadmin4#8140]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

I am running PG admin on my MAC OS. It was all running smooth but suddenly today I can observe this error 

**_LSOpenURLsWithCompletionHandler() failed with error -54. (1)**

I have uninstalled and reinstalled the latest version still facing the same 

<img width="270" alt="Screenshot 2024-11-16 at 4 06 51 PM" src="https://github.com/user-attachments/assets/19281cc9-b3dc-4fd6-b4d2-a1ac4806e5cd">

**Desktop (please complete the following information):**
 - OS: [MAC]
 - Version: [15.1]
 - Mode: [Desktop ]
 - Browser [ safari]

**Comment by adityatoshniwal** [comment]
Duplicates #8079
