### ISSUE TITLE
Startup of PgAdmin/PgAdmin4 is slow when DATA_DIR is redirected to another location in Windows

### ISSUE THREAD

**Issue by rhewy** [pgadmin-org/pgadmin4#8141]
**Describe the bug**

Although the DATA_DIR redirect eventually works, PgAdmin is busy initializing directories and files in %USERPROFILE% before the redirection happens. The location in %USERPROFILE% is not used after the redirect. On a restart of PgAdmin within in the same session the apps launches at a reasonable speed. The initialization of dirs and files happens twice on a new/clean login. 

**To Reproduce**

1. Install PgAdmin4 on Windows
2. Redirect the DATA_DIR in config.py
```Python
if IS_WIN:
    # Use the short path on windows
    DATA_DIR = os.path.realpath(
        os.path.join(fs_short_path('H:'), APP_WIN_PATH)
    )
```
3. Check %USERPROFILE% for **PgAdmin4**
4. Check the redirected directory for **PgAdmin**

*The directories have slightly different names BTW*

**Expected behavior**

If a redirect is valid, then directories and files should not be created in %USERPROFILE% and the settings directory should have the same name.

**Error message**
There is no error message on a good run, just a delayed startup. However, occasionally It does take too long and PgAdmin gives up on staring.
![image](https://github.com/user-attachments/assets/021d3926-ccb9-4586-9b80-65b601d3e9a7)

**Screenshots**
Config.py
![image](https://github.com/user-attachments/assets/299e4365-a635-490a-a072-3f293bcc2826)

%USERPROFILE%
![image](https://github.com/user-attachments/assets/2601075a-4196-4b75-bb01-6131645e8464)

DATA_DIR
![image](https://github.com/user-attachments/assets/f57e1c85-5824-4bdf-9f55-286c2339dd30)

**Desktop Info:**
 - OS: Windows 11
 - Version: Microsoft Windows [Version 10.0.22631.4169]
 - Mode: Apporto Desktop (cloud desktop)
 - Browser NA
 - Package type: Download from PgAdmin website (windows 8.13) 

**Additional context**
The profiles are not Roaming or 100% Roaming and we have to redirect the app settings to a more permanent location. If there is a better way let me know. This could also be a feature request where settings could be stored in in a different location for a user e.g a home drive that is separate from c:\users.

**Comment by adityatoshniwal** [comment]
Hi @rhewy,

There will be two directories here:
1. pgAdmin config data and logs. (DATA_DIR)
2. Cache directory created by the Electron container which wraps pgAdmin for desktop.

It is completely safe to remove the 2nd (electron) directory as it is just a cache and will be re-created. But the 1st directory(DATA_DIR) will have your server config and other pgAdmin settings. You'll lose if you remove that dir.

**Comment by rhewy** [comment]
Is there any way to prevent the files and directories (pgAdmin/pgAdmin4) from being recreated/reinitialized in %USERPROFILE% if they already exist in DATA_DIR?

**Comment by adityatoshniwal** [comment]
> Is there any way to prevent the files and directories (pgAdmin/pgAdmin4) from being recreated/reinitialized in %USERPROFILE% if they already exist in DATA_DIR?

Unfortunately no, the purpose of both the directories is different as I mentioned above.

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing the issue.
