### ISSUE TITLE
Partial selection of text in results grid always copies full text. V8.13

### ISSUE THREAD

**Issue by Customerology** [pgadmin-org/pgadmin4#8150]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

If you double-click on a cell in the results grid that contains text or JSON values, you can select a portion of the displayed text. However, clicking ctrl-c always results in the complete value of the cell being copied to the clipboard instead of just the selected/highlighted text. The behavior between JSON edits and text edits is different regarding the context menu. In a text cell, if you right-click on the highlighted text you are presented with a context menu that has cut/copy/paste/etc options available and using cut or copy from the context menu does correctly place the highlighted text in the clipboard. However in a JSON cell the presented window with the JSON content shows the character count of text as it is being selected but when the context menu is displayed the cut and copy options are greyed out. Pressing ctrl-C places the entire JSON in the clipboard. Note: pressing the delete key correctly removes only the highlighted text.

**To Reproduce**

1. Execute a query that produces columns with regular text and Json(b)
2. double click on a text or json cell and highlight a portion of the displayed text.
3. if in a json cell, invoke the context menu (right-click) and observe that cut/copy are not available.
4. Press ctrl-c.
5. Go to another window that will accept text and paste the clipboard contents there via ctrl-v etc.
6. Note that the entire content of the source cell is pasted, not just the highlighted text

**Expected behavior**

Only the highlighted text should be placed on the clipboard via ctrl-c. Also in the Json edit window the cut/copy options should be enabled in the context menu when text has been highlighted.

**Error message**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2
 - Version: pgAdmin4 v8.13
 - Mode: Desktop
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: Windows Installer

**Additional context**

**Comment by anilsahoo20** [comment]
Hi @Customerology 
I can confirm, ctrl+c copying the whole content but not the highlighted or selected content.

But the step-3 you mentioned, My context menu shows cut, copy, paste, select all options, attached screenshot for reference.
<img width="434" alt="Screenshot 2024-11-20 at 10 32 25 AM" src="https://github.com/user-attachments/assets/15c7a176-70f4-4e2c-8c4f-ff23459da941">
<img width="246" alt="Screenshot 2024-11-20 at 10 32 52 AM" src="https://github.com/user-attachments/assets/0550be17-c185-4b7b-ab0f-ba9b95c451f6">
