### ISSUE TITLE
macOS Keychain access windows always appear even when "Alway allow" clicked or "Allow" clicked multiple times

### ISSUE THREAD

**Issue by rmohammed-xtime** [pgadmin-org/pgadmin4#8151]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Keychain access windows always appear even when "Always allow" clicked or "Allow" clicked multiple times and do not go away. The initial window goes away when the password is entered and a new window appears no matter how many times when "Always allow" or "Allow" is clicked.

**To Reproduce**

Install and open pgAdmin 4 v8.13 or v8.12. The problem does not exist when installing and opening v8.11.

**Expected behavior**

The keychain access window should go away

**Error message**

N/A

**Screenshots**

![pgAdmin4](https://github.com/user-attachments/assets/97e5ac38-c955-47d1-ae81-778ebafab607)

**Desktop (please complete the following information):**
 - OS: macOS Sequoia
 - Version: 15.1
 - Mode: Desktop
 - Browser (if running in server mode): N/A
 - Package type: DMG

**Additional context**

I upgraded from v8.0

**Comment by anilsahoo20** [comment]
Hi @rmohammed-xtime 
Please check this [comment](https://github.com/pgadmin-org/pgadmin4/issues/7076#issuecomment-2481922762)

Related to #7076
