### ISSUE TITLE
when I was trying to open the pgadmin 4 the below error message was observed 

### ISSUE THREAD

**Issue by mbuny** [pgadmin-org/pgadmin4#8152]
<img width="1440" alt="Screenshot 2024-11-19 at 2 57 45 PM" src="https://github.com/user-attachments/assets/824c7bb0-f1c8-4bda-9511-cb12eccb1c43">

**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by pravesh-sharma** [comment]
Duplicates #8079
