### ISSUE TITLE
Restore tool not working since update 8.13

### ISSUE THREAD

**Issue by itcan1** [pgadmin-org/pgadmin4#8153]
I have been using PGadmin to manage my databases for more than 2 years so I am not new to how pgAdmin works.

I usually make a backup of a DB using PGadmin.
Then I restore that database to a "test DB" which I use for testing new features etc. The Database is a standard schema with no special functions etc.
Last week it worked perfectly as it has for years.

Yet after updating to version 8.13 for 64 bit the Restore Process fails every time, and I am doing exactly what I have always been doing.

So, either the Backup tool is causing a bad backup or the Restore tool is the problem.

**Comment by pravesh-sharma** [comment]
Hi @itcan1,

Can you please share your database version? Also, can you share the OS details?

**Comment by itcan1** [comment]
Thank you for the quick response.

 

I think PostgreSQL on the Server is version 10.0.1 and the server is running Windows 2016 – it’s a VPS provided through an external company.

The system I am working on is Windows 10 but I tested on a Windows 11 machine and got the same result.

Its definitely related to the last PGAdmin update. This morning I installed the previous version on another Windows 10 PC and the Backup and Restore works perfectly.

 

Regards,

Russel.

**Comment by pravesh-sharma** [comment]
@itcan1,

PostgreSQL 10 is a very old version and is no longer supported. Also, pgAdmin 8.13 ships PostgreSQL 17 binaries which might be causing issues. Please check the process logs from the processes tab. You can set default binaries from `File -> Preferences -> Paths -> Binary paths`

**Comment by itcan1** [comment]
Thank you Pravesh.

 

Hope you don’t mind if I pick your brain but….

 

1.	Are there any issues if I upgrade the PostgreSQL on the Server to release 17.1?
2.	If not, is it a simple matter of running the new installation on the Server?
3.	Do you perhaps have a suggestion for me on what version I should upgrade to

 

Regards,

Russel.

**Comment by pravesh-sharma** [comment]
@itcan1,

I suggest using the latest version. There should not be any issues with upgrading to a new version or you can run a new installation as well.

**Comment by adityatoshniwal** [comment]
Closing this as PGv10 is not supported by pgAdmin.

**Comment by RCatersels** [comment]
I see the same with PostgreSQL 14. Reverting back to the 8.12 and all started working again. So I think there is more going one here.

**Comment by itcan1** [comment]
I just uninstalled 8.13 and reinstalled 8.12 and its working perfectly.

 

Having said that, I tried upgrading my PostgreSQL v10 that is running on the
Server to version 17 and its not a simple tasks and the PG Admin that
installs during the process does not startup. No matter what I do it keeps
kicking me to the Configuration screen after 2 minutes or so.

 

You have a nice day.

**Comment by pravesh-sharma** [comment]
@itcan1 I suggest downloading pgAdmin from [here](https://www.pgadmin.org/download/).
