### ISSUE TITLE
Wide columns in Data Output are always just a few pixel too small

### ISSUE THREAD

**Issue by riuttner** [pgadmin-org/pgadmin4#8158]
If a select result contains a data column wider than the internal minimum default, the result is always truncated by a few pixels. This effect is visible when selecting something like the following string literal:
`select '[10001, 20002, 30003, 40004, 50005, 60006, 70007, 80008, 90009]'`

![grafik](https://github.com/user-attachments/assets/87c93d06-3d6d-44db-b97c-5d130fdfc85b)

which is truncated also when the same string is casted to JSON(B):

![grafik](https://github.com/user-attachments/assets/ea554991-8787-4344-8551-994e75fa55e2)

Thus the effect is independent of output formatting. As it seems to me, the column size computation just misses the left padding offset and thus always recognizes that it has to truncate the contents and show an ellipsis. This in fact always hides the last character only. I have been observing this behaviour since more than a year already.

Tested with
Version
8.13
Application Mode
Desktop
Commit:
b2782650055dd41c060cd016f29ecd5575cd1828 2024-11-11
Current User
pgadmin4@pgadmin.org
Electron Version
33.2.0
Browser
Chrome 130.0.6723.118
Operating System
Windows-10-10.0.19045-SP0

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-11-29/
Package: arm64, pip wheel
Environment: macOs Sonoma 14.7.1
