### ISSUE TITLE
Cannot redefine keyboard shortcut for text replace in Query Tool

### ISSUE THREAD

**Issue by ish1mura** [pgadmin-org/pgadmin4#8170]
### Expected behavior

1 ) I open "search dialog" in "Query Tool" with keyboard shortcut "Ctrl+F" (it works)
2 ) I want to redefine opening "search and replace dialog" in "Query Tool" with keyboard shortcut "Ctrl+H" or "Ctrl+Shift+F", but dialog always opens with shortcut "Ctrl+Alt+F" and I cannot change it

### Reproducing

1 ) Open "File -> Preferences -> Query Tool -> Keyboard shortcuts"
2 ) Change "Filter dialog" from "Ctrl+Alt+F" to "Ctrl+Shift+F" or "Ctrl+H" and press "Save"
3 ) Open "Ouery Tool"
4 ) Press "Ctrl+Shift+F" -> "search and replace dialog" doesn't open
5 ) Press "Ctrl+Alt+F" -> "search and replace dialog" opens despite shortcut setting (I think its hardcoded)

Probably "Filter dialog" setting is not intended for redefining hotkey of "search and replace dialog".
In that case it is necessary to add shortcut for opening "search and replace dialog" in "Preferences". I think many of users want to redefine that hotkey.

### Environment

 - **OS**: Ubuntu Server 24.04
 - **Version**: 8.13
 - **Mode**: Server
 - **Browser**: Chrome, Firefox
 - **Package type**: DEB and Docker

### Screenshots

![image](https://github.com/user-attachments/assets/5dbb7aea-0391-460e-8f07-615caa53b682)

![image](https://github.com/user-attachments/assets/96f48b5d-fa2b-4528-8aa6-9c1d5b0fcbbb)

![image](https://github.com/user-attachments/assets/72b0cde3-5eed-465d-9cb3-d025d9acd455)

**Comment by khushboovashi** [comment]
Duplicates #2659.
