### ISSUE TITLE
Restoring of the backup failed on SET transaction_timeout = 0;

### ISSUE THREAD

**Issue by olisom** [pgadmin-org/pgadmin4#8171]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

unable to restore a database on the same server

**To Reproduce**

1. Go to object explorer
2. Right click on DataBases > Create
3. Add a 'my_test' database
4. In the left panel, navigate to 'my_test' > 'Schemas' > 'public' >Tables
5. Right click 'Create > table...' and  add a new table 'my_table' with a column 'my_column' (data type= integer)
6. Navigate to 'my test' and select 'Backup...', Select 'my_file.dump' as filename (format = Custom) and click on backup Button
7. Delete (force) 'my_test' database
8. Recreate a 'my_test' database, click the Save button
9. Right click on 'my_test' > 'Restore...' , select the file created in step 6 and click the Restore button
10. => Process failed

**Expected behavior**

Successful database restoration

**Error message**
Restoring backup on the server 'localhost (localhost:5432)'
Running command:
/Applications/pgAdmin 4.app/Contents/SharedSupport/pg_restore --host "localhost" --port "5432" --username "postgres" --no-password --dbname "my_test" --verbose "/Users/me/Desktop/my_file.dump"

pg_restore: connecting to database for restore
pg_restore: while INITIALIZING:
pg_restore: error: could not execute query: ERROR: unrecognized configuration parameter "transaction_timeout"
Command was: SET transaction_timeout = 0;
pg_restore: creating SCHEMA "public"
pg_restore: creating TABLE "public.my_table"
pg_restore: processing data for table "public.my_table"
pg_restore: creating ACL "SCHEMA public"
pg_restore: warning: errors ignored on restore: 1

**Screenshots**

see: https://github.com/pgadmin-org/pgadmin4/issues/8044

**Desktop (please complete the following information):**
 - OS: OSX monterey
 - Version: 12.6.3
 - Mode: Desktop

**Additional context**

pg_dump --version 
pg_dump (PostgreSQL) 13.18 (Postgres.app)
pg_restore --version
pg_restore (PostgreSQL) 13.18 (Postgres.app)

similar issues were already reported:
https://dba.stackexchange.com/questions/244547/pg-restore-error-while-initializing-closed

https://github.com/pgadmin-org/pgadmin4/issues/8044

**Comment by pravesh-sharma** [comment]
Hi @olisom,

Please check this [comment](https://github.com/pgadmin-org/pgadmin4/issues/8044#issuecomment-2436821077). It is not a pgAdmin issue you need to set the default binaries compatible with your PostgreSQL version. You can set binaries from `pgAdmin 4 -> Settings -> Binary Paths`.

**Comment by ademir10** [comment]
> **_Please note that security bugs or issues should be reported to [security@pgadmin.org](mailto:security@pgadmin.org)._**
> 
> **Describe the bug**
> 
> unable to restore a database on the same server
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Go to object explorer
> 2. Right click on DataBases > Create
> 3. Add a 'my_test' database
> 4. In the left panel, navigate to 'my_test' > 'Schemas' > 'public' >Tables
> 5. Right click 'Create > table...' and  add a new table 'my_table' with a column 'my_column' (data type= integer)
> 6. Navigate to 'my test' and select 'Backup...', Select 'my_file.dump' as filename (format = Custom) and click on backup Button
> 7. Delete (force) 'my_test' database
> 8. Recreate a 'my_test' database, click the Save button
> 9. Right click on 'my_test' > 'Restore...' , select the file created in step 6 and click the Restore button
> 10. => Process failed
> 
> **Expected behavior**
> 
> Successful database restoration
> 
> **Error message** Restoring backup on the server 'localhost (localhost:5432)' Running command: /Applications/pgAdmin 4.app/Contents/SharedSupport/pg_restore --host "localhost" --port "5432" --username "postgres" --no-password --dbname "my_test" --verbose "/Users/me/Desktop/my_file.dump"
> 
> pg_restore: connecting to database for restore pg_restore: while INITIALIZING: pg_restore: error: could not execute query: ERROR: unrecognized configuration parameter "transaction_timeout" Command was: SET transaction_timeout = 0; pg_restore: creating SCHEMA "public" pg_restore: creating TABLE "public.my_table" pg_restore: processing data for table "public.my_table" pg_restore: creating ACL "SCHEMA public" pg_restore: warning: errors ignored on restore: 1
> 
> **Screenshots**
> 
> see: #8044
> 
> **Desktop (please complete the following information):**
> 
> * OS: OSX monterey
> * Version: 12.6.3
> * Mode: Desktop
> 
> **Additional context**
> 
> pg_dump --version pg_dump (PostgreSQL) 13.18 (Postgres.app) pg_restore --version pg_restore (PostgreSQL) 13.18 (Postgres.app)
> 
> similar issues were already reported: https://dba.stackexchange.com/questions/244547/pg-restore-error-while-initializing-closed
> 
> #8044

did you fix it?
I'm facing the same problem..
after to change my Bin path to the last version 17 i still have the same problem..

**Comment by ademir10** [comment]
Any suggestion guys? i'm facing the same problem..

<img width="705" alt="Captura de Tela 2024-12-12 às 09 46 59" src="https://github.com/user-attachments/assets/fee94f38-f0b4-4698-b5ff-ae92c036c313" />
<img width="907" alt="Captura de Tela 2024-12-12 às 09 47 20" src="https://github.com/user-attachments/assets/8ec01b34-43fb-460a-ba71-4e4b692db79b" />

**Comment by khushboovashi** [comment]
@olisom, Looks like, PostgreSQL and pg_restore versions are not same. Try running the same command through the command line and check.

**Comment by Muhammad-Saad12** [comment]
I encountered the same problem while transferring the data form one DB to another. Both source and target DB were using v16 and PgAdmin was using v17. I solved this problem by downloading the PgAdmin v16 to and it solved my problem . You can download from [here](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads)

**Comment by Muhammad-Saad12** [comment]
I encountered the same problem while transferring the data form one DB to another. Both source and target DB were using v16 and PgAdmin was using v17. I solved this problem by downloading the PgAdmin v16 to and it solved my problem . You can download from [here](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads)

**Comment by kiwavi** [comment]
I was facing this issue on my Archlinux installation. Solved by ensuring postgresql-libs version is compatible with postgres version.
