### ISSUE TITLE
Cannot copy selected text in jsonb field,

### ISSUE THREAD

**Issue by DanielPiersonLN** [pgadmin-org/pgadmin4#8184]
**Describe the bug**

On Windows, If I highlight some text in a jsonb filed and use ctrl-c I get the entire field value rather than just the selected text.  Right-click menu has an option for copy but it is disabled.

**To Reproduce**

1. Go to Query window
2. Run a query where results contain a jsonb field.
3. Double click jsonb field to invoke edit widnow
4. Highlight some text
5. CTRL + C
6. Open Notepad
7. Paste into notepad

**Expected behavior**
- only the text that was selected in the jsonb field is pasted.

Repeat 1 - 4
5. Right click selected text

**Expected behavior**
- Copy menu option should be enabled.

**Screenshots**

![image](https://github.com/user-attachments/assets/02c0d619-5cf9-42ed-b97f-890816f8d8ef)

**Desktop (please complete the following information):**
 - OS: Operating System Windows-11-10.0.22631-SP0
 - Version: 8.13
 - Mode: Desktop
 - Commit: b2782650055dd41c060cd016f29ecd5575cd1828 2024-11-11
 - Electron Version 33.2.0
 - Browser Chrome 130.0.6723.118

**Comment by adityatoshniwal** [comment]
Duplicates #8157.

**Comment by DanielPiersonLN** [comment]
HI @adityatoshniwal .  I see that this ticket was closed as duplicate, but the referenced ticket isn't exactly what I'm describing here.  The referenced ticket talks about incorrect quoting.  My ticket refers to copying only the selected text.

eg:  if the jsonb field has 

{
	"firstname": "Dan",
	"lastname": "Pierson"
}

and I highlight just "Pierson", I'd expect when I copy with CTRL+C, that only "Pierson" would be copied.  Instead, I'm getting the entire value for the jsonb field.
