### ISSUE TITLE
Add support for tags on a server node

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#8192]
**Describe the solution you'd like**
We have a requirement where we need to tag servers with some labels. Tags allow adding extra info without renaming the server. It can also be helpful when adding shared servers. In future, it can be helpful as a filter criteria. If you agree then I can create a git issue.

**Additional context**
Below is a sample:
<img width="353" alt="Screenshot 2024-11-28 at 15 44 28" src="https://github.com/user-attachments/assets/dbc75033-1e29-4b93-9620-ef97e8c0eaf1">

**Comment by zaidshabbir22** [comment]
Hello,

It's a nice visual feature. I would like to suggest adding labels with color coding, as it would make it easier for users to quickly identify items from a long server list.

Secondly, we need to define a policy regarding the maximum number of labels and the case sensitivity of labels that can be associated with the server.

Regards,
Zaid

**Comment by adityatoshniwal** [comment]
@zaidshabbir22 ,

I agree with colors, we could add that. I can also add one backend config variable for max number of labels if that helps.
But I'm not sure how cases sensitivity will help. I've never seen for tags.

**Comment by anilsahoo20** [comment]
Tested the feature for adding tags to a server with color and also import export of a server persisting the tags.
Tested on macOs Sonoma 14.7.1 with arm64 build

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-12-09/
Environment: macOs Sonoma 14.7.1
Package: arm64 and python

**Comment by usman-muzaffar555** [comment]
Can we exclude tags from selection of background color for server, it makes it less relavent?
![image](https://github.com/user-attachments/assets/bdfbf313-bd5e-420e-8fb3-98209b2c2dcd)

**Comment by adityatoshniwal** [comment]
> Can we exclude tags from selection of background color for server, it makes it less relavent?

The tags background is slightly transparent. May be that is the reason it looks that way. We can remove that in future release to make it look better.
