### ISSUE TITLE
Query Tool Menu Item Disabled in Latest Snapshot Build

### ISSUE THREAD

**Issue by anthonydb** [pgadmin-org/pgadmin4#8206]
In the 11/29/24 snapshot build, the Query Tool menu item is disabled.
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-11-29/

**To Reproduce**

1. Connect to a server.
2. Click on a database name in the Object Explorer.
3. Click Tools menu. 

**Expected behavior**

At this point, I would expect to see the Query Tool item available. It is not.

However, I can access the Query Tool by right-clicking the database name and selecting Query Tool from the pop-up menu.

**Desktop (please complete the following information):**
 - OS: macOS Sequioa 15.1.1
 - Version: 8.13 latest snapshot
 - Mode: Desktop

**Comment by pravesh-sharma** [comment]
Hi @anthonydb,

Can you try on this [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-11-30/)? We have fixed the issue.

**Comment by anthonydb** [comment]
@pravesh-sharma Yes, it is fixed! Thank you.
