### ISSUE TITLE
Not able to download PostgreSQL pgadmin4

### ISSUE THREAD

**Issue by wc4now** [pgadmin-org/pgadmin4#8207]
November 29 2024

Computer is a mac M2 Sequoia 15.1.1

Version of pgadmin4 that won't download from site https://www.pgadmin.org/download/pgadmin-4-macos/ is [pgAdmin 4 v8.13](https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.13/macos/) (released Nov. 14, 2024)

Looking for specific instructions of "How to download" the app into the PostgreSQL 17 folder in the applications folder.

Thanks

**Comment by yogeshmahajan-1903** [comment]
@wc4now 
Can you please share the error for downloading the installer from https://www.pgadmin.org/download/pgadmin-4-macos/ 
If you download from [here](https://www.pgadmin.org/download/pgadmin-4-macos/), then its dmg file on which you need to double click and drag to applications folder.

**Comment by yogeshmahajan-1903** [comment]
As per email , closing the ticket.
```
Hey Yogesh

 

I'm not clear on what happened but I reinstall PostrgeSQL 17. I checked off the PGAdmin 4 in the process.

 

Voila, the reinstall somehow updated PGAdmin 4 to version 8.13.

 

Problem solved. I guess I just needed a solid support behind me. Thanks so much for getting involved. Greatly appreciated.

 

thanks 
```
