### ISSUE TITLE
"Something went wrong" when trying to change text in "Code" tab

### ISSUE THREAD

**Issue by dangelsaurus** [pgadmin-org/pgadmin4#8209]
When trying to change text in the code tab, of say a materialized view...
Right Click -> Properties -> Code
After typing a few characters, the screen clears and I get a "Something Went Wrong"

Editing code
![image](https://github.com/user-attachments/assets/b4580a5f-396b-44ca-b773-ea274e68a42a)

Then after a few key strokes
![image](https://github.com/user-attachments/assets/ebcba643-69b2-4240-97b9-013caca072b2)

About...
![image](https://github.com/user-attachments/assets/5aaf6bcc-3e32-4704-a8a3-1f520f6b976d)

And console error when run in browser...
![image](https://github.com/user-attachments/assets/1dc072df-00e6-4972-a444-f8afbdd1c7bf)

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-12-21/
Package: arm64
Environment: macOs Sonoma 14.7.1
