### ISSUE TITLE
doing `Cmd+C` on a text selection copies the whole thing and wraps it in double quotes

### ISSUE THREAD

**Issue by nooblyf** [pgadmin-org/pgadmin4#8213]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

if there's an entry in the database i try to copy, i select it and hit cmd+c, first it copies the whole thing but also wraps it in double quotes, i have to use cmd+x (cut) to get around it. is there a way to disable this?

**To Reproduce**

1. query anything
2. select a part of text inside a text/varchar field
3. hit cmd+c
4. it will copy the whole thing and wrap it in double quotes

**Expected behavior**

There shouldn't be any double quotes and it should only copy selected text

**Desktop (please complete the following information):**
 - OS: OSX sequotia
 - Version: 15.1.1
 - Mode: Desktop
 - Browser chrome
 - Package type: Brew

**Comment by adityatoshniwal** [comment]
Duplicates #8157.
