### ISSUE TITLE
The pgAdmin 4 server could not be contacted:

### ISSUE THREAD

**Issue by wcool1** [pgadmin-org/pgadmin4#8234]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**
The pgAdmin 4 server could not be contacted:

**Describe the bug**
Today i download and install the postgresql 16 from https://www.postgresql.org/download then restart my windows ;
when i open the  pgAdmin 4 ,run for a while then happen as the following .
I tried many ways from youtube、issues、google and so on but not work including :

**Check PostgreSQL Service Status**

**Confirm that the PostgreSQL service is running:**
1. In Windows, press `Win + R`, type `services.msc`, and then press Enter.
2. In the list of services, find the PostgreSQL service and ensure its status is "Running." If it is not running, right-click on the service and select "Start" or "Restart."

**Restart pgAdmin and the computer:**
1. **Restart pgAdmin:**
   - Open Task Manager (`Ctrl + Shift + Esc`), find all pgAdmin processes, right-click, and select "End Task."
   - Then restart pgAdmin.
   
2. **Restart the computer:**
   - Sometimes, restarting the computer can resolve temporary connection issues.

**Clear old session data:**
1. **Clear pgAdmin session data:**
   - Press `Win + R`, type `%appdata%`, and press Enter.
   - Find the `pgadmin4` folder, enter the `session` folder, and delete all contents within.
   - If the problem persists, consider deleting the entire `pgadmin4` folder and then restarting pgAdmin.

**Check network and firewall settings:**
1. **Check network connection:**
   - Ensure your computer can access the IP address and port (default is 5432) of the PostgreSQL server.

2. **Firewall settings:**
   - Check Windows Firewall or any other security software to ensure they are not blocking communication for pgAdmin or PostgreSQL.

**Configure pgAdmin:**
1. **Configure pgAdmin:**
   - Ensure that the database connection information in pgAdmin settings is correctly configured, including hostname, port, username, and password.

**View log files:**
1. **View log files:**
   - Check pgAdmin's log files for more error information. The log file is usually located at `%appdata%\pgadmin4\pgadmin4.log`.

**Reinstall pgAdmin:**
1. **Reinstall pgAdmin:**
   - If none of the above steps resolve the issue, consider uninstalling and reinstalling pgAdmin.

The bug:
The pgAdmin 4 server could not be contacted:
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "D:\all kinds of tools\pgsql\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\86131\AppData\Roaming\pgadmin4\config.json"
Webapp Path: "D:\all kinds of tools\pgsql\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "D:\all kinds of tools\pgsql\pgAdmin 4\python\python.exe -s D:\all kinds of tools\pgsql\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\86131\AppData\Roaming
  - Classpath: E:\softwares\lingo\Lingo18.jar
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - ComSpec: C:\Windows\system32\cmd.exe
  - CURL_CA_BUNDLE: D:\all kinds of tools\pgsql\ssl\certs\ca-bundle.crt
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - ELECTRON_ENABLE_SECURITY_WARNINGS: false
  - EMULATOR_AVD_ROOT: D:\Program Files\MobileAppEngine\emui
  - EMULATOR_SDK_ROOT: C:\Program Files\MobileAppEngine\EmulatorSdk
  - FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
  - FPS_BROWSER_USER_PROFILE_STRING: Default
  - GDAL_DATA: D:\all kinds of tools\pgsql\gdal-data
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\86131
  - https_proxy: http://127.0.0.1:7897
  - http_proxy: http://127.0.0.1:7897
  - IntelliJ IDEA: D:\java\IntelliJ IDEA 2023.2.4\bin;
  - LINGO64_18_HOME: E:\softwares\lingo\
  - LOCALAPPDATA: C:\Users\86131\AppData\Local
  - NODE_PATH: E:\nodejs\node_global\node_modules
  - NUMBER_OF_PROCESSORS: 16
  - NVM_HOME: D:\all kinds of tools\nodenvm\nvm
  - NVM_SYMLINK: D:\Program Files\nodejs
  - OneDrive: C:\Users\86131\OneDrive
  - OneDriveConsumer: C:\Users\86131\OneDrive
  - ORIGINAL_XDG_CURRENT_DESKTOP: undefined
  - OS: Windows_NT
Total spawn time to start the pgAdmin4 server: 0.006 Sec
NOTE: Configuring authentication for DESKTOP mode.
pgAdmin 4 - Application Initialisation

======================================

2024-12-04 22:43:59,125: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

I can not open the pgAdmin 4  or psql 
**To Reproduce**
just install and open it

**Expected behavior**
anybody tell me why happen this ,how can i open it correctly?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11,
 - Version: [ 6.15]
 - Mode: [Desktop ]

**Comment by georgejvarghese** [comment]
Can someone please explain how this proxy setting issue is resolved ?

**Comment by yogeshmahajan-1903** [comment]
@georgejvarghese 
Can you please set no_proxy variable to 127.0.0.1 to fix the issue.

**Comment by yogeshmahajan-1903** [comment]
Duplicate of #7901
