### ISSUE TITLE
Copy-paste functionality for Data Output not working as expected for partial highlight

### ISSUE THREAD

**Issue by gabrielwol** [pgadmin-org/pgadmin4#8236]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

After double clicking on a cell in Data Output tab and copying just a portion of the text, the entire contents is copied instead. 

**To Reproduce**

1. Open query editor
2. Run `SELECT 'Hello world'::text`
3. Double click on the cell in the results grid, highlight `Hello` and press ctrl-c. 
4. Pasting results gives: `"Hello world"`

**Expected behavior**

Expected paste would be `Hello`. 

**Error message**

**Screenshots**

![image](https://github.com/user-attachments/assets/e8552329-9f62-435c-a035-5f6764f0b3dc)

Paste results: 
![image](https://github.com/user-attachments/assets/a4bbc124-b9eb-49ec-a376-075899a7c0b2)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise
 - Version: PgAdmin 8.13
 - Mode: Desktop
 
**Additional context**

**Comment by anilsahoo20** [comment]
Duplicate of #8150.
