### ISSUE TITLE
Longer loading state if localhost is specified instead of 127.0.0.1 in host name server connection

### ISSUE THREAD

**Issue by timowenz** [pgadmin-org/pgadmin4#8244]
**Describe the bug**

If you specify `localhost` in property on `Host name/address` you will get much longer responses in querying than `127.0.0.1`. 

**To Reproduce**

1. Enter `Host name/address` = `localhost`
2. Query any SQL statement and you will have much longer connection times
3. Change `Host name/address` = `127.0.0.1`
4. Query any SQL statement and you will have much shorter connection times

**Expected behavior**

Connection time should be the same, but the speed is significantly slower with `localhost`

**Error message**

No error messages.

**Screenshots**

![grafik](https://github.com/user-attachments/assets/adf8d6ab-7ee5-403c-bf27-bfcf4917e1ee)
Here specify either `localhost` (slower) or `127.0.0.1` (faster).

**Desktop (please complete the following information):**
- OS: Windows 11
- Mode Desktop
- Running `postgres:alpine` in Podman container (WSL 2)

**Additional context**

The querying takes longer to build the connection up but `pgAdmin 4` shows the querying time as normal and it works as supposed to be just slower.

**Comment by pravesh-sharma** [comment]
This is not a pgAdmin issue. It is related to your DNS resolution setup.
