### ISSUE TITLE
Pass "connection properties" to the "Password exec command" 

### ISSUE THREAD

**Issue by crimean-celica** [pgadmin-org/pgadmin4#8252]
It would be useful to be able to pass "connection properties" to the "Password exec command." 
This would allow the same command to be used for all registered servers. 
It can be done, say, using PHHOST, PHPORT, PGUSER, etc. env. variables.

**Comment by adityatoshniwal** [comment]
Duplicates [#6794](https://github.com/pgadmin-org/pgadmin4/issues/6794)
