### ISSUE TITLE
Support search database under Databases node

### ISSUE THREAD

**Issue by WaelDaoud** [pgadmin-org/pgadmin4#8259]
Add a "search database" Under "Databases" node

If the PostgreSQL server conations several databases with "unreadable" or "hard to read" format name; a "Search Database" will help quickly locate the database object and highlighted the database node.

                  |  +----------------+ |
                  |  |     Databases       | |
                  |  +----------------+ |
                           +-------------------------+
                            |       Search Database       |
                           +-------------------------+
                            |     Database Name:          |
                            | +---------------------+  |
                            |  |                                      |  |
                            |  +---------------------+ |
                            |                                           |
                            | +---------------------+  |
                            |  |             [Submit]          |   |
                            |  +---------------------+  |
                            +-------------------------+
   
                       

On the other hand, the current method to locate database by visually searching for each database.

**Comment by pravesh-sharma** [comment]
Duplicates #1714
