### ISSUE TITLE
Unable to create one to one relationship among tables

### ISSUE THREAD

**Issue by akumarbit** [pgadmin-org/pgadmin4#8261]
Currently in PGADMIN ERD diagram tool we can't create one to one relationship between tables. One to many and many to amny relationship options are present but one to one relationship is missing.

One to oen relationship is also very commonly used functinality and most of the projects need such functionality. It would be fraete to add the one to one option as well.

**Comment by adityatoshniwal** [comment]
Duplicates #5128
