### ISSUE TITLE
pgAdmin не изменяет размер окна программы

### ISSUE THREAD

**Issue by Akvilona** [pgadmin-org/pgadmin4#8262]
I'll explain the situation first. I work on, and work on, a Windows 10 laptop and connect different monitors to the laptop. At work, I have a small Dell E23 16H monitor, and at home I have a wide 21:9 Samsung S34C500GAU monitor, and due to the fact that I constantly switch between monitors via an HDML cable, the pgAdmin program disappears from view every time. That is, you click on the open pgAdmin icon and the program flies off the screen, and in order to open it somehow, you have to resize the screen so that in some way pgAdmin notices that the screen sizes have changed and you need not go beyond these limits. It's terribly inconvenient.  Please correct this error.

**Comment by pravesh-sharma** [comment]
Duplicates #8263.
